### ISSUE TITLE
Unclear how to build qubesdb without systemd

### ISSUE THREAD

**Issue by 2d1** [QubesOS/qubes-issues#1004]
t's not immediately evident in qubesdb how to build it for sysvinit.

**Edit:**
I've discovered how to cleanse qubesdb of systemd by removing systemd includes, following the resulting errors,  and then finding the comments in db-daemon.c. I'm sorry for asking so prematurely. Usually I work on a problem for much longer before asking for help. I was just so worried from the sysv/systemd targets not being in the Makefile.

That said, it would be nice if users were instructed in the Makefile how to build without systemd. That might save others from the same systemd despair. =P

Background:
I've been working on and off for a few months at porting the Qubes userland to Gentoo (https://github.com/2d1/qubes-overlay) and writing a decent MAC policy for appvms (https://github.com/2d1/qubes-policy )*

I noticed that R2 development was dead so I thought in order for my work to remain meaningful I must upgrade to R3. I've done that, and qrexec appears to be working.

But qubes-gui now depends on qubesdb, and I can't find a way to install for sysvinit (so that I can convert it as I had before for qubes-core and qubes-gui to openrc). Unconditional dependence on systemd wasn't in any announcement I managed to find, so I assume I'm doing something wrong/missing something.

I'd appreciate help in getting qubes-gui built (without touching that disgusting cesspit that is systemd)

\* I realise that Xen bugs are only hypothetical (source: /etc/sudoers.d/qubes) and by implication compromise of any one domain isn't important, but defence in depth feels good, y'know?

**Comment by marmarek** [comment]
Currently all of supported templates uses systemd in practice, but it
isn't hard requirement. Regarding qubesdb, it's just a single command
(`/usr/sbin/qubesdb-daemon 0`), so you can prepare openrc config based
on that. Currently there is no sysvinit script (with this single
command) in the repository, but feel free to provide one if you like.
Note that qubesdb needs to be started before all the init scripts from
core-agent-linux.

Let me know if you need anything else, it would be great to have gentoo
running in Qubes VM :)

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 2d1** [comment]
@marmarek I gathered the '0' bit from inspecting the systemd script. I still can't get it to work though.

Symptoms:
* With start-stop-daemon it double forks without --background and waits forever with --background
* Depending on it makes the boot wait indefinitely
* Several instances of qrexec-agent are spawned
* It makes a '(null)' log despite being passed '0'
* It does however create qubesdb.sock
* There's a missing pipe, per qrexec-agent's log: 'connect: No such file or directory'
* Xorg log contains 'fnctl(5, I_SETSIG, 0): Bad file descriptor'

Could you verify that commenting out 'if (getenv("NOTIF... } else {' (3 lines) and the associated brace was the correct change, please. I guess that being a mistake is the most likely culprit.

**Comment by marmarek** [comment]
On Fri, May 22, 2015 at 04:41:40PM -0700, 2d1 wrote:
> @marmarek I gathered the '0' bit from inspecting the systemd script. I still can't get it to work though.
> 
> Symptoms:
> * With start-stop-daemon it double forks without --background and waits forever with --background

Does start-stop-daemon set NOTIFY_SOCKET variable? If yes, qubesdb
thinks it is started under systemd (and tries to use it to notify about
successful startup)...
In this case I need to add some more robust mechanism to detect systemd
presence. Or just command line parameter?

> * Depending on it makes the boot wait indefinitely
> * Several instances of qrexec-agent are spawned

I think this is unrelated.

> * It makes a '(null)' log despite being passed '0'

This is unrelated bug.

BTW do you need pid file to be created by qubesdb? Currently it isn't
created in VM, but is it one line change to have it there.

> * It does however create qubesdb.sock
> * There's a missing pipe, per qrexec-agent's log: 'connect: No such file or directory'

You can probably ignore this - qrexec-agent tries to connect to
qrexec-fork-server (started by qubes-session script under X session),
and fallback to creating new session (by calling "su"). 

> * Xorg log contains 'fnctl(5, I_SETSIG, 0): Bad file descriptor'

I have no idea.

> Could you verify that commenting out 'if (getenv("NOTIF... } else {' (3 lines) and the associated brace was the correct change, please. I guess that being a mistake is the most likely culprit.

This can be a workaround, but I'd like to fix it properly.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
On Sat, May 23, 2015 at 02:06:24AM +0200, Marek Marczykowski-Górecki wrote:
> On Fri, May 22, 2015 at 04:41:40PM -0700, 2d1 wrote:
> > @marmarek I gathered the '0' bit from inspecting the systemd script. I still can't get it to work though.
> > 
> > Symptoms:
> > * With start-stop-daemon it double forks without --background and waits forever with --background
> 
> Does start-stop-daemon set NOTIFY_SOCKET variable? If yes, qubesdb
> thinks it is started under systemd (and tries to use it to notify about
> successful startup)...
> In this case I need to add some more robust mechanism to detect systemd
> presence. Or just command line parameter?

The intended behaviour is that it forks, the child process initiate
connection to dom0 and synchronize the data, then notify the parent
process which _then_ terminates itself. This is to prevent races when
subsequent services tries to communicate with qubesdb, which it is still
initializing.
So you should not use --background. Check the log file, maybe there is
some problem with connecting to dom0? 

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Take a look here:
https://github.com/marmarek/qubes-core-qubesdb/tree/no-systemd
I've added trivial option to not link with systemd. You can pass
`SYSTEMD=0` on make command line.
I haven't tested it though... If that works for you, I'll push it to
master branch.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 2d1** [comment]
>BTW do you need pid file to be created by qubesdb? Currently it isn't created in VM, but is it one line change to have it there.

I'd rather that be left to openrc. The reason a bit complicated. First, grsec's rbac* has a few nice subject modes including hide /proc from other process and another to override that restriction. It's possible to have start-stop-daemon *not* have the latter and still stop/signal daemons via a pid file. So start-stop-daemon can start and stop the daemon, pass the stderr fd to a logfile, and not otherwise interfere with it ;) That gets even better combined with selinux since you can write a separate domain for each init file (which is really ugly with nested grsec policy), and make sure that the domain/subject transition vector is exactly as prescribed. openrc init scripts are usually just start-stop-daemon, so it's really easy to read (and therefore audit). So daemons can only be started and stopped via an easily audited start-stop-daemon line. Compare that to systemd ;)

>Does start-stop-daemon set NOTIFY_SOCKET variable? If yes, qubesdb thinks it is started under systemd (and tries to use it to notify about successful startup)...

Honestly I don't know. I've never had problems  with start-stop-daemon and so have never had to learn anything about it. Which is very lazy, I know.

> So you should not use --background. Check the log file, maybe there is some problem with connecting to dom0?

Unfortunately, qubesdb's log remains empty (with start-stop-daemon [no --background] or /usr/sbin/qubesdb-daemon 0 &). Given that plain /usr/sbin/qubesdb-daemon 0 & has the same behavior along with the previous quote, I'd guess that openrc sets NOTIFY_SOCKET.

> I haven't tested it though... If that works for you, I'll push it to master branch.
I'll try that, thanks.

---
\* Note that I'm testing without rbac at the moment, of course.

**Comment by 2d1** [comment]
>> I haven't tested it though... If that works for you, I'll push it to master branch.
> I'll try that, thanks.

@marmarek It compiles for me. qubesdb still hangs in a double-forked state though (no log output). :(

**Comment by marmarek** [comment]
Do you have qubesdb-daemon in dom0 running for this VM (there should be
VM name in arguments)? Or maybe you have started it twice at the same
time? What do you mean by "double-forked state"? There is only one fork
in the source code...

You can also try to attach strace to this hanging process or even start
through "strace -f" and check for what is it waiting.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 2d1** [comment]
>Do you have qubesdb-daemon in dom0 running for this VM (there should be VM name in arguments)?
grep /usr/sbin/qubesdb-daemon.*(vm name) /proc/*cmdline gives around 30 results, some and appears to change over time (some are destroyed and more are created).

**Comment by marmarek** [comment]
On Fri, May 22, 2015 at 08:23:47PM -0700, 2d1 wrote:
> >Do you have qubesdb-daemon in dom0 running for this VM (there should be VM name in arguments)?
> grep /usr/sbin/qubesdb-daemon.*(vm name) /proc/*cmdline gives around 30 results, some and appears to change over time (some are destroyed and more are created).

There should be only one qubesdb-daemon per-VM in dom0. I guess some of
them are leftovers from some failed VM startups. Verify with
`ps aux |grep qubesdb-daemon.*(vm name)`. Then kill all but newest (or
if your VM isn't running, simply all of them).  Be careful to not
kill any of qubesdb for other VMs.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 2d1** [comment]
>Then kill all but newest (or if your VM isn't running, simply all of them). Be careful to not kill any of qubesdb for other VMs.

Done. strace of qubesdb-daemon after killing all dom0 instances: https://gist.github.com/2d1/e6ef3da4b659010b7720

**Comment by marmarek** [comment]
This is only the parent process - waiting for child to finish
initialization. Use `strace -f` to get also child trace (where probably
something went wrong).
I assume you've killed all dom0 instances, then started the VM (which
should start new, fresh qubesdb in dom0), right?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 2d1** [comment]
>This is only the parent process - waiting for child to finish initialization. Use `strace -f` to get also child trace (where probably something went wrong).

Sorry, here's strace -f: https://gist.github.com/anonymous/f2c22fbb9232e4287b0b

>I assume you've killed all dom0 instances, then started the VM (which should start new, fresh qubesdb in dom0), right?

That's correct.

**Comment by marmarek** [comment]
Ok, now its clear what is happening. There is a kernel bug[1] in legacy
xenstore interface (/proc/xen/xenbus), which causes a deadlock. There was
discussion about possible fixes, but it turned out to be broken by
design (/proc/xen/xenbus is a "normal file", but behaves as character
device). The new interface (/dev/xen/xenbus) does not have this problem,
and we have a patch[2] on xenstore lib to use the later one by default.

So probably you are are using vanilla xen libs, without this patch. I
have also a patch for the kernel problem (which in the end wasn't
included in upstream kernel), so if you really don't like patching xen
libs, I can provide patched kernel.

BTW I see your overlay uses 'xen-4.1' branch for vmm-xen package. The
correct branch for R3 is 'xen-4.4'. I've just changed the default to
match this.

[1]
http://lists.xenproject.org/archives/html/xen-devel/2015-03/msg02285.html
[2]
https://github.com/QubesOS/qubes-vmm-xen/commit/e63bfff856128e5c8fdb7fa51d6ce9a824014090

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 2d1** [comment]
> Ok, now its clear what is happening. There is a kernel bug[1] in legacy xenstore interface (/proc/xen/xenbus), which causes a deadlock. There was discussion about possible fixes, but it turned out to be broken by design (/proc/xen/xenbus is a "normal file", but behaves as character device). The new interface (/dev/xen/xenbus) does not have this problem, and we have a patch[2] on xenstore lib to use the later one by default.

The patch works, thanks.

> So probably you are are using vanilla xen libs, without this patch. I have also a patch for the kernel problem (which in the end wasn't included in upstream kernel), so if you really don't like patching xen libs, I can provide patched kernel.

That's correct. In Gentoo the Xen userland stuff is provided by app-emulation/xen-tools (which the overlay depends on). There's no need for a patched kernel, since it's easy to patch things via epatch_user, which applies anything in /etc/portage/patches/$category/$packagename.  Users can be directed to do so for xen-utils via post-install warnings in the vchan ebuild.

qubesdb-daemon now successfully forks and kills the parent, and I can read things by manually calling qubesdb-read.

*However* qubes-gui doesn't work. =/ I think it's something to do with eventchan, since it opens fds named data/vchan/[\d/]+/event-channel and then attempts to close them, for which the status code is 'EBADF'. qubes-gui dies and X lives on.

It also tries to open /run/xenstored/socket, which doesn't exist, which I guess is expected given that xenstored won't run in an unprivileged domain (perhaps checking whether it's in dom0)?

I suppose I should try your version of vmm-xen. I'd very much like to get the qubes userland into portage, and gentoo devs have a strong preference toward having vanilla everything/upstreamed patches where possible. But maybe walking before running is more important. =P

**Comment by marmarek** [comment]
> *However* qubes-gui doesn't work. =/ I think it's something to do with
> eventchan, since it opens fds named data/vchan/[\d/]+/event-channel

What do you mean? `data/vchan/...` is xenstore path, not something you
can open. Additionally such path is handled only inside libvchan - and
while qubesdb starts and you can get the data, it means that libvchan is
working.

> and then attempts to close them, for which the status code is 'EBADF'.
> qubes-gui dies and X lives on.

Anything on stderr there?

> It also tries to open /run/xenstored/socket, which doesn't exist, which I guess is expected given that xenstored won't run in an unprivileged domain (perhaps checking whether it's in dom0)?

Yes, this is default behaviour of xenstore client library.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 2d1** [comment]
> What do you mean? `data/vchan/...` is xenstore path, not something you can open. Additionally such path is handled only inside libvchan - and while qubesdb starts and you can get the data, it means that libvchan is working.

Sorry, I misread strace's output. Different processes => different numbers.

> Anything on stderr there?

Yes, there's this:

> Waiting on /var/run/xf86-qubes-socket socket...
> Ok, somebody connected.
> XIO: fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
> after 37 requests (36 known processed) with 0 events remaining.

Would a full trace of gui-agent be helpful?

**Comment by marmarek** [comment]
> > Waiting on /var/run/xf86-qubes-socket socket...
> > Ok, somebody connected.
> > XIO: fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
> > after 37 requests (36 known processed) with 0 events remaining.
> 
> Would a full trace of gui-agent be helpful?

This suggests rather X server crash, check /var/log/Xorg.0.log.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 2d1** [comment]
>This suggests rather X server crash, check /var/log/Xorg.0.log.

You're right, for whatever reason, X remaining alive seems to have been a one-off.
Log: https://gist.github.com/anonymous/6ae68a735c350ee8df29

**Comment by marmarek** [comment]
Ok, this looks like clean X shutdown. So most likely qubes-session is
not started properly. Take a look at
https://github.com/QubesOS/qubes-gui-agent-linux/blob/master/appvm-scripts/usrbin/qubes-run-xorg.sh
It calls xinit, which there should start X server (this is ok), and then
call some distro-specific script to setup user environment, then it
should call /usr/bin/qubes-session - which should stay alive for the
whole VM lifetime (when it terminates, xinit will terminate Xorg).
Take a look at .xsession-errors in user homedir.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 2d1** [comment]
>Ok, this looks like clean X shutdown. So most likely qubes-session is not started properly

Correct. qubes-session wasn't reaching sleep, presumably from not having loginctl or some X utilities installed. Removing everything but the sleep line made it work.

Regardless, the original problem is solved, so this can be closed.

Thanks again.
