### ISSUE TITLE
Unable to find/install templates from qubes-templates-itl

### ISSUE THREAD

**Issue by 2d1** [QubesOS/qubes-issues#1017]
>No package qubes-template-debian-8 available.
>No package qubes-template-fedora-21 available.

Templates from qubes-templates-community are found:

>Package qubes-template-whonix-ws-gnome.noarch 0:3.0.2-201505170226 will be installed

This is on an install updated to r3 from r2. I assume that r3 templates should be installable without any steps not in https://www.qubes-os.org/doc/UpgradeToR3.0rc1/ .

**Comment by marmarek** [comment]
All but `qubes-template-fedora-21` should be working now. There was a
bug in `qubes-dom0-update` tool which results in upgrade of already
installed template package. This would override all the user changes to
the template. The bug is fixed in `qubes-core-dom0-3.0.6`, but to
prevent unintentional template package upgrades (until fixed package
spreads over the qubes installations), we've removed template package
from repository metadata.

In the meantime it is still possible to download template rpm from
sf.net manually (and also manually verify its signature), but it is
somehow less convenient...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 2d1** [comment]
> All but `qubes-template-fedora-21` should be working now. There was a bug in `qubes-dom0-update` tool which results in upgrade of already installed template package.

debian is, thanks. (though fedora-21-minimal wasn't when I checked)

>In the meantime it is still possible to download template rpm from sf.net manually (and also manually verify its signature)

If you like living dangerously ;)
