### ISSUE TITLE
KDE: Double clicking on an "open" file (in the background) appears to do nothing

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1042]
I'm not sure if this relates to Qubes or if this is a KDE issue, but the scenario is:
- I have the file MyFile.txt open already by gedit, it's just in the background
- In foreground I have File Manager open
- Upon double clicking on the MyFile.txt nothing appears to happen

The correct behaviour should be to bring the already open file into the foreground, otherwise it is quite confusing and user may think the file is corrupt or cannot be opened.

**Comment by marmarek** [comment]
This is probably result of our GUI virtualization solution, which
(intentionally) passes only little subset of events/metadata to dom0.
For example I don't think VM is able to bring arbitrary window to front.
This needs some more though to prevent attacks like focus stealing...

Currently the only similar feature implemented is "demand attention"
flag. But I'm not sure how is that related to bringing existing editor
window to the front.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
Closing this for now due to the prolonged lack of activity. If you believe this is a mistake, or if anyone would like this issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by unman** [comment]
On Sat, May 08, 2021 at 12:52:56AM -0700, Andrew David Wong wrote:
> Closed #1042.
> 

It's still an unresolved issue in 4.0, and (afaik) in 4.1 - are we
closing just because of age?

**Comment by andrewdavidwong** [comment]
> On Sat, May 08, 2021 at 12:52:56AM -0700, Andrew David Wong wrote:
> > Closed #1042.
> > 
> 
> It's still an unresolved issue in 4.0, and (afaik) in 4.1 - are we
> closing just because of age?
> 

I didn't know it affected 4.0 because no one ever said it did. Reopened.
