### ISSUE TITLE
Windows logon screen is sometimes shown as override-redirect window

### ISSUE THREAD

**Issue by omeg** [QubesOS/qubes-issues#1044]
This is a long-standing bug that can be annoying if one is not using autologon in Windows. Sometimes the logon screen has override-redirect flags applied which causes it to:
1) not accept normal keyboard input (use the on-screen keyboard from the accessibility menu in the lower left)
2) be on top of all other windows, and the logon window is the size of the dom0 screen (VM has the same video resolution in seamless mode).

**Comment by unman** [comment]
@andrewdavidwong Haven't been able to test this - please change milestone to 3.2

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
