### ISSUE TITLE
Improve Windows gui agent performance

### ISSUE THREAD

**Issue by omeg** [QubesOS/qubes-issues#1045]
Windows VMs are definitely less responsive than Linux ones, especially in fullscreen mode. If I remember correctly from profiling sessions done in Qubes R2, input simulation API calls took a fair chunk of CPU time (mouse movement etc). AttachInputDesktop is also called too frequently.

**Comment by andrewdavidwong** [comment]
@omeg: For tracking purposes, what is the current status of this issue?

**Comment by omeg** [comment]
It's currently on hold while I work on the new GUI agent/driver for Windows 8+.

**Comment by unman** [comment]
@andrewdavidwong I Have not been able to test this - please change milestone to 3.2 updates

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
