### ISSUE TITLE
Windows: support restarting qrexec-agent in case of failure

### ISSUE THREAD

**Issue by omeg** [QubesOS/qubes-issues#1047]
Currently if the qrexec-agent service encounters critical errors (mostly qrexec-daemon vchan failure) it exits and is not restarted. This prevents future communication with the VM as qrexec-agent is the vchan server.

**Comment by unman** [comment]
@andrewdavidwong I Have not been able to test this - please change milestone to 3.2 updates

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
