### ISSUE TITLE
Improve usability of VM disk space / increasing disk size

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1053]
Upon using Qubes and downloading a large files, I have encountered 

**VM Settings**
Improve error msg on failure to resize (while VM is running). Currently the dialogue says `ERROR: Basic tab: resize2fs failed` 

The "new" resize value inputed by user sticks in "Private storage max. size" field even after the failure mentioned above. The VM then appears to complete the resize after being restarted. Additionally, the input field is non-editable (until restarting the VM) after the failed attempt. While the net result here is that the VM is eventually resized, this feels a bit odd as a user because I feel conditioned that "when something fails" I have to perform the action again later. So either do
1. Make the above warning message `Warning, the AppVM is currently running, the resize will complete the next time you shutdown and restart it`
2. Something like `Resizing failed because AppVM is running. Please shutdown the VM then try again` at which point reset the input to current value and make it editable.

**VM Notification Warning**

When using a VM and the disk space is running out, an OS warning message pops up alerting the user of lack of disk space. I believe clicking on the message opens a disk manager program. However, due to Qubes VM design, this program is not the most intuitive / helpful tool, as increasing the disk space happens in the `Qubes VM Manager` thus I propose one of:
1. Add button / link to `Increase Disk Space` that takes user to Qubes VM Manager and ideally opens the VM Settings for that given VM
2. Add a menu that has two buttons, one being `Increase Disk Space of VM` and `Analyze Disk Usage of VM` whereby the former load the VM settings and the later shows the current disk space tool

**Comment by marmarek** [comment]
On Tue, Jul 07, 2015 at 03:50:06AM -0700, Brennan Novak wrote:
> Upon using Qubes and downloading a large files, I have encountered 
> 
> **VM Settings**
> Improve error msg on failure to resize (while VM is running). Currently the dialogue says `ERROR: Basic tab: resize2fs failed` 
> 
> The "new" resize value inputed by user sticks in "Private storage max. size" field even after the failure mentioned above. The VM then appears to complete the resize after being restarted. Additionally, the input field is non-editable (until restarting the VM) after the failed attempt. While the net result here is that the VM is eventually resized, this feels a bit odd as a user because I feel conditioned that "when something fails" I have to perform the action again later. So either do
> 

This is already fixed (package in current-testing) - the error reporting
was wrong - VM disk was actually resized.

> **VM Notification Warning**
> 
> When using a VM and the disk space is running out, an OS warning message pops up alerting the user of lack of disk space. I believe clicking on the message opens a disk manager program. However, due to Qubes VM design, this program is not the most intuitive / helpful tool, as increasing the disk space happens in the `Qubes VM Manager` thus I propose one of:
> 
> 1. Add button / link to `Increase Disk Space` that takes user to Qubes VM Manager and ideally opens the VM Settings for that given VM
> 2. Add a menu that has two buttons, one being `Increase Disk Space of VM` and `Analyze Disk Usage of VM` whereby the former load the VM settings and the later shows the current disk space tool

Currently VM have no idea that it is even possible to increase its disk
space. Adding such option to _that_ notification would mean forking that
disk monitoring tool, which surely we don't want to do. But I see your
point. Maybe some simpler solution would be enough, something like
update notification:
1. VM have ability to report "low disk space" even to dom0 (some qrexec
service)
2. Qubes Manager displays an icon next to the VM
3. User can click on that icon and select whether he/she want to
increase private disk size (go to VM settings), or run some disk
cleaning tool inside of VM (run some qrexec service, which will start
the right tool, depending on VM distribution).

Also dom0 disk space should be considered. Running out of physical disk
space in Qubes can be somehow hard to recover from.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by deeplow** [comment]
It seems this issue is highly related: https://github.com/QubesOS/qubes-issues/issues/1441
