### ISSUE TITLE
Debian Template: cannot add KDE Konsole to dom0 app menu

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1062]
Under "add more shortcuts", KDE konsole (https://packages.debian.org/jessie/konsole) is not offered for being added. Neither the term "Konsole" nor "terminal" is in that list.

Starting 'konsole' from 'Run command in VM' however is functional.

**Comment by marmarek** [comment]
It is available as "Open a New Window"...
This is because konsole.desktop defines additional actions and this one
is the last one, so its name is used. Our desktop file parser have
support for that using simple awk script, but apparently Debian mawk
does not support "nextfile" function, so additional actions are not
skipped. This is apparently GNU AWK extension.
Can we require gawk to be installed? It would be possible to have the
script compatible with mawk, but it will be much more complex.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Ok, maybe not "much more complex". We can simply process one file at a
time... This of course means somehow worse performance (multiple calls
to awk instead of just one), but probably negligible.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
Keep it simple.

gawk - ~ 2 MB. I don't see an issue with that.

If we focus on usability, not most small images to make geeks happy,
then that's totally acceptable.
