### ISSUE TITLE
Debian Template: passive popups sometimes not closeable

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1076]
Start a debian-8 based AppVM. Test command (requires having the `libnotify-bin` package installed):

```
notify-send test
```

This is also security issue. Something wrong within the VM can spam dom0 with loads of uncloseable windows.

More discussion and ideas what could be causing this:
https://groups.google.com/d/msg/qubes-users/PtnwWxqQdHA/UwiNkLe5YJUJ

**Comment by marmarek** [comment]
On Tue, Jul 21, 2015 at 01:10:16PM -0700, Patrick Schleizer wrote:
> Start a debian-8 based AppVM. Test command (requires having the `libnotify-bin` package installed):
> 
> ```
> notify-send test
> ```
> 
> This is also security issue. Something wrong within the VM can spam dom0 with loads of uncloseable windows.
> 
> More discussion and ideas what could be causing this:
> https://groups.google.com/d/msg/qubes-users/PtnwWxqQdHA/UwiNkLe5YJUJ
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/QubesOS/qubes-issues/issues/1076

Regarding security aspect - this isn't related to notify-send (or
notify-osd package in this case), but more generally to windows with
override-redirect flag set. Those windows are not managed by dom0 WM, so
can't be moved, forcibly closed etc. Similar issue is described in
#1044.
We need some generic solution for that (like keyboard shortcut to close
misbehaving window/VM).

Regarding popups problem, I'll respond on mailing list.


-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Notification daemon in Debian changed to `mate-notification-daemon`.
