### ISSUE TITLE
Make configuring DisposableVM's easier to find in GUI

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1079]
I was trying to figure out how to customize my "disposable VM" and I was aware of the "Show / hide inactive VMs" in the VM Manager and tried that at first. I had no idea of the "Show / hide internal VMs" option as well. I had to review the documentation to come learn about it. 

I think these two "Show/hide" view filters should be collapsed into one, and then the button in the VM Manager would make the internal VMs show up as well in the list.

**Comment by adrelanos** [comment]
Brennan Novak:
> I think these two "Show/hone" view filters should be collapsed into one, and then the button in the VM Manager would make the internal VMs show up as well in the list.

Yes.

What do you think about showing inactive VMs by default? I found it
confusing at first, that my newly installed template did not show up there.

**Comment by marmarek** [comment]
I think what you suggest is just showing "internal" VMs by default.
Those VMs will be hidden if not running anyway (unless you enable "show
inactive VMs", which is much easier to find).

The idea of "internal" VMs was to prevent accidental starting non-user
VMs (like DispVM template). Because of that such VMs are not listed in
application menu. Some users use this feature to hide also templates, to
have clearer qubes manager list. By default templates are not treated as
"internal".

This step is already covered in documentation:
https://www.qubes-os.org/doc/UserDoc/DispVMCustomization/
Do you find it unclear or hard to find? User still needs that
documentation to learn about `~/.qubes-dispvm-customized` file...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by unman** [comment]
I think the current position is fine. It's documented and not difficult to understand.
There is a huge difference between showing internal and inactive VMs.
If we move to more than one dispVM template it would clutter and confuse the interface. I'm in favour of the status quo.

**Comment by bnvk** [comment]
> I think what you suggest is just showing "internal" VMs by default.

@marmarek no, something different / the opposite is what I am thinking. Keeping both DisposableVMs and TemplateVMs hidden by default, but merging them into the same "show / hide" button. Then perhaps delineating the differences in the VM Manager UI and startmenu as well. I'll make wirfeframes of this as well as other UI / UX improvements to propose a little further down the lines, especially once we figure out the Gnome / KDE issue.

> I think the current position is fine. It's documented and not difficult to understand.

@unman as an above average technical user (who codes well as designs ;) who has read the entire Qubes user documentation- the fact that I had to re-read parts of the documentation to figure this out signal to my "UX" brain, that this is too hidden / confusing of a separation. The user experiences I strive for do not require users to read docs, but rather make things easy enough to figure out from the interface itself :-)

**Comment by marmarek** [comment]
I don't quite follow... Currently we have:
1. show/hide inactive (not running) VMs - accessible from toolbar as well
   as from menu; this affects only what VMs are listed in Qubes Manager;
   hide by default
2. show/hide internal VMs - accessible only the from menu; the option
   only change visibility in Qubes Manager, doesn't affect "internal" flag
   on any VM; hide by default

Internal VM is a VM with "internal" flag set (can be freely changed by the
user in VM settings). By default it is set only for *-dvm (DispVM
"template"). Internal VMs are not listed in application menu, regardless
of show/hide setting in Qubes Manager.

What do you propose here?
1. Changing for which VMs "internal" flag is set by defaulf?
2. Changing default state of show/hide setting(s)?
3. Changing what is affected by "internal" flag (for example listing in
application menu)?
4. Adding show/hide internal VMs button to Qubes Manager toolbar?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by unman** [comment]
I think the proposal is that there should be ONE button - it will toggle show/hide for both inactive AND internal VMs.
I cant agree that this would improve the UX - there is a clear distinction between inactive and internal, and the present arrangement honours that. (It's not as if the option to show internal VMs is hidden - it's there under the View menu.) If you must, add a separate button.
Most ordinary users wont, I think, need to show internal VMs at all, so that button will be redundant. IMO it's useful to be able to remove templates from the UI by setting them internal - although this does have the unexpected consequence for GUI users that they are no longer available in the drop down when provisioning a VM. (Is this a bug?)
Anyone who wants to customise one of the many dispVM templates, (as envisaged), should be looking at the docs where the procedure is clearly explained, as bnvk did.

**Comment by marmarek** [comment]
@bnvk does the above comments makes this issue invalid? If not, reopen it.
