### ISSUE TITLE
please upgrade dom0 or consider using distribution with longer lifecycle

### ISSUE THREAD

**Issue by edwintorok** [QubesOS/qubes-issues#1086]
I installed Qubes R3.0 rc1 to test it, and it looks like dom0 is using Fedora20, which is [EOL](https://lists.fedoraproject.org/pipermail/announce/2015-June/003279.html). For something as security critical as dom0 I wouldn't like to run a distribution that doesn't get security updates anymore.
In fact even if there would be no security issues yet there is already a problem with Fedora20 as dom0:

I tried updating dom0 (by clicking on Update VM in the context menu), but I got a socket error after a while (probably lost network connection). Tried updating again, but it just seemed to get stuck on launching the update. Tried rebooting but it got stuck on the Q screen with progress bar at half, I've had to forcefully shutdown using the power button.
Now I get a corrupted screen (some diagonal lines) when booting and after a while a kernel panic before it even asks me for the disk password.
I would file a bug report about it with the panic trace and some logs, but since Fedora 20 is EOL I don't have a place where to file that bugreport.

I'd suggest to upgrade to fedora22 already to have a longer lifecycle for Qubes's dom0, and to have a place where to file bugreports if something breaks.

Alternatively Qubes could give a choice between Fedora and Debian as dom0, Debian stable usually has a longer lifetime and may even have LTS support.

**Comment by marmarek** [comment]
Take a look at this message:
https://groups.google.com/d/msg/qubes-users/D8CvUWYpQxk/VYFLp7raI_IJ

That said, we plan separation GUI into separate domain, then migration dom0 to some minimal distribution ([roadmap](https://github.com/rootkovska/qubes-roadmap)). GUI distribution upgrades would be much easier (and more frequent as a consequence). We haven't decided yet if we'll stay with Fedora there (but most likely).
But for now (R3.0), dom0 will be based on Fedora 20.
We planned dom0 upgrade in R3.1/R3.2 as a stopgap until GUI domain got implemented, but it will be probably postponed, because of major changes in KDE, which [requires more work than originally anticipated](https://groups.google.com/d/msgid/qubes-devel/20150708225129.GN900%40mail-itl).

**Comment by andrewdavidwong** [comment]
@marmarek, should this be closed as a duplicate of #1807, or would you prefer to change it to fit your comment above?

**Comment by marmarek** [comment]
There is already #833 for GUI domain, so this is a dupplicate of #1807
