### ISSUE TITLE
Using "Move To Other AppVM" fails poorly if non-existant

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1090]
If I select a file using the Nautilus File Manager and select "Move To Other AppVM" and then input a non-existent AppVM name, the dialogue disappears the same as when I input an existing AppVM and then nothing else happens. This is the same behaviour with "Copy To Other AppVM" as well.

This experience I think could be easily mis-understood as "the task completed" if a user doesn't know better / view the file's disappearing or verifies in the desired AppVM.

At the very least Qubes should notify the user `The [name of] AppVM you entered does not exist` and perhaps even better, provide a dropdown menu of the AppVMs available for file transfering

**Comment by nrgaway** [comment]
I get a dialog that opens that states something like this when the other AppVM does not exist: "Domain 'AppVM' doesn't exist (Service qubes.Filecopy called by domain vmname).  Is this issue with a Debian AppVM?  Sometimes I have seen the dialog existing but not in focus.

In regards to the drop-down, I believe that may cause a security implication since that would expose the other VM names to the AppVM.

**Comment by marmarek** [comment]
Regarding dropdown:
There is already functionality which provides recently used VM names there.
We don't want to expose full VMs list, but there is another option: #910 

Regarding original bug - is there anything special about that source VM? Was it set to be autostarted? What desktop environment chosen during installation? The default (KDE + Xfce)?

**Comment by marmarek** [comment]
@bnvk Are you able to reproduce the problem, or it happened just once? Every time I tried, I get error message that target VM doesn't exists.
Anyway if it happen to you again, check `/var/log/qubes/qrexec.VMNAME.log` in domo (replace VMNAME with name of VM from where you've tried to copy the file).
