### ISSUE TITLE
qvm-clone causes global lock on qubes.xml during the entire operation

### ISSUE THREAD

**Issue by omeg** [QubesOS/qubes-issues#1094]
Can't start new VMs, can't launch applications from the start menu etc. It would be nice if the lock was held only for actual xml/other config files updating, not the (potentially very long) image files copying.

**Comment by unman** [comment]
@andrewdavidwong Confirmed this issue still arises in 3.2 milestone

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
