### ISSUE TITLE
Debian Templates: Why change systemd default runlevel?

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1111]
Could you please explain the rationale behind modifying the systemd default runlevel? What would happen if that would be left untouched?

https://github.com/marmarek/qubes-core-agent-linux/blob/c6fa6c9b19425770e093a085da697d3c28d974c2/debian/qubes-core-agent.postinst#L104-L106

```
# Set default "runlevel"
rm -f /etc/systemd/system/default.target
ln -s /lib/systemd/system/multi-user.target /etc/systemd/system/default.target
```

https://github.com/marmarek/qubes-builder-debian/blob/56cd946068129185f69b703b9e5e450b8cfa698a/template_debian/02_install_groups_jessie.sh#L32-L36
```
#### '--------------------------------------------------------------------------
info ' Set multu-user.target as the default target (runlevel 3)'
#### '--------------------------------------------------------------------------
chroot rm -f /etc/systemd/system/default.target
chroot ln -sf /lib/systemd/system/multi-user.target /etc/systemd/system/default.target
```

**Comment by nrgaway** [comment]
I believe the purpose was to ensure a proper state upon installation.  Many of these scripts were written before Debian included systemd as default and are also used for other distros.

Most likely the `02_install_groups_jessie.sh` can be completely removed and those lines can be removed from `02_install_groups_wheezy.sh` since they are now present in `core-agent-linux.postinst`.  Note, that within `core-agent-linux.postinst` the target is only ever modified on the initial installation of the package, which happens during the template build process and not on further updates to the package.

**Comment by adrelanos** [comment]
> Most likely the 02_install_groups_jessie.sh can be completely removed and those lines can be removed from 02_install_groups_wheezy.sh since they are now present in core-agent-linux.postinst.

Yes, exactly my thoughts. Created #1112 seconds before you wrote that. :)

**Comment by marmarek** [comment]
I think this code was Fedora-specific (copied from there). On Fedora
default systemd target was "graphical.target", which tries to start
kdm/gdm/lightdm, so X server without qubes gui agent.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
The following pull request also solves this ticket:
https://github.com/marmarek/qubes-builder-debian/pull/20
