### ISSUE TITLE
Implement a "qvm" command with args instead of task specific CLI commands

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1115]
Perhaps this has been discussed in this past and was decided against, or perhaps it's not possible. Feel free to close accordingly :-)

- How about instead of typing: `qvm-copy-to-vm dest-vm Filename`
- A user would type `qvm copy-to-vm dest-vm Filename`
- Or an alternate `qvm copy dest-vm Filename`

The goal being that a CLI comfortable user could also type `qvm --help` and get all of the QVM style commands and descriptions. As a CLI comfortable user I find myself always forgetting the QVM specific commands. Curious the dev team's thoughts on this!

**Comment by marmarek** [comment]
I think the better place for the *discussion* is mailing list. Anyway
you can always use `qvm-<TAB><TAB>` to list available commands.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
If you feel this still apply after above comment, feel free to reopen it.
