### ISSUE TITLE
Live USB: opening file in DispVM doesn't work

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1119]
Opening a text file in a DispVM leads to this error:

"Unable to handle mimetype of the requested file (exit status: 256)!"

The file is not opened.

Reported at CCCamp!

**Comment by mfc** [comment]
However, an HTML file is opened fine.

**Comment by unman** [comment]
@andrewdavidwong I Have not been able to test this - please change milestone to 3.2 updates

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
