### ISSUE TITLE
files ~/.config/autostart/ in not persistent through VM reboots

### ISSUE THREAD

**Issue by fowlslegs** [QubesOS/qubes-issues#1125]
On Debian 8 template running Qubes R3-rc2 files are non-persistent in ~/.config/autostart, whereas a few places elsewhere in home, files do persist through reboots.

**Comment by unman** [comment]
I haven't seen this behaviour: autostart works as expected across reboots on my debian templates, home grown and ITL.

Since /rw/home is mounted on /home there's no reason why those files should appear to be non-persistent.
Do *none* of your autostart files persist? What about a simple xterm.desktop?

**Comment by marmarek** [comment]
Also note that files in template's /home are not propagated to already
existing VMs. Maybe this is what you mean?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by fowlslegs** [comment]
It turns out the application I was trying to autostart looks for a file in ~/.config/autostart with it's name and will remove it itself under certain circumstances. If I simply rename the .desktop file it persists.
