### ISSUE TITLE
Allow NetVM warning message to close open AppVMs

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1132]
Currently if a user tries to close a NetVM while AppVMs are using it, Qubes will not allow the NetVM to close and instead displays the message:

```
ERROR: There are other VMs connected to this VM: ['appvm-1', 'appvm-2', 'appvm-3']
```

It seems it would be helpful to users have an extra button that says "Close open VMs (using this NetVM)" and perhaps a message that explains the state of the AppVMs will be preserved.

**Comment by axon-qubes** [comment]
> and perhaps a message that explains the state of the AppVMs will be preserved.

What does this part mean? (ISTM that the states of the AppVMs would, in many cases, *not* be preserved (in many relevant senses of that word) upon being shut down.)

**Comment by bnvk** [comment]
> and perhaps a message that explains the state of the AppVMs will be preserved.

Perhaps that is not the best wording, but I meant that upon restarting an AppVM browser session data persists upon stoping and restarting AppVMs

**Comment by unman** [comment]
Well, not in dispVMs or VMs with TBB. And there may be all sorts of changes to state that would *not* be preserved on shutdown (e.g packages installed in template based VM, configuration changes), as above.
 It might be safer to warn that state *may not* be preserved.
That doesn't mean I don't like the suggestion.

**Comment by bnvk** [comment]
The UX improvement of the issue is to make shutting down a NetVM a faster & easier process. The message about state being preserved is honestly something that doesn't matter that much, it could not be included at all. That said, messages of this sort should be short and clear not trying to explain how all components of a system works.

**Comment by marmarek** [comment]
We aim to allow restarting NetVM without need to shutdown every
connected VM. This require fixing #975 and then implementing similar
functionality as described in #1082. Not something that will happen
soon...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by unman** [comment]
@andrewdavidwong Confirmed this issue still arises in 3.2 milestone

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
