### ISSUE TITLE
improve displayed apps and default VMs

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1139]
Even though a number of useful applications are installed by default, they are not displayed in the default VMs, but instead one must select "Add more shortcuts..." and add the programs.

The current default list is a pretty poor list from a usability perspective (Personal, Work, Untrusted, Banking -- all with Firefox and Terminal as the only two displayed apps).

I would recommend:
- all VMs at minimum also including the Files program when new AppVMs are created

For default installed VMs, I would further recommend:
- a Vault VM that only displays KeePassX, and is non-networked
- a Files-Offline VM that has: LibreOffice, Okular (or whatever the PDF viewer is), GIMP (or whatever image editing tool), Files and is non-networked
- an Email VM with Thunderbird, Files, and Thunderbird pre-configured for split-gpg
- a Split-GPG VM (is there a way to make Email VM dependent on this VM [like netVMs], so that when Email VM is opened this also is opened automagically?)
- tor/whonix gateway ProxyVM (only terminal displayed)
- Tor-Browser VM

other thoughts of default (or optional) displayed apps and VMs?

**Comment by marmarek** [comment]
On Thu, Aug 20, 2015 at 04:15:46AM -0700, Michael Carbone wrote:
> I would recommend:
> - all VMs at minimum also including the Files program when new AppVMs are created

This is actually on the default list, but because of bug related to #1031
it disappeared.

> - a Split-GPG VM (is there a way to make Email VM dependent on this VM [like netVMs], so that when Email VM is opened this also is opened automagically?)

It will be automatically started on first Split-GPG call.

All of this looks like ideal task for pre-configuration/mgmt stack on
which @nrgaway is working.

> other thoughts of default (or optional) displayed apps and VMs?

Maybe ask on ML?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
