### ISSUE TITLE
unduplicate / refactor umount_kill.sh

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1157]
There are 3 different versions in 3 different repositories.
- https://github.com/marmarek/qubes-builder-debian/blob/master/scripts/umount_kill.sh
- https://github.com/marmarek/qubes-linux-template-builder/blob/master/umount_kill.sh
- https://github.com/marmarek/qubes-builder/blob/master/scripts/umount_kill.sh

Step one, sync them. That alone would be worthwhile. The following two have only a single lined diff.

`diff ./qubes-builder-debian/scripts/umount_kill.sh ./qubes-builder/scripts/umount_kill.sh`

Step two, is it possible to have only one of these files in the Qubes source?

I was also always wondering if such a script and other image mount/umount/chroot related code could be upstreamed somewhere instead of reinventing it in every project. [libguestfs](http://libguestfs.org/) ([slow](https://www.redhat.com/archives/libguestfs/2014-February/msg00032.html)) [does not want kpartx based mount scripts](https://bugzilla.redhat.com/show_bug.cgi?id=1202900).

@nrgaway

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
