### ISSUE TITLE
Using SplitPGP to perform actions throws a tty error

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1160]
I've got SplitGPG setup working, or at least I think it is working. When I type `qubes-gpg-client -K` it properly shows my key UIDs correctly, and importing keys all work fine. However, if I try to encrypt anything from my `work-gpg` VM I get the following error:

```
[user@work-gpg ~]$ qubes-gpg-client --encrypt my-files.zip 
gpg: cannot open tty `/dev/tty': No such device or address
```

Is using `--encrypt` not allowed? As far as I understand from the use case of SplitGPG and the Docs, that sort of call should be allowed. Is this a bug in my system setup or a misunderstanding?

**Comment by bnvk** [comment]
Am also noticing this same error with trying to decrypt files using `qubes-gpg-client my-encrypted-file.gpg` so I'm going to assume it's something borked with my setup :/

**Comment by marmarek** [comment]
This is because it can't prompt you for a password (which would be
stupid to do in calling VM). Try adding `--batch` and/or `--use-agent`.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
