### ISSUE TITLE
do not install non-free package firmware-linux by default

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1177]
firmware-linux is a non-free package:
https://packages.debian.org/stretch/firmware-linux

So is firmware-linux-nonfree.

It's part of default package lists and installed by default in Debian templates, example:
https://github.com/marmarek/qubes-builder-debian/blob/0dccecacdd74ec1b10866143e3956e5fb8ca2241/template_debian/packages_jessie.list#L16

I haven't found any rationale on qubes-devel, qubes-user or the source code why firmware-linux(-nonfree) gets installed by default.

I am wondering about this, because these are the only non-free packages installed in Qubes-Whonix templates. And that is unfortunate, because these two non-free packages make the whole image non-free.

For finding non-free packages on Debian, vrms is quite useful.
https://packages.debian.org/stretch/vrms
Easy to use also. `sudo apt-get install vrms` + `vrms`. That's all.

If there is a rationale behind having this installed by default, then please explain and then this ticket could be closed.

**Comment by marmarek** [comment]
Yes, there is rationale - to be able to use Debian template as NetVM.
Many wireless cards requires some non-free firmware, unfortunately.

It's probably safe (and good idea) to remove those packages from Whonix
templates. @nrgaway any idea how to do that nicely (i.e. without
installing the package first, then removing it)? Maybe include it only
in "standard" flavor and do not use this flavor in Whonix templates (as
already done in Whonix-gateway)?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
> Maybe include it only in "standard" flavor and do not use this flavor in Whonix templates (as already done in Whonix-gateway)?

Both, yes.
(Whonix templates are now build using flavors minimal + no-recommends.)

**Comment by adrelanos** [comment]
Testwise:

* From `template_debian/packages_jessie.list` removed `firmware-linux`.
* To `template_debian/packages_jessie_standard.list` added `firmware-linux`.

Then those package no longer get installed in Whonix. So this should work.

**Comment by adrelanos** [comment]
Trying to come up with a pull request... Wondering...

What is the `.missing` file [template_debian/packages_stretch.missing](https://github.com/marmarek/qubes-builder-debian/commit/9934bf9dbb4fc3a53d1f816322f9eedaee2f7243) good for?

**Comment by adrelanos** [comment]
> Wondering...

> What is the .missing file template_debian/packages_stretch.missing good for?

Anyone any idea?

**Comment by marmarek** [comment]
On Mon, Sep 28, 2015 at 03:13:42AM -0700, Patrick Schleizer wrote:
> > Wondering...
> 
> > What is the .missing file template_debian/packages_stretch.missing good for?
> 
> Anyone any idea?

No idea, just guessing: maybe some placeholder instead of real file to
be done (TODO)? @nrgaway

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
* `linux-firmware` depends on both `linux-firmware-free` and `linux-firmware-nonfree`.
* Maybe `linux-firmware` was not available in Debian stretch at time of committing, so file `template_debian/packages_stretch.missing` was created as a reminder. Since this is no longer the case and the file seems unused, let's delete it.

Suggested solution:

* remove `linux-firmware*` from `template_debian/packages_jessie.list`
* add `template_debian/packages_qubes_standard.list`
* delete `template_debian/packages_stretch.missing`

What do you think?
