### ISSUE TITLE
Problems restoring Win AppVMs when the original template used a differently named user account

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1178]
If the default username as used on the original template (specifically on Qubes R2) was different than the one the current (new) template, the AppVM will not startup correctly, as Windows would be looking for the profile in `d:\Users\<new_username>`, while the AppVM will have only `d:\Users\<old_username>`.

A work-around is to switch to raw Windows template (w/o Qubes Windows Tools), create another temp user, log out from the <new_username> user, copy the c:\Users<new_username> onto d:\Users. Then shutdown and switch back to the proper Win template (with Qubes Windows Tools). Some things will not work, notably the shortcuts in SendTo context menu for copying files to other VMs. This is likely a result of old content of d:\Users\Default. One can manually copy files away from such old AppVM using qrexec-client-vm, but we need a better solution here.

**Comment by unman** [comment]
@andrewdavidwong I Have not been able to test this - please change milestone to 3.2 updates

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
