### ISSUE TITLE
Can't install Qubes

### ISSUE THREAD

**Issue by starius** [QubesOS/qubes-issues#1190]
I downloaded Qubes-R3.0-rc2-x86_64-DVD.iso and tried to install it on new Asus laptop. I had to enable CMS (whatever this CMS means) to boot from non-EFI USB device. USB device made by `dd` (official way) didn't work. I made USB device with `unetbootin`. It loaded, but installation failed.

Logs:
  * [output of journalctl](https://gist.githubusercontent.com/starius/e3e38da49d8e139d5b7e/raw/6e125efa4ee4a59d8b3af77c45bbe503a9d97119/gistfile1.txt)
  * [/run/initramfs/rdsosreport.txt](https://gist.githubusercontent.com/starius/4a3256c98da4cc765022/raw/4fd5d3a03110ff46fb4ac576459f7f385bd1c955/gistfile1.txt)

**Comment by marmarek** [comment]
Tools like `unetbootin` are not able to create proper Qubes boot media because those tools doesn't support starting Xen. What was exact issue with `dd` created media? Are you sure that USB stick is big enough (our image is slightly bigger than 4GB...).

Anyway such questions should go to [qubes-users mailing list](https://www.qubes-os.org/doc/QubesLists/) - there are many more people to help.
