### ISSUE TITLE
Qubes 3.0 rc3 still not on kernel.org mirror 

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1193]
https://mirrors.kernel.org/qubes/iso/

probably should put it up to reduce use of qubes-os.org FTP server, provide redundancy.

**Comment by marmarek** [comment]
AFAIR mirrors.kernel.org is synchronized on 2230 UTC, so should be
there really soon. Once it's there, I'll uncomment links on download
page.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
It's there.
