### ISSUE TITLE
Updating TemplateVM has weird DNS / network issues

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1196]
For the last week or two I haven't been able to get my debian-8 TemplateVM to update without errors and lots of hanging time when trying to download packages. I'm running my TemplateVMs through normal `sys-firewall` NetVM as it seems there are issues using TorVM or ProxyVM for updating packages.

Here is some of errors from running `sudo apt update`

```
...
Ign http://security.debian.org jessie/updates/main amd64 Packages/DiffIndex    
Err http://deb.qubes-os.org jessie/main Sources                                
  404  Not Found
Hit http://security.debian.org jessie/updates/main amd64 Packages         
Hit http://deb.qubes-os.org jessie/main amd64 Packages                         
Hit http://security.debian.org jessie/updates/main Sources                                   
Ign http://security.debian.org jessie/updates/main Translation-en_US
Ign http://security.debian.org jessie/updates/main Translation-en                            
Ign http://deb.qubes-os.org jessie/main Translation-en_US
Ign http://deb.qubes-os.org jessie/main Translation-en
Fetched 11.4 MB in 3min 3s (62.0 kB/s)
W: Failed to fetch http://deb.qubes-os.org/r3.0/vm/dists/jessie/main/source/Sources  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

And then here are some of the errors from running `sudo apt upgrade`

```
...
Get:4 http://http.debian.net/debian/ jessie/main libcupsmime1 amd64 1.7.5-11+deb8u1 [114 kB]         
Err http://http.debian.net/debian/ jessie/main ssl-cert all 1.0.35                                   
  500  Unable to connect
Err http://deb.qubes-os.org/r3.0/vm/ jessie/main qubes-core-agent amd64 3.0.16-1+deb8u1              
  500  Unable to connect
Get:5 http://deb.qubes-os.org/r3.0/vm/ jessie/main qubes-gui-agent amd64 3.0.11+deb8u1 [45.1 kB]     
Get:6 http://http.debian.net/debian/ jessie/main cups-daemon amd64 1.7.5-11+deb8u1 [375 kB]          
Get:7 http://deb.qubes-os.org/r3.0/vm/ jessie/main qubesdb amd64 3.0.5-1+deb8u1 [16.5 kB]            
Get:8 http://http.debian.net/debian/ jessie/main libavahi-core7 amd64 0.6.31-5 [112 kB]              
Err http://http.debian.net/debian/ jessie/main gawk amd64 1:4.1.1+dfsg-1       

...

Get:25 http://http.debian.net/debian/ jessie/main cups-browsed amd64 1.0.61-5+deb8u1 [78.8 kB]       
Err http://security.debian.org/ jessie/updates/main cups-ppdc amd64 1.7.5-11+deb8u1                  
  500  Unable to connect
Err http://http.debian.net/debian/ jessie/main gir1.2-notify-0.7 amd64 0.7.6-2
  500  Unable to connect
Get:26 http://http.debian.net/debian/ jessie/main gir1.2-packagekitglib-1.0 amd64 1.0.1-2 [32.7 kB]
Get:27 http://http.debian.net/debian/ jessie/main libcanberra-gtk-module amd64 0.30-2.1 [16.8 kB]
Get:28 http://http.debian.net/debian/ jessie/main libwnck-common all 2.30.7-2 [223 kB]
Err http://http.debian.net/debian/ jessie/main libwnck22 amd64 2.30.7-2                              
  500  Unable to connect
Err http://http.debian.net/debian/ jessie/main mate-notification-daemon amd64 1.8.1-3
  500  Unable to connect
```

**Comment by bnvk** [comment]
Here's an additional security warning re: some Qubes packages as well

```
The following packages will be upgraded:
  libicu52 libvchan-xen qubes-core-agent qubes-gui-agent qubes-utils qubesdb
6 upgraded, 44 newly installed, 0 to remove and 0 not upgraded.
Need to get 4,139 kB/17.3 MB of archives.
After this operation, 36.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
WARNING: The following packages cannot be authenticated!
  libvchan-xen qubes-utils qubes-core-agent qubes-gui-agent qubesdb
```

**Comment by marmarek** [comment]
Looks like some network issue. Or maybe updates proxy not running. Check
in `sys-net`: `systemctl status qubes-updates-proxy`.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment]
I know this isn't helpful advice but you could try creating & running a whonix gateway proxyvm, I've found they work for updating templatevms even when torvm does not.

**Comment by bnvk** [comment]
@marmarek here is the printout from `sys-net` which you requested:

```
[user@sys-net ~]$ systemctl status qubes-updates-proxy
● qubes-updates-proxy.service - Qubes updates proxy (tinyproxy)
   Loaded: loaded (/usr/lib/systemd/system/qubes-updates-proxy.service; enabled)
   Active: active (running) since Sat 2015-09-19 21:34:01 CEST; 17h ago
  Process: 451 ExecStartPre=/usr/lib/qubes/iptables-updates-proxy start (code=exited, status=0/SUCCESS)
  Process: 439 ExecStartPre=/usr/bin/install -d --owner tinyproxy --group tinyproxy /var/run/tinyproxy (code=exited, status=0/SUCCESS)
 Main PID: 470 (tinyproxy)
   CGroup: /system.slice/qubes-updates-proxy.service
           ├─ 470 /usr/sbin/tinyproxy -d -c /etc/tinyproxy/tinyproxy-updates....
           ├─ 476 /usr/sbin/tinyproxy -d -c /etc/tinyproxy/tinyproxy-updates....
           ├─ 477 /usr/sbin/tinyproxy -d -c /etc/tinyproxy/tinyproxy-updates....
           ├─ 983 /usr/sbin/tinyproxy -d -c /etc/tinyproxy/tinyproxy-updates....
           ├─1847 /usr/sbin/tinyproxy -d -c /etc/tinyproxy/tinyproxy-updates....
           ├─1848 /usr/sbin/tinyproxy -d -c /etc/tinyproxy/tinyproxy-updates....
           ├─1849 /usr/sbin/tinyproxy -d -c /etc/tinyproxy/tinyproxy-updates....
           ├─9391 /usr/sbin/tinyproxy -d -c /etc/tinyproxy/tinyproxy-updates....
           ├─9392 /usr/sbin/tinyproxy -d -c /etc/tinyproxy/tinyproxy-updates....
           └─9393 /usr/sbin/tinyproxy -d -c /etc/tinyproxy/tinyproxy-updates....
[user@sys-net ~]$ 
```

@mfc hehe yah, I'm just trying to get my normal Debian templates to work so I can go about checking email, etc... will try to integrate Whonix at some point soon!

**Comment by marmarek** [comment]
On Mon, Sep 21, 2015 at 06:23:10AM -0700, Brennan Novak wrote:
> @marmarek here is the printout from `sys-net` which you requested:
> 
> ```
> [user@sys-net ~]$ systemctl status qubes-updates-proxy
> ● qubes-updates-proxy.service - Qubes updates proxy (tinyproxy)
>    Loaded: loaded (/usr/lib/systemd/system/qubes-updates-proxy.service; enabled)
>    Active: active (running) since Sat 2015-09-19 21:34:01 CEST; 17h ago

(...)

Looks good. Check template settings - it should be:
 - connected to your sys-firewall VM (or any other providing some
   network access)
 - in firewall tab, allowed to access updates proxy

Do you have some VPN or anything else limiting/redirecting the traffic?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by bnvk** [comment]
> Check template settings - it should be:

- [x] connected to your sys-firewall VM (or any other providing some network access) 
- [x] in firewall tab, allowed to access updates proxy 

> Do you have some VPN or anything else limiting/redirecting the traffic?

No. My TemplateVMs are just connected to `sys-firewall` VM, nothing special. My AppVMs go through a TorVM which is based on my fedora-21 template.

It might be worth mentioning that my Fedora TemplateVMs are also timing out / not updating very often as well

```
[user@fedora-21-pkgs ~]$ sudo yum update
Loaded plugins: langpacks, post-transaction-actions, yum-qubes-hooks
Could not get metalink https://mirrors.fedoraproject.org/metalink?repo=updates-released-f21&arch=x86_64 error was
14: curl#22 - "The requested URL returned error: 500"
updates                                                                         | 4.7 kB  00:00:00     
http://mirror2.hs-esslingen.de/fedora/linux/updates/21/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for updates
Trying other mirror.
http://ftp.lysator.liu.se/pub/fedora/linux/updates/21/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://ftp.lysator.liu.se/pub/fedora/linux/updates/21/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
updates                                                                                                                       | 4.7 kB  00:00:00     
http://mirror.netcologne.de/fedora/linux/updates/21/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for updates
Trying other mirror.
updates                                                                                                                       | 4.7 kB  00:00:00     
http://www.nic.funet.fi/pub/mirrors/fedora.redhat.com/pub/fedora/linux/updates/21/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for updates
Trying other mirror.
http://mirror.slu.cz/fedora/linux/updates/21/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirror.slu.cz/fedora/linux/updates/21/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
http://mirror.vutbr.cz/fedora/updates/21/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirror.vutbr.cz/fedora/updates/21/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
```

**Comment by bnvk** [comment]
DOH!!! I think the root of the problem was due to a month ago @mfc suggested changing the `Dom0 Global Settings` to attempt making everything run over my TorVM- this worked for a couple weeks, then at some point stopped, so I gave up on this and switched each of my TemplateVM's individual settings to use the normal `sys-firewall` NetVM,

Apparently, I had forgotten about the global settings and left the `UpdateVM` to use my TorVM.

![dom0-global-settings](https://cloud.githubusercontent.com/assets/48677/10024960/f47d1504-6159-11e5-8837-757c7dd356e7.png)

After switching this back, all my Debian & Fedora templates update and new packages install just fine. That said, this seems like something we need to improve upon in perhaps one of these ways:

1. Make Tor & Proxy VM's more reliable
2. Limiting the configuration and possibility for this in the GUI
3. Forcing use of Whonix templates...
4. Redesigning / offering better GUI that includes how "global" settings affect each TemplateVM and AppVM ultimate settings
5. Offering a way to better report configurations like this to forums / here so less time is wasted

Feel free to close this issue or perhaps rename it, as this is definitely something to better track / work on improving!

**Comment by mfc** [comment]
yaaay glad it was solved! to be fair I recommended using a whonix-gw-based proxyvm, not a torvm, in part because I had previous encountered these same issues with trying to use torvm for template updates.

I think this maybe speaks to the need to depreciate torvm and ensure / make sure that whonix-gw can deliver on this intended functionality, which I know @adrelanos has been working on recently.

**Comment by marmarek** [comment]
TorVM (that fedora based) doesn't support updates proxy - so when set
as default netvm (or simply netvm for templates) it will not work. Also
it doesn't torify traffic originating from the TorVM itself (which is
clearly marked in the docs), so it's pointless to use it as an UpdateVM.
Both use cases works with Whonix Gw.

Generally I think we should deprecate TorVM in favor of Whonix GW. Any
objections?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by bnvk** [comment]
@mfc true, you did suggest that, I was wary as it was just after the UX review of the current state of Whonix and since the Global Settings seemed to work at that time, I went with it. Odd that they did at all based on @marmarek comment!

> Generally I think we should deprecate TorVM in favor of Whonix GW

Sounds good. Will that be in 3.0 or 3.1 or later? It seems like a pretty significant thing- perhaps enough that shipping a 3.0 with just normal TorVM (which will be deprecated) seems to mildly deflate the potential of a major release... thoughts?!

**Comment by mfc** [comment]
I have created a ticket to track torvm depreciation: #1201

**Comment by adrelanos** [comment]
We can have Whonix 12 ready for Qubes 3.0. Do you have any ETA for Qubes 3.0?

The development version Whonix UX now stays out of the way. I am in the final cleanup and testing stage (of non-UX stuff). I planned to create a thread on qubes-devel on how to proceed. There is some stuff I appreciate merged upstream at Qubes. Here are my notes:
https://www.whonix.org/wiki/Dev/Qubes#Build

**Comment by bnvk** [comment]
@mfc @adrelanos thanks, i'm closing this issue, as it is mislabled / better tracked elsewhere! Thanks y'all :)

**Comment by marmarek** [comment]
On Tue, Sep 22, 2015 at 11:41:45AM -0700, Patrick Schleizer wrote:
> We can have Whonix 12 ready for Qubes 3.0. Do you have any ETA for Qubes 3.0?

If nothing catastrophic will happen final R3.0 will be exactly the same
as R3.0-rc3 and released on Oct 1. The minor fixes which are already
fixed (pull requests) or will be discovered, will go as updates.

We can have Whonix 12 as default in R3.1 and also as an update to R3.0
(as previously done with 9->10->11).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment]
Would it be possible to add Whonix as one of the optional templates in the R3.0 ISO? Then for R3.1 we can aim to implement Qubes updates over Tor by default.

**Comment by marmarek** [comment]
On Wed, Sep 23, 2015 at 02:01:20AM -0700, Michael Carbone wrote:
> Would it be possible to add Whonix as one of the optional templates in the R3.0 ISO? Then for R3.1 we can aim to implement Qubes updates over Tor by default.

I don't think it's a good time to make any modification of R3.0 ISO.
Additionally Whonix currently needs some manual steps to work properly
(setting netvm of appvms, and the template(s) itself). In R3.1 we'll
have pre-configuration stack to handle this job.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment]
yeah true. I guess it would be more to build awareness of this functionality (so that folks try to set whonix up first instead of trying to set up torvms and avoid running into their various issues). 

at minimum maybe just add some text in the template installation screen noting that there are other templates available at https://www.qubes-os.org/doc/Templates/

otherwise users may think those templates listed (debian 7, debian 8) are the only ones other than fedora available.

**Comment by marmarek** [comment]
On Wed, Sep 23, 2015 at 02:35:14AM -0700, Michael Carbone wrote:
> yeah true. I guess it would be more to build awareness of this functionality (so that folks try to set whonix up first instead of trying to set up torvms and avoid running into their various issues). 

User still needs to look into documentation for that. So we may add some
info into TorVM documentation recommending Whonix.

> at minimum maybe just add some text in the template installation screen noting that there are other templates available at https://www.qubes-os.org/doc/Templates/

Yes, good idea.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
Using Whonix-Gateway as UpdateVM will be possible in Whonix 12, yes. It's a nice alternative in case of DNS issues, but not THE solution to updating issues.

**Comment by bnvk** [comment]
Hrm, still having weird issues with this, sometimes running `sudo apt update` seems ok and completes reasonably, other time it's hangs at various stages (usually the [Waiting for headers] stage) for really long periods 5 - 15 minutes to complete or timing out altogether.

This seems unique to the Debian TemplateVM as my Fedora template completes reasonably fast from same internet connection! Should I re-open and keep tracking this @marmarek ?

**Comment by bnvk** [comment]
Ok, definitely reopening this. The debian support seems to be quite messed up / poor in my experience. 

- Updating packages does not complete / times out
- The `locale` value seems to get erased causing Terminal (and now even Xterm) from not opening in a template I was trying to switch to `unstable` debian

It's a shame the debian support in Qubes seems so buggy, as it's the distro of choice for so many in the privacy / security community and reason consistently cited as why they don't use Qubes

**Comment by marmarek** [comment]
On Fri, Sep 25, 2015 at 03:31:48AM -0700, Brennan Novak wrote:
> Ok, definitely reopening this. The debian support seems to be quite messed up / poor in my experience. 
> 
> - Updating packages does not complete / times out

@mfc do you have any such problem?

> - The `locale` value seems to get erased causing Terminal (and now even Xterm) from not opening in a template I was trying to switch to `unstable` debian

As you've probably guessed, we don't support `unstable` debian version.
In any way.
We may consider building packages for `testing`, but not doing it
currently.

> It's a shame the debian support in Qubes seems so buggy, as it's the distro of choice for so many in the privacy / security community and reason consistently cited as why they don't use Qubes

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment]
> do you have any such problem?

no I do not, sorry. both firewall-vm and whonix-gw based template updates work for me. however i'm on 3.0rc3 and @bnvk is on 3.0rc2 which may have something to do with it?

**Comment by marmarek** [comment]
On Fri, Sep 25, 2015 at 07:51:02AM -0700, Michael Carbone wrote:
> however i'm on 3.0rc3 and @bnvk is on 3.0rc2 which may have something to do with it?

There is no difference - when you install updates on 3.0rc2, you'll
automatically be on 3.0rc3 (and later on final 3.0 when released).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by bnvk** [comment]
FWIW, I've since installed `whonix-ws` and `whonix-gw` and configured a proxy NetVM on the later. After making my normal `debian-8` template use the Whonix NetVM I'm able to update packages and install new ones perfectly.

So, perhaps my Qubes / debian-8 template is messed up somehow... I can try and do a fresh install on a spare machine using stock setup and report back!

**Comment by adrelanos** [comment]
Could be this DNS resolution issue?
https://github.com/QubesOS/qubes-issues/issues/1067

**Comment by marmarek** [comment]
On Mon, Sep 28, 2015 at 02:53:32AM -0700, Patrick Schleizer wrote:
> Could be this DNS resolution issue?
> https://github.com/QubesOS/qubes-issues/issues/1067

Since updates proxy is running in netvm (which isn't affected by this
bug) I don't think so. Unless, updates proxy was enabled in some other
VM? You can check that in VM settings - services tab (search for
"qubes-updates-proxy") - check for all the VMs in the network chain
between your template and netvm (in default setup it would be
`sys-firewall` only).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by bnvk** [comment]
I just changed the title of this issue. It definitely feels like something not specific to Debian, but rather Qubes network / DNS or what have you, like @adrelanos mentioned in the other issue, as now I'm experience *very* similar behavior with my `fedora-21` TemplateVM as it will not update and just says these sort of errors:

```
[user@fedora-21 ~]$ sudo yum update
Loaded plugins: langpacks, post-transaction-actions, yum-qubes-hooks
http://yum.qubes-os.org/r3.0/current/vm/fc21/repodata/repomd.xml: [Errno 12] Timeout on http://yum.qubes-os.org/r3.0/current/vm/fc21/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
http://yum.qubes-os.org/r3.0/current/vm/fc21/repodata/repomd.xml: [Errno 12] Timeout on http://yum.qubes-os.org/r3.0/current/vm/fc21/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
qubes-vm-r3.0-current                                                            | 2.9 kB  00:00:00     
tor                                                                              | 2.9 kB  00:00:00     
tor-source                                                                       | 2.9 kB  00:00:00     
Could not get metalink https://mirrors.fedoraproject.org/metalink?repo=updates-released-f21&arch=x86_64 error was
14: curl#22 - "The requested URL returned error: 500"
No packages marked for update
[user@fedora-21 ~]$ sudo yum update
Loaded plugins: langpacks, post-transaction-actions, yum-qubes-hooks
No packages marked for update
```

**Comment by bnvk** [comment]
Closing this as I have not experienced it since using 3.1 Whonix templates for my netvm! Hooray!
