### ISSUE TITLE
qubes-thunderbird outdated in Qubes repository?

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1199]
Using a freshly built Whonix development image. After first boot, a single package is not up to date. This happens during apt-get dist-upgrade.

```
Unpacking qubes-thunderbird (1.2.7-1+jessie1) over (1.2.7-1+deb8u1) ...
```

A bit confusing.

I guess it's the `not using +debNUMBER` bug. (https://github.com/QubesOS/qubes-issues/issues/1095) I further speculate, either https://github.com/marmarek/qubes-app-thunderbird has not been ported to the +debNUMBER style or the qubes-app-thunderbird package is outdated in the Qubes repository.

Two options. Either this can be fixed by uploading a package to the repository using the +debNUMBER style or not caring about this and waiting for next release of qubes-app-thunderbird so this would fix. Supposedly if qubes-app-thunderbird has already been ported to +debNUMBER style?

**Comment by marmarek** [comment]
There is no such thing as "package ported to +debNUMBER style" -
version suffix is in builder-debian. So this means that each package
will use +debNUMBER when newly built.
Anyway qubes-thunderbird=1.2.7-1+jessie1 is the same as
qubes-thunderbird=1.2.7-1+deb8u1, so IMHO we can ignore this issue for
now. It will just work when the new version will be uploaded.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
Alright.
