### ISSUE TITLE
Move qubes.qdb module outside qubes package

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#1252]
`qubes.qdb`, a compiled module, should still reside in `/usr/lib64`. It however
prevents importing of main `qubes` package, since `/usr/lib64` is searched
before `/usr/lib`. Therefore it should be renamed, for example to `qubesdb`.

**Comment by marmarek** [comment]
Some time ago you've pointed some module to automatically generate
C->python bindings. Can you remind me what it was?
It may be also converted to use ctypes to access that library, but I'm
not sure if that would be better (but it will be easier to read).
Not saying that strictly want to do that now.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by woju** [comment]
On Tue, Sep 29, 2015 at 03:58:13AM -0700, Marek Marczykowski-Górecki wrote:
> Some time ago you've pointed some module to automatically generate
> C->python bindings. Can you remind me what it was?
> It may be also converted to use ctypes to access that library, but I'm
> not sure if that would be better (but it will be easier to read).
> Not saying that strictly want to do that now.

[Cython](http://cython.org/). I already have some preliminary work on
that.

And no, `ctypes` is not easier to read. `ctypes` is, by some accounts,
less readable than plain C, plus it is easy to segfault the interpreter.
Cython with only minor attention make that very hard.

**Comment by marmarek** [comment]
On Tue, Sep 29, 2015 at 11:08:21AM -0700, Wojtek Porczyk wrote:
> And no, `ctypes` is not easier to read. `ctypes` is, by some accounts,
> less readable than plain C, plus it is easy to segfault the interpreter.
> Cython with only minor attention make that very hard.

You just need to define argument types (aka rewrite header file into
python), for example:
https://bitbucket.org/mhallin/py-scrypt/src/119842611360837902b12b7c5aadef5387318f70/scrypt.py?at=default

Anyway I think you know better what can be used here.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
