### ISSUE TITLE
Don't overwrite custom user commands in application menu shortcuts

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1286]
There have been persistent problems involving non-fuctional application menu shortcuts. (The most notorious examples have been `nautilus` and `xterm` failing to launch under common use cases. See #1285.) Users could easily fix these issues themselves if only their custom commands were not overwritten.

In addition to fixing problems, users might have legitimate reasons for wanting to customize their commands, e.g., to add functionality or for accessibility. These customizations should not be automatically (and silently) overwritten by Qubes scripts.

**Comment by marmarek** [comment]
This is highly difficult because different desktop environments have different methods of caching menus, editing items, etc. So it may not be even simple to notice if the file was edited by the user. Also this way, if the VM file changes location on upgrade, it won't be updated and such shortcut will be broken.

Anyway it is simple to copy the entry (in KDE menu editor - "copy", then "paste") and make the modifications in the copy. It will not be overwritten.
