### ISSUE TITLE
R3.0: Restored AppVM menu icons are buggy

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1289]
I restored several AppVMs onto a fresh R3.0 install. Even after using `qvm-sync-appmenus` and restarting everything several times, many of the KDE menu icons are exhibiting strange behavior: There appears to be no icon next to an entry, but then hovering over that entry causes the icon to appear (but only while the cursor is over it).

**Comment by marmarek** [comment]
I think this may be another case of #1106

**Comment by marmarek** [comment]
Also it may be some KDE icon cache issue... Try removing `/var/tmp/kdecache-*/icon-cache.kcache` then logout and login. 
If this doesn't help, take one misbehaving entry, find appropriate desktop file in `/var/lib/qubes/appvms/*/apps`, check the `Icon` key, check if the file pointed there really exists, is the correct icon etc.

**Comment by axon-qubes** [comment]
I was somehow able to get them all to show up correctly by add/removing entries and changing VM colors, then rebooting.

**Comment by marmarek** [comment]
I think this confirms KDE icon cache issue. The cache is removed when changing label specifically because of such problems.
Maybe we should remove it also after every `qvm-sync-appmenus` or even any icons modification? I'm not sure how it would affect performance, but outdated/broken icons in KDE is unfortunately quite common problem :(

**Comment by axon-qubes** [comment]
IME, `qvm-sync-appmenus` adds a noticeable delay when updating templates, so if we add even more steps, it would be nice if the whole process were not run automatically every time (especially if this particular issue only happens when AppVMs are restored from a backup, which should not happen very often).

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
