### ISSUE TITLE
R3.0: VMs set to autostart occasionally fail to autostart

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1290]
I'm not sure what caused this, but I set up a usbvm and set it to autostart. I tested it, and it was autostarting correctly. Then, several reboots later, it suddenly didn't autostart anymore (no autostart settings had been changed), and all the USB devices attached to it were automatically attached directly to dom0. Very dangerous.

**Comment by axon-qubes** [comment]
I did change the name of the usbvm, but if changing the name of a VM affects its autostart settings, that also sounds like a bug.

**Comment by marmarek** [comment]
On Wed, Oct 07, 2015 at 01:44:21AM -0700, Axon wrote:
> I did change the name of the usbvm, but if changing the name of a VM affects its autostart settings, that also sounds like a bug.

Yes, see #1256.
This is also fixed in `qubes-core-dom0` package in testing repository.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
