### ISSUE TITLE
R3.0: SplitGPG: User timeout override is not respected

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1292]
The default timeout is 300 seconds. Putting the following in your `~/.bash_profile` is supposed to override the default:

    export QUBES_GPG_AUTOACCEPT=86400

This worked in R2, but it no longer seems to be working in R3.0. Even with this line in `~/.bash_profile`, the timeout is still 300 seconds.

**Comment by marmarek** [comment]
What will surely work is adding such line in `/etc/qubes-rpc/qubes.Gpg`
(at the beginning). Not an ideal solution.
Maybe instead of plain env variables, we need to have config file for
split gpg?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Related issue #1316

**Comment by Rudd-O** [comment]
Glad I helped find the source of the inconsistency between the docs and the programs.  So where is this timeout thing documented?  I didn't know and it gets old clicking okay on the dialog evrytiem.

**Comment by axon-qubes** [comment]
It's documented here: https://www.qubes-os.org/doc/SplitGpg/
