### ISSUE TITLE
notify-send parameter --expire-time broken in Qubes

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1297]
How to reproduce:
1. Use a Qubes Debian template.
2. `notify-send --expire-time 20 test a`

Expected result:
Show up as on a comparable Debian jessie system.

Actual result:
The passive popup is just showing for a second.

Additional information:
When dropping the `--expire-time 20` parameter, it works normal.

**Comment by marmarek** [comment]
Check description of `--expire-time` parameter - the timeout is in
miliseconds, not seconds. It probably works on your another system,
because notification daemon running there doesn't support this feature
at all. Just curious - what notification daemon you have there?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
https://packages.debian.org/stretch/libnotify4, I think.

Right. My mistake. Not a bug. Closing.
