### ISSUE TITLE
R3.0: Minimal netvm system tray icon missing

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1299]
If you follow the instructions [here](https://www.qubes-os.org/doc/Templates/FedoraMinimal/) for using `fedora-21-minimal` as a netvm template, you will get a netvm icon (NetworkManager?) in the dom0 system tray in R2, but doing the same thing in R3.0 results in no netvm icon.

`NetworkManager` and `network-manager-applet` are both installed. Another missing package, perhaps?

**Comment by marmarek** [comment]
Did you installed update from testing repository (that fixing menu shortcuts for minimal template)? This may be the same issue.

**Comment by axon-qubes** [comment]
No, this template has no testing packages.

**Comment by marmarek** [comment]
Try simply installing `dbus-python`. This is what that fix does.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
Yes, that fixes it. However, it also causes the icon to show up for the firewallvm.

(My solution is just to base firewallvm on plain `fedora-21-minimal` instead, since I have no need for any packages in the firewallvm.)

**Comment by marmarek** [comment]
On Thu, Oct 08, 2015 at 07:16:03PM -0700, Axon wrote:
> Yes, that fixes it. However, it also causes the icon to show up for the firewallvm.

Maybe you have enabled `network-manager` also in firewallvm? Check
services tab in VM settings.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
Nope. (It's just the unmodified default `sys-firewall`.)

**Comment by marmarek** [comment]
Short answer: the missing package is `gnome-settings-daemon`, probably not something you want to install in minimal template.

Details: currently upstream [nm-applet is visible even if no NetworkManager is running](https://git.gnome.org/browse/network-manager-applet/commit?id=276a702000ee9e509321891f5ffa9789acfb053c). This is useless in Qubes, so we have some [script which hides the icon](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/network/show-hide-nm-applet.sh). It is done using gsettings - as the official way to hide the icon. This doesn't work without `gnome-settings-daemon`.
Ideally we would not start `nm-applet` at all, but since sometimes it is useful to have it not only in NetVM (for example to configure VPN), we haven't simple way to do it flexible enough.
You can disable nm-applet using other means. For example by creating `~/.config/autostart/nm-applet.desktop`:
```
[Desktop Entry]
NoDisplay=true
```
There are probably GUI tools for that.

Anyway since the main issue (missing nm-applet icon) is already fixed, I'm closing this ticket now.

**Comment by marmarek** [comment]
@Rudd-O found out that installing `dconf` alone fixes the problem. Will add to dependencies.

**Comment by Rudd-O** [comment]
No need for gnome settings daemon. Dconf alone works.
