### ISSUE TITLE
No policy definition found for qubes.WindowIconUpdater

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1318]
Getting a dom0 popup for the freshly build Whonix images.

> [dom0] Information
>
> No policy definition found for qubes.WindowIconUpdater. Please create a policy file in Dom0 in /etc/qubes-rpc/policy/qubes.WindowIconUpdater

-----

Perhaps I configure Qubes Builder `setup` to build from the 'marmarek/qubes- Stable' instead from 'marmarek/qubes- Unstable'?

**Comment by marmarek** [comment]
You're using VM packages from branch "master" (preparation for R3.1),
but dom0 from R3.0 (branch "release3.0").

Take a look at appropriate configs here:
https://github.com/QubesOS/qubes-builder/tree/master/example-configs

Probably you want switch to "release3.0" (this is what users are using).
But if you want bleeding edge R3.1, feel free to update also dom0 packages
(qubes-dom0-update --enablerepo=qubes*testing --releasever=3.1).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
