### ISSUE TITLE
virtualbox error

### ISSUE THREAD

**Issue by enjoyaol** [QubesOS/qubes-issues#1340]
Hi!
From the FAQ, it's written qube os is not supposed to be installed on a VM. However for the sake of easily testing it, i would like to be able to run it in virtualbox. It's not possible at the moment (from 3 or the alpha isos provided). Anaconda starts then after everything is set up the install begins and there is an error related to x11 I believe... Could you provide a working appliance ? Thanks!

**Comment by mfc** [comment]
This has been discussed previously on the qubes-user mailing list, the easiest way to test Qubes would be to use the live USB, found in the [Downloads page](https://www.qubes-os.org/downloads/). 

I don't think running a bare-metal hypervisor inside a hosted hypervisor is ever going to work well.

**Comment by qubesuser** [comment]
It works fine on KVM (might have to disable the x2apic CPU feature if it doesn't boot).

If there is an x11-related error in VirtualBox, maybe try to change the emulated graphics card model if that's possible.

It would indeed be nice to offer images for popular virtualization platforms (KVM, VirtualBox, VMWare Fusion/Workstation, Parallels Desktop) since it's much more convenient to test the system this way that by booting on the hardware itself, and new users generally aren't willing to put much effort in trying new things until they are sure they want to use them.

**Comment by marmarek** [comment]
@mfc it's up to you what we should do in this subject, but I'd close it as "wontfix" since we have a lot of more important tasks.

**Comment by mfc** [comment]
@marmarek agreed, I don't have the permissions to tag or close though.

**Comment by adrelanos** [comment]
I agree, that being able to run an operating system in VirtualBox on your existing operating system helps to make people try out and learn it. Many years ago, this is how I started trying out and learning how to use various linux distributions while I was still a Windows users. Even while I maintained a linux distribution myself (@Whonix), I would have jumped earlier into Qubes, if I had had a chance to get to know it inside a virtualizer. However, I recognize that there are loads of other tasks and this one cannot be easily/quickly be implemented.
