### ISSUE TITLE
Debian Templates: linux-headers-amd64 package installation fails

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1353]
```
Unpacking linux-headers-3.16.0-4-amd64 (3.16.7-ckt11-1+deb8u5) ...
dpkg: error processing archive /var/cache/apt/archives/linux-headers-3.16.0-4-amd64_3.16.7-ckt11-1+deb8u5_amd64.deb (--unpack):
 unable to clean up mess surrounding `./lib/modules/3.16.0-4-amd64' before installing another version: Read-only file system
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package linux-headers-amd64.
Preparing to unpack .../linux-headers-amd64_3.16+63_amd64.deb ...
Unpacking linux-headers-amd64 (3.16+63) ...
Processing triggers for man-db (2.7.0.2-5) ...
Errors were encountered while processing:
 /var/cache/apt/archives/linux-headers-3.16.0-4-amd64_3.16.7-ckt11-1+deb8u5_amd64.deb
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Any idea?

**Comment by marmarek** [comment]
`/lib/modules` is indeed mounted read-only. Same as the kernel, it is
provided by dom0, so VM have no influence on the kernel. So, in short
it is senseless to install kernel modules in the VM (using distro package).
What exactly linux-headers package try to write there? And why do you
want to install it?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
Use cases:

* Non-Qubes-Whonix builds try to install it (ok, that can be worked around)
* kernel module development, I wanted to compile a kernel module.

**Comment by marmarek** [comment]
On Fri, Oct 23, 2015 at 04:10:53AM -0700, Patrick Schleizer wrote:
> * kernel module development, I wanted to compile a kernel module.

That'd require having packaged headers exactly for kernel VM is using.
Currently we have them only as rpm package... So I think in practice the
only way to go is to get that rpm package (kernel-devel) and somehow
install it in Debian VM (either using "alien" or manually extracting to
some directory and pointing build scripts to use that).

This would be much easier when #1354 got implemented. I wonder why we
hadn't ticket for this already - the idea isn't anything new.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
We'll go PV Grub way (#1354).
