### ISSUE TITLE
Fail PCI device assignment to HVM on systems without IOMMU

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1373]
Otherwise it is really not obvious why the device isn't working.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
