### ISSUE TITLE
Warn when backuping rpm-installed template

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1385]
It would be next to impossible to restore it later (especially when this is the only template).
https://groups.google.com/d/msgid/qubes-users/084d6750-bd02-426c-a966-60096ca53f17%40googlegroups.com

**Comment by unman** [comment]
@andrewdavidwong Confirmed this issue still arises in 3.2

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
