### ISSUE TITLE
Appmenus creation tests

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1412]
- [ ] whether `NoDisplay=true` is respected
- [ ] whether entries are removed (from all the places, including AppVMs) when application got uninstalled in template
- [ ] check icon, also after VM color change

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by woju** [comment]
@andrewdavidwong This would be actually nice to have, but possibly low priority. Unless those tests were actually written and the bug not closed.

@marmarek?

**Comment by DemiMarie** [comment]
I am pretty sure this has been done.  Closing.
