### ISSUE TITLE
support copying (multiple) folders also by Qubes gui using dolphin

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1429]
Referring to:
https://www.qubes-os.org/doc/copying-files/

At the moment, only copying files is supported. Copying folders doesn't work.

**Comment by marmarek** [comment]
It's just documentation thing. Copying folders works just fine (cmdline
and nautilus, probably also dolphin).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
I only tested in dolphin yet. Doesn't work for me.

**Comment by mfc** [comment]
for me: the issue is with Dolphin in Debian-8, it is also unable to copy files. command line works fine. 

For Dolphin in fedora-21, whonix-ws it works fine.

**Comment by adrelanos** [comment]
> for me: the issue is with Dolphin in Debian-8, it is also unable to copy files.

This is:
https://github.com/QubesOS/qubes-issues/issues/1429

**Comment by mfc** [comment]
not sure if you meant to point to a different issue? or are suggesting I open a different issue for this (not sure if it's the same or not). but this is definitely a significant (UX) debian template bug.

**Comment by adrelanos** [comment]
Sorry, I confused your previous post. I thought you posted in a different ticket. Will delete my post.

**Comment by unman** [comment]
The issue with dolphin arises because kdialog isn't installed in the debian template. It can't be made a dependency of the core-agent package as it pulls a ridiculous amount of kde stuff with it, and isn't automatically installed with dolphin.
There's a PR which closes the problem with dolphin.

As @marmarek  said, the functionality to copy folders is already there, so this issue should be closed, and https://github.com/QubesOS/qubes-issues/issues/1839 updated.
