### ISSUE TITLE
Debian template: Agent admitted failure to sign using the key

### ISSUE THREAD

**Issue by talex5** [QubesOS/qubes-issues#1438]
With the Debian template, attempts to use ssh result in the error `Agent admitted failure to sign using the key.`

This seems to be caused by gnome-keyring-daemon, which is overriding ssh-agent's settings. I tried removing it, but this also removes qubes-gui-agent.

The solution seems to be to edit `/usr/bin/qubes-session` and comment out the code near the start that runs gnome-keyring, but this needs to be done again each time the package is upgraded, so a proper solution would be nice.

**Comment by marmarek** [comment]
And I think the proper solution is probably "remove hard dependency on
gnome-keyring-daemon". Anyway, what is wrong with ssh-agent built in
gnome-keyring? It should also just work...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by unman** [comment]
@andrewdavidwong  This has been resolved for some time (qubes-gui-agent 3.2.8 stopped loading of gnome-keyring environment), and in any case isn't really a Qubes issue per se. Also, there are simple mechanisms using rc.local and bind-dirs to reset qubes-session if needed. 
Issue can therefore be closed.
