### ISSUE TITLE
[UX] improve Nautilus file manager defaults

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1448]
talking with @bnvk, we agree that Nautilus has some really poor defaults for the user, and that unfortunately the settings are confusing to find (there are three different settings buttons, just try to find how to enable tree view...).

I would recommend the following defaults:
- list rather than grid
- tree view enabled

My own opinion is that Dolphin has better UX than Nautilus (all possible views are offered to the user without clicking any drop-downs, can do split view for users coming from using a Mac, selecting files/folders is based on icon/text rather than row, etc) but we won't go there for now. 

Have others had any UX issues with Nautilus defaults?

**Comment by bnvk** [comment]
Ah I actually had an open browser tab to file a similar issue. There was some specifics which are worth taking into account: it *might* be that, the grid view on Nautilus is either A.) buggy or B.) due to it's implementation in Qubes is failing. 

- Nautilus does not seem to respect sorting alphabetically even if `Arrange items: By Name` is selected when in `Grid View`

However, as @mfc mentions above, the defaults do seem to change / improve things quite a bit. An additional defaults that significantly improve Nautilus is:

- Enable the `Soft folders before files`

**Comment by bnvk** [comment]
To add slightly more information to the case I experienced above. There are actually two different shortcuts (for VMs based on Fedora Template) which can be used to launch Nautilus, one is `Files` and the other `File Manager`. The former seems to respect alphabetically organizing grid view, while the later does not!

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
