### ISSUE TITLE
tests for EFI support

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1493]
Add tests for correctly setting EFI configs on kernel upgrade, Xen upgrade etc.
For example see #1492

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
