### ISSUE TITLE
add cryptsetup as default app in debian templates

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1496]
`cryptsetup` is default installed in fedora templates. but since it is not installed by default in debian templates, the user may think that their encrypted volume (USB, hard drive, etc) is corrupted or otherwise inaccessible, when in fact they just need to install cryptsetup in thei debian template. 

there may be other important applications like this the user may have uneven user experiences with depending on debian vs fedora.

**Comment by adrelanos** [comment]
Created https://github.com/marmarek/qubes-builder-debian/pull/22 which is the equivalent for `sudo apt-get install cryptsetup lvm2`.(*) Is that enough? @mfc 

(*) For build and installed templates only. These packages will not be installed by default in existing templates. If you want this also, it requires another ticket, because that that is more difficult than anticipated.

**Comment by mfc** [comment]
i think so, thanks!
