### ISSUE TITLE
UAC enabled causes some anomalies

### ISSUE THREAD

**Issue by omeg** [QubesOS/qubes-issues#1500]
So far noticed that get-image-rgba process is erroring out when UAC is active. TODO: check what's the exact problem (error output is sent via stderr to the dom0 side of icon parser, possible to read? or capture in debug log in qrexec-wrapper).

**Comment by omeg** [comment]
Log files are *not created* by get-image-rgba in such case, which is pretty strange. Permission issues?

**Comment by marmarek** [comment]
On Wed, Dec 09, 2015 at 08:07:04AM -0800, Rafał Wojdyła wrote:
> Log files are *not created* by get-image-rgba in such case, which is pretty strange. Permission issues?

stderr in service calls is redirected to /dev/null on calling side, to
not deal with potentially untrusted logs... Can you log it in Windows
(applies to other services too)?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
