### ISSUE TITLE
Make Fedora template image smaller

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1507]
Currently qubes-template-fedora-23 rpm package is over 1.2GB, while qubes-template-debian-8 only slightly over 500MB. This all means that installation image does not fit on DVD.

**Comment by jgriffiths** [comment]
At the end of the build (post  'dnf clean packages'), there are 250MB of data in /var/cache/yum and 150MB ins /var/cache/dnf, plus a further ~430MB in /usr/share/locale (650 locales installed).

Debian appears to care more about space in general, for example they provide the foomatic printer DB compressed at ~450k vs 45 MB for fedora's uncompressed version.

https://fedoraproject.org/wiki/Changes/Glibc_locale_subpackaging will help when implemented no doubt. For dnf and yum, I wonder if a straight `rm -rf` instead of cleaning the packages would cause any harm.

**Comment by marmarek** [comment]
`rm -rf /var/cache/yum` is probably good idea. Not sure about `/var/cache/dnf`, because it will also remove cached metadata of repositories. Which means `dnf makecache` will be quite lengthy (even with fixed libsolv, it still takes some time).

**Comment by marmarek** [comment]
As dropping KDE was enough to fit the image on DVD, it is no longer an issue.
