### ISSUE TITLE
qvm-copy-to-vm incorrect progress report

### ISSUE THREAD

**Issue by kirill9000** [QubesOS/qubes-issues#1519]
It copies file fully, but reports in a manner like: `sent 10004/10005 KB` or even `sent 0/1 KB` for small files and that may confuse some users.

**Comment by Rudd-O** [comment]
Round up?  That might be the correct answer.

**Comment by bnvk** [comment]
Agree. This discrepancy has made me question if the copying was completed correctly of if some file failed to finish!

**Comment by unman** [comment]
@marmarek  There are cases where the report is correct, so Rudd-O's proposed solution wont work. 
I think the problem arises because the target figure comes from `du` operation on the sender, and the "progress" figure comes from the recipient, using a division in C (`x/1024`) to get Kb value. Division in C always truncates to zero so there will always be the possibility of discrepancy.
The only way I can think of guaranteeing there would be no discrepancy would be to write after a successfull copy , duplicating the target figure (sent TARGET of TARGET ), which is pretty monstrous.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by rustybird** [comment]
Affects 4.2 and 4.1
