### ISSUE TITLE
Set vm.swappiness=0

### ISSUE THREAD

**Issue by kirill9000** [QubesOS/qubes-issues#1520]
I think it should be done for SysVMs at least. With default value (60) they start swapping way too early:

    [root@sys-net ~]# free -m
                    total        used        free      shared  buff/cache   available
    Mem:            261          97           4           0         159         136
    Swap:          1027          57         970

**Comment by pqg** [comment]
This is not my strong suite, so sorry if this is a silly question, but what's wrong with that example memory distribution?  To push much of that swapped memory into RAM, the kernel would need to evict quite a bit of its buffers and caches.  It's not clear to me, just from the output of `free -m`, that this would be an advantageous decision.  Are you sure the kernel is getting it wrong and swapping out memory pages that are more heavily accessed than the cache?

**Comment by kirill9000** [comment]
Hmm. I figured that SysVM which is used just for routing doesn't need that much cache anyway. But maybe you're right. Let's see what the developers will say about this suggestion.

**Comment by marmarek** [comment]
IMO using some swap is not bad, unless the system is heavily swapping.
For example every VM is running X server with a bunch of GUI services
(gnome keyring etc). If those services aren't used, there is nothing
wrong with having them in swap. Generally Linux is quite good on
deciding what should be in RAM and what can be swapped to disk.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by kirill9000** [comment]
OK, I'll close it then.

**Comment by adrelanos** [comment]
We set it in Whonix for a long time now, and it has decreased
performance complaints a lot. Good idea.
