### ISSUE TITLE
logrotate on /var/log/xen fails every night

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1547]
@Rudd-O:

> error: skipping /var/log/xen/<name of>.log because parent directory has
> insecure permissions (It's world writable or writable by group which is
> not "root") Set "su" directive in config file to tell logrotate which
> user/group should be used for rotation.
> 
> pertinent RPM: xen-runtime-4.6

**Comment by ssm** [comment]
This still happens on qubes 4.0-rc2, with the package "xen-runtime-4.8.2-7.fc25.x86_24".

In the dom0, /var/log/xen, and all the files within, is owned by user "root" and group "qubes".  Logrotate expects "root" and "root" for each directory unless configured otherwise, and will skip these logs with an error if directory do not match this. It will also exit with exit code "1" each run, and an error in the journal.

To configure logrotate for the ownership of this directory, add the following line in /etc/logrotate.d/xen inside the {} block 

    su root qubes
