### ISSUE TITLE
dnf automatically runs in the background in AppVMs

### ISSUE THREAD

**Issue by greenrd** [QubesOS/qubes-issues#1575]
when using Fedora 23 template, at least.

This wastes resources.

**Comment by marmarek** [comment]
Generally AppVMs should check for updates, so you know when to update template. The problem is that DNF is extremely inefficient in that. Reported upstream here:
https://bugzilla.redhat.com/show_bug.cgi?id=1227014
OpenSUSE/libsolv#111
Fedora update pending here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-778555cbc2

I'll let this issue open for reference

**Comment by marmarek** [comment]
DNF high CPU usage is already fixed.
