### ISSUE TITLE
qvm-create-default-dvm whonix-ws - ERROR: Cannot start qubes-guid!

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1591]
```
qvm-create-default-dvm whonix-ws
```
```
--> Using TemplateVM: whonix-ws
--> Creating directory: /var/lib/qubes/appvms/whonix-ws-dvm
--> Copying the template's private image: /var/lib/qubes/vm-templates/whonix-ws/private.img
--> Creating volatile image: /var/lib/qubes/appvms/whonix-ws-dvm/volatile.img...
--> Creating icon symlink: /var/lib/qubes/appvms/whonix-ws-dvm/icon.png -> /usr/share/icons/hicolor/128x128/devices/appvm-gray.png
--> Creating default whitelisted apps list: /var/lib/qubes/appvms/whonix-ws-dvm/whitelisted-appmenus.list
--> Creating volatile image: /var/lib/qubes/appvms/whonix-ws-dvm/volatile.img...
--> Loading the VM (type = AppVM)...
--> Starting Qubes DB...
--> Setting Qubes DB info for the VM...
--> Updating firewall rules...
--> Starting the VM...
--> Starting Qubes GUId...
Connecting to VM's GUI agent: ..............................................timeout
ERROR: Cannot start qubes-guid!
```
Happening since I updated 3.0 using the Qubes testing repositories to 3.1.

How to reproduce.
1) remove any eventually already existing Whonix DispVMs
2) shut down all Whonix VMs
3) run `qvm-create-default-dvm whonix-ws`

**Comment by marmarek** [comment]
`whonix-legacy.service` is set to start before `qubes-gui-agent.service`, but after `qubes-dvm.service`. But `qubes-dvm.service` waits for gui agent startup, so it is dependency cycle. I think it shouldn't be set `Aftter=qubes-dvm.service`, maybe it should be even before it.

Systemd doesn't detect this dependency cycle because `qubes-dvm.service` doesn't have explicit `After=qubes-gui-agent.service`. But setting this, would lower concurrency of the boot process, especially in case of non-DispVM startup.

Background: `qubes-dvm.service` is the point where DispVM savefile is created. So everything before is running during savefile creation, everything after - in actual DispVM.

**Comment by adrelanos** [comment]
Fixed in git. Will land in Whonix 13.

Thanks so much for debugging this!
