### ISSUE TITLE
CalledProcessError in Qubes VM Manager

### ISSUE THREAD

**Issue by hansWURSCHT10000** [QubesOS/qubes-issues#1604]
I'm on Qubes R3.0 and I think I got this error now for the third time. Always when my PC boots and as soon as Qubes VM Manager starts.

It says:

> Whoops. A critical error has occured. This is most likely a bug in Qubes Manager
> 
> `CalledProcessError: Command '['/usr/bin/wmctrl', '-R', 'Qubes VM Manager']' returned non-zero exit status 1
> at line 542
> of file subprocess.py.`

Details:

```
----
line: raise CalledProcessError(retcode, cmd)
func: check_call
line no.: 542
file: /usr/lib64/python2.7/subprocess.py
----
line: ['/usr/bin/wmctrl', '-R', str(manager_window.windowTitle())])
func: bring_manager_to_front
line no.: 1959
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
----
line: bring_manager_to_front()
func: show_manager
line no.: 1916
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
```

I don't know why this error occurred.

[var_log_xen_console_hypervisor_log.txt](https://github.com/QubesOS/qubes-issues/files/86215/var_log_xen_console_hypervisor_log.txt)

**Comment by relder251** [comment]
I'm having the same issue in 3.2r1.  It only started after an update to dom0 (update in the last week).

**Comment by payalord** [comment]
I have the same problem after update just right now.

**Comment by Gastonite** [comment]
I'm having the same problem on R3.2.
I didn't change anything to the system. Yesterday it was working as usual, and today i have the same error message. How to recover a working machine? i tried to kill the qubes manager and relauch it the message does not appear anymore. But when i restart, it the same.

So i tried to update dom0, nothing change.

**Comment by Gastonite** [comment]
Ok 
I reproduced the bug on a fresh R3.2:

1. create some windows (e.g. Firefox of sys-net)
2. press ALT+F4 multiple times (this will close all the windows and when all are closed, the xfce session menu opens.
4. click the shut down button
3. power on and login

Now all the windows borders disappeared, there is only 1 desktop instead of 4 and an error prompt says: ```CalledProcessError: Command '['/usr/bin/wmctrl', '-R', 'Qubes VM Manager']...```

Thanks to [this post](https://groups.google.com/forum/#!topic/qubes-users/5oc8F_8u3wc), i followed the instructions of http://wiki.xfce.org/faq#i_have_only_one_desktop_and_can_t_move_my_windows_anymore_help

So, to resolve the problem, press ALT+F2 and type the following command :
```
xfwm4 --sm-client-id=${SESSION_MANAGER##*/} & disown
```
Normally, all windows will reappear and the error prompt will not appear at startup.
