### ISSUE TITLE
Please consider providing a Privacy Policy

### ISSUE THREAD

**Issue by o-** [QubesOS/qubes-issues#1624]
While reading https://www.qubes-os.org/news/2016/01/14/qubes-counter/ I couldn't help but wonder about the fact that you seem to retain PII of your users for a significant amount of time.

Maybe this is wrong and you actually convert ip addresses to pseudononymous identifiers. But i could not find out, therefore please consider publicly documenting your data retention policies. 

Good advice on the subject by the EFF https://www.eff.org/wp/osp e.g. states:
- Collect the minimum amount of information necessary to provide OSP services.
- Store information for the minimum time necessary for operations.
- Effectively obfuscate, aggregate and delete unneeded user information.
- Maintain written policies addressing data collection and retention.

For pointers on how to perform meaningful measurements while preserving user privacy I would recommend http://freehaven.net/anonbib/#wecsr10measuring-tor

**Comment by woju** [comment]
We rotate web server logs (which do contain IP addresses) monthly and
keep 2 files. However here in Poland IP addresses are not considered
PII, so technically we don't "retain PII" and therefore we are not
subject to any data protection requirements.

However, you are right we can write that somewhere.

/cc @joanna, @mfc, @marmarek

**Comment by rootkovska** [comment]
We make a statement in each of our canaries that the infrastructure should not be trusted:
https://github.com/QubesOS/qubes-secpack/blob/master/canaries/canary-006-2016.txt#L32-L37

This means that even if _we_ decided not to retain access logs, there is about a trillion of other entities (e.g. your ISPs, IXs, datacenter where the servers are hosted, etc) who might still decide otherwise and keep preserving the logs/traffic dumps for another millennium. Thus I think any statement from our side on this topic would be rather meaningless and potentially even misleading.

We do offer, however, an option for users to connect to the updates servers via Tor. As Wojtek wrote in the above mentioned post in Qubes 3.1 this could even be enabled at the installation wizard (= so very easy).

**Comment by mfc** [comment]
hey o-, thanks again for bringing this to our attention. let us collect this information woju and joanna mention, format it in a way the EFF highlights, and present it on the website.

**Comment by andrewdavidwong** [comment]
@mfc: Any update on this?

**Comment by mfc** [comment]
it would be helpful if someone with some legal experience could contribute.

**Comment by andrewdavidwong** [comment]
I have used [PrivacyPolicies.com](https://privacypolicies.com) to generate a standard [Privacy Policy](https://www.qubes-os.org/privacy/) and added it to the website. I have also added [Cookie Consent](https://cookieconsent.insites.com/). I am neither a lawyer nor a privacy expert. The Privacy Policy should be reviewed and modified or replaced as needed by legal and privacy experts as soon as possible.

**Comment by marmarek** [comment]
About cookie consent - we don't have any user login (session cookies) or specific traffic analyzers using cookies. In fact all site is static htmls (generated by jekyll), so there is no server-side processing of any cookies. We also avoid as much as possible using 3rd-party scripts - specially downloading them directly from 3rd-party servers.
It looks like the only cookies on the www.qubes-os.org are from Cloudflare. Those are [impossible to disable](https://support.cloudflare.com/hc/en-us/articles/200170156-What-does-the-CloudFlare-cfduid-cookie-do-), but [there are](https://webmasters.stackexchange.com/a/100637) [opinions](https://community.cloudflare.com/t/disable-cfduid-cookie-for-eu-law-compliance/19323) that those are exempted from consent requirement.

**Comment by andrewdavidwong** [comment]
> About cookie consent - we don't have any user login (session cookies) or specific traffic analyzers using cookies. In fact all site is static htmls (generated by jekyll), so there is no server-side processing of any cookies. We also avoid as much as possible using 3rd-party scripts - specially downloading them directly from 3rd-party servers.
> It looks like the only cookies on the www.qubes-os.org are from Cloudflare. Those are [impossible to disable](https://support.cloudflare.com/hc/en-us/articles/200170156-What-does-the-CloudFlare-cfduid-cookie-do-), but [there are](https://webmasters.stackexchange.com/a/100637) [opinions](https://community.cloudflare.com/t/disable-cfduid-cookie-for-eu-law-compliance/19323) that those are exempted from consent requirement.

Removed language about session cookies and tracking.

**Comment by marmarek** [comment]
Ok, I've switched off cloudflare for www.qubes-os.org. And enabled https on github pages there (provided by lets encrypt). Now, entering https://www.qubes-os.org/ leaves no cookies in the browser :)
(you may need to remove those old ones from cloudflare)
Can we remove that annoying message?

**Comment by andrewdavidwong** [comment]
Done.

**Comment by andrewdavidwong** [comment]
Here are some questions about the Privacy Policy:

We may also collect information about how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

I know we count IPs for the [Userbase Estimate](https://www.qubes-os.org/statistics/), but what about the other things mentioned here? I doubt we monitor time spent of pages, for example, so could that be removed?

> The Qubes OS Project uses the collected data for various purposes:
> 
> To provide and maintain the Service
> To notify you about changes to our Service
> To allow you to participate in interactive features of our Service when you choose to do so
> To provide customer care and support
> To provide analysis or valuable information so that we can improve the Service
> To monitor the usage of the Service
> To detect, prevent and address technical issues

Can or should any of these be removed?

**Comment by jpouellet** [comment]
The "customer" and "service" language does not seem fitting. Perhaps "user" and "Qubes OS"? IANAL, standard disclaimers apply.

also:

> To allow you to participate in interactive features of our Service when you choose to do so

I am not aware of anything interactive on the site.

**Comment by andrewdavidwong** [comment]
> I am not aware of anything interactive on the site.

One concern is that a lawyer could argue that any current or future JavaScript-based functionality is "interactive" or that a reasonable layperson might interpret it as such.

**Comment by marmarek** [comment]
Even if those parts (automatic ToC generation, anything else?) are interpreted as "interactive", they do not send any data to the server, it's purely client-side, so we don't collect anything there.

**Comment by andrewdavidwong** [comment]
> Even if those parts (automatic ToC generation, anything else?) are interpreted as "interactive", they do not send any data to the server, it's purely client-side, so we don't collect anything there.

The policy says that we use collected data to improve those things, not that we collect data by means of them.

**Comment by andrewdavidwong** [comment]
> The "customer" and "service" language does not seem fitting. Perhaps "user" and "Qubes OS"? IANAL, standard disclaimers apply.

The "Service" is the website, not Qubes OS.

**Comment by jpouellet** [comment]
Any chance the URLs could be changed to /legal/privacy and /legal/terms (and not redirect from /privacy)?

It feels rather odd and... just... wrong IMO for qubes-os.org/privacy to be legal boilerplate instead of information about how users can leverage Qubes to protect their privacy. IMO, if /privacy is a valid URL, it should point at https://www.qubes-os.org/doc/#privacy-guides or something.

**Comment by andrewdavidwong** [comment]
> Any chance the URLs could be changed to /legal/privacy and /legal/terms (and not redirect from /privacy)?

Even if the URL were changed at this point, it should still redirect from `/privacy/` since it's already been publicly established there.

(Note that `/privacy/` and `/terms/` are standard URLs for website Privacy Policies and Terms of Use.)

> It feels rather odd and... just... wrong IMO for qubes-os.org/privacy to be legal boilerplate instead of information about how users can leverage Qubes to protect their privacy. IMO, if /privacy is a valid URL, it should point at https://www.qubes-os.org/doc/#privacy-guides or something.

I don't share that intuition. We maintain a distinction between content about *using* Qubes OS once it's installed (`/doc/`) and stuff that's broader (`/`), including the website and the project itself. For example, https://www.qubes-os.org/security/ hangs directly off of the base URL because it's also about the security of the project, not just about the security of Qubes OS as a piece of standalone software (and because security is a special concept, being what Qubes is all about).

**Comment by esote** [comment]
@andrewdavidwong I think this issue is now resolved. Qubes has added a privacy policy, and it looks to be sufficient.
