### ISSUE TITLE
Template policy, services->features, core plugins

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#1637]
Some templates, like `whonix-ws`, may like to impose some policies unto their appvms. (The example, discussed here, is time synchronisation — by default Whonix should not receive current time from `dom0` for privacy reasons).

Those policies will be expressed as some plugins/enhacements to the core-admin. The logic (and program flow) of such plugins will contain that policy. Policy may be influenced by domain's properties (which are hardcoded into core) or "features", an expansion of the previous (core1-2) concept of "services". Features is a dictionary (key-value store), with keys being subset of ASCII and values being UTF-8 encoded strings. Value may be an empty string or the entire key-value pair may be absent.

During installation, template is started and it may perform some qrexec rpc calls. There should be one call (it is currently called `qubes.NotifyTools`), which when called signals to the plugins that there are some qubesdb entries updated, that should help the plugin to set the policy and maybe store it in domain's properties and/or features.

Then some tools, when faced with policy decision, may make decision based on the features of the domains in store. It is expressly allowed to make decisions based on properties/features of other domains, like domain's template or netvm.

Features may be shared between plugins/subsystems (i.e. plugin/tool may make decisions based on features kept by other tool/plugin), like in `/proc/cmdline`.

Anything missing?

/cc @marmarek

**Comment by woju** [comment]
How that fits our previous conversation about qrexec policy?

**Comment by marmarek** [comment]
Another use case for this mechanism would be Windows VMs, with Qubes Windows Tools being installed, or not. When it calls `qubes.NotifyTools`, some plugin will handle that to record the fact that tools are installed and the next time (or even this time?) VM should have proper GUI daemon started, possible to enable seamless mode etc.

> How that fits our previous conversation about qrexec policy?

I think it is mostly orthogonal, as new qrexec policy (#867, #865) is mostly about calls made *from* ~~VMs~~ qubes, but here we are talking about mostly qubes settings and calls made *to* qubes. At best, those "features" discussed here may be (some of) factors being considered by qrexec policy.

**Comment by marmarek** [comment]
Related to: https://github.com/QubesOS/qubes-issues/issues/1323

**Comment by aberja** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "qubesos-bot [Masked]" <FWD-737QTYSMENAIYCQANIQDDYDDEBMGAKZBA3UHCIZQERQDGACTBZAAEUAJ4ZAIMDO2CA6UDIAORVCDQL4CNLHDEARYKUKFA3AEKMEBBOROEARUYWSUIMBVIRBS5VSMQQROCHCQFKLCEABMCEGAAHYAHOACPAANQADYALNUXPBAF4YCWMBFMEUEOMSXFMEGIABAAAQA====@opayq.com> is being returned by server opayq-outbound.junkemailfilter.com on Fri, 09 Jun 2017 14:48:51 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  mm1@canadianmoneymatters.ca
    host canadianmoneymatters.ca [67.231.20.103]
    SMTP error from remote mail server after RCPT TO:<mm1@canadianmoneymatters.ca>:
    554 Security failure
