### ISSUE TITLE
The drive attachment icon sometimes remains after shutting down a vm 

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1640]
https://groups.google.com/d/msgid/qubes-users/56991577.9030003%40openmailbox.org

> The drive attachment icon sometimes remains next to a vm in the
> Manager list after shutting down a vm with an attached volume. Starting the
> vm again does not clear the icon, and the 'Detach...' menu option is visible
> in the context menu (but using it has no effect). The restarted vm itself
> does not show any /dev/xvdi entries.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
