### ISSUE TITLE
Application menu isn't update after switching VM template

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1651]
1. Create Fedora 23 based VM
2. Check if "Terminal" shortcut does work (it should)
3. Shutdown the VM
4. Switch template to Debian 8
5. Try to start "Terminal" - it doesn't work now

Menu entry still points to the old menu entry (from Fedora 23), which is different.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
