### ISSUE TITLE
hardening Whonix update/upgrade design inside Qubes

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1666]
from this design:- 
![snapshot1](https://cloud.githubusercontent.com/assets/11895339/12464502/2b2397f2-bfc1-11e5-92ef-9b49c57f076b.png)

to this design:- 

![snapshot2](https://cloud.githubusercontent.com/assets/11895339/12464556/7288a8b2-bfc1-11e5-909d-caf9a5e735c0.png)

and i think its obvious for reasoning why it has more security and even useability at the same time.

**Comment by mfc** [comment]
apologies but the diagrams are actually not that illuminating, it might be better to write out your ideas?

1. whonix-gw should be a proxyvm not an appvm
2. you seem to be suggesting... standalone VMs for the whonix-gw and -ws rather than templates?

please pitch these ideas to the mailing lists or whonix forums first to get feedback, thanks!

**Comment by TNTBOMBOM** [comment]
> apologies but the diagrams are actually not that illuminating, it might be better to write out your ideas?

already did that:-
https://forums.whonix.org/t/upgrading-the-update-upgrade-mechanism-of-whonix-templates/1933

> 1. whonix-gw should be a proxyvm not an appvm

yeah , but meant by the appVM it will be based on a template whonix , or it is not a sudoers/standalone VM.

> 2. you seem to be suggesting... standalone VMs for the whonix-gw and -ws rather than templates?

nope.

> please pitch these ideas to the mailing lists

to be honest with u , i hate the google groups and i hope i dont need to use it in the future. because i hate google.

**Comment by marmarek** [comment]
On Sat, Jan 23, 2016 at 05:55:31AM -0800, TNT BOM BOM wrote:
> > please pitch these ideas to the mailing lists
> 
> to be honest with u , i hate the google groups and i hope i dont need to use it in the future. because i hate google.

You can use whatever email client you want. I use mutt for example.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by TNTBOMBOM** [comment]
aha ok , i will fix the design then (from appvm to proxyvm) and re-upload the photos but witha mailing list. 

thnx (f)

>  I use mutt for example.

i just want to tell u : damn how old and gold u r dude.
