### ISSUE TITLE
anti-conformational attack (Whonix+Qubes theory)

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1671]
the design:- 

https://forums.whonix.org/uploads/default/original/1X/258fdf25ca73641ee3610de4a6893ee6e001b60b.png

 with this design if im getting it correctly , it will be very hard to make a conformational attack or at least very hard also to compromise the GW (Whonix GateWay = medified debian + Tor).

Note:- this design is very possible to happen inside Qubes OS + Whonix OS

The explanation:-

there will be for e.g. five DisposableVM (amnesic VM) which they are connected to the WS (Whonix workstation = medified debian + TBB) , but in fact they wont be working together how?

if u c the refresh icon it means the DisposableVM is turning OFF and going to be ON again after few minutes. while others r still working , and by this we get:-

continuing connection to workstation (working area) , and anti-compromisation to Tor , because the disposableVM will keep shutting shutdown itself and start again from point 0.

the green lines means the disposableVM is working, and red lines means disposableVM is refreshing itself by turning on/off itself from time to time (automatic off/on switcher).

i dunno if my guess is right or wrong. hope i c some activity to this idea. 

copied from my report to Tor-trac:- 
https://trac.torproject.org/projects/tor/ticket/18121

**Comment by marmarek** [comment]
In that case data in GW will not be persistent. AFAIR it is a problem for entry guards, isn't it? @adrelanos

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> In that case data in GW will not be persistent. AFAIR it is a problem for entry guards, isn't it? @adrelanos
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/QubesOS/qubes-issues/issues/1671#issuecomment-173736213
> 

Yes.

But let's put that aside for now. You could say, it's a feature, not a bug:
https://www.whonix.org/wiki/Tor#Non-Persistent_Entry_Guards

Even then I think this concept is fundamentally flawed. An end-to-end
correlation attack conceptually does not get broken by default just
because you are keep switching to new Tor clients. I don't see why it
shouldn't work even if it's just short lived connections.

If that concept in indeed great, then the Tor community would be the
ones to be convinced. It's possible to describe this concept in generic
terms while avoiding the terms 'Qubes', 'Whonix' and perhaps even 'VM'.
This is what should be done if you want to peruse this. It would take a
whole lot more work.

**Comment by TNTBOMBOM** [comment]
yeah i should describe this in generic terms , because i doubt if they got what does disposableVM or TorVM mean. 

 the main issue also with entry guards. hmm but Tails then has severely fallen into this issue , and what im suggestion is kinda similar to multiple Tails with no TBB inside it (instead of DisposableVM) + the isolation security of whonix (workstation+TBB). 

so even if my idea is bad regarding entry guards then whole Tails idea is also bad. and if we say that my idea is bad to anonymity similarly to Tails then i dont think it is a bad idea the first place because Tails is known for its issue with entry guards but tho it is well useable in the anonymity field.

and maybe im missing the point , i dunno for sure ...

**Comment by mfc** [comment]
this should probably be first pitched to tor-talk and other tor-related mailing lists for further feedback from the tor community, qubes-issues is not the best place to have this discussion. seems like you already got some useful feedback from the torproject trac ticket.
