### ISSUE TITLE
Consider blacklisting PCI hotplug-related modules

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#1673]
Would it make sense to disable CONFIG_HOTPLUG_PCI (which all the PCI hotplug modules depend on) in qubes-linux-kernel, to prevent DMA attacks via ExpressCard and Thunder~~bird~~bolt ports?

**Comment by marmarek** [comment]
While is some cases it is really good idea, some people depend on those ports, so we can't make this change distribution-wide.
On the other hand, it may be good idea to blacklist related modules.

**Comment by ttasket** [comment]
If the whole pcie hotplug feature could be blacklisted as a module, that would be great. I thought it was a module, but I see no sign of it now.

**Comment by marmarek** [comment]
Indeed, since 3.11 it isn't possible anymore: http://linux-ia64.1045702.n5.nabble.com/PATCH-0-2-PCI-Convert-hotplug-core-and-pciehp-to-be-builtin-only-td5710754.html

**Comment by rustybird** [comment]
> While is some cases it is really good idea, some people depend on those ports, so we can't make this change distribution-wide.

They could still use the ports, only they'd have to plug their stuff in before the Linux kernel starts.

**Comment by rustybird** [comment]
@marmarek:

FWIW, I've been running this setup in the last few weeks: Using a kernel with CONFIG_HOTPLUG_PCI disabled, when I need an ExpressCard I plug it in during GRUB (not before, in case it has an option ROM). Works very well, especially with flush-mount ExpressCards.

Isn't this a good trade-off between extensibility and security against a very quick physical attack?

**Comment by marmarek** [comment]
Ok, I'm for this change.
@rootkovska any reason to not do this?

**Comment by rootkovska** [comment]
Sure, we should do that.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.4.14-11.pvops.qubes` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/762d41e99b007e1e9a61a6b71af1c7b722c7b84b...ec697d5db041a2e404599fc7d4ac4346b4fdf6c9

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.4.14-11.pvops.qubes` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/762d41e99b007e1e9a61a6b71af1c7b722c7b84b...ec697d5db041a2e404599fc7d4ac4346b4fdf6c9

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-4.4.14-11.pvops.qubes` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/762d41e99b007e1e9a61a6b71af1c7b722c7b84b...ec697d5db041a2e404599fc7d4ac4346b4fdf6c9

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.4.14-11.pvops.qubes` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...ec697d5db041a2e404599fc7d4ac4346b4fdf6c9

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.4.14-11.pvops.qubes` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...ec697d5db041a2e404599fc7d4ac4346b4fdf6c9

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-4.4.14-11.pvops.qubes` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...ec697d5db041a2e404599fc7d4ac4346b4fdf6c9

**Comment by andrewdavidwong** [comment]
@rustybird:
> when I need an ExpressCard I plug it in during GRUB (not before, in case it has an option ROM). Works very well, especially with flush-mount ExpressCards because those can be left in the slot without being a bother.

I don't understand. If you leave one plugged in throughout an entire reboot process, doesn't that mean it's plugged in before GRUB?

**Comment by andrewdavidwong** [comment]
@marmarek, what was the actual resolution of this issue? Did we end up blacklisting PCI hotplug-related modules or not? Is the current behavior in Qubes documented somewhere?

**Comment by rustybird** [comment]
> @rustybird:
>> when I need an ExpressCard I plug it in during GRUB (not before, in case it has an option ROM). Works very well, especially with flush-mount ExpressCards because those can be left in the slot without being a bother.
> 
> I don't understand. If you leave one plugged in throughout an entire reboot process, doesn't that mean it's plugged in before GRUB?

Right, to prevent the BIOS from executing an option ROM, you'd have to remove the card during that part of the reboot cycle. The reference to flush mount cards was about leaving them in while the notebook is running (which might be annoying with non-flush mount cards that stick out of the slot).

Alternatively, coreboot/SeaBIOS can be configured to never execute option ROMs.

> what was the actual resolution of this issue? Did we end up blacklisting PCI hotplug-related modules or not?

Yes - except that the PCI hotplug code is organized monolithically, so [Qubes does not compile it at all](https://github.com/QubesOS/qubes-linux-kernel/blob/0ea1c7b71f23e4179e92c3d4af9545537e5005df/config-qubes#L71-L75) (i.e. there's no module that the user could load).

**Comment by imjustmatthew** [comment]
Does this choice to disable hotplug assume the Thunderbolt device authorization model is somehow broken? I'm not familiar with the low-level interface, but I thought the entire point of device authorization was to prevent DMA attacks by requiring the host OS to authorize the device before PCIe and DMA were enabled by the controller?

I'm looking at the as-shipped BIOS settings in a 2017-era Dell laptop and thunderbolt devices by default require authorization. I realize older laptops may not have this, but since Qubes is only targeting devices with VT-d,it seems like most of these devices will actually have device authorization support.

**Comment by marmarek** [comment]
@imjustmatthew no, it's because Thunderbolt are not the only DMA capable, hotpluggable devices. There are also Express cards, Firewire, and few more.

**Comment by imjustmatthew** [comment]
> @imjustmatthew no, it's because Thunderbolt are not the only DMA capable, hotpluggable devices. There are also Express cards, Firewire, and few more.

Thanks. Would it be reasonable to blacklist the individual modules for thunderbolt, firewire, expresscard, etc. instead of removing CONFIG_HOTPLUG_PCI entirely? That at least gives end users the option to enable thunderbolt support without building a custom kernel for dom0.

More broadly, it seems safer to use Thunderbolt-based PCI devices, such as network adapters, that can be directly attached to a specific security domain rather than USB devices that have all the USB-related security problems. As was pointed out in [another issue](https://github.com/QubesOS/qubes-issues/issues/2454#issuecomment-369754473), securing thunderbolt is an area of active development upstream. The user also gains the ability to have a plethora of USB controllers that can be isolated --- for example, one of the docks I'm testing has 3 different PCI USB controllers, potentially allowing USB devices to be used with much stronger isolation than sys-usb can offer.

**Comment by marmarek** [comment]
Unfortunately it isn't that easy. First of all, Thunderbolt hotplug support in Linux depends on PCIe hotplug, which will also get you Express Card hotplug. You can't enable just Thunderbolt. But then, it needs to be carefully coordinated with Xen. Otherwise the device will end up in dom0 - even if for a short time, it would be enough time to perform some attack. This last part may be non-trivial and from preliminary analysis it will require some changes in Xen.
In this case, USB is better, because all USB devices are contained in sys-usb, even shortly after plugging them in (as the whole controller is isolated). While there are multiple problems with USB, at least it is isolated from dom0.

Anyway, as you pointed out, the correct solution is tracked as #2454
