### ISSUE TITLE
bad Qubes 3.1-rc2 torrent advertised

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1684]
http://burnbit.com/torrent/446015/Qubes_R3_1_rc2_x86_64_iso

advertised checksum/hash does not match:

https://mirrors.kernel.org/qubes/iso/Qubes-R3.1-rc2-x86_64.iso.DIGESTS
https://ftp.qubes-os.org/iso/Qubes-R3.1-rc2-x86_64.iso.DIGESTS

would be good to implement https://github.com/QubesOS/qubes-issues/issues/1245 to reduce likelihood of this type of issue.

**Comment by john-tho** [comment]
In case anyone is looking for a good torrent, the one hosted at this link worked for me:
[https://rudd-o.com/downloads/qubes/Qubes-R3.1-rc2-x86_64.iso.torrent/view](https://rudd-o.com/downloads/qubes/Qubes-R3.1-rc2-x86_64.iso.torrent/view)

**Comment by marmarek** [comment]
Since @Rudd-O is hosting good torrent and its advertised on our download page, it shouldn't be a problem anymore.

**Comment by mfc** [comment]
it would be really nice if we hosted the .torrent file on ftp.qubes-os.org for consistency https://github.com/QubesOS/qubes-issues/issues/1245 (just like the ISO file). We can also advertise it hosted on rudd-o's site if we want, but it would be nice for users to not have to be introduced to a third site to download the ISO.

**Comment by Rudd-O** [comment]
I have a pull request open to reform the download page.  I can eliminate the burnbit link.

I am not opposed to putting the torrent file into the ftp.qubes-os.org.  This would require creating the .torrent file on the Qubes OS Project side, which is not hard, and sending it to me so that I can seed it.  The creation of the torrent must include a Web seed so that my server can download the file and begin seeding.  This is more or less the process:

```bash
mkdir Qubes-R3.1-rc3-x86_64
cd Qubes-R3.1-rc3-x86_64
ln ../Qubes-R3.1-rc3-x86_64.iso
ln ../Qubes-R3.1-rc3-x86_64.iso.DIGESTS
ln ../Qubes-R3.1-rc3-x86_64.iso.asc
cd ..
mktorrent -a udp://tracker.openbittorrent.com:80 -d -l 20 -v Qubes-R3.1-rc3-x86_64 -w https://mirrors.kernel.org/qubes/iso/ -w https://ftp.qubes-os.org/iso/
rm -r Qubes-R3.1-rc3-x86_64
```

This torrent then gets uploaded next to the ISO file.

Then I should get notified as part of the release process.   I will download the torrent initially over HTTPS, then upload it to my server.  Then my server will download the files listed above via HTTPS, then it will check the checksums, then it will begin seeding automatically.  This is pretty normal.

I bet the above can be automated as part of the (I assume already automated) Qubes release process, even down to sending me a notification to seed the torrent.

**Comment by marmarek** [comment]
> I bet the above can be automated as part of the (I assume already automated) Qubes release process

You'd be surprised here, unfortunately... I think it's time for it.

**Comment by mfc** [comment]
thanks for sharing the steps Rudd-O. just a reminder to add all the open trackers listed in https://github.com/QubesOS/qubes-issues/issues/1245 for redundancy rather than just openbittorrent.com:
```
udp://tracker.torrent.eu.org:451
udp://tracker.coppersurfer.tk:6969
udp://tracker.openbittorrent.com:80
```

**Comment by mfc** [comment]
can be closed now that we have official torrent files listed on the download page: https://www.qubes-os.org/downloads/
