### ISSUE TITLE
Create an option to not automatically start VMs during boot

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1709]
In some cases (mostly buggy firmware/hardware, but not only) system will freeze when starting a VM with some PCI device attached. For example it applies for some Broadcom wireless adapters.
Sometimes a workaround of [enabling permissive mode](https://www.qubes-os.org/doc/assigning-devices/) is enough. Sometimes no simple workaround is possible, but one may decide to simply not use such device (detach it from `sys-net`).
In any case, to implement any solution, user needs to start the system, otherwise changing those options is quite tricky.

I see this as an option on kernel command line option, which could be used as an condition in VM starting services. Then such option could be added from bootloader menu. A catch here: it isn't possible when booting in UEFI mode...

**Comment by unman** [comment]
@andrewdavidwong I Have not been able to test this - please change milestone to 3.2 updates

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
