### ISSUE TITLE
Re-design the graph on the "Counter" page on website

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1711]
Do to [some feedback](https://twitter.com/hashbreaker/status/693137777475608576) on our newly added statistics [counter page](https://www.qubes-os.org/counter/) some refactoring is in order.

- Combine releases older than 3.0 into one value
- Combine 3.0 and 3.1 into one value
- Remove orange "any" line
- Match colors with the rest of our branding
- Change "TOR" to "Tor"

Some additional feedback from a Qubes user / friend (to which I don't know the answer) was:

*"I was wondering, is the shaded part for Tor the number of exit IPs that are getting torified updates? And if so would it be possible to replace it by the estimate for the number of actual Tor users, not Tor exits?"*

Those are the low hanging fruit ideas to improve it. Doing it in SVG in the browser using D3.js would allow for some nicer interactivity and user controlled details!

**Comment by Zrubi** [comment]
I noticed several things about this:

- it is breaks the https page by the plain http insertion of the graph.

- the raw .json data is a way too sophisticated
Even if it is a proper json format, using data as a field name (the
date) is seems a bad idea to me.
The structure is also seems too complicated to me.
I would do some more simple structure like:

{
date: "2016-02",
"any_plain": 1916,
"any_tor": 89,

"r1_plain": 8,
"r1_tor": 0,
"r2_plain": 157,
"r2_tor": 2
..
..
},


Insted of:

  "2016-02": {
    "any": {
      "plain": 1916,
      "tor": 89
    },
    "r1": {
      "plain": 8,
      "tor": 0
    },
    "r2": {
      "plain": 157,
      "tor": 2
    },
    "r2-beta2": {
      "plain": 22,
      "tor": 8
    },
    "r2-beta3": {
      "plain": 7,
      "tor": 0
    },
    "r3.0": {
      "plain": 1164,
      "tor": 45
    },
    "r3.1": {
      "plain": 726,
      "tor": 54
    }
  },


Of course it can be restructured by the app try to use the data - just
need to know if we keep this structure for sure. Asking because I'm
planning to make some more fancy graphs around the raw data.


- the data provided is not consistent.
I mean the "any" numbers are not matching with the sum of the detailed
(release based) numbers.

**Comment by Zrubi** [comment]
> Combine releases older than 3.0 into one value
> Combine 3.0 and 3.1 into one value

I would keep all the major releases - but merge the bata releases for sure.

> Remove orange "any" line

Only if the version bars are stacked.

> Match colors with the rest of our branding

Do we have any? :) I mean is there any Qubes style guide? Or just what we currently see on the main site?

**Comment by Zrubi** [comment]
Do we have any? :) I mean is there any Qubes style guide? Or just what we currently see on the main site?

And I found this:
https://github.com/QubesOS/qubes-issues/issues/1207

@bnvk Do we have the final style guide/template available?

**Comment by andrewdavidwong** [comment]
@marmarek @woju: Is this still an issue?

**Comment by woju** [comment]
Hmm, most of bnvk's points are already done. Format was left as is and I don't want to change it just for sake of changing.

For me, it can be closed.

**Comment by andrewdavidwong** [comment]
@woju: Minor thing I just noticed: It looks like the dates are starting to overlap, which makes them hard to read. Maybe orient the text vertically or diagonally?

**Comment by woju** [comment]
See if you like it now.

Next time (probably in half a year) we'll probably have to join the bars and place labels every 2-3 months or so.

**Comment by andrewdavidwong** [comment]
@woju: Perfect!
