### ISSUE TITLE
qubesos.org should redirect to qubes-os.org

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1718]
Currently, qubesos.org:

* Doesn't redirect to qubes-os.org
* Isn't served over HTTPS

**Comment by marmarek** [comment]
qubesos.org is not owned by us, unfortunately.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
Wow, really? Someone is just voluntarily using it to show the contents of qubes-os.org? (In that case, perhaps they'd be willing to donate it?)

**Comment by marmarek** [comment]
It looks like so. It is done using a frame. I haven't noticed that
forwarding before, but visited it few times in the past. With NoScript
enabled it looks just like an empty page. LOL

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment]
let us hope it is well-intentioned, and not a malware vector... I will reach out to the owner and ask them to donate the domain.

**Comment by mfc** [comment]
I received the contact information for the owner and am reaching out to them directly

**Comment by marmarek** [comment]
Done. We've received the domain from kind Qubes OS fan.
