### ISSUE TITLE
Screen brightness

### ISSUE THREAD

**Issue by JasperWeiss** [QubesOS/qubes-issues#1720]
Screen brightness can't be adjusted. The usual fn+f5/f6 keys don't work. And the screen brightness slider in settings doesn't do anything. Makes using Qubes at night rather uncomfortable. I'm using a Sony Vaio laptop.

**Comment by TNTBOMBOM** [comment]
this is un-related specifically to Qubes. because Qubes using KDE and/or XFCE which both of them arent maintained by Qubes developers. 

so u should contact KDE or XFCE upstream based on which interface that u r using.

**Comment by JasperWeiss** [comment]
All right, thanks. Does Qubes always use the latest version of KDE?

**Comment by TNTBOMBOM** [comment]
if u mean alpha/beta releases the answer is no. but any stable updates yeah sure.

**Comment by marmarek** [comment]
No, we are stuck with KDE 4.14. Upgrade to KDE 5 is non-trivial because
of decoration plugin API change. Details here:
https://groups.google.com/d/msgid/qubes-devel/20150708225129.GN900%40mail-itl

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by TNTBOMBOM** [comment]
aha i c , but if there wasnt any problems for upgrading Qubes to KDE5 then we will upgrade to KDE5 with no problems. which is kinda what i have said but yeah sorry didnt clarify that in my comment.

**Comment by axon-qubes** [comment]
I'm assuming this issue has been resolved based on the lack of recent activity. If not, please feel free to re-open it.
