### ISSUE TITLE
Qubes Manager shows a tooltip relevant to another VM

### ISSUE THREAD

**Issue by Zrubi** [QubesOS/qubes-issues#1731]
As you can see the attached screenshot Qubes Manager shows an error in tooltip relavant to another (non running) VM.
![qubes-manager-tooltip-error](https://cloud.githubusercontent.com/assets/7664714/12907952/ed34d4d4-cef1-11e5-88f9-bd03be83f5bb.png)

Restarting Qubes Manager will clear this fals state.
I can not reproduce - but it happened at least 2nd time when I noticed the bad error tooltip.

I'm running Qubes 3.1 with the latest updates.

**Comment by Zrubi** [comment]
And of course the badly labelled VM is started (and running) fine.

**Comment by Zrubi** [comment]
Correction: not used the latest updates becaue of another issue #1732 
was using qubes-core-dom0-linux 3.1.6

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
