### ISSUE TITLE
simplify using custom kernel [module] installation by installing PV Grub related packages by default

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1738]
The current documentation on custom kernel usage is quite long.
https://www.qubes-os.org/doc/managing-vm-kernel/

It could be made shorter and simpler by installing the related PV Grub (#1354) packages by default inside the templates. Installing custom kernels and custom kernel modules is somewhat a basic feature that is usually simple. Requiring to install extra packages to make that work first is a unpleasant surprise. By installing these packages by default, the required extra template size is justified and we are adhering the principle of least surprise better, thereby improving usability.

packages to be installed by default...

dom 0
- qubes-kernel-vm-support
- grub2-xen

fedora:
- qubes-kernel-vm-support 
- grub2-tools

debian:
- qubes-kernel-vm-support
- grub2-common

This can wait until the PV Grub approach is considered stable. Or at least until these packages flow into Qubes stable repositories. Or at least the likelihood the the mere installation of these packages will not break Qubes for users who do not require this.

Long term this feature would be useful for Qubes-Whonix also. Would simplify installation [instructions for grsecurity kernels](https://www.whonix.org/wiki/Grsecurity) and usage of [grsecurity-installer](https://github.com/Whonix/grsecurity-installer).

**Comment by marmarek** [comment]
Generally moving to PV Grub by default would make some things easier. For example system installed in the template will be much closer to baremetal installation, so all the kernel-related upstream instructions will apply.
I think some (not so strict, but still) requirement is getting rid of / upstreaming `u2mfn` module - the only custom module needed in VM. Otherwise every installation would require compiling that module for whatever kernel is used there (dkms do that automatically, but still it's some inconvenience). See #1654 for details.

**Comment by marmarek** [comment]
Templates for Qubes 4.0 have grub installed by default.
