### ISSUE TITLE
improve user notification of template & admin vm updates 

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1760]
currently the user only knows if there are updates in adminVM (dom0) or a templateVM by looking at the Qube VM Manager. For non-runnings VMs (likely all templateVMs), the user must also un-hide inactive VMs before seeing whether updates are needed.

Instead, there should be a sys-tray notification of a new update as they are found, ideally for:
- admin VM
- any template for which appVMs based on that template are running

**Comment by adrelanos** [comment]
As I heard, this issue might change or vanish with the QVMM usability
revamp.

//cc @bnvk

**Comment by bnvk** [comment]
> Instead, there should be a sys-tray notification of a new update as they are found, ideally for:

Definitely. In GNOME, the [GNotification API](https://developer.gnome.org/GNotification/) allows for notifications to specify "actions" which present buttons to the user inside of the notification. 

> As I heard, this issue might change or vanish with the QVMM usability
revamp. 

My thinking is we move away from this monolithic QVMM window that tries to do *everything* and instead we hook more into relevant desktop interfaces / APIs, thus Template Updates -> Notification Action.

@marmarek what do you think about having a "GNOME" label to assign to issues which signifies "implement this new feature in GNOME only" as per #1806 seems a duplication of work to start trying to implement things in KDE first.

An aside, I got an email saying I had "push" access to this repo but I still can't seem to assign myself to issues / add labels?

**Comment by marmarek** [comment]
> My thinking is we move away from this monolithic QVMM window that tries to do everything and instead we hook more into relevant desktop interfaces / APIs, thus Template Updates -> Notification Action.

Yes, this is good idea to split qubes manager into smaller parts dedicated to precise tasks, using existing APIs etc.

> @marmarek what do you think about having a "GNOME" label to assign to issues which signifies "implement this new feature in GNOME only" as per #1806 seems a duplication of work to start trying to implement things in KDE first.

Actually using proper APIs may mean that the same will work on any desktop environment. For example that thing with actions on notification is a part of standard, also supported in KDE (and used by standard non-Qubes update notification).

> An aside, I got an email saying I had "push" access to this repo but I still can't seem to assign myself to issues / add labels?

It is strange you can't, since I can assign you. Will look into github settings...

**Comment by andrewdavidwong** [comment]
As of 3.2, on Xfce4, there's a notification bubble in the corner of the screen when dom0 updates are available. On my system, this bubble persists until I click it. In order to satisfy the stated requirements of this issue, all we need to do is have a similar bubble appear for TemplateVMs. Would that be consistent with the intent of your proposal, @mfc?

**Comment by mfc** [comment]
yep! either with the logic of focusing on TemplateVMs that currently running appvms are based on (e.g. "hey this thing you are using has updates"), or just any TemplateVM.

**Comment by jpouellet** [comment]
@andrewdavidwong @marmarta -- can this be closed since we have the updates widget now?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong @marmarta -- can this be closed since we have the updates widget now?

Yes, I believe the update widget satisfies the original request.
