### ISSUE TITLE
"NetVM" -> "Networking" in VM Settings

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1763]
use of the term "NetVM" in VM Settings > Basic for the settings of an AppVM is confusing because the "NetVM" could be a ProxyVM.

**Comment by axon-qubes** [comment]
I think it's actually a more general problem with the way the term "NetVM" is used in Qubes OS. It has at least two distinct meanings:

1. A type of VM which provides network access (usually directly to ProxyVMs and indirectly to AppVMs).
2. Whichever VM is directly connected to a VM for networking purposes (even if it's a ProxyVM!).

Imagine the following exchange:
A: "`sys-firewall` is this VM's NetVM."
B: "So `sys-firewall` is a NetVM?"
A: "No, it's a ProxyVM."
B: "But you just said that it's this VM's NetVM!"
A: "Well, yes, it's *this VM's* NetVM, but it's not *itself* a NetVM."
[*B glares menacingly at A.*]

(We've already made good progress on eliminating ambiguity here by changing `netvm` to `sys-net`.)

**Comment by axon-qubes** [comment]
BTW, I didn't mean to sound like I disagree with you, @mfc. I do agree with you. I just think that we would also have to disambiguate and decompose the term "NetVM" throughout Qubes OS (and the docs) to really fix this. It's not a big deal and not urgent, but it's something we should be aware of, I think.

**Comment by mfc** [comment]
I agree with you so let's find those instances where it is the second case and disambiguate (like in this instance I proposed). if we can find them we can fix them :)

**Comment by Zrubi** [comment]
I would use the word 'router' or 'uplink'  for the 2. case - instead of the current 'NetVM'

**Comment by marmarek** [comment]
I like 'uplink', or maybe even 'network uplink'? Any idea for one
word related to both 'network' and 'uplink'? Is 'uplink' clearly enough
related to network for average user?

@bnvk

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment]
I don't think "uplink" is understood by average users unfortunately. The other categories in this settings page (VM Settings > Basic) are descriptive: "Name and Label", "Template". I feel like "Networking" is similarly descriptive. If it is selected as "none", the user knows "there is no networking for this qube", which feels more natural to say/understand than "there is no uplink for this qube".

**Comment by marmarek** [comment]
On Thu, Feb 25, 2016 at 03:21:58AM -0800, Michael Carbone wrote:
> I don't think "uplink" is understood by average users unfortunately. The other categories in this settings page (VM Settings > Basic) are descriptive: "Name and Label", "Template". I feel like "Networking" is similarly descriptive. If it is selected as "none", the user knows "there is no networking for this qube", which feels more natural to say/understand than "there is no uplink for this qube".

I think that may be good option in "VM setting" window. See what it
would look like:
Networking:
 - network
 - firewall
 - tor
 - usb
 - none

Maybe worth explanation somewhere what is the difference between
"network" and "firewall". But generally looks good.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by bnvk** [comment]
Why is `usb` in this list? Seems like that should go under a different category like **Devices** to me. I added `vpn` in it's place, as that is a term + thing users are starting to understand / use to some degree!

Networking:
- network
- firewall
- tor
- vpn
- none

I've been thinking for awhile, GUI wise, we should separate out Networking away from the other VMs. I should finish some design comps to better explain this!

**Comment by marmarek** [comment]
On Thu, Feb 25, 2016 at 05:13:45AM -0800, Brennan Novak wrote:
> Why is `usb` in this list? Seems like that should go under a different category like **Devices** to me. 

Because USB VM is created as NetVM type. To be able to use USB network
devices (3G modems and such).

In 4.0 there will be no longer separate "NetVM type". There will be
"provides network" (switchable) property. So it should be much clearer
then.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment]
maybe have it be called `usb-modem`?

**Comment by marmarek** [comment]
On Thu, Feb 25, 2016 at 06:37:27AM -0800, Michael Carbone wrote:
> maybe have it be called `usb-modem`?

That would be misleading even further. USB VM is where you have USB
controllers. Whatever is plugged in there.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
> I like 'uplink', or maybe even 'network uplink'? Any idea for one word related to both 'network' and 'uplink'? Is 'uplink' clearly enough related to network for average user?

Maybe "connection"?

**Comment by mfc** [comment]
"connection", "networking", "network connection", all are fine. any are disambiguous compared to "NetVM".

**Comment by tasket** [comment]
I think 'uplink' is best because it will stick no matter how novice or technical the howto or conversation is. In the technical case, you are now having to distinguish between eth0, vif*, tun*, etc. You can use terms like 'uplink', 'downlink' or 'downstream' together without the confusion that 'connection' would bring.

We have to think about whether these terms retain their meaning when writing instructions for users of different technical ability.

**Comment by marmarek** [comment]
See https://github.com/QubesOS/qubes-issues/issues/1763#issuecomment-188737737

**Comment by tasket** [comment]
If terms like 'uplink' and 'downlink' are unpalatable (though it seems like they are descriptive enough to give users the right idea) then I'd suggest borrowing terminology of common consumer routers, which are things that people have to deal with already. This is apt because service VMs are virtual routers. They often call the uplink ports "WAN" or "Internet".

**Comment by andrewdavidwong** [comment]
Based on this discussion, I think further UX improvement is still needed:

https://groups.google.com/d/topic/qubes-users/3yijlzrNjEQ/discussion

**Comment by mfc** [comment]
yes this seems to have been changed at some point: in Qube Settings, it now says "Networking:" so seems to have been solved :)

**Comment by andrewdavidwong** [comment]
Oh, I completely forgot about this issue. I actually just submitted a PR to change several remaining instances of "NetVM" to "net qube" in GUIs and also changed it in the glossary.

**Comment by mfc** [comment]
hmm but "net" is not an abbreviation for "networking", it is an abbreviation for "internet". since we are trying to disambiguate and make more clear the language we use (both for users and for localization) can you make sure to use "networking qube"? and in the context you are using it see if having "qube" is necessary or redundant.

Sep 9, 2021 01:02:53 Andrew David Wong ***@***.***>:

**Comment by andrewdavidwong** [comment]
> hmm but "net" is not an abbreviation for "networking", it is an abbreviation for "internet". 

Erm, "Inter**net**" is short for "inter**network**":

https://en.wikipedia.org/wiki/Internet#Terminology

> since we are trying to disambiguate and make more clear the language we use (both for users and for localization) can you make sure to use "networking qube"?

Eh, I'm not sold on "networking qube" being better. At any rate, my only goal with these recent changes was to (1) eliminate the use of "VM" in "NetVM" and (2) eliminate inconsistency (sometimes using "NetVM" and sometimes using "Networking" to refer to the same thing, for example). Now that it's (hopefully) consistent, we can make further iterative improvements. If "networking qube" really is better than "net qube" (I have a feeling many who have objected to other long terms will also object to this one), then we can make that change, but I sense another holy war starting...

> and in the context you are using it see if having "qube" is necessary or redundant.

Of course, but it's difficult to think of a context in which we can refer to a qube without calling it a qube.

Actually, the really weird thing about "NetVM"/"net qube" is that it's technically a *property*, not a type of qube, but trying to enforce that seems like a lost cause.

**Comment by mfc** [comment]
> Actually, the really weird thing about "NetVM"/"net qube" is that it's technically a /property/, not a type of qube, but trying to enforce that seems like a lost cause.

yes, that's why "networking" fits. it is the current implementation in Qube Settings.

>
> Erm, "Inter*net*" is short for "inter*network*"


so you are arguing people say: "what net does this qube have"?

the point of this issue was to get rid of abbreviations. i hope it's clear the benefit of not using abbreviations? that these abbreviations are also nonstandard english (or, not typical/expected abbreviations) should be a further reason to get rid of them.

Sep 9, 2021 16:36:26 Andrew David Wong ***@***.***>:

**Comment by andrewdavidwong** [comment]
> the point of this issue was to get rid of abbreviations.

I think you're misunderstanding what's happening here. I never claimed to be working on this issue. I didn't close it. I didn't claim that my changes resolved it.

All I did was point out that I had completely forgotten that it existed until the recent activity and that, coincidentally, I had recently submitted a PR and made a doc update eliminating the term "NetVM."

In fact, now that I review my changes again, I actually replaced "NetVM" with "networking" in a few cases where contextually appropriate, which is what you want, and in no case did I replace "networking" with "net." **I am the one helping you achieve your goals!**

You are upset with me because I have not done *even more* to further your goals, when in fact I never set out to do so and never agreed to shoulder that commitment.

**Comment by andrewdavidwong** [comment]
>> hmm but "net" is not an abbreviation for "networking", it is an abbreviation for "internet".
> 
> Erm, "Internet" is short for "internetwork":
> 
> https://en.wikipedia.org/wiki/Internet#Terminology

Another data point to consider:

https://www.dictionary.com/browse/net
_noun
7. any network or reticulated system of filaments, lines, veins, or the like.
8. Telecommunications. any network containing computers and telecommunications equipment.
9. Sometimes Net .Digital Technology. internet (preceded by the, except when used before a noun)_

So, the use of "net" to mean "network" is well-established, even independently of the word "Internet."

> so you are arguing people say: "what net does this qube have"?

Obviously not, because it's "net qube," not just "net." People absolutely do say "what netvm does this qube have," and replacing "netvm" with "net qube" results in: "what net qube does this qube have."

People *don't* say, "what networking does this qube have." That wouldn't really make sense. It would be, at best, very casual slang usage and, at worst, broken English.

**Comment by mfc** [comment]
hey i'm not upset so sorry it's being read that way.

i didn't see (wasn't referenced) your related commits so i just replied as generally as possible.

i think using general terminology where possible ("networking" vs "netvm" or "net qube") results in lower barrier to user understanding, easier localization, and it sounds like you agree. so all good!

Sep 9, 2021 17:33:49 Andrew David Wong ***@***.***>:

**Comment by ninavizz** [comment]
Amusingly timely discussion—just had a loooong call with a trainer, desiring more visibility into generalized networking stuff in Qubes. Glad we're calling it "internet" and no longer "net vm."
