### ISSUE TITLE
Copy/generate VM icon instead of using symlink

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1770]
As reported by other users:
https://groups.google.com/d/msg/qubes-users/2h2ASFZDDEA/RKVd5O4MBgAJ

the initial issue was a broken syslink `icon.png` in the root folder of the TemplateVM `/var/lib/qubes/appvms/[vmname]/icon.png`. In this case it was pointing to `vm49/vm9/vm41//usr/share/qubes/icons/template.png`.

Attempting to fix the link to `/usr/share/qubes/icons/template.png` by running `ln -sf /usr/share/qubes/icons/template.png /var/lib/qubes/vm-templates/[vmname]/icon.png` doesn't work cleanly because `/usr/share/qubes/icons/template.png` doesn't exist.

However, some TemplateVMs with broken symlinks I was able to back-up, they did not have the vm# gunk in front of their broken `/usr/share/qubes/icons/template.png` symlink. Other times they would need to be pointed to someplace that exists, like `/usr/share/qubes/icons/black.png`

TemplateVMs affected include fresh, untouched R3.1rc2 Debian 8 and Fedora 23 TemplateVMs and modified TemplateVMs.

this fix https://github.com/QubesOS/qubes-issues/issues/1515 for dom0 does not help since these are issues faced when backing up TemplateVMs.

**Comment by marmarek** [comment]
I think the ultimate solution for this problem, is getting rid of this
symlink completely and simply copy the icon file there. That symlink was
source of other problems too (for example KDE icon cache sometimes
doesn't notice the change).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment]
yes please do :)
