### ISSUE TITLE
change default appvm name: anon-whonix -> anonymous-browsing

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1775]
we need to stop using non-intuitive abbreviations, which are:
- confusing for new users
- bad for localization/translation (directly or in documentation)

"whonix" is not a meaningful domain / use-case, unlike "vault" etc. I suggest the default whonix-ws template-based appvm be called "anonymous-browsing" or "anonymous-web" or similar.

**Comment by adrelanos** [comment]
If anything, I prefer anonymous-web since it is a bit more generic. Or
perhaps anonymous-internet.

**Comment by axon-qubes** [comment]
What exactly is the significance of default VM names, given that users are free to change the name of any VM? I understand these:

* Comprehensibility to new users
* Use in documentation (incl. translation)
* Common reference standard

But are there actually security/privacy implications? For example, if I rename my VM from the default `anonymous-web` to `anon-web` because I prefer shorter names, will I now "stand out" or be more fingerprintable? Or is this solely about first impressions on users?

**Comment by adrelanos** [comment]
Axon:
> What exactly is the significance of default VM names, given that users are free to change the name of any VM? I understand these:
> 
> * Comprehensibility to new users
> * Use in documentation (incl. translation)
> * Common reference standard

Right.

> But are there actually security/privacy implications? For example, if I rename my VM from the default `anonymous-web` to `anon-web` because I prefer shorter names, will I now "stand out" or be more fingerprintable? Or is this solely about first impressions on users?

Short:
For all practical purposes the VM name does not matter.

**Comment by adrelanos** [comment]
I think it's a bad idea. It's not an anonymous-browsing or anonymous-internet VM. It's a Whonix-Workstation VM. It can be used for anonymous browsing/internet given the right knowledge and behavior.

* Quote: "am i completely anonymized if i log onto my facebook account?"
* https://www.whonix.org/wiki/DoNot#Login_into_your_real_life_Facebook_account_and_think_you_are_anonymous
* https://github.com/QubesOS/qubes-issues/issues/1777#issuecomment-189201185
* [a browser is not a safe environment to type](https://www.whonix.org/blog/browser-not-safe-for-typing)
* [Anonymous Photo Sharing](https://www.whonix.org/wiki/Surfing_Posting_Blogging#Anonymous_Photo_Sharing)
* [Metadata](https://www.whonix.org/wiki/Metadata)
* and more... ([Documentation](https://www.whonix.org/wiki/Documentation))

I know you want to simplify it, but I don't think this kind of simplicity is possible with the resources that we have. Just implying, 'here is your anonymous browser now do whatever you want' will get users in trouble since we are far from being able to deliver such an experience. We, as in the whole anonymity ecosystem, would have to solve many hard technical problems. A few...

* When the user is typing [Anti-Keystroke Fingerprinting (#1850)], don't have him type in the actual VM. Do the typing in another VM.
* Then defeat stylometry (deanonymization using your spelling style). Have some usable writing style anonymization tool (that does not exist yet) integrate well.
* When adding files, don't add them to the VM. Have them added to an intermediary VM first. Have the documentation integrate and pop up exactly in that moment to educate about this. Offer to clean the metadata (make that actually work reliably).
* Relay the final anonymized user work result back to the actual VM.

**Comment by andrewdavidwong** [comment]
It appears that the debate on this matter is settled. Closing as `notanissue`.
