### ISSUE TITLE
Windows7 HVM: Cannot Mount or Attach USB Devices

### ISSUE THREAD

**Issue by dfirence** [QubesOS/qubes-issues#1783]
Hi,

Thank you for this awesome project.  My main use-case for Qubes is to be able to virtualize Windows 7 VMs.  Everything is working fine except successfully Attaching USB Devices. Unfortunately, this is a show stopper for me :-(

My Software:
1. QUBES R3.1.rc2 64 bit
2. Windows 7 64 Bit SP1 Professional
3. Qubes Windows Tools installed from your testing repo

---

My Problem:
1. I **cannot see** the attached USB or its contents in my Windows7 HVM.  I can attach it via CLI and the VM Manager GUI, but I never see the USB device within the Windows OS.

I **can attach** the USB Device on other VMs like personal, work and access it's contents via Nautilus file manager.  I can't see the USB mounted on the Windows 7_x64_SP1 HVM I created

---

What I have done:
1.  I have used your recommended steps via CLI with QVM-BLOCK.  Here's the output when I run.
     (attached to 'windows7' as 'xvdi')
1.  I have tried attaching the USB drive from the GUI VM Manager.  When I do so, I can see the USB is mounted as:
   (attached to 'windows7' as 'xvdi')

I have followed your Documentation steps here:
- https://www.qubes-os.org/doc/usb/
- https://groups.google.com/forum/#!topic/qubes-users/ZNKfCxWQB2U

---

Your help is greatly appreciated for me to continue on this QUBES Journey :)

**Comment by marmarek** [comment]
Unfortunately this probably will not work in the near future. This is one of known issues listed here: https://www.qubes-os.org/doc/releases/3.1/release-notes/
Technically the problem is with Xen block frontend driver (PV disk driver), or its integration into Qubes Windows Tools. The result is random BSODs and/or data corruption. So in default installation this driver is disabled. But without this driver, dynamic block devices can't work.
One workaround is to attach such devices before VM startup (VM settings - advanced tab, or `qvm-start --hddisk` option). But that may mean a lot of VM restarts (to change that device).

**Comment by abbluiz** [comment]
Am I correct to assume that using `qvm-start --hddisk` will always mount the device as an internal hard drive? Or is there a way to mount it as "removable media"?

**Comment by brendanhoar** [comment]
For Qubes 4.1 (presumably utilizing Xen 4.12) is it possible that the Xen frontend (PV disk driver) is stable enough in that Xen release to be enabled by default?

**Comment by marmarek** [comment]
Xen version should be irrelevant here, only PV drivers version should matter. And maybe installed windows updates. You can try with PV drivers 8.2.2 from [here](https://xenproject.org/downloads/windows-pv-drivers/windows-pv-drivers-8-series/windows-pv-drivers-8-2-2/) - I think our current build has 8.2.1.

**Comment by elliotkillick** [comment]
Xen PV drivers 9.0.0 have recently been released. See [here](https://xenproject.org/downloads/windows-pv-drivers/windows-pv-drivers-9-series/windows-pv-drivers-9-0-0/).

**Comment by cbmiller2610** [comment]
Has anyone been able to successfully use the 9.0.0 drivers and be able to pass through a USB device? I installed Windows 10 with QWT and am getting the error "Device attach failed: Failed to open data vchan connection" when I use qvm-usb attach to try to pass through a device.

**Comment by v6ak** [comment]
When the issue title mentions USB, this is rather about block devices
(regardless they originate from a USB, iso file or whatever else) than
about USB.

**Comment by cbmiller2610** [comment]
Ah, understood. I'll look elsewhere to ask, since my question is about general pass-through.

**Comment by aronowski** [comment]
A workaround has been available and described in the Community Documentation since Oct 7, 2022:
https://github.com/Qubes-Community/Contents/commit/d63b9adc36d66f32de9ca181ff8fae47849cdc10

@dfirence, while this is not an official solution, you can take a look if you still consider the goal described in the issue's introductory post.

**Comment by dfirence** [comment]
Thanks, been too long since opened.
