### ISSUE TITLE
Tor Browser in whonix-ws should have default Tor Browser welcome page

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1790]
We have worked hard to have the exact same Tor Browser in Qubes that exists elsewhere in linux, not modified like in Tails, etc.

Modifying the welcome page to instead be the Whonix welcome page is confusing to users because they have just opened the Tor Browser, not Whonix OS. They will think it has been modified, not understand what Whonix OS means (since they have opened a browser, not an OS).

**Comment by marmarek** [comment]
I think this is bad idea, hiding the fact it is Whonix-workstation, taking away credits from Whonix project.
This nothing surprising that default home page is set to vendor specific page, users are used to it. See for example Firefox in Fedora - home page is set to https://start.fedoraproject.org/
cc @adrelanos

**Comment by mfc** [comment]
The fact that it is a whonix-ws is not hidden from the user at all, that type of information already exists in the whonix-ws in: Documentation, Donate, Whonix Blog, Whonix Feature Blog, WhonixForum, Contribute, etc. 

That information could also exist in the Help that is currently pre-populated in every AppVM created, and currently does not contain any Qubes or Whonix-specific context. perhaps a place for https://github.com/QubesOS/qubes-issues/issues/1019

An application whose users are very wary of it being modified is not the right place to put that information. I've had to explain to some new Qubes users who were confused about what Whonix was "doing" to the Tor Browser (or if it was different) since it was branded. One of the selling points of Whonix actually is that it is vanilla Tor Browser not modified in any way (no adblocker added, etc).

Branding the Firefox start page is not the same as branding the Tor Browser start page due to the unique security/privacy concerns with Tor Browser, and it not being the right place for this type of information.

**Comment by adrelanos** [comment]
> The fact that it is a whonix-ws is not hidden from the user at all, that type of information already exists in the whonix-ws in: Documentation, Donate, Whonix Blog, Whonix Feature Blog, WhonixForum, Contribute, etc. 

These have been removed by default.
[ Only images that were upgraded will keep those. (As a matter of of a hard-to-solve-wontfix Qubes specific issue.) ]

-----

Is the about:tor page less confusing than the Whonix browser welcome page? With links to:

- Run a Tor Relay Node (that won't work as is in Qubes because you would need Qubes specific port forwarding into the VM)
- Volunteer Your Services (to The Tor Project)
- Make a Donation (to The Tor Project)

It's not just the Tor Browser. It's the Tor Browser in Whonix.

Is Whonix is an advertised feature of Qubes? It was "port Whonix to Qubes", that we have now, but not it's morphing into more like "have something underlying using Whonix but totally avoid mentioning Whonix"?

It's good to know for users that they are using Whonix, because for any questions they have these get redirected to Whonix [documentation](https://www.whonix.org/wiki/Documentation) and [support](https://www.whonix.org/wiki/Support).

**Comment by mfc** [comment]
> These have been removed by default.

okay I wasn't aware of that.

> Is the about:tor page less confusing than the Whonix browser welcome page? 

Yes, because the about:tor describes what the Tor Browser is, I think that's pretty useful information for a user. maybe the whonix page can also describe what it is to the user, as you have just done.

Apologies if the suggestion came off as rude, I'm just trying to think of ways to create a more uniform user experience. Maybe we should go the opposite direction and brand the Firefox in Fedora & Debian templates, it's weird to have some browsers be branded and some not. I've created #2006 to track this.
