### ISSUE TITLE
DVM savefile creation failed error from low/fragmented RAM

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#1792]
When starting a dispvm the savefile creation process sometimes fails due to low or fragmented memory. However, the displayed error does not give any hint there is a memory issue. It would be better to tell the user about the memory condition.

**Comment by marmarek** [comment]
Are you sure about "fragmented memory" case? It shouldn't affect VM without PCI devices.

**Comment by ttasket** [comment]
No. "Fragmented" is just an assumption because dom0 shows some large amount of memory in Manager.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
