### ISSUE TITLE
sys-net phones home to fedoraproject.org for captive portal detection

### ISSUE THREAD

**Issue by hdevalence** [QubesOS/qubes-issues#1814]
When connecting to some WiFi networks, e.g., open networks, sys-net phones home to fedoraproject.org:

```
sys-net NetworkManager[551]: <info>  connectivity: check for uri 'http://fedoraproject.org/static/hotspot.txt' returned status '302 Moved Temporarily'; assuming captive portal.
```

It would be good to discuss whether this is desired behaviour and whether there's a better way to deal with captive portals in Qubes (e.g., testing random domains).

**Comment by hdevalence** [comment]
Another interesting idea would be to integrate captive portal detection with a Qubes DispVM system, so that when a captive portal is detected, Qubes could launch Firefox in a DispVM to do the login. Maybe that should be a different ticket?

**Comment by marmarek** [comment]
As for connectivity check, you can disable it by removing `NetworkManager-config-connectivity-fedora` package. Indeed it may be a good option to not install it at all by default.

As for captive portal handling, it it interesting idea, worth a separate ticket and/or discussion on qubes-devel mailing list.

**Comment by 0x27** [comment]
Perhaps it might be better to see what it is that the Subgraph people are doing with their Captive Portal detector/dealwith contraption and integrate that?

Integrating their automatic MAC changer might be another cool thing to do as an optional NetVM accessory for bonus privacy.

**Comment by cfcs** [comment]
"Captive portal detection" is inherently going to connect back to /something/. I think we should make it an install-time option (before we enable the network).

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by cfcs** [comment]
@marmarek do you know if this is different in the `sys-net` template for `4.1`?

**Comment by marmarek** [comment]
Probably the same, according to our policy: https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros

**Comment by cfcs** [comment]
In that case maybe we should consider reopening this issue @andrewdavidwong ?

**Comment by andrewdavidwong** [comment]
> Probably the same, according to our policy: https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros

> In that case maybe we should consider reopening this issue @andrewdavidwong ?

According to the policy @marmarek linked, it looks like this is `not our bug`. In that case, this issue should stay closed, and the bug should be reported to the Fedora Project.

**Comment by cfcs** [comment]
@andrewdavidwong It's not their bug, it's their spyware feature. :)

**Comment by adrelanos** [comment]
I cannot find this log message in my sys-net journal log even though connected to a private WiFi. But I am not sure how to reproduce this. Probably to be expected, because...

> As for connectivity check, you can disable it by removing `NetworkManager-config-connectivity-fedora` package. Indeed it may be a good option to not install it at all by default.

That package is no longer installed by default in `fedora-35` by looking at `dnf list installed | grep -i connectivity`. Installation would be possible using `sudo dnf install NetworkManager-config-connectivity-fedora` which is further conformation that it is no longer installed by default.

Seems like this fixed itself.

What's missing is a Qubes openQA test which shows an error should the package `NetworkManager-config-connectivity-fedora` get re-introduced into the default installation at some point.
