### ISSUE TITLE
Implement new firewall dom0->VM interface

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1815]
This is placeholder for the outcome of this discussion: https://groups.google.com/d/msgid/qubes-devel/20160114163808.GW4892%40mail-itl

**Comment by adrelanos** [comment]
The outcome is... [Quote](https://forums.whonix.org/t/sys-whonix-does-not-yet-function-was-qubes-firewallvm/2239/4?u=patrick) @marmarek:

> 1. have updates proxy running over qrexec instead of TCP/IP, so template will not have its own netvm at all [comment by me: --> will edit soon to add ticket]
> 2. ease integration of "qubes firewall rules" with other firewalls (like Whonix one) [comment by me: this ticket]

**Comment by andrewdavidwong** [comment]
Questions pertaining to using Whonix with firewall rules keep coming up, so I'm providing a response here, so that I can direct people to this issue:

Whonix-Gateway does not currently support firewall rules. This is a known issue, which I brought up [here](https://groups.google.com/d/topic/qubes-users/PAnwbpdP-jI/discussion) and [here](https://forums.whonix.org/t/how-to-add-a-proxyvm-between-anon-whonix-and-sys-whonix-whonix-ws-email-sys-fw-whonix-whonix-gw-sys-firewall-sys-net/2238), which branched off [here](https://forums.whonix.org/t/sys-whonix-does-not-yet-function-was-qubes-firewallvm/2239) and is being tracked in #1815 (this issue) and [here](https://phabricator.whonix.org/T476).

Short answer: For now, there's no way to enforce firewall rules for a VM using a `whonix-gw` as its NetVM, but a solution is in the works.

**Comment by marmarek** [comment]
I've documented new (yet to be implemented) interface for firewall rules:
https://www.qubes-os.org/doc/vm-interface/

As for implementation (in the VM), I plan to replace current iptables-based `qubes-firewall` script, with [nftables](http://wiki.nftables.org/) one. Thanks to independent tables it will allow to avoid interference between different firewall tools. For example it will allow to respect those rules by Whonix Gateway, without breaking Whonix firewall.
This is somehow extended idea of #974 
/cc @adrelanos

**Comment by ubestemt** [comment]
Shouldn't a warning be displayed when using sys-whonix as NetVM and opening the Firewall tab in VM Preferences, just like it is when sys-net is used as NetVM? Otherwise, how will the average user know?

**Comment by andrewdavidwong** [comment]
> Shouldn't a warning be displayed when using sys-whonix as NetVM and opening the Firewall tab in VM Preferences, just like it is when sys-net is used as NetVM? Otherwise, how will the average user know?

Sounds like this is covered by #2003.
