### ISSUE TITLE
Qubes checks for dom0 updates in sys-net even when that's not the UpdateVM

### ISSUE THREAD

**Issue by hdevalence** [QubesOS/qubes-issues#1851]
I have Qubes configured with a custom UpdateVM. However, I notice that tinyproxy is making connections out of sys-net to check for dom0 updates, even though it's not set as the UpdateVM.

**Comment by marmarek** [comment]
On Thu, Mar 17, 2016 at 02:49:07PM -0700, Henry de Valence wrote:
> I have Qubes configured with a custom UpdateVM. However, I notice that tinyproxy is making connections out of sys-net to check for dom0 updates, even though it's not set as the UpdateVM.

Are you sure it's about dom0 updates, not VM updates (when you update
some of your templates)? The tinyproxy in sys-net is used for VM
updates.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by hdevalence** [comment]
I'm not sure what's using it as an update proxy, but something is, even though I set the UpdateVM to something else.

I am pretty sure that it's not template updates since those run through the UpdateVM I set.

**Comment by axon-qubes** [comment]
I'm assuming this issue has been resolved based on the lack of recent activity. If not, please feel free to re-open it.
