### ISSUE TITLE
Documentation: Improve 'How is Qubes Different' description

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#1860]
I keep hearing (even from technical people) that Qubes is just a nice convenient packaging of Xen or other Linux/hypervisor combination. It would benefit Qubes' image to hone the Tour page by enhancing the section comparing Qubes to other VMs on other systems. More detail and emphasis should be given to the _graphics and clipboard isolation_ , as well as other ITL-developed code that enhances security in ways that isn't reproducible by assembling the right packages and configuration options in a regular OS.

I used to refer people to Joanna's blog post 'How is Qubes OS different from...', but even when "trusted window manager" is mentioned, it is presented in terms of usability and not the added security of graphics isolation.

**Comment by axon-qubes** [comment]
Sounds good to me. The Tour might not be the optimal place for a *comprehensive* explanation of how Qubes is different from everything else, since that aims to be simple and short, but we can certainly include the highlights there, then perhaps link to a dedicated page.

@rootkovska, @marmarek: Any specific technical points we should make sure to mention?

**Comment by ttasket** [comment]
I think a full sentence or two at that point in the Tour would be optimal; perhaps as its own paragraph because of its significance.

**Comment by andrewdavidwong** [comment]
I updated the page for this a while back but forgot to close this issue from the commit message. If you still think further edits are required, please feel free to submit a PR, comment, or re-open.
