### ISSUE TITLE
Implement UI Notifications for cases of a Qube disk full

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1872]
Currently, one only realizes that a Qube is full usually after some other operation (downloading, installing) fails. We should surface notifications to users when a Qube is
- 75% full
- 85% full
- 90% full

These should be system notifications that provide an actionable button that takes user to the Qubes Manager for that given Qube. 

Additionally, there is the case where the sum total of "potential disk space allowed" for all Qubes, might be greater than that of the actual physical hard drive. In the case that this limit is actually reached @marmarek and @woju claim that all information about a users Qubes is erased. This of course is very bad for users and should be mitigated by not allowing a user to set each Qube to larger than total available space.

**Comment by marmarek** [comment]
Related to #1053

**Comment by tasket** [comment]
This could be quickly done in 4.0 if its added to @marmarta 's disk space widget, or just made into a cron job or systemd timer.

I'll also suggest expanding this function beyond a warning:

Perhaps pausing domUs if the storage pool (containing admin root) free space goes below a certain number. It could even un-pause automatically once enough space has been freed. I don't know if Linux offers a better way to handle this (i.e. an LVM feature that can reserve space in a pool for a particular LV)... open to suggestions.

**Comment by marmarek** [comment]
> I don't know if Linux offers a better way to handle this (i.e. an LVM feature that can reserve space in a pool for a particular LV)... open to suggestions.

This is very similar to what we've discussed in https://github.com/QubesOS/qubes-issues/issues/3226#issuecomment-374076605

As for pausing qubes, this may be tricky. Imagine someone using USB keyboard, or just yubi key for screen unlock. Pausing sys-usb in that case would be bad...

**Comment by tasket** [comment]
Probably could make an exception for sys-usb, which isn't expected to command a large private volume anyway.

**Comment by tasket** [comment]
BTW, was referring to current arrangement with dom0 in thin pool in 3226.

**Comment by tasket** [comment]
Note: dom0 has dm-event.service which runs `dmeventd`. This supposedly monitors thin pools for the amount of space left and will log warnings (and even try to dismount member volumes) at certain percentage thresholds.

Monitoring this log output (via `rsyslogd`?) may be one way to implement notifications/pausing. But I still think using the widget is a good option, especially since it can be applied uniformly to the other storage types.

**Comment by marmarek** [comment]
Notification + widget implemented as part of https://github.com/QubesOS/qubes-issues/issues/3240

Safeguards against filling up pool where dom0 root lives would be much easier to implement in 4.1, where GUI will be moved out - no direct user interaction with dom0, can be much smaller, static volume.

**Comment by andrewdavidwong** [comment]
Reopening due to #4404. Either there is more that needs to be implemented here, or it is not easily discoverable (UX issue).

**Comment by marmarek** [comment]
Actual notifications (besides icon color change) are done in package in current-testing: https://github.com/QubesOS/updates-status/issues/741

**Comment by andrewdavidwong** [comment]
> Actual notifications (besides icon color change) are done in package in current-testing: QubesOS/updates-status#741

FYI @brendanhoar. Please consider helping us test this, if you can.

**Comment by brendanhoar** [comment]
It wasn't clear to me from the thread, and it might only be because I'm think headed...but I will ask specifically:

Is the idea of having dom0 (and perhaps management/GUI VMs) be located in a separate LVM pool ("system" LVM pool) than most of the other VMs ("user" LVM pool) being considered? 

I think that makes it less likely that dom0 will fail to start up and gives users additional recovery flexibility if there are issues with the "user" LVM pool. Proper log rotation, etc. would of course be key in dom0 to keep it semi-clean and below a certain %age of the "system" LVM pool...

Brendan

**Comment by brendanhoar** [comment]
Update: it appears that 4.1 will use two pools by default: one (smaller) pool for dom0 use, one (larger) pool for all VMs.

This means that if the VM-containing pool has issues, dom0 may still be booted and utilized to fix the VM pool. Esp. if https://github.com/QubesOS/qubes-issues/issues/5820 is addressed. :)

**Comment by marmarta** [comment]
So, notifications for lvm pools being close to full are implemented already, I've just pushed a commit that will also notify about VM volumes being close to full. Is there anything else we should do here?

**Comment by andrewdavidwong** [comment]
Looks good to me, @marmarta. If anyone feels that more should be done here, please leave a comment.
