### ISSUE TITLE
Add field for VM Icon

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1873]
Similar to #899 it would be useful (for GUI) users to have intelligent "auto chosen" icons for each Qube, so `Vault => Lock Icon` or `Web Browsing => Globe Icon` as well as provide the ability for a user to choose an icon of their choice for a Qube

**Comment by marmarek** [comment]
@woju how do you see this? Some ideas:
 - use whatever icon is in VM directory - then new Qubes Manager can simply replace it
 - add a second icon file (source icon), then have the current icon being colored version of that source icon
 - similar to the above, but keep only path/name of the source icon (as VM property)

Question: should this icon be colored to VM color, or used as-is?

**Comment by woju** [comment]
On Thu, Mar 24, 2016 at 08:37:28AM -0700, Marek Marczykowski-Górecki wrote:
> @woju how do you see this? Some ideas:
>  - use whatever icon is in VM directory - then new Qubes Manager can simply replace it
>  - add a second icon file (source icon), then have the current icon being colored version of that source icon
>  - similar to the above, but keep only path/name of the source icon (as VM property)

I think we should ultimately place the processed icon in the VM
directory, however the Qubes Manager shouldn't mess with that icon
directly... There should be API and/or CLI tool for this. The source
icon should also be copied there, because user may change the colour
of the label after setting the icon. Possibly reflinked, but hardlinked
only if selected from a default set, which we should provide.

Correct me if I'm wrong, but I imagine that there will be some dialog
similar to "pick image for upload". User may then remove the icon (since
it was probably downloaded from the Internet and the dialog was really
in some VM).

> Question: should this icon be colored to VM color, or used as-is?

I think it should be coloured according to the label, because it gets
used as default window icon if there is no icon extracted from inside of
the VM. However we may have an exception for some stock icons we will
provide. We may generate them on the fly, using colour as input
parameter.


-- 
pozdrawiam / best regards       _.-._
Wojtek Porczyk               .-^'   '^-.
Invisible Things Lab         |'-.-^-.-'|
                             |  |   |  |
 I do not fear computers,    |  '-.-'  |
 I fear lack of them.        '-._ :  ,-'
    -- Isaac Asimov             `^-^-_>

**Comment by marmarta** [comment]
I think that given various developments such as https://github.com/QubesOS/qubes-issues/issues/5676 (and the whole idea of giving different types of VMs different icons), we can safely say this is not the direction we want to go in.
