### ISSUE TITLE
Clarify "certified" status of Purism Librem laptops

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1902]
* Why is the Librem 13 "Qubes-certified," but the Librem 15 [apparently is not](https://www.qubes-os.org/doc/certified-laptops/) even though both have the option to ship with Qubes pre-installed?
 * What exactly does it mean to say that these laptops are "Qubes-certified"? We [say](https://www.qubes-os.org/doc/certified-laptops/), "Qubes-certified laptops are laptops that have been tested by the Qubes developers to ensure compatibility with all of Qubes’ features." But is that really true? If so, why are there so few/old HCL entries for these laptops, and none with all-green cells?
 * I thought Qubes devs were supposed to receive a Librem for the purpose of testing and validation as part of this certification process. Did that ever occur? If so, why did no HCL reports or announcements result from that?

CC: @mfc

**Comment by marmarek** [comment]
On Tue, Apr 12, 2016 at 04:17:48PM -0700, Axon wrote:
>  * Why is the Librem 13 "Qubes-certified," but the Librem 15 [apparently is not](https://www.qubes-os.org/doc/certified-laptops/) even though both have the option to ship with Qubes pre-installed?

Yes, Librem 15 is not certified (yet). Generally anyone can sell laptops
with Qubes preinstalled, even if those are not certified ;)
In practice we haven't checked if 4k display used there is working on
Qubes. And since we've received some reports of problems with 4k on
Qubes in general, we can't assume anything here. Hopefully we'll receive
Librem 15 unit with 4k screen soon and will be able to check that. 

>  * What exactly does it mean to say that these laptops are "Qubes-certified"? We [say](https://www.qubes-os.org/doc/certified-laptops/), "Qubes-certified laptops are laptops that have been tested by the Qubes developers to ensure compatibility with all of Qubes’ features." But is that really true?

Yes, we're regularly testing Qubes on certified laptop(s), including new
major versions, and updates to make sure no regressions are introduced
and every (supported in Qubes/listed on the certified laptop page) feature is working.

>  * I thought Qubes devs were supposed to receive a Librem for the purpose of testing and validation as part of this certification process. Did that ever occur? If so, why did no HCL reports or announcements result from that?

Indeed that's an oversight, will update HCL report soon.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
Thanks, Marek! I'll update the Certified Laptops page accordingly.
