### ISSUE TITLE
Create a "Ceritified Hardware" page

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1904]
I believe there are three sub-categories to `Certified Hardware` pages that should be taken into account and interlink:

- Certified Products (easy to buy links, etc...)
- Documentation for Certified Hardware - [currently](https://www.qubes-os.org/doc/certified-laptops/)
- Becoming certified / partnerships - [currently](https://www.qubes-os.org/hardware-certification/)

The later two are already in existence, but could be improved. The first one starts to border on a **Store** page, so prolly doesn't make sense with just the Librem's at present.

**Comment by mfc** [comment]
thanks for putting it up: https://www.qubes-os.org/hardware-certification/

it would be good to also link to it from certified laptops page and partners page

**Comment by mfc** [comment]
since we already have a "certified laptops" page, maybe you are just looking to add a "buy" button next to the Librem 13, since currently the user has to guess that the image is a link?

more generally, instead of a store what this ticket could be is a page mapping the different aspects in an ideal Qubes laptop, and rate what hardware currently exists.

**Comment by andrewdavidwong** [comment]
This was implemented some time ago: https://www.qubes-os.org/hardware-certification/
