### ISSUE TITLE
Create "Who uses Qubes" or "Why use Qubes" section

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1906]
We need some user friendly content that explains _Who should use Qubes_ users base. The Tor project has [a nice one](https://www.torproject.org/about/torusers.html.en). 

This relates to #1833 @mfc are you up for working on this?

**Comment by axon-qubes** [comment]
As I brought up in the discussion of #1833, it's not really clear to me who exactly the intended userbase of Qubes is. I think it's a high-level project decision that ought to be consciously made. In some respects it doesn't matter (for example, it won't change the security-oriented nature of Qubes), and many different answers can be justified. But, for the purpose of writing for one's audience, it's important to have an idea of who that audience is.

**Comment by mfc** [comment]
First this should be framed "Who uses Qubes" not "Who should use Qubes". The *should* makes it into a value judgment which is unnecessarily thorny. Notice that the Tor page is not a value judgment (on the face of it). 

We actually don't want to be listing like five categories of "types of people/users" if that means that some potential users (or current users) are not listed/captured. So that is one reason with the Tor page has "normal users", "high/low profile users", etc. So if we go this route we do want catch-all categories like that, and a mix of current users and desired users (just as Tor does implicitly).

I think more useful would be focusing on *why* someone would be interested in using Qubes -- malware protection, identity management, safely using Windows applications, etc. There is still no place that describes these things.

**Comment by bnvk** [comment]
yah @axon-qubes this is an effort to bring *who* that audience is into focus- it's not going to happen by *not* discussing it and not experimenting with our marketing and outreach :smile: 

Sounds good on the framing @mfc I updated the title. Feel free to help create content you think is best. I've found much mileage in the "persona" style explanations. So perhaps mixing...

> why someone would be interested in using Qubes -- malware protection, identity management, safely using Windows applications, etc. 

...with some user persona's of real (and non-real) people from the categories I mentioned, and by no means being exhaustive about this. An example would be:

---

![Picture of Isis](https://avatars2.githubusercontent.com/u/907241?v=3&s=100)
**Name:** Isis Agora Lovecruft
**Job:** Cypherpunk, Core Developer, Tor Project
**Website:** https://patternsinthevoid.net
**Quote:** `"With QubesOS, I feel more comfortable accessing Tor Project infrastructure from the same laptop as I use to execute random GameBoy ROMs that I downloaded from the internet."`
**Setup:** To do what Ms. Lovecruft is talking about, one simply makes a clone of their normal Debian or Fedora Template and then installs various emulators in that cloned Template. With this setup, if one plays a video game ROM, which happens to be infected with malware, no serious work, encryption keys, or server passwords get compromised, as the emulator and the game ROM are both isolated.

does this sound right @isislovecruft ?

**Comment by isislovecruft** [comment]
@bnvk Sounds pretty good! Maybe change my title somehow, because the first two things are things which I am, but I'm certainly not the entire Tor Project. :)

Also I'm not sure which readers this is targeted at, but maybe some basic Qubes explanation of "things are run in VMs based off of separate templateVMs" or something similar, in order to make it more clear that I'm not SSHing to bridges.torproject.org from my GameBoy emulator VM.

**Comment by isislovecruft** [comment]
Also, I'm not sure if I am a cypherpunk. Those people are _cool_.

**Comment by bnvk** [comment]
@isislovecruft thanks. Updated. Silly coma. You *totes* are a cypherpunk!

**Comment by bnvk** [comment]
adding as per @andrewdavidwong suggestion and @mfc feedback in QubesOS/qubesos.github.io#42

---
![Picture of Snowden](https://www.qubes-os.org/attachment/site/picture-snowden.jpg)
**Name:** Edward Snowden
**Job:** Whistleblower and privacy advocate
**Website:** https://edwardsnowden.com
**Quote:** `"Remember the 'I Hunt Sysadmins' presentation by @NSAGov? Make it hard for them. Use @QubesOS."`
**Setup:** ...to be written, but perhaps a "Sys Admin" configuration of Qubes with Split GPG, VPN, Standlone VMs, etc...

- [tweet](https://twitter.com/Snowden/status/728208443002101760)

**Comment by andrewdavidwong** [comment]
Related (possibly duplicate): #1947

**Comment by mfc** [comment]
so i think this should be framed in terms of types of people/professions who use Qubes (like the Tor website has), rather than the people themselves. if we want to highlight people, either should be a quote on the main page or a "case study" that we promote (on the blog?). 

I think I was a bit too harsh above about the differences between "use" and "should use", the Tor Project page actually says: 
> "Here are some of the specific uses we've seen or **recommend**."

and I think ours will likely also have some userbase projection to it.

below is a basic draft of one approach, that uses professions to frame different Qubes functionalities that may be relevant to them (#1947 could potentially be a source for some of these).

------------------

* **developers**
  * splitgpg (for email, git signing)
  * malware protection / isolation for build environment
* **system administrators**
  * fine-grained networking control: have multiple firewalls, VPNs, Tor connections running in parallel
  * Qubes OS considered the highest level of security practices for sys-admins according to [Linux Foundation IT](https://github.com/lfit/itpol/blob/master/linux-workstation-security.md)
* **businesses**
  * use legacy Windows applications within a secure environment
  * integrate Windows, Debian, Fedora and more applications within a single desktop environment 
  * protect confidential information while still interacting with less secure environments
  * boot integrity (anti-evil-maid) to ensure the security of your laptop while you travel 
* **researchers**
  * malware protection, safely interact with email attachments
  * visit government or corporate websites without them knowing it is you
  * use Martus to gather information more securely
* **activists**
  * easily create and maintain multiple identities online depending on the risks you face 
  * visit media, whistleblowing, government, or corporate websites without them knowing it is you
* **LGBTIQ communities**
  * easily create and maintain multiple identities online depending on the risks you face 
* **journalists**
  * splitgpg
  * communicate with anonymous sources in a secure way
  * visit government or corporate websites without them knowing it is you
* **normal users**
  * integrate Windows, Debian, Fedora and more applications within a single desktop environment
  * safely interact with the web, whether visiting websites or opening files
  * easy backup and restore functionality

**Comment by andrewdavidwong** [comment]
Very helpful discussion of use cases and user stories:
https://groups.google.com/d/topic/qubes-users/S32mraCRdac/discussion

**Comment by andrewdavidwong** [comment]
We can also add a use case for individuals who manager their finances digitally. I can write that one up once we have the page.

**Comment by Jeeppler** [comment]
@mfc you should differentiate between an user need and a technical solution to address it. You do that in most cases. However, you sometimes mix it up. For example, a everyday user actually does not have a need to "integrate Windows, Debian, Fedora and more applications within a single desktop environment". An everyday user, at least for my understanding, does not even know the difference between Windows, Debian and Fedora.

**Comment by andrewdavidwong** [comment]
> you should differentiate between an user need and a technical solution to address it.

Agreed.

> For example, a everyday user actually does not have a need to "integrate Windows, Debian, Fedora and more applications within a single desktop environment". An everyday user, at least for my understanding, does not even know the difference between Windows, Debian and Fedora.

But that's just a difference in the way you're using the term "everyday user."

**Comment by Jeeppler** [comment]
The problem with the group "everyday users" includes basically everybody who has Qubes OS installed on their main computer. The term is to general to be useful. All other terms are group specific, such as researcher or journalist.

There must be a term which describes an user who does not use Qubes OS for professional purposes and it would be beneficial to differentiate between levels of technical expertise. For example, home user surfer, home user technical enthusiast and home user professional. Home user professional would be somebody who uses Windows, macOS or Linux at work, but Qubes OS at home for personal projects or simply playing arround. Home user technical enthusiast could be everybody who does not work in the IT area, but developed an strong interest in computers and uses Qubes OS at home. home user surfer is somebody who uses Qubes OS for online banking, surfing etc. and really likes Qubes OS, but does not care about the technical details. Home user surfer did not install Qubes OS her-/himself instead somebody else installed it for him.

**Comment by mfc** [comment]
my aim was/is to include one category that was a catch-all, just as tor does with the ["normal people" category](https://www.torproject.org/about/torusers.html.en).

**Comment by Jeeppler** [comment]
@mfc "normal people" is even more worse then "everyday users", because the opposite of normal is: abnormal?

**Comment by mfc** [comment]
opposite is "specialized use-cases", but yes it is less clear, hence me using "everyday users". 

let's keep contributions to this thread actually moving it forward -- like filling out / improving some of the [example use-cases](https://github.com/QubesOS/qubes-issues/issues/1906#issuecomment-217473679). it's not going to go anywhere otherwise.

**Comment by Jeeppler** [comment]
@mfc Yes, I try to do exactly that. Please consider a better term then "everyday users".

**Comment by Jeeppler** [comment]
General Qubes Features:
- safely interact with the web, whether visiting websites or opening files
- easy backup and restore functionality
- handle untrusted PDF and DOC files
- convert untrusted PDF into trusted PDFs

Technical Features:
- transparent integration of Windows, Debian, Fedora and more applications within a single desktop environment
- boot integrity (anti-evil-maid) to ensure the security of your laptop while you travel

Group Specific:
- developers
     - multiple development environments with different configurations for different projects
     - testing applications on Windows and Linux (Debian, Fedora, ....)
     - for email and git signing  (splitgpg)
     - malware protection / isolation for build environment
- system administrators
     - fine-grained networking control: have multiple firewalls, VPNs, Tor connections running in parallel
        Qubes OS considered the highest level of security practices for sys-admins according to Linux Foundation IT
- businesses
    - use legacy Windows applications within a secure environment
    - protect confidential information while still interacting with less secure environments
- researchers
    - malware protection, safely interact with email attachments
    - visit government or corporate websites without them knowing it is you
    - use Martus to gather information more securely
    - availability of different operating systems (Windows, Linux, Unikernel) from a single desktop environment
- activists
    - easily create and maintain multiple identities online depending on the risks you face
    - visit media, whistleblowing, government, or corporate websites without them knowing it is you
- LGBTIQ communities
    - easily create and maintain multiple identities online depending on the risks you face
- journalists
    - encrypt your emails (splitgpg)
    - communicate with anonymous sources in a secure way
    - visit government or corporate websites without them knowing it is you
    everyday users

**Comment by Jeeppler** [comment]
this line:  

> visit media, whistleblowing, government, or corporate websites without them knowing it is you

sounds like anonymity. Even TOR can not provide absolute anonymity (bugs, zero-days etc. can jeopardize it)

**Comment by mfc** [comment]
sorry for the delay in responding, i really like your framing! i don't know if we want to pepper it with hyperlinks to different Qubes functionalities or if that would be overwhelming to the reader. 

we might want stock images for the different groups similar to the Tor page, or graphics/icons to add some visual element to it.

**Comment by tlaurion** [comment]
@marmarek @mfc : Is there a OEM image permitting to change LUKS encrypted password and user passwords in a second stage, permitting to deploy those implemented persona as salt recipes, installing predefined [softwares and customizations](https://github.com/SkypLabs/my-qubes-os-formula)?

**Comment by marmarek** [comment]
> @marmarek @mfc : Is there a OEM image permitting to change LUKS encrypted password and user passwords in a second stage, permitting to deploy those implemented persona as salt recipes, installing predefined [softwares and customizations](https://github.com/SkypLabs/my-qubes-os-formula)?

It is offtopic here... But the problem is not in passwords (you can change them at any time), but in LUKS key, you need to re-encrypt the whole disk, see [here](https://security.stackexchange.com/q/123955) for example. We [have done something different in the past](https://github.com/marmarek/qubes-installer-qubes-os/tree/r3.2-librem): strip down the installer to ask  only for LUKS passhprase. Write it into a partition, copy `images/oem.img` from there to the first partition (future `/boot`) and it will launch installer on the first boot.

**Comment by tlaurion** [comment]
> It is offtopic here... But the problem is not in passwords (you can change them at any time), but in LUKS key, you need to re-encrypt the whole disk, see [here](https://security.stackexchange.com/q/123955) for example. We [have done something different in the past](https://github.com/marmarek/qubes-installer-qubes-os/tree/r3.2-librem): strip down the installer to ask only for LUKS passhprase. Write it into a partition, copy `images/oem.img` from there to the first partition (future `/boot`) and it will launch installer on the first boot.

Sorry to be off topic for the LUKS encryption password, but manually, it is as simple as:
`sudo cryptsetup luksChangeKey /dev/sda2 --key-slot  0`

**Comment by tlaurion** [comment]
> @marmarek @mfc : Is there a OEM image permitting to change LUKS encrypted password and user passwords in a second stage, permitting to deploy those implemented persona as salt recipes, installing predefined [softwares and customizations](https://github.com/SkypLabs/my-qubes-os-formula)?

@marmarek : and what about deploying custom salt recipes for defined personas?

**Comment by marmarek** [comment]
On Tue, Sep 18, 2018 at 08:11:59PM -0700, tlaurion wrote:
> > It is offtopic here... But the problem is not in passwords (you can change them at any time), but in LUKS key, you need to re-encrypt the whole disk, see [here](https://security.stackexchange.com/q/123955) for example. We [have done something different in the past](https://github.com/marmarek/qubes-installer-qubes-os/tree/r3.2-librem): strip down the installer to ask only for LUKS passhprase. Write it into a partition, copy `images/oem.img` from there to the first partition (future `/boot`) and it will launch installer on the first boot.
> 
> Sorry to be off topic for the LUKS encryption password, but manually, it is as simple as:
> `sudo cryptsetup luksChangeKey /dev/sda2 --key-slot  0`

No, it is not. This doesn't change the actual encryption key (aka LUKS master key). You can see this with `sudo cryptsetup luksDump --dump-master-key /dev/sda2` before and after luksChangeKey.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by tlaurion** [comment]
> No, it is not. This doesn't change the actual encryption key (aka LUKS master key). You can see this with `sudo cryptsetup luksDump --dump-master-key /dev/sda2` before and after luksChangeKey.

Sorry for the noise, @marmarek. I deleted my initial comment after reevaluating the facts. 

Any discussion threads at hand of what led to r3.x-librem and why it was not used for QubesOS deployements on Librems?

**Comment by andrewdavidwong** [comment]
@tlaurion, please take off-topic discussion out of this issue and to the appropriate place (probably the `qubes-users` [mailing list](https://www.qubes-os.org/support/)).

**Comment by mfc** [comment]
* [Tor Browser example](https://2019.www.torproject.org/about/torusers.html.en)

**Comment by deeplow** [comment]
Some other examples can be taken from:
  * https://usable.tools/personas/
  * [Tails' website](https://tails.boum.org/):
    
    ![tails](https://user-images.githubusercontent.com/47065258/113189094-58347480-924a-11eb-9c68-0310a777a369.png)

**Comment by kennethrrosen** [comment]
Seems like this can be closed, or is there still documentation needed @andrewdavidwong ?
