### ISSUE TITLE
Fix pages with multiple h1 headings

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1914]
Here's an example page:

https://www.qubes-os.org/doc/copy-from-dom0/

There are two h1 headings on that page. The second one doesn't show up in the automatically-generated table of contents on the right (or bottom, if on mobile).

**Comment by bnvk** [comment]
This relates to the same jQuery plugin as #1713 However, in this case, I believe the plugin explicitly ignores `h1` headings as those are supposed to be the *page heading* and not repeated throughout the content. 

Thus, I believe the right approach here is to **Convert `h1` in doc pages to `h2,  h3` tags** rather than modify the plugin. Is that something you are up to doing @axon-qubes ?

**Comment by axon-qubes** [comment]
Sure, not a problem. However, I don't know of a good way to find all the pages with duplicate `h1`s, so I can only fix it for this one page for now.

**Comment by axon-qubes** [comment]
(For all I know, this may be the only page that has duplicate `h1`s.)

**Comment by axon-qubes** [comment]
I'm reopening this issue since we've come across at least one more page with multiple `h1` headings (and since there are probably more out there), but I'm changing the title to reflect the decision made here.

**Comment by andrewdavidwong** [comment]
I'll just fix these as I come across them in the future.
