### ISSUE TITLE
XFCE and KDE prompt choices are opposite to each other

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1916]
#### Qubes OS version (e.g., `R3.1`): R3.1

---

### Expected behavior:

prompts in XFCE and KDE have the same order. prompts include file transfer prompt, closing a VM, plugging in a USB mouse, etc. In all of these prompts, the order of the options is opposite between XFCE and KDE: in XFCE `no` is the left selection and `yes` is the right selection, while in KDE it is the opposite (for example).

### Actual behavior:

they should be the same. we should have to have a unified UX across different desktop environments as much as possible.

### Steps to reproduce the behavior:

do anything that creates a prompt in KDE, and then in XFCE.

**Comment by marmarek** [comment]
Indeed XFCE and KDE uses opposite buttons order.
I'm not sure if "expected behavior" is right. I think more important is being consistent with other parts of DE. People don't switch DE frequently, but do work on multiple applications in the same DE. Having all the prompt one way, but Qubes prompt the other way (to be consistent with some other DE) seems wrong to me.

**Comment by mfc** [comment]
cool, good to know it is the DEs and not something Qubes did.
