### ISSUE TITLE
Whonix default VM settings fixes - salt management

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1954]
1) **whonix-ws default NetVM sys-whonix**:
When creating a whonix-ws based VM using QVMM (or cli...), could the default selection for its NetVM be set to sys-whonix using salt somehow? [3]

2) **whonix-ws-dvm default NetVM sys-whonix**:
After creating a whonix-ws based DisposableVM... [1] [2] Could the default NetVM be set to sys-whonix [3] using salt somehow?

3) **dynamically created DispVM default NetVM sys-whonix**:
When running `qvm-open-in-dvm https://www.google.com` the newly created DispVM will by default be using sys-net as its NetVM. Could it be set to sys-whonix by default? -- Or alternatively, should the DispVM not get the NetVM setting from the dvm template anyhow? Do we have a ticket for that or should create one?

4) **whonix-gw VM type ProxyVM**:
When creating a new VM based on whonix-gw using QVMM, could VM type ProxyVM be selected by default?

---

[1] `qvm-create-default-dvm whonix-ws`
[2] https://www.whonix.org/wiki/Qubes/Disposable_VM
[3] Or if there is not VM names sys-whonix, use the 'next best' one, i.e. a ProxyVM based on a whonix-gw template? (Not sure that makes sense or is too much.)

**Comment by marmarek** [comment]
> 1) **whonix-ws default NetVM sys-whonix**:

Currently there is only global "default NetVM" setting - independent of VM's template. So the simple answer is "no". But we may think of some API for that in Qubes 4.0.

> 2) **whonix-ws-dvm default NetVM sys-whonix**:

Yes, `whonix-ws-dvm` can be created by salt and `sys-whonix` set there.

> 3) **dynamically created DispVM default NetVM sys-whonix**:

NetVM of DispVM is inherited from calling VM (or `dispvm_netvm` setting of that VM if set). So when you call `qvm-open-in-dvm` from a VM behind `sys-whonix`, that DispVM will also have `sys-whonix` as NetVM. You can also set `dispvm_netvm` property of all the VMs to `sys-whonix` to achieve what you want.
Other than that - same as in "1" - there is no per-template default for that, we may think of it in Qubes 4.0. Since multiple DispVM templates are going to be implemented in 4.0, it will have more sense there.

> 4) **whonix-gw VM type ProxyVM**:

Same as "1" - this isn't currently possible. And to be frank I don't think it would be useful. For most of users, one `sys-whonix` will be enough (created by salt). Others will manage to set ProxyVM (one option in Qubes Manager).

**Comment by adrelanos** [comment]
I guess all of this is implemented due to improvements in Qubes R4 / Qubes-Whonix 14 / qubes-core-admin-addon-whonix / qubes-mgmt-salt-dom0-virtual-machines?

**Comment by marmarek** [comment]
@adrelanos yes, when whonix-ws-based AppVM is created with `qvm-create` this all works already. When it's created with GUI, `netvm` is reset to default, @marmarta will fix shortly.
