### ISSUE TITLE
Add social media meta tags

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1960]

**Comment by marmarek** [comment]
Can you elaborate?

**Comment by adrelanos** [comment]
Opengraph, structured data, http://ogp.me/. The metadata for various (sub) web pages. The ones that describe the preview image, excerpt text, product name, price and whatnot.

I recommend using the following linters:

* https://developers.facebook.com/tools/debug/
* https://cards-dev.twitter.com/validator
* https://developers.google.com/structured-data/testing-tool/

Since this has been implemented on the Whonix website (that uses entirely different content generators, mediawiki, wordpress, phabricator, discourse), I may be a bit of help with these metadata. Can do a bit testing and question/answer on the topic.

**Comment by kalkin** [comment]
I did a microdata project some time ago and I would recommend using https://schema.org instead of opengraph, because it's more widely(?) supported. You can also express the schema.org vocabulary with RDFa

**Comment by akuckartz** [comment]
:+1: for using schema.org

**Comment by andrewdavidwong** [comment]
Why not both?

**Comment by kalkin** [comment]
@andrewdavidwong You can do both.  As far as I'm not mistaken OpenGraph also uses RDFa with own namespace/vocabulary, this will get cumbersome very fast if you do it by hand. If you generate it automatically  there might be cases where you can't generate both vocabularies data without some special handling for each vocabulary, i.e. when you need to insert empty/hidden tags which only contain data. It's definitely doable, but cumbersome and is more effort.

**Comment by andrewdavidwong** [comment]
Done:
https://github.com/QubesOS/qubesos.github.io/commit/dc4806053a8a14604412a8a553e4b98c017a1756
https://github.com/QubesOS/qubesos.github.io/commit/f52407915788e7676ed195ccc7b12491958aa95e
