### ISSUE TITLE
Document installation to a USB drive

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1975]
Standard installation to a USB drive is different from Qubes Live USB. Requires two USB drives (one for installation ISO, one as target of installation) or one USB drive and some other installation medium (e.g., optical disc). Should be documented here, since the possibility is already mentioned here: https://www.qubes-os.org/doc/installation-guide/

**Comment by crypt0beard** [comment]
Hello Andrew,

Attached is a word document that I created with the instructions on installing Qubes to a USB drive. Please review and let me know your input. 

Thanks,

Alexander
[InstallingonUSB.docx](https://github.com/QubesOS/qubes-issues/files/302674/InstallingonUSB.docx)

**Comment by crypt0beard** [comment]
Here is the link if you don't feel like downloading the word doc.

https://github.com/crypt0beard/QubesWork/wiki/Install-onto-USB

**Comment by andrewdavidwong** [comment]
@crypt0beard: Thank you for helping out! A couple of comments:

1. Our documentation is written in Markdown and managed under Git. The main documentation repository is [qubes-doc](https://github.com/QubesOS/qubes-doc). Please read [this page](https://www.qubes-os.org/doc/doc-guidelines/) for instructions on how to contribute. In the case of #1975, you should submit a pull request against [this page](https://www.qubes-os.org/doc/installation-guide/). We generally don't accept `.docx` files or content in GitHub built-in wikis.

2. Most of what you've written is about the installation process more generally (i.e., not specific to #1975). That's fine. Maybe it should be integrated into the rest of the Installation Guide. However, most of it doesn't seem to be about #1975 in particular. Is that just because there's nothing else to say about installing to a USB drive? (Did you test this procedure and find that there was nothing else noteworthy? If so, that's fine.)

**Comment by crypt0beard** [comment]
Andrew,
I will make sure to follow the proper documentation procedure from here on out. Thank you for explaining that to me. As far as the installation to the USB, I did a test myself and there wasn't to much else to note. The main difference would be selecting that as the medium for the install and assuring the drive meets the minimum requirements for Qubes. Would you like me to resubmit my documentation the way you explained? Or would you rather just have the brief notes that differ from the normal install? Let me know!
Thanks,
Alexander 
On Jun 7, 2016 21:01, Andrew David Wong <notifications@github.com> wrote:@crypt0beard: Thank you for helping out! A couple of comments:

Our documentation is written in Markdown and managed under Git. The main documentation repository is qubes-doc. Please read this page for instructions on how to contribute. In the case of #1975, you should submit a pull request against this page. We generally don't accept .docx files or content in GitHub built-in wikis.Most of what you've written is about the installation process more generally (i.e., not specific to #1975). That's fine. Maybe it should be integrated into the rest of the Installation Guide. However, most of it doesn't seem to be about #1975 in particular. Is that just because there's nothing else to say about installing to a USB drive? (Did you test this procedure and find that there was nothing else noteworthy? If so, that's fine.
 )

**Comment by andrewdavidwong** [comment]
Yes, please submit a pull request.

**Comment by crypt0beard** [comment]
I will make sure to do so first thing in the morning. (on EST time)
On Jun 7, 2016 21:51, Andrew David Wong <notifications@github.com> wrote:Yes, please submit a pull request.

**Comment by crypt0beard** [comment]
I have submitted the pull request. 
 

    On Wednesday, June 8, 2016 1:52 AM, Andrew David Wong <notifications@github.com> wrote:
 

 Yes, please submit a pull request.—

**Comment by andrewdavidwong** [comment]
Thanks!
