### ISSUE TITLE
Kernel crash/hang during sys-net shutdown

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1978]
https://groups.google.com/d/msgid/qubes-users/2732b4d5da4cc5d319468510e81039cc1540%40guerrillamail.com.

iwlwifi module crashes during sys-net shutdown. Most likely because of [removing underlying PCI device](https://github.com/QubesOS/qubes-core-admin/commit/2658c9a6e69ed272f49e71e04b5b342ea2dc388f) without detaching driver first.

**Comment by t-pa** [comment]
I have the same problem on a Thinkpad X260. The workaround of unloading the iwlwifi module before shutdown as suggested by Marek solves this problem for me:

```
#!/bin/bash
qvm-shutdown --wait --all --exclude=sys-net
qvm-run sys-net "sudo ifconfig wlp0s1 down; sudo modprobe -r iwlmvm; sudo modprobe -r iwlwifi"
qvm-shutdown --wait sys-net
sudo shutdown now
```

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
