### ISSUE TITLE
Options to set `dispvm_netvm` to 'none' for all VMs and as default

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1988]
Currently, the default for `dispvm_netvm` is `same as VM own NetVM`. Rarely do I want this. Almost always, I want to set this to `none`. However, there is no way to change this setting for all VMs simultaneously, and there is no way to change the default to `none`, so my only option is to change the setting for each VM manually, which, having many VMs, is very tedious.

Ref: https://github.com/QubesOS/qubes-issues/issues/1272#issuecomment-146387241

Edit: Corrected current default.

**Comment by andrewdavidwong** [comment]
Would the current default count as an example of an "insecure default"?

Imagine a new Qubes user opens a malicious file in a DispVM which communicates against the user's wishes with an external server.

User: "Why did Qubes allow that to happen? I opened the file in a DispVM."
Us: "Well, by default, the DispVM inherits its NetVM from the VM from which it was generated. If you want to change that behavior, you have to change the setting. For example, you can change it to `none`."
User: "So, I have to change it manually if I want the most secure setting? Why wouldn't you just make it secure by default?"

**Comment by adrelanos** [comment]
I agree this being an insecure default. At very least as far as Qubes-Whonix is concerned. The [Qubes-Whonix documentation on using DispVMs](https://www.whonix.org/wiki/Qubes/Disposable_VM) is also getting quite cryptic because of this.

> The NetVM of DispVM is inherited from calling VM's netvm setting or - if set - from the dispvm_netvm setting. So when run Open in DispVM from a VM behind sys-whonix, that DispVM will also have sys-whonix as NetVM. But when you run Open in DispVM from a VM behind sys-net, it will not be through Tor. If you want that, you can set the dispvm_netvm setting of all the VMs to sys-whonix to achieve what you want. [5] Here is an example how to set the dispvm_netvm setting of the VM work-mail to sys-whonix.

> `qvm-prefs -s work-mail dispvm_netvm sys-whonix`

(Related: `Whonix default VM settings fixes - salt management` (#1954))

Related: In `edits in DispVM are saved, counter to user expectations` (https://github.com/QubesOS/qubes-issues/issues/1118) I commented on the various conflicting use cases and expectations: https://github.com/QubesOS/qubes-issues/issues/1118#issuecomment-131395780

Possible duplicate: `DispVM should be non-networked by default, or have a clear option to users to do so` (https://github.com/QubesOS/qubes-issues/issues/1121)

**Comment by andrewdavidwong** [comment]
I thought #1121 was about setting the NetVM of the DVM template (e.g., `fedora-23-dvm`) to `none`, whereas this is about setting the `dispvm_netvm` proper of each VM to `none`, but on second look, they may indeed be duplicates. @marmarek?

**Comment by andrewdavidwong** [comment]
In the meantime, here's a simple script that sets every VM's `dispvm_netvm` property to `none` and reads back the value of that property for confirmation:

```
#!/bin/bash
for vm in `qvm-ls --raw-list`; do
    echo -n "$vm : ";
    qvm-prefs -s $vm dispvm_netvm none;
    qvm-prefs -l $vm | grep dispvm_netvm:
done;
exit
```

**Comment by marmarek** [comment]
In Qubes 4.0 it's enough to set netvm of whatever default DispVM you have (`fedora-29-dvm`?) to none, so I consider it implemented.

Totally offtopic: since it's possible to change DVM template's template in Qubes 4.0, should we rename it to `default-dvm` or such? Otherwise migrating to new default template involve either creating new default DVM template, or adjusting and ideally renaming the old one. @andrewdavidwong if you think it's a good idea, feel free to open new issue about it...

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong if you think it's a good idea, feel free to open new issue about it...

Done: #4589.
