### ISSUE TITLE
m.2 SSD not selectable in Installer.

### ISSUE THREAD

**Issue by KuroSaru** [QubesOS/qubes-issues#1999]
#### Qubes OS version (e.g., `R3.1`):
 R3.1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): 
Installer.
---

### Expected behavior: 
m.2 SSD detected as potential installation location.

### Actual behavior: 
Not selectable, but is shown in /dev as sdb

### Steps to reproduce the behavior:
try to install on a plextor px-g512m6e m.2 SSD with a 2nd drive (2x 1TB SSDs in stripe raid mode)

### General notes:

Not really sure what else at this point i can give.

m.2 SSD is shown in /dev in the console of the installer, only the raid shows as potential installation location which is /dev/sda and m.2 SSD is /dev/sdb, trying to install from USB (mounted as /dev/sdc)

Tested in legacy and UEFI boot modes. same results.

Also check SATA mode is set to ACHI instead of Raid and had same issue.

---

**Comment by andrewdavidwong** [comment]
Other users have [reported](https://groups.google.com/d/msg/qubes-users/Q1t2yl5A1gI/D5CGKCWPCwAJ) being able to install Qubes R3.1 on an M.2 SSD, so it sounds like this might be an incompatibility issue specific to your hardware. Generally, we ask that localized problems are sent to `qubes-users` rather than filed as issues here. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).) `qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
