### ISSUE TITLE
Update icon incorrectly appears for TemplateVMs when no updates are available

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#2009]
#### Qubes OS version (e.g., `R3.1`):

R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

`debian-8`, possible that the same problem exist for `whonix-gw` and `whonix-ws`.

---
### Expected behavior:

The update icon in qubes-manager is only visible when updates is available.
### Actual behavior:

The update icon shows up even if there is no updates available. The icon usually (or always, not sure) disappears after pressed the the update button and APT have run `update`.
### Steps to reproduce the behavior:

I'm not entirely sure, but the icons tends to show when I've powered up/rebooted the computer.
### General notes:

---

**Comment by andrewdavidwong** [comment]
Related: #1476, #1511

**Comment by andrewdavidwong** [comment]
Qubes user "q" [reports](https://groups.google.com/d/msgid/qubes-devel/4aba2d2e-98ec-40b5-bfdc-05bbab0e508b%40googlegroups.com) that this also happens on `fedora-23` templates in Qubes `R3.2-rc1`:
> template upgrade notification bug: i have to run update, reboot template, 
> run again, shut down template, then the update notification in 
> qubes-vm-manager goes away. it should go away when the first update 
> completes. i tried reproducing this. it only occurred on whonix-gw and 
> fedora-23 templates. strange and intermittent. when all else fails it is 
> good to let qubes "try again".

**Comment by pdinoto** [comment]
Just want to report that same is happening to a clone of debian-8, on Qubes R3.2rc1.
Reboot does not fix it. Except for this cosmetic issue, everything else works as expected.

**Comment by pierwill** [comment]
I'm seeing this issue in Qubes 3.2 with the debian-9 template

**Comment by AlmightyLaxz** [comment]
I have a related issue where "template_for_dispvms" enabled AppVMs are incorrectly displaying 'Updates Pending!' notifications in the Qube Manager. This occurs even when the VM's TemplateVM is updated and the update notification disappears (on the template). The AppVM is stuck with an update notification permanently.

A temporary workaround is to remove the updates-available setting from the AppVM's features
`qvm-features --unset <AppVM name> updates-available`

I haven't found a way to reproduce this issue yet.

This issue has been mentioned before in #3464.

**Comment by bigdx** [comment]
Same issue in R4.0 with a fedora-28 template, permanently marked as "Updates pending", but in my case it's not set as "template_for_dispvms", thats the case for fedora-28-dvm which is not marked for updates

**Comment by andrewdavidwong** [comment]
> Same issue in R4.0 with a fedora-28 template, permanently marked as "Updates pending", but in my case it's not set as "template_for_dispvms", thats the case for fedora-28-dvm which is not marked for updates
> 
> This means #1511 isnt solved ?! At least reguarding R4.0 ...

No, #1511 is about the icon for dom0 updates, whereas you're talking about the icon for template updates (this issue, #2009).

**Comment by bigdx** [comment]
Just thought that this could be related somehow. I have only seen incorrect update icons for TemplateVMs, not for Dom0 (yet).

Update: Not exactly sure what happend because I recognized much later that the update icon was gone, but it seems that a update that really did some updates let the icon vanish. Instead of all updates before which resulted with "Nothing to do. Complete!" and had no effect on the icon. Vis versa only "real" updates seem to provocate this issue.

**Comment by speedtester** [comment]
Hello,

I' had the same problem with my new debian-10 qube: "Qubes Update" icon appeared in tray with: "Updates are available." message, and down arrow icon appeared also in qube manager.
However both update methods ended with no updates available.

When I installed this debian-10 template from itl-testing repo, I remember the post processing script ran into some problems (waiting loop complaining the vm already killed), but I ignored that.
Maybe because I've just installed the latest dom0 update, but it was pending reboot.
(the running code may differ from the expected/installed version?)

Do you think there is a connection between the post-process script problem, pending reboot and the stuck update available sign?

Running "qvm-features --unset debian-10 updates-availabe" worked as expected, however I'm concerned about the reliability of the update notification system.

Is there a documentation how it exactly works?

I also noticed, that updates available usually shows up when a related qube is started, and then it's too late, need to update template and relaunch each qube. It would be nice to receive updates info prior to launching.

Thanks.

**Comment by marmarek** [comment]
> I also noticed, that updates available usually shows up when a related qube is started, and then it's too late, need to update template and relaunch each qube. It would be nice to receive updates info prior to launching.

This is because only qube based on a given template (or the template itself) can possibly know if any updates are available. If nothing related to a template is running, nothing can report updates availability.

**Comment by speedtester** [comment]
> > I also noticed, that updates available usually shows up when a related qube is started, and then it's too late, need to update template and relaunch each qube. It would be nice to receive updates info prior to launching.
> 
> This is because only qube based on a given template (or the template itself) can possibly know if any updates are available. If nothing related to a template is running, nothing can report updates availability.

Yes, I suspected how this works, although it could be implemented in this way (delegated):
-A template/standalone qube could report all the necessary information (installed package info, sources, etc.) required to query update info. 
-The update notification system should do regular checks for each subscribed qube.

**Comment by andrewdavidwong** [comment]
I'm also still seeing this problem with a Fedora template. It occurs whenever I start a particular VM that installs a local RPM on startup (via `/rw/rc.local`).

**Comment by marmarek** [comment]
> Yes, I suspected how this works, although it could be implemented in this way (delegated):
> -A template/standalone qube could report all the necessary information (installed package info, sources, etc.) required to query update status.
> -The update notification system should do regular checks for each subscribed qube.

That is not enough. Note that different distributions use different repository formats. It isn't just "check this URL". You actually need to parse that format, extract relevant information, possibly refer to other files referenced there etc. What you propose is basically "have a universal package manager supporting all existing(*) distributions". While technically possible, definitely not practical. And also it would have a huge attack surface.
Also "the update notification system" would need to be something that have network access, and have a lot of information about the system. A perfect attack target. One could say you can isolate reporting updates about each template into separate components. But this is exactly how it's done now: it's just happen that those components are placed into qubes based on that template.

(*) you could limit to only "supported" distributions, but it would be hostile for community contributions then. It would even more segregate templates into first and second class citizens.

On the other hand, one might want to distinguish update types into "new features", "bug fixes", "security fixes" (or similar categories). Some distributions do provide metadata for it. Then, you would see how important is it to install updates now vs some time later.

**Comment by marmarek** [comment]
> I'm also still seeing this problem with a Fedora template. It occurs whenever I start a particular VM that installs a local RPM on startup (via `/rw/rc.local`).

Are you referring to when updates are reported, or to updates being reported when everything is up to date?

**Comment by andrewdavidwong** [comment]
> > I'm also still seeing this problem with a Fedora template. It occurs whenever I start a particular VM that installs a local RPM on startup (via `/rw/rc.local`).
> 
> Are you referring to when updates are reported, or to updates being reported when everything is up to date?

I'm referring to updates being reported when everything is up-to-date. Steps to reproduce:

1. Start AppVM.
2. `dnf -y install some_package.rpm` in AppVM.
3. Qubes Update widget appears, stating update available for TemplateVM on which AppVM is based.
4. Use Qubes Update widget or command-line to update TemplateVM.
5. Receive message that no updates are available in TemplateVM.

**Comment by marmarta** [comment]
@andrewdavidwong , I can't seem to reproduce this - which Fedora template version are you using?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong , I can't seem to reproduce this - which Fedora template version are you using?

I'm using Fedora 29.

**Comment by marmarek** [comment]
> Use Qubes Update widget or command-line to update TemplateVM.

When you check with command-line, try `dnf update --refresh`, maybe metadata cache is stale.
Does the VM where you install rpm package have network access? What you get if you run `dnf check-update` there just after receiving notification?

**Comment by andrewdavidwong** [comment]
> > Use Qubes Update widget or command-line to update TemplateVM.
> 
> When you check with command-line, try `dnf update --refresh`, maybe metadata cache is stale.
> Does the VM where you install rpm package have network access? What you get if you run `dnf check-update` there just after receiving notification?

Oh, I see what's happening! My second step above was `dnf -y install some_package.rpm`. Well, it turns out that this very package has an update available right after I install it. My mistake! :sweat_smile:

**Comment by marmarta** [comment]
@andrewdavidwong haha, that explains why I couldn't reproduce that! The problem is that in the current state, there's just no way to detect whether update is for a package in an AppVM or in its TemplateVM (the VM doesn't really know that well it's an AppVM, it just has packages - the fact that those installed locally in it will vanish on reboot is not known to it)... it would require changes to the package manager itself, and that sounds like a bad idea. And we can't use the TemplateVM itself to check for updates - that would require starting it, and starting VMs just to check for updates sounds like a resource waste. 
I think it's the sort of case when you manage to genuinely trick the system (not only you install a package in a template-based AppVM, but the package is not the newest available) and we should accept it as a weird rare sideeffect? @marmarek, would you agree?

**Comment by marmarek** [comment]
I think there is still an issue that icon remains when TemplateVM has no updates, even just after checking it in TemplateVM itself. I think in no-op case our `dnf` plugin isn't called and this fact isn't reported back to dom0.

**Comment by andrewdavidwong** [comment]
> I think there is still an issue that icon remains when TemplateVM has no updates, even just after checking it in TemplateVM itself.

I agree. From the user's point of view:

* There is an icon requesting that I take action.
* I take the requested action.
* The icon does not go away.
* I conclude there is nothing I can do to make the icon go away. I just have to live with it. This is annoying.
* The icon is less useful now, because it does not accurately tell me when I need to take action. (It has false positives.)

**Comment by marmarta** [comment]
I wonder what should we do in such a case - we can of course turn off the widget, but when should it turn on again? Or, in other words, when should updates-available get set again? Because if nothing changes, the package manager will just report updates available again in a few moments.

**Comment by marmarek** [comment]
> The icon does not go away.

Fixing just this one would be an improvement already. Then, if you avoid installing outdated packages (but you need to notice this being the case - which as you see isn't obvious), it should be fine. Otherwise, the alternative would be to prevent this particular VM from reporting updates for its template.

**Comment by andrewdavidwong** [comment]
> I wonder what should we do in such a case - we can of course turn off the widget, but when should it turn on again? Or, in other words, when should updates-available get set again?

I would think it would be the next time that a normal update check is performed (as usual, in a VM based on that template).

> Because if nothing changes, the package manager will just report updates available again in a few moments.

Hm, why would that be true? VMs normally do not check for updates every few moments.
