### ISSUE TITLE
Qubes Manager "Create New VM" window doesn't handle resize

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2095]
When window is resized, all widgets stays with the same size and place. Especially annoying on HiDPI screen, where initial placement doesn't allow to fit even field labels.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by iamahuman** [comment]
Fixed in R4.1 by https://github.com/QubesOS/qubes-manager/pull/196

**Comment by andrewdavidwong** [comment]
> Fixed in R4.1 by [QubesOS/qubes-manager#196](https://github.com/QubesOS/qubes-manager/pull/196)
> 
> `Qube Settings » Devices » Configure strict reset for PCI devices` (https://github.com/QubesOS/qubes-manager/blob/22281bd770f071b34e91b304848681a6dd938706/ui/backupdlg.ui) still seems to be affected though (no `sizepolicy` and no resizeable layout)

It sounds like you're implying that this bug is fixed in 4.1 but is still present in 4.0, so I've reopened this issue and updated the milestone appropriately.
