### ISSUE TITLE
USB VM not properly suspended/resumed for S3

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2123]
It seems as if my USB-controllers-holding VM doesn't get proper suspend/resume treatment from Dom0, which results in a long timeout after resume during which USB devices are not accessible. I think this might be specific to a system installed with Xfce4 only, without KDE?

**Comment by marmarek** [comment]
Can you provide some logs? At least kernel messages from USB VM and logs from `qubes-suspend` service in dom0:
```
sudo journalctl -b -u qubes-suspend
```

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
