### ISSUE TITLE
JavaProgramm TheBrain Detailed Popup-Boxes don't work

### ISSUE THREAD

**Issue by XGlobetrotter** [QubesOS/qubes-issues#2137]
#### Qubes OS version (e.g., `R3.1`):

R3.1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

StandaloneVM with Debian8

---

### Expected behavior:

TheBrain version 7 (meta-mindmapping) should work as always, to define the structure and 

### Actual behavior:

TheBrain version 7 (meta-mindmapping) works fine, also the first level popup-boxes will work. 
But the second level popup-boxes are shown by Q R.31 only a couple of ms. 

### Steps to reproduce the behavior:

Download the PB7 from the webpage www.thebrain.com.
http://www.thebrain.com/products/thebrain/download/
On the bottom of the screen you found older releases, PB8 is the actual release.
http://www.thebrain.com/products/thebrain/download-old/
Downlaod the PB7 Linux 32 bit (which is more stable) and install it inside a Debian Standalone VM.

i) Define Type for a Thought
Generate a new brain.
F6 Generate a new thought.
You see a popup-box of the new thought and now press the button Type.
Here you can choose or define new Types, but under Q it will not be possible because this second popup will be seen only very short.

ii) Define Color of a Tag
Goto the Tag window.
Define a new Tag with the + sign.
Click on the Tag with the right mouse and choose Properties.
Choose the color of the Tag, but this is not possible because the color-palette is open very short.

So it seems that Q R3.1 under JAVA cannot show all popup-levels of an application running inside a Standalone VM.

### General notes:

PB7 is based on JAVA

I use PB7 quite heavily as a meta-mindmapping tool, so I would be happy if it will work also under Qubes OS, like I'm used to.

---

**Comment by andrewdavidwong** [comment]
Are you sure that this is a Qubes-specific issue? Does this software work on baremetal Debian 8? Are you missing any dependencies?

Generally speaking, we can't provide support for software compatibility within AppVMs. There's just too much software in the world, and we have to focus our efforts on Qubes OS rather than troubleshooting other projects' software. But if you can clearly and concisely explain why this is a Qubes bug (or a feature we should have), then we can have an issue for this. Otherwise, this sort of question should be asked on qubes-users.
