### ISSUE TITLE
"back" mouse button freeze windows applications in seamless mode

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2138]
https://groups.google.com/d/msgid/qubes-users/a725a627-df4c-48a5-bab7-28f47e43b6d6%40googlegroups.com

> I found the situation when "window" of WIn7 freeze. "Window" become
> unresponsive for all mouse events. But Windows7 still working and I can use
> "Win" key to open Start Menu after I switched to "non seamless mode".
> I can unfreeze the VM by some keyboard events.
> 
> The situation can be reproduced with with the mouse that have "BACK"
> button.
> 
> So, it's occur when I click "back" button on the mouse. And all opened
> windows on this WinVM freeze :)

**Comment by marmarek** [comment]
@omeg while you're fixing tools, take a look at this one.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
