### ISSUE TITLE
VM Manager doesn't load after user re-login

### ISSUE THREAD

**Issue by lhaeberle** [QubesOS/qubes-issues#2175]
#### Affected TemplateVMs: none

---
### Expected behavior:

loadable VM Manager
### Actual behavior:

After re-login into QubesOS VM Manager doesn't load any more // isn't loadable
### Steps to reproduce the behavior:
1. log off
2. re-login
3. try to load VM Manager
### General notes:

---

**Comment by marmarek** [comment]
I can confirm this issue. The problem is that qubes-manager is still running in the background, so the new instance refuses to start...

**Comment by lhaeberle** [comment]
ok. Will kill the process to work around. Thanks.

**Comment by Zrubi** [comment]
relogging involves more issues:
- the tray icons stop changing ("animating") for example the NM icon shows the disconnected state even if it is actually connected.

- all the opened windows, from started VMs are not closed
I see no real difference between lock and logout. 
logout only resets the KDE/Xfce session related things, leving all the VMs alone.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
