### ISSUE TITLE
Qubes-compatible dom0 Xfce4 dark theme

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2204]
[Branched from #911]

Select one of the preexisting Xfce4 dark themes and ensure that all Qubes widgets are compatible with it. This ensures that users who prefer a dark theme in dom0 will have at least one working option.

**Comment by Jeeppler** [comment]
This is an issue where the community could help (testing/selecting).

**Comment by 0keh** [comment]
Most themes are usable. The dark theme 'Xfce-dusk' is maybe a bit too dark.
But every theme I tried, the font color in qubes-manager is unreadable because of white fore- and background or, if I use the Xfce-dusk theme, the font color of the bars in qubes-manager is not readable anymore.
The qubes-manager is overall more affected as the most application of dom0. O.o

**Comment by cartman4** [comment]
in R-4.0-RC1 adwaita-dark  seems to look ok.

**Comment by mannp** [comment]
Its all a bit of a mess really.

The network icon has a white background so look terrible with any dark theme.

I am really enjoying qubes 4rc1 and updates, but compared to my fedora 26 desktop, qubes looks like its from the dark ages on top, while underneath its state of the art.

**Comment by andrewdavidwong** [comment]
> The network icon has a white background so look terrible with any dark theme.

This issue is tracked separately in #2846.

**Comment by ninavizz** [comment]
Is this actually/already built-into `4.1`?

**Comment by andrewdavidwong** [comment]
> Is this actually/already built-into `4.1`?

I think so. I'm using a dark theme in dom0. I customized it, but I don't think I had to do anything to make all the Qubes widgets or the Qube Manager compatible with it.

So, I'll close this as resolved. If anyone believes the issue is not yet resolved, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by quantumpacket** [comment]
> So, I'll close this as resolved. If anyone believes the issue is not yet resolved, please leave a comment, and we'll be happy to reopen this. Thank you.

I'm using 4.1 and have chosen the Adwaita-dark theme, but not all windows are being themed dark.

**Dark Theme Works:**
- Qubes Update

**Dark Theme Does Not Work:**
- Qubes Backup Restore
- Qubes Global Settings
- Qubes Manager
- Template Manager
- Create New Qube

I thought at least Qubes Manager would work since it's mentioned in this thread. I've tried switching to other dark themes, but they too don't work.

**Comment by andrewdavidwong** [comment]
> > So, I'll close this as resolved. If anyone believes the issue is not yet resolved, please leave a comment, and we'll be happy to reopen this. Thank you.
> 
> I'm using 4.1 and have chosen the Adwaita-dark theme, but not all windows are being themed dark.
> 
> **Dark Theme Works:**
> 
> * Qubes Update
> 
> **Dark Theme Does Not Work:**
> 
> * Qubes Backup Restore
> * Qubes Global Settings
> * Qubes Manager
> * Template Manager
> * Create New Qube
> 
> I thought at least Qubes Manager would work since it's mentioned in this thread. I've tried switching to other dark themes, but they too don't work.

It appears that the reason for this difference between 4.0 and 4.1 might be captured in #7389.

**Comment by DemiMarie** [comment]
> > 
> 
> It appears that the reason for this difference between 4.0 and 4.1 might be captured in #7389.
> 
> @DemiMarie, @SvenSemmler: Does it make sense to keep both of these issues open?

I don’t think so.

**Comment by SvenSemmler** [comment]
> > @DemiMarie, @SvenSemmler: Does it make sense to keep both of these issues open?
> 
> I don’t think so.

Agree.
