### ISSUE TITLE
"Klipper" system tray icon is transparent

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2216]
#### Qubes OS version (e.g., `R3.1`):

`R3.2-rc2`

![Screenshot](https://i.imgur.com/VKQ3aeW.png)
(The "Klipper" icon should appear to the left of the sound icon.)

[Reported](https://groups.google.com/d/msgid/qubes-users/452c5988-6dae-9402-34b3-0e3837dbe35b%40openmailbox.org) by @evadogstar

**Comment by andrewdavidwong** [comment]
Other systray icon issues (possibly related?): #2242, #2264, #2268

**Comment by adrelanos** [comment]
`sdwdate-gui tray icon invisible in Debian stretch` (Whonix [T598](https://phabricator.whonix.org/T598)) might result from the same root cause.

Can you reproduce this at the moment? If so, can you please purge the `sni-qt` package? (`sudo apt-get purge sni-qt`)

Then after reboot the issue might be gone. That would help to pinpoint the issue. Removal of the `sni-qt` package however isn't a solution. A workaround at best because that breaks passive popups systemd wide (for some or all applications [/ systrays]).

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
