### ISSUE TITLE
Installer media check consistently fails at 4.8%

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2246]
#### Qubes OS version (e.g., `R3.1`):

`R3.1`

#### Problem description:

Gabriele Bini wrote:
> I have exactly the same problem. This is what I did:
> 1. I downloaded the Qubes-R3.1-x86_64.iso ISO from the Torrent.
> 2. I checked the signature and the hash values in the DIGEST file (I checked just the hash values in a second PC) and everything was fine.
> 3. I used dd to copy the ISO in a USB flash drive (Sony 8Gb)
> 4. When I booted from the USB I tried the “Verify and Install” option but, exactly at 4,8% (as for Cory Nelson) the check failed. There was a message of this type (copied by hand):
> Failed to start media check on /dev/sdc
> See 'systemctl status checkisomd5@-dev-sdc.service' and 'journal.ctl-xn'  for details
> 5. I couldn't check anything because the system was halted

[Original message](https://groups.google.com/d/msgid/qubes-users/6cf64646-8d0e-4339-ada4-ef26e0ebfe47%40googlegroups.com)

---

#### Related issues:

Possibly related to #2051.

**Comment by marmarek** [comment]
> I made another test: I copied the same ISO on another USB Flash drive (8Gb Kingstone) from a different computer (Mint 17.1), then I tried again the installation on the previous computer: this time it worked!

**Comment by ThomasWaldmann** [comment]
Just had the same thing. GPG sig valid, sig check by qubes invalid at 4.8%.

Potential issue: inserting the stick into a windows 10 machine once after creating, before using at (yeah, bad idea).

I just recreate the stick to check that...

**Comment by eduncan911** [comment]
I ran into this as well.

* Used Etcher on macOS to create USB.
* Put into my Windows 10 tablet, and missed the startup process and it booted to Windows.  
* Rebooted to bios, booted up, 4.8% failure every time.

The trick for me, because this tablet requires a boot to Windows before rebooting to F12 selection, is to:

* boot Windows first
* reboot into BIOS
* insert USB
* reboot back to F12 boot selection screen.

And now it passes.

**Comment by andrewdavidwong** [comment]
So we've learned that if you merely insert your USB drive into a Windows machine and take no further action, Windows will silently modify the contents of your drive? Interesting.

**Comment by eduncan911** [comment]
Yep. I dont think I even signed in, just booted up to login prompted and restarted to get to the USB stick.

**Comment by marmarek** [comment]
> So we've learned that if you merely insert your USB drive into a Windows machine and take no further action, Windows will silently modify the contents of your drive? Interesting.

Yes, we already know this: https://github.com/QubesOS/qubes-issues/issues/2051#issuecomment-224249753

There was some attempt to prevent this behavior - basically already included the files Windows adds in the image, but it wasn't enough. It also alter modification time of it (or such)... There are some more ideas how to mitigate this (like reverse known modifications before validation).

Anyway, it's a duplicate of #2051

**Comment by andrewdavidwong** [comment]
Ah, you're right. That was so long ago that I forgot.

**Comment by zylstra** [comment]
So the option of "Test this media & install Qubes [...]" doesn't work with a USB created in Windows?  Does the "Install Qubes [...]" option work?  Not sure I understand what to do here.

Should the Installation Guide (https://www.qubes-os.org/doc/installation-guide/) mention this?  Should I add this information to the Installation Guide myself?

Should the Installation Guide include directions to disable Secure Boot and Enable legacy mode, or CMS as it is also commonly called?  

Should the website include a link to support, wherever it may be determined to be given, in the footer?  Where is support given by the way?  The help link at the bottom of the installation guide page just links to documentation again.  :/

etc. ...

**Comment by scalablecory** [comment]
@zylstra I was unable to create a bootable USB via Windows. I had to juggle an Ubuntu live USB to run `dd` from Linux.

**Comment by andrewdavidwong** [comment]
Since this issue is closed as a duplicate of #2051, I suggest instead commenting on #2051, which is open.

> Should I add this information to the Installation Guide myself?

A PR adding some information on this might be a good idea. If you haven't already, please take a look at our [Documentation Guidelines](https://www.qubes-os.org/doc/doc-guidelines/) for information about contributing.

> Should the website include a link to support, wherever it may be determined to be given, in the footer? Where is support given by the way? The help link at the bottom of the Installation Guide page just links to documentation again. :/

As is common among free and open-source software projects, support is primarily given by knowledgeable members of the community through our [mailing lists](https://www.qubes-os.org/mailing-lists/).

**Comment by adler-amorette** [comment]
The UEFI on my Gigabyte motherboard creates the same problem.

I wrote the installer image onto a usb drive in Linux with `dd`, detached and reattached the drive, checked with `vmtouch` that it's not cached, verified with `dd ... | sha256sum` that it indeed contains the image.

When booting from that drive and choosing "Test media", the check fails at 4.8%

Turns out only two specific bytes change:
- at offset 446 the byte is changed from `0` to `0x80` (first entry in MBR partition table becomes bootable)
- at offset 462 the byte is changed from `0x80` to `0` (second entry becomes non-bootable)

I determined this by comparing the original `.iso` against the modified one with `cmp -l <orig> <mod>`.

The difference can also be seen with `parted`:
- original has empty "Disk Flags"
- modified has "Disk Flags: pmbr_boot"

Disabling CSM(BIOS compatibility) makes no difference.
Choosing UEFI or non-UEFI entry in the boot menu, with CSM enabled, makes no difference.

**Comment by marmarek** [comment]
@adler-amorette firmware in your system clearly does something wrong, it marks GPT protective partition as bootable...
At this point, you have several options:
- complain to your firmware vendor (Gigabyte?)
- use USB stick with write-protect switch
- skip media verification on installer startup

**Comment by alimirjamali** [comment]
It is a well known behaviour of Gigabyte motherboards. We have it analysed on forum:

https://forum.qubes-os.org/t/qubesos-test-media-always-fails/28166/13
