### ISSUE TITLE
bug in qubes-upgrade-vm package

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#2250]
#### Qubes OS version (e.g., `R3.1`):

R3.2rc2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

user-created R3.1 Fedora-23 template

---
### Expected behavior:

upgraded template will have access to 3.2rc2 sources.
### Actual behavior:

upgraded template does not have access to 3.2rc2 sources.
### Steps to reproduce the behavior:

create R3.1 fedora template, [follow R3.2 upgrade instructions](https://www.qubes-os.org/doc/upgrade-to-r3.2/#tocAnchor-1-1-2), sources in template (`/etc/yum.repos.d/qubes-r3.repo`) not updated to R3.2.
### General notes:

upgraded R3.1 user-created Debian-8 templates did not run into this issue. 

The upgraded user-created Fedora-23 template still pointed to r3.1 in `/etc/yum.repos.d/qubes-r3.repo` which when edited to point to R3.2 fixed the problem. So it seems like a problem with `qubes-upgrade-vm`.

**Comment by marmarek** [comment]
Did you made any manual modifications to that file? In such a case, `rpm` will not override it and store new content in `/etc/yum.repos.d/qubes-r3.repo.rpmnew` file.

**Comment by mfc** [comment]
nope no `/etc/yum.repos.d/qubes-r3.repo.rpmnew` was created. for further context in case it's helpful this was from a fresh R3.2rc2 installation with R3.1 templates that were then upgraded (i.e. I did not in-place upgrade Qubes from R3.1 to R3.2rc2).

**Comment by marmarek** [comment]
What version of `qubes-core-vm` package do you have? Did you actually finished the upgrade (including the last step: `dnf upgrade --refresh`)?

**Comment by mfc** [comment]
how do i check the version? `qubes-core-vm --version` doesn't work. yes i completed the upgrade including running `dnf upgrade --refresh`.

**Comment by marmarek** [comment]
On Thu, Aug 18, 2016 at 02:42:52AM -0700, Michael Carbone wrote:
> how do i check the version? `qubes-core-vm --version` doesn't work. yes i completed the upgrade including running `dnf upgrade --refresh`.

`rpm -q qubes-core-vm`

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment]
qubes-core-vm-3.2.9-1.fc23.x86_64

but I updated the template after changing the sources so that may not have been the version when the problem was encountered.

**Comment by marmarek** [comment]
> qubes-core-vm-3.2.9-1.fc23.x86_64

Ok, this is the right version for R3.2. Maybe you have modified
`/etc/yum.repo.d/qubes-r3.repo` somehow? You can verify if the file
content matches what was in the package using  `rpm -V qubes-core-vm`.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
