### ISSUE TITLE
R3.1 laptop fans won't start; becomes too hot to use

### ISSUE THREAD

**Issue by chewzerita** [QubesOS/qubes-issues#2258]
#### Qubes OS version R3.1

---

### Expected behavior:
I expected that Qubes would automatically deal with thermal throttling / turning on fans.
### Actual behavior:
The CPU doesn't slow down, and the fans do not start up either. 
### Steps to reproduce the behavior:
Just regular usage.
### General notes:
I am using a Thinkpad T420

**Comment by andrewdavidwong** [comment]
Qubes should automatically handle thermal throttling and fans. No one else has reported this on R3.1 (as far as I'm aware), and I have not experienced it there either, so it's very likely that the issue has to do with your specific hardware/firmware configuration.

Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
