### ISSUE TITLE
Installing Qubes Windows Tools causes networking to stop working

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2263]
#### Qubes OS version (e.g., `R3.1`):

`R3.2-rc2`

---

Note: (User installed `qubes-windows-tools` from `current-testing`.)

[On 2016-08-21 17:22, neilhardley@[...].com wrote:](https://groups.google.com/d/msgid/qubes-users/48fc8ee9-b59d-4069-a853-4e4b3090649d%40googlegroups.com)

> I installed it. Networking was working prior to Windows Tools. After installing it, the network no longer works.
> 
> "no network access" when you click the network icon in the taskbar.

**Comment by 0spinboson** [comment]
Networking stopped working on the 2nd reboot after tools installation as well, due to the gateway information disappearing from the network adapter tcp/ipv4-settings. After entering it manually everything was once again fine.

**Comment by marmarek** [comment]
Which version of windows tools?
/cc @omeg

**Comment by 0spinboson** [comment]
The person who first reported this got his tools
qubes-dom0-current-testing, and so did I. (3.2.1, for me.)

**Comment by omeg** [comment]
Are you sure the network is really not working (the tray icon may show an exclamation mark even if it's working)?
What does ipconfig show?
Is the Xen PV network device working correctly in the Device Manager?
And lastly, network-setup logs might be helpful.

**Comment by 0spinboson** [comment]
@omeg: I asked the person who originally reported this to check whether the gateway information was 'there', but he hasn't responded back yet (in the qubes-users group). But for me, it was just a case of the gateway info going missing, and having to manually enter it.

**Comment by LordJashin32** [comment]
I was alarmed by this until i just figured out it was cosmetic. Haha. Here's also straight from the read me on Qubes Tools ISO:

II. Known issues
----------------

1) The Xen PV disk driver is disabled by default. This is because it causes
   a BSOD after installation in Qubes. However, it seems to work fine after
   that, so you may want to use it (for better performance and the ability
   to use qvm-block). MAKE SURE TO BACK UP YOUR VM FIRST in case something
   goes very wrong.
   
2) Windows shows an exclamation mark on the network icon in the system tray,
   but this is only a **cosmetic issue** (network configuration is being set
   properly).

Just wanted to point this out for anyone else who is trying to figure this out accidently. Lol.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
