### ISSUE TITLE
systray tooltips broken, showing only 'VMapp command'

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2264]
#### Qubes OS version (e.g., `R3.1`):

R3.2 with testing repository
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

debian-8

---
### Expected behavior:

When hovering over a systray icon, the tooltip should show whatever the tooltip actually is (just like any operating system).
### Actual behavior:

When hovering over a systray icon, the tooltip only says `VMapp command`.
### Steps to reproduce the behavior:

Start a Debian 8 based VM.

`sudo apt-get install klipper`

Then start from command line, run `klipper`.

Also happens in sys-whonix with `sdwdate-gui`.
### General notes:

Did not notice this before R3.2. (Does not mean, it did not happen there.)

**Comment by adrelanos** [comment]
Issue persists after reboot.

**Comment by andrewdavidwong** [comment]
Other systray icon issues (possibly related?): #2216, #2242, #2268

**Comment by marmarek** [comment]
This is a "feature" of new KDE - the icon there is no longer what
application places there, but a copy of that window. And a tooltip is a
title of that window, which is unset in most cases ("VMapp command" is
qubes-specific placeholder for unset window title). This KDE behaviour
is totally non-standard.

Just one another reason why we've chosen to move away from KDE being
default environment.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by ttasket** [comment]
This is good from a security standpoint, but the vm name should be _added_ to the real tooltip instead of the former replacing the latter.

**Comment by Zrubi** [comment]
This issues is not template specific. I have this issue using fedora based templates as well.
It is related only the to the new KDE 5 System Tray

**Comment by unman** [comment]
@andrewdavidwong Can you remove the Debian and Whonix labels, and the xfce4 one too? I guess we need a kde5 label to cover this one.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
