### ISSUE TITLE
Why does qvm-run from VM to VM take a quarter of a second?

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#2274]
Latest R3.2b packages.  `qvm-run somevm true` (with policy already accepted) takes 0.260 s.  This is making bombshell take about a half a second just to complete `true`.

Thanks.

**Comment by marmarek** [comment]
Most of the time (all of it?) is spent on running qrexec-policy. It is
standalone python script and I bet importing modules takes the most of
its run time. It can be improved by implementing simple
qrexec-policy-daemon, which would respond for policy requests, but
currently it is rather low priority task. If you like, you can work on
this...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
