### ISSUE TITLE
Firstboot: option to create "USB qube" is disabled when using USB mouse during installation

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2276]
... while it should only be disabled if USB keyboard is being used.

**Comment by marmarek** [comment]
Are you using wireless mouse? Or some other fancy one? Some of them
advertise being both keyboard and mouse. You can check that using
`udevadm info -q all -n /dev/input/eventX` (replace X with your mouse
device number - you can check all of them).

For example for Logitech receiver (with only mouse connected) I
get this:

    (...)
    E: ID_INPUT=1
    E: ID_INPUT_KEY=1
    E: ID_INPUT_KEYBOARD=1
    E: ID_MODEL=USB_Receiver
    E: ID_MODEL_ENC=USB\x20Receiver
    (...)

and this:

    (...)
    E: ID_INPUT=1
    E: ID_INPUT_MOUSE=1
    E: ID_MODEL=USB_Receiver
    E: ID_MODEL_ENC=USB\x20Receiver
    (...)


Some workaround would be to add a "recheck" button to give a chance to
unplug USB keyboard (or something pretending to be one) and then enable
USB qube.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
