### ISSUE TITLE
The new pinkish decoration color under Xfce4 is ugly

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2279]
On a serious note: we should ensure the colors match the padlock icon colors.

**Comment by marmarek** [comment]
In fact now decoration color is taken from exactly the same place as
icon colors. But then the chosen decoration theme is applied (actually
only "value" part of it), so it may appear to be brighter depending on
your theme.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarta** [comment]
Given that there were no further bug reports, I'm closing this one.
