### ISSUE TITLE
Use default allow for qubes.FileCopy service

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2280]
We want to minimize the amount of prompts which only train the user to hit yes to get work done. qubes.FileCopy has been designed to be safe even if the srcvm is malicious, so it's rational to use default allow here IMHO.

**Comment by andrewdavidwong** [comment]
This seems dangerous, since it makes it easy for a novice user to unwittingly transfer a file from a less secure domain to a more secure domain, then (wondering what this curious new file is that mysteriously appeared in the more secure domain) open it. Prompt fatigue is already handled by providing the option to choose "always allow." This keeps the user in control of deciding whether she considers prompt fatigue a bigger risk than accidentally moving files to the wrong domains.

**Comment by marmarek** [comment]
Additionally, and more importantly, having "allow" by default here may compromise user privacy - for example if compromised VM (DispVM / Whonix VM / ...) can trivially leak traces to other, persistent VMs, which later could be correlated with the user. The same applies in opposite direction - compromised sys-net could place some indicator in almost every VM, to correlate user actions.

So, I agree that we shouldn't enable this by default unconditionally. Maybe create "allow" rules for  default VMs (using mgmt stack)? Or somehow encourage users for using "always allow" for "safe" transfer directions (and make accidental confirmation harder, https://github.com/QubesOS/qubes-issues/issues/1166#issuecomment-137818344)?

**Comment by Kozuno** [comment]
From an unexperimented and non developper Qubes user's point of view, I don't think this would change much security for people unconcerned about documentation and risk exposure reduction by always copying files from a more trusted VM to a less secured. Even for people concerned by Qubes documentation but without good knowledge on how information travel through a local network, I think it would rather be a nice improvement to utility than a real risk reduction.

I mean everyone knows the UAC on Windows or that Windows firewall asks automatically for some programs if users want to add network rules to use them. Would it change their habits if Windows was asking many times if they're sure to do so ? No, because anyway they just want to get rid of warnings and reduce fatigue.

From my newbie perspective, I think Qubes developpers should keep focusing their efforts in terms of security improvement on all that is Template-related, and documentation is already very well written on this subject. With many others original aspects, Templates are what makes Qubes really unique as an OS and entertaining :)
Because anyway you can't protect users taking unconsidered risks, and I don't know, if you didn't google once iptables or at least get information on how to reduce exposure and understand how firewall works in Qubes OS, then you're probably not in the right place lol.

So yes, those warning prompts would make sense for copies to Templates, but not really in others VMs imo, but this is just a suggestion, I don't know if this might be possible in coding development.
I'm just saying that because for instance I would appreciate to copy a bit easier files from my vault VM to configure VPN on a proxyVM when I reinstall new Qubes releases, so I have to say I rather agree with general rootkovska :) (who wouldn't ? I don't want to stay in the matrix lol ^^).

**Comment by tasket** [comment]
Although prompt fatigue is a valid security concern, I think we should respectfully pass on this idea. Marek's initial point is valid, and its worse to create an atmosphere where users fear correlation attacks and feel they need to be adjusting and re-adjusting this setting when they manage their VMs.

The current default best balances usability and security because fundamentally there is no way for Qubes to guarantee that even the most trusted domUs are not compromised (whether or not the malware is disk-based or RAM-only).

OTOH, having a dom0 qvm-copy that can copy between 2 domUs without prompts could be nice (even though qvm-run/cat works).

IMHO -- I think ITL needs to be very careful about UX enhancements for two reasons: 1) FOSS does poorly here in the first place and the offerings are chaotic, and 2) this is unfortunately not your specialty and its easy to underestimate the difficulty of envisioning and implementing operating system UIs. Even so, Qubes concept did hit on something rather unique: GUI that is essentially vertically integrated with the deep security contexts in the system. As an avid watcher of MS and Apple designs since the 80s, and the fumblings of FOSS UIs, I see the current situation as fairly decent in addition to offering some exciting visualization/monitoring possibilities for the future.

**Comment by WhiteWinterWolf** [comment]
Hello,

Let's say I download a file from the web (let's say in an AppVM called _web-untrusted_) and archive it in a network-less AppVM (let's say it is called _archive_) with other files I want to store out of reach of browser and other network-enabled software.

Let's say this file happens to bring a malicious payload. My expectation is that, while the file may potentially corrupt, infect or delete other files in the _archive_ AppVM (thus forcing me to restore a sane backup of this AppVM), this AppVM being network-less the malicious payload will have no easy way to exfiltrate the content of this AppVM.

If I understand correctly this suggestion, such malicious payload would now be able to dump the whole content of the _archive_ AppVM inside _web-untrusted_ AppVM (maybe dozen of GB, hundreds of files) without the user noticing, making them reachable from a networked and potentially exploited browsers or email software (the interest of exploiting browsers and email software is that it allows in turn to infect legitimate files downloaded by the user, making the second stage of this attack easier).

Would such threat make sense, or would it fall outside of Qubes scope? I'm asking this because of [this post](https://theinvisiblethings.blogspot.fr/2011/03/partitioning-my-digital-life-into.html):

> I would like to make it clear that we are not interested in eliminating cooperative covert channels between domains in Qubes any time in the near future, and perhaps in the long term as well. I just don't believe into such approach, and I also don't like that this approach does nothing to preserve the integrity of the more-trusted domain  it only focuses on the isolation aspect. 

From this point of view I understand the logic behind eliminating the prompt, however personally I would not feel safe knowing that large amount of data may be transferred from one AppVM to another without me knowing it, nor would I feel safe in using an OS with what I perceive to be insecure defaults for the sake of "usability".

Speaking of usability, I think the prompt should not be deleted but instead be improved to better highlight the source and destination AppVM. I agree with Andrew about the "Always allow" button.

Regards,

**Comment by marmarek** [comment]
Ok, I think we all agree it isn't the best idea to implement this change.
