### ISSUE TITLE
Text based installation not working

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#2297]
#### Qubes OS version (e.g., `R3.1`):

R3.2-rc3
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

---
### Expected behavior:

Complete specification of installation parameters possible in text based installation - perform installation
### Actual behavior:

When the Xserver for installation cannot be started, installation drops back to a text based sequence, which is a very good feature. In this case, however, the script cannt completed due to the following behaviour:
Installation parameter 5 (target device / filesystem) cannot be completed. There is no possibility to specify whether encryption should be used, and there is no prompt for a passphrase. The script then complains that encryption was specified and no passphrase was given. As this parameter cannot be completed, installation has to be aborted.
### Steps to reproduce the behavior:

Start installtion in an environment where the Xserver cannt be started. Trying installation under Virtualbox does the trick. (It does not mater that Qubes is not supported in this environment, as this behaviour is to be expected whenever no graphic installation is possible.)
### General notes:

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
