### ISSUE TITLE
cannot find character device

### ISSUE THREAD

**Issue by petertyyseng** [QubesOS/qubes-issues#2299]
**Qubes OS version** 
R3.2-rc3

**Affected TemplateVMs** 
win7 standaloneVM

**Expected behavior:**
 1. connect qrexec 2. GUI connect when I start window VM 

**Actual behavior:**
There is error: internal error : cannot find character device <null>

**Steps to reproduce the behavior:**

1. start the window VM from command line:
2. It shows ERROR: Cannot execute qrexec-daemon! 
3. Access VM console: [user@dom0 ~]$ virsh -c xen:/// console my-vm

**Comment by marmarek** [comment]
Have you installed Qubes Windows Tools? Using qrexec require it. If you
don't want, do enable qrexec (qrexec_installed setting using qvm-prefs
tool).

As for console - HVM domains do not have text console, so `virsh
console`
do not work by design.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by petertyyseng** [comment]
I did installed Qubes Windows Tools, both **sudo qubes-dom0-update qubes-windows-tools** and
**sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing qubes-windows-tools** reply
Last metadata expiration check: 0:01:15 ago on Fri Sep 9 14:14:06 2016
No package --enablerepo=qubes-dom0-current-testing available
No package Qubes Windows Tools available
Error: Unable to find a match

After I enable qrexec with **qvm-prefs -s my-vm qrexec_installed True**
I restart my-vm and got message popup:
Cannot execute qrexec-daemon!

**Comment by andrewdavidwong** [comment]
> No package --enablerepo=qubes-dom0-current-testing available

This looks like a mistake. That option should not be interpreted as a package. Are you sure you typed in the command correctly? For reference, it should be done as documented here: https://www.qubes-os.org/doc/windows-appvms/#tocAnchor-1-1-2

**Comment by petertyyseng** [comment]
![p_20160910_114817](https://cloud.githubusercontent.com/assets/22073087/18407787/88723fdc-774d-11e6-83b0-c7066568494b.jpg)
