### ISSUE TITLE
Installer fails to get template package from anaconda [Errno 256]

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2308]
#### Qubes OS version (e.g., `R3.1`):

`R3.1`
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

`fedora-23`

---
#### Problem description:

On 2016-09-08 20:17, Jodie wrote:

> I get past the configuration window, but the install is currently failing on the installation of the
> qubes-template-fedora-23 package, with this error message:
> 
> "The following error occurred while installing. This is a fatal error and installation will be aborted.
> 
> getPackage error: failure: Packages/q/qubes-template-fedora-23-3.0.5-201603081705.noarch.rpm from anaconda: [Errno 256] No more mirrors to try."

[Picture of error message](https://13366229192823780453.googlegroups.com/attach/50456be8bd8d8/IMG_0715.JPG?part=0.1&view=1&vt=ANaJVrHAN7p0En5WkSbcX9vcwSz5q1S8UJIDlcsa81sNugHTMXFvQaqMakH7t27o7Hq-wgiGTl3X6lYauK-jq0g4Px44_SBcqY8QYUvmiUwc2yVLb-_PNXQ)

[Full thread](https://groups.google.com/d/topic/qubes-users/0kvPMr6Jsog/discussion)

**Comment by unman** [comment]
@andrewdavidwong   I Have not been able to test this - In any case I have no idea what the appropriate response should be, because I dont understand how the iso can pass the tests and then fail with missing files. 
Particularly odd since (from the thread) the install **did** succeed using the same medium just by attempting to repeat a number of times.  This suggests to me a fault in the install medium.
I would be tempted to close this.
