### ISSUE TITLE
Use bind-dirs to handle crontab persistence

### ISSUE THREAD

**Issue by jbwells** [QubesOS/qubes-issues#2327]
#### Qubes OS version (e.g., `R3.1`):

R3.2-rc2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

AppVM using debian-8 TemplateVM

---
### Expected behavior:

Whenever cron is running, it should obey a crontab installed via the crontab program.  It should also be possible to remove a crontab while cron is not running.
### Actual behavior:

Crontab files installed while cron is not running are hidden by a directory mounted over them when cron is started.
### Steps to reproduce the behavior:

  sudo systemctl stop cron
  crontab FILE
  sudo systemctl start cron
### General notes:

See /lib/systemd/system/cron.service.d/30_qubes.conf.

This is very confusing when trying to debug why your cron jobs are not running!

---

**Comment by jbwells** [comment]
I forgot to mention: This problem also mean that you can not configure cron jobs in the TemplateVM that will run in AppVMs based on it.

**Comment by unman** [comment]
@jbwells @andrewdavidwong 

This isn't a Debian specific issue, and I'm not convinced it's a bug - it's a feature of the normal Qubes treatment of template based qubes. The statement of expected behaviour seems to me to be inappropriate for Qubes. 
The use of /rw/cron enables something approaching a standard use of cron. Since a standard crontab file would disappear on reboot, the /rw/cron files enable cron jobs to persist for a template based qube.

It is possible to configure cron jobs in a Template, using the /rw/cron mechanism, and they will run in any qube created using that template. Like changes in /home, later editing of files on the template will not feed through to the qube after it has been created.

**Comment by andrewdavidwong** [comment]
I can see the arguments on both sides. Ultimately, this may be more of a feature request than a bug report. @marmarek?

**Comment by marmarek** [comment]
Since we have [bind-dirs](https://www.qubes-os.org/doc/bind-dirs/), it should be quite easy to move that cron handling

**Comment by adrelanos** [comment]
@marmarek https://github.com/QubesOS/qubes-doc/pull/199#issuecomment-252912201

> I think it would be better to package bind-dirs configuration for cron, as part of QubesOS/qubes-core-agent-linux#19, instead of relying on user to manually do it.

**Comment by marmarek** [comment]
It's done.
