### ISSUE TITLE
provide GUI mechanism (Qubes Manager, Settings, etc) for enabling USB keyboard

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#2329]
I couldn't find a ticket tracking this. The options available to the user for [enabling USB keyboard](https://www.qubes-os.org/doc/usb/#tocAnchor-1-1-4) should be available to the user through a GUI, with appropriate warning.

**Comment by jpouellet** [comment]
Here's some more wishful thinking:

Even better would be to detect how the keyboard is attached during install and set this automatically. I have had friends reinstall without sys-usb because they were unable to enable it without a working keyboard with which to do so.

Additionally, some informative message could be shown during install or on first boot stating that this is the case on your system, and pointing them to [the security warning in the docs about usb keyboards making sys-usb more trusted](https://www.qubes-os.org/doc/usb/#security-warning-about-usb-input-devices) (or [perhaps duplicate the warning directly in a message rather than point them at the docs](https://github.com/QubesOS/qubes-app-linux-input-proxy/pull/4)).

I believe it's better to give people system with a high-liability sys-usb than have Qubes not work at all by default for their hardware. See also https://github.com/QubesOS/qubes-issues/issues/2736

**Comment by mfc** [comment]
I would make that a separate ticket.

**Comment by marmarta** [comment]
So, this is in the new global config tool (no CLI needed), closing this.
