### ISSUE TITLE
Xfce4 window buttons hardly visible

### ISSUE THREAD

**Issue by bisam** [QubesOS/qubes-issues#2357]
#### Qubes OS version (e.g., `R3.1`):

3.2

---
## In the new xfce4 window bar the buttons for maximizing, closing etc. fade into the background so they are not clearly visible. The darker the window color is, the harder it gets to recognize the buttons.

See this screenshot: 
![xfce-buttons](https://cloud.githubusercontent.com/assets/5684437/19019903/e0b6cec8-8897-11e6-99e7-ae28acc852d4.png)

**Comment by marmarta** [comment]
Is this still an issue? I'm unable to reproduce it even with 'black' colored VMs.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
