### ISSUE TITLE
qvm-grow-root can fail silently for a TemplateVM

### ISSUE THREAD

**Issue by jbwells** [QubesOS/qubes-issues#2359]
#### Qubes OS version (e.g., `R3.1`):

R3.2-rc2 with all updates
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

debian-8 (probably all templates)

---
### Expected behavior:

"qvm-grow-root --allow-start debian-8 12G" should either grow the filesystem or give an error message.
### Actual behavior:

It fails silently if any AppVMs based on the TemplateVM are running.
### Steps to reproduce the behavior:
1. Create an AppVM based on debian-8 (or probably any template).
2. Start that AppVM.
3. Run "qvm-grow-root --allow-start debian-8 12G".
4. Observe that the command in step 3 gives the appearance of having succeeded.
5. Observe that the filesystem in debian-8 is not any bigger.
### General notes:

Until you stop all the AppVMs that use the TemplateVM and then restart the TemplateVM, the TemplateVM wlll think the partition has not grown any larger, and it therefore won't grow the filesystem when resize2fs is run.

I haven't checked whether qubes-manager handles this case any better.

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
