### ISSUE TITLE
Improve backup passphrase UX

### ISSUE THREAD

**Issue by petaramesh** [QubesOS/qubes-issues#2365]
### Expected behavior:

I would like to perform VM backups without encryption (as I'm sending backup to an already LUKS-encrypted device).
### Actual behavior:

Even if the `Encrypt backup` check box is left unchecked, the GUI's [`Next>`] button will stay greyed out, unless 2 corresponding passwords are entered. (Then I dunno if they are actually used to encrypt the backup, or not...)
### Steps to reproduce the behavior:

Try to perform a backup without encryption...

**Comment by adrelanos** [comment]
It's used for data integrity check.

I agree, this is an usability issue.

**Comment by andrewdavidwong** [comment]
As @adrelanos points out, a password is required even if you opt not to use encryption, since the password is used to check the integrity of the backup. IIRC, you should be able to use an empty password for this if you want.

I'll change the title of this issue to reflect the usability issue.

This would probably be a good candidate for an explanatory tooltip (#2211), so that we can explain to users what's going on here (i.e., why a password is required even without encryption).
