### ISSUE TITLE
Missing instructions for adjusting partition table and filesystem after growing HVM disk image

### ISSUE THREAD

**Issue by psionin** [QubesOS/qubes-issues#2378]
https://www.qubes-os.org/doc/resize-disk-image/

Missing instructions after "The partition table and file-system must be adjusted after this change:"

under the **HVM disk image** section

Please fix.

**Comment by unman** [comment]
@psionin @andrewdavidwong  
There are instructions for Windows 7 and FreeBSD - do we need to add instructions for Linux or just a line that says something like "use the appropriate commands for your OS".
Or is the issue that the format of the headings doesn't make it clear that those are subheadings, following the colon?

**Comment by andrewdavidwong** [comment]
@unman: It could be either or both. I'll add clarifications on top of your PR.

**Comment by psionin** [comment]
I was coming from using the Qubes VM Manager to resize a VM using the GUI. It does all the steps necessary except the last one, that needs to be done inside the VM.

`sudo resize2fs /dev/mapper/dmroot` is the specific command, which could save some time if included in the doc or VM Manager notification.

**Comment by unman** [comment]
@psionin @andrewdavidwong  The problem is that in a HVM we have no idea how the disk is partitioned or used. For example, in a default Debian install, there would be /root and /swap in an extended partition. Growing the image creates free space at the _end_ of the disk. resize2fs doesn't touch partitions so in this case would be no use.
There really isn't a general answer to this - it's so dependent on how the disk is partitioned in the first place, and where the user wants to use the new space.
