### ISSUE TITLE
Consider better alternative to setting default "runlevel" in /etc/systemd/system

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#2392]
core-vm.spec in qubes-core-agent-linux screws with /etc/systemd/system:

```
# Set default "runlevel"
rm -f /etc/systemd/system/default.target
ln -s /lib/systemd/system/multi-user.target /etc/systemd/system/default.target
```

This is unnecessary.   A simple boot command line parameter "systemd.unit=multi-user.target" does the trick.  Of course, the fix needs to be applied in qubes-core-dom0 as well.

**Comment by unman** [comment]
@Rudd-O 

> core-vm.spec in qubes-core-agent-linux screws with /etc/systemd/system:

No it doesn't - this is the canonical way of changing default runlevel.
See [here](https://www.freedesktop.org/wiki/Software/systemd/FrequentlyAskedQuestions/)
No fix is needed.

**Comment by Rudd-O** [comment]
This bug was more about NOT changing the default runlevel, but rather providing a graphical.target that did the right thing, instead of trying to override stuff in the base image.

How should I summarize that idea in the bug's title?

**Comment by andrewdavidwong** [comment]
@Rudd-O: How's that?

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
