### ISSUE TITLE
Trusted image conversion should explicitly label trusted output and preserve original filename

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2437]
#### Qubes OS version (e.g., `R3.1`):

R3.2

---

There are (at least) three reasons in favor of this change:

1. To maintain consistency with PDF conversion.
2. To make it unmistakable that the conversion has occurred by looking *only* at the *produced* file.
3. Not to interfere with (i.e., rename) the original file.

[On 2016-11-15 06:00, '091823'04918'032948'1093248018243 wrote:](https://groups.google.com/d/msgid/qubes-users/7b5d7c23-3499-4f2e-adda-de6277d1d2d1%40googlegroups.com)
> wow cool, I found out that now QR32 also can convert pictures into a trusted image.
> 
> Only I got confused, because after the conversion, I got two files:
> 
> i) xy.jpg
> ii) xy_untrusted.jpg
> 
> In the PDF work flow it was the opposite:
> 
> i) xy.pdf
> ii) xy_trusted.pdf
> 
> I liked the last work flow much better, because after the conversion, I can see it, that this conversion took really place!
> (especially after the copying around from files, so it will be easy to lost the overview...)
> 
> I don't found some docu for the untrusted.jpg, this means I must wipe the xy_untrusted.jpg and keep the xy.jpg, which is now the 100% dead jpg picture, right?

---

#### Related issues:

#1995

**Comment by unman** [comment]
Actually, there is a difference in workflow: the PDF converter moves the original file to an "Untrusted " folder, whereas the image converter leaves both in place, and leaves it to the user to deal with them.
It seems more likely that users will want to keep the original PDF, rather than the original image, because of the fact that there is more functionality in the original.
I like having the file marked "untrusted", and this is implicit in the PDF case because of the folder name.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
