### ISSUE TITLE
UEFI Installation Disallows Removable Boot Device

### ISSUE THREAD

**Issue by baffo32** [QubesOS/qubes-issues#2445]
#### Qubes OS version (e.g., `R3.1`):
3.2

### Expected behavior:
May install /boot to removable device.

### Actual behavior:
If booting with UEFI, selection of removable device for boot loader is _deselected_ by installer after selection by user.

### Steps to reproduce the behavior:
1. Boot to installer with UEFI boot
2. When selecting installation destination, configure for manual partitioning, and specify that the boot loader be placed on a removable device ([photo](https://ipfs.io/ipfs/QmVwNLkGZijMzEPr74xmrBzH6fSAS66XmKWx1CfcaYPYxH))
3. Select 'done' in the upper left, and examine the disk summary again using the link in the lower left ([photo](https://ipfs.io/ipfs/QmbtLsStaioCbN4sugxU3aL3DvEFh5LaBw4jJVkBb75CKL))
Observe: the boot device has mysteriously changed back to the internal hard drive!

### General notes:
The only way I have found to convince the installer to install a UEFI /boot to a removable device on my system was to physically disconnect my internal harddrive.

---

#### Related issues:

This was one of the issues in #2419

**Comment by andrewdavidwong** [comment]
As you point out, this is included in #2419. For the sake of organization, I'm closing this as a duplicate.

**Comment by andrewdavidwong** [comment]
After re-reading the discussion on #2419, I agree it's better to split that issue into the two issues you've discovered, @baffo32. Reopening this one and creating #2457 for the other issue.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by xloem** [comment]
hey @andrewdavidwong, I'm still using my systems this way, but haven't upgraded to Qubes 4.  Do you know whether the issue has been fixed in Qubes 4?

My boot setup is one boot key that I use for multiple systems (which I keep chained to myself with my keys), so I don't reformat it when I install new systems, and it's always removed after boot.

**Comment by andrewdavidwong** [comment]
> hey @andrewdavidwong, I'm still using my systems this way, but haven't upgraded to Qubes 4. Do you know whether the issue has been fixed in Qubes 4?
> 
> My boot setup is one boot key that I use for multiple systems (which I keep chained to myself with my keys), so I don't reformat it when I install new systems, and it's always removed after boot.

Sorry, I don't know. I see no indication here that it was worked on or fixed, though.
