### ISSUE TITLE
Problem with adding USB device to a VM

### ISSUE THREAD

**Issue by john6611** [QubesOS/qubes-issues#2473]
#### Qubes OS version (e.g., `R3.1`):
3.2

#### What is the problem?
I installed Qubes 3.2 on a USB SSD drive.
I am also using an USB modem (huawei E3372)

To use the USB modem I need to add the PCI device (USB slot) to the sys-net VM. However upon adding the USB PCI device to the 'selected' devices list and booting the sys-net VM the entire system crashes (because the USB drive from which qubes is booted and the USB modem are the same PCI device).

Once it crashes it also appears to corrupt the entire system, after entering the luks password it just throws bad block errors and freezes.

#### Tried the alternative approach (qvm-usb)
It says ERROR: qubes-usb-proxy not installed in the VM 
While it is infact already installed

sudo yum install qubes-usb-proxy --> Package qubes-usb-proxy-1.0.5-1.fc23.noarch is already installed, skipping.

**Comment by andrewdavidwong** [comment]
Hm, this hardware configuration might simply be incompatible with Qubes (with networking).

**Comment by dimlev** [comment]
I have the same qubes version and I get the same message: "ERROR: qubes-usb-proxy not installed in the VM"

After modifing /usr/lib64/python2.7/site-packages/qubes/qubesutils.py to dump the stderr I get the underlying error which was:

> Invalid speed received

If I understand correctly, qubes-usb-proxy passes on the usb params to the AppVM (in my case sys-usb 2.4-3) 

which executes:
> /etc/qubes-rpc/qubes.USBAttach sys-usb 2-4.1

which then executes:
> sudo qrexec-client-vm "sys-usb" "qubes.USB+2.4-3" /usr/lib/qubes/usb-import "/var/run/qubes/usb-import-sys-usb-2.4.3.state"

which then produces the following output:

> /bin/sh: 0: Can't open /etc/qubes-rpc/qubes.USB
> Invalid speed received

Setting a default speed in /usr/lib/qubes/usb-import does not help because it then complains about an "Invalid devid"

Thats how far I got. I hope it helps.

**Comment by marmarek** [comment]
It isn't about "invalid speed", it's about missing
/etc/qubes-rpc/qubes.USB, which is part of qubes-usb-proxy package. You
need it in both sys-usb (actually its template) and the VM to which you
connect the device.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by dimlev** [comment]
@marmarek you are right... I just assumed qubes-usb-proxy should be installed only in the AppVM which I connect the device.

**Comment by marmarek** [comment]
So, does it work for you now?

**Comment by dimlev** [comment]
yes it works
