### ISSUE TITLE
Fedora template update: automatically reinstall custom user rpms

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2477]
For users upgrading their original Fedora templates (which don't have any custom repos added), it's easy to retrieve and "play back" the list of all custom RPMs installed:
```
[user@fedora-23 ~]$ sudo dnf history userinstalled | sed -re 's/^(.*)-([^-]+)-([^-]+)$/\1/' | tail -n +2 > pkgs
[user@fedora-23 ~]$ qvm-copy-to-vm fedora-24 pkgs
[user@fedora-24 ~]$ sudo dnf install -y `cat ~/QubesIncoming/fedora-23/pkgs`
```
Of course the above doesn't take into account any non-RPM-packaged template modifications (e.g. custom /rw/config/), nor RPM packages from other-than default YUM repos.

Still, I think somehow aumating the above would be helpful for many users. It's not clear to me, however, UI-wise, how this automation should be done to be most useful and easy to use? I.e. who should offer to run these scripts?

**Comment by marmarek** [comment]
Interesting. But I was thinking about something totally different:
install additional packages using salt stack. This way, you can easily
redo the operation on any other template. 

Also, I think if someone want to preserve as much as possible - can
simply upgrade the template in-place. If someone want to "refresh" the
template, probably want to review the list anyway (and not install no
longer used tools). So the above command IMHO should just go somewhere
into documentation.

BTW - slightly simplified command:

    sudo dnf history userinstalled | sed -e 's/\(.*\)-.*-.*/\1/' | tail -n
+2

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
