### ISSUE TITLE
Cannot install Windows 7 HVM unless "cirrus" driver is used

### ISSUE THREAD

**Issue by lorenzog** [QubesOS/qubes-issues#2488]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): N/A

---

### Steps to reproduce the behavior:

1. Install a windows HVM following the documentation
2. Watch the glowing logo glow

To fix:

1. Create a new Windows HVM with `qvm-create --hvm --label green win7`
2. Start it with an install ISO as described in the documentation
3. The VM will be stuck at the glowing logo: kill it with qubes VM manager
4. Copy the configuration file: `cp /var/lib/qubes/appvms/win7/win7.conf /tmp`
5. Edit the file, substituting the video driver from 'xen' to 'cirrus':

    <video type='vga'>
        <model type='cirrus' vram'16384'/>

6. Start the VM using the modified config file: `qvm-start win7 --custom-config=/tmp/win7.conf`
7. Install windows *note* Windows will reboot a few times: make sure to start the VM with the `--custom-config` argument every time
8. When windows is successfully installed, disable driver signing with `bcedit` (see install docs)
9. Start the VM, but use the Qubes Tools option: `qvm-start win7 --install-windows-tools`
10. The VM will get stuck at the glowing logo: kill it with Qubes VM manager
11. Copy the config file: `cp /var/lib/qubes/appvms/win7/win7.conf /tmp`
12. Edit the file, replacing 'xen' with 'cirrus' like at step 5 (note: this file will not have the windows ISO as cdrom but the Qubes Tools ISO instead)
13. Start the VM using the modified config file: `qvm-start win7 --custom-config=/tmp/win7.conf`
14. Install Qubes tools, making sure to reboot with the --custom-config
15. When the Qubes tools are installed, try booting the VM with its own config file: `qvm-start win7`
16. The VM should now be running with the Xen driver.

### General notes:

---

**Comment by mfc** [comment]
see related qubes-users thread for reference: https://groups.google.com/d/msgid/qubes-users/592a8ca0-255d-4172-a36f-0b64c01cbc0a%40googlegroups.com

**Comment by MegaTraveller** [comment]
Working, only thing is, that you have to run 
`sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing qubes-windows-tools`
otherwise thewindows-tools are not downloaded, because of an issue with the repo.

**Comment by BlueOrigin** [comment]
The very first line of this procedure results in this output:

> Wrong label name, supported values are the following:
> * blue
> * gray
> * green
> * yellow
> * orange
> * black
> * purple
> * red

I think the syntax is wrong...

**Comment by lorenzog** [comment]
@BlueOrigin ``--label L`` was intended to mean "give it a color you want". I've put "green" now.

**Comment by mfc** [comment]
this needs to be captured in the documentation at minimum. 

also this seems like something that could be easily fixed to reduce major user headaches related to a major feature (Windows 7 integration).

**Comment by bogdanstoica35** [comment]
Thanks for sharing the fix. It worked just fine in my case.

**Comment by vemrun** [comment]
Qubes OS version : R3.2
General notes:

Hey
I have problem with install Windows on QubeOS with HVM.
When i runing vm with windows system my vm stop and loading file /windows/system32/drivers/CLASSPBP.SYS and i have glowning logo but i fix this with this solution:
#2488
I change "xen" to "cirrus" in vga but,
i finish in steps 5 because
when i run vm with custom config:

 `<domain type='xen'>
  <name>win</name>
  <uuid>17fc3487-6eeb-4b15-8ac1-5a263ef669db</uuid>
  <memory unit='MiB'>10000</memory>
  <currentMemory unit='MiB'>10000</currentMemory>
  <vcpu placement='static'>2</vcpu>
  <os>
    <type arch='x86_64' machine='xenfv'>hvm</type>
    <loader>hvmloader</loader>
    <boot dev='cdrom'/>
    <boot dev='hd'/>
  </os>
  <features>
    <pae/>
    <acpi/>
    <apic/>
    <viridian/>
    
  </features>
  <clock offset='variable' adjustment='0' basis='localtime'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>destroy</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    
    <emulator type='stubdom' cmdline='-net lwip,client_ip=10.137.2.11,server_ip=10.137.2.254,dns=10.137.2.1,gw=10.137.2.1,netmask=255.255.255.0'/>
    <disk type='block' device='disk'>
      <driver name='phy'/>
      <source dev='/var/lib/qubes/appvms/win/root.img'/>
      <target dev='xvda' bus='xen'/>
    </disk>

    <disk type='block' device='disk'>
      <driver name='phy'/>
      <source dev='/var/lib/qubes/appvms/win/private.img'/>
      <target dev='xvdb' bus='xen'/>
    </disk>


    <interface type='ethernet'>
      <mac address='00:16:3E:5E:6C:09'/>
      <ip address='10.137.2.11'/>
      <script path='vif-route-qubes'/>
      <backenddomain name='sys-whonix'/>
    </interface>


    <input type='tablet' bus='usb'/>
    <video type='vga'>
      <model type='cirrus' vram='16384'/>
    </video>
  </devices>
</domain>

Appears me screen with this error:
http://imgur.com/AKjIN5f
Please help me with this error and im sorry for my bad english :D

**Comment by jcholsap** [comment]
It sure would be nice to be able to pass a parameter via qvm-start. something like --vga=cirrus. seems to me that this might prove useful for other (less popular) vm's. btw, i remember windows has a history of vga probs at install

**Comment by hugoncosta** [comment]
I did everything as instructed, but after installing Qubes' tools, the machine would boot up but not show anything (even though I wasn't on seemless GUI). I tried opening programmes using the qvm-run and nothing happened. I followed a french tutorial and used this command

`qvm-prefs -s (win7) qrexec_timeout 300`

And it's currently working

**Comment by chesheer-smile** [comment]
Thank you! This instruction totally works.
What is strange, though, it's that I actually installed Windows 7 a couple days before just following official documentation with no problems at all. And having my *.img files accidentally corrupted I had to reinstall it.. And then this particular problem with glowing logo appeared. Looks like it's kinda random.

**Comment by Jommoner** [comment]
I had the same experience, reinstalling Windows 7 several times (getting a BSOD once installation was complete due to another issue); a few times I needed to use cirrus rather than xen for the video driver, although there seems to be no way to reproduce the behaviour.

Could there be a footnote in the official documentation, describing how to do the 'cirrus' fix - a short entry after the qvm-start --cdrom instruction, saying 'if you get stuck on a glowing Windows 7 logo, then, on some systems, the following workaround may help:' - this would probably save a lot of time for people who need 'cirrus' and experiment and google for a while till they stumble upon it, like I did!

**Comment by andrewdavidwong** [comment]
@Jommoner: Thanks for the report. If you're interested in contributing the documentation fix, please see [here](https://www.qubes-os.org/doc/doc-guidelines/) for how to contribute.

**Comment by niccokunzmann** [comment]
When I tried installing the Windows tools with `--install-windows-tools`, it still used the Windows 7 cdrom image.

The fix was to add the `qubes-windows-tools-*.iso` to the edited config file:

1. Edit `/tmp/win7.conf` and go to the `<disk type='block' device='cdrom'>` section. In it, do the following:
2. replace the path of the Windows iso file with `/usr/lib/qubes/qubes-windows-tools-3.2.2.3.iso` (name may change)
3. set the `<backenddomain name='...'>` to `<backenddomain name='dom0'>`

Then, you can start the Windows vm again with `qvm-start win7 --custom-config=/tmp/win7.conf`. The Windows tools can be found in the cdrom drive and can be installed.

**Comment by boistordu** [comment]
@hugoncosta I have the same problem than you and the changing of timeout didn't do the trick. I'm still with a running win7 vm but no GUI, not appearing apps or whatsoever

**Comment by boistordu** [comment]
no it's okey... Apparently the reboot went wrong after installation or the installation itself. 
So I needed to launch the vm in debug mode, then uninstall the tools, reboot,reinstall them, reboot, making sure that everything was in order. then shutdown. try a qvm start without debug mode this time and it was okey. There are still some bugs. The pid bug is still there I think and starting fro the qubes manager seems to be slightly different than start from the terminal

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
