### ISSUE TITLE
Harcoded Whonix template names used in Qubes scripts

### ISSUE THREAD

**Issue by 3n7r0p1** [QubesOS/qubes-issues#2490]
#### Qubes OS version (e.g., `R3.2`):
all

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Whonix

---

### Expected behavior:
Whonix templates should be identified by markers and not by their names since it is not a requirement for templates to be kept using default names (whonix-gw, whonix-ws)

@adrelanos suggests using markers:
* /usr/share/whonix/marker
* /usr/share/anon-gw-base-files/gateway
* /usr/share/anon-ws-base-files/workstation

### Actual behavior:
Some scripts check template name to identify Whonix templates.

Example commits:
https://github.com/QubesOS/qubes-app-linux-split-gpg/commit/ead80b1af153ee54172f21b468ce5b11cad1f63c
https://github.com/QubesOS/qubes-app-linux-split-gpg/commit/1a22a2f9d995e5544afb8cc3364554acd16f1666

Further work is required to identify additional scripts.

**Comment by marmarek** [comment]
Can you spot anything else? Because those two places are totally ok. It's about automated tests, where environment is strictly controlled and it's ok to require some particular names of templates/VMs.
Also, this is about looking at those templates from dom0, where you can't easily check those markers (without starting the template).

Quick grep yields no other in-VM places detecting Whonix by name.
