### ISSUE TITLE
USB mouse works without approval

### ISSUE THREAD

**Issue by starius** [QubesOS/qubes-issues#2491]
Qubes OS version: `R3.2`.

When I plugged in my USB mouse, it became usable without any approval from me. I think, it smells like a security problem. I have not tested a keyboard, but if it works in the same manner, it is even worse. A malicious USB device can pretend to be a mouse and tamper user's activity in dom0 (e.g., open Qubes VM manager or some application, reboot physical machine).

Note: if the OS requested an approval for all USB devices, there would be a chicken-and-egg problem with requesting an approval for a keyboard if there is only one keyboard and it is the USB keyboard in question. It can be solved by pre-approving some devices during the installation (explicitly asking a user to choose which devices to trust).

**Comment by andrewdavidwong** [comment]
I think enabling mouse input by default if the user opts to create a USB qube is an intentional design decision related to issue #1930. Is that right, @marmarek?

@starius, just so you know, you can edit your own policy however you see fit in `/etc/qubes-rpc/policy/qubes.InputMouse`.

**Comment by marmarek** [comment]
On Tue, Dec 06, 2016 at 03:35:38AM -0800, Andrew David Wong wrote:
> I think enabling mouse input by default if the user opts to create a USB qube is an intentional design decision related to issue #1930. Is that right, @marmarek?

By default policy is set to 'ask'. I think either USB VM is not enabled
at all (and device is indeed in dom0 directly), or you clicked "yes to
all", which save the decision and do not ask on further occasions (about
the mouse connected to sys-usb, other services or other VMs should still
result in prompt dialog).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
