### ISSUE TITLE
[Clarification request/Documentation wrong/or Bug] Re-installation of a template does not work

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2500]
#### Qubes OS version (e.g., `R3.2`):
R3.2

https://www.qubes-os.org/doc/reinstall-template/ explains the command 

`$ sudo qubes-dom0-update --action=reinstall

This fails with 
```
ERROR: yum version installed in VM sys-firewall does not support --downloadonly option
ERROR_ only 'install' and 'upgrade' actions are supported (reinstall root)
```

Please fix either the underlying problem or the text on https://www.qubes-os.org/doc/reinstall-template/ .

**Comment by andrewdavidwong** [comment]
On which TemplateVM is your `sys-firewall` based?

**Comment by Wikinaut** [comment]
debian-8 (I changed that some days ago)

**Comment by andrewdavidwong** [comment]
That's probably why you're getting that message. The commands differ between `yum`/`dnf` and `apt-get`.

`yum`/`dnf`:
```
dnf reinstall <package>
```

`apt-get`:
```
apt-get install --reinstall <package>
```

Change your `sys-firewall` template to Fedora and try again.

**Comment by marmarek** [comment]
The actual reason is that yum version shipped in Debian-8 is too old to
support everything needed for action reinstall (as error message
mentions: the missing feature is --downloadonly option). This is
required to download package in sys-firewall (but not install it there),
then transfer to dom0 for actual installation.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by Wikinaut** [comment]
Thank you for your swift answers. (I also already supported the project with a donation, every user who can should do so.)

**Comment by andrewdavidwong** [comment]
> The actual reason is that yum version shipped in Debian-8 is too old to support everything needed for action reinstall [...]

Thanks for the correction, Marek. (I didn't even know yum was in `debian-8`!)

So, @Wikinaut, it appears the answer is: Either use a Fedora template or a newer Debian template for your `sys-firewall`.
