### ISSUE TITLE
[Clarification request] Is it possible to run e.g. Firefox _in_ a TemplateVM ?

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2506]
I noticed, that I can _start_ Firefox in a TemplateVM (after having added this as a "shortcut"), but no network connection appears to be working then. 

(You can open Terminal, Files etc. in a TemplateVM, this is why I thought that also FF can be run.)

I just wanted to know whether this is the correct behaviour (as a TemplateVM is not intended for this), or if it is a bug.

Firefox ESR is working fine in my personal AppVM, for example.

**Comment by andrewdavidwong** [comment]
Yes, it is possible (but inadvisable) to run any program in a TemplateVM. However, by default, TemplateVMs allow network connections only via the updates proxy. This is for your security, since unfettered network access can easily lead to you accidentally compromising your TemplateVM, which would result in compromising every AppVM based on that TemplateVM. (Note that the updates proxy restriction does not currently apply when the TemplateVM uses `sys-whonix` as its NetVM.)

P.S. - These sorts of questions are more appropriate for `qubes-users`.

**Comment by Wikinaut** [comment]
@andrewdavidwong thanks again, you answered exactly my (unasked) question, because of course I noticed, what makes sense, that _updates_ in and of the TemplateVMs do work.

(no further answer needed)
