### ISSUE TITLE
Consider raising VM limit  above 254

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2519]
Currently, there's a hard cap of 254 VMs. If a user attempts to create more, they'll receive this error:

> Cannot find unused qid!

A couple of users have hit this limit, so it's worth considering raising it:

* https://groups.google.com/d/topic/qubes-users/Zw5XjZndrDo/discussion
* https://groups.google.com/d/topic/qubes-users/NQTbGx6LhHY/discussion

**Comment by luserx0** [comment]
@andrewdavidwong As I understand the qid assigned to a VM is also used to assign the specified VM its internal IP address. Could we make this behaviour dynamic and automatically rotate to the next octet (i.e. x.x.1.254 and the next becomes x.x.2.1)? Is this already performed dynamically (I couldn't spot something in qubes-core-admin)?

If messing with the damn 254 value means a spiral of network behaviour changes, maybe we should leave the max_qid as is (since it's an edge case usage scenario).

- [Hard-set of the max_qid variable](https://github.com/QubesOS/qubes-core-admin/blob/84ec49e98df8f7d0413d0b62199d83a26c02a773/qubes/config.py#L78)

**Comment by unman** [comment]
On Wed, Mar 25, 2020 at 04:22:49AM -0700, Harry wrote:
> @andrewdavidwong As I understand the qid assigned to a VM is also used to assign the specified VM its internal IP address. Could we make this behaviour dynamic and automatically rotate to the next octet (i.e. x.x.1.254 and the next becomes x.x.2.1)? Is this already performed dynamically (I couldn't spot something in qubes-core-admin)?
> 
> If messing with the damn 254 value means a spiral of network behaviour changes, maybe we should leave the max_qid as is (since it's an edge case usage scenario).
> 
> - [Hard-set of the max_qid variable](https://github.com/QubesOS/qubes-core-admin/blob/84ec49e98df8f7d0413d0b62199d83a26c02a773/qubes/config.py#L78)
> 
I would be interested to see the use case that has led you to use more
than 254 qubes. Not questioning, just interested.
Any chance you could provide a little detail on how you have
compartmentalised ?

**Comment by fepitre** [comment]
Hi,
From my side, I already reached a huge number of VMs by using overkill method for one worker (~ 100) per VM when I'm working on some project using 'celery' scheduler. If you add also several infrastructures into the same Qubes server, that increase a lot.

In case that would have interested you :)

Best,
Frédéric


Le 25 mars 2020 13:23:58 GMT+01:00, unman <notifications@github.com> a écrit :
>On Wed, Mar 25, 2020 at 04:22:49AM -0700, Harry wrote:
>> @andrewdavidwong As I understand the qid assigned to a VM is also
>used to assign the specified VM its internal IP address. Could we make
>this behaviour dynamic and automatically rotate to the next octet (i.e.
>x.x.1.254 and the next becomes x.x.2.1)? Is this already performed
>dynamically (I couldn't spot something in qubes-core-admin)?
>> 
>> If messing with the damn 254 value means a spiral of network
>behaviour changes, maybe we should leave the max_qid as is (since it's
>an edge case usage scenario).
>> 
>> - [Hard-set of the max_qid
>variable](https://github.com/QubesOS/qubes-core-admin/blob/84ec49e98df8f7d0413d0b62199d83a26c02a773/qubes/config.py#L78)
>> 
>I would be interested to see the use case that has led you to use more
>than 254 qubes. Not questioning, just interested.
>Any chance you could provide a little detail on how you have
>compartmentalised ?
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/QubesOS/qubes-issues/issues/2519#issuecomment-603809969

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by unman** [comment]
On Wed, Mar 25, 2020 at 05:36:10AM -0700, Fr??d??ric Pierret wrote:
> Hi,
> >From my side, I already reached a huge number of VMs by using overkill method for one worker (~ 100) per VM when I'm working on some project using 'celery' scheduler. If you add also several infrastructures into the same Qubes server, that increase a lot.
> 
> In case that would have interested you :)
> 
> Best,
> Fr??d??ric
> 
> 
> Le 25 mars 2020 13:23:58 GMT+01:00, unman <notifications@github.com> a ??crit :
> >On Wed, Mar 25, 2020 at 04:22:49AM -0700, Harry wrote:
> >> @andrewdavidwong As I understand the qid assigned to a VM is also
> >used to assign the specified VM its internal IP address. Could we make
> >this behaviour dynamic and automatically rotate to the next octet (i.e.
> >x.x.1.254 and the next becomes x.x.2.1)? Is this already performed
> >dynamically (I couldn't spot something in qubes-core-admin)?
> >> 
> >> If messing with the damn 254 value means a spiral of network
> >behaviour changes, maybe we should leave the max_qid as is (since it's
> >an edge case usage scenario).
> >> 
> >> - [Hard-set of the max_qid
> >variable](https://github.com/QubesOS/qubes-core-admin/blob/84ec49e98df8f7d0413d0b62199d83a26c02a773/qubes/config.py#L78)
> >> 
> >I would be interested to see the use case that has led you to use more
> >than 254 qubes. Not questioning, just interested.
> >Any chance you could provide a little detail on how you have
> >compartmentalised ?
> >

Of course - always interested in other ways of using Qubes.
Thank you.

**Comment by marmarek** [comment]
In fact, IP address assignment already have some supports for 16bit qid. One issue may be it doesn't avoid `.0` and `.255` addresses, so if someone (for example on Windows VM) sets netmask 255.255.255.0, it will break. The correct netmask for this case would be 255.255.0.0.

**Comment by luserx0** [comment]
@marmarek These scenarios I am anxious about. By "it will break", how badly do we mean?
The scenario when someone "sets" it like that isn't of the utmost importance, but the correct initialization of the VM.

Time to move everything to link-local ipv6 and experiment with mesh nets? :old_key: 

Back to the issue in hand, netmasks have to be auto-configured or hard-set to go with the 16bit qid? Also where in the source I might be able to get a glimpse of this functionality?

**Comment by ilka-schulz** [comment]
> I would be interested to see the use case that has led you to use more than 254 qubes.

I asked that same question myself. I just heavily reorganized and pruned many VMs off my system and still have 91 VMs:

- one for every project I work on, both personal and for work
- one for each messenger
- one for each remote system that I manage independently
- one for each VPN (I need to connect different VMs to different VPNs at the same time)
- one for each piece of untrusted hardware that needs proprietary drivers or is otherwise unsafe (e.g. office hardware like printers and scanners)
- one for each piece of untrusted software
- two for each service I run locally (e.g. GitLab, crawlers and home automation; one for the service and one for the firewall)
- one for each TeXstudio instance and for special purposes that need extra isolation (e.g. my finance planning and weight watching VMs have no network connection)
- (only!) 10 different templates

Additionally, I only do web browsing in disposable VMs and I separate those by topics so I don't do research on the same VM I use to connect to Google services, so I always have 3..8 of those concurrently.

I finally received my new machine and got Qubes to run on it, so I am looking forward to run more services locally instead of on cloud servers. And I also want to create specific firewall VMs for many VMs.

I don't consider myself a power user, actually I am rather new to Qubes, so ~100 VMs are probably more or less normal. I can easily believe that power users hit that 254 VMs limit...

**Comment by rustybird** [comment]
Can the current tooling handle many thousands of existing VMs? E.g. `qubesd` or `qvm-*` might become unresponsive, or something like `qubes.xml` serialization might fail.

[This recently came up on the forum](https://forum.qubes-os.org/t/disposable-vms-names-can-the-launcher-know-the-name/12312/5) in the context of allowing a VM to call `admin.vm.CreateDisposable`, for which `max_qid` is an implicit limit.

**Comment by marmarek** [comment]
Enumerating more VMs (like `qvm-ls`) might became slower indeed, but I don't think `qubesd` itself would suffer much. 10000 VMs in qubes.xml is about 20M, not small, but also not unthinkable large. `qubesd` (and other tooling) is more sensitive to the number of running VMs (for example when querying available devices, collecting CPU/memory usage etc), and this number is limited by available RAM.
In any case, you can still get just a VM list with a single (quick) call `qvm-ls --raw-list` - that should work rather fast even with several thousands VMs.

In the future, we may want to add some more limits on resource usage in general, when non-dom0 management VMs will be more common. This applies not only to the number of VMs created, but also disk usage, memory usage, CPU usage etc.
