### ISSUE TITLE
Remove separate service for starting default NetVM

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2533]
[Marek:](https://groups.google.com/d/msg/qubes-users/YANigkN59k8/DNgZCmeVKgAJ)
> Default netvm (and other VMs required by it) is started at boot, 
regardless of its autostart setting. If you really want, you can disable 
qubes-netvm service (via systemctl), but I'd expect some problems then. 

In this case, users should not be presented the (ostensible) option to disable autostarting the default NetVM. ~~This option should be removed in two places:~~

~~* `qvm-prefs` (deny action with explanatory note)~~
~~* Qubes Manager (grey out checkbox)~~

(See below.)

**Comment by marmarek** [comment]
I'd like to do the opposite - remove separate service for starting
default netvm. This require fixing concurrent VM startup - if two VMs
use the same netvm and it isn't running initially, starting both of them
at the same time will result in starting the netvm twice - one of them
will fail. It's realistic to schedule it for Qubes 4.0.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 3n7r0p1** [comment]
I'm mashing a couple issues together with this comment - not sure where to say what.

> This require fixing concurrent VM startup

This would _indirectly_ fix: [Consider adding option 'none' to set Default NetVM](https://github.com/QubesOS/qubes-issues/issues/2252). At boot, all VMs in a network chain are launched simultaneously causing issues with ordered initialization (vpn, tor, etc). Under normal (non-boot) circumstances, VMs are launched in an orderly fashion (by netvm dependency).
