### ISSUE TITLE
Renaming HVM-Template sometimes results in complete Data Loss

### ISSUE THREAD

**Issue by entr0py** [QubesOS/qubes-issues#2539]
Qubes R3.1

Triggering sequence:

1. Using VM Manager > Settings, change Windows HVM-Template name.
2. Name does not change in VM Manager per #2054: Renaming VMs doesn't change qubes-manager entry
3. Name does not change in qubes.xml.
4. `/var/lib/qubes/vm-templates` does not contain either old-name files or new-name files.

IIRC, the removed vm-templates directory size was about 20 GB. Largest file (root.img) was about 18 GB out of 40 GB max. No QWT FWIW.

Tried to reproduce and unable.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
