### ISSUE TITLE
Installation on M.2 SSD fails

### ISSUE THREAD

**Issue by cschritt** [QubesOS/qubes-issues#2545]
#### Qubes OS version (e.g., `R3.2`): 
R3.2

### Expected behavior: 
continue of the installation process (?)

### Actual behavior: 
popup window with the following content: http://pastebin.com/i0djd8fU

### Steps to reproduce the behavior: 
choose the partitioning option in the second dialog of the install wizard (right after choosing the language)

### General notes:
I am trying to install Qubes R3.2 on a Samsung SM961 M.2 SSD. When clicking "Done" in the partitioning Screen I get an unknown error. Someone on the IRC channel told me that this is a known Xen bug that can be fixed by putting `pci-phantom=<busid>` to the boot options. I did that but it doesn't change the behavior. 
I have saved all the log files of the installation process to the point when the error occurs. Here's the anaconda.log:
http://pastebin.com/i0djd8fU

If you need any further logs, please let me know.

---

**Comment by andrewdavidwong** [comment]
Other users have [reported](https://groups.google.com/d/msg/qubes-users/Q1t2yl5A1gI/D5CGKCWPCwAJ) being able to install Qubes R3.1 on an M.2 SSD, so it sounds like this might be an incompatibility issue specific to your hardware. Generally, we ask that localized problems are sent to `qubes-users` rather than filed as issues here. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).) `qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
