### ISSUE TITLE
Support for Coreboot+SeaBIOS hardware

### ISSUE THREAD

**Issue by kugg** [QubesOS/qubes-issues#2553]
#### Coreboot 4.5
---

### Expected behavior:
Booting from disk after bios stage.
The following log from coreboot shows the same system successfully booting on a (non XEN) live distribution (Tails): https://paste.debian.net/hidden/fdc9fc95/

**Note**: To add debug prints I had to build another coreboot flash with spkrmodem hence the differing versions and dates. The behavior trying to boot Qubes from disk was the same on both versions of coreboot.

### Actual behavior:

Coreboot SeaBIOS cursor blinks OS does not start.

Output is:
Press ESC for boot menu.
(pressing ESC)
Select boot device:

1. AHCI/0: INTEL SSDSA2BW160G3L ATA-8 Hard-Disk (149 GiBytes)
2. USB MSC Drive Kingston DataTraveler 3.0 PMAP
3. iPXE (PCI 00:19.0)
(pressing 1)

Booting from Hard Disk...
Cursor keeps blinking, nothing boots.
The following log from coreboot shows a boot failure trying to boot the successfully installed Qubes OS R3.2 from disk: https://paste.debian.net/906598/

### Steps to reproduce the behavior:

1. Install coreboot 4.5 with SeaBIOS payload on Lenovo Thinkpad x220
1.2 Turn on debuging using either spkrmodem (and record/wait for about 5 hours for bios to boot) or use a EHCI debugger (https://www.coreboot.org/EHCI_Debug_Port). Configure either: CONFIG_HAVE_USBDEBUG=y || CONFIG_SPKMODEM=y
2. Install Qubes 3.2 on disk.
3. Boot from disk in SeaBIOS.

### General notes:
I have followed the discussion in: https://github.com/QubesOS/qubes-issues/issues/1594
I have tried to put iommu=0 in xen.conf with no success.
I have also unsuccessfully tried to add the options suggested in: https://www.qubes-os.org/doc/uefi-troubleshooting/

---

#### Related issues:
https://github.com/QubesOS/qubes-issues/issues/1594

**Comment by andrewdavidwong** [comment]
This is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.

**Comment by rustybird** [comment]
@andrewdavidwong: I think this should be reopened, because the installer bug affects all coreboot+SeaBIOS users.

Since https://github.com/QubesOS/qubes-installer-qubes-os/commit/147941657f7892089d8b7b4bcf61de3dad9ef8bd, GRUB is not installed on coreboot systems. Nor are Xen/kernel parameters etc. configured in `/etc/default/grub`, hence e.g. the [non-Plymouth boot after calling `grub2-install` manually](https://groups.google.com/d/msg/qubes-users/TS1zfKZ7q8w/JQFkVF4xBgAJ).

But if SeaBIOS is running, GRUB actually needs to be configured and installed. I'm working on a patch [(seabios branch](https://github.com/QubesOS/qubes-installer-qubes-os/compare/master...rustybird:seabios?expand=1), untested!) that attempts to detect SeaBIOS and also adds a `skip_grub={0,1}` boot parameter to override. Does someone have a coreboot-without-SeaBIOS installation around (maybe @tlaurion) to verify that `biosdecode` (as root) _doesn't_ print the line `BIOS32 Service Directory present.`?

Meanwhile, a good workaround for SeaBIOS users is switch to a terminal in the installer and effectively disable coreboot detection: `ln -sf /bin/true /usr/sbin/dmidecode && systemctl restart anaconda`

**Comment by andrewdavidwong** [comment]
> I think this should be reopened, because the installer bug affects all coreboot+SeaBIOS users.

Thanks, @rustybird. Reopened and updated title.

**Comment by mfc** [comment]
FYI easiest workaround is in this [HCL report](https://groups.google.com/d/msg/qubes-users/TS1zfKZ7q8w/JQFkVF4xBgAJ):

> Luckily it can be fixed: boot from your Qubes R3.2 installation media, go to "Troubleshooting -> Rescue a Qubes system", after booting to anaconda installer please choose "1) Continue" (and enter your Qubes partition password if you chose to encrypt it during install), then enter "chroot /mnt/sysimage" - and, finally, "grub2-install /dev/sdX" (where X is a letter for your hard drive with Qubes, in my case it was sda: "grub2-install /dev/sda")

**Comment by rustybird** [comment]
The workaround from the HCL report will leave the system in an undefined state:

> Nor are Xen/kernel parameters etc. configured in `/etc/default/grub`, hence e.g. the [non-Plymouth boot after calling `grub2-install` manually](https://groups.google.com/d/msg/qubes-users/TS1zfKZ7q8w/JQFkVF4xBgAJ).

Note that some of [those parameters](https://github.com/QubesOS/qubes-installer-qubes-os/blob/147941657f7892089d8b7b4bcf61de3dad9ef8bd/anaconda/pyanaconda/bootloader.py#L1494-L1516), such as `dom0_mem`, are not just cosmetical.

Hey do you still happen to have access to a coreboot-without-SeaBIOS installation @mfc?

**Comment by mfc** [comment]
this was for someone else, should i have also disabled coreboot detection like you suggested? or edited a bootfile for the necessary parameters? not interested in re-flashing SeaBIOS for them.

i run a heads machine which is coreboot without SeaBIOS. if i run `biosdecode` (as root) in dom0 it does not prints the line `BIOS32 Service Directory present`, only `ACPI 2.0 present` and `SMBIOS 2.7 present` (with further details of each).

**Comment by rustybird** [comment]
> this was for someone else, should i have also disabled coreboot detection like you suggested? or edited a bootfile for the necessary parameters?

Just disabling the Qubes installer's coreboot detection would be the cleanest.

If you don't want to reinstall, I'd at least add the line `GRUB_CMDLINE_XEN_DEFAULT="console=none dom0_mem=min:1024M dom0_mem=max:4096M"` and rerun `grub2-mkconfig`. Not sure what to do about `GRUB_CMDLINE_LINUX`, because it is generated dynamically, depending on installation layout and LUKS UUIDs. But apparently it's not essential (unless they want to try AEM).

> i run a heads machine which is coreboot without SeaBIOS. if i run biosdecode (as root) in dom0 it does not print the line BIOS32 Service Directory present, only ACPI 2.0 present and SMBIOS 2.7 present (with further details of each).

Great, thanks!

**Comment by rustybird** [comment]
>  - allowing /boot to be encrypted on coreboot(+grub2)

It is even encrypted _automatically_ in this case, right?

> Can we somehow detect grub2 payload presence (not only coreboot presence)?

No idea

> Is the above (biosdecode | grep BIOS32) the way to detect SeaBIOS?

Yes, and it really is the wrong thing to check. For example, coreboot's GRUB payload could be chainloaded from SeaBIOS.

Maybe we should just scrap the automagic for now and add two independent boot parameters, `encrypt_boot={0,1}` and `skip_grub={0,1}`? There are just so many moving parts - coreboot, SeaBIOS, GRUB payload, @osresearch's Heads, #2442, ...

**Comment by marmarek** [comment]
> allowing /boot to be encrypted on coreboot(+grub2)
> 
> It is even encrypted automatically in this case, right?

Yes.

> Maybe we should just scrap the automagic for now and add two independent boot parameters, encrypt_boot={0,1} and skip_grub={0,1}? There are just so many moving parts - coreboot, SeaBIOS, GRUB payload, @osresearch's Heads, #2442, ...

Yes, it would be much less error-prone.

**Comment by rustybird** [comment]
OK, I'll submit a PR.

**Comment by rustybird** [comment]
Now I'm really confused:

1. The lines `self.encryption_support = True` and `self.stage2_format_types += ["lvmlv"]` do _not_ automatically encrypt the boot partition. In retrospect that makes sense, because otherwise the "manual `grub2-install`"  partial workaround for SeaBIOS would not be viable.

2. The two lines don't seem to change how Anaconda behaves for manual partitioning. With or without them, you can choose LVM and/or encryption for the boot partition. And there will actually be no encryption, even if you choose it.

3. I don't know how what to make of @tlaurion's instructions in https://github.com/QubesOS/qubes-issues/issues/2118#issue-162353768. Is the idea for Anaconda to create `/boot` as a regular folder on the encrypted root partition inside the LVM? If I follow the steps, enter `/` into the "Mount Point:" field for matrix-rootvol in the Manual Partitioning screen, and click Done, Anaconda clears the field and fails with "You have not defined a root partition (/)".

**Has anyone successfully installed R3.2 with an encrypted boot partition?**

**Comment by marmarek** [comment]
In step "3" you need to click "update" first (right bottom corner). AFAIR without `self.encryption_support = True` and `self.stage2_format_types += ["lvmlv"]` Anaconda would complain that /boot cannot be on LVM and/or encrypted.
There was some method to make Anaconda not create separate /boot. Maybe it was some older version of this function?

**Comment by rustybird** [comment]
> In step "3" you need to click "update" first (right bottom corner).

This also just clears the Mount Point field for me, then I get the same error after clicking Done. Is it working for you?

**Comment by marmarek** [comment]
I don't have coreboot machine handy, but just checked and setting "/" do work this way. If you're trying to re-use existing partition, you need to select also "reformat" checkbox (there is a warning at the bottom of screen about it, if you don't do that).

**Comment by rustybird** [comment]
Thanks! Somehow the checkbox looked greyed out to me. (PTSD intensifies)

**Comment by DarkCoridor** [comment]
I installed Qubes 4 RC1 on a Lenovo x220 with Coreboot + SeaBIOS (1.9.1) successfully but booting stays stuck in endless boot loop. I tried the `grub2-install /dev/sda` trick (despite that being for Qubes 3.2?), however that does not make any different. 

I know it's not my machine that has an issue, as it successfully runs Tails, Subgraph, and Debian. Help or pointers would be appreciated.

**Comment by marmarek** [comment]
Remove `iommu=no-igfx` option from xen parameters (in grub config).

**Comment by DarkCoridor** [comment]
Thanks @marmarek I did that and it is no difference in the looping. Anything else I can try?

**Comment by h01ger** [comment]
On Sun, Sep 03, 2017 at 04:59:07PM -0700, DarkCoridor wrote:
> Thanks @marmarek I did that and it is no difference in the looping. Anything else I can try?

are you using the intel vga bios blob or the free firmware written in ADA?

(i'm using the latter on my x230 and it works fine.)


-- 
cheers,
	Holger

**Comment by DarkCoridor** [comment]
@h01ger I am unsure of that. Did you experience similar issue with one or other? Perhaps worth noting is I also used [me_cleaner](/corna/me_cleaner) on the Coreboot BIOS

**Comment by h01ger** [comment]
On Mon, Sep 04, 2017 at 05:01:35PM +0000, DarkCoridor wrote:
> @h01ger I am unsure of that. Did you experience similar issue with one or other? Perhaps worth noting is I also used [me_cleaner](/corna/me_cleaner) on the Coreboot BIOS

I never used the intel vga bios blob (except with the original lenovo firmware
of course) and have not yet any experience with me_cleaner.


-- 
cheers,
	Holger

**Comment by zxyz** [comment]
I had the same problem as @DarkCoridor with my X220 and Qubes-Os 4.0 rc1 (corebot from master, Seabios from master and me_cleaner from master) using the free firmware. Using the VGA blob I get to see the grub menu, which is as expected - but the computer reboots as before. But editing the XEN parameters and removing the `iommu=no-igfx` option did the trick and Qubes finally boots.

For extracting the BIOS I followed:
https://nroach44.id.au/index.php/2016/12/11/thinkpad-x220-coreboot-and-me-removal/
