### ISSUE TITLE
DispVM documentation page: small correction regarding "poweroff"

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2563]
On your page https://www.qubes-os.org/doc/dispvm-customization/ 

```
4. Shutdown the VM (either by "poweroff" from VM terminal, or "qvm-shutdown" from dom0 terminal).
```

s/poweroff/sudo poweroff/

**Comment by andrewdavidwong** [comment]
It's generally assumed in *nix documentation that you may need appropriate privileges to execute certain commands. We don't add `sudo` (or equivalent) explicitly everywhere that it might be needed.

P.S. - You should submit documentation changes as pull requests instead of issues, especially if they're very minor.

**Comment by Wikinaut** [comment]
ok.
