### ISSUE TITLE
Mouse click problem

### ISSUE THREAD

**Issue by 2k16user** [QubesOS/qubes-issues#2571]
Qubes OS version: 3.2

Somehow after the recent update (along with that new addition search box in VM manager), whenever I click anything say when I want to close a window or click anything, it doesn't work but I have to hover somehow my mouse again to that I want to click, I have to click twice to make the click work.

---

**Expected behavior:**

One mouse click should work as one click

**Actual behavior:**

Two clicks or even sometimes three times

**Steps to reproduce the behavior:**

Whenever I open a window, say Firefox and want to close it, before the update I could just close it with one click but now I either have to hover my mouse back and forth and click close button two or three times.

**General notes:**

I've used Qubes since v3.1 and I want to contribute to Qubes project but I'm new to github.

---

**Related issues:**

Sometimes whenever I want to open a program from a VM, despite it's running, the programs don't start or doesn't show up. I have to sometimes try to open it two or three times before it can show up.

**Comment by andrewdavidwong** [comment]
I am unable to reproduce this.

> I've used Qubes since v3.1 and I want to contribute to Qubes project but I'm new to github.

Thanks! Please see:
https://www.qubes-os.org/doc/contributing/

> Sometimes whenever I want to open a program from a VM, despite it's running, the programs don't start or doesn't show up. I have to sometimes try to open it two or three times before it can show up.

I've experienced this too, but only with Nautilus (#2449).

**Comment by andrewdavidwong** [comment]
Is it possible that the problem is with your mouse? Please try using this mouse with a non-Qubes OS and check whether the problem exists.

**Comment by cabusar** [comment]
Hello,

I have (i think) the same problem.

I use an USB mouse (mad catz rat 3) and an USB keyboard.

When i start qubes OS it works fine, but after a few minutes the left click just stop working.
Sometimes right click work, sometimes not, for no apparent reason.

I found that the left click don't work with all the part related directly with DOM0 (window, focus etc).

After a while it work again and the problem is solved until the next reboot.

I think (as i understand how qubes OS work) that it might be related to USB device attachment.

I continue to search by myself how to solve this, if you have an idea, feel free to let me know.

Best regards and many thanks for creating this OS, it is truly amazing.

**Comment by qubezz** [comment]
cabusar,

I have the same problem here. I got some kinda Roccat Cyborg gaming mouse here or something, however the thing is that no dom0 gui element is clickable; this includes the colored window frames or the bar on top with the Qubes symbol.

Pressing CTRL + ALT + F2 and then pressing CTRL + ALT + F1 helped fix the problem until the next reboot, thank you very much! I hope this issue gets fixed soon, I run Qubes OS 3.2 without any problems except for this one. My mouse works perfectly fine on any other (Windows) system.

**Comment by yilmi-vmw** [comment]
I have the same issue over here, I've been using the same mouse/laptop/configurations for the last 2 years without any issue. I didn't had a lot of time to dig it as it happens while I'm at work and it is not always reproducible. 

I don't think there's an issue with the mouse itself as the mouse is always working on dom0 (for me at least). 
My guess is that it is probably a focus/graphic driver issue and noticed it often happens when my AppVM was reaching its max memory limit. But that's only a guess, I will try to reproduce and troubleshoot in order to provide more details.

**Comment by yilmi** [comment]
I have the same issue over here, I've been using the same mouse/laptop/configurations for the last 2 years without any issue. I didn't had a lot of time to dig it as it happens while I'm at work and it is not always reproducible.

I don't think there's an issue with the mouse itself as the mouse is always working on dom0 (for me at least).
My guess is that it is probably a focus/graphic driver issue and noticed it often happens when my AppVM was reaching its max memory limit. But that's only a guess, I will try to reproduce and troubleshoot in order to provide more details.

**Comment by conorsch** [comment]
Affected by this. The behavior is somewhat inconsistent, but results in left-click actions not being recognized at all, neither by an external mouse nor by the built-in trackpad. The external USB mouse works fine on other machines, and has previously worked with Qubes, as well. Plugging in the external mouse _often_ gets left click working on the external mouse, but nothing I've tried has resulted in the left-click working on the trackpad again.

**Comment by pgporada** [comment]
I'm unsure if I'm encountering the same problem, but on Qubes R4.0 if my secondary monitor is not powered on prior to starting AppVMs and I drag an AppVM window into the secondary monitor all mouse clicks in the secondary monitor will render on the primary monitor. The "solution" I have is to reboot and make sure that my secondary monitor doesn't power off waiting for a video signal while Qubes boots.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
