### ISSUE TITLE
Archlinux community TemplateVM upgrade error after recent dom0 update

### ISSUE THREAD

**Issue by pugege** [QubesOS/qubes-issues#2585]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
archlinux community templatevm

---

### Expected behavior:

usual pacman sync and upgrade

### Actual behavior:

```
error: failed to prepare transaction (could not satisfy dependencies)
```

### Steps to reproduce the behavior:

```
pacman -Syu
```

### General notes:

normal sync and upgrade before recent dom0 upgrade, post dom0 upgrade;
(normal sync)

```
:: starting full system upgrade
resolving dependencies
looking for conflicting pkg
:: xorg-server and xf86-input-joystick are in conflict (X-ABI-XINPUT version)
remove xf86-input-joystick y/n: y
error: failed to prepare transaction (could not satisfy dependencies)
:: qubes-vm-gui: installing xorg-server (1.19.1-1) breaks dependency 'xorg-server<1.19.0'
```

---

**Comment by cryptix** [comment]
I'm also blocked on this. We found out through some discussion and kind help by another volunteer (didn't get to test it myself) that if you bump the xorg dependency of the `qubes-vm-gui` package, you run into problems with pulseaudio.
Archlinux already uses pulseaudio version 10 and [the headers need to be present](https://github.com/QubesOS/qubes-gui-agent-linux/blob/master/archlinux/PKGBUILD#L54) in the source tree of [qubes-gui-agent-linux/pulse](https://github.com/QubesOS/qubes-gui-agent-linux/tree/master/pulse).

I think the tangential overarching issue is, if we (the arch using qubes community) want to supply a binary repo for the qubes packages. Otherwise we have to individually go thorugh rebuilding the templates.. which is quite a hassle imho.

**Comment by ptitdoc** [comment]
This has been fixed using the latest marmarek repo (qubes-vm-gui), or by using the binary packages if you have a repository pointing to my server:
[qubes-r3.2]
Server = http://olivier.medoc.free.fr/archlinux/current/

The documentation for the template has also been updated:
https://www.qubes-os.org/doc/templates/archlinux/

**Comment by cryptix** [comment]
@ptitdoc I tried your repo but links don't work.. Hope your account wasn't suspended? :sob: 

I will try to rebuild my template with the new instructions.

**Comment by ptitdoc** [comment]
Hello, the link does not work only because directory listing is disabled.

If you add the following line to pacman.conf, this should work.
```
 [qubes-r3.2]
Server = http://olivier.medoc.free.fr/archlinux/current/
```

**Comment by cryptix** [comment]
@ptitdoc ah.. okay. I was thrown off by the index being disabled and trying the URL from the template building docs (ending in `/pkgs/`) that also returns 404.

I tried your mirror and everything downloads and verifies except this one:

```
error: failed retrieving file qubes-vm-core-3.2.15-11-x86_64.pkg.tar.xz from olivier.medoc.free.fr : Maximum file size exceeded
```

not sure what that means... there i

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
