### ISSUE TITLE
[GUI improvement] Qubes VM Manager StandaloneVM: keep the original TemplateVM OS name

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2592]
#### Qubes OS version (e.g., `R3.2`):
3.2

When I set up a StandaloneVM, let's say based on `debian-9`, this information is overwritten with the string `"StandaloneVM"` when the SVM is created.

I want to suggest that the original TemplateVM name is kept, e.g. `"Standalone VM (based on debian-9)"` or so.

**Comment by marmarek** [comment]
That's bad idea - since StandaloneVM is not really bound to its original template, it can easily desynchronize - for example when you update to the next distribution (like debian-9 StandaloneVM created of debian-8 or even older VM), or even morph it to a differend distribution (like [kali](https://www.qubes-os.org/doc/pentesting/kali/)).

In the future, VM description field may be used for such thing: #899

**Comment by Wikinaut** [comment]
It was just and only meant as a reminder to the user what the original OS was.
