### ISSUE TITLE
Debian stretch HVM

### ISSUE THREAD

**Issue by dot-slash** [QubesOS/qubes-issues#2615]
I've been trying to set up a Debian HVM in Qubes. It works fine using Debian Jessie but after upgrade to stretch the screen is non-functional after login. It seems to be the same issue as described here in the Kali installation issue #1981:

"I was wondering if anyone else is experiencing problems with installing Kali on a HVM in Qubes. When I boot the fresh installed Kali HVM i see the logon screen fine, but after that I see the top op the screen in the lower 10% of the window."

There was mention of adding the following lines to /etc/X11/Xwrapper.conf
`allowed_users=anybody`
`needs_root_rights: no`

But that doesn't seem to help.

**Comment by andrewdavidwong** [comment]
You're on Qubes 3.2, I presume?

**Comment by dot-slash** [comment]
Yes. Freshly installed and updated.

**Comment by dot-slash** [comment]
After some testing I can add that everything functions fine when using alternate desktop managers i.e. XFCE or MATE, but the issue arises again when the default desktop manager is set to Gnome 3 in `/etc/X11/default-display-manager`

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
