### ISSUE TITLE
Implement website translations

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2652]
Tasks:
- [ ] Create separate *untrusted* submodule for translated files (i.e., no signed commits or tags).
- [ ] Give Transifex push access to the new submodule for uploading translated files.
- [ ] Extend `_utils/update-submodules` script to ensure that all translated pages are within a separate namespace (e.g., `qubes-os.org/es/`) and use an appropriate layout.
- [ ] Create new layout(s) for translated pages, including a disclaimer about our inability to evaluate content in languages we can't read. (This is why there will be no signed commits or tags in this submodule.)
- [ ] Move non-doc translatable pages out of main repo (back into `qubes-doc`?).
- [ ] Implement a language switching mechanism on the website (highly non-trivial, since we can't use Jekyll plugins).

**Comment by tokideveloper** [comment]
Hello @andrewdavidwong, what is the current state? Your TODO list has no checkmarks. How can I help you?

**Comment by andrewdavidwong** [comment]
@tokideveloper: Thanks for asking! All the tasks except the last one are internal tasks that we'll take care of when the time comes. But we would love help with the last one, if you have experience in this area: "Implement a language switching mechanism on the website (highly non-trivial, since we can't use Jekyll plugins)."

Other than that, I think the best way to help with translations would be to focus on:

1. Actual translation at [Transifex](https://www.transifex.com/otf/qubes/).
2. Determing the translation guidelines (including workflow): #2824 and [this thread](https://groups.google.com/d/topic/qubes-devel/a4gg3g4UuJg/discussion).

**Comment by tokideveloper** [comment]
> But we would love help with the last one, if you have experience in this area: "Implement a language switching mechanism on the website (highly non-trivial, since we can't use Jekyll plugins)."

No, I don't have any experiences in this area. However, I suggest a poor man solution for a language switch: To each (*.md) file, add a line (or two) containing the links to all translations. E.g.:


The content of the fictional file `/doc/example.md`:

*YAML header*
[Deutsch](/de/doc/example.md) **English** [Français](/fr/doc/example.md)
*rest of document*
[Deutsch](/de/doc/example.md) **English** [Français](/fr/doc/example.md)


The content of the fictional file `/de/doc/example.md`:

*YAML header*
**Deutsch** [English](/en/doc/example.md) [Français](/fr/doc/example.md)
*rest of document*
**Deutsch** [English](/en/doc/example.md) [Français](/fr/doc/example.md)


The content of the fictional file `/fr/doc/example.md`:

*YAML header*
[Deutsch](/de/doc/example.md) [English](/en/doc/example.md) **Français**
*rest of document*
[Deutsch](/de/doc/example.md) [English](/en/doc/example.md) **Français**


This should be a practicable way since the translators have to adapt links anyway.

**Comment by andrewdavidwong** [comment]
I've broken this out into the following separate issues, so I'm closing this one:

#2925 
#2926 
#2927 
#2928 
#2929 
#2930
