### ISSUE TITLE
please rephrase "Using and Managing USB Devices"

### ISSUE THREAD

**Issue by emdete** [QubesOS/qubes-issues#2657]
i think the document [Using and Managing USB Devices](https://www.qubes-os.org/doc/usb/) needs some polishing. it mixes past & present features, contradicts itself and has no clear flow. example:

> it is possible to prepare and utilize a USB qube.
>
> For this reason, you may wish to avoid using a USB qube

it tries to cover the two major setups (sys-usb installed yes/no), describe concrete procedures (create sys-usb, use usb-proxy), metiones existing problems (reset bug of chips) and is partly incomplete.

finally i doubt that it is very useful for the standard user targeted by qubes.

**Comment by andrewdavidwong** [comment]
PRs welcome.

**Comment by Yethal** [comment]
Did some updates/cleanup of this file. Updated version available here for feedback:
https://github.com/Yethal/qubes-doc/blob/patch-6/common-tasks/usb.md
If no further changes are required I'll send a PR.

**Comment by Yethal** [comment]
@andrewdavidwong @emdete  - Are any further changes required or can I send a PR now?

**Comment by andrewdavidwong** [comment]
@Yethal: This is a cumbersome diff to evaluate because of the way you moved a large stretch of preexisting text without making it clear whether you made any specific changes, additions, or removals. Can you point out exactly what changes you've made here?

**Comment by Yethal** [comment]
@andrewdavidwong 

- Moved USB qube instructions to the top of the document to stress the importance of using one
- Added USB mouse instructions to mirror the USB keyboard one
- Added a warning that USB keyboards cannot be used to type disk passphrase if USB controllers were hidden from dom0
- Removed redundant Qubes 3.1 specific instructions due to Qubes 3.1 becoming EOL
- Block devices segment moved to the bottom for better flow (Users should first be taught how to manage USB controllers before they are taught how to use USB devices)

**Comment by andrewdavidwong** [comment]
@Yethal: Thanks. My comments are on your PR.
