### ISSUE TITLE
qubes-gpg-client-wrapper should ignore --homedir

### ISSUE THREAD

**Issue by lechten** [QubesOS/qubes-issues#2660]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All templates with Split GPG.

---

### Expected behavior:
qubes-gpg-client-wrapper should remove the option --homedir, which makes no sense for offline GnuPG VMs.
### Actual behavior:
qubes-gpg-client-wrapper passes the option to qubes-gpg-client, which exits with an unrecognized option.
### Steps to reproduce the behavior:
qubes-gpg-client-wrapper --homedir ~/.emacs.d/elpa/gnupg/ -k
### General notes:
qubes-gpg-client-wrapper removes keyserver-options with a comment on Torbirdy compatibility. Removal of homedir would increase Emacs compatibility (package management).

---

**Comment by unman** [comment]
I think that there is a difference here in that Torbirdy forces the use of  `keyserver-options` , but it's meaningless in the context of Qubes split gpg. That's why it's safe to remove it. There is no use of qubes-split-gpg where it could make any difference to operations.
But I can imagine someone setting up the backend with two gpg configs and attempting to use them both via split gpg by passing `--homedir` . This option isn't *meaningless* in this context: it's not supported. If it were simply stripped as you suggest they would be baffled by the results.
It's clear from documentation that the `homedir` option isn't supported by qubes-gpg-client, and the "unsupported option" message *may* lead someone to look there.
I'd have thought the right solution here would be to configure emacs not to pass the option.

**Comment by lechten** [comment]
I see. I'll propose a change to Emacs.
