### ISSUE TITLE
Windows VMs sometimes (rarely) freeze with CPU usage 100% (typically at startup)

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#2690]
#### Qubes OS version (e.g., `R3.2`):
3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Windows 7 HVM
WIndows 7 templated 
---

### Expected behavior:
Windows 7 not to freeze, at startup or otherwise
### Actual behavior:
Windows 7 sometime freezes, most typically at startup (when rebooted often) with CPU usage 100% )per qubes VM manager

Sometimes that happens during normal operation (VM would stop responding and Qubes VM manager will show 100% CPU usage) but this is much less common (most typical occurrence is at startup)

Happens only to windows VMs. 

Assigning more VCPUs or more RAM does not affect the issue.

### Steps to reproduce the behavior:

Have a windows 7 VM

Reboot it many times. 

Eventually the "100% CPU freeze" will happen.

### General notes:

Killing a frozen VM from Qubes VM manager works fine.

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
