### ISSUE TITLE
4.4.38-11 kernel-devel missing for Fedora 24

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#2692]
#### Qubes OS version (e.g., `R3.2`):
3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Fedora 24 (maybe 23 too?)

---

### Expected behavior:
kernel devel to update to latest kernel so I can build a driver that I need once again.

### Actual behavior:

Can't update kernel-devel to work with 4.4.38-11, can't build stuff for 4.4.38-11

Have to use kernel 4.4.31-11 for which kernel-devel installs fine and driver builds

### Steps to reproduce the behavior:

trying to install kernel-devel for 4.4.38-11 does not succeed, package seems not to exist

### General notes:

---

**Comment by aberja** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "qubesos-bot [Masked]" <FWD-737QTYSMENAIYCQANIQDDYDDEBMGAKZBA3UAJ6YCSFZ2AIZ6BQTTBJ2MUBWKQQBIN5TBAIY2BVBS2WBMMARUX2Z7GYIECXLRMG2CHYAE5BBOCALCCFBDJCKVCBMZCSHEF3HESXI6RJ6JAABFEFASAI2QE4MCIWBBHAQFQJJ36JOGAD4ABOAALYQIU4BFEY3JAAQAAIA=@opayq.com> is being returned by server opayq-outbound.junkemailfilter.com on Mon, 12 Jun 2017 11:31:01 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  mm1@canadianmoneymatters.ca
    host canadianmoneymatters.ca [67.231.20.103]
    SMTP error from remote mail server after RCPT TO:<mm1@canadianmoneymatters.ca>:
    554 Security failure
