### ISSUE TITLE
Publish per-page hit counts

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#2711]
It may be useful to those of us trying to improve the docs to know which pages to focus on first.

Publishing some minimal data such as:
```
<path> <hits in last month>
/ 3321
/intro/ 1024
/downloads/ 812
/doc/ 432
...
/doc/network-printer/ 14
```
would not invade privacy, and may be useful data to have.

**Comment by andrewdavidwong** [comment]
What method do you propose?

**Comment by jpouellet** [comment]
I don't know what logs you have access to with github/cloudflare. Perhaps something in [common log format](https://en.wikipedia.org/wiki/Common_Log_Format)?

If so I could provide a simple awk script or something.

**Comment by marmarek** [comment]
I don't think we have access to any of this. I see only some aggregated
data in Cloudflare (like total request count, total size etc).
While I see how we could add such tracking functionality (easiest:
include some 1px image downloaded from server where we have logs, and
look at `Referer:` field), I think it is a bad idea to add such things
on our website.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by jpouellet** [comment]
[Indeed looks that way](https://blog.cloudflare.com/what-cloudflare-logs/), so nevermind then. Perhaps this could be revisited if the site hosting infrastructure ever changes.

**Comment by andrewdavidwong** [comment]
AFAIK, there are no server-side options for counting page hits with GitHub Pages + Cloudflare. We don't get access to logs of any significance. @marmarek?

**Comment by andrewdavidwong** [comment]
(Ignore previous message. I was commenting on a page that hadn't been refreshed in 12 hours...)
