### ISSUE TITLE
Add Debian-minimal template to repository

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#2716]
There are regular requests for a Debian minimal template on the mailing lists.
Can one be added alongside the fedora-minimal?

**Comment by andrewdavidwong** [comment]
Usually @marmarek points out that the existing Debian template is already pretty minimal (compared to the non-minimal Fedora template).

**Comment by unman** [comment]
Closing as Debian minimal now available

**Comment by andrewdavidwong** [comment]
Reopening because it still needs to be documented.

**Comment by andrewdavidwong** [comment]
@unman, would you be willing to document it?

**Comment by unman** [comment]
On Fri, Feb 01, 2019 at 07:36:31PM -0800, Andrew David Wong wrote:
> @unman, would you be willing to document it?
> 
Of course.
I'll cover the same ground as Fedora minimal.

**Comment by diederikdehaas** [comment]
I'd like to offer a couple of improvement suggestions:
- reduce the list of manually installed packages
Most library files are only needed as a dependency. Having them marked as automatically installed is cleaner and allows for smoother upgrades. I did that with the following commands:
```
aptitude markauto '?narrow(~i^lib,!~M)'
aptitude unmarkauto libc-bin libc6 libstdc++6
```
The first command marks all manually installed packages starting with 'lib' as automatically installed and the second command sets some (back) to manually installed. You can add other packages to the 2nd command if you want to.

- install libpam-systemd
On a systemd based Debian system, you really want libpam-systemd. I haven't (yet) looked into how Qubes templates get build, but f.e. cdebootstrap only installs Depends, not Recommends (which libpam-systemd is)

- run 'dpkg-reconfigure locales'
I normally install en_US.UTF-8 (and sometimes nl_NL.UTF-8) and set system default locale to 'None'.
I noticed that no locales were installed and consequently you often get errors/warnings when running f.e. aptitude. I forgot to track whether it also happened before I upgraded to Buster, so this may be a non-issue.

**Comment by diederikdehaas** [comment]
On https://www.qubes-os.org/doc/templates/debian-minimal/ the instruction to use `sudo` is to install `qubes-core-agent-passwordless-root polkit`, but on Debian there is no package named `polkit`.

Installing `policykit-1` seems to do the trick, although I'm not sure that's the correct solution. There are various packages with polkit (and some with policykit) in their name.

**Comment by unman** [comment]
@diederikdehaas - Thanks for your posts.

There's already a doc request that covers your second post. In fact policykit isn't required to get passwordless root - just install qubes-core-agent-passwordless-root - I'll update the page accordingly.

On your earlier post, our policy is to match the native installation as closely as possible. Almost all the library files in the minimal template are marked as manually installed in a native installation - you can easily confirm this for yourself. So I dont think that Qubes will change this.
The minimal installation is intended to be barely functional and only to be used by somewhat experienced users. It functions as it is without libpam-systemd - once you start extending the template, (e.g by installing qubes-core-agent-network-manager), libpam-systemd is often upulled in.

I believe that the minimal template has en_US.UTF-8 set by default. I dont know why your version wouldn't have this. Can you check again?

**Comment by diederikdehaas** [comment]
policykit: awesome, thanks.

automatically/manually installed: I can understand that, especially as it's indeed what happens with Debian as well. I do think 'fixing' it is an improvement and it would make it better then Debian itself ;)
(improved command: `aptitude markauto '?narrow(~i~slibs~n^lib,!~M)'`)

libpam-systemd: I do realize that when you install additional things, there's a good chance it will get pulled in. At least it very likely should. Besides as a basis to build a full template yourself I see another use case for the minimal template: 'headless' systems/VMs. When you ssh into such a headless VM is precisely when you'll encounter problems when you don't have libpam-systemd installed. That is the direct reason for this commit: https://github.com/debian-pi/raspbian-ua-netinst/commit/7c768246b30d5ade6353a56f586479d4cc9e8c7f. The Raspbian Netinstaller is meant to make a minimal system and/or to tailor it precisely to ones needs. Just like the minimal template.
The description for libpam-systemd contains this line:
_If in doubt, do install this package._
That line was added for a reason.
I think the reasons for installing it by default are strong, but it's still just a suggestion.

locales: this isn't the first time I'm confused about locales. And probably won't be the last.
`locale -a` gives me `C, C.UTF-8, en_US.utf8 and POSIX`, which indicates I was wrong.
OTOH, running `dpkg-reconfigure locales` shows no enabled locales and `grep -v '#' /etc/locale.gen` only returns empty lines.

Then another interesting thing happened.
Previously I immediately cloned the template after installing it and worked on my clone (as recommended). So this was the first time I actually ran something in the template (terminal).
As the system default is to automatically update qubes, I got notified that there were updates available.
So I ran `aptitude safe-upgrade` and one of the updates was the `locales` package.
Immediately after the upgrade was completed, I ran `aptitude clean` and then I saw one of the problems I saw earlier and was the reason I reported it:
```
Warning: Invalid locale (please review locale settings, this might lead to problems later):
   locale::facet::_S_create_c_locale name not valid
```
You'll get that warning on every subsequent (aptitude) command.
(Sidenote: I noticed that `man`/`man-db` wasn't installed, so `man X` gives an error)

I have now disabled the system default to automatically update the cube and I'm now going to delete the `debian-9-minimal` template and install it fresh again, so that I can see whether that issue also happens OOTB, thus without any updates.

...

Well, that failed. Running `sudo qubes-dom0-update --enablerepo=qubes-templates-itl-testing qubes-template-debian-9-minimal` gave me:
"No match for argument: qubes-template-debian-9-minimal
Error: Unable to find a match"
I (already) removed the template manually before I saw the 'normal' method, but I don't think that should matter wrt this.

**Comment by unman** [comment]
@diederikdehaas You should be able to pick up the template from the current repo now (templates-itl).
If you want to follow up the point re libpam-systemd, I'd suggest taking that to the qubes-devel mailing list initially. In my view, packages that need this functionality will pull it in, and this should be left to the packaging system. (E.g. openssh-server has libpam-systemd as a recommend, not a dependency.) 
The locales stuff is undoubtedly qubes-users material, (ripe for the arcana of locales) - I think that what you are seeing is a reflection of the fact that the locale on your system has not been generated from the locales package.

I'm closing this issue as completed.

**Comment by TNTBOMBOM** [comment]
Debian Minimal Template seems missed again from Qubes repos , can you please check again? 

@unman

**Comment by unman** [comment]
On Tue, Jun 18, 2019 at 01:56:46PM -0700, TNT BOM BOM wrote:
> Debian Minimal Template seems missed again from Qubes repos , can you please check again? 
> 
> @unman 
> 
It's definitely there - what makes you think it's missing?

**Comment by TNTBOMBOM** [comment]
when i run:

```
[user@dom0 ~]$ sudo qubes-dom0-update
--enablerepo=qubes-templates-itl-testing qubes-template-debian-9-minimal
```

its showing:

```
No match for argument: qubes-template-debian-9-minimal
```


unman:
> On Tue, Jun 18, 2019 at 01:56:46PM -0700, TNT BOM BOM wrote:
>> Debian Minimal Template seems missed again from Qubes repos , can you please check again? 
>>
>> @unman 
>>
> It's definitely there - what makes you think it's missing?
> 
>

**Comment by marmarek** [comment]
Are you sure you don't have this package installed already? Check `rpm -q qubes-template-debian-9-minimal`.

**Comment by TNTBOMBOM** [comment]
hmm interesting its showing to me the template name/version. but nothing
i have on Qubes Manager.

Any idea how to figure out whats wrong here?

Marek Marczykowski-Górecki:
> Are you sure you don't have this package installed already? Check `rpm -q qubes-template-debian-9-minimal`.
>

**Comment by marmarek** [comment]
Probably you have removed template manually instead of uninstalling the package. You can[reinstall the template](https://www.qubes-os.org/doc/reinstall-template/) using either method described there.

**Comment by TNTBOMBOM** [comment]
Thats true , thanks for the help :)

Marek Marczykowski-Górecki:
> Probably you have removed template manually instead of uninstalling the package. You can[reinstall the template](https://www.qubes-os.org/doc/reinstall-template/) using either method described there.
>
