### ISSUE TITLE
Run automated tests on PRs before merging

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2725]
@marmarek: Is there a way we can run automated Travis CI test on qubes-doc and website PRs before merging them? I often find that I merge a qubes-doc PR only to have it report a broken link after your automated script updates the submodule. It would be great for PR contributors to be able to see that their PR is going to break a link and fix it before I merge.

**Comment by marmarek** [comment]
Will look into it, shouldn't be that hard.

**Comment by jpouellet** [comment]
I have some WIP initial testing in [here](https://github.com/qubesos-bot-jpo/qubesos.github.io/tree/travis) and [here](https://github.com/qubesos-bot-jpo/qubes-doc/tree/travis-testing-pr2). General idea is to always checkout qubesos.github.io, have a _utils/travis.sh script there which properly checks out upstream version of all submodules, substituting specific repo under test. Then run tests on that.

WIP version is broken because it uses master rather than the PR. Fix should be simple but I won't have time to work on this (or really anything qubes-related) for the next few weeks, so just sharing WIP version in case anyone wants to pick it up in the mean time.

Once that works, I've also implemented incremental spell checking. Will merge after.

**Comment by marmarek** [comment]
The easiest way to make it working on the right sources (PR instead of master) is rely on Travis and use whatever it downloaded. Like here:
https://github.com/QubesOS/qubes-builder/blob/master/scripts/travis-build#L63-L67

**Comment by jpouellet** [comment]
@marmarek I see you've started merging this. A few notes:

1. The reason I had a separate old_site and new_site dirs checked out in separate locations simultaneously is because I found some checks (for example reporting words introduced by the PR not found in the dictionary *nor in existing documentation text*) seem to make the most sense to implement by building both new and old `_site`s and diffing results of scripts run each.
2. I intentionally used all repos of the owner of the "base" of the PR rather than hard-coding QubesOS, which means it's possible to test net effect of changes in multiple repos before sending any PR to QubesOS/*. IMO that behavior is worth retaining.

I'm in final exams right now, otherwise I'd have sent PRs already :)

**Comment by marmarek** [comment]
On Fri, May 05, 2017 at 06:03:04PM -0700, Jean-Philippe Ouellet wrote:
> @marmarek I see you've started merging this. A few notes:
> 
> 1. The reason I had a separate old_site and new_site dirs checked out in separate locations simultaneously is because I found some checks (for example reporting words introduced by the PR not found in the dictionary *nor in existing documentation text*) seem to make the most sense to implement by building both new and old `_site`s and diffing results of scripts run each.

I see, I've retained this behaviour - simply use ./_site instead of
"~/new_site".

> 2. I intentionally used all repos of the owner of the "base" of the PR rather than hard-coding QubesOS, which means it's possible to test net effect of changes in multiple repos before sending any PR to QubesOS/*. IMO that behavior is worth retaining.

+1

> I'm in final exams right now, otherwise I'd have sent PRs already :)

Good luck :)

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Merged work by @jpouellet . For now I've enabled it for qubes-doc and qubes-posts repos. Unfortunately it will work only for new PRs (made from just updated master) - there is no no easy way to add this to all those existing PRs...
But there is a trick: you can merge a bunch of PRs into some test branch, push it (without signed tag yet) and wait for Travis to check it. If ok, sign and push to master.

**Comment by andrewdavidwong** [comment]
Thanks, @jpouellet and @marmarek!

**Comment by andrewdavidwong** [comment]
@marmarek, can you please enable this on the HCL subrepo?

**Comment by marmarek** [comment]
Done.

**Comment by andrewdavidwong** [comment]
Thanks, @marmarek!

**Comment by jpouellet** [comment]
xref https://github.com/QubesOS/qubes-issues/issues/2935 (qubesos.github.io: travis builds ~/old_site using merge head instead of base)
