### ISSUE TITLE
qvm-open-in-vm fails silently when reopening file in same qube

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#2726]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All

---

### Expected behavior:
qvm-open-in-vm will allow file to be opened twice in same qube

### Actual behavior:
File does not open - fails silently.

### Steps to reproduce the behavior:
use qvm-open-in-vm.
Close file in target.
Attempt to reopen same file in same target qube.

### General notes:
Sven Eriksson reported to qubes-users.
Identified that problem lies in failure to remove file from /tmp in target qube on closure.

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
