### ISSUE TITLE
Install centOS as Template VM

### ISSUE THREAD

**Issue by 3rzx** [QubesOS/qubes-issues#2745]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-23

---

### Expected behavior:
I want to install centOS as my template VM. I find the document to build non-fedora-templateVM here https://www.qubes-os.org/doc/building-non-fedora-template/. But I can't find any script in the repo. 
And I find another issue here https://github.com/QubesOS/qubes-issues/issues/1450. It said all script are separate now and we can read plugin API document. The document said "But the code to actually build some packages/templates should be provided as a plugin." Does it mean if there is no option of building centOS template in the setup step,  qubes is not support centOS right now?  
Or does anyone has the experience about build centOS as templateVM? 

### General notes:

---

**Comment by jpouellet** [comment]
This might be a better question for the [qubes-users](https://www.qubes-os.org/mailing-lists/#qubes-users) mailing list (which gets more traffic, where perhaps someone has tried it), but no. It is not currently supported. You can still install whatever you like in an [HVM](https://www.qubes-os.org/doc/hvm/) though.

May I ask what difference between fedora & centos makes you want to install the latter?

**Comment by marmarek** [comment]
I guess it should be quite easy to modify builder-fedora to build CentOS
template. Probably just a matter of providing different repository URLs
and keys for verification.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 3rzx** [comment]
@jpouellet thanks for your advice, I will try HVM.
the reason of using centOS is order by my boss
@marmarek, what is "different repository URLs" mean? centOS project?

**Comment by marmarek** [comment]
On Wed, Apr 12, 2017 at 06:56:52AM -0700, 3rzx wrote:
> @marmarek, what is "different repository URLs" mean? centOS project?  

Yes, exactly. It's here: https://github.com/QubesOS/qubes-builder-fedora/blob/master/yum-bootstrap.conf
And also take a look at initial packages list (especially
fedora-release):
https://github.com/QubesOS/qubes-builder-fedora/blob/master/prepare-chroot-base#L40

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
As JPO pointed out, this should be on the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead.
