### ISSUE TITLE
Qubes VM Manager Crashes - can't restart it without rebooting

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#2764]
Affected: Qubes OS version R3.2

From time to time the Qubes VM Manager crashes so it's no longer visible. Trying to restart it by clicking it in the menu does nothing. A reboot is required to restart it.

---

### General notes:

---

**Comment by andrewdavidwong** [comment]
Does Qubes Manager start from the command line? In dom0, try:

```
$ qubes-manager &
```

**Comment by marmarek** [comment]
Also make sure the old one is really no longer running. Qubes Manger
have mechanism to avoid running two of them simultaneously.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by Simon-Davies** [comment]
It has just crashed again now. It crashed after the computer going into sleep.

I tried qubes-manager &

This image shows the output, Qubes Manager is not respawned: http://tinypic.com/r/14kdsew/9

**Comment by Simon-Davies** [comment]
pkill qubes-manager
qubes-manager &

This is the fix

**Comment by jpouellet** [comment]
What version of qubes-manager are you running?

`rpm -q qubes-manager` in dom0 to check

**Comment by MarkRijckenberg** [comment]
Sorry, if I am hijacking this thread. I had the exact same issue and Simon-Davies' pkill workaround for this bug works for me as well.

I am also using Qubes OS 3.2.  Output of rpm -q qubes-manager in dom0  is  qubes-manager-3.2.12-1.fc23.x86_64

Running "sudo qubes-dom0-update" does not show any new updates since the last update.
Qubes is running GNU/Linux kernel version 4.4.67-13.pvops.qubes.x86_64 #1 SMP.

**Comment by marmarta** [comment]
As it's hard to diagnose what exactly failed in this instance - unfortunately, with the R3.2 Qubes Manager design there was a bunch of things that could fail (and any undiscovered bugs too, of course), and also R4.0 should not have this problem, I'm going to close this one.
