### ISSUE TITLE
Disposable VM gained persistance!

### ISSUE THREAD

**Issue by tezeb** [QubesOS/qubes-issues#2792]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): archlinux

---

### Expected behavior:
When process for which dvm has been started exits, dvm shall be stopped and removed.

### Actual behavior:
Most of the time it works, but sometimes the dvm stays open. It's even possible to shut it down and start again.

### Steps to reproduce the behavior:
N/A, it happens randomly and I am not able to reproduce it.

### General notes:
I can provide some logs(but which?), as I have such dvm running in my system right now.

---

**Comment by jpouellet** [comment]
Is this distinct from https://github.com/QubesOS/qubes-issues/issues/2200? (You have updated since then... right?)

**Comment by tezeb** [comment]
Yes I did. And it seems distinct.
It's not persistence of DispVM filesystem, rather that DispVM does not get shutdown and removed automatically. Also it's possible to shut it down and it is as usable as other AppVMs are.

**Comment by rustybird** [comment]
That seems familiar... In the context of Split Browser, I've seen DisposableVMs lingering around for no discernible reason, occasionally.

**Comment by tezeb** [comment]
@rustybird was it on ArchLinux template or something else?

**Comment by rustybird** [comment]
In my case, it was a whonix-ws template.

**Comment by jpouellet** [comment]
Hmmm... I just observed this too with a fedora-24 based vm.

/tmp/qubes-session-waiter had 2 PIDs, both were dead.

**Comment by mig5** [comment]
I can reproduce this reliably by running from the dom0 shell:

```
echo xterm | /usr/lib/qubes/qfile-daemon-dvm qubes.VMShell dom0 DEFAULT red
```

The dispVM terminal pops up. I exit the terminal and sometimes the dom0 command which doesn't exit, hangs for a moment. If I Ctrl+C that process in dom0, I get the KeyBoardInterrupt python exception and the dispVM is still running.

If I then close the dispVM via Qubes Manager, it 'persists' in the list of VMs.

So in general I would say if there is something that can cause /usr/lib/qubes/qfile-daemon-dvm to throw an exception instead of cleaning up on a clean exit, there is the chance the VM can linger.

**Comment by marmarek** [comment]
`/usr/lib/qubes/qfile-daemon-dvm` process is responsible for cleaning up DispVM, so it is not surprising at all that if you kill it, DispVM is not cleaned up.

> So in general I would say if there is something that can cause /usr/lib/qubes/qfile-daemon-dvm to throw an exception instead of cleaning up on a clean exit, there is the chance the VM can linger.

Yes, this is right question. If the DispVM was started from menu, check `~/.xsession-errors`. If from other VM - check its qrexec log (/var/log/qubes/).

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
