### ISSUE TITLE
Using username 'qubes' causes installer to hang

### ISSUE THREAD

**Issue by anoadragon453** [QubesOS/qubes-issues#2793]
#### Qubes OS version (e.g., `R3.2`):
R3.2

---

### Expected behavior:
* With a new installation providing 'qubes' as the user name should produce a new install with 'qubes' as my username

### Actual behavior:
* The installer hangs at the end with a message similar to can't create user. user already exists.

### Steps to reproduce the behavior:
* New Qubes R3.2 install
* At portion where you can set your username, enter 'qubes'
* Installer will go til the end until it hangs, making install impossible

### General notes:
* The user should not be able to set 'qubes' as the username
* Perhaps instead we should show a warning/error message if qubes is entered into the username box, and advise the user to change it

**Comment by rustybird** [comment]
It probably breaks if any username that's already in `/etc/passwd` (adm avahi-autoipd bin daemon dbus ftp games geoclue halt lightdm lp mail nobody operator polkitd pulse root rtkit saslauth shutdown sync systemd-bus-proxy systemd-network systemd-resolve systemd-timesync unbound) is entered?

Maybe the dom0 username should just be hardcoded to `user`, which would be consistent with VMs and get rid of a bit of friction in the installer. (I also find it aesthetically pleasing, somehow.)

**Comment by anoadragon453** [comment]
I too enjoy and currently use 'user' as the username as it makes
scrubbing logs much less hassle.

I'll update the issue description.

Thanks,
Andrew Morgan

**Comment by eduncan911** [comment]
Hello!  I originally reported this here:

https://groups.google.com/forum/#!msg/qubes-users/HH2rK1Yt9Jc/0fO-ujP7BQAJ

And thanks to @anoadragon453, he brought it over to this git issue.  👍 

--

Basically, two options on **Expected Behavior**:

A) With a new installation providing 'qubes' as the user name should produce a new install with 'qubes' as my username.  (`dom0` would use a `user` account instead). 

or B) Installer should have Validation to not allow `qubes` on the username input.

Thanks!

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
