### ISSUE TITLE
Page(s) on onion site stuck in redirect loop

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2807]
This page (and possibly others) on our onion site are stuck in a redirect loop:

http://qubesos4rrrrz6n4.onion/doc/firewall/

Reported by [qubenix on qubes-users](https://groups.google.com/d/msgid/qubes-users/68566c1c-b22e-74fd-4dfd-82d1545c9a85%40riseup.net).

CC @fortasse

**Comment by fortasse** [comment]
Maybe it's because I'm building with a different version of Ruby / Jekyll, but it looks like `/doc/firewall/` is setup to be a redirect to itself: https://github.com/QubesOS/qubes-doc/commit/2d07f7831c9be109f3dbc42165b3e38038f9bee8#diff-608601de22bd52215556760eb918a502

Is that intentional? I don't know a whole heck of a lot about Jekyll, but I think that's _probably_ the problem?

**Comment by fortasse** [comment]
Upon further inspection of the commit, it _looks_ like it was a mass search-replace gone awry.

**Comment by fortasse** [comment]
PR here: https://github.com/QubesOS/qubes-doc/pull/424
