### ISSUE TITLE
Better promote the Qubes StackExchange proposal

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#2880]
The [Qubes OS proposal](https://area51.stackexchange.com/proposals/98519) on StackExchange has received only 140 commits so far over the course of 11 months. There should be a more targeted promotion for it in the Qubes website (maybe a banner that is displayed in the documentation pages?).

Having a StackExchange website for Qubes is very important as the answers and questions are routinely crawled, and are favored on major search engines. This may make it easier for people to find help for common questions.

**Comment by jpouellet** [comment]
OTOH, it creates yet more places to search for people looking for questions that have been already answered, and further dilutes the pool of competent answerers, and when questions are not answered there it gives people the impression that the Qubes community is somehow small, dead, inactive, or unresponsive because of the low volume on their non-mailing-list discussion platform of choice. We [already have that problem with the subreddit](https://www.reddit.com/r/Qubes/comments/5ct1ir/debating_on_qubes/) ([r/Qubes](https://reddit.com/r/Qubes)).

To quote @andrewdavidwong from [a mailing list thread on whether or not to create a Qubes forum](https://groups.google.com/d/msg/qubes-users/2rqas38ncFA/wRUng-uIQAAJ) (emphasis mine):
> After much deliberation, we have decided not to create an official Qubes 
forum (though we do not discourage any members of the community from 
creating an unofficial forum). 
> 
> The team never reached a consensus on whether an official forum would be 
in the best interest of the Qubes community, so an executive decision 
was made not to proceed, mainly for the following reasons: 
> 
> **1. There would be too many places where Qubes is discussed, and this 
might make it more difficult for people to find information.**
> 
> **2. It would create an additional burden on members of the team. (For 
example, Marek would probably have to spend time reading and answering 
questions on the forum.)**
> 
> Again, I want to emphasize that we are not trying to discourage any 
members of the community from creating an unofficial Qubes forum, if 
that's what they want to do.

Since it appears very unlikely to meaningfully displace the mailing lists as the primary place for questions, I don't think it should be further promoted for the reasons stated above.

**Comment by andrewdavidwong** [comment]
I think the current level at which we promote the Qubes StackExchange proposal on the Qubes website is appropriate.

@rootkovska, @marmarek, any opinion?

**Comment by rootkovska** [comment]
What is this StackExchange, again? And why is it better/different than our mailing list?

**Comment by header-repo** [comment]
@rootkovska 

> What is this StackExchange, again?

Best way to answer is to give some examples: [[1]](https://stackoverflow.com), [[2]](https://askubuntu.com/questions/24006/how-do-i-reset-a-lost-administrative-password).

> And why is it better/different than our mailing lists?

* Answers and questions are routinely crawled, making questions/answers much easier to lookup since they always appear in the first links in a [your-favorite-search-engine] search. In comparison, how many times did you use the search function in the Google mailing list to lookup answers if they don't appear in your search engine?
* More friendly to non-technical people, mailing lists can be intimidating to use.
* One can use pictures/gifs inside answers/questions.
* Better formatting: [Example](https://askubuntu.com/a/28087).
* SE system ensures that duplicate questions are closed, ensuring one central canonical set of answers.
* SE has a comment section so one has no longer have to complain about top posting being such a bad thing.


@jpouellet points are correct, just one note: there's nothing preventing one from exporting questions/answers from the mailing list to SE.

**Comment by forgotone** [comment]
Oh, forgot another ones:

* Questions can be organized by different labels.
* Thanks to analytics this may reveal how many times a certain question was seen, maybe interesting/useful to devs or not.
* Better compatibility with search engines, here's an example: (you can replicate it by going to https://duckduckgo.com and searching for `how delete a non-empty directory in terminal ubuntu`)

![](https://i.stack.imgur.com/AirJK.png)

**Comment by andrewdavidwong** [comment]
Unfortunately, our StackExchange proposal was closed some time ago due to lack of activity.
