### ISSUE TITLE
 Fix your SMTP on qubes-os.org 

### ISSUE THREAD

**Issue by haroon-ali** [QubesOS/qubes-issues#2891]
Hi,
I wanted to contact some of your team members who have emails @qubes-os.org but found that its smtp is failing security checks.
https://ssl-tools.net/mailservers/qubes-os.org
I tested on different sites and found similar results.
Please fix it so as to contact them for contributions.

**Comment by andrewdavidwong** [comment]
Thanks for the report. Just to make sure we're on the same page, have you already read [What does it mean to “distrust the infrastructure”?](https://www.qubes-os.org/doc/user-faq/#what-does-it-mean-to-distrust-the-infrastructure) and [Why doesn’t this website have security feature X?](https://www.qubes-os.org/doc/user-faq/#why-doesnt-this-website-have-security-feature-x)

We don't believe that the absence of any SMTP security feature should prevent you from securely contacting any of us, since PGP signing and encryption should be relied upon for security rather than features of SMTP.

CC @marmarek

**Comment by andrewdavidwong** [comment]
Assigned to @marmarek to fix if practical and desirable.

**Comment by marmarek** [comment]
In the meantime our mail provider improved it.
