### ISSUE TITLE
Qubes Builder - can no longer build Ubunutu+desktop flavours

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#2892]
For example, building with DISTS_VM = Xenial+desktop produces the same image as Xenial.
The flavour is not processed.

**Comment by marmarek** [comment]
This is surely caused by https://github.com/QubesOS/qubes-linux-template-builder/commit/a97fe13c1b5a1525e10dcff3796dcf539d349f9e
Any idea what variable is missing there? I see both `TEMPLATE_FLAVOR` and `TEMPLATE_FLAVOR_DIR` already on the whitelist.

An idea: change `TEMPLATE_FLAVOR_DIR` in `qubes-builder/example-configs/templates.conf` to use `$$TEMPLATE_SCRIPTS` instead of `$$SCRIPTSDIR`.

**Comment by unman** [comment]
That worked.
But then, I blew away the old build VM, cloned anew, and everything worked as expected.
Closing this.
