### ISSUE TITLE
Before installing template check if name is already used

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#2914]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
all?

---

### Expected behavior:
Attempting to install Template with same name as existing Qube will throw warning
### Actual behavior:
Template apparently installs correctly, but is not usable.

### Steps to reproduce the behavior:
Create HVM - Stretch.
Install stretch template.

### General notes:

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
