### ISSUE TITLE
add nautilus-wipe to default templates

### ISSUE THREAD

**Issue by derDieDasJojo** [QubesOS/qubes-issues#2915]
I propose to add the package: nautilus-wipe to the default-installation of
debian-8 template. because it is a easy way to shred files via gui.

https://askubuntu.com/questions/523570/is-there-a-way-to-add-shred-to-right-click-menu

**Comment by andrewdavidwong** [comment]
The reason "because it is a easy way to shred files via gui" isn't a good reason for the program to be installed by default. Most programs make doing something easier. It doesn't follow that most programs should be installed by default.

We leave most decisions about default program inclusion to the upstream distro. See:
https://www.qubes-os.org/doc/devel-faq/#what-is-qubes-attitude-toward-changing-guest-distros
