### ISSUE TITLE
KDE-related bugs

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2968]
New widgets in Qubes 4.0:
 - [ ] devices widget have invisible icon
 - [x] left click doesn't work, only right-click
 - [ ] there are no elements on the right in menus - no device icon, no memory info 
 - [ ] tooltip says "devices.py" and "domains.py"
 - [ ] if widget is close to the right screen edge, submenus still tries to open to the right - outside of screen

**Comment by zander** [comment]
Todays update has this one fixed;

>  left click doesn't work, only right-click

**Comment by zander** [comment]
Adding an issue;

the generated `/tmp/ques-session.env` file has 3 variables that seem to be hardcoded to xfce as they do not adjust appropriately when running qubes inside of a KDE dom0 desktop.

Please make sure that these get generated appropriately;

```
DESKTOP_SESSION="plasma"
XDG_CURRENT_DESKTOP="KDE"
XDG_MENU_PREFIX="kde-"
```

The difference will be very visible because KDE apps will suddenly start following KDE theme settings (icon-theme being the most visible one) instead of GTK settings.

**Comment by donob4n** [comment]
I did a little progress with the first point
>  devices widget have invisible icon

On /qui/tray/devices.py switching "media-removable" to "drive-removable-media" works (although I think it breaks xfce), so the problem seems the icon file but I don't know the exact reason yet.

@zander I think I read some post about this of you but I don't find it. Do you remember what I mean?

**Comment by manasb** [comment]
I use KDE with Qubes and I can confirm that these issues still exist.
