### ISSUE TITLE
Ctrl-key gets stuck after switching between VM windows

### ISSUE THREAD

**Issue by anoadragon453** [QubesOS/qubes-issues#2976]
#### Qubes OS version:
R3.2

#### Affected TemplateVMs:
Presumably All, but seems to only happen after some time.

---

### Expected behavior:
1. Use Ctrl-Shift-C to copy something from a VM
2. Switch to another VM window
3. Switch back to original VM window and left-click somewhere
4. Normal left-click behavior ensues

### Actual behavior:
1. Use Ctrl-Shift-C to copy something from a VM
2. Switch to another VM window
3. Switch back to original VM window and left-click somewhere
4. What you did was actually a Ctrl-Left-click, and continues to be until Ctrl if pressed again

### General notes:
I notice this a lot with Atom, which uses Ctrl-left-click for spawning another cursor. Has been the result of many code bugs from random text being typed where it shouldn't :)

**Comment by anoadragon453** [comment]
Confirmed happens in Nautilus as well, not just an Atom problem.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
