### ISSUE TITLE
VPN seems 'throttled' R4.0-rc1

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#2980]
#### Qubes OS version (e.g., `R3.2`):
R4.0-rc1

### Process

Created an AppVM based on fedora-25 with 'provides network' checked. Installed AirVPN client, selected sys-firewall as NetVM. Ran airvpn as sudo (wouldn't let me run as user). It connected to VPN server OK but very slow. Tried many alternative servers - same result.

Tried changing the netVM to sys-net - same problem.

Tried installing VPN in another AppVN - same problem.

Tried adding PCI devices such as network-manager in the VPN AppVM settings but that caused an error.

Added network-manager and meminfo-writer under services - no difference

The problem is definitely this installation and not Airvpn as everything works fine in R3.2 where I have the same setup. 

Any ideas? Am I doing something wrong?

**Comment by tasket** [comment]
Not sure if this belongs logged as a bug; Qubes networking is not vanilla Linux and VPN provider custom scripts/clients AFAIK are not supported. This would be better addressed on qubes-users list.

@JPL1 My advice for now would be to use the Airvpn [config generator](https://airvpn.org/generator/) then use that config with the [Qubes VPN doc](https://www.qubes-os.org/doc/vpn/). The doc was written for Qubes 3.x, so when you create "qubes-firewall-user-script" save it as "qubes-ip-change-hook" instead. Of course, where it says "proxyVM" use an appVM that "provides network". This should get it running with Qubes-specific leak protection (which the Airvpn client probably doesn't provide, though I can't tell because its a compiled binary).

**Comment by JPL1** [comment]
@tasket I will try that. Thanks for the tip.

**Comment by JPL1** [comment]
I can report that the problems do not occur on 4.0rc2. AirVPN works 'out of the box'
