### ISSUE TITLE
qvm-run --dispvm doesn't work when invoked from dom0

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3012]
#### Qubes OS version (e.g., `R3.2`):

4.0-rc1, latest core 4.0.5 from current-testing

### Steps to reproduce the behavior:

```[user@dom0 ~] $ qvm-run --dispvm -- xterm```

The error message from qubesd is that dom0 has no property `default_dispvm`.

If I then specify e.g. fedora-25 to be used as a template, this also fails, because the template does not have `dispvm_allowed` property, and it doesn't seem possible to set it via qvm-prefs.
If I specify some AppVM as a template (after manually changing dispvm_allowed to True), this step works.
Unfortunately, the startup fails, Actually it seems like the DispVM starts for a second, then dies. Some relevant message might be about the Storage Pool for the dispvm (qubes_dom0/vm-dispXYZ-root-snap) "being in use"...

**Comment by marmarek** [comment]
> The error message from qubesd is that dom0 has no property default_dispvm.

This means you haven't update qubes-core-dom0: https://github.com/QubesOS/updates-status/issues/176
Please update and try again (there are more fixes than just this).
Also, for GUI application I recommend updating template too, and use `--service qubes.StartApp+xterm`, instead of bare `xterm` (which use `qubes.VMShell`).

**Comment by marmarek** [comment]
Or maybe, you don't have `default_dispvm` set? If it isn't set for dom0, it defaults to global property. But maybe you don't have it set either?

**Comment by marmarek** [comment]
(and of course you've meant `qvm-run --dispvm`, not `qvm-start --dispvm`. I've updated description)

**Comment by 3hhh** [comment]
@`qvm-run --dispvm -- xterm`:
I had also tested that yesterday afternoon and this morning with the latest updates:

This morning it did work on the 3rd try, the first two tries just resulted in qvm-run exiting without any comment and nothing happening.

I then tested `qvm-run --dispvm --service qubes.StartApp+xterm` which worked on the first try.

Afterwards I ran
```
qvm-run --dispvm fedora-25-dvm xterm
Running 'xterm' on $dispvm:fedora-25-dvm

$dispvm:fedora-25-dvm: Cannot execute qrexec-daemon!
Traceback (most recent call last):
  File "/usr/bin/qvm-run", line 9, in <module>
    load_entry_point('qubesadmin==4.0.5', 'console_scripts', 'qvm-run')()
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_run.py", line 235, in main
    dispvm.cleanup()
  File "/usr/lib/python3.5/site-packages/qubesadmin/vm/__init__.py", line 376, in cleanup
    self.kill()
  File "/usr/lib/python3.5/site-packages/qubesadmin/vm/__init__.py", line 118, in kill
    self.qubesd_call(self._method_dest, 'admin.vm.Kill')
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 69, in qubesd_call
    payload_stream)
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 482, in qubesd_call
    return self._parse_qubesd_response(return_data)
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 102, in _parse_qubesd_response
    raise exc_class(format_string, *args)
qubesadmin.exc.QubesVMNotStartedError: Domain is powered off: 'disp3011'
```

--> Doesn't look stable to me yet.

I also noticed a few less important bugs, but I'll create separate issues for that.

**Comment by marmarek** [comment]
> This morning it did work on the 3rd try, the first two tries just resulted in qvm-run exiting without any comment and nothing happening.

This is because `qubes.VMShell` service do not wait for X server startup in the VM - so, there is a race. If it starts xterm before X server, it fails. You can see that adding `--pass-io` option. `qubes.StartApp` service do wait for X server.

> $dispvm:fedora-25-dvm: Cannot execute qrexec-daemon!

That's strange. Can you set `debug` to `true` on this VM and try again? You should get VM VGA output and see what's wrong with VM startup.

**Comment by 3hhh** [comment]
Out of ten tries I only had it once so far and unfortunately debug was off then...

Now however 2/3 tries of
`qvm-run -p --dispvm --service qubes.StartApp+xterm`
resulted in
`xterm: Xt error: Can't open display: :0`
i.e. there seems to be a racing condition still. In general it might be worth making "wait for X" another command-line flag.

**Comment by 3hhh** [comment]
What also happened multiple times with debug = true was that I got a totally black dispVM, unable to type and not starting xterm.
In the upper left corner I get
```
[
_
```
Before I could see from the scrolling down startup messages that it got past the login.
Pass-io just shows some missing font for xterm (also happens on other occasions).

**Comment by marmarek** [comment]
> What also happened multiple times with debug = true was that I got a totally black dispVM,

By default configuration in Fedora X server switch to empty tty, even if not going to use it. Simply switch back to other tty, for example with ctrl+alt+left.

> Now however 2/3 tries of
> qvm-run -p --dispvm --service qubes.StartApp+xterm
> resulted in
> xterm: Xt error: Can't open display: :0

Do you have newest qubes-core-agent there (https://github.com/QubesOS/updates-status/issues/188)?

> i.e. there seems to be a racing condition still. In general it might be worth making "wait for X" another command-line flag.

There is one: `--gui`. But normally it require calling another qrexec service before actual command. And DispVM is automatically destroyed after qrexec service call finishes... So, this option in practice works only for non-Disposable VMs.

**Comment by 3hhh** [comment]
> Do you have newest qubes-core-agent there (QubesOS/updates-status#188)?

Now I understand that previous comment...
No, I had not upgraded my template VM with the testing repo.

So now it worked 7/7 times or so without any of the aforementioned errors.

Totally my bad, sorry!

**Comment by 3hhh** [comment]
@marmarek : `qvm-run -p --dispvm --service qubes.StartApp+firefox` seems to be indeed more reliable than `qvm-run --dispvm -- firefox` due to the waiting time for X. How can one pass arguments to the application with `--service qubes.StartApp+firefox` then though?

E.g. `qvm-run -p --dispvm --service 'qubes.StartApp+firefox google.com'` didn't work last time I tried (invalid service or something).

**Comment by rootkovska** [comment]
I still keep getting the same error about `qubes_dom0/vm-disp{id}-root-snap` being in used.

**Comment by marmarek** [comment]
> I still keep getting the same error about qubes_dom0/vm-disp{id}-root-snap being in used.

This problem is during DispVM cleanup, should not affect starting _new_ DispVM.

As for `qubes.StartApp` - it do not allow passing an argument to application on purpose - this service is to start an application, _without_ giving arbitrary command execution in the VM. Also, the service argument is not a command name, but a name of application (name of .desktop file in `/usr/share/application`, without .desktop extension - by coincidence it is the same for xterm and firefox).
The issue with original form is that `qubes.VMShell` service (the thing used without --service option) is not considered GUI service, so do not wait for X server startup. Unconditionally marking `qubes.VMShell` as GUI service IMO is a bad idea, because there are some use cases when GUI is not needed (for example downloading updates for dom0). And in Qubes 4.0 you can even choose to not start X server in a VM at all (set `gui` feature to false).

I see multiple possible solutions here:
1. Introduce another service, `qubes.VMShellWithGUI`, which will wait for X server startup.
2. Modify qvm-run tool to prepend wait for X server startup to the command, unless `--nogui` option is given (the command is already mangled before piping to `qubes.VMShell`, at least to add `exit` at the end).
3. Repurpose `qubes.VMShell` service to be the one with GUI, then introduce another one, for example `qubes.VMShellHeadless` without GUI. And carefully modify all places that use it (in practice there should be very few such places).

**Comment by rootkovska** [comment]
This still doesn't work.

**Comment by marmarek** [comment]
What _exact_ command have you used?

**Comment by marmarek** [comment]
Also, see https://github.com/QubesOS/qubes-issues/issues/3012#issuecomment-325016860 for possible solutions. Personally I like the third one.

**Comment by rootkovska** [comment]
> What exact command have you used?

```qvm-run --service qubes.StartApp+xterm --dispvm```

(BTW, it seems the argparse doesn't accept if I specify the arguments in a different order?)

**Comment by marmarek** [comment]
> qvm-run --service qubes.StartApp+xterm --dispvm

It works for me... What error have you got? Did you installed template updates (from testing)?
 
> (BTW, it seems the argparse doesn't accept if I specify the arguments in a different order?)

Yes, argparse is more strict about ordering than previous, deprecated version (optparse).
Technically, the correct order is `qvm-run --dispvm --service qubes.StartApp+xterm`. `--dispvm` accepts optional argument - a name of base VM, so if you use `qvm-run --service --dispvm qubes.StartApp+xterm`, it will get `qubes.StartApp+xterm` as a base VM name...

**Comment by marmarek** [comment]
Interesting, it works better when you add `-p` option. I have no idea why, yet.

**Comment by jpouellet** [comment]
> 2. Modify qvm-run tool to prepend wait for X server startup to the command, unless --nogui option is given (the command is already mangled before piping to qubes.VMShell, at least to add exit at the end).
> 3. Repurpose qubes.VMShell service to be the one with GUI, then introduce another one, for example qubes.VMShellHeadless without GUI. And carefully modify all places that use it (in practice there should be very few such places).

From just reading the command line help / man page, I expected that that `qvm-run --gui` *would* wait for the X session to be up before running my command.

Requiring users to be aware of qubes.VMShell* and X-related side-effects makes the command line (specifically --gui without --service) feel broken IMO.

My expectations as a user would be solution 2, or solution 3 iff --gui / --nogui controls which of qubes.VMShell / qubes.VMShellHeadless the positional command string is passed to.

**Comment by marmarek** [comment]
> Interesting, it works better when you add -p option. I have no idea why, yet.

Found it: it's about qrexec data connection timeout, which is 5s by default. Waiting for session is included in that timeout, so on slower machines it didn't had a chance.
