### ISSUE TITLE
Laptop overheating (Dell XPS L502X) in Qubes R3.2 after kernel update to 4.9.x

### ISSUE THREAD

**Issue by hopefulfork** [QubesOS/qubes-issues#3025]
#### Qubes OS version (e.g., `R3.2`):
R3.2

### Expected behavior:
Laptop doesn't get hot when idle or under small loads.

### Actual behavior:
Laptop overheats even when idle. Critical temperature levels are reached with 30-40 minutes, resulting in a hardware protection turning the system off.

### Steps to reproduce the behavior:
Boot the system, login.

### General notes:
Seems like it is a regression with latest upgrade to kernel 4.9.x. This behavior isn't observed with kernels from 4.4.x branch.

I expect it has something to do with video card or memory, not CPU - average load is less then 0.2, but the system still overheats. I can provide more info, just don't know how to debug this issue it further.

**Comment by andrewdavidwong** [comment]
Might have to close this if it's too localized (i.e., only affects your laptop model), but I'll leave it open for now in case it's a more widespread issue with the new kernel.

**Comment by carryforward** [comment]
I am also seeing a regression on my Dell.  I was observing numerous crashes pointing to video issues. I have seen the crashes occur when I am using an external HDMI monitor.  reconfiguring the attached monitors causes the system to crash fairly repeatably.

Video is the embedded intel video on a broadwell i7-5600U

The wireless network card also no longer resumes from suspend.

(note, the last kernel update last week hosed my system.  I could not boot after upgrading.  The kernel would panic as it was booting.  Reinstalling 3.2 from scratch and updating to the latest kernel is the current state)

will the 4.0 release also be using the 4.9.x kernel?

**Comment by marmarek** [comment]
Try adding 'iommu=no-igfx' option to Xen command line (just after
dom0_mem option).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by rtiangha** [comment]
@hopefulfork: I have this exact same laptop and I do not encounter this issue; my unit works fine for hours running kernel 4.9. However, the L502X is notorious for having a crappy cooling system, and simply replacing the stock thermal pad of the heatsink with proper thermal paste can reduce temperatures by a significant number of degrees (check out the forums on notebookreview.com; overheating issues appearing over time on these units have been heavily documented and most people have worked around it by reapplying proper thermal paste and re-seating the heatsink).

The definitive test would be booting into kernel 4.4 and running your machine for a few hours to see if the issue persists (I know you said it didn't happen before, but you should do it now to see if it really is a regression). If it does still persist, it'd be a hardware problem. Although to be fair, this model is about six years old now, so maybe a fan replacement or cleaning might help as well (there could be a lot of fan blade buildup, depending on your usage).

**Comment by hopefulfork** [comment]
I can confirm that with 4.9 kernel my unit overheats while with 4.4 it works fine (to the degree that bad cooling system allows; still it is good enough to keep it warm, but not hot). So I'm basically forced to use it with 4.4 kernel in dom0 and 4.9 kernel in domU.

So the issue isn't with the cooling system but the software. Any ideas how to debug it further?

**Comment by rtiangha** [comment]
@hopefulfork: What version of the BIOS are you running?

**Comment by rtiangha** [comment]
For the longest time, I ran A12, but I've recently switched to a modded bios that has a few more tweaks (like completely removing Computrace), including an undervolted version that runs slightly cooler (but even on regular A12, I could still run the laptop on kernel 4.9 for hours).

https://github.com/Thiblizz/l502x-modded-bios

But yeah, Dell only lists those two versions now, but back in the day, they had others like A08 and such, and I remember that there were some power management and ACPI fixes that might make it work better with kernel 4.9. If you can, try updating to see if it helps (even A06 could help with performance since it enabled AES-NI support in the CPU).

Unfortunately, there's no way to do it without Windows, unless you can figure out how to boot into DOS on a flash drive to run the utility there. Unfortunately, the DOS method only works with Dell's stock BIOS and not the modded version. I keep a version of Windows on a separate hard drive just for things like this, and swap it in whenever I need access to it.

**Comment by hopefulfork** [comment]
BIOS update resolved the issue for me. Thanks @rtiangha
