### ISSUE TITLE
Interrupting qvm-shutdown --all causes system freeze

### ISSUE THREAD

**Issue by Yethal** [QubesOS/qubes-issues#3052]
#### Qubes OS version (e.g., `R3.2`): 
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): 
Dom0

---

### Expected behavior:
Interrupting the action will leave the system usable and stable
### Actual behavior:
Interrupting the action causes the system to stop responding to input
### Steps to reproduce the behavior:
1. Have a lot of VMs open
2. qvm-shutdown --all
3. While the above command executes interrupt it by pressing Ctrl+C
### General notes:
I have recent backups so I don't mind reproducing it over and over in order to obtain logs (if necessary).

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
