### ISSUE TITLE
USB devices are not auto-detached when DispVM is destroyed

### ISSUE THREAD

**Issue by Yethal** [QubesOS/qubes-issues#3053]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-25 but the issue is not template-dependent

---

### Expected behavior:
USB devices are detached before DispVM gets destroyed
### Actual behavior:
USB devices are not detached which makes it impossible to attach them to another VM without physically replugging/power-cycling the device. "Invalid speed received" error message is printed.
### Steps to reproduce the behavior:
1. Launch a DispVM
2. Attach a USB device to DispVM
3. Close all windows belonging to DispVM (to trigger its destruction)
4. Try attaching the USB device anywhere else.
### General notes:

Everything works fine if the device is manually detached from DispVM so adding an additional step to the shutdown script should solve the issue. Something akin to this could be used:
qvm-usb -d $(qvm-usb|grep disp|cut -f1)
---

#### Related issues:

**Comment by hyperfekt** [comment]
It appears to me this bug also occurs when shutting down any other VM normally.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
