### ISSUE TITLE
nemo-3.4.7-2 changes Firefox download handling in Fedora 25 minimal template

### ISSUE THREAD

**Issue by mvermaes** [QubesOS/qubes-issues#3064]
#### Qubes OS version

R3.2

#### Affected TemplateVMs

fedora-25-minimal

---

### Expected behavior

Firefox downloads open with the default file manager (Nautilus)

### Actual behavior

After updating to `nemo-3.4.7-2.fc25.x86_64`, Firefox downloads are now opened in Nemo instead. This means Qubes extensions like _Move To Other AppVM..._ are unavailable.

### Steps to reproduce the behavior

- Create AppVM based on `fedora-25-minimal`
- `dnf install -y firefox`
- _Firefox->Tools->Downloads->Open Containing Folder_ next to a downloaded file
- Nautilus will open
- `dnf install -y nemo`
- Reopen Firefox
- _Tools->Downloads->Open Containing Folder_ will now open Nemo

### General notes

The issue seems to be https://bugzilla.redhat.com/show_bug.cgi?id=1384788, where it's indicated that this is a bug/change in behaviour in Nemo. So I'm not sure if anything can/should be done in Qubes to address this, but I also don't know why Nemo is installed by default in the minimal template? I hadn't realized it was until encountering this change, and unfortunately it doesn't seem like it can be easily removed.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
