### ISSUE TITLE
Default emulated disk in Qubes 4.0 HVM is not supported by Windows 7 installer

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3068]
### Expected behavior:

Windows installer allow to install the system.

### Actual behavior:

Windows installer complains: "No drives were found".

### Steps to reproduce the behavior:

Launch Windows 7 installation (currently tricky because of #2951).

**Comment by marmarek** [comment]
PR for #2951 created, so working on this issue is easier now.

From what I see, Windows 7 do not support the SCSI controller emulated by qemu option `-drive if=scsi,...`. But it does support standard IDE and AHCI (`-device ahci,id=ahci0 -drive if=none,id=ahcidisk-0,... -device ide-hd,bus=ahci0.0,drive=ahcidisk-0`). Libxl do support creating AHCI disks (VM-wide switch: `b_info->u.hvm.hdtype = LIBXL_HDTYPE_AHCI`), but qemu does not support AHCI read-only disks (as well as IDE). For IDE drives in qemu, read-only property is tied up to being CDROM (`ide_dev_initfn` function in `hw/ide/qdev.c`).
I see those options:
 - look how it worked in Qubes 3.2 with qemu-xen-traditional (maybe read-only disks weren't supported there either?)
 - try some other device supported by qemu (maybe another SCSI controller?),
 - create IDE/AHCI device for read-write devices, and SCSI for read-only ones (those will be unavailable to Windows...),
 - look how hard would be adding read-only support to AHCI emulation

@HW42 do you have idea for reasonable solution here?

**Comment by HW42** [comment]
I would try another scsi controller. I already looked at the problem a while back and there are scsi contollers supported by Windows out of the box (I had tested some Win 7 Pro and Win 10 Pro installers). IIRC 'mptsas1068' and 'megasas' are supported by windows. I did not switched to those because Linux and Freebsd had problems with the emulated controller. But maybe this is already fixed. I/We have to retry.
