### ISSUE TITLE
An instruction for mirror operators

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#3069]
Could you set up a page for mirror operators with a short instruction? Just that
- we welcome mirrors
- we are happy to provide rsync or HTTP master
- preferred frequency is once per 24 h, but anything up to once per 6-8 h is fine
- for technical accommodations please contact Wojtek or Marek, for website update please contact Andrew <details>The truth is we have anonymous rsync master, but we don't want to announce it publicly. And putting authentication in front of that would be a pain for current mirrors.</details>
- anything else?

Probably linked below the mirror list at https://www.qubes-os.org/downloads/, also maybe somewhere around donations/partners for people that can't or don't want to give money but can help by donating bandwidth.

I anticipate there will be more of them coming. Cf. #3056.

Cc: @marmarek

**Comment by adrelanos** [comment]
Recently forwarded a mirror offer to Marek. He said currently no more
mirrors are required.

I also think it's good to keep the number low as long as not required.
We used to have a similar setup for whonix.org downloads, but it was
quite a time effort being wasted since a lot mirrors went down and then
a few (round robin lottery) users wondered why downloads are broken.

**Comment by woju** [comment]
We could monitor uptime of those and reject the unreliable.

The problem is, a mirror is generally a one-time offer. If we turn down the mirror, they most likely won't come again. We might need them in the future, if we like Qubes to conquer the world.
