### ISSUE TITLE
Crashing when attempting to create win7 or kali HVM.

### ISSUE THREAD

**Issue by Kayloria** [QubesOS/qubes-issues#3078]
I'm trying to setup a Windows 7 and Kali Linux HVM on my Qubes laptop. I have followed the steps outlined in the official HVM guide. I have placed both ISO files on the dom0 desktop. When I attempt to run the following command it will start to run and then force restart the machine. This has happened with both the kali and win7 iso.

### Expected behavior:
Initial startup of a win7 or kali HVM with the ISO attached with the --cdrom command.

> qvm-start win7 --cdrom=/home/me/Desktop/win7.iso

### Actual behavior:

Command will start to run and then the laptop hard restarts. I get the following text before it happens..

> --> Loading the VM (Type=HVM)...
> --> Starting Qubes DB... (It sits on this for 2-3 seconds then crashes)

### General notes:
Laptop Model: HP Elite Book 745
AMD virtualization is enabled in the bios.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
