### ISSUE TITLE
sys-usb crashes after accessing filesystem of an Android device connected to an AppVM

### ISSUE THREAD

**Issue by Yethal** [QubesOS/qubes-issues#3081]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-25

---

### Expected behavior:
It is possible to access filesystem of an Android device

### Actual behavior:
After tapping Yes on the MTP prompt on the Android device sys-usb crashes
### Steps to reproduce the behavior:
Attach an Android phone or tablet to the machine
Attach it to a VM via qvm-usb
Open Nautilus in the VM holding the phone
Try accessing the phone's filesystem
Tap Yes on the MTP confirmation screen on the device

### General notes:
Does not occur if filesystem is accessed from within sys-usb itself.

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
