### ISSUE TITLE
Installer silently failed to setup templates.

### ISSUE THREAD

**Issue by dhksa** [QubesOS/qubes-issues#3122]
#### Qubes OS version (e.g., `R3.2`):
4.0-RC1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All templates.

---

### Steps to reproduce the behavior:
Download 4.0-RC1 iso and install, finish setup with default options(install templates, add sys-net/sys-usb and add domains.)

### Expected behavior:
Installer should setup templates

### Actual behavior:
Templates are not setup correctly,  have no apps on any template or domain. sys-firewall won't start so could not reinstall templates.

```
[user@dom0]$ ls /var/lib/qubes/vm-templates/
debian-8  fedora-25  tmp-debian-8  tmp-fedora-25
```

```
[user@dom0]$ ls /var/lib/qubes/vm-templates/debian-8/
icon.png
```

```
[user@dom0]$ ls /var/lib/qubes/vm-templates/tmp-debian-8/
apps  root.img.part.00  root.img.part.01  root.img.part.02  icon.png (etc.)

```

```
[user@dom0]$ ls /var/lib/qubes/vm-templates/fedora-25/
icon.png
```

**Comment by marmarek** [comment]
Do you have them listed by `qvm-ls`? Almost empty /var/lib/qubes/vm-templates/fedora-25/ is ok, because now template data live in LVM.

**Comment by test1943** [comment]
Hi, @marmarek,

here are some screenshot of my new install(without debian template):

![image](https://user-images.githubusercontent.com/584294/30845058-45596f56-a2c4-11e7-993b-68c8f55f4cd3.png)

![image](https://user-images.githubusercontent.com/584294/30844802-30cb972c-a2c3-11e7-9ae6-51215fbd5fa2.png)

![image](https://user-images.githubusercontent.com/584294/30844830-59d13348-a2c3-11e7-81dc-f0c8a8538fbd.png)

![image](https://user-images.githubusercontent.com/584294/30845281-44eb5e34-a2c5-11e7-9f90-1096bd5bacae.png)
sys-firewall vm exits inmediately after this screenshot.

**Comment by marmarek** [comment]
Ok, so there is indeed something wrong with template setup, but not lack of the files.
There are two things:
1. Why it happened.
2. How to fix it.

The later one should be simple:
1. Start `fedora-25` template (either from the menu, or using `qvm-start`). Wait for the startup to complete (VM window will disappear, but VM will remain running).
2. Call `qvm-run --pass-io --service fedora-25 qubes.PostInstall`
3. Shutdown the template

This should fix menu etc.

As for diagnosis about why it happened, check `sudo journalctl` - about the date of initial configuration. Look for errors from `initial-setup` service.

**Comment by DonnchaC** [comment]
I encountered a similar broken state after template setup.  Sorry for the confusing explanation. I don't know the proper names for the different parts of the installer. In my case the problem was caused after going into the template options part of the installer a second time. 

I selected the templates that I wanted and the installer began configuring those templates after I clicked to go back to the main screen. I then clicked into the template options again, after clicking back to the main screen again the installer started to configure the templates a second time, this time as 'debian-8-tmp' and 'fedora-tmp'. Perhaps there is a problem where the installer does not recognise that the VMs have already been configured.

This second configuration eventually failed with a bunch of Python exceptions from qvm-template-postprocess `qubesadmin.exc.QubesException: root.img not found`. The VMs that were left seemed misconfigured and had names like "fedora-25-tmp"

**Comment by andrewdavidwong** [comment]
@DonnchaC: That sounds familiar. I remember seeing something similar (#2433) in R3.2.

**Comment by SelfRando** [comment]
4.0 RC2 Initial Setup 

I had the same problem that DonnchaC reports above.
The initial setup ran correctly the first time. I had left the room and when I returned I clicked again on the Qubes OS banner (which was now highlighted in blue so looked different from the previous time I had seen it).
The next screen opened and since I did not wish to make any changes I clicked Done at which point the setup script ran again. This time it failed (after quite a while) with some error messages that I did not record.

I booted Qubes for the first time and it loaded okay however no VMs would start.

To resolve this issue I did a full reinstall.

I suggest the Initial Setup script set a flag to show that it has been executed.
