### ISSUE TITLE
qvm-open-in-dvm [pdf] opens gimp

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3148]
#### Qubes OS version (e.g., `R3.2`):
4.0rc1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
debian-8, didn't test fedora

### Steps to reproduce the behavior:
`qvm-open-in-dvm [pdf file]`

### Expected behavior:
Opens a pdf reader (e.g. evince) in a dvm.

### Actual behavior:
Opens gimp in a dvm.

**Comment by marmarek** [comment]
Apparently gimp register itself as pdf viewer. Try setting something
else in debian-8 template using xdg-mime command (as root).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 3hhh** [comment]
For some reason I thought Qubes would maintain an own MIME handler list, but once I come to think about it that wouldn't make too much sense.
@marmarek Thanks for the hint once again!

Then it's https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807772 and not a Qubes issue.

For reference:
Editing `/usr/share/applications/mimeinfo.cache` in the debian-8 template fixed the issue.
