### ISSUE TITLE
Qubes R4 - first boot wizard - Cannot execute qrexec-daemon

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3153]
#### Qubes OS version (e.g., `R3.2`):

R4 RC1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

default R4 RC1
---

### Steps to reproduce the behavior:

Fresh installation Qubes R4 RC1. Leaving standard settings at first boot wizard.

### Expected behavior:

No such error.

### Actual behavior:

```
[Dom0] Error
['/usr/bin/qvm-start', 'sys-firewall'] failed:
stdout: ""
stderr: "Cannot execute qrexec-daemon!"
OK
```

**Comment by marmarek** [comment]
See if anything more is in `sudo journalctl`. Or try `qvm-start sys-firewall` from console.

**Comment by stevenc99** [comment]
I've seen the same error during installation of 4.0rc2, twice to an empty hard drive, using all default settings except that I ticked the "Configure template updates over Tor" option.  journalctl has no additional information.

After configuration (and the above-mentioned error), the Qubes Manager GUI fails to open, and its icon tooltip is blank. Trying to start most of the pre-configured VM fails, because they depend on sys-net, and that VM fails to start.  "xl console sys-net" remains blank, and "xl console sys-net-dm" shows a general protection fault from qemu. After about a minute, both of these VMs are destroyed.

I guess, the problem starting sys-firewall (during first-boot wizard) could be because sys-net fails to start.  The error in sys-net-dm console is:

+ xenstore-watch -n 2 device-model/13/command
traps: qemu[44] general protection ip:7fb953e3def5 sp:7fb951f6f8e0 error:0 in libc-2.24.so[7fb953dbd000+1bd000]
u2mfn_release,priv= (null)

Immediately before that is some mention PCI passthrough configuration, for slot=6 (device:133, vendor:32902, qdev_id:xen-pci-pt_0000-03-00.0) which is my wireless chipset, Intel Centrino Advanced-N 6205 [Taylor Peak] (rev. 34).  This is a Thinkpad x230, 16GB RAM, tried with both 250 HDD and 525GB SSD.

Many thanks.

**Comment by stevenc99** [comment]
sys-net starts normally when I detach my PCI WLAN card:
dom0# qvm-device pci detach sys-net dom0:03_00.0
so that appears to be crashing qemu-dm somehow.

sys-firewall starts successfully after that.

**Comment by stevenc99** [comment]
Changing sys-net from virt_mode:hvm to pv, also fixes this bug for me (with PCI WLAN passed through).

**Comment by marmarek** [comment]
Install updates from testing repository, especially QubesOS/updates-status#295. Very similar issue (qemu crash) is fixed there. Then switch virt_mode back to hvm.

**Comment by stevenc99** [comment]
Updating to xen-hvm-stubdom-linux from testing, seems to have fixed this, thank you!
(I am able to start the sys-net VM in hvm mode, with PCI WLAN attached, without it crashing.  I cannot test the first-boot wizard.)
