### ISSUE TITLE
Kernel-devel still 1000:4.4.31-11.pvops.qubes on Fedora 25 somehow?

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#3158]
#### Qubes OS version (e.g., `R3.2`):
R 3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Fedora -25
---

### Steps to reproduce the behavior:

try installing kernel-devel 
sudo yum install kernel-devel

### Expected behavior:

Kernel devel being available for a relatively recent kernel

### Actual behavior:

Only kernel-devel 1000:4.4.31-11.pvops.qubes is available, and if different, more recent kernel is used, building custom drivers (like say wifi) becomes impossible.

Having a netvm use a rather old kernel makes me nervous, plus qubes-updates become rather annoying experience because the (very old) kernel gets uninstalled and I have to install it manually just to get network going (which is a bit annoying if your netvm can't load the driver)

### General notes:
Same thing happened in fedora 24 but I kind of thought/hoped it was a sunsetting thing and kernel devel would be available for 25 without any issue 

---

#### Related issues:

https://github.com/QubesOS/qubes-issues/issues/2692

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
