### ISSUE TITLE
deleteing fedora-25-dvm breaks qubesd in Qubes R4

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3161]
#### Qubes OS version (e.g., `R3.2`):

R4 RC1 with all stable upgrades

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

dom0

---

### Steps to reproduce the behavior:

    qvm-remove fedora-25-dvm

Reboot.

### Expected behavior:

qubesd and whole Qubes should still work normally after reboot.

### Actual behavior:

qubesd fails to start which makes Qubes unusable.

### General notes:

How to get out of this?

(qvm-create fedora-25-dvm to satisfy qubesd isn't possible since qvm-create itself requires qubesd.)

**Comment by marmarek** [comment]
It shouldn't be possible to remove VM that is referenced from somewhere (`default_dispvm` global property in this case). This is already fixed in testing updates.

> How to get out of this?

Edit `/var/lib/qubes/qubes.xml` and replace `default_dispvm` value with some existing VM. Then qubesd should start and you can re-create fedora-25-dvm.

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
>> How to get out of this?
> 
> Edit `/var/lib/qubes/qubes.xml` and replace `default_dispvm` value with some existing VM. Then qubesd should start and you can re-create fedora-25-dvm.
> 

Removing all references to default_dispvm from /var/lib/qubes/qubes.xml
worked for me, thanks!
