### ISSUE TITLE
after qvm-killing sys-net, can't restart it, Mac address in use (R4.0-rc1)

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#3163]
#### Qubes OS version (e.g., `R3.2`):
R4.0-rc1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
debian-8

---

### Steps to reproduce the behavior:
start, then qvm-kill sys-net, then try to restart it.
### Expected behavior:
sys-net boots
### Actual behavior:
sys-net fails to boot, error message is displayed about mac address.

**Comment by schnurentwickler** [comment]
That also happens in Qubes 3.2.
Because a clean shutdown is missing, some missing command cannot release the xen mac address. After some time waiting the restart works without any error. (only if the sys-net VM boots up successfully and then and only then the following network-ordered ProxyVM starts.)

**Comment by ERFier** [comment]
I had a similar issue in R4 rc2. It turned out that I can restart sys-net if i shutdown the attached sys-firewall. I dont know how its working in detail but it seems like the connected VM keeps the pipe open and the restarted vm tries to create a new one with the same MAC. Once the connected vm is shut down the channel is freed and sys-net can create it again.

**Comment by marmarek** [comment]
This is user visible effect of missing libvirt functionality: #1426. Closing as duplicate.

**Comment by marmarek** [comment]
I'm reopening this one, because there may be a way to allow this particular functionality (restarting sys-net without restarting all other VMs) without fully implementing missing underlying functionality (#1426).

**Comment by andrewdavidwong** [comment]
> I'm reopening this one, because there may be a way to allow this particular functionality (restarting sys-net without restarting all other VMs) without fully implementing missing underlying functionality (#1426).

Is there any reason not to implement the "restarting sys-net without restarting all other VMs" feature as a script that performs the steps below?

1. Sets the netvms of all ProxyVMs depending on `sys-net` to `none`.
2. Shuts down `sys-net`.
3. Starts `sys-net`.
4. Sets the netvms of all ProxyVMs modified in step 1 back to `sys-net`.

I personally use a simple bash script for this (because the only ProxyVM I have to modify is `sys-firewall`).

**Comment by marmarek** [comment]
> The problem is that there's a bug that prevents step 3 from occurring, because sys-net won't start back up again after it's been shut down. Is that right?

Yes. Also step 1 breaks if sys-net is already crashed.
And I think I've fixed both things already. It should be possible to start sys-net again, after it being shutdown for whatever reason, even without detaching network first. This isn't the proper fix, mostly a workaround, but I hope an effective one.
