### ISSUE TITLE
office 365 in windows hvm 

### ISSUE THREAD

**Issue by changemenemo** [QubesOS/qubes-issues#3176]
#### Qubes OS version:

R.3.2

#### Affected TemplateVMs: 

HVM win 7 

---

because of the lack of windows to recognize the connectivity and that the system is connected to internet, it seems that the connection module of office once installed, can't recognized that windows is connected and so it cannot connect me to my account to retrieve my notes on onenote for example. 
I never encountered this issue just after the installation and since the network in win7 hvm is known issue, I guess it's been related.
Is there any attempt to resolve the pronlem of the network not being identified ?

**Comment by boistordu** [comment]
![screenshot_2017-10-15_22-24-33](https://user-images.githubusercontent.com/9523075/31588847-2685627c-b1f8-11e7-84ca-198d1316f76a.png)

**Comment by marmarek** [comment]
Does network in that VM works at all (regardless of status icon)?

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
