### ISSUE TITLE
no shares accessible with windows hvm

### ISSUE THREAD

**Issue by changemenemo** [QubesOS/qubes-issues#3177]
#### Qubes OS version:

R3.2

#### Affected TemplateVMs: 

windows 7 hvm

---
Because of the known issue about the network. I can't link my windows hvm to network share since it will propose to me to connect to internet through dial up or broadband. 
Since xen disk drivers are not operaitonal, network shares would have been a good alternatives but seems difficult now...

**Comment by 3n7r0p1** [comment]
> the known issue about the network

Are you referring to https://github.com/QubesOS/qubes-issues/issues/2263? That seems to be purely cosmetic. Ask qubes-users for help troubleshooting your Windows net connection.

> network shares would have been a good alternatives

Many options for Windows file transfers:
qvm-copy-to-vm
samba shares (as per https://github.com/QubesOS/qubes-issues/issues/2826)
ssh
freerdp

**Comment by boistordu** [comment]
Yeah I'm refering to the cosmetic issue which is apparently more deep thanjust cosmetic since i have a problem with office 365 too.

I thought that qvm-copy-to-vm would'nt work because of the xen disk drivers problem? 
samba shares that was what I was refering to... I have a window that says that I have no connectivity, but it seems that we can press cancel and then retrieve the window of the configuration of the share and then configure it normally. 

didn't think about ssh and freerdp right.

**Comment by boistordu** [comment]
![screenshot_2017-10-15_22-23-00](https://user-images.githubusercontent.com/9523075/31588863-53f58c14-b1f8-11e7-88df-14304c839f68.png)

**Comment by 3n7r0p1** [comment]
Tested with Win 7, Win 10, with and without QWT. Samba, RDP, qvm-copy-to-vm (with QWT) all work. Network functionality is fine despite system tray icon that says "No Internet access". If system tray says something else, you need to troubleshoot your Windows network settings.

This is a configuration issue. Not a bug. Please close.
