### ISSUE TITLE
DispVMs are autodestroyed if default terminal is changed from xterm

### ISSUE THREAD

**Issue by Yethal** [QubesOS/qubes-issues#3180]
#### Qubes OS version:

3.2

#### Affected TemplateVMs: 

issue does not seem to be template dependent

---

### Steps to reproduce the behavior:

1. Go to /usr/local/share/applications
2. Open qubes-dispvm-xterm.desktop file
3. Change Exec from xterm to gnome-terminal
4. Save changes
5. Start terminal in a dispvm

### Expected behavior:

VM is started and gnome-terminal stays open until closed by the user.

### Actual behavior:

VM is started and gnome-terminal is launched however after a second it selfdestructs.

### General notes:

I assume the whatever mechanism is responsible for destroying the VM has a hardcoded check for xterm. If that's the case, documenting its location seems sufficient.
---

**Comment by marmarek** [comment]
> I assume the whatever mechanism is responsible for destroying the VM has a hardcoded check for xterm. If that's the case, documenting its location seems sufficient.

No, the problem is when you start `gnome-terminal`, it ends immediately, even though actual terminal is still running (hosted by gnome-terminal-server process). You can see this behavior by starting gnome-terminal from another terminal.
Since DispVM is destroyed immediately after its "main application" exits, gnome-terminal is not suitable for this use, unfortunately.

**Comment by andrewdavidwong** [comment]
Duplicate of #2581
