### ISSUE TITLE
Dynamic network switch does not work with debian-9 based VMs

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3192]
#### Qubes OS version:

R4.0rc1, probably R3.2 too.

#### Affected TemplateVMs: 

debian-9

---

### Steps to reproduce the behavior:

1. Setup debian-9 based VM
2. Start it
3. Change its netvm (for example from sys-firewall to sys-net)

### Expected behavior:

Network works with new setting.

### Actual behavior:

`eth0` is there, but is not configured (no IP address, not up, no default gateway).

**Comment by mfc** [comment]
just wanted to comment that I currently encounter this with Debian 9-based qubes/AppVMs in R3.2. The template is up-to-date so it is not totally clear what the issue is, however thanks to Marek's advice I can run `sudo INTERFACE=eth0 /usr/lib/qubes/setup-ip` from the qube/AppVM to make it update to the new networking path.
