### ISSUE TITLE
qvm-remove sys-whonix error - QubesException: domain is in use "sys-whonix"

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3193]
#### Qubes OS version:

Qubes R4 with all Qubes testing repositories

#### Affected TemplateVMs: 

Dom0

---

### Steps to reproduce the behavior:

Install Qubes R4 with all Qubes testing repositories.

Enable Qubes community templates repository in /etc/yum.repos.d/qubes-templates.repo.

    sudo qubes-dom0-update qubes-template-whonix-gw qubes-template-whonix-ws

(Did last command because of https://github.com/QubesOS/qubes-issues/issues/3188.)

    sudo qubesctl state.sls qvm.sys-whonix
    sudo qubesctl state.sls qvm.sys-whonix
    sudo qubesctl state.highstate

    qvm-prefs --set sys-whonix netvm sys-firewall

    qvm-start sys-whonix

    qvm-kill sys-whonix
    qvm-remove sys-whonix

### Expected behavior:

sys-whonix removed.

### Actual behavior:

Error message

> QubesException: domain is in use "sys-whonix"

Checked using `qvm-ls` that sys-whonix is not running, it's halted, whonix-gw and whonix-ws are halted as well and anon-whonix does not exist. No other VM using sys-whonix. I wonder what may be using sys-whonix?

**Comment by marmarek** [comment]
See `journalctl` in dom0 for details where exactly it is used. You can't remove it if it's netvm of some other VM, even if not running. You need to change netvm first.

**Comment by adrelanos** [comment]
Right.

`whonix-ws-dvm` is using `sys-whonix`.

And `qvm-remove whonix-ws-dvm` is also refused, because it is being used by `whonix-ws-dvm.default_dispvm`.

The required commands are:

    qvm-prefs --set whonix-ws-dvm netvm ""
    qvm-prefs --set whonix-ws-dvm default_dispvm ""
    qvm-remove whonix-ws-dvm
    qvm-remove sys-whonix

So this is not a core, but more a documentation or usability issue.

**Comment by adubois** [comment]
From an end user point of view, whonix-ws-dvm is visible from qvm-ls, so it make sense for him to naturally delete it before it's netvm.
However what is not obvious is qvm-remove whonix-ws-dvm -> Domain in use.
`qvm-prefs --set whonix-ws-dvm default_dispvm ""` as mentioned above fixed it.

If there is no real dependency (AFAIK this property is a property of the object itself, so should not be a blocker) -> so rather than doc update, should this ticket be tagged as bug in qvm-remove?

otherwise, happy to do the PR for the doc update of qvm-remove instructing that:
- --force should be used because of that qvm-prefs value
- that qvm-prefs should be cleared <-- my preferred solution

**Comment by adubois** [comment]
Created https://github.com/QubesOS/qubes-doc/pull/610
Problem is not limited to qvm-prefs of DVM itself.
