### ISSUE TITLE
Sudden tearing in videos (youtube etc) as if a "vsync issue" was afoot when trying to get two monitors with different refresh rates work in dual-head config (esp if another, unrelated VM is highly active)

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#3194]
#### Qubes OS version:

R 3.2

#### Affected TemplateVMs: 

dom0 ?

---

### Steps to reproduce the behavior:

Just play a video on youtube using intel embedded driver on Skylake while having two screens (144 hz one and a 60 hz one)

The window with movie (youtube in a browser) is on 144hz screen.

### Expected behavior:

No VSYNC issue, no tearing, movie plays smooth.

### Actual behavior:

Spontaneous bursts of tearing as consistent with "vsync not working right"

### General notes:

Two 60hz screens and 144 Hz + 144 Hz screen have so far not produced this issue.

P.S.: adding the following to xorg.conf alleviated issue MASSIVELY in firefox and "moderately" in chrome.

Option "TearFree" "true"
Option "TrippleBuffer" "true"
Option "Vsync" "true"

More interestingly, according to https://www.vsynctester.com/ the issue becomes more pronounced if some "heavy lifting" is done  in **another** (unrelated) VM. 
Is a VM being able to affect VSYNC (and, seemingly, only VSYNC since no dropped frames) in another VM... normal?

---

**Comment by Yethal** [comment]
Where exactly did you modify the file? In dom0? In templates? And in which directory?

**Comment by tonsimple** [comment]
in dom0
/etc/X11/xorg.conf

**Comment by Yethal** [comment]
I don't have that file there.

**Comment by tonsimple** [comment]
Weird, I do, and its settings are working (easily tested by trying to delete all screen entries, which prevents xfce start (I did try it just to make sure my file actually **works**)

**Comment by Yethal** [comment]
[Yethal@dom0 ~]$ ls /etc/X11
applnk  fontpath.d  xinit  Xmodmap  xorg.conf.d  Xresources
Is this file supposed to be autocreated at some point during the installation process?

**Comment by tonsimple** [comment]
I don't know, but I think it "was there for me" when I recently re-installed qubes due to one of ASUS's dumb weird BIOS bugs.
I think there's an x command to autocreate it if it is absent....

**Comment by samcv** [comment]
I am using 4.0-rc3, and by default XFCE is setup with vertical sync (vsync) disabled. May not be totally related to this issue, maybe I should open another issue to see if the default for that preference can be changed?

P.S. @tonsimple are you using KDE of XFCE?

**Comment by brendanhoar** [comment]
FWIW, the following substantially improved youtube HD video viewing in my personal VM (using firefox) on a Thinkpad W520 with integrated (intel) graphics. The options may be specific to the intel driver.

- Open Terminal in dom0
- cd /etc/X11/xorg.conf.d/
- sudo vi 10-display.conf
- Put the following content in it (assumption you know vi basics)

Section "Device"
   Identifier "Intel Graphics Card0"
   Driver "intel"
   Option "TearFree" "true"
   Option "TripleBuffer" true"
   Option "Vsync" "true"
EndSection

-- Save the file

If you make a typo (or if I did) and Xorg can't parse it, X11 won't load. You'll need to hit alt-f2, login as qubes-user and remove or rename the file without the conf extension and reboot to fix it. Ask me how I know... :)

I also enabled Qubes/System Tools/Windows Manager Tweaks/Compositor/"Synchronize drawing to the vertical blank" before the above, but that did not seem to make a difference. I haven't turned it off since making the above change, though.

**Comment by brendanhoar** [comment]
Clarification: this was under Qubes V4.0RC4

**Comment by marmarek** [comment]
Thanks for researching this @brendanhoar !
While considering something we could put in default installation, the above will break non-intel hardware. But I think using `OutputClass` should work:
```
Section "OutputClass"
    Identifier "Intel Graphics Card0"
    # not sure if should be "intel" or "i915"
    MatchDriver "i915"
    Option "TearFree" "true"
    Option "TripleBuffer" true"
    Option "Vsync" "true"
EndSection
```

**Comment by samcv** [comment]
Personally it doesn't make sense to me to force the GPU driver settings into a less efficient and non-driver portable setting instead of changing the settings for the DE to use vsync. Changing the setting for XFCE would affect all video cards and not have to mess with any of the Xorg or driver settings. Forcing the drivers to use "TearFree" reduces performance and battery life needlessly. The simple solution is to have the DE use vsync instead of trying to get the GPU to correct for the DE's lack of using vsync itself.

On the Intel driver: TripleBuffer and VSync are already enabled by default. @brendanhoar referred to the setting as "Vsync" but it is actually "VSync" for the Intel GPU driver. It could possibly be case insensitive or the setting may be being ignored as the default is enabled so the setting not being applied still results in the same result.

**Comment by Yethal** [comment]
What about non-Intel GPUs? If it's as simple as single configuration file per vendor it would only be a matter of detecting the gpu via lspci/modprobe and choosing appropriate file.

**Comment by brendanhoar** [comment]
Hi Sam,

Thanks for the information on the default settings for the Intel driver making some of my changes redundant (or ignored). I will do more testing with the settings later this week.

Also, I agree with your premise, if by DE you mean Desktop Environment: if a DE setting can handle it, we shouldn't need to modify the display driver settings.

So...

I thought I had already tried that by checking the Qubes/System Tools/Windows Manager Tweaks/Compositor/"Synchronize drawing to the vertical blank" setting, but that did not seem to reduce the tearing.

Can you think of another place in the DE that I should be adjusting this? Am I interpreting your "DE" correctly?

Thanks,
Brendan

**Comment by SurinameClubcard** [comment]
I'm running Qubes R4.0 on two systems. Both have only one, Intel based, video card. The first system has an rather old Intel HD 4600 chip (PCI-id 8086:0412), the second system has a pretty new Intel HD Graphics 630. On the first system, setting "Synchronize drawing on the vertical blank" immediately fixed the tearing, on the second one nothing changed. It is (a bit annoyingly) visible when playing movies. I will experiment with above suggestions.
