### ISSUE TITLE
Qubes 3.2 and 4.9 kernel breaks Acer wifi

### ISSUE THREAD

**Issue by dballard** [QubesOS/qubes-issues#3222]
#### Qubes OS version:
3.2 with the 4.9 kernel

#### Affected TemplateVMs: 

dom0 fedora-24 net

---

### Steps to reproduce the behavior:
Install updates and get 4.9 kernel, reboot

### Expected behavior:
Wifi works

### Actual behavior:
Wifi does not work
Using the command
rfkill list all
I can see that the wifi is hard off, and pressing fn-f3 (the wifi function button) as many times as I can changes nothing

### General notes:
As per 
https://askubuntu.com/questions/98702/how-to-unblock-something-listed-in-rfkill
it appears something is bad in the acer-wmi module, adding it to /etc/modules.d/blacklist.conf and rebooting solves the problem and wifi works again

It's an Atheros wifi chip in an Acer TravelMate 8172-6643 netbook

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happen to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
