### ISSUE TITLE
200MB default boot partition size too small

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#3224]
#### Qubes OS version:
R4.0-rc2

### Steps to reproduce the behavior:
1. Install Qubes using default settings (tested with EFI), or look at the default partition layout in custom partitioning

### Expected behavior:
Boot partition is at least 500MB, preferably 1GB large.

### Actual behavior:
Boot partition is 200MB

### General notes:
200MB is enough for the current use case, but potentially impedes future features as well as tinkering by power users. Since it's very difficult to change, a larger size seems warranted. Other distributions also seem to have adopted or be moving towards 500MB+ sizes.

**Comment by marmarek** [comment]
On default non-EFI installation, /boot is about 1GB. On EFI, /boot/efi [should be 500MB](https://github.com/QubesOS/qubes-installer-qubes-os/blob/master/anaconda/pyanaconda/installclasses/qubes.py#L64-L78), and no separate /boot should be created. Apparently the latter doesn't work. 200MB is default value in Fedora, so that function either is buggy, or not called at all in the current anaconda.

**Comment by qubesuser** [comment]
The 200MB is what the automatic partition creation button after choosing custom partitioning offered on my system.

Maybe that uses a different codepath? (it also defaults to LVM instead of LVM Thin Provisioning, so it seems it could be)

Also not quite sure about the logic in having different sizes between /boot and /boot/efi since the biggest space usage is Xen and the Linux kernels and initramfses, which are of course present in both cases.

**Comment by evadogstar** [comment]
Please, remember, that some users still at 128Gb SSDs. :)

**Comment by marmarek** [comment]
Test for this (failing right now): https://openqa.qubes-os.org/tests/646#step/mount_and_boot_options/21
