### ISSUE TITLE
VMs in file-based storage pools cannot use fstrim for /rw

### ISSUE THREAD

**Issue by na--** [QubesOS/qubes-issues#3255]
#### Qubes OS version:

4.0 RC2

#### Affected TemplateVMs: 

any (tested with VMs based on both the fedora and archlinux templates)

---

### Steps to reproduce the behavior:

1. Create a file-based storage pool in dom0: `qvm-pool -a newpoolname -o dir_path=/somepath,revisions_to_keep=1`
2. Clone an existing VM to the new pool `qvm-clone -P newpoolname some-vm some-vm-2`
3. Check that the VM is present in `/somepath/appvms/some-vm-2` *(though the sparseness of the private volume is not preserved - its filesize is equal to the maximum allowed for the VM)*
4. Start the new VM
5. Verify that the private volume is mounted at `/rw` with `discard` by running `mount`
6. Try to run `sudo fstrim -v /rw`

### Expected behavior:

Successful execution of `fstrim` and reducing the actual filesize of the VM private partition file in dom0 to the actually used space (as in QubesOS 3.2 and lower) 

### Actual behavior:

Error: `fstrim: /rw: the discard operation is not supported`

### General notes:

---

#### Related issues:

None that I could find

**Comment by marmarek** [comment]
Private image on file-based pool is similar to root volume on Qubes 3.2 - online trim cannot work, but is should be possible to do it using temporary VM. Technically it is this way, because there is device-mapper snapshot-origin in the middle. It is there, to allow starting DispVMs from such VM.

In theory we could implement separate pool driver (or an option to file pool) to turn off this feature, which means:
 - only private volume could be placed there, no root volume
 - no DispVMs based on such VMs
But first we have a lot of higher priority tasks (for example affecting default configuration).

> (though the sparseness of the private volume is not preserved - its filesize is equal to the maximum allowed for the VM)

This bug should be trivial to fix.

BTW For file-based pool, IMO better approach would be looking at btrfs and implementing pool driver for it, instead of extending file + device-mapper based one. But that require btrfs instead of any filesystem.

**Comment by na--** [comment]
I'm not sure what the practical value of starting disposable VMs based on a specific AppVM is vs. being able to use just TemplateVMs for the purpose - what are the use cases for that?

And if an option to disable this feature was added to the file pool driver, do we loose the ability to have multiple `revisions_to_keep` as well?

**Comment by marmarek** [comment]
> I'm not sure what the practical value of starting disposable VMs based on a specific AppVM is vs. being able to use just TemplateVMs for the purpose - what are the use cases for that?

Customizing also private volume for that VM (like browser plugins etc), while still using the same template for other VMs (less places to apply updates). And also smaller disk usage.

> And if an option to disable this feature was added to the file pool driver, do we loose the ability to have multiple revisions_to_keep as well?

Unfortunately yes.

**Comment by qubesuser** [comment]
How about just disallowing having both an AppVM and DispVMs based on it running at the same time when using a file pool? (and thus mounting the volume directly in the AppVM and only creating the LVM-based CoW setup when DispVMs are running)

It shouldn't be a problem in normal use, and the user can always just clone the VM and make the clone the dispvm template if it is.

But just deprecating the file pool in favor of the thin pool seems an even better short term solution.

**Comment by Rudd-O** [comment]
Well this seems like a big problem, I noticed my ZFS pool (where I store VM images using the `file` Qubes pool) was getting enormous and I couldn't quite figure out wtf was wrong.  Then I tried `fstrim` and it failed as well.

Obviously for us ZFS users it's not at all an option to deprecate the file-based pool.  A while ago I offered funding for a ZFS pool driver but I was told that I couldn't direct what the funding would be used for, so I withdrew the offer.

**Comment by rustybird** [comment]
The device-mapper snapshot target recently gained some sort of discard support (see [snapshot.rst](https://www.kernel.org/doc/Documentation/admin-guide/device-mapper/snapshot.rst)) that might be suitable for the `file` driver's [block-snapshot](https://github.com/QubesOS/qubes-core-admin/blob/master/linux/system-config/block-snapshot) script. But I don't get the sense anyone really wants to touch this code unless it's unavoidable.

> Obviously for us ZFS users it's not at all an option to deprecate the file-based pool. A while ago I offered funding for a ZFS pool driver but I was told that I couldn't direct what the funding would be used for, so I withdrew the offer.

Maybe OpenZFS would accept funding for good old openzfs/zfs#405?

**Comment by andrewdavidwong** [comment]
> A while ago I offered funding for a ZFS pool driver but I was told that I couldn't direct what the funding would be used for, so I withdrew the offer.

I think it depends on how you go about it. As a general policy, [we don't implement specific feature requests based on donations](https://www.qubes-os.org/donate/#do-donors-get-personalized-support-or-special-feature-requests). However, some users have set up independent bounties for specific pieces of work ([example](https://github.com/QubesOS/qubes-issues/issues/4318)). Intuitively, the difference is between (1) trying to "buy" time/work from the Qubes OS Project or trying to use money to influence the project's direction versus (2) paying independent developers (who are not Qubes core devs) to do some work that they then submit to the Qubes OS Project as a pull request consistent with free and open-source software practices. If, independently of the Qubes OS Project, one person pays another to write and contribute good patches (and there's nothing shady going on), then that's not really our business. Of course, this is all ultimately up to @marmarek as project lead.

**Comment by Rudd-O** [comment]
Well, bummer.  I'm **specifically trying to "buy" time/work** from anyone who is willing to contribute to Qubes OS to solve key problems (like this one, or the ZFS one).  Say what you need, I'll pay, we all benefit.  The Qubes OS project may or may not be involved in the transaction.  I'm running out of disk space right now because `fstrim` was never enabled for the file-based storage pools, so this is kind of urgent now.  VMs that have allocated 50 GB of space and seen a lot of writes but really are only using 10 GB, should not actually be using 50 GB of space.

**Comment by tasket** [comment]
Underlying issue here is that Qubes supports a plain POSIX file storage mode that mimics CoW, and this has limitations (like not supporting TRIM/discard). Using this legacy driver to support ZFS may not be the best option since it requires changes both in OpenZFS and Qubes.

The best option going forward would be to write a Qubes pool driver for ZFS that uses ZVOLs, as they are block devices (good match for VMs) and I understand its possible to CoW-clone them in ZFS. IIUC this can be done without modification to OpenZFS codebase.

It may also be feasible to create a non-ZVOL version that snapshots and clones ZFS datasets (one per VM volume) instead. I mention this bc it holds out hope that existing Qubes+ZFS users like Rudd-o could migrate their disk images into the new scheme without having to copy all their data.

Short of that, there are still options for efficient over-provisioning of disk space: Marek's fstrim maintenance script suggestion (which I've done before on Qubes 3), or migrating to LVM thin pools or Btrfs pools.

**Comment by strugee** [comment]
@Rudd-O you can manually reclaim some of your disk space using the procedure in #6041, assuming you're running ext4 inside your individual qubes. tl;dr you will need to:

* Install `zerofree` in the relevant templates
* Use `systemctl emergency` (or `rescue`, can't remember - if you get the wrong one it's fine, but you'll have to kill a bunch of D-Bus processes) in dom0 `xl console $affected_qube` - you need `xl console` because the systend command will stop the gui-agent
* Still in `xl console`, run `umount /dev/xvdb` (or whatever device name the qube's private volume is assigned); you will need to run this repeatedly until you get a "/dev/xvdb: not mounted" error because this volume is bind-mounted all over the place
* Run `zerofree -v /dev/xvdb` (`-v` just prints progress so it's optional)
* Shut down the qube
* Run `fallocate --dig-holes` on all of the qubes' files (`/var/lib/qubes/appvms` IIRC but I'm on mobile so I'm not sure)

This will reclaim all the free space in the qube. Note that `fallocate` doesn't do any advanced parsing, just looks for zeroes, so this _should_ be safe although I have not actually looked at the source code myself to confirm.

**Comment by Rudd-O** [comment]
Thanks.

**Comment by DemiMarie** [comment]
Other than ZFS, are there reasons to use the file-base storage pool anymore?  BTRFS has its own implementation, and ZFS may be getting support for the ioctls used by that pool, which would make ZFS Just Work.  Once that is done, I see no reason to use the file storage pool anymore, as it has other limitations too.  @marmarek is it okay to close this as “won’t fix” and deprecate the file pool in R4.1?

**Comment by DemiMarie** [comment]
Other than ZFS, are there reasons to use the file-base storage pool anymore?  BTRFS has its own implementation, and ZFS may be getting support for the ioctls used by that pool, which would make ZFS Just Work.  Once that is done, I see no reason to use the file storage pool anymore, as it has other limitations too.  @marmarek is it okay to close this as “won’t fix” and deprecate the file pool in R4.1?

**Comment by DemiMarie** [comment]
https://github.com/openzfs/zfs/issues/405#issuecomment-703164586 is my source for the ZFS support.

**Comment by DemiMarie** [comment]
@marmarek Given that the file storage pool is going to be deprecated, can this be closed as “won’t fix”?

**Comment by DemiMarie** [comment]
@tasket It is also worth noting that XFS fully supports reflinks, and I believe that XFS on zvols can be very fast (though don’t quote me on that).

**Comment by Rudd-O** [comment]
Goodbye, bug.  Since using ZFS, this has never been a problem anymore.
