### ISSUE TITLE
VPN service keeps being stopped

### ISSUE THREAD

**Issue by digital-nomad17** [QubesOS/qubes-issues#3276]
#### Qubes OS version:

Qubes 4.0rc2

#### Affected TemplateVMs: 

sys-net(vpn)

---

### Steps to reproduce the behavior:

Installed private internet access openvpn certs using their script(https://helpdesk.privateinternetaccess.com/hc/en-us/articles/219660347-OpenVPN-setup-in-Fedora). Was able to connect to VPN service but the vm crashed. 

Rebooted the machine and retried connecting to VPN with no success. Everytime I try to connect, the service says 'connection lost, vpn service has been stopped'. 

### Expected behavior:

Expecting to be able to connect to VPN service using sys-net vm. 

### Actual behavior:

Unable to connect to VPN.

Getting message 'The VPN  connection to ****** has been disconnected because the VPN service has been stopped'. 

### General notes:

My machine might be compromised. Is there any way to resolve this?

---

**Comment by JPL1** [comment]
I found something similar in RC1.
https://github.com/QubesOS/qubes-issues/issues/2980

**Comment by tasket** [comment]
VPN via Network Manager perhaps should be supported in Qubes in to some degree, however NM is notorious for handling VPN configurations incorrectly which is why you see so many custom scripts/clients from VPN providers just to get openvpn working. Also, NM won't even try to protect against leaks, so using a VPN with it is more of a curiosity.

The best thing is to download your provider configs[1] to a dedicated VPN VM then set it up using the [Qubes VPN doc](https://www.qubes-os.org/doc/vpn/). I provided some detail in issue #2980 but I suggest using `qubes-users` list to hash out specific questions.

[1] PIA configs:
'Recommended' version: https://www.privateinternetaccess.com/openvpn/openvpn.zip
'Strong' version: https://www.privateinternetaccess.com/openvpn/openvpn-strong.zip
