### ISSUE TITLE
Some programs (especially LibreOffice) open as a tiny windows

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#3281]
#### Qubes OS version:

`R3.2`

#### Affected TemplateVMs: 

`fedora-25-minimal`

---

### Steps to reproduce the behavior:

In Nautilus, double-click a LibreOffice Calc file (e.g., `*.ods`).

### Expected behavior:

Good: It opens to a sensible default size.
Best: It remembers the size at which you last closed it, and reopens to that size.

### Actual behavior:

In most cases, it opens as a tiny window (small enough that the content of the file is not even visible).

### General notes:

The behavior is not consistent. For example, I have two AppVMs based on the same template. In one of them, this problem doesn't exist. In the other one, this problem happens with `*.ods` files every time. Even if I create a new AppVM based on the same template and copy the `*.ods` files there (from the problematic AppVM), the problem still occurs.

**Comment by donob4n** [comment]
Here is someone experimenting same problem using wayland and working fine with Xorg: https://ask.libreoffice.org/en/question/143015/opening-window-size-using-wayland-fedora-27/

So probably the problem is something related with Qubes GUI and DUMMY screens. It seems hard to fix without modifying Libreoffice, I will try to investigate.

**Comment by ktmdan** [comment]
This happens all the time for me.  Qubes 4, Fedora-26, 3 monitors.
It always opens in the left corner of the very left monitor.  Not sure where to start debugging why this is happening.  Not sure if its LibreOffice or if its the window manager.

**Comment by shaaati** [comment]
Is there any update on this issue? I am seeing the same behaviour as described before, my setup is Qubes 4 with Fedora-30 AppVMs and two external monitors attached to my Laptop (three monitors in total). I think this also happens when only using the internal monitor of the Laptop.
We use multiple different Qubes installations at work and as far as I know, everyone experiences the same issue.
@andrewdavidwong maybe the milestone for this issue should be updated, as it also seems to affect Qubes 4 installations?

**Comment by andrewdavidwong** [comment]
> Is there any update on this issue? I am seeing the same behaviour as described before, my setup is Qubes 4 with Fedora-30 AppVMs and two external monitors attached to my Laptop (three monitors in total). I think this also happens when only using the internal monitor of the Laptop.
> We use multiple different Qubes installations at work and as far as I know, everyone experiences the same issue.

No update as far as I know. I'm still experiencing the problem too.

> @andrewdavidwong maybe the milestone for this issue should be updated, as it also seems to affect Qubes 4 installations?

Good idea, thanks.

**Comment by initCCG** [comment]
This is definitely still there in Qubes 4 and in more than just LibreOffice.
The latest guesses are that it's something in XFCE settings.

**Comment by pabpas** [comment]
There is a related issue open at fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1752089

A workaround that works for me is to lauch libreoffice base and set the desired window size. This size will be inherited by libreoffce Calc/Writer and so on.

**Comment by yankyhoffman** [comment]
I am also experiencing such issues with LibreOffice windows.

I am on Gnome (currently Ubuntu 19.10, experiencing the issue since 18.04 (didn't use anything prior)).

![Screenshot from 2019-12-02 13-19-03](https://user-images.githubusercontent.com/41123800/70271604-b8112d00-1774-11ea-9026-eef307de3029.png)

See the arrow showing the app window

**Comment by peterfreeth** [comment]
Same for me, only with Libreoffice. It started in Ubuntu 18 as I recall, still the same in 19.10.

**Comment by darkduelist2** [comment]
Same problem here in Ubuntu 19.10 described by yankyhoffman and peterfreeth.

**Comment by qtpies** [comment]
Same here with Qubes 4, Fedora 31 qube. It does not occur in an unmodified (apart from installing Libreoffice) Debian 10 Qube. Difference is that it uses x11 instead of gtk3.

Fedora Qube Libreoffice about page:
Version: 6.3.6.2
Build ID: 6.3.6.2-2.fc31
CPU threads: 8; OS: Linux 4.19; UI render: default; VCL: gtk3; 
Locale: en-US (C.UTF-8); UI-Language: en-US
Calc: threaded

Debian Qube Libreoffice about page:
Version: 6.1.5.2
Build ID: 1:6.1.5-3+deb10u6
CPU threads: 2; OS: Linux 4.19; UI render: default; VCL: x11; 
Locale: en-US (en_US.UTF-8); 
Calc: group threaded

**Comment by qtpies** [comment]
A fix was brought by Steve Coleman [on the Qubes mailinglist](https://groups.google.com/d/msg/qubes-users/GA21ZTGWWBA/2ATd3VhmAgAJ).

Summarized: In the VM where you want to open Libreoffice, in the file `~/.config/libreoffice/4/user/registrymodifications.xcu`, find the lines containing `ooSetupFactoryWindowAttributes `, and edit the third and fourth values to your desired width and hight, for instance 1800 and 900. Do this once for every template and LibreOffice will always open at this size.

I think it's unlikely that there is going to be a better fix than this so I propose to close this issue.

**Comment by andrewdavidwong** [comment]
> A fix was brought by Steve Coleman on the Qubes mailinglist.

Thanks for sharing this here!

> I think it's unlikely that there is going to be a better fix than this so I propose to close this issue.

IMHO, it would be a mistake to close this issue without doing anything. At the very least, we should document the workaround you've just shared. Hopefully we could do more than that.

**Comment by SoyBison** [comment]
I'm having this same issue on Ubuntu 20.04, so it persists.

**Comment by gulliverfoyle** [comment]
Ubuntu 20.04, libre office, had this issue.  Ran clam tk and deleted everything found.   No more problems!

**Comment by kevin-alfred** [comment]
I have just installed a fresh 20.04 Ubuntu and this same issue is happening.

**Comment by Tasty213** [comment]
Issue is still happening from libre office about:
Version: 6.4.6.2
Build ID: 1:6.4.6-0ubuntu0.20.04.1
CPU threads: 4; OS: Linux 5.4; UI render: default; VCL: gtk3; 
Locale: en-GB (en_GB.UTF-8); UI-Language: en-GB
Calc: threaded

**Comment by unman** [comment]
On Sat, Nov 07, 2020 at 04:33:52AM -0800, Tasty213 wrote:
> Issue is still happening from libre office about:
> Version: 6.4.6.2
> Build ID: 1:6.4.6-0ubuntu0.20.04.1
> CPU threads: 4; OS: Linux 5.4; UI render: default; VCL: gtk3; 
> Locale: en-GB (en_GB.UTF-8); UI-Language: en-GB
> Calc: threaded

This is *not* specific to libre office, although you may see it there.
I regularly have xterm windows opening as tiny window in top LH corner of
screen, particularly with dual monitors.
As I have kboard shortcuts to maximise/move, no biggy.

**Comment by andrewdavidwong** [comment]
> This is *not* specific to libre office, although you may see it there.
I regularly have xterm windows opening as tiny window in top LH corner of
screen, particularly with dual monitors.

I've personally never witnessed this with xterm (or any other program besides LibreOffice), but I've generalized the issue title a bit just in case.

**Comment by iamahuman** [comment]
qubes-gui-agent seems to be the culprit. *At some point*, it resizes the program's window to 0x0, which is remembered until next launch.

**Comment by unman** [comment]
On Sun, Nov 28, 2021 at 04:33:37PM -0800, Jinoh Kang wrote:
> qubes-gui-agent seems to be the culprit. *At some point*, it resizes the program's window to 0x0, which is remembered until next launch.
> 

I'm not convinced you are right, since there is an open issue at
Fedora, and the same behaviour has been reported on Ubuntu. That makes
it an upstream bug.
I think it's an open/libre office bug, and the configuration suggested
by slcoleman seems to fix it. It's certainly not Qubes specific.

**Comment by DemiMarie** [comment]
@andrewdavidwong Time to close this as “not our bug”?  In any case it might be fixed when Qubes OS switches to Wayland.

**Comment by andrewdavidwong** [comment]
Closing as "not our bug" (the Qubes OS Project does not develop the software that is causing this bug). If anyone believes this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

Related FAQ: [Why don’t you fix upstream bugs that affect Qubes OS?](https://www.qubes-os.org/faq/#why-dont-you-fix-upstream-bugs-that-affect-qubes-os)

**Comment by baskinsy** [comment]
I have the same issue on Opensuse Tumbleweed. I used KDE Special application settings, Ignore requested geometry set to YES to resolve it until there is an upstream fix. Hope it helps until there is a proper solution.

**Comment by unman** [comment]
Thanks baskinsy.
I said MUCH earlier in the thread that this behaviour can be seen in other
distros, and this is not a Qubes bug.

**Comment by bsa7** [comment]
> ooSetupFactoryWindowAttributes

Deleting all entries with that tag also helpful for Ubuntu 23.04 LibreOffice 7.5.3.2
