### ISSUE TITLE
Lost system tools menu from the qubes icon menu and the right click menu.

### ISSUE THREAD

**Issue by mannp** [QubesOS/qubes-issues#3294]
#### Qubes OS version:

v4.0rc2 updated to current.

#### Affected TemplateVMs: 

dom0 fc25

---

### Expected behavior:

No menu is present and I am not sure how to get it back.

There is just a spacer with no menu.

### General notes:

---

**Comment by tasket** [comment]
I ran into the same issue:
https://groups.google.com/d/msgid/qubes-users/551eba63-92d1-0026-396d-884b8ecc7caa%40posteo.net

**Comment by na--** [comment]
I also ran into this last week and forgot to report it... In my case I think that it was also reinstalling a template that caused it.

**Comment by mannp** [comment]
Thanks for the latest update today which added back the 'System Tools' and 'Create Qubes VM' menu items, but it didn't add back any items under the System Tools icon.

There are no system tools listed.

**Comment by tasket** [comment]
Same here... Menu was added back with only the Create app.

**Comment by mannp** [comment]
@tasket the workaround was solved for me in this thread by jpouellet;

https://github.com/QubesOS/qubes-issues/issues/2952#issuecomment-350898716

**Comment by jpouellet** [comment]
Yep, it just happened to me again. Something is definitely deleting most of the.desktop files under /usr/share/applications. Looking into what...

**Comment by jpouellet** [comment]
@marmarek: I found the root cause: https://github.com/QubesOS/qubes-linux-template-builder/blob/fcc771715a16419a8cb49eb1ef00eee21efed25f/templates.spec#L56-L63

I don't have time to figure out the correct fix right now though.

**Comment by SeVaS2016** [comment]
I have something to add to this. 
Date of Bug: March 7th, 2018
OS: Qubes 4.0 rc4 + 1 qvm-dom0-update (fully updated as of 3/7/18

When performing a debian-9 template reinstall as described in the qubes docs, I ran into a... well....
The same errors mentioned above but also the kernel did a houdini. 

dom0$ sudo qubes-dom0-update --action=reinstall qubes-template-debian-9
Andrew David Wong said something about the following command and I tried it yielding the following result.
dom0$ for VM in `qvm-ls --raw-list`; do qvm-prefs -s $VM kernel 4.14.13-3; done
# kernel not installed (not actual output)

More specifically:
dom0$ for VM in `qvm-ls --raw-list`; do qvm-prefs -s $VM kernel default; done
## qubesadmin.exc.QubesPropertyValueError: Kernel 'default' not installed

I reinstalled the kernel but 

dom0$ qubes-dom0-update kernel
## Complete!
dom0$ restart
dom0$ for VM in `qvm-ls --raw-list`; do qvm-prefs -s $VM kernel 4.14.13-3; done
## qvm-prefs: error: no such property: 'kernel'

I did not solve this. I reinstalled. But heres other outputs for your viewing pleasure. 

dom0$ qubes-dom0-update kernel-qubes-vm
## Complete!
dom0$ restart
dom0$ qubes-dom0-update --clean #Clean yum repos...
dom0$ qubes-dom0-update qubes-core-dom0*
## find: '/var/lib/qubes/dom0-updates/var/cache/yum': No such file/directory
## Installing *linux-debug *vaio-fixes(1/2)
dom0$ qubes-dom0-update --gui
## xterm: cannot load font '-misc-fixed-medium-r-semicondensed--##-##------
dom0$ qubes-dom0-update --action=downgrade
## yum version in sys-firewall does not support --downloadonly option
## Error: downgrade not supported
dom0$ qubes-dom0-update --action=install
## find: '/var/lib/qubes/dom0-updates/var/cache/yum': No such file/directory
dom0$ qubes-dom0-update --action=upgrade
## No upgrade available

**Comment by tasket** [comment]
The `xdg-desktop-menu uninstall` command that @jpouellet pointed out is indeed triggering the menu erasure. I temporarily replaced the executable in /usr/bin with a script that only exits and the erasure didn't reoccur when reinstalling templates.

Looking at the scriptlet contents of a debian-8 rpm package, I copied the expanded `xdg-desktop-menu` commands into a CLI (first using `sudo` then `su -`). But I was unable to reproduce the menu erasure with this manual method. So there is something about the execution environment of the rpm scriptlets that is causing (or triggering a bug in) `xdg-desktop-menu`.

My suspicion at this point is that some difference in environment variables, PATH, globbing, etc. could be contributing to the problem especially since `xdg-desktop-menu` is itself an sh script.

---

To fix or workaround this, we could just comment-out that part of the rpm scriptlet in builder. Otherwise, find an upstream fix, or even have `qubes-dom0-update` disable the `xdg-desktop-menu` temporarily before running `dnf reinstall`.

**Comment by marmarek** [comment]
Upstream bug report: https://bugs.freedesktop.org/show_bug.cgi?id=105635

In the meantime, I'll apply some workaround.
