### ISSUE TITLE
add qubes-app-linux-yubikey to Qubes repository (Module for Qubes OS to integrate Yubikey authentication through a USB VM)

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3305]
https://www.qubes-os.org/doc/yubi-key/

https://github.com/adubois/qubes-app-linux-yubikey

Could you please build it and upload to Qubes repository?

//cc @adubois

**Comment by adubois** [comment]
Hi Andrew, I will look into this in the coming days/weeks. I however only have a 4.0rc4 system at hand. There are few things I need to fix anyway on my side. PLease help me on how to proceed to have it possibly included in 4.0 (if Joanna/Marek are OK with this obviously).

**Comment by andrewdavidwong** [comment]
Thanks! Our package contribution procedure is explained here:

https://www.qubes-os.org/doc/package-contributions/

Please let us know if you have any questions.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
