### ISSUE TITLE
Ubuntu templates fail to build

### ISSUE THREAD

**Issue by noptys** [QubesOS/qubes-issues#3308]
#### Qubes OS version:
R4.0

#### Affected TemplateVMs: 
trusty, xenial
---
### Steps to reproduce the behavior:
- follow https://github.com/QubesOS/qubes-template-configs and select trusty or xenial templates

### Expected behavior:
- template RPMs are created in build qube ready to be installed in dom0

### Actual behavior:
- build fails on dh_install errors

### General notes:
- problem occurs because of change in dh_install behavior.

**Comment by noptys** [comment]
Fix for build issues are in pull requests https://github.com/QubesOS/qubes-core-agent-linux/pull/71 and https://github.com/QubesOS/qubes-gui-agent-linux/pull/24.  Both templates have other problems which I am troubleshooting, but should build now.

**Comment by noptys** [comment]
The build finishes and creates an installable RPM, but the finished template is not usable:

- (1) qubes-vm-recommended fails to install because of a dependency error
  - this means access via the console and qvm-run is broken
- (2) make template fails to build after the first attempt
  - this is due to a trusty-specific fix for systemd and may not be worth fixing

I think I have (1) fixed; A fix for (2) is in progress.

**Comment by 0spinboson** [comment]
When I try to build qubes-vm for xenial, I run into a script complaining that it can't locate digest::md5.

**Comment by unman** [comment]
@0spinboson Can you give some more detail?
What build environment are you using?
Have you run `make install-deps` ?
At what stage does this error appear?

**Comment by nextgenthemes** [comment]
How am I even supposed to build a ubuntu template. The builder docs redirect me to the guide to build arch. I followed that as far as I could, there is no ubuntu to select in the setup script. I saw in the screenshot that there are ubuntu release names like trusty further down at a step I cant even get it. Also there is no config file to edit for version 4.

**Comment by unman** [comment]
I dont understand - If you run the setup script, select "Debian" and click through to get to the list of templates to build. Did you even try this? The config file is generated AFTER you've completed the setup script.

That said, it probably isnt worth your while at the moment because the Ubuntu builds are almost certainly broken in rc5 - as things change there's a lag before the builds are fixed.
I'd suggest you drop down to 3.2 but the builds are currently broken there too.
Sucks indeed.

**Comment by nextgenthemes** [comment]
I actually somehow by trail and error ended up at least trying to build it - it failed. I messed up the order of things or something, I remember selecting debian first because it made most sense to me but having no options later. I also did the config edit before the ./setup and I think thats the way the arch template build docs say I am supposed to do it. I also encountered some small bugs and the unpolishedness of qubes is making it really hard to decide if I want to move my life to this and invest so much time. I consider just installing kubuntu 18.04 beta1 and get on with my life in a insecure way ;( But its also needs users who actually report bugs. 

Recently read a article heading about it wanting to get as polished as Ubuntu. Well its years away from this sadly. But given its been around so many years I think at least a script to build Ubuntu should be at the top of the priority list if it can't be included because of licensing then the users should at least be able to build it on the click of a button instead of going down a long tutorial that involves manually editing files ... that not even works. And there actually is not even anything in the docs on Ubuntu template build. It just says "should be straight forward". When I could have 16.04 and soon 18.04 running at the same time would be a huge deal for me then I could use qubes instead of virtualbox. My guess is that I probably cant run virtualbox from inside a Qube and if I would not really want to.

**Comment by unman** [comment]
Ah, OK since Marek included a 4.0 conf file , which sets TEMPLATE_ROOT_WITH_PARTITIONS the template build pulls in linux-image-amd64 - this isnt available from Ubuntu. The equivalent package is linux-image-generic.
I've put in PR to fix this for Ubuntu builds.

There's a separate issue in that the new template doesn't seem to populate menu with applications. If I can confirm this I'll have this issue closed and raise that as a separate issue.
