### ISSUE TITLE
Installer option created unbootable installation

### ISSUE THREAD

**Issue by zander** [QubesOS/qubes-issues#3334]
#### Qubes OS version:
Failed on both 3.2 and 4.0R2

### Steps to reproduce the behavior:

In the installer part where you select which disks you want to install to,
change from lvm to  the BtrFs option in the combobox. 

Continue creating your partitions as normal.

### Expected behavior:

A bootable OS.

### Actual behavior:

A underline-cursor on a black screen immediately after bios screen. We never see the boot-loader.

It looks like this is an unfinished feature that nobody supports / owns. Much like #3327, maybe this option should just be removed?

**Comment by marmarek** [comment]
According to https://github.com/QubesOS/qubes-issues/issues/2294#issuecomment-370989962 it is fixed in 4.0-rc4+. For 3.2 it is still an issue and should be addressed in 3.2.1.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
