### ISSUE TITLE
R3.2 clean install and update disables usb keyboard at disk encryption passphrase

### ISSUE THREAD

**Issue by Halumiumi** [QubesOS/qubes-issues#3336]
#### Qubes OS version: 

R3.2 

#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

- clean install of R3.2 on usb ssd drive with diskencryption turned on (setup disables usb-vm)
- multiple startes work fine and the usb keyboad is active at disk encryption passpharse prompt
- excute "update vm system" and restart --> usb keyboard isn't working only ps2 keyboard possible 

### Expected behavior:

usb keyboard should be working for disk encrytion passpharse input

### Actual behavior:

usb keyboard is not working at disk encryption passphrase input

### General notes:

- this happens after a clean install and the update of all packages

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
