### ISSUE TITLE
qvm-convert-img: ValueError: No icon received

### ISSUE THREAD

**Issue by h01ger** [QubesOS/qubes-issues#3344]
#### Qubes OS version:

3.2

#### Affected TemplateVMs: 

debian-8 (according to Unman, haven't tried myself)
debian-9 (according to Unman and myself)
fedora (according to Unman, haven't tried myself)

### Steps to reproduce the behavior:

$ qvm-convert-img image.jpg image_clean.jpg
Traceback (most recent call last):
  File "/usr/lib/qubes/qimg-convert-client", line 47, in <module>
    main()
  File "/usr/lib/qubes/qimg-convert-client", line 41, in main
    img = qubes.imgconverter.Image.get_through_dvm(args.src)
  File "/usr/lib/python2.7/dist-packages/qubes/imgconverter.py", line 207, in get_through_dvm
    return cls.get_from_stream(sys.stdin, **kwargs)
  File "/usr/lib/python2.7/dist-packages/qubes/imgconverter.py", line 131, in get_from_stream
    raise ValueError('No icon received')
ValueError: No icon received

**Comment by h01ger** [comment]
On Tue, Nov 28, 2017 at 10:52:43AM +0000, Holger Levsen wrote:
> #### Qubes OS version:
> 
> 3.2
> 
> #### Affected TemplateVMs: 
> 
> debian-8 (according to Unman, haven't tried myself)
> debian-9 (according to Unman and myself)
> fedora (according to Unman, haven't tried myself)
> 
> ### Steps to reproduce the behavior:
> 
> $ qvm-convert-img image.jpg image_clean.jpg
> Traceback (most recent call last):
>   File "/usr/lib/qubes/qimg-convert-client", line 47, in <module>
>     main()
>   File "/usr/lib/qubes/qimg-convert-client", line 41, in main
>     img = qubes.imgconverter.Image.get_through_dvm(args.src)
>   File "/usr/lib/python2.7/dist-packages/qubes/imgconverter.py", line 207, in get_through_dvm
>     return cls.get_from_stream(sys.stdin, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/qubes/imgconverter.py", line 131, in get_from_stream
>     raise ValueError('No icon received')
> ValueError: No icon received

gentle ping on this, which I believe is broken core functionality in the
stable release…


-- 
cheers,
	Holger

**Comment by unman** [comment]
I believe this is broken because Stretch has v6.9 and versions of ImageMagick later than 6.8.9 have an "identify" which has problems with the file input. I suspect this is related to a changelog entry relating to reading from stdin no longer working. 
In old versions `identify -:filename` worked.
In later versions it doesn't, and identify tries to find a file **named** `-:filename`

That is set in qubes.getImageRGBA here:
```
elif [ "${filename}" = "-" ] || [ "${filename##*:}" = "-" ]; then
    tmpfile="$(mktemp /tmp/qimg-XXXXXXXX)"
    cat > "${tmpfile}"
    if [ "${filename##*:}" = "-" ]; then
        filename="${filename%:*}:${tmpfile}"
    else
        filename="${tmpfile}"
    fi
```

Simply using `filename="${tmpfile}"` restores functionality here, but possibly(probably?) breaks something else

It's not clear to me what that section is doing, or where else it might be used, so I'm reluctant to change it.
@marmarek ??

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by ben-grande** [comment]
Please reopen. Qubes R4.2

```sh
user@disp7111:~$ qvm-convert-img image.svg image.svg.safe
gm identify: No decode delegate for this image format (/tmp/qimg-7C8BP9Rv).
gm identify: Request did not return an image.
```
```python3
Traceback (most recent call last):
  File "/usr/lib/qubes/qimg-convert-client", line 50, in <module>
    main()
  File "/usr/lib/qubes/qimg-convert-client", line 44, in main
    img = qubesimgconverter.Image.get_through_dvm(args.src)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/qubesimgconverter/__init__.py", line 320, in get_through_dvm
    return cls.get_from_stream(sys.stdin.buffer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/qubesimgconverter/__init__.py", line 197, in get_from_stream
    raise ValueError('No icon received')
ValueError: No icon received
```

**Comment by marmarek** [comment]
It doesn't look like the same issue, please open a new one.

**Comment by ben-grande** [comment]
https://github.com/QubesOS/qubes-issues/issues/9145
