### ISSUE TITLE
qubes.xml corrupted due to disk full

### ISSUE THREAD

**Issue by zander** [QubesOS/qubes-issues#3376]
#### Qubes OS version:
4.0RC2

### Steps to reproduce the behavior:

I personally did not see this behavior, it was reported on the user mailinglist. As I realize database corruption like this is a show-stopper bug, I'm reporting it here.

https://groups.google.com/d/msg/qubes-users/svrJiQ1d7S8/zHLoTWiQBQAJ

### Expected behavior:

The xml file should never be left in a corrupted state.

**Comment by blacklight447** [comment]
Ive had this too once (in qubes 3.2 admittely), but its a fairly easy fix, you just have to delete the qubes.xml and let it regenerate itself automatically. maybe we can make a script which does this by itself (removing and regenerating) once it detects a full disk?

**Comment by zander** [comment]
My thinking was more in the direction that the component that generates the XML uses an atomic operation to replace the old one.
On Unix this means the xml is fully generated under a slightly different name and then (the atopic operation) renamed over the old file.

This way there is no risk of corruption.

**Comment by tasket** [comment]
The file-saving code appears to be in qubes/app.py and it does already use the save/flush/rename method. This would mean the culprit for the error probably lies in the filesystem or thin-lvm or layers beneath.

**Comment by dimlev** [comment]
I tested changing some settings using the qubes-manager (on 3.2 using qubes-manager) while my disk was full and I did not manage to corrupt qubes.xml. I did manage to corrupt firewall.xml though. 

qubes/app.py uses the save/flush/rename method but [qubes/firewall.py](https://github.com/QubesOS/qubes-core-admin/blob/master/qubes/firewall.py#L570) does not. So if you happen to change a firewall setting while the disk is full you end up with a zero byte / corrupted firewall.xml file. 

Should I open a new issue for this?

**Comment by dimlev** [comment]
I also tested changing vm settings on 4.0RC3 (running on virtualbox) while the disk was full. Same results with 3.2

- qubes.xml was fine.
- firewall.xml became corrupted.

Also: Patrick (in the google groups) does not mention changing any settings that would trigger saving the qubes.xml file. So if he didn't, then what are some other ways that this could happen?

**Comment by iamahuman** [comment]
`qubes.xml` should ideally be replaced atomically.

1. Create `qubes.xml-` or an O_TMPFILE.
2. Serialize into the file.
3. Hard link/rename the new file into `qubes.xml`.

Alternatively symlinking is also an option.

**Comment by rustybird** [comment]
> `qubes.xml` should ideally be replaced atomically.
> 
>  1. Create `qubes.xml-` or an O_TMPFILE.
>  2. Serialize into the file.
>  3. Flush and perform an `fsync()`. [...]
> 4. Hard link/rename the new file into `qubes.xml`.

5. `fsync()`  the directory containing `qubes.xml`, for durability.

[`qubes.app.save()`](https://github.com/QubesOS/qubes-core-admin/blob/v4.1.18/qubes/app.py#L1088-L1129) is missing both `fsync()` calls. I'll submit a PR to move a slightly modified [`qubes.storage.reflink._replace_file()`](https://github.com/QubesOS/qubes-core-admin/blob/v4.1.18/qubes/storage/reflink.py#L357-L375) decorator to [`qubes.utils`](https://github.com/QubesOS/qubes-core-admin/blob/master/qubes/utils.py), and then call that from the qubes.xml and firewall.xml save routines.

Btw it's not yet possible to use `O_TMPFILE` for atomic file replacement, because the kernel flag to overwrite a `linkat()` target still hasn't landed after ([checks Patchwork again](https://patchwork.kernel.org/project/linux-fsdevel/list/?series=&submitter=&state=*&q=linkat&archive=both&delegate=)) over 4 years, aaarghh

**Comment by iamahuman** [comment]
Should this issue's milestone be updated to Release 4.1? After all, I'm not sure if this should be called a bug or an enhancement.

**Comment by DemiMarie** [comment]
> Should this issue's milestone be updated to Release 4.1? After all, I'm not sure if this should be called a bug or an enhancement.

Anything that can corrupt `qubes.xml` is definitely a bug (and a bad one at that).  Release 4.0 is correct.  @marmarek should I go ahead and backport this?

**Comment by rustybird** [comment]
Another one for the "backport needed" label. Sorry for the hassle
