### ISSUE TITLE
BCM43224 in v4.rc3 - Works on Fedora but not qubes

### ISSUE THREAD

**Issue by mannp** [QubesOS/qubes-issues#3377]
#### Qubes OS version:

R4rc3

#### Affected TemplateVMs: 

fedora-25
---

### Steps to reproduce the behavior:

Add device to a qube and the system locks up.

I wondered if the firmware package was loaded in dom0 for the latest kernel at all?

### Expected behavior:

The qube would boot so modules can be added as required.

The devices works out of the box on fedora 26 and I have tried a fedora-26 template for the wifi device and the lockup is the same.

**Fedora has brcmsmac, b43, mac80211 loaded with kernel driver bcma-pci-bridge in use with kernel module bcma loaded.**

I cannot afford to replace the laptop and would welcome using qubes on my laptop as well as my desktop.

### Actual behavior:

qubes boots and locks up early in the boot process.

### General notes:

I have added the device as passive, as the wiki suggested without success.

I have also searched the google groups with no luck.

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by mannp** [comment]
Having re-read the guidelines there is nothing there about being localised or hardware specific.

As I said in the report its has **already** been reported to qubes-issues as well as needing specific answer to modules loaded in dom0 and the firmware too.

I felt that could only be answered by devs and not users; hence why posting as an issue.

**Comment by andrewdavidwong** [comment]
@mannp:
> As I said in the report its has *already* been reported to qubes-issues [...]

I do not see this mentioned anywhere in your report. What is the other qubes-issue number, so that we can link these related issues?

> [...] as well as needing specific answer to modules loaded in dom0 and the firmware too.
> 
>  I felt that could only be answered by devs and not users; hence why posting as an issue here.

I'm afraid that still falls outside the intended scope of qubes-issues. The main purpose of qubes-issues is not for developers to answer user questions, but rather for reporting issues (bugs, enhancements, and tasks). The more appropriate venue to address questions to developers is [qubes-devel](https://www.qubes-os.org/mailing-lists/#qubes-devel).

**Comment by mannp** [comment]
qubes-issues should be qubes-user in that quoted part; my error.

> qubes-devel - This list is primarily intended for people who are interested in contributing to Qubes or who are willing to learn more about its architecture and implementation.

So odd that thats more applicable, but hey who am I to challenge the norm.

Decided to use Arch Linux on the laptop and main machine and park qubes until 4 is out and I have more 'compatable' hardware; if ever.
