### ISSUE TITLE
qubes-os.org HSTS max-age has legacy value

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#3378]
Google recently [increased](https://github.com/chromium/hstspreload/commit/3bc993aebe5da3a3c7555e9bd70099a722fbb59e) the minimum required `max-age` value for new entries to the HSTS preload list from 10886400 to 31536000 seconds. They've grandfathered in old entries (including qubes-os.org with 15552000 seconds), but [claim](https://hstspreload.org/?domain=qubes-os.org) those "may be at risk of removal". Which sounds silly, but who knows.

**Comment by andrewdavidwong** [comment]
> It appears we are using a Cloudflare certificate for qubes-os.org.

Not anymore.

And since we're not using Cloudflare anymore, I don't believe we have any control over the HSTS `max-age` value. (In fact, moving off of Cloudflare may have resolved this issue as a byproduct.) Closing as "won't do" [since "can't" implies "won't" ;)].

**Comment by esote** [comment]
@andrewdavidwong Ah, I was checking qubes-os.org ([which uses a cloudinary cert](https://www.ssllabs.com/ssltest/analyze.html?d=qubes%2dos.org&s=104.24.111.67)), but redirects to www.qubes-os.org which [uses a Let's Encrypt cert](https://www.ssllabs.com/ssltest/analyze.html?d=www.qubes%2dos.org&s=185.199.109.153&latest) & has the right HSTS duration.

So we don't even need "won't do", because it's already done :+1:
