### ISSUE TITLE
VM/Logs links in VM Manager point to wrong VM

### ISSUE THREAD

**Issue by svenssonaxel** [QubesOS/qubes-issues#3379]
#### Qubes OS version: R3.2

---

### Steps to reproduce the behavior:

1. In Qubes VM Manager, right-click on vm1.
2. In the context menu, click on "Logs".
3. Note that the Logs menu have links that pertain to vm1.
4. Left-click on vm2.
5. Open the VM menu (Alt+M)
6. Open the Logs submenu

### Expected behavior:

7. The Logs submenu have links that pertain to vm2.

### Actual behavior:

7. The Logs submenu have links that pertain to vm1.
8. Right-click on vm2 to bring up the context menu.
9. Left-click on vm2 to close the context menu.
10. Repeat steps 5-6.
11. The Logs submenu now have links that pertain to vm2 as expected.

### General notes:

Supposedly, the links in the VM/Logs submenu are updated on context-menu open for a VM, when they should be updated on selecting a VM.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
