### ISSUE TITLE
dispVM/appVM silent name clash

### ISSUE THREAD

**Issue by svenssonaxel** [QubesOS/qubes-issues#3383]
#### Qubes OS version: R3.2

---

### Steps to reproduce the behavior:

1. Create a new appVM and name it "disp1"
2. Create a new dispVM that would have been named "disp1".

### Expected behavior:

3. A new dispVM is created, OR there is a message explaining that it is not.

### Actual behavior:

3. User command silently ignored
4. Try open a new dispVM again
5. A new dispVM is created named "disp2".

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
