### ISSUE TITLE
(design improvement) Split domain name space

### ISSUE THREAD

**Issue by svenssonaxel** [QubesOS/qubes-issues#3385]
#### Qubes OS version: R3.2

---
### General notes:

There are several problems with the current design of VM names. These include:
* Possible confusion between VM names and keywords, e.g. #2857. This problem can reappear if there is need to introduce new keywords.
* Name clashes between appVMs and dispVMs, see #3383.
* Name clashes between appVMs and internal VMs such as "fedora-XX-dvm".
* Direct mapping to xen domain names exposes the system to possibl xen-specific naming issues (I've had an issue with this, will update if I can reproduce it).

Perhaps consider introducing a way to divide the namespace in non-overlapping classes, for example
* `sys-` prefix for service VMs
* `_` prefix for appVMs, maybe for templates too
* `disp` prefix for dispVMs
* new keywords can be created at will that do not interfere with any prefix
However an actual change would have to be worked out a lot more carefully than this example.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
