### ISSUE TITLE
install of 4.0 rc3 hangs on XPS 15 (9560)

### ISSUE THREAD

**Issue by mememan** [QubesOS/qubes-issues#3389]
#### Qubes OS version:

Dell XPS 15 1TB 32GB HiRes Touchscreen

Installer hangs often prior to getting to the GUI installer with a soft lock on CPU 7 When it does proceed further I am able to get to the point of the installation however it gets to action (797/1018) qubes-mgmt-salt-base-topd.noarch and then hangs with system freeze

#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

install from USB

### Expected behavior:

install works!

### General notes:

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
