### ISSUE TITLE
Main partition is MBR LVM, but Qube OS install ask me to create an EFI boot partition

### ISSUE THREAD

**Issue by davejones2** [QubesOS/qubes-issues#3392]
#### Qubes OS version:

Qubes 3.2

#### Affected TemplateVMs: 

---

### General notes:

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
