### ISSUE TITLE
qubes-builder offline iso

### ISSUE THREAD

**Issue by TomzOk** [QubesOS/qubes-issues#3401]
#### Qubes OS version:
R3.2

#### Affected TemplateVMs: 
archlinux fedora-25

### Steps to reproduce the behavior:
Following the steps documented:
https://www.qubes-os.org/doc/qubes-r3-building/
https://www.qubes-os.org/doc/building-non-fedora-template/

1. Install qubes-builder
2. run ./setup.sh
3. Select build all qubes (Not template only)
4. From dialog select builder-fedora, builder-archlinux mgmt-salt
5. From templates select fedora-23 fedora-25 archlinux
6. make get-sources qubes iso

### Expected behavior:
New ISO with fedora-25 and archlinux template-vm's available

### Actual behavior:
New ISO only fedora-23 template available

### General notes:
I know I can install the templates after first installing a base install of qubes - but I would like the additional templates available from the ISO for offline computers.  Did I miss a step or is this not expected behavior.

**Comment by marmarek** [comment]
The above settings only build the template(s). To have them included on
installation iso, you need to add appropriate configuration to installer
itself. See qubes-src/installer-qubes-os/comps-qubes.xml and search for
other templates already included there. Probably the easiest way is to
add it to some existing group.


-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
