### ISSUE TITLE
Qubes builder: Can't locate Digest/MD5.pm ion @INC

### ISSUE THREAD

**Issue by digitalnomad17** [QubesOS/qubes-issues#3420]
#### Qubes OS version:

QubesOS R3.2

---

### Steps to reproduce the behavior:

cloned commit '0d1319984bbb05db4402961ad9c71bbbde3480e2' and installed the dependencies. Copied templates.conf to builder.conf and ran the setup. 

### General notes:

I am only trying to build the xenial template(ubuntu 16.0) and it's running into this dependency error. 

```
Can't locate Digest/MD5.pm in @INC (you may need to install the Digest::MD5 module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /usr/share/perl5/vendor_perl/Digest.pm line 44.
make[2]: *** [/home/user/scratch/qubes-builder/qubes-src/builder-debian/Makefile.qubuntu:169: dist-build-dep] Error 2
make[1]: *** [Makefile.generic:156: packages] Error 1
make: *** [Makefile:212: core-vchan-xen-vm] Error 1

```

---

**Comment by marmarek** [comment]
Looks like dpkg-dev package in Fedora have missing dependencies:
perl-Digest-MD5 and perl-Digest-SHA. Install them manually (dnf install
perl-Digest-MD5 perl-Digest-SHA).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
