### ISSUE TITLE
Completely buggy OS [BUGS]

### ISSUE THREAD

**Issue by matmat94** [QubesOS/qubes-issues#3436]
Latest stable release downloaded on 31/12/12

I installed OS with default options.
Then I change 'personal' VM to Debian 8.
In 'personal' VM I run apt-get update then apt-get upgrade in order to make Google Chrome work.
I shutdown the VM then restart it.
Everything disappeared. Even worse, after an apt-get update the google-chrome-stable package can't be found but it was found in the first place as if in between something changed the apt repositories list.
It's very frustrating as I don't understand one bit of why all of this happened.
When VM are shut down, are they reset ? Why in the world would someone want that behavior ? 
Plus I guess there are disposable VMs for a reason.
Also, a connection to the Tor network could not be made despite multiple retries despite the fact that Internet was working perfectly.
I was very excited to use this OS but now I just want to throw it away.

Please tell me I made a mistake somewhere while installing the OS or did something bad somewhere. I would love to use this OS which seemed perfect in the first place for people who care about security/privacy.

Thanks in advance and sorry for the angryness...

**Comment by matthazinski** [comment]
>  In 'personal' VM I run apt-get update then apt-get upgrade in order to make Google Chrome work.
I shutdown the VM then restart it.
Everything disappeared.  It's very frustrating as I don't understand one bit of why all of this happened.
When VM are shut down, are they reset ? Why in the world would someone want that behavior ?

> Plus I guess there are disposable VMs for a reason.

This is intentional. Each qube's root filesystem is a read-only mount of the corresponding TemplateVM, but (except for disposable VMs) the home directory is preserved between reboots. Installing software outside of your home directory must be done in the TemplateVM. The [getting started guide](https://www.qubes-os.org/getting-started/) has more details.

>  Also, a connection to the Tor network could not be made despite multiple retries despite the fact that Internet was working perfectly.

More information is needed to debug this. You may have more success if you open a new issue adhering to the issue template and share details of your network topology and any relevant logs.

**Comment by matmat94** [comment]
Oh alright it makes a lot more sense now; I should have read the guide first.
I'll make another issue adhering to the template about the Tor problem.
Thank you for your reply.
