### ISSUE TITLE
git-remote-gcrypt not working with qubes-gpg-client-wrapper (-q and --gen-rand not supported)

### ISSUE THREAD

**Issue by whohoho** [QubesOS/qubes-issues#3445]
### Steps to reproduce the behavior:

sudo apt-get install git-remote-gcrypt
git config --add gpg.program /usr/bin/qubes-gpg-client-wrapper
git remote add crypted gcrypt::[remote-url]
git pull crypted master

### Relevant errors:

/usr/bin/qubes-gpg-client-wrapper --no-tty --armor --gen-rand 1 9
qubes-gpg-client: unrecognized option '--gen-rand'

/usr/bin/qubes-gpg-client-wrapper --no-tty --status-fd 3 -q -d
qubes-gpg-client: invalid option -- 'q'

  
### more errors after fixing prev. ones in git-remote-gcrypt
+ /usr/bin/qubes-gpg-client-wrapper --no-tty --with-colons --print-md SHA256
qubes-gpg-client: unrecognized option '--print-md'

+ /usr/bin/qubes-gpg-client-wrapper --no-tty --batch --no-default-keyring --secret-keyring /dev/null --keyring /dev/null --passphrase-fd 3 -d
qubes-gpg-client: unrecognized option '--no-default-keyring'

**Comment by whohoho** [comment]
another one:
gpg --no-tty --batch --force-mdc --compress-algo none --trust-model=always --passphrase-fd 3 -c

**Comment by marmarek** [comment]
On Sat, Jan 13, 2018 at 01:11:15AM +0000, whohoho wrote:
> gpg --no-tty --batch --force-mdc --compress-algo none --trust-model=always --passphrase-fd 3 -c

Is this configurable to not use --passphrase-fd? --passphrase-fd does
not make sense in split gpg trust model - client VM should not know any
secret.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by whohoho** [comment]
In that command symmetric encryption with a passprase is used, so it does not actually have to go to the gpg vm.

I am working on a patch now to have the local gpg do those things.

**Comment by marmarek** [comment]
Ah, indeed there is `-c`. Currently options whitelist is not context aware, so it isn't possible to whitelist options for specific mode only. And better keep it this way for simplicity.

Handling it locally indeed may be a good idea, should be doable in gpg-client-wrapper script, or yet another wrapper.

**Comment by whohoho** [comment]
This is what i have now:
https://github.com/whohoho/qubes-app-linux-split-gpg/blob/master/gpg-client-wrapper

**Comment by marmarek** [comment]
See https://github.com/QubesOS/qubes-app-linux-split-gpg/pull/16

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
