### ISSUE TITLE
Lenovo ThinkPad – installs, but does not boot

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#3461]
#### Qubes OS version:

R4.0-rc3

#### Affected TemplateVMs: 

N/A

---

### Steps to reproduce the behavior:

Install on a very recent Lenovo ThinkPad

### Expected behavior:

Qubes boots successfully

### Actual behavior:

The firmware does not recognize Qubes and refuses to boot it

### General notes:

I could not use R3.2 because it refused to start X, due to my NVidia graphics card.

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
