### ISSUE TITLE
qvm-run returns 0 even if DisposableVM fails to start 

### ISSUE THREAD

**Issue by v6ak** [QubesOS/qubes-issues#3482]
#### Qubes OS version: 

3.2

---

### Steps to reproduce the behavior:

Run this script: https://gist.github.com/v6ak/81dcab48400d24ea636f630a6a693b76

### Expected behavior:

It starts new VMs until there is not enough memory. Once a VM start fails, qvm-run returns non-zero code, failing recursively all the script instances across the VMs.

### Actual behavior:

When OOM point is reached, qvm-run returns 0. See the output in the gist.

**Comment by marmarek** [comment]
FWIW, this issue is fixed in Qubes 4.0 (as the whole DispVM handling is rewritten there).

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
