### ISSUE TITLE
qvm-usb won't list after suspend

### ISSUE THREAD

**Issue by SamuelHentschel** [QubesOS/qubes-issues#3491]
#### Qubes OS version:

R3.2

#### Affected TemplateVMs: 

Dom0, sys-usb(?)

---

### Steps to reproduce the behavior:

1. Run qvm-usb -l after a reboot
2. Shut laptop lid
3. Open laptop lid
4. Run qvm-usb -l again

### Expected behavior:

qvm-usb -l should show all the usb devices I have.

### Actual behavior:

No devices are shown, even though two are supposed to be there.

### General notes:

$ qvm-usb -l
sys-usb:3-1    ****.****    **********************
sys-usb:3-8    ****.****    **********************
sys-usb:3-5    ****.****    **********************
$ qvm-usb -l
$

---

**Comment by SamuelHentschel** [comment]
This might actually be related to an ACPI error I'm getting (since it is only after shutting my laptop lid).  I'll try and catch that error and put it here.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
