### ISSUE TITLE
Ease creating USB VM even if USB keyboard is used

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3516]
Even if the system have only one USB controller, and only USB keyboard, creating USB VM, with [`qubes.InputKeyboard` service, part of input-proxy, enabled](https://www.qubes-os.org/doc/usb/#how-to-use-a-usb-keyboard) still makes some sense. While USB VM will be able to spy and/or subvert the keyboard, user will see resulting actions. Malicious USB device will not be able to exploit some dom0 kernel driver, silently in the background. And when bundled with [some 2FA](https://www.qubes-os.org/doc/yubi-key/), malicious USB VM will not be able to unlock the screen on its own.

Besides enabling `qubes.InputKeyboard` service, there is one more problem: USB controllers are blacklisted in dom0 (specifically: connected to xen-pciback driver, before loading actual USB controllers drivers) - this prevents entering LUKS passphrase using USB keyboard. 

For now, lets ease the basic thing:
 - do not blacklist USB controllers early (only just before actual starting USB VM)
 - enable qubes.InputKeyboard service

To (semi-)securely use it, user is responsible for disconnecting any untrusted USB device from the system for the boot time. Note that this (unfortunately) should be a standard routine even in non-USB keyboard case, because BIOS (also having USB drivers) potentially could be exploited by malicious device at early boot stage too.

Later, we can employ additional protection, using [usb device authorization](https://www.kernel.org/doc/Documentation/usb/authorization.txt), to allow only HID devices and only for the LUKS passphrase entering time. This is still far less protection than USB VM + input-proxy, but something better than allowing all devices.

Some long term solution could be bundling minimal USB VM with input-proxy into initramfs, but at this level of complexity (and required work), it may be better to simply adjust hardware configuration instead (like installing separate USB controller for this).

This is related to #2959, #2116, #3203

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> Even if the system have only one USB controller, and only USB keyboard, creating USB VM, with [`qubes.InputKeyboard` service, part of input-proxy, enabled](https://www.qubes-os.org/doc/usb/#how-to-use-a-usb-keyboard) still makes some sense. 

In this situation (system with only one USB controller, and only USB
keyboard) it also makes sense to use USBVM for features only: it allows
one to assign specific USB devices to specific VMs, which is great!

(Even if these are not mass storage, which would work even without USBVM.)

**Comment by davex25** [comment]
I just tried running this:

sudo qubesctl state.sls qvm.sys-usb

Which I guess was stupid because I have a USB keyboard.  My mouse continued to work but my keyboard did nothing.  After an hour or so of monkeying around with a recovery usb image, I found the /etc/qubes-rpc/policy/qubes.InputMouse and InputKeyboard files.  

The keyboard file was set to deny everything.  But from the looks of this issue, it seems like that should not have happened?

**Comment by xaki23** [comment]
by now, we have working qubesctl solutions, but it still requires users read the documentation and do these manual steps.

i suggest we change the installer to take care of this:

#### if usb-keyboard is detected (and user didnt actively deselect sys-usb creation), 
* apply qvm.sys-usb (as without usb kbd),
* apply qvm.usb-keyboard (dont hide usb controllers, allow kbd proxy),
* disable sys-usb autostart (thats a new part and important!) 


#### for users without usb kbd:
* this does not change anything 

#### for users with usb kbd:
* this does not change the security situation of a fresh install (compared to "no sys-usb at all")
* this does not change install-reliability situation (unlike "sys-usb with autostart")
* this does improve the perceived usability for both casual and advanced users

**Comment by xaki23** [comment]
(brainstate dump after looking into this for some hours and having some more mails about it on/near -users mailinglist)

relevant pieces of code:
https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/blob/master/qvm/sys-usb.sls
https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/blob/master/qvm/usb-keyboard.sls
https://github.com/QubesOS/qubes-anaconda-addon/tree/master/org_qubes_os_initial_setup/

this turns out to be slightly less straightforward than i hoped. (who would have thought!)
there are some extra scenarios to consider beyond "does the user have a usb keyboard or not".
* started-from-usb (as in: installed-to-usb) ... sys-usb is simply not possible in a sane way.
* merge-sysnet-and-sysusb ... not safe to offer with usb-keyboard since it has unwanted-autostart potential.
* sys-usb autostart in general ... perhaps disabling sys-usb autostart should be merged into usb-keyboard.sls, it does not make _much_ difference for the security situation and avoids so much drama.
* big red warning ... since we are talking about a "not recommended" configuration, perhaps it should have a warning popup during install like the "no iommu detected" one.

overall i still think this is a good idea because currently we have users who run with a no-sysusb "usb connected to dom0" situation for months which seems like one of the worst possible results.

**Comment by marmarek** [comment]
The salt approach is already included in R4.1. Further simplifications will be tracked separately.
