### ISSUE TITLE
Laptop Lenovo W520 cannot switch off properly

### ISSUE THREAD

**Issue by ThierryIT** [QubesOS/qubes-issues#3531]
#### Qubes OS version:

4.0 r4

#### Affected TemplateVMs: 

dom0

---

### Steps to reproduce the behavior:

switch off laptop

### Expected behavior:

switch off properly

### Actual behavior:

see attached file

### General notes:

Didn't have this problem with Qubes 3.2 and Qubes 4.0 r3
Seems to be link to the possibility, before shutting down the laptop, to validate the "Save session for future logins" option..
If I do not validate it, the laptop switch off by himself, but it take time still ...

---

#### Related issues:

![img_20180204_094008](https://user-images.githubusercontent.com/31948106/35775733-115348fa-0997-11e8-97c3-2b6e981e062f.jpg)

**Comment by andrewdavidwong** [comment]
Leaving this open for now in case it turns out to a broader problem not confined to a single model. Note, however, that our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/) state that bugs that affect only a specific hardware configuration are too localized for `qubes-issues` and should be sent to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead, so this may be closed if that turns out to be the case.

**Comment by ThierryIT** [comment]
I am closing and transfering this ticket to the mailing list ..
Just to inform you that the problem appeared when I have upgraded from 4.0r3 to 4.0r4.
Thx
