### ISSUE TITLE
Cleanup VM/Qube/qube usages in UI

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3540]
- [x] "Create Qubes VM" in the Appmenu -> "Create a new qube"
 - [ ] "Qube Manager" -> "Qubes Manager" (because manages the whole systems, not just qubes)?
 - [x] "{Update,Clock,net}VM" in Qubes Global Settings -> \1 qube
 - [ ] "dom0" -> "admin" (ibid.)

@andrewdavidwong

**Comment by andrewdavidwong** [comment]
:ok_hand:

**Comment by marmarta** [comment]
I'm not sure about Qube Manager -> Qubes Manager; we've had this whole discussion about how we don't want to have a single place to manage all of Qubes (like the old Qubes Manager), and that's why we're resurrecting only parts of it, those that pertain to managing qubes themselves. After all, the first proposed name was 'VM and Template Manager'.

About updatevm, clockvm, netvm: do we really want to use UpdateQube, ClockQube, NetQube? I think it looks really ugly, and also, the properties in CLI tools use the updatevm, clockvm, netvm names, so it adds a layer of confusion.

And where do you want to replace dom0 with 'admin'? 'dom0' is just a VM name at the moment, not some special value (most of the time).

**Comment by marmarta** [comment]
I think this was generally done by various changes in https://github.com/QubesOS/qubes-desktop-linux-manager/ , except for renaming dom0 to adminvm. But in many places (like config tool) we do use Type: AdminVM to denote all admin qubes (as happens in policy). I think this can be closed.
