### ISSUE TITLE
Debian based UpdateVM does not support --action=list or reinstall

### ISSUE THREAD

**Issue by awokd** [QubesOS/qubes-issues#3553]
#### Affected TemplateVMs: 

debian-9, whonix-gw

---

### Steps to reproduce the behavior:

Set UpdateVM to a debian-9 based sys-firewall or standard sys-whonix
sudo qubes-dom0-update --action=list kernel-qubes-vm  (or --action=reinstall, etc.)

### Expected behavior:

packages will be listed or reinstalled

### Actual behavior:

ERROR: yum version installed in VM host does not suppport --downloadonly option
ERROR: only 'install' and 'upgrade' actions supported (list not)

### General notes:

Ideally these additional `--action` commands would work with a Debian based UpdateVM, but if it's a WONTFIX there should be a documented work-around available. `--action=reinstall` is easy enough to document (dnf remove, then install the package) but how does one `--action=list` available packages in the qubes-dom0-unstable repository for example?

---

#### Related issues:

https://github.com/QubesOS/qubes-issues/issues/1029
https://github.com/QubesOS/qubes-issues/issues/3495

**Comment by andrewdavidwong** [comment]
You left the "Qubes OS version" field empty, but I'm guessing you meant 4.0.

**Comment by awokd** [comment]
@andrewdavidwong No, it applies to both 3.2 & 4.0 using a Debian based UpdateVM.

**Comment by awokd** [comment]
Probably older versions too, since #1029 was released. Should I have written "all"?

**Comment by andrewdavidwong** [comment]
> Probably older versions too, since #1029 was released. Should I have written "all"?

Yeah, or "3.2 and 4.0," or "3.2 and 4.0 confirmed, but probably all," depending on your temperament with respect to verbosity and speculation. :slightly_smiling_face: 

Since an issue can have only one milestone, I'll change this one to 3.2

**Comment by awokd** [comment]
> ERROR: yum version installed in VM host does not suppport --downloadonly option
> ERROR: only 'install' and 'upgrade' actions supported (list not)

If I copy in qubes-dom0.repo to my debian-9 template (and disable all repos in there and replace `r$releasever` with `r3.2`), yum lets me list available packages. Like the error message says though, `--downloadonly` is not supported. sys-whonix can't resolve yum.qubes-os.org probably for security reasons, but there must be a way to accomplish the same thing in there because it can download updates for dom0.

~~~
user@debian-9:~$ yum --enablerepo=qubes-dom0-current list kernel-qubes-vm
qubes-dom0-current                                                                     | 3.6 kB  00:00:00
qubes-dom0-current/primary_db                                                          | 890 kB  00:00:01
Available Packages
kernel-qubes-vm.x86_64                      1000:4.9.56-21.pvops.qubes                      qubes-dom0-current
user@debian-9:~$ yum --enablerepo=qubes-dom0-current-testing list kernel-qubes-vm
qubes-dom0-current-testing                                                             | 3.6 kB  00:00:00
qubes-dom0-current-testing/primary_db                                                  | 1.6 MB  00:00:02   
Available Packages
kernel-qubes-vm.x86_64                  1000:4.14.18-1.pvops.qubes                  qubes-dom0-current-testing
user@debian-9:~$
~~~

**Comment by awokd** [comment]
Looks like the error is coming from qubes-download-dom0-updates.sh. Need to try modifying it to permit `--action=list` on a debian-9 template. sys-whonix needs a UWT wrapper defined, if I'm reading the error right.

**Comment by marmarek** [comment]
See [`/usr/lib/qubes/qubes-download-dom0-updates.sh`](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/misc/qubes-download-dom0-updates.sh#L110-L133)
For list, you don't really need `--downloadonly`, because you don't download any package. Try something like this: https://github.com/marmarek/qubes-core-agent-linux/commit/e60194bde84fe40390d512a4724c331167bb4291

**Comment by awokd** [comment]
That's the file I was looking at too. Wasn't seeing anything that would prevent a list! Thanks, will try it out and see if I can figure out how to make sys-whonix work with it too. Think it needs a wrapper defined for yum.

**Comment by adrelanos** [comment]
awokd:
> sys-whonix needs a UWT wrapper defined, if I'm reading the error right.

Sure?

There is a uwt wrapper for yum and yumdownloader.

https://github.com/Whonix/uwt/blob/master/usr/bin/yum.anondist

https://github.com/Whonix/uwt/blob/master/usr/bin/yumdownloader.anondist

These are the programs run by qubes-download-dom0-updates.sh. It makes
more sense to uwt wrap (since there are no socks settings available
which would be better) the actual network using programs by the
qubes-download-dom0-updates.sh scripts than the
qubes-download-dom0-updates.sh script itself.

There is no 'dnf' in Debian.

Let me know ASP please if something is missing in Whonix so it can make
its way into Whonix 14 in time.

**Comment by awokd** [comment]
Thanks, @adrelanos . Found those wrappers where you said they'd be. 
I got @marmarek 's script running on a standard debian-9 template and it works there. It's not super clean output (like it always lists my currently installed packages) but it does also list packages available in the repo specified. Copied it over to sys-whonix, but when I tried the same '--action=list' there with sys-whonix as my updatevm, I got:
~~~
mktemp: failed to create file via template '/tmp/uwt_root/tmp.XXXXXXXXXX': Permission denied
chmod: cannot access '': No such file or directory
/usr/bin/uwt: line 259: : No such file or directory
uwt: Missing torsocks configuration file "\.
~~~

But I think I may have figured out a work-around at least, I removed `fakeroot` from this section of Marmarek's code:
~~~
+    elif [ "$YUM_ACTION" == "list" ] || [ "$YUM_ACTION" == "search" ]; then
+        # those actions do not download any package, so lack of --downloadonly is irrelevant
+        YUM_COMMAND="fakeroot $YUM $YUM_ACTION -y"
~~~

and now it lists packages for the specified repo!
Maybe `fakeroot` throws off the UWT wrapper?

**Comment by awokd** [comment]
And this is just something where it would be nice to have feature parity with the Fedora template. If it doesn't make the cut for Whonix 14 it's not a big deal for me at least. Can patch it in later!

**Comment by awokd** [comment]
In the (Debian) portion of the `qubes-download-dom0-updates.sh` script, list/search are the only options that use yum instead of yumdownloader. Maybe removing `fakeroot` there is all that needs to be done since `yum` can apparently list and search without being sudo.

**Comment by adrelanos** [comment]
Whonix 14 doesn't use /usr/bin/uwt anymore since it is no longer required. The mktemp workaround is no longer required. (This is because torsocks was improved.)

We are using `/etc/tor/torsocks.conf`.
```
# Set Torsocks to use an automatically generated SOCKS5 username/password based
# on the process ID and current time, that makes the connections to Tor use a
# different circuit from other existing streams in Tor on a per-process basis.
# If set, the SOCKS5Username and SOCKS5Password options must not be set.
# (Default: 0)
IsolatePID 1
```

Since it doesn't use mktemp anymore, you won't have the issue described in https://github.com/QubesOS/qubes-issues/issues/3553#issuecomment-364773920.

I've removed `fakeroot` from `/usr/lib/qubes/qubes-download-dom0-updates.sh` as per your instructions and commented out the `exit 1` of the `does not suppport --downloadonly` check.

It's downloading. Dunno yet if it will actually reinstall the template but at least for sure we don't have any uwt / connectivity issues.

**Comment by awokd** [comment]
Doc link for tracking: https://github.com/QubesOS/qubes-doc/pull/584
