### ISSUE TITLE
Application menu shortcut starts custom disposable template instead of disposable based on that template

### ISSUE THREAD

**Issue by kototama** [QubesOS/qubes-issues#3574]
#### Qubes OS version:
4RC3

#### Affected TemplateVMs: 

Own created custom DVM Template.

### Steps to reproduce the behavior:

`qvm-create --template debian-9 custom-dvm --label red`
`qvm-prefs custom-dvm appmenus-dispvm 1`

Click Firefox menu in the `Disposable: custom-dvm` menu. Qubes indicates `custom-dvm` is starting.

### Expected behavior:

A DisposableVM is started with Firefox.

### Actual behavior:

The custom DVM Template is started, running Firefox.

### General notes:

Runnin `qvm-run --dispm custom-dvm firefox` from the command line works.
The menu also works after a reboot.

---

**Comment by marmarek** [comment]
Steps lack setting `template_for_dispvms=True`, but since `qvm-run --dispvm custom-dvm firefox` worked for you, I assume you just forgot mentioning it here.

Anyway, I can't reproduce it on fully updated (current-testing) system. Try installing updates.
If that still happens to you then, collect some more info, especially how custom-dvm-firefox.desktop looks like (there are multiple copies of it, in user home directory, use `find`). Especially check if those copies are in sync.

**Comment by andrewdavidwong** [comment]
Closing this for now as "cannot reproduce." If you believe this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by kototama** [comment]
I am running with the stable channel of Q4, so @marmarek may have fixed in testing.

**Comment by 0brand** [comment]
This `dvm` behavior was reported in the following thread and I was able to reproduce it.

https://whonix.org/t/whonix-14-starting-a-whonix-14-dispvm-actually-starts-the-templatebasedvm-instead/5579/1

The user created a Whonix dvm using [salt](https://whonix.org/wiki/Qubes/DisposableVM#Creating_Whonix_Default_DVM_Template_Based_on_Whonix-Workstation). 

`sudo qubesctl state.sls qvm.whonix-ws-dvm`

When launching the expected `DispVM` from the appmenu, the `dvm` template was launched instead. While I was not able to reproduce this behavior using the `salt` method of `dvm` creation. I was able to manually create the `dvm` template and consistently reproduce the behavior.
```
qvm-create -t whonix-ws-14-dvm --label red whonix-ws-14-dvm
qvm-prefs whonix-ws-14-dvm template_for_dispvms true
qvm-features whonix-ws-14-dvm appmenus-dispvm 1
```
When starting the DispVM (expected ) the `dvm` template is started instead. This only happens on first start. All starts afterwords are the expected DispVM.

Not sure if this is relevant or just coincidence but when I also set the  `default_dispvm=whonix-ws-14-dvm` the DispVM was spawned at first start as expected. While this pref is already set, I tested this a number of times and it always had the expected Dispvm start. When not re-set, I got the `dvm` template at first start.

I was also able to reproduce this with a Debian dvm. Didn't try with Fedora.

**Comment by marmarek** [comment]
Looks like some XFCE caching issue. If I `touch` relevant `.desktop` file (for example `~/.local/share/applications/whonix-ws-14-dvm-firefox.desktop`, it starts to work. `xdg-desktop-menu forceupdate` does _not_ help.

**Comment by marmarek** [comment]
Restarting the whole xfce4-panel (`xfce4-panel --restart`) does help too, but is "a bit" drastic. And have negative side effects, like network manager icon is gone now...

**Comment by andrewdavidwong** [comment]
> Is this not a somewhat serious issue? For example, browser history will remain forever for the first session across all subsequent DispVM instances. I was very surprised when I saw this today after updating my VMs to fedora-29 based templates (with salt).

I'm inclined to agree. This bug basically tricks the user into doing DisposableVM activities in the DVM Template. I just experienced the bug myself, and it's very easy to miss the fact that it opened the DVM Template instead of a DispVM based on that DVM Template. If the user doesn't notice the, the unintended persistence and cross-contamination could be disastrous.

**Comment by mvermaes** [comment]
Just encountered this for the first time, recreating a custom DispVM template with Fedora 30 on Qubes 4.0. Otherwise same behaviour as original report. Not using Whonix or Salt.

Touching `~/.local/share/applications/<dispvm>-firefox.desktop` per https://github.com/QubesOS/qubes-issues/issues/3574#issuecomment-445499543 fixes the problem.

**Comment by NieDzejkob** [comment]
An issue with labels "major security bug; core component" open for almost 2 years now doesn't inspire confidence. After reading the comments here, I don't understand what is currently blocking getting this fixed. Would it help if I bisected the relevant xfce commit?

**Comment by gasull** [comment]
I created a DVM out of a Debian 10 template, and this doesn't happen to me anymore.

But as far as I know, Qubes still ships with Debian 9, so I don't think this cannot be closed just yet.

**Comment by EncryptedGiraffe** [comment]
This happened to me with a newly created disposable template based on debian-11 in Qubes 4.1. Clicking on any menu entry for debian-11-dvm would open the template itself. Rebooting fixed the issue, menu links now opening in dispxxxx.

**Comment by mkfifos** [comment]
An issue I can confirm. After creating a DVM-Template I had to reboot in order to get an xfce-menu with "Disposable: new-dvm" on Qubes 4.0.4, all packages up-to-date, Debian-10, Fedora-33 and Kali-Rolling as TemplatesVM.

**Comment by adrelanos** [comment]
I cannot reproduce his anymore in Qubes R4.2. Qubes start menu there has:

> Apps | Templates

* Starting the dvm under "Apps" always is the Disposable.
* Starting the dvm under "Templates" always is the Disposable Template.
