### ISSUE TITLE
wifi button doesn't work on HP 1040 G3

### ISSUE THREAD

**Issue by qubecub** [QubesOS/qubes-issues#3587]
#### Qubes OS version:

Qubes Release 4.0-rc4 (release candidate)

#### Affected TemplateVMs: 

dom0 / sys-net

---

### Steps to reproduce the behavior:

On HP 1040 G3 laptop, 
Press wifi enabling physical button (above the keyboard). Pressing the button does not enable / disable wifi, no effect whatsoever. 

### Expected behavior:

Pressing wifi buttom once - enables wifi, pressing wifi button again disables wifi. Toggle button. 

### Actual behavior:

Pressing physical wifi button doesn't bring any effect. wifi is always on/enabled. 

### General notes:

I could disable wifi by removing wifi module from the kernel

sudo rmmod iwlmvm
sudo rmmod iwlwifi

After that no wifi networks are available for connection, wifi adapter doesn't receive signal.

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
