### ISSUE TITLE
qvm-sync-clock causes netvm to start on the hour

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#3588]
#### Qubes OS version:

R4.0rc4

---

### Steps to reproduce the behavior:

Shutdown networked VMs, including default netvm (sys-net), i.e. system is in a defacto 'offline' state.

### Expected behavior:

Netvm remains shutdown/not running.

### Actual behavior:

ClockVM starts, which is sys-net or something that depends on a networkVM. This happens each hour.

### General notes:

I think preferred behavior would be not to use --autostart and quietly avoid updating from the network if no networkVMs are running.

This is with an eye toward managing sets of VMs that run according to exclusion rules (notably, networkVMs would be the most excluded).

But even before that's a reality, having your networkVM suddenly start is unsettling if you have shutdown all your networked VMs and intend to work offline for a time. It seems like a potential security and privacy risk to automatically enable NICs (esp radio) from an unseen background process. 

---

#### Related issues:

#2866

**Comment by rustybird** [comment]
I have a patch for dom0 qvm-sync-clock to bail out if the clockvm isn't already running. But how to do the same for VM qvm-sync-clock?

**Comment by marmarek** [comment]
I see two options (or a combinations of them):
 - a VM property whether it should be started on qrexec call (in this case `qubes.GetDate`)
 - a qrexec call setting (argument in policy?) whether it should start target VM if not running

In any case, explicit qvm-start (`admin.vm.Start` Admin API call) would start a VM.

**Comment by rustybird** [comment]
An optional `autostart=no|yes` qrexec policy parameter raising `AccessDenied` on `no` if the resolved target is not running would satisfy everything (because you simply don't set it for an `admin.vm.Start` call or `ask` action), fit into the existing `param_name=value` syntax, and allow exceptions for individual VMs.

But it might take me a while to start working on it, and I'm not really familiar with the qubespolicy code. Maybe someone else wants to take this?

**Comment by tasket** [comment]
Since the undesired event is triggered by dom0, could this be addressed simply by adding an `autostart=True` default parameter to app `run_service()` and have `qvm-sync-clock` specify False?

**Comment by marmarek** [comment]
> Since the undesired event is triggered by dom0

Not really, calling `qvm-sync-clock` in VM will also cause this. And it is scheduled for automatic call. Or rather should be: https://github.com/QubesOS/qubes-core-agent-linux/pull/96

**Comment by tasket** [comment]
I see. In that case the suggested policy parameter would work in most cases where clockvm=networkvm.

However, it may be better to have a dom0 rpc script handle the call for qubes.GetDate and trace netvm dependencies from clockvm to networkvm first. If networkvm isn't running, return a date sourced from dom0. Then isolated vms won't have any obvious sign about the system networking state.

**Comment by andrewdavidwong** [comment]
> having your networkVM suddenly start is unsettling if you have shutdown all your networked VMs and intend to work offline for a time. It seems like a potential security and privacy risk to automatically enable NICs (esp radio) from an unseen background process.

In the era of Meltdown and Spectre, it seems like an undeniable security risk.

**Comment by rustybird** [comment]
> In the era of Meltdown and Spectre, it seems like an undeniable security risk.

Yup. A workaround (which of course only helps users aware of this issue) would be to remember doing `qubes-prefs -s clockvm ''`, or its GUI equivalent, when working offline. But there's a similar problem for VM update checks, and more broadly for any RPC that somehow triggers a netvm startup.

**Comment by tasket** [comment]
What if clockvm was a property for use by dom0 only, and guest VMs just got the time from dom0? Then dom0 could check the time periodically _if_ the associated networkVM is already running.

**Comment by rustybird** [comment]
I suppose the clockvm might want to do things that are too complicated to hardcode into dom0, e.g. give out a slightly randomized time to each caller.

**Comment by esote** [comment]
@marmarek I am currently experiencing this issue, even though I have `qubes-core-dom0-4.0.24-1.fc25` from the default `current` repository.

**Comment by trueriver** [comment]
My preference would be an option under "provides network" in each qubes settings that "Allow start when other VMs ask for this network". Option would be ignored/greyed out if the VM did not provide network for anyone else. This would be a three way radio button "Always", "Ask each time", "Never"

My suggestion is that the default on installtion would be "Ask each time".

The less-secure but user friendly option would be to set this to Always by default, so that current behaviour is maintained unless a user overrides it. 

The advantage of my design is that users could allow some network qubes to start on demand, but make sure others that may be sensitive in their current location do not expose them to unwelcome scrutiny. 

Example user may be happy to connect to the wifi at an internet cafe from one VM, but not want another VM to start a tor connection when in a country where tor is unwelcome.

I cannot comment on the technical feasibility of what I am asking, nor any adverse security consequences that I have not noticed. I DO think that the current settings are inherently risky for some users in some situations.

**Comment by jpouellet** [comment]
Check your `/etc/qubes-rpc/policy/qubes.GetDate` in dom0.

It should contain `target=dom0`, but probably still contains `target=sys-net`.

See also https://github.com/QubesOS/qubes-issues/issues/3941

**Comment by tasket** [comment]
This is still occurring for me, despite having `target=dom0` in qubes.GetDate.

**Comment by esote** [comment]
@jpouellet @tasket Same for me with latest `qubes-core-dom0-4.0.27-1.fc25`, with `target=dom0` in `qubes.GetDate`. Could other components be starting `sys-net` hourly?

**Comment by trueriver** [comment]
The best workaround I have found is to set sys-net so that whenever it boots up it does so with wifi disabled. When wifi is truly desired, it is simple to right click the network icon in the system tray and enable it. When wifi was not wanted, all that is wasted is a few machine cycles and at least Qubes is not advertising my presence at an embarrassing time.

This Qubes Users thread
 https://groups.google.com/forum/#!topic/qubes-users/0_LUn4ha8Jg 
shows the technique that Chris L kindly helped me to get right

I offer this as a viable workaround but not a long term fix

**Comment by rustybird** [comment]
https://github.com/QubesOS/qubes-core-admin/pull/225
