### ISSUE TITLE
Monitor DPMS power-saving not working

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#3590]
#### Qubes OS version:

R4.0-rc4

---

### Steps to reproduce the behavior:

In `xfce4-power-manager-settings` adjust the display to suspend and/or power off after a set time, then wait.

### Expected behavior:

As with R3.2, monitor goes into standby/suspend/low power mode.

### Actual behavior:

Monitor display is blanked, but remains fully powered-on.

### General notes:

This may be related to the fact that I used KDE on R3.2, and now I use Xfce on R4.0.

---

#### Related issues:

Maybe issue #2212

**Comment by taradiddles** [comment]
FWIW I've had the same problem since I began to use Qubes (aroud R3.0rcX), and like you I have the same problem with R4.0rc{3,4}. I used Xfce in R3.x so maybe Xfce's power manager is the culprit.

When sitting around the laptop doing other stuff I've noticed that the monitor would turn off but would then wake up after a few seconds and stay blank, without any user interaction.

Maybe double check that xscreensaver has its power management settings off.
(which makes me think that I'll try to disable Xfce's screen power management and enable xscreensaver's and see what happens).

**Comment by schnurentwickler** [comment]
I got this issue as well since Q3.2.
Same bug already posted with similar behavior, but from 2006: https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/71368
My workaround after some research is to turn off xfce4-power-management stuff in System Tools -> Session and startup because it seems buggy. I am using the xorg displaycommand: `xset s SECONDS ` (or `xset s on` / off) and it works very well.
But the xfce4 lockscreen does not work anymore for standby / lid-close. 

I do not care about this chaotic window manager smacking, because the new qubes control center (...) handles display dpms and VM (video/fullscreen/notify) activity - working as an overlay with wayland hopefully.

**Comment by taradiddles** [comment]
> But the xfce4 lockscreen does not work anymore for standby / lid-close.

Systemd manages lid events (among others) until an app like xfce's power manager "takes over". If you don't have xfce's power manager running you should be able to set HandleLidSwitch=lock in /etc/systemd/logind.conf. (see `man logind.conf`).
For standby a pre-suspend script that would run `xcrensaver-command -lock` should do the trick.
Not tested though...

**Comment by taradiddles** [comment]
For info dpms works as expected with xfce power manager's display settings disabled and xscreensaver's enabled (which should be identical to `xset` commands). The drawback for laptops is that there aren't different timeouts when on battery or AC. A workaround is to change the timeout with `xset` commands upon ac/bat events.

**Comment by schnurentwickler** [comment]
If it is for the milestone 4.0 and future based releases: Avoid any Desktop Manager dependencies.
Qubes is far more robust and lesser bugged if the settings for dom0' system is set via configuration files.
Even if qubes is soon cloud based and/or remote using is possible, the user still needs a device to use qubes. And this device should be configured as simple as possible. 
Xcfe (and most other window manager) are too much for qubes. Configuration is a pain.

**Comment by DemiMarie** [comment]
@marmarek OK to apply the `logind.conf` workaround?

**Comment by gr-g** [comment]
I have also experienced strange interactions between xfce4-power-manager and xscreensaver in a recent install of 4.1-rc2. This is what happens as far as I understand:
- xfce4-power-manager has settings for blanking the screen and for display suspend/poweroff. For blanking the screen it actually uses an external screensaver (xscreensaver, either directly or through the `xset s` commands). For suspend/poweroff, it sets the timeouts in the X server (similarly to running the `xset dpms` commands, with settings visible via `xset q`).
- However, when xscreensaver is installed, its own settings (in ~/.xscreensaver) are applied and override the settings in xfce4-power-manager. So if power management is disabled in xscreensaver, standby/suspend/poweroff will not work irrespective of the settings in xfce4-power-manager. if power management is enabled in xscreensaver, those standby/suspend/poweroff timeouts will be applied.
- Still, xfce4-power-manager will trigger the blanking of the screen through its own timeout, and this actually ignores the xscreensaver settings (for instance, it will always lock the screen even if locking is deactivated in the xscreensaver settings).
- Another minor issue is that in xscreensaver, setting "Mode=Disable Screensaver" will also disable power management even if "Power Management Enabled" remains checked.

I would summarize the problems for Qubes users as follows, but please let me know if I am missing something:
1. Users can be confused by duplicated display settings under "Power Manager" and "Screensaver", and are not likely to understand that the settings under "Power Manager" are (mostly) ignored since they are overriden by "Screensaver".
2. Even if users understand that "Screensaver" takes precedence, not everything will work as expected unless they turn off all display management options under "Power Manager", including setting "Blank after=never" (if they don't, setting "Mode=Disable Screensaver" in xscreensaver will not work, and deactivating screen locking in xscreensaver will not work). Even then, they cannot set "Mode=Disable Screensaver" or they will lose the ability to standby/suspend/poweroff the display.

Honestly I have no good ideas on how to improve the situation from the Qubes perspective, since both programs have to be installed and they just don't play well together.

**Comment by gr-g** [comment]
One further element I missed in the previous comment: `xss-lock` is also active by default and interferes with xfce4-power-manager and xscreensaver.
(xss-lock is executed by `/etc/xdg/autostart/xfce4-xss-lock.desktop`, which is provided by `xfce4-settings-qubes`)

In particular, even if a user disables screen locking in xscreensaver, when the display goes in standby/suspend/poweroff `xss-lock` is activated and triggers the screen lock despite the user configuration (xss-lock calls xflock4, which calls xscreensaver-command -lock).

**Comment by ng0177** [comment]
I figured the HDMI vs DVI cable to be the culprit. The following settings on a DVI cable (only) on fairly recent hardware gets my monitor into power-saving:

1. Power Manager
	Display Power Mangement: OFF
2. Screensaver
	Mode: Blank Screen Only
        Advanced:
               Power Management: ON
               Quick Power: ON
