### ISSUE TITLE
Can't backup VMs: Selected directory do not exists or is not a directory

### ISSUE THREAD

**Issue by dmoerner** [QubesOS/qubes-issues#3594]
Fresh install of Qubes R4.0 rc4

On attempting to back up any VM, I get the error "Selected directory do not exists or is not a directory." I am choosing a directory on an external, encrypted hard disk that definitely exists, and the disk is mounted in a VM. I am selecting it with the Nautilus window that pops up from the appropriate VM, and this is the same directory I successfully restored backups from on installing Qubes R4.0 rc4. I've tried with both an appvm and a dispvm, and get the same error.

**Comment by marmarek** [comment]
Wild guess - some spaces in directory path?

**Comment by dmoerner** [comment]
No spaces, directory path is: /run/media/user/$drive/Data/Backups, where $drive includes no spaces.

Also reported on the mailing list: https://groups.google.com/forum/#!topic/qubes-users/crXfuSQCCbI

**Comment by mig5** [comment]
I reproduce this. In my case, I am mounting an external hard drive at /mnt/removable on my sys-usb, but I get the same error as the OP even though I was allowed to select the directory in the UI.

Can we also fix the grammar:  "Selected directory do not exists" should read "Selected directory does not exist" (note no plural on 'exist', and 'does not' because it's a single directory)

**Comment by mig5** [comment]
The issue appears to be that the check on line 240 of qubesmanager/backup.py:
```
 os.path.isdir(backup_location)
```

That is a local check on the dom0, instead of being a check on the VM that has the mounted disk (in my case sys-usb).

As proof, I can 'cheat' this by running sudo mkdir /mnt/removable on my dom0, and then I can proceed to backup my VMs on the disk mounted on sys-usb at /mnt/removable
