### ISSUE TITLE
Qubes OS 4.0 rc4 - fan constantly on in "pulsating" manner

### ISSUE THREAD

**Issue by qubecub** [QubesOS/qubes-issues#3599]
#### Qubes OS version:

Qubes OS 4.0 rc4

#### Affected TemplateVMs: 

entire system but configuration probably relates to dom0

---

### Steps to reproduce the behavior:

After starting up the laptop (HP 1040 G3) Qubes OS starts. Then fan kicks in and constantly stays on, even without anything apart from dom0 running. 
The fan in on but increases intensity every so slightly every 2-3 secons, creating annoying pulsating fan noise. I was unable to find any configuration or settings regarding power management / fan speed online. Hence raising this as an issue. 

### Expected behavior:

Fan kicks in when CPU processing increases, but then goes off when ide. 
Also, when on I would expect constant noise/hum rather than pulsating. 

### Actual behavior:

Fan always on, pulsating intensity with about 2-3 Hz

### General notes:

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
