### ISSUE TITLE
Qubes running on a dual EPYC 7301 system!

### ISSUE THREAD

**Issue by wilsonk** [QubesOS/qubes-issues#3602]
#### Qubes OS version:

Qubes-4.0-RC4 
AMD EPYC 7301 X 2
128 GB of 2666 RAM
240 GB SSD drive in SATA 3 (not SAS)
Radeon onboard graphics

IOMMU enabled in rather new BIOS (Nov 27/17)
SM enabled   (Virtualization support)

#### Affected TemplateVMs: 

All VM's affected

---

### Steps to reproduce the behavior:

Try to start VM

### Expected behavior:

VM starts

### Actual behavior:

VM doesn't start and there are errors in the ```/var/log/libvirt/libxl/libxl-driver.log``` that say "PCI device... error. Possibly IOMMU is not enabled?"

### General notes:

dmesg seems to indiacate that IOMMUv2 won't start but there are no errors for IOMMU and the device listing shows IOMMU was initialized.

I can gather a little more info on this later, but thought I would post this here quickly in case someone might know a simple fix for this that I am missing.

I can start a VM by disabling networking and not using sys-net/sys-firewall, so it might be somewhat related to 3125?
---

#### Related issues:

#3125 might be related

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
