### ISSUE TITLE
VM not starting with 3 Monitors

### ISSUE THREAD

**Issue by TheBubblePopped** [QubesOS/qubes-issues#3634]
#### Qubes OS version:
4.0RC4

#### Affected component(s): 
VM not starting

---

### Steps to reproduce the behavior:
Install OS then just sudo qubes-dom0-update => no vm starts at all again from that point on ( starts but no window appears)

i tested current-testing unstable and secure updates but still facing the same problem

### Expected behavior:
Vm should open

### General notes:
1800x 
I think the kernel updates there too and causes problems but i have no idea

---

**Comment by marmarek** [comment]
> no vm starts at all again from that point on ( starts but no window appears)

So does VM start or not? Check with `qvm-ls` command - what do you have in "STATE" column? What happens when you try starting a VM from terminal with `qvm-start SOME_VM`? Can you start any application with `qvm-run` command (for example `qvm-run work firefox`)?

**Comment by TheBubblePopped** [comment]
I am reformatting it now. Will check and update but the VM start in general in the Qubes manager it appears green ( and i can t shut it down) but there is no window that opens. I tried the qvm-run personal firefox but it does nothing at all and seems like stucked

**Comment by TheBubblePopped** [comment]
So here is my update. Now i know that the main problem is. Everytime i connect my 3t monitor nothing is starting. Any ideas how to solve this? its a 4k 60hz ASUS pb 279Q

**Comment by marmarek** [comment]
What is your total resolution?

**Comment by marmarek** [comment]
So, in total it is 6640 x 3840, right? This should be far from GUI protocol limits (max window 16384x6144). But check /var/log/qubes/gui*log  in dom0 and X logs in VMs anyway.

**Comment by TheBubblePopped** [comment]
But it is not as 1 monitor it is splitted into 3 parts so why does the total resolution matter? I ll check and let you know

**Comment by TheBubblePopped** [comment]
The only thing i get is Icon size: 128x128 

4 times in a row, and if i connect my monitor and do some stuff i get under each of these icon size messages 

5 times : 
reloading X server parameters...

and then one time random on the second icon size message the message:

open /var /run/qubes/qubes/clipboard.bin.xevent; No such file or directory

**Comment by TheBubblePopped** [comment]
And on the qube personal log i can see 
Icon size: 128x128
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
open /var/run/qubes/qubes-clipboard.bin.xevent: No such file or directory
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
invalid PMaxSize for 0x400045 (587/32767)

**Comment by swilso793** [comment]
Anyone else with 3 monitors have the same problem? I am about to buy a third one as well and this would be a deal breaker.

**Comment by Polygonbugs** [comment]
> This should be far from GUI protocol limits (max window 16384x6144).

What happens if there are four 4K monitors? BTW, it won't be possible unless if I could install dGPU drivers... I've only seen few of them use dGPU.

**Comment by tonsilware** [comment]
This issue is probably the same as https://github.com/QubesOS/qubes-issues/issues/3174 

Basically the hardcoded "VideoRam 65536" in /etc/X11/xorg-qubes-conf.template in the problem. As I mentioned in the other issue, the VideoRam value should dynamically calculated to ensure it accommodates the total resolution and not just hardcoded at 65536, because 65536 is too low for multiple 4k displays and causes the VMs to not start.

My current solution: Disconnect all extra monitors (so you can actually start the vms). Then start each template vm and edit /etc/X11/xorg-qubes-conf.template in each template vm, increasing the "VideoRam 65536" to a sufficiently large value to ensure that there is sufficient memory to accommodate your total resolution. (I just doubled the VideoRam to 131072 and that is fine for my setup.) Then shutdown the edited template vms and after that everything should work.. until an update overwrites your xorg-qubes-conf.template and you have to re-edit the files to fix the problem again..
