### ISSUE TITLE
qvm-usb fails to attach devices: "No unused port found!"

### ISSUE THREAD

**Issue by mdickers47** [QubesOS/qubes-issues#3649]
#### Qubes OS version:

R3.2

#### Affected component(s): 

qubes-usb-proxy

---

### Steps to reproduce the behavior:

On a simple R3.2 installation, that recently received version 1.0.16 of the qubes-usb-proxy and qubes-usb-proxy-dom0 packages.

The versions of kernel-qubes-vm on the machine are:
kernel-qubes-vm-4.4.14-11.pvops.qubes.x86_64
kernel-qubes-vm-4.4.38-11.pvops.qubes.x86_64

Run "qvm-usb -a" to attach any device to any VM to reproduce the failure below:

### Expected behavior:

usb device becomes available 

### Actual behavior:

[user@dom0 ~]$ qvm-usb -a somevm sys-usb:2-2
ERROR: Device attach failed: No unused port found!sh: printf: I/O error

### General notes:

I found that the shell script **usb-import** looks for the string "port" on line 43 to detect an "old" kernel header.  My kernel actually emits the string "prt".  I changed the test to "prt" on my local copy of **usb-import** and it is back to working.

This commit changed the test from "prt" to "port" and looks like it may have been a mistake:

https://github.com/QubesOS/qubes-app-linux-usb-proxy/commit/5f94e1064fd5946f127e1257062756be75f92f99

---

#### Related issues:

Probably related to #3455

**Comment by VinceW** [comment]
I can confirm the solution @mdickers47 presented above. 

File: /usr/lib/qubes/usb-import (version: 1.0.16+deb9u1)

Instead of line 43, in the above file it is line 40. 
The current (no-working) line 40 is:

            if [ "$hub" = "port" ]; then

After I changed this into:

            if [ "$hub" = "prt" ]; then
 
It works for me. 

Perhaps this issue could/should be mentioned on the documentation page (https://www.qubes-os.org/doc/usb/)?
