### ISSUE TITLE
Power management / sleep / suspend settings ignored in 3.2 & 4.0-rc4

### ISSUE THREAD

**Issue by 0pcom** [QubesOS/qubes-issues#3668]
#### Qubes OS version:

issue occured for me on both:

3.2
4.0-rc4

#### Affected component(s): 

S3 Sleep
dom0

---

### Steps to eliminate the behavior:

Changed settings are ignored

### Expected behavior:

Sleep / suspend timer adjusts sleep parameters

### Actual behavior:

Adjusting system settings for sleep and suspend are ignored

### General notes:

Observed this issue in both 3.2 and 4.0-rc4 when attempting to disable sleep and suspend

---

**Comment by awokd** [comment]
You may need to restart the daemon or just reboot before the settings changes will take effect.

**Comment by nathanhourt** [comment]
> You may need to restart the daemon or just reboot before the settings changes will take effect.

Restart which daemon?

**Comment by awokd** [comment]
In dom0's Screensaver preferences dialog, when you go to the File menu there's a Restart Daemon command. Not sure if that's the same one that handles system sleep, but a reboot will restart all of them!

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
