### ISSUE TITLE
KDE Desktop Settings lost on reboot

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#3676]
#### Qubes OS version:

3,2
4.0rc5

#### Affected component(s): 

Desktop decorations

---

### Steps to reproduce the behavior:

Install KDE
Set desktop Settings with Layout Desktop and Wallpaper set.
Shutdown

### Expected behavior:

Settings will be retained.

### Actual behavior:

Settings lost - Layout changed and wallpaper choice forgotten.
Reverts to default.

### General notes:

Multi-monitor setup.
Usually it is the Primary Display affected - the secondary seems to keep settings most of the time.

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
