### ISSUE TITLE
KDE - Some windows lack titlebar colour/qube name

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#3681]
#### Qubes OS version:

R3.2

#### Affected component(s): 

Desktop KDE

---

### Steps to reproduce the behavior:

Open an application

### Expected behavior:

Window titlebar will show qube name, and appropriate colour

### Actual behavior:

The application icon is coloured appropriately, but (particularly for disposableVMs) no qube name is shown.
In some cases the name appears.

### General notes:

Relevant: #2968

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
