### ISSUE TITLE
Device UI widget list of devices desync after backend VM shutdown

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3715]
I qvm-block-attached a device to a (disposable) qube. The device itself contained a number of logical volumes. These volumes were (correctly) showed on the widget list as available to attach to other qubes. Yet, after I shutdown the disposable (backend) qube, the list kept showing these logical devices.

Qubes 4.0, all latest from current.

**Comment by marmarek** [comment]
What exactly version of qubes-desktop-linux-manager package do you have? Something very similar was already fixed by https://github.com/QubesOS/qubes-desktop-linux-manager/pull/15, part of 4.0.7. You need to at least restart the widget after update (kill `python3 -mqui.tray.devices` process and start it again).

**Comment by rootkovska** [comment]
Ok, I still have 4.0.6, will try later.
