### ISSUE TITLE
Qubes 4.0-rc5 on MBP 13,2 boot into black screen

### ISSUE THREAD

**Issue by Ninlives** [QubesOS/qubes-issues#3723]
### Qubes OS version:

4.0-rc5

### Affected component(s): 

---

### Steps to reproduce the behavior:

1. Boot into the usb installer.(It ran graphical installer directly without showing the grub menu)
2. Install Qubes (I installed on an external ssd)
3. Reboot, hold option key and choose to boot into Qubes.

### Expected behavior:

Successfully reboot and boot into qubes.

### Actual behavior:

1. The installer didn't recognize the macbook's keyboard, have to use a usb keyboard.
2. Reboot after installation freeze the system. Have to manually power down the MacBook.
3. Boot into Qubes and I only got a black screen, nothing happens after that.

### General notes:

Using MacBook Pro late 2016, 13-inch with Touch Bar.
CPU: Intel Core i7
GPU: Intel Iris Graphics 550

Should I install rEFInd first or not? I have totally no idea about the root cause.

---

### Related issues:

https://github.com/QubesOS/qubes-installer-qubes-os/pull/20 
This pr seems to fix the issue of installation on MacBook. Does it compatible with my Mac?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
