### ISSUE TITLE
Lenovo X1 Carbon Gen 6 only creates bootable install when installer is booted with Legacy mode

### ISSUE THREAD

**Issue by Ranguvar** [QubesOS/qubes-issues#3733]
### Qubes OS version:

4.0-rc5

### Affected component(s): 

System boot after booting and running installer using UEFI boot

---

### Steps to reproduce the behavior:

Boot Qubes installer using UEFI _with or without_ CSM enabled.
Install, completely wipe target disk, no changes to settings beyond encryption.

### Expected behavior:

Successful boot of installed USB media.

### Actual behavior:

Attempt to boot USB using UEFI (CSM off/on) or Legacy mode - both return to the boot select screen after a second.

Boot Qubes installer using Legacy mode.
Created USB now boots.

### General notes:

I'm going to use Legacy boot to install to a USB and use Qubes like this, but it is annoying to switch between UEFI CSM off (for Windows and normal Linux) and Legacy for Qubes.

I did check to ensure the install media has the perfect checksum.

Please let me know if I can provide any relevant information.

---

**Comment by marmarek** [comment]
Are you installing to external USB? See https://www.qubes-os.org/doc/uefi-troubleshooting/#boot-device-not-recognized-after-installing

And better use qubes-users mailing list for this type of problems.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
