### ISSUE TITLE
3.2: playing music is too CPU demanding

### ISSUE THREAD

**Issue by h01ger** [QubesOS/qubes-issues#3741]
### Qubes OS version:

3.2

### Affected component(s): 

all

### Steps to reproduce the behavior:

play music, eg using mplayer, audio only. look at xentop on dom0. I see roughly 30% cpu usage in dom0 and 20% in the app VM (out of 400% available…)

I think that's way too much.

### Expected behavior:

maybe 10% cpu usage on both dom0 and app vm combined?

**Comment by tasket** [comment]
I used to get around 7-11% when using VLC or Totem (Gnome Videos) on R3.2. Its about the same on R4.0rc5. But when videos were played the usage is more than triple (which is expected).

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
