### ISSUE TITLE
On new install 4.0 rc5 volume sizes exceed available space

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#3744]
### Qubes OS version:

4.0 rc5

### Affected component(s): 

qubesd

---

### Steps to reproduce the behavior:

Install rc5.

### Expected behavior:

No qubesd warnings - possibly pools accomodate to available space.

### Actual behavior:

journal filled with qubesd warning:
Sum of all  thin pools exceeds size of thin pool and the size of whole volume group.
dmeventd 0 no longer monitoring thin pool qubes_dom0-pool00-tpool

### General notes:

I dont know how important this is, or whether the log entries are just a distraction.
The implication seems to be that the default install allocates more than the available space - since the stated minimum requirement remains 32 GB, isn't this going to cause problems?
If I've misunderstood what's happening here, close this and accept my apologies.
 

---

**Comment by tasket** [comment]
IIUC this is a standard effect of over-provisioning and can be ignored. But you'll notice that the "no longer monitoring thin pool" messages are immediately followed with "Monitoring thin pool...".

The only thing I don't get are the messages that follow stating "Thunar: Failed to launch the volume manager". Looks like a misconfiguration of `dmeventd` or related tool.

What must be done to safeguard against over-allocation is covered I think by issue #1872

**Comment by marmarek** [comment]
@tasket is right, over-provisioning here is expected (most of it is caused by snapshots of template's root for each VM started from it). Apparently there is no option to mute this warning, even in legitimate use cases:
https://bugzilla.redhat.com/show_bug.cgi?id=1347008
https://www.redhat.com/archives/linux-lvm/2016-April/msg00032.html

I'd like to avoid redirecting the whole stderr to /dev/null, to have logged relevant messages. Maybe some filtering `grep -v ...` style. It's messy.
