### ISSUE TITLE
Graphical Installer: Screen Flickering while manually partitioning or freeing disk space

### ISSUE THREAD

**Issue by diffusae** [QubesOS/qubes-issues#3747]
### Qubes OS version: 

R4.0rc5

### Affected component(s):  

Graphical Installer

---

### Steps to reproduce the behavior: 

Use GUI for manually partitioning

### Expected behavior:

 Should work as all other screens.

### Actual behavior: 

After a while screen begins to flicker.

### General notes: 

That only happens, if you choose manually partitioning.

---

### Related issues:

?

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

- This issue is on the "Release 4.0 updates" milestone.
- [Qubes OS 4.0 reached EOL (end-of-life) over one year ago.](https://www.qubes-os.org/news/2022/08/04/qubes-4-0-has-reached-eol/)
- There has not been any activity on this issue in over one year.

If anyone believes that this issue should be reopened and reassigned to an active milestone, please leave a brief comment.
(For example, if a bug still affects Qubes OS 4.1, then the comment "Affects 4.1" will suffice.)
