### ISSUE TITLE
Cannot execute qrexec-daemon! win7

### ISSUE THREAD

**Issue by Ersond** [QubesOS/qubes-issues#3773]
### Qubes OS version:

R3.2

### Affected component(s): 

HVM Standalone Win7

---

### Expected behavior:

qvm-start win7

### Actual behavior:

Not starting win7 in normal mode and in debug mode.

Getting error message in dom0 terminal: 
--> Starting the qrexec daemon...
Waiting for VM's qrexec agent..........................................
......................................................................................
Cannot connect to 'win7' qrexec agent for 300 seconds, giving
ERROR: Cannot execute qrexec-daemon!

### General notes:

Was working fine until i increased the disk size in the VM and in Windows 7 itself.
It was running fine even after i did the increase of disk, then it stopped to work.

state: stuck on yellow

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
