### ISSUE TITLE
Qubes Won't Run 

### ISSUE THREAD

**Issue by redblade8** [QubesOS/qubes-issues#3779]
Hi, I just bought a Dell Inspiron 15, 3000 series model 3567. Qubes wont boot, I just get a black screen & a flashing cursor after. It has an Intel Core i5 7200U processor with IOMMU & integrated intel hd graphics. Is it possible for Qubes to run on this system? Thanks! Its much appreciated. =)

### Qubes OS version:

3.2

### Affected component(s): 

---

### Steps to reproduce the behavior:

Boot from USB drive on legacy mode in bios. 

### Expected behavior:

Qubes booting to disk password screen then the main user login screen.

### Actual behavior:

Black screen. Flashing cursor.

### General notes:

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
