### ISSUE TITLE
missing amdgpu firmware for Raven Ridge APU

### ISSUE THREAD

**Issue by coeusite** [QubesOS/qubes-issues#3796]
### Qubes OS version:

R4.0

### Affected component(s): 

- kernel / linux-firmware
- gpu / display

---

### Steps to reproduce the behavior:

- ```ls /lib/firmware/amdgpu/```

### Expected behavior:

list some ```raven_*.bin``` files

### Actual behavior:

no ```raven_*.bin```

### General notes:

- the ```linux-firmware``` package is just too old to support Raven Ridge APU
- Fedora 25 is end of life since last December, and it seems to be the reason
- kernel 4.15 and above will recognize Raven Ridge APU, which may leads to further issues
- kernel 4.14, on the other hand, does not recognize the GPU so that it works as normal

so...is it possible to upgrade dom0 to fedora 26/27 officially?

---

### Related issues:

This may related to issue #3790

**Comment by Aekez** [comment]
@coeusite @andrewdavidwong 
I think this has changed since 7th april, but there is currently a newer linux-firmware package in the Qubes unstable repository which is quite new and includes the Raven drivers, it should do the trick? If you want to verify before installing the RPM, you can check by opening the RPM package and unpack into Tar.gz, which again can be unpacked to normal folder structures. Then you're free to check and inspect if the Raven binaries are inside or not. It should be inside. You can browse the download here https://yum.qubes-os.org/r4.0/unstable/dom0/fc25/rpm/ or install with `sudo qubes-dom0-update --enablerepo=qubes-unstable linux-firmware`

The firmware doesn't appear to fix the other additional issues on some (all?) Ryzen APU systems though, however on-going issues that happen after updating the firmware can be found in the issue https://github.com/QubesOS/qubes-issues/issues/3790
