### ISSUE TITLE
template update won't use proxyVM

### ISSUE THREAD

**Issue by coeusite** [QubesOS/qubes-issues#3819]
### Qubes OS version:

R4.0

### Affected component(s): 

- templates
- global settings

---

### Steps to reproduce the behavior:

- update template Debian 9

### Expected behavior:

I can choose whether template update traffics will go through a proxyVM or not.

### Actual behavior:

there is no such option, and the updateVM is only for dom0. 
templateVMs will directly update through the clear net.

Currently templateVMs can update while the updateVM is down.

### General notes:

The problem for me is that template update processes fail frequently due to my ISP, thus I need to update template behind a proxyVM in some degrees.

Additionally, I do think certain people would like hide these processes from their ISPs due to privacy concerns.

---

**Comment by andrewdavidwong** [comment]
Possibly related: #3702

**Comment by jsmaniac** [comment]
It seems that template updates are hardcoded to use the VM `sys-net`. I tried successfully to have the following network configuration:

```
some-template-vm ~~~> sys-net (the update-vm, actually) → sys-firewall → sys-ethernet (formerly called sys-net) → actual hardware
```

To get this, I renamed via the GUI the original `sys-net` to `sys-ethernet`, make sure that `sys-firewall` points to `sys-ethernet` using

```
qvm-prefs --set sys-firewall netvm sys-net
```

and renaming using the GUI my `update-vm` to `sys-net`, with the following settings:

```
qvm-service --enable sys-net clocksync
qvm-service --enable sys-net qubes-updates-proxy
qvm-prefs --set sys-net provides_network True
qvm-prefs --set sys-net netvm sys-firewall
```

It is necessary to enable `qubes-updates-proxy`, otherwise templates will not be able to use that VM to download updates. The clocksync and provides_network features might not actually be necessary, but I didn't test without.
