### ISSUE TITLE
Macbook Pro (Retina, 13-inch, Early 2015): QubesOS R4.0 installer doesn't use existing /dev/sda1 EFI System Partition

### ISSUE THREAD

**Issue by pruflyos** [QubesOS/qubes-issues#3823]
### Qubes OS version:

R4.0

### Affected component(s): 

Qubes OS R4.0 Installer

---

### Steps to reproduce the behavior:

- flashed Qubes-R4.0-x86_64.iso using Etcher (https://etcher.io)
- freed (50GB) at the end of my Macbook's disk
- **did not install** `rEFInd`. R4.0 should work with the standard UEFI manager (holding down option key) as well, right???
- plug-in USB thumb drive and hold down option key during boot
- select `EFI Boot`
- screen goes dark but after waiting 20 seconds Qubes 4.0 installer starts fine
- in the installer overview: keep the default `automatic partitioning`
- begin installation

### Expected behavior:

- /dev/sda1 (EFI System Partition) should have been mounted to /boot/efi
- Qubes entry should have been added to /dev/sda1

### Actual behavior:

For some reason the Qubes installer creates a new 200MB EFI partion (/dev/sda6 in my case) and creates a Qubes entry in this partition:
```
INFO program: Running... efibootmgr -c -w -L Qubes -d /dev/sda -p 6 -l \EFI\qubes\xen.efi
```
Of course, my Macbook isn't able to boot Qubes after I finish installation and hold down the Option key, because the Macbook EFI manager looks in /dev/sda1 for available systems, but Qubes was added to /dev/sda6.

And that's exactly what's happening, after qubes installation is complete and I reboot my Macbook while holding down the Option key, Qubes is not shown as an option. I can't boot the installed Qubes 4.0.

### General notes:

- /dev/sda1 still has 169M of free space on my system, so that can't be the reason why the Qubes installer isn't using it. The EFI partition the Qubes installer creates (/dev/sda6) only uses 66M after installation is finished. So this would fit on /dev/sda1, no need to create a new EFI partition, right? Or is there another reason?

---

### Related issues:

- https://github.com/QubesOS/qubes-installer-qubes-os/pull/20
- https://github.com/QubesOS/qubes-issues/issues/3784

**Comment by pruflyos** [comment]
> Does this bug affect people erasing the entire disk and starting anew?

When you erase the entire disk, Qubes 4.0 doesn't boot after installation. I guess the issue is the following:
Qubes installer creates a 200MB partition for UEFI of type `Standard Partition` with `Linux HFS+ ESP` as the file system.
Ubuntu 18.04 on the other hand (which boots fine after installation) creates a 512MB partition using `EFI System Partition` as the file system.
If I try to replicate the Ubuntu layout using `manual partitioning` in the Qubes 4.0 installer, it won't let me install and complains with:
```
Error checking storage configuration.

No vaild boot loader target device found. See below for details.
For a UEFI installation, you must include and EFI System Partition an a GPT-formatted disk, mounted at /boot/efi.
```

So I guess this is a bug. Although I manually created a partition of type `EFI System Partition` and set the mount point to `/boot/efi` I get the above error and can't install. And the automatic partitioning uses the wrong file system type so Qubes 4.0 installs but won't boot.

So neither automatic partitioning nor manual partitioning lead to a bootable Qubes on a Macbook Pro 2015.

**Comment by eduncan911** [comment]
> Of course, my Macbook isn't able to boot Qubes after I finish installation and hold down the Option key, because the Macbook EFI manager looks in /dev/sda1 for available systems, but Qubes was added to /dev/sda6.

That's not exactly correct.  With Sierra and High Sierra, macOS scans all HFS+ partitions on the system for EFI files that have been `bless`ed, and displays them.  I have actually tested a system with 3 USB bootsticks (some "blessed", others not) along with a dual boot system - all 5 EFI partitions across 4 drives all showed up under "OPTION" key hold.

As far as Qubes creating the proper partitioning schema, R4.0rc5 and confirmed with R4.0 RTM both default to creating a new EFI partition for macos (according to the Anaconda python installer).  Not the most efficient; but, we didn't want to re-invent the wheel so late into the RC releases to get it RTM.  

But do note, that's a macOS-specific thing - not a Macbook.  And technically Qubes isn't support on mac hardware anyways (I've had a heck of a time getting a fully functional system working on any of my Apple devices - and I have several 2014, 2015, 2016 model iMacs and Macbook Pros).

For all of my tests, I never have wiped the local disk - I left it intact and always wiped a USB HDD I installed Qubes on.  

I've since shelled out the change for a Thinkpad and no longer spend time on Qubes with Apple devices.

If anyone would like to help, I can help give pointers as to where to start:

* Have a machine ready for multiple (dozens) of wipes, partial installs, dual-booting, etc
* `git clone` this repo: https://github.com/QubesOS/qubes-installer-qubes-os
* Review my last PR here where I was modifying the parts for macOS detection and boot: https://github.com/QubesOS/qubes-installer-qubes-os/pull/20
* Create a small 50 MB partition on your local drive, to use to move files back and forth to and from to make things easier (if coding on the same machine, like I was)

To make changes (which is the most time consuming part):

* Use Etcher to create a USB boot stick from the normal R4.x RTM ISO (or even 4.1 RCs now)
* Boot the installer (which will verify the USB stick), but don't click any buttons. You want to switch to console. I think it was alt-5, 6 or or something like that.  They use Tmux!, but I think they changed the default keybindings.  May need to peak at the .tmux.conf and see what changes windows.
* Now, with the installer started and waiting for your input, and you have switched to a console, now you can copy your modified files to override the anaconda ones.
* alt-1/alt-f1 or something to get back to the Anaconda UI and continue the installer normally, with your modified files.

Rinse and repeat, but every change.  Yeah, it's a PITA.  The only other option is to build a new ISO each and every time after a modification - and burn that one over and over.  I preferred to the manual copy as it didn't kill my USB sticks, like burning an ISO would dozens of times over.

Technically, we still need the macOS detection part - but only for the `bless` commands for the HSF+ partition.  I wanted to remove a lot of the duplicate EFI code and merge it with other EFI patterns in this file.  

Lastly, there is a lot of hardcoding here that I wanted to abstract to values.

**Comment by andrewdavidwong** [comment]
> But I think this is normal for all of Qubes as Qubes does not support dual-booting and highly advises against it (as booting another OS can compromise the rest of the system, hardware, firmware, etc).  **So the want of installing to an existing `/dev/sda1` is not valid here.**  Instead, Qubes just creates another EFI partition.  @andrewdavidwong perhaps we can close the issue since that is out of scope?

@marmarek, can you confirm that this is working as intended?

**Comment by marmarek** [comment]
While it indeed isn't advisable to dual-boot Qubes and something else, it is supported configuration. And it should be possible to make Qubes use existing EFI partition. Just the installed doesn't do that by default (I think).
The behavior @pruflyos describe indeed sounds like a bug. It's interesting that this happens specifically on Mac devices, as on other machines EFI partition is correctly created as EFI System partition. 
@pruflyos can you provide full `fdisk -l /dev/sda` and/or `gdisk -l /dev/sda` output?
