### ISSUE TITLE
Unable to start imported Windows 7 image

### ISSUE THREAD

**Issue by kaspro** [QubesOS/qubes-issues#3838]
### Qubes OS version: 4.0
Newby to QubesOS, so I'm not too versed to the specific tools or config files - please forgive if I should've overseen something:

I (tried to) follow the explanations [here](https://www.qubes-os.org/doc/windows-appvms/) - mixed with [these](https://www.qubes-os.org/doc/hvm/) as the creation changed for 4.0 - but ran into the following issues:
* "sudo qubes-dom0-update qubes-windows-tools" doesn't exist - I suppose it's included in 4.0
* creation works as per second link
* then, I imported my own raw image (copying it into /var/lib/qubes/appvms/mywin7/root.img, as well as tried the import of the MS 90 day eval image as described (just in case there was something wrong with mine).
* upon starting, the machines comes up with "No bootable device"

I started the machine successfully with live- CDROMs, but they won't see any other Harddrives - so I suppose there is some config value missing - which I don't know where to find.
Also, some issues mention a config file in the same directory - there's none created at vm creation.

Thanks in advance for any help,
Regards Chris

### Affected component(s): 
qvm-create
qvm-run
qvm-start

### Steps to reproduce the behavior:
qvm-create win7 --class StandaloneVM --property virt_mode=hvm --property kernel="" --property memory=4096 --property maxmem=4096 --property debug=True --label green
qvm-features win7 video-model cirrus
qvm-run --pass-io untrusted 'cat "/media/user/externalhd/win7.raw"' > /var/lib/qubes/appvms/win7/root.img
qvm-start win7

### Expected behavior:
Windows is being started successfully

### Actual behavior:
Boot fails with "No bootable device"

### General notes:
-

**Comment by andrewdavidwong** [comment]
You might want to take a look at #3592 if you haven't already done so. I don't know whether it'll help in your case, but it's at least worth a look.

**Comment by kaspro** [comment]
Thanks for mentioning it - I have seen this, but used all the options mentioned there for first startup (and double- checked with "qvm-prefs win7" - unfortunately it didn't help.

**Comment by taradiddles** [comment]
> qvm-create win7 --class StandaloneVM --property virt_mode=hvm --property kernel="" --property memory=4096 --property maxmem=4096 --property debug=True --label green
> [...]
> qvm-run --pass-io untrusted 'cat "/media/user/externalhd/win7.raw"' > /var/lib/qubes/appvms/win7/root.img

this won't work because qubes 4.0 uses LVM, not image files; so you first have to copy your image file to dom0 (let's say in /home/user/win7root.img) and then use qvm-create's `--root-move-from /home/user/win7root.img` (or `--root-copy-from` if you want to keep the image).

Something like this:

~~~
qvm-run --pass-io untrusted 'cat "/media/user/externalhd/win7.raw"' > /home/user/win7root.img
qvm-create --class StandaloneVM --label green  --property virt_mode=hvm --property memory=4096 --property maxmem=4096 --property debug=True --root-move-from /home/user/win7root.img win7new
~~~

**Comment by kaspro** [comment]
Yes this works - at least for the import of the root image.
Obviously, the storage driver is different now to a qemu-kvm: is there any driver I can install (and where from, as the qubes-windows-tools don't exist) to get the system booting again?

**Comment by taradiddles** [comment]
If your own VM image works on another machine, maybe try to set the storage drivers to plain IDE and see if you manage to boot it in qubes. Or maybe boot from the CD and try to repair the install. You can also post to the qubes-user ML and see if someone has a solution.

FWIW I always end up re-installing windows from scratch because importing windows images between different virtualization implementations is always a PITA  - that's not specific to Qubes OS.

By the way, see issue #3585 for QWT on 4.0

**Comment by kaspro** [comment]
Thanks Ivan, I ended up re-installing - after 2 hours of fiddling it didn't seem to be worth the time, as nothing really worked out.

**Comment by taradiddles** [comment]
Hi kaspro,
Sorry to read it didn't work out. If you re-try to install windows in the future, please send some feedback about the documentation (= where it doesn't work for you) so that I can improve it.

**Comment by kaspro** [comment]
Honestly, I mixed all a bit - as I'm a lazy typer, I combined the instructions from 3.2 with 4.0 and then kinda followed #3592. 

> The official doc has separate 3.2 / 4.0 sections (as per Qubes doc guidelines), with links on the right.

I wasn't aware of that part of the Guidelines - I would put at least a link at the top for 3.2, 4.0 and QWT on 4.0? But that's just me :)

> It's already in the official doc

You're right - I guess I've been reading too much between articles!

30GB should be fine, then there's still a bit margin for error, or some basic tool- installation like AV etc. (e.g. I got Firefox and an AV product on there, getting me to ~28.3GB).
