### ISSUE TITLE
Attach/Detach audio-input to Qube

### ISSUE THREAD

**Issue by qubesissues** [QubesOS/qubes-issues#3845]
### Qubes OS version:
4.0

### Affected component(s): 

Qube Manager and individual Qubes

---

### Steps to reproduce the behavior:

Try to attach audio to a qube.  I dare you.

### Expected behavior:

In 3.2 in the "VM Manager you could right-click on a VM, then choose:

`Attach/detach audio-input to the VM`

Also there was a microphone icon in the Vm Manager.

Those were great.

### Actual behavior:

If there is a way to attach audio to a Qube I do not see it.

### General notes:

---

**Comment by mirrorway** [comment]
Maybe I am misunderstanding, but under the USB applet do you not have a microphone you can attach to a VM?

**Comment by qubesissues** [comment]
@mirrorway Yes!  Thank you.

**Comment by andrewdavidwong** [comment]
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by qubesissues** [comment]
I do not see how this is resolved.  @mirrorway found a workaround.  But there is still a bug in the Qubes Manager as described in the issue report.

**Comment by andrewdavidwong** [comment]
Reopened and unmarked as resolved.

Here's how I interpreted the exchange above as indicating that issue was resolved:
1. @qubesissues reported that there is no way to attach an audio input device to a qube.
2. @mirrorway pointed out a way to attach an audio input device to a qube.
3. @qubesissues confirmed that @mirrorway's method worked.
4. Since the problem was that there seemed to be no way to attach an audio input device to a qube, but there turned out to be a way after all, I interpreted the issue as resolved.

> I do not see how this is resolved. @mirrorway found a workaround. But there is still a bug in the Qubes Manager as described in the issue report.

If I understand correctly, the idea is that the ability to attach an audio input device to a qube should not only be available in the USB/Storage applet in the notification area; it should also be available from the monolithic Qubes Manager window. Is that correct?

This might be a case where the audio input functionality is intended to be "decomposed" (i.e., moved) out of the monolithic Qubes Manager and into the the USB/Storage applet in the notification area, but I'll leave that for @marmarek and @marmarta to decide.

**Comment by marmarek** [comment]
> This might be a case where the audio input functionality is intended to be "decomposed" (i.e., moved) out of the monolithic Qubes Manager and into the the USB/Storage applet in the notification area, but I'll leave that for @marmarek and @marmarta to decide.

Yes, exactly, this is the case. Qube Manager in 4.0 is about _static/persistent_ configuration.
