### ISSUE TITLE
install qubes-usb-proxy in default templates or change documentation to reflect

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#3866]
### Qubes OS version: 

R4.0

### Affected component(s): 

default templates: Debian 9, Whonix-workstation

Fedora 26 template has it installed by default.

---

### Steps to reproduce the behavior:

attempt any activities that require `qubes-usb-proxy` and get error that it is not installed (or get silent fail if using GUI).

### Expected behavior:

`qubes-usb-proxy` is installed in these default templates or change documentation to reflect this. In [the documentation](https://www.qubes-os.org/doc/usb/#installation-of-qubes-usb-proxy) it says: "`qubes-usb-proxy` should be installed by default in the template VM".

### Actual behavior:

Debian 9 and Whonix-workstation do not have it installed by default.

### Related issues

This is an example where [better tracking of installed packages in default templates](https://github.com/QubesOS/qubes-issues/issues/1781) may be helpful.

**Comment by unman** [comment]
@marmarek @andrewdavidwong  @mfc  The documentation here is completely inconsistent, since it says _both_ that you need to install the package _and_ that it's installed by default. 
I've always been content with it not being installed by default, and hadn't realised it was included in Fedora, but we should be consistent between the distros.  Which way shall we go?

**Comment by dmoerner** [comment]
I want to put in a vote for installing this in all templates. Some software (e.g., tails-installer) expects that USB devices be available as /dev/sdX, not /dev/xvdX, so qubes-usb-proxy must be installed by hand.
