### ISSUE TITLE
1024x780 max resolution on Asus RS500A

### ISSUE THREAD

**Issue by 0pcom** [QubesOS/qubes-issues#3879]
### Qubes OS version:

4.0

### Affected component(s): 

Display, resolution, missing modes

---

### Steps to reproduce the behavior:

Fresh install has only this and two lower resolutions
Probably Specific to my hardware- ASUS RS500A workstation
Have not experienced this with another qubes install using the same monitor.

### Expected behavior:

Resolution should be at least 1280x1024.
The monitor and onboard VGA graphics are both capable of higher resolutions

The low resolution itself isn't too hard to live with,
however, some VMs try to display at a higher resolution
which pushes the bottom of the window off the edge of the screen.

### Actual behavior:

1024x786 maximum available resolution

### General notes:

Unsure where to find the configuration file in dom0 where I could possibly add 1280x1024 resolution mode. Insights appreciated.

I also suggest that the default behavior should be to limit the resolution of VMs to less than that of the physical display.

**Comment by andrewdavidwong** [comment]
> I also suggest that the default behavior should be to limit the resolution of VMs to less than that of the physical display.

I'd think most users would want the option of displaying a fullscreen window with exactly the same resolution as they physical display.

**Comment by 0pcom** [comment]
Sorry I meant to say limit the resolution of VMs to *not more than* that of the physical display.

I managed to add the modeline with xrandr but this does not survive reboot.

**Comment by Cognomines** [comment]
First thing I noticed when I booting usb into Xen+linux dom0 on qubes os iso in efi mode ... kill the computer it **relinquished graphics**. Then I booting Xen + linux dom0 on qubes iso in legacy mode graphics display fine. My computer bios likes to change settings on the fly when it automagically detects and changes settings. I delete the lvm logical volume: /dev/mapper/lvroot-mainvolume. I rename the volume group lvroot to vgroot because lvroot is a misnomer.Then I run the qubes installer giving it a 100GiB on a new logical volume existing on the renamed volume group vgroot to be lvm:/dev/mapper/vgroot-qubes. Grub install phase fails when installing after qubes os files are installed onto lvm: /dev/mapper/vgroot-qubes(100G). I opened up a TTY in order to chroot into the previous os install on a the different lvm: /dev/mapper/vgroot-bedrock. I install grub on the old os again because the qubes installation failed. I boot into archlinux but the first thing I notice is the display on the monitor is totally downscaled to some 1024 times some other 32 multiple.  Then you come down and I show you xrandr not showing the max native resolution of the DVI-D-1 not allowed to be 1600x1050 but instead of that ugly 1024x(multiple of 32) resolution.

I test with nvidia drivers and with nouveau drivers. Both monitors work during graphics usage on OS with nvidia with one being at lower resolution but the monitor with the EDID issue does not work with nouveau drivers. I notice a blank monitor with nouveau and not a max resolution for my ACER monitor (AL2216W model number). Then I came across this error in linux device messages on archlinux. I only run into issues when running after using qubesOS. 

```bash
# dmesg | grep -i nouveau
[    5.036121] fb0: switching to nouveaufb from EFI VGA
[    5.036217] nouveau 0000:09:00.0: vgaarb: deactivate vga console
[    5.036261] nouveau 0000:09:00.0: NVIDIA GK107 (0e7060a2)
[    5.152751] nouveau 0000:09:00.0: bios: version 80.07.35.00.04
[    5.153733] nouveau 0000:09:00.0: fb: 1024 MiB GDDR5
[    5.844640] nouveau 0000:09:00.0: DRM: VRAM: 1024 MiB
[    5.844644] nouveau 0000:09:00.0: DRM: GART: 1048576 MiB
[    5.844647] nouveau 0000:09:00.0: DRM: TMDS table version 2.0
[    5.844649] nouveau 0000:09:00.0: DRM: DCB version 4.0
[    5.844651] nouveau 0000:09:00.0: DRM: DCB outp 00: 01000f02 00020030
[    5.844653] nouveau 0000:09:00.0: DRM: DCB outp 01: 02011f80 00000000
[    5.844654] nouveau 0000:09:00.0: DRM: DCB outp 02: 08011f82 00020030
[    5.844656] nouveau 0000:09:00.0: DRM: DCB outp 03: 02022f62 00020010
[    5.844657] nouveau 0000:09:00.0: DRM: DCB conn 00: 00001031
[    5.844658] nouveau 0000:09:00.0: DRM: DCB conn 01: 00000100
[    5.844660] nouveau 0000:09:00.0: DRM: DCB conn 02: 00010261
[    5.847786] nouveau 0000:09:00.0: DRM: MM: using COPY for buffer copies
[    5.849378] snd_hda_intel 0000:09:00.1: bound 0000:09:00.0 (ops nv50_audio_component_bind_ops [nouveau])
[    6.021527] nouveau 0000:09:00.0: DRM: DDC responded, but no EDID for DVI-D-1
[    6.157463] nouveau 0000:09:00.0: DRM: allocated 1920x1200 fb: 0xa0000, bo 00000000e1acb414
[    6.157535] fbcon: nouveau (fb0) is primary device
[    6.197278] nouveau 0000:09:00.0: [drm] fb0: nouveau frame buffer device
[    6.207516] [drm] Initialized nouveau 1.3.1 20120801 for 0000:09:00.0 on minor 0
[    6.711528] nouveau 0000:09:00.0: DRM: DDC responded, but no EDID for DVI-D-1
[    6.989081] nouveau 0000:09:00.0: DRM: DDC responded, but no EDID for DVI-D-1
[   15.709613] nouveau 0000:09:00.0: DRM: DDC responded, but no EDID for DVI-D-1
[   16.590186] nouveau 0000:09:00.0: DRM: DDC responded, but no EDID for DVI-D-1
[   17.901369] nouveau 0000:09:00.0: DRM: DDC responded, but no EDID for DVI-D-1
```

This may be the fix of the problem caused by something else but is not the fix of the root cause: 
Then I duckduckgo to this interesting [Superuser link](https://superuser.com/questions/960416/laptop-screen-blank-kernel-log-full-of-edid-errors). I have not found exactly the root cause of this but I have diagnosed an [EDID error](https://www.extron.com/article/uedid) on my computer monitor. My monitor resolution no longer shows it max size. 

Please carefully diagnose your monitor without bricking any computer hardware. Please try to diagnose what is wrong with the root cause. I am not sure if this is a Xen or Qubes gui domain issue but it leaves my computer monitor in a state that is ugly. I am not also aware of using Qubes because I have failed to install the latest version as of 9/17/21.
