### ISSUE TITLE
qubes-template-whonix-gw should depend on qubes-core-admin-addon-whonix

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3881]
`qubes-template-whonix-gw` should depend on `qubes-core-admin-addon-whonix`?
`qubes-template-whonix-ws` should depend on `qubes-core-admin-addon-whonix`?

Where to declare such a dependency?

([T792](https://phabricator.whonix.org/T792))

----

Related:

* https://github.com/QubesOS/qubes-issues/issues/3595
* https://github.com/QubesOS/qubes-core-admin-addon-whonix
* https://forums.whonix.org/t/qubes-core-admin-addon-whonix-for-qubes-r4-testers-wanted

**Comment by marmarek** [comment]
By design template packages should not have any additional dependencies as a way for installing dom0 packages. This is especially relevant in R4.0, where you can install template package in some Mgmt VM (the template will be transferred to dom0 using Admin API automatically, if policy allows).
Such dependency can be added to a package with whonix salt formulas (qubes-mgmt-salt-dom0-virtual-machines). There is no separate package for whonix formulas, but since the common one include whonix, IMO it's ok to carry also whonix-related dependencies.
Alternatively, this could be added to relevant [package group](https://github.com/QubesOS/qubes-installer-qubes-os/blob/master/conf/comps-qubes.xml#L1422-L1432), but this could be not picked up during upgrade, so IMO not such a good idea.

**Comment by adrelanos** [comment]
Since this was merged, this ticket was solved. Therefore closing.
