### ISSUE TITLE
Improve handling of services in Qubes Manager

### ISSUE THREAD

**Issue by qubesissues** [QubesOS/qubes-issues#3891]
### Qubes OS version:
4.0

### Affected component(s): 

Qubes Manager

---

### Steps to reproduce the behavior:

Create a new Qube.  Go to its details and click "Services"

### Expected behavior:

I expect to see network-manager like they talk about here:
https://www.qubes-os.org/doc/vpn/

### Actual behavior:

No services are listed.  Manually typing network-manager and hitting "enter" makes the Settings window crash.  Manually typing network-manager and hitting Plus Sign makes network-manager show up but you can type any word and hit Plus and it will show up so what is really happening?

### General notes:

---

**Comment by donob4n** [comment]
I think this is wrong for Qubes 4. sys-net and sys-firewall do not have 'network-manager' service.

Did you select 'provides network' when creating the Qube?

**Comment by donob4n** [comment]
What I meant is probably 'network-manager' service does not exist in Qubes 4, since sys-net has the network applet but It has not the service.

**Comment by marmarek** [comment]
> No services are listed.

This is correct, you need to add this entry as you described.

> Manually typing network-manager and hitting "enter" makes the Settings window crash.

"Enter" here accepts all the settings (as you hit "OK"). This will be fixed in upcoming update - see linked pull request.

> Manually typing network-manager and hitting Plus Sign makes network-manager show up

This is how you should add network-manager service there.

> but you can type any word and hit Plus and it will show up so what is really happening?

That's correct. You can find a list of services in documentation ([3.2](https://www.qubes-os.org/doc/tools/3.2/dom0/qvm-service/), [4.0](https://dev.qubes-os.org/projects/core-admin-client/en/latest/manpages/qvm-service.html)), but you can also [create your own](https://www.qubes-os.org/doc/qubes-service/) (or install other packages handling other names there) - that's why it's possible to add any entry there.

**Comment by andrewdavidwong** [comment]
Reopening as a UX enhancement issue.

> > Manually typing network-manager and hitting Plus Sign makes network-manager show up
> 
> This is how you should add network-manager service there.

IMHO, there should be some way to discover available services and select from them instead of having to know the name or look it up from an external source and type it in manually.

> > but you can type any word and hit Plus and it will show up so what is really happening?
> 
> That's correct. You can find a list of services in documentation (3.2, 4.0), but you can also create your own (or install other packages handling other names there) - that's why it's possible to add any entry there.

IMHO, we should distinguish between:
1. Giving the user the ability to enter arbitrary names of possible services.
2. Presenting the complete list of arbitrary user inputs as if it were the actual list of services.

1 is fine, but 2 is not. If possible, the system should present the actual list of services. If the list isn't validated, a simple typo would mean that the intended service doesn't get used.

**Comment by qubesissues** [comment]
> IMHO, there should be some way to discover available services and select from them instead of having to know the name or look it up from an external source and type it in manually.

Yes this would solve the Issue.

**Comment by marmarta** [comment]
There is no way to actually list all available services, but perhaps we could show a list of suggestions (as man qvm-services displays).
