### ISSUE TITLE
Documentation is unclear about how to configure a single AppVM application shortcut involving qvm-run and qubes.StartApp

### ISSUE THREAD

**Issue by heinrich-ulbricht** [QubesOS/qubes-issues#3899]
### Qubes OS version:

R4.0

### Affected component(s): 

[Documentation about shortcuts to AppVM applications](https://www.qubes-os.org/doc/managing-appvm-shortcuts/) (and some RPC service info)

---

### Expected behavior:

I have an app saved to one AppVM home directory that is not automatically included in the list of available apps in this AppVM's menu - which is ok and expected. I now want to add a shortcut to this app by following the [instructions of the official documentation](https://www.qubes-os.org/doc/managing-appvm-shortcuts/#what-if-my-application-has-not-been-automatically-included-in-the-list-of-available-apps).

Unfortunately, reading this documentation I was not able to achieve the following (but should be):

* creating a shortcut to an application in a __single__ AppVM as advertised [here](https://www.qubes-os.org/doc/managing-appvm-shortcuts/#what-if-my-application-has-not-been-automatically-included-in-the-list-of-available-apps)
* using a *.desktop* file that resides inside this single AppVM
* referencing this *.desktop* file using *qvm-run* (with *qubes.StartApp service*) from dom0 as described in the [Behind the scenes](https://www.qubes-os.org/doc/managing-appvm-shortcuts/#behind-the-scenes) section of the documentation

As a technical user with no Linux background I should be able to configure this. I'm sure I made mistakes on my way and I'd like to improve the documentation so that people like me can get it running :)

### Actual behavior:

[Here](https://www.qubes-os.org/doc/managing-appvm-shortcuts/#what-if-my-application-has-not-been-automatically-included-in-the-list-of-available-apps) the section *If you only want to create a shortcut for a single AppVM, you can create a custom menu entry instead* describes, how to add an application as shortcut by doing things entirely in dom0 while referring to *qvm-run* in the [Behind the scenes](https://www.qubes-os.org/doc/managing-appvm-shortcuts/#behind-the-scenes) section which says I can refer to a *.desktop* file in my AppVM. But exactly how to do this was not entirely clear to me.

My questions about these instructions are:
 
* Is it really ok to modify `~/.config/menus/applications-merged/<vmname>-vm.menu` in dom0? It feels odd (for a newbie to the os) for several reasons:
  * There are no _\<vmname\>-vm.menu_ files (the docs refer to them) in this folder, but rather _**user-**\<vmname\>-vm.menu_ files - should I modify those instead?
  * The folder name *applications-merged* suggests the files in there are auto-generated and will be overwritten at some point - are my changes really persisted? Do I have to re-apply them after synchronizing shortcuts between VMs? I think it even says in the *.menu* files that these were auto-generated and that they shouldn't be touched, yet the documentation says to do so.
* In which folder do I have to place the *.desktop* file in the AppVM so it can be called via *qvm-run* and *qubes.StartApp* from dom0?
* While trying things I suspected my call to the _qubes.StartApp_ service was wrong - how to debug this? Is *qubes.StartApp* documented somewhere? I found a list of services [here](https://www.qubes-os.org/doc/qrexec3/), not including *qubes.StartApp*.
  * Specifically in the string *qubes.StartApp+**firefox*** (this is from a sample in the docs) - is _firefox_ the name of the _.desktop_ file (without ending) in the AppVM? Bonus question: how does this handle spaces in the filename; what's the syntax?
  * Is it even necessary to create a .desktop file in the AppVM? Can the binary of the app be referenced as well?

### General notes:

With above questions clarified I can verify that my configuration is either wrong or correct and then file a technical issue if still necessary.

Any information or links to additional documentation I might not have been able to find are appreciated.

**Comment by heinrich-ulbricht** [comment]
I found my answers in https://github.com/QubesOS/qubes-core-agent-linux/commit/22e261f9095f2d6f4f1b67533c20b9a0e18459a2 which added the service _qubes.StartApp_. To make my scenario work you have to do the following:

1. create a _.desktop_ file in the AppVM (in my case _vault_) in _/home/user/.local/share/applications_
   - create the _applications_ folder if it doesn't yet exist
2. in a dom0 terminal create a _.desktop_ file in _~/.local/share/applications_ as described [in the docs](https://www.qubes-os.org/doc/managing-appvm-shortcuts/#what-if-my-application-has-not-been-automatically-included-in-the-list-of-available-apps)
   - the _Exec_ value can now reference the _.desktop_ file in the AppVM, e.g.: `Exec=qvm-run -q -a --service -- vault qubes.StartApp+keepass`, where _keepass_ is the name of the file created in step 1 (_keepass.desktop_) without its ending
3. still in dom0 terminal edit the _user-\<vm name\>-vm.menu_ file in _~/.config/menus/applications-merged_ as described [in the docs](https://www.qubes-os.org/doc/managing-appvm-shortcuts/#what-if-my-application-has-not-been-automatically-included-in-the-list-of-available-apps) (but note the _user-_ prefix that is missing in the docs)
   - this warning in the file can apparently be ignored: _Do not edit manually - generated and managed by xdg-desktop-menu_ ...
   - these manual changes stay in this file also after calling `qvm-sync-appmenus fedora-26`

The reason it didn't work in my case was completely unrelated to any of this. In my AppVM _.desktop_ file I had errors in the _Exec_ value. To test and debug this you can call `qubes-desktop-run` in the AppVM to invoke your _.desktop_ file directly. This is what _qubes.StartApp_ does under the hood.

**Comment by AlmightyLaxz** [comment]
Hi,

Here are the steps I have tested to create a shortcut to an app in a single AppVM on R4.0.

In dom0:
1. `cd ~/.local/share/applications`
2. Create new .desktop - should be named vmname-appname.desktop (make up an appname), copying vmname-firefox.desktop is a good starting point
It should look like this:

[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
X-Qubes-VmName=vmname
Icon=/home/user/.local/share/qubes-appmenus/personal/apps.icons/firefox.png
Name=vmname: appname
GenericName=vmname: some name, can be appname again
Comment=whatever
Categories=Network;X-Qubes-VM;
Exec=qvm-run -q -a -- vmname 'path to application e.g. /home/username/myapp'
X-Qubes-DispvmExec=qvm-run -q -a --dispvm=vmname -- 'path to application again'

3. Edit `~/.config/menus/applications-merged/username-vmname-vm.menu` , add filename line into include section: `<Filename>vmname-appname.desktop</Filename>` filename should be the one created in step 2
4. Done

New shortcut seems to survive appmenu refreshes.

> Is it really ok to modify ~/.config/menus/applications-merged/<vmname>-vm.menu in dom0? It feels odd (for a newbie to the os)

Adding an application to a single AppVM is not really supposed to be done as applications are intended to all be installed inside TemplateVMs or standalone AppVMs. I think this method is unfriendly because it breaks from that design.

> In which folder do I have to place the .desktop file in the AppVM so it can be called via qvm-run and qubes.StartApp from dom0?

A .desktop file inside the AppVM isn't needed for this and would likely not work, the qubes.StartApp service reads .desktops from the AppVM's `/usr/share/applications` folder (I think). Because it is an AppVM, this folder would be cleared each time the VM is restarted.

> Can the binary of the app be referenced as well?

In my above example of qvm-run the --service flag is removed, which means the command passed is a shell command instead of an Admin API service, so use the path to the application.

**Comment by heinrich-ulbricht** [comment]
I'm now using a different approach to creating shortcuts for specific AppVMs:

1. in your AppVM make sure there is a _.desktop_ file as described in my last comment - this is going to be called
1. in a dom0 terminal create a _.desktop_ file in _~/.local/share/qubes-appmenus/\<vmname\>/apps.templates_
    - the _apps.templates_ directory did not exist in my case so I created it
    - don't use the real name of your AppVM in property values for  _Name_, _GenericName_ and _Exec_ - use the placeholder _%VMNAME%_ in its place; otherwise you'll get an error when opening the Qube's settings

You can check that this worked by calling _qvm-appmenus --get-available --i-understand-format-is-unstable \<vmname\>_ in a dom0 terminal. This lists all available applications including the one you created.
Note: If you did not use the _%VMNAME%_ placeholder correctly you will get the following error: _AssertionError: template '\<path to .desktop file\>' does not contain name_

This approach feels more in line with how the collection of AppVM shortcuts works. (Correct me if I'm wrong here.)
I don't know if this approach is specific to Qubes 4 so I'm hesitant to edit the documentation.

**Comment by marmarek** [comment]
Since https://github.com/QubesOS/qubes-issues/issues/4152 got implemented, it should be enough to create `.desktop` file in the qube with command you want to run - it should be visible in qube settings in "applications" tab for this particular qube. You may need to press "Refresh Applications" button.
Since it's relatively new thing (especially GUI part of it), you may need to install updates from testing repositories.
Both what you've described and the above simplified version is specific to Qubes 4.x.
