### ISSUE TITLE
Applications list is empty in cloned TemplateVMs (debian-9; fedora-26)

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#3902]
### Qubes OS version:

R4.0

### Affected component(s): 

debian9 TemplateVM
fedore-26 TemplateVM

---

### Steps to reproduce the behavior:

1. Select debian-9 (check: Qube settings > Applications > Available: 15)
2. Clone qube => debian-9-clone-1
3. Select debian-9-clone-1
4. Qube settings > Applications > Available: 0

Please assist, is it a bug or feature?

### Expected behavior:

I expected that a clone of a TemplateVM comes with the same number of Applications.

I wanted to install further programs to debian-9-clone-1 and then use this TemplateVM for creating a  couple of AppVM or Standalone VMs. I think, this was easily possible with the previous Qubes 3.2.

### General notes:

---

**Comment by andrewdavidwong** [comment]
I'm pretty sure I've seen this problem reported or discussed somewhere, but now I can't find it. If anyone knows, please provide a link here.

**Comment by loadcorp** [comment]
I have the same issue in Qubes 4.0

I thought that all what we need is notifying dom0 about installed applications.

Because of I don't know that exact command about this notifying, I am using this commands (if anybody knows the exact commands, please type below, it would be easier):


for Fedora:

[user@dom0 ~]$ qvm-clone fedora-26 fedora-26-clone
[user@dom0 ~]$ qvm-run -a fedora-26-clone gnome-terminal
[user@fedora-26-clone ~]$ sudo dnf clean all
[user@fedora-26-clone ~]$ sudo dnf update


for Debian it is a little bit different:
[user@dom0 ~]$ qvm-clone debian-9 debian-9-clone
[user@dom0 ~]$ qvm-run -a debian-9-clone gnome-terminal

Now you must install new package or delete already installed package in Debian terminal (for example I will show how it work if you want to install/uninstall 'Filezilla'):
[user@debian-9-clone ~]$ sudo apt-get install filezilla
(if you have not this package)
or
[user@debian-9 ~]$ sudo dpkg -r --force-depends "filezilla"
(this one will delete package without dependencies if you don't need this package)


P.S.
Inspired by this guides:
https://www.qubes-os.org/doc/template/fedora/upgrade-27-to-28/
https://www.qubes-os.org/doc/template/debian/upgrade-8-to-9/

**Comment by crknadle** [comment]
I also quickly ran into this bug, but I've found a workaround:
After cloning the TemplateVM, the Application list can be refreshed using the Qube Manger by:

- right-clicking on the new TemplateVM clone
- chose "Qube settings"
- go to the "Applications" tab
- press the "Refresh Applications" button at the top just under the tabs.

This will start the TemplateVM if it isn't running already and then refresh the application list.

**Comment by Wikinaut** [comment]
@crknadle I never noticed, that this is a button which can be clicked... (#userinterfacedesignfail)

**Comment by marmarta** [comment]
I've made the button smaller and more like a button (that is, less like a 'huge thing spanning the whole window' that it was before) here: https://github.com/QubesOS/qubes-manager/pull/128 ; it should solve at least this part of the problem :)
