### ISSUE TITLE
kernel 4.14 has intel mei_me module re-enabled

### ISSUE THREAD

**Issue by mvermaes** [QubesOS/qubes-issues#3916]
### Qubes OS version:

R4.0

### Affected component(s): 

Kernel

---

### Steps to reproduce the behavior:

`lsmod | grep mei`

### Expected behavior:

No output from above command

### Actual behavior:

`mei_me` and `mei` modules are loaded

### General notes:

* These modules were removed from both 3.2 and 4.0 kernels in https://github.com/QubesOS/qubes-linux-kernel/commit/e0f8e9ca81b80d897b190f48a4af80eff3198cb1
* They were re-enabled in 4.0 as part of the cleanup in https://github.com/QubesOS/qubes-linux-kernel/commit/537e0d17a8429b57a9502571e8847ed5955a681a
* I'm not really sure how much is gained by disabling these modules anyway, but I couldn't see any reason for them to be disabled in 3.2 and enabled in 4.0

---

**Comment by lunarthegrey** [comment]
Same module is loaded for me. Running kernel 4.14.35-1.

**Comment by lunarthegrey** [comment]
The mei and mei_me modules are still loaded with the 4.14.41-1 kernel (latest stable as of now). Is there any specific reason why the modules were added back @HW42 ?

**Comment by lunarthegrey** [comment]
Still wondering why. Maybe @andrewdavidwong can help?

**Comment by andrewdavidwong** [comment]
> Still wondering why. Maybe @andrewdavidwong can help?

I haven't the foggiest, but I bet @marmarek does.

**Comment by marmarek** [comment]
The reason is simple and not very technical - we try to avoid maintaining custom kernel configuration as much as possible, as we don't have much resources for that (including testing configurations for new drivers etc). For this reason we reuse Fedora kernel configuration as a base.

Disabling mei_me module doesn't really disable ME. It only means that kernel wouldn't be able to ask nicely ME for some information (and the same user space daemons - but we don't have any for this device). ME will still be able to extract whatever information it want, because it has full access to system memory at CPU level, sadly.

Anyway, if you like to help to disable it, send a pull request to adjust [custom options for the kernel](https://github.com/QubesOS/qubes-linux-kernel/blob/master/config-qubes). Please test it first.
