### ISSUE TITLE
Hanging in Xen when trying for new instalation 

### ISSUE THREAD

**Issue by elkimek** [QubesOS/qubes-issues#3917]
### Qubes OS version:

4.0

### Affected component(s): 

Intel NUC ES Hades Canyon KIT 8i7HVK (newest BIOS)

---

### Steps to reproduce the behavior: 

Reflashed bootdrive with Qubes 4.0 img

### Expected behavior: 

To be able to install form flashdrive.

### Actual behavior: 

Hanging in XEN

### General notes:

Hey, I'm trying to install Qubes 4.0 on my new NUC Hades Canyon (ES)
Hanging in Xen screen EFI loader
Using configuration file "BOOTX64.cfg"
vmlinuz: some hex
initrd.img: again some hex
hex ROM
hex ROM

Just hanging and doing nothing

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
