### ISSUE TITLE
Not installable on xps 15 9570 - Black screen.

### ISSUE THREAD

**Issue by fentas** [QubesOS/qubes-issues#3946]
### Qubes OS version:

Latest release R4.0

### Affected component(s): 

Dell XPS 15 9570
Core i9 / 32 GB / 1TB SSD

---

### Steps to reproduce the behavior:

Download iso and copy it to usb (`dd`). Boot from it.

### Expected behavior:

Anything else.

### Actual behavior:

Black screen. 100% cpu guessing from heat and fan speed / noice. Nothing else happens. Waited for 5-10 Minutes.

### General notes:

- Tried also R3.2
- Ubuntu 18 is booting from the same usb stick.

---

**Comment by fentas** [comment]
> The installer loads Xen right at the beginning, so chances are high that if you can see the installer’s graphical screen and you pass the compatibility check that runs immediately after that, Qubes will work on your system. :)

As I can't see the graphical screen changes are high that XPS 15 9570 is not compatible? :/

**Comment by fentas** [comment]
Interesting, gparted (0.3.1) iso will also not boot up.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by ethanfrey** [comment]
@fentas I just got the same laptop, and was also interested in installing Qubes.... Did you ever get the xen installation to work (with a tip or two how?) or is it simply incompatible? I figured I'd do a little research before wiping the disk clean a few times....

**Comment by qazero** [comment]
Any update regarding this? I'm encountering the same issue...

**Comment by fentas** [comment]
Had no time to investigate, sorry.
