### ISSUE TITLE
Wireless networking does not work on Macbook 2015 (macbook8,1)

### ISSUE THREAD

**Issue by gerd2002** [QubesOS/qubes-issues#3954]
### Qubes OS version:

R4.0

### Affected component(s): 

Networking (sys-net)

---

### Steps to reproduce the behavior:

Install qubes normally.

### Expected behavior:

Networking works OOB.

### Actual behavior:

Only a loopback interface is created in the networking qube.

### General notes:

I also tried to install the firmware for the BCM4350 (https://wiki.debian.org/brcm80211) in a modified networking cube (changed template to debian 9), but that did not work either.

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by gerd2002** [comment]
@andrewdavidwong I am inclined to believe that this problem applies not only to the Macbook8,1 but also to other laptops with a BCM43xx chip.

**Comment by andrewdavidwong** [comment]
I'm afraid an issue specific to Broadcom BCM43xx chips is still too localized for `qubes-issues`. Unfortunately, Broadcom chips are notorious for not working well with Qubes.

**Comment by gerd2002** [comment]
@andrewdavidwong Sorry if this seems inappropriate, but then I am wondering how #3784 is not too device-specific?
