### ISSUE TITLE
Unable to configure VMs and boot after sucessfully install

### ISSUE THREAD

**Issue by arraiano** [QubesOS/qubes-issues#3956]
Im trying to install Qubes 4.0 on this machine:

Processor: AMD Athlon X2 340 Dual Core
Motherboard: AsRock FM2A75M
IOMMU: Enabled
SATA Mode: AHCI
Memory: 8 Gb
HD: SSD Kingston 240 Gb

I can finish the installation process successfully, but then, on the first boot when I go to the VMs configuration screen (i choose settings done by default), my PC reboots without finish the process. On the next boot, the system returns to the VM configuration screen: if I try to repeat the normal configuration, it freezes. If this second time I choose "don't configure anything", I can continue de boot process, dom0 seems to start successfully, but then the job of starting sys-firewall, sys-net and sys-whonix crashes, and a lot of messages like "ata2.00: failed command: READ FPDMA Queued" and "Buffer I/O error on device dm-4, logical block (and the block number here)" appears. As I can,t boot the system, i can,t get the real logs (perhaps I could try it by booting the PC from a Live distro. What logs should I look for?).
I  had tried the installation on several HD (the last one is a new SSD), whit several SATA cables, whith all the SATA Modes possible...and the result is the same. The only one time i arrived to the login screen was onece when, by mistake, I disabled IOMMU...but, of course, the system doesn't runs.
By the way, on the early boot I get another error: "sp5100_tco: I/O address 0x0cd6 already in use. Disabling DMA". I get the same error runing in the same computer Debian 9, but the OS boots and runs without problems.

Could anymody help me?? Thankyou very much!

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
