### ISSUE TITLE
Can't Delete disp VM

### ISSUE THREAD

**Issue by qubesissues** [QubesOS/qubes-issues#3993]
### Qubes OS version:

4.0

### Affected component(s): 

Qubes Manager

---

### Steps to reproduce the behavior:

Try to delete a disp VM.

### Expected behavior:

The disp VM should be deleted after you enter it's name.

### Actual behavior:

You get an error that it cannot be deleted and check system log (see this issue: https://github.com/QubesOS/qubes-issues/issues/3992)

### General notes:

WHAT ARE dispVM ANYWAY?

---

**Comment by RefinedSoftwareLLC** [comment]
Even though DispVM sounds like its short for Display, it really means Disposable. These are VMs that leave behind less changes then any other type of VM. If you open a file in a Disposable VM, then only changes to that file are saved (anyone correct me if this is incorrect). In order to delete a Disposable VM, you have to remove it from the "Default DispVM" advanced setting of every other VM manually.

**Comment by RefinedSoftwareLLC** [comment]
(Using `qvm-remove <vmname-dvm-template>` or Qube Manager's Delete qube)
Instead of the message `VM can't be deleted, check system log` how about giving the following:

"This qube can't be deleted while it is the `Default DispVM` of another qube.
With any qube who's `Default DispVM` is <vmname-dvm-template>,
change their `Default DispVM` to: "
Then give a dropdown with the options of `default`, list of dvm-templates (except qube being deleted), and `none`.
Lastly, display "Effected qubes: " and list of every qube who's `Default DispVM` would be changed.

If triggered by qvm-remove in the console, then display and number the entries of the drop down, and have the console user select the replacement or cancel deleting the qube.

**Comment by RefinedSoftwareLLC** [comment]
If the qube being deleted is the "[Dom0] Qube Global Settings" `Default DispVM`, then display:

"This qube can't be deleted while it is the system default of `Default DispVM`.
Change the system default of `Default DispVM` to: "

Then give a dropdown with the options of default, list of dvm-templates (except qube being deleted), and none.
Lastly, display "Effected qubes: " and list of every qube who's Default DispVM would be changed.

**Comment by andrewdavidwong** [comment]
> Lastly, display "Effected qubes: " 

Should be: "Affected qubes:"

Just noting it in case this language gets implemented.

**Comment by qubesissues** [comment]
@RefinedSoftwareLLC @andrewdavidwong You still never explained what is "DispVM" - it is a complete mystery.

**Comment by qubesissues** [comment]
@RefinedSoftwareLLC Can you say all of this again?  What you are saying is completely not clear.  Maybe an English translation problem?

> 
> 
> With any qube who's Default DispVM is <vmname-dvm-template>,
> change their Default DispVM to: "
> 
> Then give a dropdown with the options of default, list of dvm-templates (except qube being deleted), and none.
> Lastly, display "Affected qubes: " and list of every qube who's Default DispVM would be changed.

**Comment by qubesissues** [comment]
@RefinedSoftwareLLC 


> Even though DispVM sounds like its short for Display, it really means Disposable. 

Why do they get created by themselves?  And why does a regular Qube have a "default disposable VM"?  What is the relation?

Why do I ever need more than one?

You suggested:

> Instead of the message VM can't be deleted, check system log how about giving the following:
> "This qube can't be deleted while it is the Default DispVM of another qube.

How about:

"This Qube is the Default Disposable Qube of <whatever Qube>.  Please remove it in under the Advanced settings."

Ideally <whatever Qube> would be a list but at least if it is one then the error will repeat with a new <whatever> after <whatever Qube>'s settings are changed.

**Comment by RefinedSoftwareLLC** [comment]
@qubesissues: 
Sure I would be happy to, some of these definitions are not self evident. First off, you can read the official documentation from here: https://www.qubes-os.org/doc/glossary/ & https://www.qubes-os.org/doc/dispvm/:

Second, sorry for the confusion, but there is no translation problem, what you quoted was a post meant for the developers of Qubes OS to add a feature that would fix a frustrating problem both you and I had. I have updated which posts are for you directly.

Understanding DispVMs is a completely separate issue, so let me retry.

Qube: You can look at a Qube as a separate sandboxed emulated PC that only displays the windows of applications you are using inside it.

VM: A VM is a subtype of Qube (Future updates will hopefully allow remote hardware to be Qubes too).

App Qubes: Since people do not want their documents deleted every time their computer reboots, these Qubes need to have permanent storage in your home directory. Because viruses like to modify executable files, only 3 directories are permanent. Your executable files loose all their updates (and corruptions) every time the Qube reboots.

Template Qubes: Each App Qube is based on one of these. You must update executable files here, then reboot your App Qubes, for updates to be permanent.

Disposable Qubes: What makes these confusing is that these Qubes have 3 different modes, so I will break them down below.

- Disposable VM Without Editing: If you use your Applications Menu then open an application from "Disposable: whonix-ws-dvm" you would get this kind of Disposable Qube. These are exactly like App Qubes except none of their directories are permanent. You lose all changes when the Qube reboots. The window title bar will start similar to [disp1234].

- Disposable VM Edit Single Document: If you open up the File Manager in an App Qube, then right click a document, and select the option "Open in DisposableVM" or "Edit in DispVM". Inside a fresh Disposable Qube, it will open up the default application for the document you sent it. Unlike other Disposable Qubes, This will keep changes to a single file, the original file back on the App Qube! The window title bar will start similar to [disp1234].

- Disposable VM Template: Each [disp1234] is based on one of these, just like Template Qubes. If you open the Qube Manager, right click "whonix-ws-dvm", then select "Run command in qube", and manually type in console a command (for example: dolphin). You must update executable files here, then reboot your [disp1234] Qubes, for updates to be permanent. The window title bar will start similar to [whonix-ws-dvm].

**Comment by qubesissues** [comment]
@RefinedSoftwareLLC I realized some of the confusion and deleted my post.   But now I have new confusion.

Please put yourself in someone else's position.  There is no UI/UX explanation of why these things exist.  And you give me these definitions.  Well they do nothing to explain how a dispVM was created for no reason that I understand.  They do nothing to explain how a dispVM is connected to one of my qubes, or why it is part of the settings, seriously why does a Qube need a "default dispVM"?.  And now you list these three types of things-that-I-still-dont-know-why-they-exist.  

I don't  mean to sound angry.  I'm just confused. :)

And how do I create one of these if I want it?  How do I decide which of the three types it is when I create it?  Why would I create it exactly?

I understand App Qube vs Template Qube.  Totally clear.

> https://www.qubes-os.org/doc/dispvm/

Okay yes.  I read that doc some time ago but I did not connect this idea (disposable vm) to the annoying dispVM that take up 25 slots in my Qube Manager. Now I see.  (I thought it was a display vm so did't connect these two things.)

I will also say that that doc didn't make any sense to me when I read it (or when I re-read it now) but at least it would have helped understand what the dispVM are a little bit.  Here is an example of a phrase that is confusing:

> Changes made to a file opened in a DispVM are passed back to the originating VM.

Huh?  What is "the originating VM" and how do you open a file in a DispVM?  And none of this explains why the Advanced settings have a default disp VM.  Very confusing. 

But now I am at least not afraid to delete these things. :)  That is big.  Since scrolling in the Qube Manager is basically broken it has been very very difficult to use Qubes with 25 dispVM in the way.  One problem gone!

**Comment by RefinedSoftwareLLC** [comment]
@qubesissues 
> Please put yourself in someone else's position.
I empathize with you, but I am not a developer of Qubes OS. It would be better to not tag me in posts meant for everyone, or the developers may miss it.

**Comment by RefinedSoftwareLLC** [comment]
@qubesissues 
> why does a Qube need a "default dispVM"

Because of the feature "Disposable VM Edit Single Document", see my previous post for details.

**Comment by RefinedSoftwareLLC** [comment]
@qubesissues 
> And how do I create one of these if I want it? 

https://www.qubes-os.org/doc/dispvm-customization/

**Comment by RefinedSoftwareLLC** [comment]
@qubesissues 
> How do I decide which of the three types it is when I create it?

A Single Disposable Qube listed in the Qube Manager is the harddrive files for all three types at once. See above for how to open that harddrive in each mode.

**Comment by RefinedSoftwareLLC** [comment]
> I thought it [dispVM] was a display vm

Me too! The issue is that tempVM would get confused with Template VM, which is so sad.

It would be a huge discomfort, to rename all dispVMs to tempVMs, and rename Template VM to something else like Base VM; As this would break many of the online tutorials throughout the internet.

I wish a better name could be used, but even if the developers decided to, they would have to wait until R5.0 when R4.0 just came out.

**Comment by RefinedSoftwareLLC** [comment]
@qubesissues 

I would recommend backing up your system any time you are on a "delete 25 qubes" crusade.

I have no idea how you got 25 dispVM. when installing Qubes OS it asked me to create default Qubes (I accepted) then it only made one dispVM for the global default.

Did an upgrade duplicate your qubes as dvms or convert some of them? Make sure none of the Qubes you are deleting have information in them you want to keep!

As stated earlier, I recommend keeping at least 1 dispVM for your global default.

**Comment by RefinedSoftwareLLC** [comment]
@andrewdavidwong 
With the above section `Understanding DispVMs is a completely separate issue, so let me retry.`, would adding something similar to the documentation be a benefit? (After someone else rewrites it with improvements of course.)

**Comment by andrewdavidwong** [comment]
@RefinedSoftwareLLC, @qubesissues:

1. Please stop using this issue as a discussion thread about explaining DisposableVMs and other types of VMs in Qubes. That's simply not what this issue is about, and this type of discussion is a misuse of `qubes-issues`. Having such a high volume of off-topic comments on an issue makes it extremely difficult for people (especially busy devs) to find the relevant information for this specific issue. Please take the discussion to `qubes-users`.

2. Common topics like DisposableVMs and the different types of VMs are covered in the documentaiton. If you believe the documentation is missing something, that's fine. The doucmentation is a work-in-progress, and we all want it to improve. But this is not the way to do it. Open a separate documentation issue and contribute a PR to `qubes-doc`. The documentation is mostly a volunteer, community effort. [You can help improve it.](https://www.qubes-os.org/doc/doc-guidelines/#how-to-contribute)

**Comment by qubesissues** [comment]
@andrewdavidwong 

> Please take the discussion to qubes-users.
Can you explain what that is?

> Common topics like DisposableVMs and the different types of VMs are covered in the documentaiton. 

Yes but you miss the point.  I read the doc on Disposable VMs but I did not know that "Disposable VMs" were the same as the "disp" VMs that were causing me enough trouble to justify an Issue.  And it was an Issue.  Regarding the other types of VMs I did not ask about those but I appreciate the help @RefinedSoftwareLLC offered (perhaps a link would have been better).

> Open a separate documentation issue and contribute a PR to qubes-doc

Again please: what is this place you are talking about?  Links please?

> The doucmentation is a work-in-progress, and we all want it to improve.

Yes but my friend, do try to get out of your own head for thirty fucking seconds please.  The way we learned that Disposable VMs are the thing that was causing the Issue is by going through this discussion.  The *result* of that was that now we know we have a doc issue to fix (also a UI issue because the UI does not make clear what a disp VM is or why it exists).  So this discussion was not just okay but absolutely critical and now we can create better docs and also I can create a more specific UI issue.

**Comment by andrewdavidwong** [comment]
>> Please take the discussion to qubes-users.
>>
> Can you explain what that is?

It's the mailing list for Qubes users to ask questions have discussions. See:

https://www.qubes-os.org/support/

And specifically this section:

https://www.qubes-os.org/support/#qubes-users

If you search for "qubes-users" on DDG or StartPage (and probably every other search engine), the web interface for the group is the first result, and the Support page linked above is the second result. (The web interface also links back to the Support page.)

https://duckduckgo.com/?q=qubes-users
https://www.startpage.com/do/dsearch?query=qubes-users

>> Common topics like DisposableVMs and the different types of VMs arecovered in the documentaiton.
>
> Yes but you miss the point.  I read the doc on Disposable VMs but Idid not know that "Disposable VMs" were the same as the "disp" VMs that were causing me enough trouble to justify an Issue.

The abbreviation is in both the URL and the title of the page you read:

URL: https://www.qubes-os.org/doc/dispvm/

Title: `Disposable VMs (DispVMs)`

It's also in the Glossary:

https://www.qubes-os.org/doc/glossary/#dispvm

This page is also the very first search result for "dispvm" on DDG and StartPage (and probably every other search engine):

https://duckduckgo.com/?q=dispvm
https://www.startpage.com/do/dsearch?query=dispvm

>> Open a separate documentation issue and contribute a PR to qubes-doc
>
> Again please: what is this place you are talking about?  Links please?
>`qubes-doc` is the repository for Qubes documentation:

https://github.com/QubesOS/qubes-doc

This was explained in the first sentence of the page to which I linked in the message to which you're replying. Here it is again:

https://www.qubes-os.org/doc/doc-guidelines/

It's also the first result if you use the search bar at the top of this page to search for "qubes-doc".

>> The doucmentation is a work-in-progress, and we all want it to improve.
>>
> Yes but my friend, do try to get out of your own head for thirty fucking seconds please.  The way we learned that Disposable VMs are the thing that was causing the Issue is by going through this discussion.

No, this is the way that *you* learned that "DispVM" means "Disposable VM." Everyone else here already knew this because we make it obvious in many ways, and you could have easily found your answer in a few seconds by doing a simple web search or by reading the documentation. But you didn't even need to do that, because @RefinedSoftwareLLC clearly explained it to you in the [first comment on this issue](https://github.com/QubesOS/qubes-issues/issues/3993#issuecomment-397370169). Everything after that was an off-topic discussion that should have taken place in `qubes-users` instead. But that's not even the main problem here. We're generally pretty understanding of new users and contributors who aren't familiar with our practices and who politely ask questions that they don't realize have already been answered elsewhere. The problem is not just that you're asking to be spoon-fed information that we've already gone to great effort to make easily discoverable for you, but that you're now responding *rudely* after being asked to have this discussion in the appropriate venue.

You need to understand that you're entering an existing community of people, many of whom are *volunteering* their own time to try to help you (with an operating system that you're getting for *free*, by the way). Like any community, we have a reasonable set of rules and practices for keeping things organized and running smoothly. It's completely unreasonable to barge in and start throwing insults after
being asked to follow the rules, *especially* when you've shown no evidence that you've made any effort to find the answers to your questions on your own and no appreciation for the hard work that everyone else has done to make the answers to your questions easy to find.
