### ISSUE TITLE
qvm-run -p --localcmd output is interpreted by shell instead of being sent to command in appvm

### ISSUE THREAD

**Issue by homotopycolimit** [QubesOS/qubes-issues#4040]
### Qubes OS version:
R4.0

### Affected component(s): 
qvm-run

### Steps to reproduce the behavior:

in dom0 run a `qvm-run -p` command with the `--localcmd` option

for example:
`qvm-run -p --localcmd="cmd0" $appvm "cat > /home/user/output"`

### Expected behavior:

Expect the output of cmd0 to be passed to the command on the appvm side, i.e. in this example we expect the output to be written to /home/user/output

### Actual behavior:

It seems as if the output of the localcmd (cmd0) is being sent to bash (qubes-VMShell?) on the appvm side instead of to `cat`. It is trying to be interpreted by the shell! 

### General notes:
This seems to potentially be a serious issue because the shell is interpreting things that it is not meant to.

**Comment by homotopycolimit** [comment]
A mimimal example:

`qvm-run -p --localcmd "date;sleep 1" sys-net "cat > /tmp/foo"`

gives

`/bin/bash: line 1: Wed: command not found` (at least on a Wednesday)

**Comment by heinrich-ulbricht** [comment]
I'd love to see this one fixed. Need this to pass a password from dom0 to an AppVm application via stdin which currently does not seem to work.

**Comment by unman** [comment]
I think this issue is simply based on a misunderstanding, and misplaced expectations. It *may* be unclear documentation, but I dont think so.

qvm-run is used to run a command :  @homotopycolimit gives the example of `cat > /tmp/foo`. Obviously *that* command is not going to generate any content in /tmp/foo

`-p` is used to pass stdin/stdout to and from the remote program.
The program runs, stdout is captured and passed to dom0 as input, output from dom0 passed back to qube input.
e.g `qvm-run -u root -p <qube> passwd`
can be used to interactively change root password on the qube.

`--localcmd` is used _together_ with `-p` to pass stdin and stdout to and from the given program.  It doesnt change the order of execution. Remote is executed and output passed back to dom0 as input for localcmd. In the @homotopycolimit example, by the time localcmd runs, the remote command has already executed, and terminated. If you  make the remote command wait for input then you can feed it from the dom0 program.

There's an obvious example of how --localcmd *should* be used: using a mouse in sys-usb. The proxy sender and proxy receiver both run, and shuttle events back and forth between them. See [here](https://github.com/QubesOS/qubes-app-linux-input-proxy)
`qvm-run -u root --pass-io --localcmd="input-proxy-receiver --mouse" usbvm "input-proxy-sender /dev/input/event2"`

@andrewdavidwong I would close this.

@heinrich-ulbricht  I dont think there is anything to fix: I suggest you ask over at qubes-users with a little more detail on what you are trying to achieve.

**Comment by marmarek** [comment]
@unman this works in Qubes 3.2, and indeed is broken in Qubes 4.0. As @homotopycolimit written, if you use `--localcmd`, the command you give to qvm-run isn't executed - instead localcmd is connected to a shell (instead of the requested command) running in that VM.

**Comment by unman** [comment]
Late at night after a long weekend, it all seemed to make perfect sense to me. I wont be doing that again.
Apologies all round.
