### ISSUE TITLE
whonix-os not work internet

### ISSUE THREAD

**Issue by oytunistrator** [QubesOS/qubes-issues#4062]
### Qubes OS version:
R4.0

### Affected component(s): 
whonix-os components

### Steps to reproduce the behavior:
- added whonix-os 
- whonix not connected to tor

### General notes:
Whonix tor internet connection not work.

**Comment by Aekez** [comment]
It might be a good idea to provide more information, and also to clarify whether this is a bug/developer focus, or an end-user/support focus, i.e. better to post questions in the mailing lists https://groups.google.com/forum/?_escaped_fragment_=forum/qubes-users#!forum/qubes-users while keeping the bugs and feature requests in GitHub.

- **How did you get your Whonix installed?**
  - Your wording `added whonix-os` makes it look like you might have installed Whonix as an HVM rather than as a Qubes template. Is that a misunderstanding, or did you do this?
  - Did you manually install Whonix Qubes templates via sudo qubes-dom0-update? If so, then it might be that you need sys-whonix properly setup (for example qvm-prefs to enable provides networking), and change dom0 Qubes-RPC policies to enable template package install/updates.
  - Did you use the automatic Qubes Whonix installer?
  - Are you using the pre-installed Whonix?

- **General information, like?**
  - Are you using Whonix 13 or Whonix 14?

- **Descriptions and error types?**
  - Is all internet gone? i.e. can you install/update in whonix templates? or the opposite where you can access internet in the Whonix AppVM but not install/updates in the template? or both is missing?
  - Any error messages or clues you can provide and include? Screenshots, logs, anything that might be useful?

**Comment by oytunistrator** [comment]
Installation after run **whonix** templates but connections wrong. **Whonix-ws** have internet connection problem.

**Comment by andrewdavidwong** [comment]
@oytunistrator, please answer **all** of @Aekez's questions. In general, you need to provide more detailed information, or else we will not be able to help you.

**Comment by adrelanos** [comment]
> Whonix OS is not alowed to change "obfs4" servers.

What do you mean by "not allowed"?

> My internet blocked tor networks.

Please try if you can make Tor Browser Bundle (TBB) work first in non-Whonix (such as Debian) VM as per https://www.whonix.org/wiki/Computer_Security_Education#Tor_Browser.

**Comment by adrelanos** [comment]
I suggest to close as `user disappeared` if/until the user returns.

**Comment by andrewdavidwong** [comment]
Closing this for now due to the lack of response. If you revisit the matter in the future, or if anyone would like the issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by rg687** [comment]
Hello, 

I am experiencing the same problem, I reinstall whonix and internet is no longer working. Im not sure where to start to resolve the problem.
Help appreciated. Thanks

**Comment by andrewdavidwong** [comment]
@rg687: Please provide more details. See above for some questions to which you should provide answers. Also see our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/).

**Comment by oytunistrator** [comment]
I cant select obfs4 servers. Tor blocked my country. This reason tor browser works but whonix cant work on qubesOS.  Tor browser selects first startup obfs4  and meek. And we need openvpn server creator also. 

Thanks for answer.

**Comment by adrelanos** [comment]
Whonix seems to work as expected but censorship circumvention is hard. Should be closed here since Qubes isn't working on censorship circumvention. Belongs here:

* https://www.whonix.org/wiki/Bridges
* https://forums.whonix.org

**Comment by andrewdavidwong** [comment]
Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
