### ISSUE TITLE
GlobalProtect vpn client will not connect

### ISSUE THREAD

**Issue by blissjoe** [QubesOS/qubes-issues#4069]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

Debian 9 and Fedora 28 template
StandaloneVM based on Fedora 28 template
GlobalProtect Linux Client

---

### Steps to reproduce the behavior:

1. Download globalprotect linux client
1.1 RPM - https://drive.google.com/open?id=114b9qKCb6B9piwU7z5olaBM88cV7n3Hk
1.2 DEB - https://drive.google.com/open?id=1w4vsEEwIXBCKreyP2SIj7P40Zc7auYL2
2. Install (rpm - i or dpkg -i)
3. Enable network-manager service  
4. Run globalprotect from the terminal

### Expected behavior:

Normally running `globalprotect connect --portal portaladdress.com` will result in the terminal requesting your username/password

### Actual behavior:

The GlobalProtect agent is unable to get input from the terminal. 

`[user@work ~]$ globalprotect`
`Cannot connect to local gpd service.`

`[user@work globalprotect]$ systemctl status gpd`
`● gpd.service - GlobalProtect VPN client daemon`
`   Loaded: loaded (/usr/lib/systemd/system/gpd.service; enabled; vendor preset: disabled)`
`   Active: active (running) since Wed 2018-07-11 07:22:17 EDT; 1 day 1h ago`
`  Process: 525 ExecStartPre=/opt/paloaltonetworks/globalprotect/pre_exec_gps.sh (code=exited, status=0/>`
` Main PID: 547 (PanGPS)`
`    Tasks: 10 (limit: 4671)`
`   Memory: 20.7M`
`   CGroup: /system.slice/gpd.service`
`           └─547 /opt/paloaltonetworks/globalprotect/PanGPS`

`Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.`

Sample log output -
`cat /opt/paloaltonetworks/globalprotect/PanGPS.log`
`P 547-T-210675968 Jul 12 07:40:33:30146 Debug( 756): Display hip report V4 on the UI`
`P 547-T-210675968 Jul 12 07:40:33:30745 Error(1117): Failed to send 512 bytes to client`
`P 547-T-210675968 Jul 12 07:40:33:31450 Error(1117): Failed to send 464 bytes to client`

### General notes:

I opened the issue here instead of with PaloAlto because the client works under a non-Qubes Debian or Fedora installation. I tried to run yum groups install "Fedora Workstation" thinking that it may be a missing dependency. I'm under the assumption that this may be a Qubes security feature, but I'm unsure what terminology I would need to search for or how to troubleshoot further.

Any help would be appreciated.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by anon8675309** [comment]
I am able to reproduce this issue in Qubes 4 using debian-9 as a base image. I have not found any workaround. I'd like this to be considered for re-opening, as it does seem to be a valid bug.

The report describes how to reproduce the problem and how it was confirmed that it is specific to Qubes.  The desired action is to fix the thing which prevents this software from working (I'm not sure of all the things changed for the Qubes version of debian-9).  The report does lack the information about the root cause of the issue, but I'd be happy to provide whatever information it is that is needed.  I'm also willing to do any testing or write and submit a patch once the root cause is identified.

**Comment by anon8675309** [comment]
I believe I found the root cause as well as a workaround and therefore revoke my request for this ticket to be re-opened.  Since this is the top hit in Google for the error message "Cannot connect to local gpd service" I'll provide the workaround to help the people of the future.

There's hints that the root cause of this issue is that GlobalProtect requires xauth (I can only see the preview of the following post).
https://live.paloaltonetworks.com/t5/custom/page/page-id/GlobalSearch#q=Cannot%20connect%20to%20local%20gpd%20service&sort=relevancy

It's completely reasonable for Qubes to not support xauth, as there is a ot of things going on between dom0 and the VMs to make the user experience smooth.  Honestly, it's pretty unreasonable for GlobalProtect to require this (I consider pretty much all X11 code hazardous), but I digress.

The release notes for OpenConnect v8.00 state that it added support PAN GlobalProtect earlier this month.
http://lists.infradead.org/pipermail/openconnect-devel/2019-January/005178.html

Since this is a new release, it is not in repos yet, however I compiled it from source and I can confirm that this works, on Qubes 4.0 with debian-9 as a base.  For reference, here are steps to reproduce my results (assuming you have a GlobalProtect VPN server to connect to):

```
wget ftp://ftp.infradead.org/pub/openconnect/openconnect-8.00.tar.gz
tar zxvf openconnect-8.00.tar.gz
cd openconnect-8.00/
sudo apt install libssl-dev pkg-config libxml2-dev zlib1g-dev
./configure --disable-nls
make
sudo ./openconnect --protocol=gp $VPN_SERVER
```

**Comment by andrewdavidwong** [comment]
Thanks for providing this information, @anon8675309! Hopefully it'll help some people.

**Comment by douglasg14b** [comment]
@anon8675309 Thanks!

This is a prime example of why github issues should not be auto-locked over time. As often someone will come along a year alter and add extremely helpful information...

**Comment by marmarek** [comment]
FWIW openconnect 8.x is available in Debian buster and Fedora 29+
https://repology.org/project/openconnect/versions

**Comment by andrewdavidwong** [comment]
> @anon8675309 Thanks!
> 
> This is a prime example of why github issues should not be auto-locked over time. As often someone will come along a year later and add extremely helpful information...

Yes, this is why our GitHub issues are *not* auto-locked over time. Even after we close an issue, anyone is allowed to leave a comment requesting that it be reopened for good reason. (The only time we lock issues is when people misbehave and cause problems.)
