### ISSUE TITLE
Updates fail when update proxy VM not already running

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#4096]
### Qubes OS version:

R4.0

### Affected component(s): 

Template updates

---

### Steps to reproduce the behavior:

Initiate update procedure for any template whose update proxy is not already running. For example, whonix-ws when sys-whonix is not running.

### Expected behavior:

Proxy comes online before update begins, or update waits for proxy to come online.

### Actual behavior:

Many 'unable to retrieve' type errors until the update process fails. Update must be coordinated manually instead.

### General notes:

The method by which the template's network dependency is satisfied is unlike the normal handling of an assigned netvm; the asynchronous nature doesn't lend itself to predictable updates with normal update clients such as apt, dnf, etc.

---

**Comment by marmarek** [comment]
Does it happen for non-whonix update proxy VMs too?

**Comment by adrelanos** [comment]
Yes, because qvm-start logic does not analyze `/etc/qubes-rpc/policy/qubes.UpdatesProxy`.

----

Qubes-Whonix 14 addresses this and has code to wait which seems to work quite well.

https://github.com/Whonix/qubes-whonix/blob/master/etc/uwt.d/40_qubes.conf

But that is not pretty. I would prefer if Qubes would make update proxy VM start before the TemplateVM starts as it was the case in Qubes R3.2.

In case you want to test:

* https://www.whonix.org/wiki/Qubes/Install/Testing
* https://forums.whonix.org/t/whonix-14-release-blockers-status-of-whonix-14-development

----

Related:
https://github.com/QubesOS/qubes-issues/issues/3412

**Comment by rustybird** [comment]
For non-Whonix templates, I only seem to have this problem when my system is under high load. I'd guess that dnf and maybe apt-get have some sort of (configurable?) minimum throughput or read timeout, so if the updates proxy VM takes too long to start, they give up on the connection. Without retrying - good thing that internet connections are 100% reliable.

> I would prefer if Qubes would make update proxy VM start before the TemplateVM starts as it was the case in Qubes R3.2.

Could be pretty rough if you're starting the template for reasons other than installing software, e.g. to edit a configuration file. In the worst case, this would cause sys-net -> sys-firewall -> sys-whonix startup, maybe even a fourth VM if the updates proxy is running in a separate VM. People seemed to dislike that for clock sync (#3588).

For my Whonix templates, I've opted to disable the Whonix safety mechanism by _enabling_ their `whonix-secure-proxy` qvm-service.

**Comment by adrelanos** [comment]
> Could be pretty rough if you're starting the template for reasons other than installing software, [...]

Fair point. However, Qubes automatically starting dnf / apt-get for updating negates this.

**Comment by rustybird** [comment]
> However, Qubes automatically starting dnf / apt-get for updating negates this.

If you're opening the template for a quick edit, you have a leisurely ;) 5 minutes until qubes-update-check.timer kicks in. (I usually just disable the qubes-update-check qvm-service.)

**Comment by tasket** [comment]
In addition to whonix templates, a regular template will likely fail if its configured to redirect to an "update VM" that is also dependent on another netvm and they both have to start. For example, a logical combination is:
  Mytemplate >> sys-update --> sys-vpn.

For the time being, I'm playing with parsing the qubes.UpdatesProxy policy from my `qubes4-multi-update.py` script -- though I wish I had a general solution that worked like Whonix 14. I'd rather have some way for the template to test the update proxy connection (hint...).

**Comment by tasket** [comment]
FWIW, I currently cannot reproduce the problem with regular templates after 3 tries (starting 2 upstream VMs each time).

The problem persists for Whonix, however. I am trying a workaround to trigger the update VM to start and then wait for it, like:

```
curl -s --connect-timeout 30 localhost:8082 >/dev/null
sleep 10s
# start update process...
```

**Comment by adrelanos** [comment]
Also as far as I understand in Qubes R4, templates are started after being downloaded so they can process `/etc/qubes/post-install.d/` (`qvm-features-request` mechanism) and then shut down. This needs to be kept in mind.

* https://github.com/QubesOS/qubes-core-agent-linux/blob/master/qubes-rpc/qubes.PostInstall
* https://github.com/QubesOS/qubes-core-agent-linux/tree/master/post-install.d

**Comment by ArrayBolt3** [comment]
This bug has come back in R4.3 with Whonix 18. After implementing IPv6 support in Whonix, Tor ended up needing to take a little longer to start, and that small added delay seems to have triggered this again. Could we re-open this?

**Comment by ArrayBolt3** [comment]
Brain-dump of my work debugging this so far:

At the moment, Qubes Update attempts to update all templates that need updated basically as fast as it can start the update procedure. If dependency VMs like sys-firewall, sys-net, and sys-whonix need to launch and initialize whatever part of networking support they provide before the updates will succeed, the updater ends up racing the other VMs initialization process. Previously, apparently by chance, the VMs almost always win the race, so the update procedure works without problems. With Whonix 18 however, the VMs are repeatedly losing the race time and again.

The most likely culprit here is an extra 10-second delay added to Tor's startup in Whonix 18. After we added IPv6 support, we found Tor was repeatedly failing to launch, because Tor itself was racing the networking subsystem and was attempting to bind itself to IPv6 addresses that didn't exist yet. After quite a bit of research, we concluded that the best solution to this was to insert a `sleep 10` into the startup scripts used for Tor in Whonix, so that if IPv6 was going to be available, Tor would wait long enough for it to become available before starting, and if IPv6 was not going to be available, Tor would have waited long enough to know that IPv6 almost certainly wasn't going to become available any time soon. [1]

Unfortunately this means that `sys-whonix` now has a 10-second disadvantage in the race with the updater, so now the updater always wins the race, attempts to update packages before they become available, and fails after trying a few times. This results in the VMs failing to update.

Now as @adrelanos covered above, we *do* have a script in place that intentionally prevents apt from running until the Tor update proxy comes up. Unfortunately, Qubes Update bypasses this script by default, as it uses the APT API rather than `apt-get` directly when possible, so that it can provide a progress bar allowing users to see how far along an update is. There is a mode that allows using `apt-get` instead, but using it removes the progress bar. (The script itself may also need an extra `sleep 10` inserted into it to match the one in Tor, at least if we're going with an easy-as-possible fix-it-later solution.)

I can see a few of ways forward, there might be more, but:

1. We could add a special case to qubes-core-admin-linux that disables the use of the APT API on Whonix virtual machines. This will ensure our apt wrapper script comes into play. Personally I hate this solution - Whonix does so many "weird" things in order to achieve its goals that we have special-cases for it peppered throughout Qubes OS's code. On top of that, this would regress functionality that's worked perfectly fine in R4.2 for quite a while.
2. We could try to add a qrexec endpoint for update proxy VMs that would indicate that the VM is ready for updates to be downloaded through it. How that would then be implemented would be up to each VM - a simple VM like sys-net or sys-firewall would be "ready" if it had a global IP address on an external-facing interface. sys-whonix would be "ready" if the Tor service was operational and had a functional connection to the Tor network. This could be implemented as an endpoint on the dom0 side that update proxy VMs would call when they were ready, or it could be implemented as endpoints on the domU side that dom0 would poll until they reported that they were ready (probably the former is better). This seems like the best solution to me, but it also means adding yet another feature to R4.3, which is already in feature freeze. (Arguably it's a bug-fix, but complexity-wise it's a feature.)
3. We could add a special case to qubes-core-admin-linux that simply adds a 10-second pause before it attempts to update a Whonix template. This is probably the ugliest of all the solutions, but it would avoid all regressions, and it would be pretty simple to implement. Then we could try to replace it with a real solution in R4.4 or R5.0.

@marmarek Is there maybe a better solution than any of the above three? If not, which one do you think would be best?

[1] Yes, adding a sleep to fix a race is a horrible solution 99% of the time. The reason we decided this was one of the 1% of times where it wasn't a bad idea is:

* Figuring out whether a network interface supports IPv6 or not is like solving the halting problem as far as I'm aware - once you get an IPv6 address, you know IPv6 is supported, but until then, you have no idea whether there isn't any IPv6 support, or whether the router just hadn't gotten around to giving you IPv6 support yet. Thus one has to wait until either IPv6 shows up or a timeout is reached, whichever comes first. 10 seconds seemed like a reasonable timeout to us.
* Since this would mean always delaying IPv4-only connections by 10 seconds anyway, we didn't see much value in listening for when an IPv6 address showed up, since that would be a minor performance optimization that many users wouldn't benefit from and that would introduce very substantial complexity into the Tor startup scripts.
* Thus for simplicity, we just `sleep 10`, then check to see if we have IPv6 or not. If we don't, we configure Tor to not try to provide IPv6 support, otherwise we configure it to provide IPv6 support.

**Comment by marmarek** [comment]
> 1. We could add a special case to qubes-core-admin-linux that disables the use of the APT API on Whonix virtual machines.

Yeah, I don't like it either.

> 2\. We could try to add a qrexec endpoint for update proxy VMs that would indicate that the VM is ready for updates

Some variation of this is probably the best idea. Maybe, it could be as simple as `qubes.UpdatesProxy` service on the sys-whonix side waiting for Tor to connect before forwarding the request? This means the first request would get response with a delay, but it is the case anyway. This would change sending error back to apt, to sending successful response but later. Hopefully apt won't timeout due to this, but if that's an issue, increasing the timeout should be easy.
Technically, it's a bit unfortunate, as the `qubes.UpdatesProxy` wouldn't use qrexec built-in tcp forwarding anymore (on Whonix), but would be a script again. But that's a small price to pay. I'd assume Whonix simply replaces that file with Whonix-specific one (that waits for Tor). https://github.com/QubesOS/qubes-issues/issues/1844 could be useful for that, but we don't have it currently...

> 3\. We could add a special case to qubes-core-admin-linux that simply adds a 10-second pause before it attempts to update a Whonix template.

Something like this could also work (via [a plugin](https://github.com/QubesOS/qubes-core-admin-linux/tree/main/vmupdate/agent/source/plugins)), but TBH I hate the "sleep 10" idea. Better use the method that apt-get wrapper does for waiting (IIUC it repeatedly checks if Tor+proxy is up already).

**Comment by ArrayBolt3** [comment]
> Maybe, it could be as simple as `qubes.UpdatesProxy` service on the sys-whonix side waiting for Tor to connect before forwarding the request? This means the first request would get response with a delay, but it is the case anyway.

That sounds pretty close to ideal. I'll try it and see what happens. I wasn't aware of how that service worked, I guess that means there isn't a race with anything other than Whonix VMs, which is good.

**Comment by ArrayBolt3** [comment]
Yep, that worked perfectly. I'll create the override in `qubes-whonix` and then this should be fixed.

Fix implemented: https://github.com/ArrayBolt3/qubes-whonix/commit/34418e335c6ea8d09d018ebda871a2ead4f392c1

**Comment by adrelanos** [comment]
This fix is now in Qubes-Whonix trixie-developers repository.
