### ISSUE TITLE
Macbook installation

### ISSUE THREAD

**Issue by qubesosmacbook** [QubesOS/qubes-issues#4133]
### Qubes OS version:

Hi

I want to install qubes r4.0 on Macbook pro 13" Mid 2012
16GB memory i5 2.5Ghz
ios El capitan
Install is failing. With same hardware installed Fedora 28. No issues except wifi etc but fixing that now... easy fixed with updating the kernel, installing akmod wl and had to update policyreutils-devel and policycoreutils the rpmfusion etc. (if you want to know more about it happy to share but thinking most of the readers already know this and the goal is not fedora but qubes)

What I expect to happen
Flawless installation of Qubes r4.0 on a macbook with a split partition of macbook and ios with an etcher io install of the iso

What happens

All well until running the installer from rEFind 

there is EFI\BOOT\vmlinuz from ANACONDA
Boot Fallback boot loader from ANACONDA
Qube installation freezes at dracut-timeout
Also I get a [FAILED] Kernel load prior to that halfway 
only with the fallback boot loader i get 
(error unable to emunerate usb device, usb 2 and usb 1  it freezes
device not accepting address 5 error 110

dracut initqueue [534] Warning dracut initqueue timeout - starting timeout scripts
then the installer goes into 

dracut:/#

it starts to freeze at sdb1 Attached SCSI removable disk in the installer

What I did

Install iOS
Install Etcher
Install reFind 

Download Qube iso 
Erase USB with ios to format ms dos-fat

Turn off SIP (csrutil status shows disabled)

When selecting the linux installation on refind it loads the qubesinstaller but freezes and gives me a dracut timeout

!-- Type above this line. -->
### Affected component(s): 

Installation of Qubes OS

Is it better to get an SSD and install QubesOS and then keep a partition free then install ios on that partition and use refind to boot? Cause I tried that but that sent me in to the jungle of circular reference.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
