### ISSUE TITLE
Just putting in gpu kills screen.

### ISSUE THREAD

**Issue by p-suedo** [QubesOS/qubes-issues#4148]
### Qubes OS version: 4.0

Heya. I tried putting in gpu. Just attached and put in cords, no drivers.

### Affected component(s): 

Only see the encryption password screen. No splash screen, if type in password, only blank screen. If I shut down, will see cascading stuff before shut down. This is even if screen plugged into motherboard integrated graphics, not gpu.

---

### Steps to reproduce the behavior:

Maybe put gpu in your machine.

### Expected behavior:

Being able to see screen.

### Actual behavior:

Not seeing screen.

### General notes:

gpu = amd radeon rx 580
cpu = intel i7 i think 7700

---

**Comment by Aekez** [comment]
> Only see the encryption password screen. No splash screen, if type in password, only blank screen. If I shut down, will see cascading stuff before shut down. This is even if screen plugged into motherboard integrated graphics, not gpu.

I'm just a normal user like you and not a developer, but I don't think this is a bug.

However this does look like a classic "too new hardware" on Linux problem, which is a general Linux (kernel / Linux-Firmware) problem and not specifically a Qubes problem.
- Remember installing Qubes from fresh will give you an older kernel and linux-firmware package. Hench it's quite possible if you could update Qubes, that a driver would be included to one or both of your graphic chips. But without graphics you can't update, and there is no newer Qubes installer out right now, hence your problem right there.
- There is also a big difference between how quick a hardware developer company releases their Linux drivers, so it may take a while for it to get into the Linux stream.
- Your hardware is just old enough to be considered a grey zone (between hardware release dates and Qubes 4.0. release date), but it's hard to tell from dates alone if its included in the Qubes installer or not, however your symptoms does indicate that they were not included.
- It's normal to be able to see text-mode and basic graphics, i.e. your encryption screen, as these are low-end graphics, and not your high-end graphics loaded from your operative system (and naturally those are encrypted too, so you will naturally be able to see the encryption screen, even if you have no high-end graphic drivers. This typically results in a black screen after the disc encryption lock-in screen, which is when the low-end and high-end graphic drivers get switched.

---

### 1. Dates
Below is just some rough estimates, I haven't spend enough time to find exact info.

**amd radeon rx 580**
- Launch Date: 4/18/2017 
  - Source: https://www.amd.com/en/products/graphics/radeon-rx-580

**Intel® HD Graphics 630** 
You need to be sure of the exact processor, it's not enough to say you think, it needs to be precise, otherwise you can't be sure to find the right driver.
- Assuming you indeed got, i7 7700, then https://ark.intel.com/products/97128/Intel-Core-i7-7700-Processor-8M-Cache-up-to-4_20-GHz shows that you got Intel® HD Graphics 630 integrated graphics.
- Launch date: Not immediately clear from a quick search, but it looks like the windows drivers at least was released in May, 2017. 
  - Source: https://downloadcenter.intel.com/product/98909

**Qubes drivers**
Qubes 4.0. was released, iirc, kernel 4.14, and Linux-Firmware from around Nov. 2017, or so abouts (please correct if wrong).

**Not making it to the Operation system release date**
It may be normal having to wait half a year, at the very least, between new hardware releases, and firmware/drivers in Linux. Furthermore there may be up to a year, two or more, between Qubes releases, and since you have no graphics, you can't just update, you need a new Qubes installer including the drivers. The above dates are not exact days for Linux drivers, but it should be close enough. It looks like you could have gotten a machine with two graphics card, just barely not making it in time to the Qubes 4.0. installer release (and if you use Qubes 3.2., then you most certainly have an installer with mismatching drivers included).

<br /> 

--- 

### 2. If this is indeed too new hardware to match the current Qubes installer
Then it won't be fixed anyway before a new Qubes installer is released, and it won't really be a bug because this is how it normally works right now. It sucks, but it's an on-going hard problem to fix, not only in Qubes but in Linux in general.

<br /> 

---

### 3. A manual work-around solution you can try
You can download newest Kernel and Linux-Firmware from Qubes official repository server. https://yum.qubes-os.org/r4.0/current/dom0/fc25/rpm/
- linux-firmware-20180402-83.git8c1e439c.qubes2.fc25.noarch.rpm 
- Either newest kernel and kernel-qubes-vm packages, or kernel-latest and kernel-latest-qubes-vm. 
  - Kernel-lastest* is less tested, but it is possible you need a newer kernel on some new hardware, even if you got the right Linux-Firmware or other driver packages.

Then verify the downloads with `rpm -K /path/to/your/downloads/*` and remember it needs to be a big capital letter K, and include the * at end to hash check everything in that folder. Also this only works in a template or dom0 which has the Qubes keys, but it shouldn't be a problem if you do it from another Qubes system, otherwise you need to get the key too. Finally, make sure they all check out ok, it might be easy to miss one.

Then you can just throw them on an USB pen with your packages on it, and start Qubes in text mode, which should be possible by replacing quiet, etc. in Grub with the letter 3. (You might want to google that if in doubt).

From there, you can in terminal mount your USB pen and do `sudo dnf install /path/to/your/dom0-packages/on/your/USB/pen/*.rpm`. Then reboot, and if everything went smoothly and there is no other problems, you should have graphics now. That is assuming, your graphic card drivers are included in the newest packages, but it probably is by now since it's been at least over a year between graphic card releases and newest kernel / Linux-firmware packages. Besides both Intel and AMD tend to work pretty ok with Qubes / Linux.

**Other possible solutions**
- You can also pull out the drive and install Qubes on another machine, then update and install newest kernel and linux-firmware, and then put the drive back in your original machine again. But remember there is always a risk that you can contaminate your dom0 if you do it on a machine with exploited firmware.
- If you worry about warranty and don't want to pull out the drives, or dont have the experience, then you can try use something like diskcloning instead. Arch Linux fokes have some good guides there using something as simple as good old dd unix command (but be careful you don't reverse it and instead delete all your data, dd is powerful but also easy to get wrong if you reverse input / output). You can find one of those guides here https://wiki.archlinux.org/index.php/Disk_Cloning it should work for Qubes as well despite being a different OS.
- You may also try build Qubes from scratch, however this might be too much of a hurdle to start learn if you haven't compiled code before. But it may be worth it if you got some experience to lean on, or if you are willing to learn, albeit still a lot of effort either way.
- Last but not least, though probably the least desired solution, is to wait for a new Qubes release. It sucks, but if you don't find a solution that works for you, then you may have to wait for a new release that contain the right driver/firmware/kernel support.

**Final thoughts**
Above is just a quick sketch, I may have forgotten a detail or two, but it should work and I've done it myself in the past (I can verify all mentioned solutions work with Qubes, though some are tougher to pull off than others).

I gather you could at least install Qubes, however if you can't see the installer graphic either, then you may or may not need additional steps to get going. But from what I can see, it seems like you could at least install Qubes, so the above should be sufficient.

### 4. Whether this is a bug or missing driver
Please confirm if this works, if it doesn't work, then perhaps it's indeed a bug instead.

**Comment by qubenix** [comment]
FWIW, I have an MSI RX580 and i7-6700k. I've had this setup on r3.2, and now on r4.0. Both the gpu and integrated graphics work for me. I used the gpu to provide graphics even during install of r4.0.

**Comment by Aekez** [comment]
@qubenix 
Interesting, then he might get it working by trying again on the Raedon card.

The i7 6700 CPU has the Intel® HD Graphics 530 graphic chip though, compared to his Intel® HD Graphics 630 one. But I suppose if your 530 didn't work, then his 630 probably won't work either anyway.

Could it be that you needed to enable your Radeon card in Grub? AMD/Radeon graphics sometimes have that issue after all, and it could explain why it worked for you and not for him in that case.

**Comment by qubenix** [comment]
Yes, both gpu and cpu can provide graphics. No mods to Grub.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
