### ISSUE TITLE
Idea: bind-dirs config that copies to AppVM on creation

### ISSUE THREAD

**Issue by t4777sd** [QubesOS/qubes-issues#4156]
### Qubes OS version:
4.0

### Affected component(s): 
Creation of new AppVM

### Steps to reproduce the behavior:
1. Create a new file /rw/config/qubes-bind-dirs.d/50_user.conf in the TemplateVM and add a bind dir
2. Create a new AppVM
3. In the AppVm look at /rw/config/ and you will see that the bind-dir configuration was not copied from TemplateVM. As a result, the AppVM does not bind the directories as specified in the TemplateVM

* It has been pointed out that none of the files in /rw/config get copied over. So, I propose instead that there is some config maybe /rw/global/config that can copy over in order to let bind-dirs copy on AppVM creation.

### Expected behavior:
While TemplateVMs should not process bind-dirs themselves any corresponding bind-dirs config directory should be copied to the AppVM so that the template can function as a template for bind-dirs on AppVM creation.

### Actual behavior:
Template does not function as a template for AppVMs in respect to bind-dir configuration

### Rational for needing this:
Bind-dirs carrying over to AppVMs on creation of AppVM is essential for many software to work correctly. Off the top of my head the following software will be broken within the AppVM as a result of the failure to carry over:

1. MySQL - data directory
2. Apache - sites-enabled directory
3. Tor - state file

The only work around is to configure software like the above (there are likely dozens) for each AppVM which when someone has many, many VMs becomes really tedious. Bind-dirs being copied on AppVM creation seems logical enough that I suspect this is a bug.

**Comment by unman** [comment]
I dont understand your "Rationale", since it doesn't match my experience of the examples, none of which are broken as a result of the alleged failure.

In fact, if you check you would see that changes made in /rw/config in the template are not carried through to qubes based on it. (Try it with rc.local or the firewall script). So I dont think this is a bug. It's the way that TemplateBasedVMs are implemented. Doing it this way allows you to use one TemplateVM for many different qubes implementing different services and software configurations.

If you want to have the same bind-dirs config across multiple qubes, you should look at the use of salt to configure them and avoid tedium.

**Comment by marmarek** [comment]
It is already possible, see https://www.qubes-os.org/doc/bind-dirs/#other-configuration-folders
You can save such configuration in a place that is shared with TemplateBasedVMs.
