### ISSUE TITLE
add ‘autoremove –purge’ to the update/upgrade default command

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#4178]
### Qubes OS version:

R4.0

### Affected component(s): 

Qubes manager update/upgrade button/mechanism 

sudo apt update && sudo apt dist-upgrade

---

### Steps to reproduce the behavior:

Press on the blue bottom :arrow_down: which is on Qubes Manager to update/upgrade whonix

### Expected behavior:

`sudo apt update && sudo apt dist-upgrade && sudo apt autoremove --purge`

### Actual behavior:

`sudo apt update && sudo apt dist-upgrade`

### General notes:

Qubes default template update mechanism that has some issue when some programs after been upgraded doesn’t need the old components which are as well need to be deleted as its useless to be there for no use so we use 'autoremove' and better to use as well '--purge', but in order to do that we need to open the konsole manually and write that command manually (which is pain in the ..). 

---

**Comment by unman** [comment]
On the principle of least surprise, I would be reluctant to autoremove anything.
Users often get used to programs and functionality that are pulled in with other packages.
I think autoremove would be a mistake.

**Comment by andrewdavidwong** [comment]
Closing as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by TNTBOMBOM** [comment]
@unman im sorry i didint get you , a program got upgraded and there are some trashes residue kept useless there because it has been UPGRADED how come is that useful ???

**Comment by unman** [comment]
On Fri, Aug 24, 2018 at 01:16:35PM -0700, TNT BOM BOM wrote:
> @unman im sorry i didint get you , a program got upgraded and there are some trashes residue kept useless there because it has been UPGRADED how come is that useful ???
> 

Package managers know nothing about usage or user intentions, just about
install/removal history and relations.
That's why your proposal isnt the default.

Here's an example:
User installs libreoffice., and then configures all work related qubes to
use liberation fonts as default. That makes it easy to distinguish work
related activities.
After a while user removes libreoffice. Everything is fine.
Later user upgrades, (your proposal in place), and suddenly work related
apps look like others. Why? Is the font not available anymore? Yes, it is. SO
why did the upgrade remove it?

You see? All the package manager knows is the package was required by
a package that's been removed.
Not every residual package is "trash" or useless, and the package
manager cant distinguish those that are from those that aren't. That's
why it is best left to the user.
(The number of people who post about borking their Qubes by
accidentally deleting Qubes core packages suggests that it may not be
best left to the user either.)

**Comment by TNTBOMBOM** [comment]
i see, im just against the last statement of not leaving to the user to delete or what he wants (if thats what it meant)
