### ISSUE TITLE
sys-net failed to start after the latest kernel update

### ISSUE THREAD

**Issue by irykoon** [QubesOS/qubes-issues#4183]
### Qubes OS version: 

R3.2

### Affected component(s):

 `sys-net` and `sys-firewall`

`sys-usb` is not affected.

---

### Steps to reproduce the behavior:

Reboot the machine after the lastest update by `sudo qubes-dom0-update`:

```
Transaction ID : 
Begin time     : Fri Aug  3
Begin rpmdb    : 1245:edae891c8c1cd7c9830e44a2c1cc16855f9e984b
End time       :           
End rpmdb      : 1255:af78e02325cbd9e97f0d81721912747972d93503
Return-Code    : Success
Command Line   : --exclude=qubes-template-fedora-26-minimal,qubes-template-whonix-gw-14,qubes-template-archlinux,qubes-template-whonix-ws,qubes-template-debian-8,qubes-template-whonix-ws-14,qubes-template-fedora-26,qubes-template-whonix-gw,qubes-template-fedora-28-minimal,qubes-template-fedora-28, upgrade
Transaction performed with:
    Installed     dnf-1.1.10-1.fc23.noarch        (unknown)
    Installed     rpm-4.13.0-0.rc1.13.fc23.x86_64 (unknown)
Packages Altered:
    Install kernel-1000:4.14.57-1.pvops.qubes.x86_64          @qubes-dom0-cached
    Erase   kernel-1000:4.9.45-21.pvops.qubes.x86_64          (unknown)
    Install kernel-qubes-vm-1000:4.14.57-1.pvops.qubes.x86_64 @qubes-dom0-cached
    Erase   kernel-qubes-vm-1000:4.9.45-21.pvops.qubes.x86_64 (unknown)
Scriptlet output:
   1 mke2fs 1.42.13 (17-May-2015)
  10 Failed to install module salsa20-x86_64
  11 Failed to install module salsa20-x86_64
  12 Failed to install module salsa20-x86_64
```

### Expected behavior:

`sys-net` and `sys-firewall` should be started as normal.

### Actual behavior:

`sys-net`, along with `sys-firewall`, failed to start. The error message is as follows:

```
● qubes-netvm.service - Qubes NetVM startup
   Loaded: loaded (/usr/lib/systemd/system/qubes-netvm.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-08-04 
  Process: 2432 ExecStart=/bin/sh -c NETVM=`qubes-prefs --get default-netvm`; [ -n "$NETVM" ] && qvm-start -q --no-guid $NETVM (code=exited, status=1/FAILURE)
 Main PID: 2432 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/qubes-netvm.service

Aug 04 05:41:03 dom0 sh[2432]: xid=super(QubesNetVm, self).start(**kwargs)
Aug 04 05:41:04 dom0 sh[2432]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1979, in start
Aug 04 05:41:04 dom0 sh[2432]: self.libvirt_domain.createWithFlags(libvirt.VIR_DOMAIN_START_PAUSED)
Aug 04 05:41:04 dom0 sh[2432]: File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1059, in createWithFlags
Aug 04 05:41:04 dom0 sh[2432]: if ret == -1: raise libvirtError ('virDomainCreateWithFlags() failed', dom=self)
Aug 04 05:41:04 dom0 sh[2432]: libvirt.libvirtError: libxenlight 'sys-firewall'
Aug 04 05:41:04 dom0 systemd[1]: qubes-netvm.service: Main process exited, code=exited, status=1/FAILURE
Aug 04 05:41:04 dom0 systemd[1]: Failed to start Qubes NetVM startup.
Aug 04 05:41:04 dom0 systemd[1]: qubes-netvm.service: Unit entered failed state.
Aug 04 05:41:04 dom0 systemd[1]: qubes-netvm.service: Failed with result 'exit-code'.
```

### General notes:

I have to set the Default kernel to an older one via qubes-manager to be able to start `sys-net` and `sys-firewall`. Specifically, there are three kernels available in qubes-manager: `4.9.56-21`, `4.14.18-1` and `4.14.57-1`. And both `4.14.18-1` and `4.14.57-1` **doesn't** work.

**Comment by andrewdavidwong** [comment]
Possibly related: #3657

**Comment by frozentime345** [comment]
I have the same issue and the related issue doesn't seem to have a solution(all that downgrade or upgrade stuff just returns libxenlight failed to create new domain 'sys-firewall')?

---My specifics
Qubes R3.2, Laptop: Asus Rog g750gs->running off usb (Sandisk Extreme SDCZ80) for a long while now.
Attached lscpi1.txt, qubeslogs.txt.

I know the issue is the kernel because if I switch to an older kernel in qubes vm manager it works aswell,
for a while now I've been updating and switching to kernel 4.9.56-21 but finally I reached an update that erased 
that kernel(all future kernels have caused this error). I backed up my entire system before updating and have kernel 4.9.56-21 rpms(two files) but on trying to install it
dom0 says "conflicting requests". The issue is the ethernet controller specifically as removing that allows the sys-net to start.


[lscpi1.txt](https://github.com/QubesOS/qubes-issues/files/2408299/lscpi1.txt)
[qubeslogs.txt](https://github.com/QubesOS/qubes-issues/files/2408300/qubeslogs.txt)

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
