### ISSUE TITLE
no longer install emacs and vim by default

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4195]
Qubes and by extension Qubes-Whonix is primarily a desktop focussed operating system. Most users prefer GUI applications over terminal. I am sure emacs and vim are great tools for geeks who like them but there is no need to install these tools by default. Reaons:

* most uers don't use them
* these tools are difficult to learn
* these are messing up the default application (`xdg-open`)

```
DE=generic xdg-mime query default text/plain
emacs24-term.desktop

DE=generic xdg-mime query default text/plain
vim.desktop
```

In other words when double clicking a file or opening from another application it opens in an editor where a non-trivial learning curve is required. An editor where one has to use a search engine or read manual to figure out basic actions such as save file or close file.

After uninstalling both, finally Qubes-Whonix had the desired default editor.

```
DE=generic xdg-mime query default text/plain
org.kde.kwrite.desktop
```

After removing emacs and vim `xdg-open` uses a sane (for most users) default (org.kde.kwrite.desktop).

**Comment by andrewdavidwong** [comment]
See:

https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros

This should probably be an upstream request.

I'll leave it open to see what @marmarek thinks.

**Comment by unman** [comment]
vi, although not emacs, is included in a standard Debian install, and would be expected to be present.
As @andrewdavidwong  says, we have a policy on this, and as @mfc repeatedly points out, we have an open issue #1781 to deal with this sort of case.
The problem is, as the discussion in #1781 demostrates, (courtesy of @andrewdavidwong), 

> a lot of it is just people pushing to make their personal preferences the default with little or no objective justification for doing so.

It seems to me that this is just such a case: a series of assumptions about who uses Qubes, and how they use it. I would not endorse the change for _Debian_ templates.

Of course, there's no reason why the default should not be set in Whonix templates using xdg-mime without changing default Debian, and I'd endorse *that* change.

**Comment by unman** [comment]
In Debian the base system includes all packages with required or important priority - you can check these using searches like:
`aptitude search -prequired -F"%p"`
`aptitude search -pimportant -F"%p"`

By default debootstrap will install these packages: vim is included.
It's possible to limit the packages installed with debootstrap using `--variant=minbase` option - that will still include vim.
Even a "core" installation will install vim and nano. (You can get this using the netinst.iso and have a functioning system with far fewer packages than the base system.)

It's trivial to install Debian without gpg, and indeed Buster will revert to the practice of not including it in the base system.

It seems to me that the packages in (e.g ) packages-stretch.list have been selected to make the Debian templates somewhat closer to the Fedora templates, so they aren't _arbitrary_. In any case it's useful to have those packages set out so that one can see what goes in to a Qubes template. If one questions the inclusion of certain applications then #1781 is intended to cover that sort of discussion.

Naturally, there are situations where double clicking a file will open it in a terminal based editor, depending on what packages one has installed. It just doesn't make sense to say "Debian doesn't have this issue".

Finally, let's not forget that there are Qubes users who do not use Whonix. It seems perverse to remove packages from the **Debian** templates because one doesn't like the effect they have in Whonix. The right thing to do is configure the Whonix templates to use the preferred application in Whonix, (kwrite).

**Comment by adrelanos** [comment]
unman:
> In Debian the base system includes all packages with required or important priority - you can check these using searches like:
> `aptitude search -prequired -F"%p"`
> `aptitude search -pimportant -F"%p"`
> 
> By default debootstrap will install these packages: vim is included.
> It's possible to limit the packages installed with debootstrap using `--variant=minbase` option - that will still include vim.
> Even a "core" installation will install vim and nano. (You can get this using the netinst.iso and have a functioning system with far fewer packages than the base system.)
Alright, all I want is moving closer to Debian defaults. If vim and nano are installed either way, then that doesn't speak against merging https://github.com/QubesOS/qubes-builder-debian/pull/17 ?
> It seems to me that the packages in (e.g ) packages-stretch.list have been selected to make the Debian templates somewhat closer to the Fedora templates, so they aren't _arbitrary_.
Make which template closer to which one? Fedora to Archlinux or why are Debian and Fedora privileged for being made uniform?

What's the rationale of making templates closer to each other? Why offer different templates when then making them as uniform as possible?

Should we make a survey of packages installed by default in Fedora and install them by default in Debian and vice versa? I am not advocating that, I am just trying to point out the inconsistencies.

> In any case it's useful to have those packages set out so that one can see what goes in to a Qubes template.
packages_stretch.list doesn't help to see what goes into Qubes templates easily. packages_stretch.list is only a tiny subset of all non-Qubes Debian default applications. packages_stretch.list is only a tiny subset of all applications installed in a Qubes Debian stretch template.

To answer the question "Which packages are installed by default in a Qubes Debian template" it's easier to answer

A)
[1]
`aptitude search -prequired -F"%p"` / `aptitude search -pimportant -F"%p"`" / plus Qubes packages plus dependencies.

Rather than than answer B)

"[1] plus packages_stretch.list" (which includes packages which are included in [1] anyhow)"

> Naturally, there are situations where double clicking a file will open it in a terminal based editor, depending on what packages one has installed. It just doesn't make sense to say "Debian doesn't have this issue".

But double clicking a simple text file in a terminal based editor shouldn't be the Qubes default if the Qubes Debian template if that is not also the default in non-Qubes Debian?

> Finally, let's not forget that there are Qubes users who do not use Whonix. It seems perverse to remove packages from the **Debian** templates because one doesn't like the effect they have in Whonix. The right thing to do is configure the Whonix templates to use the preferred application in Whonix, (kwrite).
When there is a bug in a lower level (packages_stretch.list is processed during the Whonix build process since it is a flavor on top of the Debian template), you fix the bug in the lower level and don't add workarounds (uninstall packages) on the higher level.

Qubes documentation to open files:

Do we reference `nano`, `kwrite` or `gedit`? Sometimes instructions are in essence the same for all templates. (Such as [open Qubes user firewall scripts](https://www.qubes-os.org/doc/firewall/).)

But the default editor differs per template. So which editor should the documentation pick by default?

"none" would be best. The distribution/template agonistic way to go about it is `xdg-open`. Usually in Debian, Whonix and I guess Fedora and others as well `xdg-open` does the right thing. It does not so in Qubes Debian based template.

I think sticking with distribution defaults is a good, most easy to maintain, least bug prone way. But then we shouldn't mix it up with "make Debian closer to Fedora template" because then we are messing up mime types and files open in terminal based editors by default.

me wrote:

> Qubes and by extension Qubes-Whonix is primarily a desktop focused operating system. Most users prefer GUI applications over terminal. I am sure emacs and vim are great tools for geeks who like them but there is no need to install these tools by default. Reasons:

@unman quoted:

>> a lot of it is just people pushing to make their personal preferences the default with little or no objective justification for doing so.

@unman wrote:

> It seems to me that this is just such a case: a series of assumptions about who uses Qubes, and how they use it. 

Alright. Let's justify it better. Starting with the project goals and then making deduction from that.

Assumptions:

* Qubes wants to be popular (high number of users).
* Qubes wants to provide good usability. Usability designer @bnvk used to work on Qubes and I learned a lot during that time.

Are these agreed or contested or did I miss an update and things changed?

When I say "good usability" I mean things should be doable by most "normal" people, let's say that >=90% desktop computer users who are currently using Windows and finding Linux, let alone Qubes too complicated.

Facts:

* vim / emacs do not provide good usability.
* In extension terminal based editors don't provide good usability.
* Therefore double clicking a simple text file shouldn't result in opening the file in a terminal based editor. That's a usability bug?

Is agreed or contested that double clicking a simple text file in a terminal based editor is a usability bug?

If that is agreed, how to we solve that usability bug? As said, I think it's easiest to follow Debian default applications and to drop most of packages_stretch.list and to cover it using the usual Debian mechanism.

**Comment by h01ger** [comment]
On Fri, Aug 10, 2018 at 03:20:00AM -0700, cfcs wrote:
> I agree with @adrelanos that double-clicking a text file should not open `emacs` or `vim`. I don't personally double-click anything, but I appreciate that that must be a frustrating experience to end-users, of which Qubes has a decent proportion.
> 
> Really, I think the issue here should be about making the default double-click action do something sensible.

both emacs and vim have an X mode, so that's not entirably
unreasonable...

and I'd also foresee that many people will be frustrated if emacs or vim
are not installed.

I also think this depends on the desktop environment one uses: and then
I think that xdg-open should (be configured to) use some kde editor
(I guess kate) if kde is the desktop, some other graphical (non kde) editor
if xfce is used (so mousepad probably) and if i3 is used IMO its only the
question whether to use vim or emacs ;)

Installing kate (and all the kdelibs) everywhere seems to be pretty bad
to me.

Finally, please use recommends, not depends, for editors.


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
                    holger@(debian|reproducible-builds).org

**Comment by unman** [comment]
I'm with @h01ger on this.
I dont see large numbers of complaints about the current situation, and users are free to install whatever packages they like. Some of these (e.g libreoffice) seem to become default apps for text/plain - others don't. That's an upstream issue.

If it's an issue in Whonix where it's preferred to control user applications more tightly, for understandable reasons, then configure the Whonix templates as desired. This shouldn't impact other Qubes users, or Whonix users using non-Whonix templates.

> Facts:
> 
> vim / emacs do not provide good usability.
> In extension terminal based editors don't provide good usability.
> Therefore double clicking a simple text file shouldn't result in opening the file in a terminal based editor. That's a usability bug?
> 
> Is agreed or contested that double clicking a simple text file in a terminal based editor is a usability bug?

These are not facts, and I wouldn't characterise it as a usability bug. "Normal people" are capable of using vi - maybe not emacs - or installing a different text editor if they prefer.

The question of what applications should be used should be dealt with in  #1781 - correctly configuring the Whonix templates should be a separate issue.
Following the Debian default means retaining installed vi/vim - the choice of default editor is up to the user.

**Comment by cfcs** [comment]
- @unman "normal people" are definitely not capable of using vim without detailed instructions, most Qubes users I know don't know what neither vim nor emacs is, and are intimidated by the command-line. I'm not trying to get into an editor war here; I personally use both vim and emacs, and think they're good for different purposes.
I know from experience that vim is much less intuitive than emacs since at least you can start typing right away in emacs - I've had to helped freaked out users with this. I agree that basic operation of `vim` is not hard to learn, but it's definitely not intuitive.
Both are somewhat alien to users who are used to GUI and Windows or OSX shortcuts, and you can easily get stuck in weird modes where nothing you type shows up in your document, or bad stuff happens.

- I think the `recommends` vs `depends` thing for the debian template is very sensible.

- I don't really have an opinion on whether or not to remove either of these. I think there are definitely other things that would make more sense to remove if we're optimizing for space all of a sudden (cups?!?!)

**Comment by unman** [comment]
The standard Debian way would be to create /usr/share/applications/mimeapps.list with content:
```
[Default Applications]
text/plain=org.kde.kwrite.desktop
```
Put this in the Whonix-ws template and the issue should be resolved.

**Comment by unman** [comment]
@cfcs 

> "normal people" are definitely not capable of using vim without detailed instructions,

our experiences differ

**Comment by marmarek** [comment]
I agree with @adrelanos here. The current state is not great given https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros. AFAIR the list constructed by @nrgaway was based on tasksel initially, but for some reason not used directly. And since then it diverged significantly.

There is another related issue - the current Debian template is rather minimal (for example missing file manager, as mentioned in #1781). I think the solution for this is to rename the current template to -minimal (after cleaning up packages_*.list), then use tasksel to produce actual non-minimal Debian template. It should include whatever default applications are installed in Debian, including choice of editor(s), browser(s), file manager(s) etc. If anything, we should tweak at tasksel group selection level, preferably not individual packages.

**Comment by unman** [comment]
I've put in a PR to install nautilus in Default Debian template as per #1781. 
It seems to me that's the right place to deal with these issues, not here. Though I have suggested that the lack of discussion on that issue means it should be closed and that a default application list be set by fiat.

The real issue here was this: Qubes-Whonix did not have the desired default editor set to kde,write
The solution to this is **not** to uninstall vim, which is, as I pointed out, a core part of every Debian install, even base system. It's to configure the Whonix templates properly for default applications.
This can be done by creating /usr/share/applications/mimeapps.list

By default installing gimp makes it the default application for opening PDF files. The solution is *not* to remove gimp, but to configure the system as one wants.

I think the current situation leaves maximum choice in the hands of the user.
The current template is not minimal: that's a separate target.
If it's desired to ship a full template, there's the existing stretch+gnome.

**Comment by h01ger** [comment]
On Thu, Sep 06, 2018 at 11:26:52PM +0000, Marek Marczykowski-Górecki wrote:
> There is another related issue - the current Debian template is rather minimal (...)
> I think the solution for this is to rename the current template to -minimal
> (after cleaning up packages_*.list), then use tasksel to produce actual
> non-minimal Debian template. 

yes. probably even more than one-minimal kind: xfce & gnome & kde, I
guess.


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by h01ger** [comment]
On Fri, Sep 07, 2018 at 05:01:24AM -0700, Holger Levsen wrote:
> On Thu, Sep 06, 2018 at 11:26:52PM +0000, Marek Marczykowski-Górecki wrote:
> > There is another related issue - the current Debian template is rather minimal (...)
> > I think the solution for this is to rename the current template to -minimal
> > (after cleaning up packages_*.list), then use tasksel to produce actual
> > non-minimal Debian template. 
> 
> yes. probably even more than one-minimal kind: xfce & gnome & kde, I
> guess.

I meant: probably even more than one non-minimal kind: xfce & gnome &
kde...


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by adrelanos** [comment]
> The real issue here was this: Qubes-Whonix did not have the desired default editor set to kde,write

This is not a Whonix-only issue.

> The solution to this is not to uninstall vim, which is, as I pointed out, a core part of every Debian install, even base system.

Keep vim - with cleaning up packages_*.list + taskel solution this will be ok most likely in most cases.

> It's to configure the Whonix templates properly for default applications.
> This can be done by creating /usr/share/applications/mimeapps.list

This seems like a bandaid. It seems wrong for a distribution to take over file `/usr/share/applications/mimeapps.list`.

With cleaning up packages_*.list + taskel this won't be necessary.

**Comment by unman** [comment]
> This is not a Whonix-only issue.

I meant that it is a problem that has surfaced in Whonix. It hasn't arisen on the Qubes mailing lists, for example, although there are plenty of Debian users.

> This seems like a bandaid. It seems wrong for a distribution to take over file /usr/share/applications/mimeapps.list.

That is the canonical place for distributions to store preferences. (https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-1.0.html). 
It's ideal for Whonix, or indeed Qubes, to use that file to set defaults if wanted.
It's always open to users to override that setting should they wish.

**Comment by marmarek** [comment]
Regardless of proper solution for default editor problem, https://github.com/QubesOS/qubes-builder-debian/pull/17 is about not installing vim/emacs in base template (aka minimal) - note it modifies packages_stretch.list, not packages_stretch_standard.list.
@unman would you be ok with moving vim/emacs to `packages_*_standard.list`, instead of removing them, at least until proper solution gets implemented?

**Comment by unman** [comment]
That seems like a good compromise. Nano and Vim will still be available in minimal templates, but I assume that won't be problematic.

**Comment by adrelanos** [comment]
unman:
>> This is not a Whonix-only issue.
> 
> I meant that it is a problem that has surfaced in Whonix. It hasn't arisen on the Qubes mailing lists, for example, although there are plenty of Debian users.

I remember having seen a few, and having experienced a few:

* https://github.com/QubesOS/qubes-issues/issues/1603
* https://github.com/QubesOS/qubes-issues/issues/1773
* maybe more here https://github.com/QubesOS/qubes-issues/issues?utf8=%E2%9C%93&q=mimetype or on google when spending time finding them

>> This seems like a bandaid. It seems wrong for a distribution to take over file /usr/share/applications/mimeapps.list.
> 
> That is the canonical place for distributions to store preferences. (https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-1.0.html). 
> It's ideal for Whonix, or indeed Qubes, to use that file to set defaults if wanted.
> It's always open to users to override that setting should they wish.
> 
If Qubes was to own /usr/share/applications/mimeapps.list using a package, then Whonix couldn't own the same file without dpkg refusing to install a second package owning the same file without workarounds (config-package-dev displace perhaps). Getting more and more messy the more distriubtions stack up (perhaps one day Qubes Debian template -> Qubes-Whonix -> [Qubes-Whonix-Securedrop](https://securedrop.org/news/road-towards-integrated-securedrop-workstation/))

So I guess we'd better extend environment variable XDG_DATA_DIRS and then use $XDG_DATA_DIRS/applications/mimeapps.list.

**Comment by marmarek** [comment]
> So I guess we'd better extend environment variable XDG_DATA_DIRS and then use $XDG_DATA_DIRS/applications/mimeapps.list.

Yes, that sounds more flexible. It may be better idea to use "Removed Associations" section to blacklist vim/emacs (and maybe gimp as pdf viewer), instead of setting explicit defaults.

Specification says also about `$desktop-mimeapps.list`, so alternative could be whonix providing own file and setting `$desktop` (it seems to be actually `$XDG_CURRENT_DESKTOP`) to "whonix".

**Comment by adrelanos** [comment]
Sounds good.

(Changing `XDG_CURRENT_DESKTOP` could have some side effects, trigger some bugs in `xdg-open` or so.)
