### ISSUE TITLE
qubes-core-agent debian package depends on xserver for no apparent reason

### ISSUE THREAD

**Issue by a-barinov** [QubesOS/qubes-issues#4202]
### Qubes OS version:

4.0

### Affected component(s): 

qubes-core-agent debian package

---

### Steps to reproduce the behavior:

Remove qubes-gui-agent

### Expected behavior:

xserver-xorg-core, xinit and x11-xserver-utils removed

### Actual behavior:

xserver-xorg-core, xinit and x11-xserver-utils stay in the system as qubes-core-agent depends on them. The headless qube works just fine without gui.

### General notes:

Qubes supports headless debian qubes just fine. Qubes-core-agent works and does not attempt to start xserver after qubes-gui-agent is uninstalled. Therefore qubes-core-agent dependency on xserver-xorg-core, xinit and x11-xserver-utils should either be removed or changed from "depends" to "recommends".

---

**Comment by unman** [comment]
This isn't specifically a Debian issue, I think.
Removing qubes-gui-agent from a Fedora template make it unbootable, afaik.

So the question should be how best to support headless qubes.

Incidentally, there's no reason to suppose that removing qubes-gui-agent would itself remove xserver-xorg-core, xinit and x11-xserver-utils. And keeping them on the system doesn't seem to be a problem to me.
@a-barinov Can you clarify what the issue is with having those packages installed?

**Comment by marmarek** [comment]
>  Removing qubes-gui-agent from a Fedora template make it unbootable, afaik.

If that's the case, it is a bug. It may be needed to set `qvm-features VMNAME/TEMPLATENAME gui ''` manually, though.

Anyway, the bug is about qubes-*core*-agent package depending on xserver, not qubes-*gui*-agent.

**Comment by a-barinov** [comment]
There is no issue with xserver-xorg-core, xinit or x11-xserver-utils being
installed. The issue is *qubes-core-agent* package formally depends on
xserver package while there is no real dependency. Additionally this means
that I have xserver installed in my headless qubes (firewall, tor, etc)
creating additional attack surface there by bringing some suid binaries
with it.
