### ISSUE TITLE
DVM  Templates should be non-networked by default

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4226]
Reason? It's a template. Same reasons as for making TemplateVMs non-networked by default.

**Comment by unman** [comment]
Since *any* qube can now be a DVM Template I dont see how this would work in practice. It seems to run against the extension of DispVMs in 4.0.

**Comment by DemiMarie** [comment]
In particular, this does not work for whonix-ws-dvm, which must be able to access the network to update Tor Browser.

**Comment by adrelanos** [comment]
unman:
> Since *any* qube can now be a DVM Template I dont see how this would work in practice.

> It seems to run against the extension of DispVMs in 4.0.
 
Could you please elaborate?


If convincing... Maybe only default DVM's?

What's the use case where DVM's require networking?

What about giving DVM's access to internet through Qubes updates proxy?

Demi Marie Obenour:
> In particular, this does not work for whonix-ws-dvm, which must be able to access the network to update Tor Browser.
> 
Running Tor Browser Update in Whonix DVM is discouraged:

https://www.whonix.org/wiki/Tor_Browser/Advanced_Users#tb-updater_in_Qubes_DVM_Template

I am the founder and a developer of Whonix btw.

**Comment by unman** [comment]
> Could you please elaborate?

In 4.0 it's possible to set any qube as a DVM Template, so that one can create disposable instances of that qube.
The disposable instances inherit the netvm and firewall of the qube which acts as DVM Template.

This allows one to (e.g) test all sorts of system changes and configurations on a disposable version of "work" without endangering the actual "work" qube.
The intention is not to constrain the qube that is used as DVMTemplate but to extend its possibilities.

> What's the use case where DVM's require networking?.

Where the qube acting as DVMTemplate requires networking. (This isn't really an answer at all, but it's the best I can do.)

> If convincing... Maybe only default DVM's?

Perhaps, but I dont see that default DVM's are privileged in any way, and most users would expect to have a fully working DisposableVM, (that uses the default netvm setting), out of the box.

It's always possible to clone a qube and change the netvm/firewall for the clone so as to have networked and non-networked disposableVMs based on the original qube. The overhead is small.

>  I am the founder and a developer of Whonix btw.

:+1:

**Comment by marmarek** [comment]
Closing for the reasons explained by @unman - mostly because DVM Template's settings are directly applied to DispVMs, so network-less DVM Template would result in network-less DispVM.
Considering it intended case is already covered in #1121
