### ISSUE TITLE
XSA-273: L1 Terminal Fault

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4252]
### Qubes OS version:

All

### Affected component(s): 

Xen, dom0 kernel

---

### Steps to reproduce the behavior:

Run `cat /sys/devices/system/cpu/vulnerabilities/l1tf` in dom0

### Expected behavior:

```
$ cat /sys/devices/system/cpu/vulnerabilities/l1tf
Mitigation: PTE Inversion
VMX: SMT disabled
L1D cache flushes
```

### Actual behavior:

```
$ cat /sys/devices/system/cpu/vulnerabilities/l1tf
cat: /sys/devices/system/cpu/vulnerabilities/l1tf: No such file or directory
```

### General notes:

This indicates that Qubes is vulnerable to L1 Terminal Fault attacks, which can result in compromise of arbitrary data located in any Qubes domain.  Since this includes LUKS keys, this cannot be fully mitigated by not running sensitive and untrusted code simultaneously.

This bug is already known to affect Xen (XSA-273), and has already been brought up on the qubes-users mailing list.  As such, it is rather shocking that no QSB has been issued, nor does the XSA tracker make any mention of this XSA.

---

**Comment by andrewdavidwong** [comment]
> This bug is already known to affect Xen (XSA-273), and has already been brought up on the qubes-users mailing list. As such, it is rather shocking that no QSB has been issued, nor does the XSA tracker make any mention of this XSA.

You must have missed this:

https://groups.google.com/d/msg/qubes-users/Isn_hko7tQs/PcqIuUleEQAJ

**Comment by DemiMarie** [comment]
Yes, I did miss it.  That makes sense.  How difficult would it be to
preemptively push out an updated Xen package?

**Comment by andrewdavidwong** [comment]
> Yes, I did miss it.  That makes sense.  How difficult would it be to
preemptively push out an updated Xen package?

You mean before @marmarek gets back? I don't have any way to do that, so unless someone else like @woju or @omeg does, it won't happen before then.

**Comment by HW42** [comment]
Now, there's https://github.com/QubesOS/qubes-vmm-xen/pull/45 for people who can/want build it themselves.

> You mean before @marmarek gets back? I don't have any way to do that, so unless someone else like @woju or @omeg does, it won't happen before then.

In principle they should both be able to do so since their keys are in https://github.com/QubesOS/qubes-builder/blob/master/qubes-developers-keys.asc, so the builder infrastructure should accept tags signed by them.

**Comment by HW42** [comment]
@DemiMarie: AFAIU the dom0 kernel doesn't need to be patched.

**Comment by lunarthegrey** [comment]
Packages got pushed 6 hours ago that set smt=off in your grub configuration. https://github.com/QubesOS/updates-status/issues/642

Does anyone know the impact this will have on performance? I just updated to the new xen binaries from the qubes-dom0-current-testing repository.

**Comment by andrewdavidwong** [comment]
We have just published Qubes Security Bulletin (QSB) #43: L1 Terminal Fault speculative side channel (XSA-273).

https://www.qubes-os.org/news/2018/09/02/qsb-43/

**Comment by taradiddles** [comment]
FWIW performance is catastrophic after the l1tf updates on my thinkpad T450s (i7-5600). What used to be an expensive "state-of-the-art" laptop 2 years ago is now as useful as an electrical heater, to the point that I'm considering ditching all those security fixes and live with the vulnerabilities :(

Eg.:
- without apps or cpu-intensive background services running in VMs, power consumption doesn't drop below 11W, compared to ~ 6W before (which is still quite higher than the power consumption of stock fedora, but that's another topic).
- loadavg is > 0.30 
- `xentop` doesn't show anything striking but the fan is always on, between mid to full speed, which never used to be the case.

I'll try to disable the "fixes" one by one when time allows to see what causes the high loadavg, which is probably the reason for the increased power consumption and the fan kicking in. (Meanwhile, any suggestions welcome).

**Comment by marmarek** [comment]
R3.2 or R4.0? In case of R3.2, make sure VMs use updated kernel, otherwise fallback mitigation may kick in, which greatly reduce performance (look for `L1TF-vulnerable L1e ,,, - Shadowing` in `xl dmesg`).

**Comment by lunarthegrey** [comment]
I have the same CPU as @taradiddles and I've noticed an increase in heat coming from the laptop as well (I'm running 4.0). I was expecting this though, as disabling SMT is going to make the CPU work harder. I wonder if we'll ever be able to enable SMT safely again?

**Comment by taradiddles** [comment]
I'm not convinced SMT (or lack thereof) is the culprit here: SMT helps in some cases but may also be detrimental in others (eg. scientific simulations, hpc, ...).
Also, from the redhat doc you linked:

> Disabling HT in environments with less than ~50% cpu utilization usually showed no performance impact. Disabling HT in environments with higher cpu utilization yields a serious performance drop

(I clearly should be under 50% cpu utiliziation with only a browser + mail client appvms).

I'll try to turn SMT back on later today for tests.

**Comment by taradiddles** [comment]
@lunarthegrey: I guess you're right...

I just did a quick test with smt=on: the laptop's fan stays off or runs at very low speed, and power consumption is back to ~6W on battery.

But quite oddly, loadavg and xentop "metrics" are worse (loadavg @ 0.80, `xentop` shows ~20% usage by dom0, and ~14% for sys-{usb,net}-dm, `top` shows 96% idle). No idea how those were before the updates, but those metrics don't seem to be meaningful/representative of the performance problem.
Measuring the time spent by the system doing context switches may provide a better metric. Which makes me think of trying to lower each VM's nb. of cpus to 1 and pin the physical cores to each running VM. That'll be for the next test... (I'll edit the post accordingly).

**Comment by airelemental** [comment]
With smt=on, I see similar xentop cpu usage of ~14% for HVMs.
With smt=off, during some sessions, xentop halves all the cpu usage(?).
Overall, I haven't seen any deterioration of my user experience with smt=off. (Maybe because I have a quad-core cpu and hardly ever use >400% cpu before.)

**Comment by taradiddles** [comment]
@airelemental : are you using a laptop ? If yes, it may be interesting to compare the power consumption on battery with both smt=on and smt=off since it's the only "reliable" metric I've found for now.

I've kept smt=on since my last comment because I can't work on my laptop with smt=off, but I've tried to disable two theads (one on each core) from the cpu pool, with `xl cpupool-cpu-remove Pool-0 XX` (XX = 1 and 3 resp.). My reasoning is that using only one thread per core *should* be the same as disabling HT. However I'm not seeing any performance degradation so I expect to be wrong - otherwise xen's people would have disabled the cpu threads instead of turning off HT completely. It'd be interesting to hear what @marmarek thinks about that...

**Comment by airelemental** [comment]
On my laptop, my power consumption is either unchanged or somewhat improved compared to before.

**Comment by eug48** [comment]
Does the stubdom still need to be updated? I'm getting intermittent crashes of the "-dm" stubdom of a Window 10 VM.

xl dmesg:
(XEN) d30 L1TF-vulnerable L1e 0000000008800000 - Crashing
(XEN) domain_crash called from /home/user/rpmbuild/BUILD/xen-4.8.4/xen/include/asm/shadow.h:185
(XEN) Domain 30 (vcpu#1) crashed on cpu#6:
(XEN) ----[ Xen-4.8.4  x86_64  debug=n   Tainted: M    ]----
...

...-dm.log:
Linux version 4.14.57-xen-stubdom (user@build-fedora4) (gcc version 6.4.1 20170727 (Red Hat 6.4.1-1) (GCC)) #1 Mon Jul 23 01:07:34 UTC 2018
...

**Comment by marmarek** [comment]
Yes, that looks to be the case.

@HW42 that's interesting, as stubdomain don't have swap, any idea?

**Comment by eug48** [comment]
Thanks, the stubdomain hasn't crashed for 2 days now.

**Comment by marmarek** [comment]
@taradiddles Have you changed vcpus count for any VM? If so, you may need to adjust it for reduced CPU threads. Basically make sure it's not bigger than available threads.
See `qvm-ls --fields name,vcpus`

**Comment by taradiddles** [comment]
@marmarek Yes I did change the vcpus to '2' back then.
I'm still with `smt=on` and I've [removed](https://github.com/QubesOS/qubes-issues/issues/4252#issuecomment-419055538) a thread on each core from the cpu pool thinking it should be equivalent to turning off smt. No idea if that migitages the exploit though.
The odd thing is that performance was OK after a reboot with `smt=off` until I resumed the laptop so I'm wondering if there's not something related to the custom power management scripts that I have installed, given that I seem to be the only one with this problem (IIRC @andrewdavidwong also has a T450s, I guess we'd have heard from him if he had the same problem). I'll try to disable the scripts and see what happens when I have a bit more time.

**Comment by 3hhh** [comment]
> FWIW performance is catastrophic after the l1tf updates on my thinkpad T450s (i7-5600). What used to be an expensive "state-of-the-art" laptop 2 years ago is now as useful as an electrical heater, to the point that I'm considering ditching all those security fixes and live with the vulnerabilities :(

I can confirm that I felt roughly the same with a T530 i5 dual core 3rd gen after hyperthreading was disabled. Even playing music would stutter on R4 with 8-10 VMs. I guessed it was the increased necessity for context switches.

After upgrading the laptop to an i7 quad core the issue went away.

**Comment by tfm1** [comment]
> @marmarek Yes I did change the vcpus to '2' back then.
> I'm still with `smt=on` and I've [removed](https://github.com/QubesOS/qubes-issues/issues/4252#issuecomment-419055538) a thread on each core from the cpu pool thinking it should be equivalent to turning off smt. No idea if that migitages the exploit though.
> The odd thing is that performance was OK after a reboot with `smt=off` until I resumed the laptop so I'm wondering if there's not something related to the custom power management scripts that I have installed, given that I seem to be the only one with this problem (IIRC @andrewdavidwong also has a T450s, I guess we'd have heard from him if he had the same problem). I'll try to disable the scripts and see what happens when I have a bit more time.

You are not the only one. I'm using a Thinkpad X1 Carbon 6gen and after suspend/resume with `smt=off` CPU temperature rises by 10C. I did not experience any noticable performance loss, but I guess I didn't do anything where I would notice. I only noticed that I got annoyed by the fan running more often/louder. The increase in temperature was reproduced by one other X1C6 owner on qubes-users.

If I go with `smt=on` but hyperthreading disabled in BIOS, the issue does not arise.

**Comment by szymonmatuszczak** [comment]
How do you measure the power consumption? Do you have your battery removed, to prevent measuring the battery charge current?

**Comment by taradiddles** [comment]
@tfm1 - thanks for the report ; it looks like I'm not the only one with that problem then. Still didn't have any time to test with my power saving tweaks disabled but since you have the same issue the tweaks are probably not related (or maybe they exacerbate it). I can't test with hyperthreading disabled in BIOS - the thinkpad I have doesn't have such option...

@szymonmatuszczak : simply unplug the laptop and look at `/sys/class/power_supply/BAT*/power_now` (actually I have a script that display my batteries' status in xfce's panel based on those values). Note that depending on the laptops the values may take time to stabilize; eg. they were nearly real-time on my old t400 IIRC but it now takes half a minute to a minute to get a meaningful value on the t450s I have now.

**Comment by donob4n** [comment]
@szymonmatuszczak you can also use powertop (available from qubes-dom0-update)

**Comment by andrewdavidwong** [comment]
@esote: It looks like @marmarek is still merging commits from @fepitre for this. I expect to see this issue closed from such a commit when they consider it to be done. Closing before that could be problematic if it results in things being forgotten or inadvertently deprioritized.

**Comment by esote** [comment]
Ah, good point. I didn't notice the timestamp on those commits. Thanks!
