### ISSUE TITLE
Presentation mode in the battery monitor doesn't prevent the screensaver

### ISSUE THREAD

**Issue by gasull** [QubesOS/qubes-issues#4275]
### Qubes OS version:

R4.0

### Affected component(s): 

---

### Expected behavior:

The battery monitor panel item has the option "Presentation mode".  Clicking on the checkbox should prevent the screensaver from starting.

### Actual behavior:

Checking the box for "Presentation mode" doesn't have any effect on the screensaver.  It's activated after the usual interval.

### General notes:

---

**Comment by andrewdavidwong** [comment]
Which DE are you using?

**Comment by gasull** [comment]
> Which DE are you using?

The default one:  Xfce.

I think the only things I changed are:

1. Applications > System Tools > Screensaver > Display Modes > Blank After: 9 minutes; ☑️ Lock Screen After: 1 minutes
1. Applications > System Tools > Appearance > Style > Industrial

**Comment by esote** [comment]
I checked and I also have this issue with XFCE.

**Comment by tasket** [comment]
FWIW, this feature (among many others not working in Xfce) does work in KDE5. I should start making a list...

**Comment by imme-emosol** [comment]
What the "presentation mode" could do, probably through dom0;
enable presentation mode: xscreensaver-command -exit
disable presentation mode: xscreensaver && disown

**Comment by liketechnik** [comment]
Any update on this? Or a hint how to apply above "fix" on my local system?

**Comment by sptankard** [comment]
@liketechnik I'm not sure i know how to get the xfce feature to work, but you might be able to get desired behavior (ability to watch movies without interruption...etc) by settings the xscreensaver settings directly. See here: https://www.jwz.org/xscreensaver/faq.html#dvd 

> When you want to watch a movie, fire up xscreensaver-demo and select Mode: Disable Screen Saver from the option menu, which means not to blank the screen at all. When you're done watching the movie, re-select your previous mode. 
> [...] If you are trying to use XFCE's "Presentation Mode"... don't. It breaks everything. Use XScreenSaver's "Disable Screen Saver" mode instead.

I haven't done this myself so can't guarantee how well it works. They also suggest two player-specific options (mplayer and vlc), which i assume WILL NOT work in qubes because they can't, and shouldn't, access dom0.

For some context/background, there seem to be a lot of problems caused by using `xfce4-power-manager` and `xscreensaver` (especially together). They compete/conflict.

For anyone coming across this thread and for future documentation, here's some links providing context:
https://forum.xfce.org/viewtopic.php?id=8154
https://bugzilla.xfce.org/show_bug.cgi?id=10205
https://bugs.launchpad.net/ubuntu/+source/xscreensaver/+bug/924278
https://www.jwz.org/xscreensaver/faq.html#dvd
https://www.jwz.org/xscreensaver/faq.html#no-blank
https://docs.xfce.org/xfce/xfce4-power-manager/preferences

And a (non-exhaustive) list of related Qubes issues...

https://github.com/QubesOS/qubes-issues/issues/3590
https://github.com/QubesOS/qubes-issues/issues/3674
https://github.com/QubesOS/qubes-issues/issues/3727
https://github.com/QubesOS/qubes-issues/issues/3898

**Comment by tlaurion** [comment]
@fepitre @marmarta @marmarek  : this is sadly a missing feature and is totally giving a bad image to QubesOS since expected to work by default since the option is presented but not working.

**Comment by andrewdavidwong** [comment]
We have a similar [thread](https://qubes-os.discourse.group/t/cannot-disable-the-dom0-xscreensaver-5-4-3-locking/894/) about this on the forum. There, I [wrote](https://qubes-os.discourse.group/t/cannot-disable-the-dom0-xscreensaver-5-4-3-locking/894/13?u=adw):

> Lately, I’ve found that if I just want to watch a movie or something without the screen locking or turning off, it works to make these two changes:
> 
> 1. XScreenSaver Settings -> Display Modes -> Mode -> Disable Screen Saver
> 2. XScreenSaver Settings -> Advanced -> (uncheck) Power Management Enabled
> 
> I usually leave the XScreenSaver Settings window open in the background so that I don’t forget to change the settings back afterward. :slightly_smiling_face: 

It's not exactly the same as being able to toggle presentation mode, but some people might find it helpful as a workaround in many situations.

**Comment by burningrooftop** [comment]
This is a solution which works for me (ie. the Presentation Mode check box in power manager stops xscreensaver from activating):

Use **System Tools** > **Settings Editor** to add a new setting:

**Property:** /xfce4-power-manager/heartbeat-command
**Type:** String
**Value:** xscreensaver-command -disable

I assume you could also use xfconf-query to add the setting, but I haven't tried that myself.

See this [bug report](https://bugzilla.xfce.org/show_bug.cgi?id=11083) for details. The heartbeat-command setting doesn't seem to be well documented.

**Comment by rustybird** [comment]
> **Property:** /xfce4-power-manager/heartbeat-command
> **Type:** String
> **Value:** xscreensaver-command -disable

Neat! But the `xscreensaver-command` argument  should be `-deactivate` (there is no `-disable`).

> I assume you could also use xfconf-query to add the setting, but I haven't tried that myself.

This works:

    $ xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/heartbeat-command -n -t string -s 'xscreensaver-command -deactivate'

For added safety, I also automatically turn Presentation Mode off again whenever the screen is locked (by hotkey or anything else that invokes the `xflock4` script):

    $ xfconf-query -c xfce4-session -p /general/LockCommand -n -t string -s 'eval xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode -s false; xscreensaver-command -lock'

**Comment by burningrooftop** [comment]
You are correct of course - it is -deactivate. I like the idea of disabling presentation mode when the screen is locked too - I'll try that. Thanks for the feedback.
