### ISSUE TITLE
[Feature] More Desktop Enviorments

### ISSUE THREAD

**Issue by asddsaz** [QubesOS/qubes-issues#4288]
**Feature**: More Desktop Enviorments

**Longer Summary**: Official documentation for using major DEs such as MATE, Cinnamon, lxde, and my personal favorite Pantheon. 

**Why**? More customization and ease of use.
The "Q" of course, would would most likely need to stay.

**Comment by andrewdavidwong** [comment]
This is not likely to be done except via external contributions. It seems likely that a given contributor will contribute code support or a package for a single DE, rather than all the DEs you've listed here. Therefore, I think it makes more sense to open separate GitHub issues, where each issue is about supporting a single DE. You might consider first starting a general thread about this in qubes-devel, then only opening the specific issues for single DEs when someone volunteers to take on the task.
