### ISSUE TITLE
Clear instructions for simple Upgrade of main system template needed

### ISSUE THREAD

**Issue by DTMW2** [QubesOS/qubes-issues#4298]
### Qubes OS version:

3 & 4

### Affected component(s): 

Online Qubes Documentation "DOCS"

---

### Steps to reproduce the behavior:

For most of us (at least for me) fedora is the main template for sys*-VMs and the disp VM. When a new release is available that leads to three tasks for me as a user:
1. download the new template
2. install software
3. change disp VM (e.g. from fedora 27 to fedora 28)

I think the documentation on these tasks is fragmented. As far as I know there is no single "how to upgrade your template" - document. Especially the current documentation does not tell me how to switch the template for my DVM:
https://www.qubes-os.org/doc/templates/fedora/

### Expected behavior:

I'd like to have one simple support document telling me about two choices:
a) inplace upgrade of existing template (or cloning it at first)
b) parallel download of the new template

and afterwards how to switch dispvm template.

Suggesstion:
1) # sudo qubes-dom0-update qubes-template-fedora-28
2) hint that I need to increase template disk in case of many applications I am going to install
3) switch template VM for existing qubes VMs in Qubes manager
4) qvm-create -l red -t fedora-29 fedora-28-dvm; qvm-prefs fedora-28-dvm template_for_dispvms True; qvm-features fedora-28-dvm appmenus-dispvm 1; qubes-prefs default-dispvm fedora-28-dvm
5) deinstall old template if everything works

### General notes:

---

**Comment by andrewdavidwong** [comment]
I've clarified the Fedora TemplateVM instructions. We won't be combining all of the instructions into a single page, because different users have different needs, and properly-abstracted, modular documentation allows us to address all users' needs with a single set of maintainable documentation.

For example, you expressed your needs as follows:

> When a new release is available that leads to three tasks for me as a user:
> 1. download the new template
> 2. install software
> 3. change disp VM (e.g. from fedora 27 to fedora 28)

1. Many users upgrade their Fedora templates in-place rather than downloading a new one (or do both), so they differ from you on this point. Moreover, the in-place upgrade instructions tend to differ slightly with each subsequent Fedora version.
2. Many users keep a vanilla template with no additional software installed, so they differ from you on this point.
3. Changing the DVM template from one template to another is the same process regardless of what the old and new templates are, so we'd have to repeat the same instrucitons for every document that covers a different combination of template upgrade paths. If the instructions need to be corrected or clarified, all the documents would be changed. This is why I've factored out those instructions and added them to the general TemplateVM page:

- https://www.qubes-os.org/doc/templates/#how-to-switch-templates-32
- https://www.qubes-os.org/doc/templates/#how-to-switch-templates-40

The patch above links to those instructions from the Fedora TemplateVM page so that they'll be easier to find.

> I'd like to have one simple support document telling me about two choices:
> a) inplace upgrade of existing template (or cloning it at first)
> b) parallel download of the new template
> 
> and afterwards how to switch dispvm template.

For the reasons explained above, each of these three things are documented on separate pages, but there are links on each pages pointing to the other ones, so they should not be hard to find. (Please add or report any missing links.)

 In-place upgrades for Fedora:

https://www.qubes-os.org/doc/templates/fedora/#upgrading

Installing new Fedora templates:

https://www.qubes-os.org/doc/templates/fedora/#installing

How to switch the DVM Template:

https://www.qubes-os.org/doc/templates/#how-to-switch-templates-32
https://www.qubes-os.org/doc/templates/#how-to-switch-templates-40
