### ISSUE TITLE
[Question] Changing Firefox To Nightly or Developer etc

### ISSUE THREAD

**Issue by zero77** [QubesOS/qubes-issues#4306]
I cannot see any information in the FAQ or elsewhere about changing the Firefox version to Nightly or Developer etc and keeping the same security configurations.

Is it just a case of uninstalling the current and installing the desired version, if not could some info be added to the FAQ or Qubes documentation.
Thanks

**Comment by unman** [comment]
This seems more appropriate to the mailing list.

Yes, you can change as you say. 
There's an obvious trade off because using nightly will make you much easier to track, and it's not been subject to the same review and audit as a final release.
If you want to do this, you'll probably want to remove firefox from the template and do a local install in ~ in your chosen qube.
You can still have disposableVMs based on the qube in which you have installed Nightly.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
