### ISSUE TITLE
Low qrexec throughput

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4334]
### Qubes OS version:

R4.0

### Affected component(s): 

qrexec

---

### Steps to reproduce the behavior:

Benchmark qrexec throughput.  I used `dd` for that purpose, running in dom0.  `dd` in the mode I used just blindly copies data, so this should be safe.

### Expected behavior:

Speed of over 1GB/s.

### Actual behavior:

Speed of around 850MB/s (vm -> dom0)/317MB/s ( dom0 -> vm)

### General notes:

There are several optimizations that could be made here, I believe.  Most focus on reducing the number of copies and/or increasing buffer sizes.  For instance, data from the shared memory region could be passed directly to the `write` system call, avoiding a copy.  Similarly, `read` can put data directly into the shared memory region.

---

**Comment by marmarek** [comment]
> For instance, data from the shared memory region could be passed directly to the `write` system call, avoiding a copy. Similarly, `read` can put data directly into the shared memory region.

Vchan API was designed specifically this way to shield application from shared memory handling. Otherwise it's easy to introduce all king of bugs, including hitting some unexpected compiler optimizations (see [XSA-155](https://xenbits.xen.org/xsa/advisory-155.html) for example). While in this particular case (handing the data directly to/from read/write syscall, without much interpreting it) probably could be done properly, we don't want to risk it.
Also, it could limit portability to other hypervisors, which could expose something else than shared memory as communication primitive (AFAIR the case for VirtualBox).

As for buffer sizes, shared ring buffer size can be controlled with `qrexec-client-vm --buffer-size=..` option. But I guess the most limiting is protocol-level limit of 4kb in one data chunk (see [linux-utils/qrexec-lib/qrexec.h](https://github.com/QubesOS/qubes-linux-utils/blob/master/qrexec-lib/qrexec.h#L28), `MAX_DATA_CHUNK` - it's maximum allowed value for msg_header.len). Changing this value needs to be done on both side of connection at the same time, which make it very hard to do as a normal update. But also making this value too high can cause a deadlock.

**Comment by andrewdavidwong** [comment]
Closing as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
