### ISSUE TITLE
WhonixCheck reports outdated packages after performing in-place upgrade

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4340]
### Qubes OS version:

`R3.2`

### Affected component(s): 

Whonix (in-place upgrade from 13 to 14)

---

### Steps to reproduce the behavior:

1. Perform the in-place upgrade procedure documented [here](https://www.whonix.org/wiki/Qubes/Update).
2. The in-place upgrade procedure completes without any warnings or errors.
3. Restart all VMs.
4. Run WhonixCheck in `sys-whonix` and `anon-whonix`.

### Expected behavior:

WhonixCheck reports no problems.

### Actual behavior:

In `sys-whonix`, WhonixCheck reports:

```
WARNING: Whonix News Result:
✘ Outdated: Installed whonix-gateway-packages-dependencies 3.4.2-1 is outdated! 
You should update. You can automatically update using Whonix's internal updater. Please update using: 
sudo apt-get update && sudo apt-get dist-upgrade 
```

In `anon-whonix`, WhonixCheck reports:

```
WARNING: Whonix News Result:
✘ Outdated: Installed whonix-workstation-packages-dependencies 3.4.2-1 is outdated! 
You should update. You can automatically update using Whonix's internal updater. Please update using: 
sudo apt-get update && sudo apt-get dist-upgrade 
```

Running these commands again in their respective TemplateVMs reports that no packages are available (as expected, since we just updated/upgraded successfully).

### General notes:

The same problem appears to be described here:

- https://tech.michaelaltfield.net/2018/09/12/how-to-check-whonix-version-in-qubes/
- https://forums.whonix.org/t/whonix-packages-dependencies-3-4-2-1-is-outdated/5717

---

### Related issues:

https://github.com/QubesOS/qubes-issues/issues/4112#issuecomment-424581888

CC: @adrelanos

**Comment by adrelanos** [comment]
Thank you for raising this! Reminds me to ask a question on Qubes policy regarding intrusive popups.

I supposed for users to apply https://www.whonix.org/wiki/Stay_Tuned and/or to use search engines and then finding out about news and https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14. But neither seems working.

Andrew David Wong:
> ```
> WARNING: Whonix News Result:
> ✘ Outdated: Installed whonix-gateway-packages-dependencies 3.4.2-1 is outdated! 
> You should update. You can automatically update using Whonix's internal updater. Please update using: 
> sudo apt-get update && sudo apt-get dist-upgrade 
> ```

What is doable is two things.

1) whonixcheck error message improvement

Easily doable is showing a better error message in whonixcheck.

> Whonix 13 has been deprecated. Upgrade to Whonix 14 required. See https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14

But since many people don't run whonixcheck it would be overlooked.

2) popup at boot

Another thing doable would be an error popup which shows up at every boot.

> Whonix 13 has been deprecated. Upgrade to Whonix 14 required. See https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14

It wouldn't be dismissible by using a "do not show this message again" checkbox. If you like that, I'd need someone to help with this ticket

"do not show this message again checkbox" tool needed
https://phabricator.whonix.org/T865

Such a persistent popup could be dismissed by a documented command "sudo rm /usr/bin/whonix-upgrade-notification".

Alternative upgrade notification popup message:

> Whonix 13 has been deprecated. Upgrade to Whonix 14 required. See https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14
>
> If you want to prevent seeing this popup again, run in Whonix TemplateVM:
> sudo rm /usr/bin/whonix-upgrade-notification
>
> Or disable autostart of this VM or uninstall Whonix.

Please let me know if such a popup notification is permissible.

**Comment by andrewdavidwong** [comment]
> I supposed for users to apply https://www.whonix.org/wiki/Stay_Tuned and/or to use search engines and then finding out about news and https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14. But neither seems working.

FWIW, I'm subscribed to Whonix News via RSS and read every post, yet I still got confused.

> Please let me know if such a popup notification is permissible.

It seems permissible to me for this use case (i.e., the user is still on a version that is no longer receiving security updates). A "do not show me again" option would be nice but is not required, IMO. @marmarek, what do you think?

**Comment by marmarek** [comment]
Yes, a popup is ok. It should be possible to disable it, but using a command mentioned in the message is fine.

**Comment by adrelanos** [comment]
Whonix 13 whonixcheck package upgraded which includes deprecation notice popup at boot including instructions on how to disable it.

**Comment by adrelanos** [comment]
Closeable?
