### ISSUE TITLE
tlp power consumption support (PM_RUNTIME kernel builtin support,  acpi-call kernel module built)

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#4348]
### Qubes OS version:

R3.2 R4.0

### Affected component(s): 

Dom0 kernel

---

### Steps to reproduce the behavior:

dom0:
```
sudo qubes-dom0-update tlp
sudo tlp start
sudo tlp stat
```

### Expected behavior:

PM-RUNTIME being present in kernel.
acpi-call built as a kernel module to permit proper management of batteries

### Actual behavior:

Result:

PM_RUNTIME is not builtin kernel.
acpi-call is not provided as a kernel module to manage batteries

**Comment by marmarek** [comment]
CONFIG_PM_RUNTIME option is gone since Linux 3.19, which was over 3 years ago. Now all the things enabled by that option are enabled with just CONFIG_PM, which is enabled.

As for acpi-call - generally we avoid including kernel modules that are not in upstream kernel. If it isn't there, there are probably good reasons for that. If you're talking about https://github.com/mkottman/acpi_call, it looks not maintained for 5 years.
