### ISSUE TITLE
Scary messages at early boot (pre-FDE password entry) after latest round of dom0 updates, R3.2

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#4358]
### Qubes OS version:

R 3.2

### Affected component(s): 

Dom0/Xen hypervisor?

---

### Steps to reproduce the behavior:

Have intel-based system (Skylake)

Have Qubes R 3.2

Install latest dom0 updates

(re)Boot

### Expected behavior:

Boot proceeding as normal without any scary messages

### Actual behavior:

Boot proceeds, and I can login and seemingly use the system (posting from this qubes machine right now)

However, very early on (BEFORE the password to full disk encryption is entered) following scary messages appear:

```
xen_acpi_processor: (CX): Hypervisor error (-14) for ACPI CPU 5
xen_acpi_processor: (CX): Hypervisor error (-14) for ACPI CPU 6
xen_acpi_processor: (CX): Hypervisor error (-14) for ACPI CPU 7
xen_acpi_processor: (CX): Hypervisor error (-14) for ACPI CPU 8
```

### General notes:

It is _prrobably_ not super important (the system boots, and seems to work okay) but it is definitely worrisome and sounds like something that is dangerous

---

**Comment by pqyptixa** [comment]
Same happens in my Ryzen R5-1600 setup, except I get these messages for CPUs number 2, 4, 6, 8, 10 and 12
.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
