### ISSUE TITLE
DOM0 Kernel 4.14.x Unstable/Lockups R3.2

### ISSUE THREAD

**Issue by thewildcat** [QubesOS/qubes-issues#4367]
### Qubes OS version:

R3.2

### Affected component(s): 

---

### Steps to reproduce the behavior:

After Installing a Kernel from 4.14, specifically 4.14.67-1, the system becomes increasingly unstable and is barely usable.

### Expected behavior:

Smooth behaviour as before

### Actual behavior:

- Constant freezes and lockups, poor performance

### General notes:

Lenovo T460P
CPU: i5-6440HQ
Microcode: 0xc6
Bios: 2.26
[error.log](https://github.com/QubesOS/qubes-issues/files/2442713/error.log)

---

### Related issues:

Might be related to https://github.com/QubesOS/qubes-issues/issues/4236

**Comment by andrewdavidwong** [comment]
> Might be related to #4236

How is this different from #4236?

**Comment by thewildcat** [comment]
I am able to login and use my VMs every time, just in a very slow manner. His system appears to not be able to get past the login screen. Also it didn't have any logs yet, as ACPI issues are present at my system, I opened this bug. But yes, might be the same issue in the end.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
