### ISSUE TITLE
Windows 7 DispVM halted itself after launched

### ISSUE THREAD

**Issue by wynn1212** [QubesOS/qubes-issues#4369]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

Windows 7 DispVM

---

### Steps to reproduce the behavior:

Create a Windows 7 Template. Update the VM and install Qubes Windows Tools. Create Windows 7 DispVM Template base on Windows 7 Template. Start the Windows 7 DispVM from Qubes menu(For example, I'm starting "Windows Explorer")

EDIT Update 2: Not only the Windows Explorer have this issue. Literally, all programs on windows 7 have same issue

### Expected behavior:

Windows 7 DispVM should started. and launched Windows Explorer in my desktop

### Actual behavior:

Windows 7 DispVM started. But after launched Windows Explorer(I can see the Windows Explorer window about half-seconds), it halted itself and deleted that DispVM.

### General notes:

---

### Related issues:

EDIT Update 1:
Might be related to #3878
>Quoted from jimtahu
I am suspecting gnome-terminal returning immediately is tricking the disposable vm into thinking it should shutdown.

Now I'm thinking Windows Explorer running on background and returning immediately is tricking the DispVM into thinking it should shutdown.

**Comment by daibhidh** [comment]
I am not sure of your case for a windows DispVM, but mine is for Malware testing and Application Debugging.  A work around I have found is to use windows 'start' command with the '/wait' flag.  Example would be:

qvm-run --dispvm=win7-dvm start\ \/wait\ cmd.exe

This forces the DispVM to stay open until it is manually shutdown or the command prompt window is closed since it is waiting for the exit code from the 'start' command and not the command prompt window.  Other commands can be used there as well as long as they are in the default windows path  (example being powershell.exe).

I have not been able to get the path escaping to work properly yet with calling an application in C:\Program Files\XXX yet, not have I figured out the correct way to add/prepend this to underlining service calls (qubes.StartApp+).
