### ISSUE TITLE
Hung up VM locks up whole machine

### ISSUE THREAD

**Issue by ThinerDAS** [QubesOS/qubes-issues#4388]
### Qubes OS version:

R3.2

### Affected component(s): 

VM

---

### Steps to reproduce the behavior:

1. open a `gdb` in an AppVM and run a program

2. interrupt and set `cs` register into an invalid number (other than 0x33, 0x23)

3. continue

### Expected behavior:

`SIGSEGV` reported back to gdb.

### Actual behavior:

VM hung up using all vCPU available for it. Any attempt of killing the VM lock up dom0.

### General notes:

Any action that can spam segment register with invalid number should work.

I did not try the same thing in dom0 for obvious reasons.

---

**Comment by DemiMarie** [comment]
Obviously this is a security bug in Xen.

Let me check if this happens in R4.0.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
