### ISSUE TITLE
QubesDaemonNoResponseError: Got empty response from qubesd

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#4414]
### Qubes OS version:

Qubes 4

### Affected component(s): 

DisposableVM

---

### Steps to reproduce the behavior:

Not much, (but i think) opening and closing excessive dispvm lead to it. 

### Expected behavior:

Close and Open dispvm simultaneously and smoothly 

### Actual behavior:

```
----
line: 'Got empty response from qubesd. See journalctl in dom0 for '
func: _parse_qubesd_response
line no.: 81
file: /usr/lib/python3.5/site-packages/qubesadmin/base.py
----
line: return self._parse_qubesd_response(return_data)
func: qubesd_call
line no.: 490
file: /usr/lib/python3.5/site-packages/qubesadmin/app.py
----
line: payload_stream)
func: qubesd_call
line no.: 68
file: /usr/lib/python3.5/site-packages/qubesadmin/base.py
----
line: self.vm.name, 'admin.vm.feature.Get', item).decode('utf-8')
func: __getitem__
line no.: 55
file: /usr/lib/python3.5/site-packages/qubesadmin/features.py
----
line: return self[item]
func: get
line no.: 74
file: /usr/lib/python3.5/site-packages/qubesadmin/features.py
----
line: self.internal = self.vm.features.get('internal', False)
func: update
line no.: 340
file: /usr/lib/python3.5/site-packages/qubesmanager/table_widgets.py
----
line: self.internal_widget.update()
func: update
line no.: 146
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: self.vms_in_table[qid].update()
func: on_halted
line no.: 467
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: callback(*params)
func: signal_fired
line no.: 15
file: /usr/lib/python3.5/site-packages/pydbus/proxy_signal.py
----
line: callback = (lambda con, sender, object, iface, signal, params: signal_fired(sender, object, iface, signal, params.unpack())) if signal_fired is not None else lambda *args: None
func: <lambda>
line no.: 52
file: /usr/lib/python3.5/site-packages/pydbus/subscription.py
```

![qubesissue](https://user-images.githubusercontent.com/11895339/47270443-6e0ebd00-d55b-11e8-9068-38ba5e9bd3d7.png)

**Comment by marmarek** [comment]
Should be fixed in https://github.com/QubesOS/updates-status/issues/741 - try that.

**Comment by TNTBOMBOM** [comment]
@marmarek is this as well related:

```
Whoops. A critical error has occured. This is most likely a bug in Qubes Manager.

KeyError: 26
at line 415
of file /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py.

---
line: self.vms_in_table[vm.qid].update()
func: check_updates
line no.: 415
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
```

**Comment by marmarek** [comment]
@marmarta do you remember fixing this (from the comment above)?

**Comment by bakeromso** [comment]
I got the same issue again. I was making a new issue but I believe it is preferred to post here.

**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
Service network-manager in standalone Debian-10 networking qube


**Brief summary**
I was adding a qube to use as a VPN.  After adding the network-manager service and clicking apply, the error message popped up:
Whoops. A critical error has occured. This is most likely a bug in Qubes Manager.

QubesDaemonNoResponseError: Got empty response from qubesd. See journalctl in dom0 for details.
at line 283
of file /usr/lib/python3.5/site-packages/qubesmanager/settings.py.


**How Reproducible**
I wasn't able to replicate the issue.



**To Reproduce**

Steps to reproduce the behavior:
1. Create new qube
2. Set trust level green
3. Type: standalone copied from template
4. Template: Debian-10
5. Check the box that this qube will provide network
6. Go into terminal and type: ```apt-get install -y strongswan network-manager-strongswan libcharon-extra-plugins``` (These are the instructions I received for setting up the VPN)
7. Go into qube settings, services, and add `network-manager`
8. Click `Apply`

**Expected behavior**
The service should be applied and I should see no error message.

**Actual behavior**
I got the popup message:
Whoops. A critical error has occured. This is most likely a bug in Qubes Manager.

QubesDaemonNoResponseError: Got empty response from qubesd. See journalctl in dom0 for details.
at line 283
of file /usr/lib/python3.5/site-packages/qubesmanager/settings.py.


**Screenshots**
![2021-02-15-131803](https://user-images.githubusercontent.com/43439704/107945692-4ba4d700-6f90-11eb-90a0-e3b17b9590c6.png)


**Additional context**
This was the full error message that was showing:

----
line: 'Got empty response from qubesd. See journalctl in dom0 for '
func: _parse_qubesd_response
line no.: 81
file: /usr/lib/python3.5/site-packages/qubesadmin/base.py
----
line: return self._parse_qubesd_response(return_data)
func: qubesd_call
line no.: 597
file: /usr/lib/python3.5/site-packages/qubesadmin/app.py
----
line: payload_stream)
func: qubesd_call
line no.: 68
file: /usr/lib/python3.5/site-packages/qubesadmin/base.py
----
line: self.vm.name, 'admin.vm.feature.Get', item).decode('utf-8')
func: __getitem__
line no.: 55
file: /usr/lib/python3.5/site-packages/qubesadmin/features.py
----
line: return self[item]
func: get
line no.: 74
file: /usr/lib/python3.5/site-packages/qubesadmin/features.py
----
line: and not vm.features.get('internal', False))
func: _filter_internal
line no.: 31
file: /usr/lib/python3.5/site-packages/qubesmanager/utils.py
----
line: choice_list = list(choice_list)
func: prepare_choice
line no.: 81
file: /usr/lib/python3.5/site-packages/qubesmanager/utils.py
----
line: *args, **kwargs)
func: prepare_vm_choice
line no.: 168
file: /usr/lib/python3.5/site-packages/qubesmanager/utils.py
----
line: allow_default=True, allow_none=True)
func: __init_basic_tab__
line no.: 431
file: /usr/lib/python3.5/site-packages/qubesmanager/settings.py
----
line: self.__init_basic_tab__()
func: apply
line no.: 283
file: /usr/lib/python3.5/site-packages/qubesmanager/settings.py


I saved the journalctl output of the last hour, but I wasn't sure if this contains sensitive data. So if needed, let me know and I can add it in here as well.


**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://github.com/Qubes-Community/Contents/blob/master/docs/configuration/vpn.md this page showed me to add the service
