### ISSUE TITLE
Boot error on Intel NUC with UEFI - Qubes R3.2

### ISSUE THREAD

**Issue by flomo29** [QubesOS/qubes-issues#4420]
Hi. First i wrote the Qubes R3.2 ISO to a SD Card with Etcher from a MacBook and then boot from it
on the newest generation Intel NUC with the i7-8809G Processor with the intel visual bios with only uefi boot and no legacy boot option.
At the Grub menu i can select every entry and i got every time the following error:

/EndEntire
file path: /ACPI(a0341d0.0)/PCI(2,1)/PCI(0,0)/UnknownMessaging(1a)/File(\EFI\BOOT)/File(xen.efi)
/EndEntire

By the way: Booting with a sd card written by etcher worked with Windows and other linux distros.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by andrewdavidwong** [comment]
On second thought, I'll reopen this to see if @marmarek thinks it's general enough.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
