### ISSUE TITLE
debian-9 template will not update on new install

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#4450]
### Qubes OS version:

Qubes r4 just installed yesterday.  Imported VM's from older installation and all of them work.  All of them update.  whonix14 works.  But debian-9 and fedora-26 templates do not have access to internet.

One idea is because I deleted sys-net and I use custom sys-net.  But I don't see where to change this for the VM's if this is the real source?  Thx.

### Affected component(s): 

---

### General notes:

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by straussmaus** [comment]
@andrewdavidwong That is the most terrible and rude reply I have ever seen to a user issue posting.  I post and issue and you tell me it's not good enough for you to call it an issue and that if I disagree I should prove it to you?

Of course this is a bug.  Two necessary and fundamental templates do not receive updates and there is no error reporting that explains the problem.  It is the most clear example of a bug that could exist.

Either the error reporting must be fixed to help the user make the necessary changes or if this is a code problem then the code must be changed.

If this is not a bug then you are saying that it is reasonable for Qubes OS to forbid debian-9 and fedora-26 templates from updating.

What a terrible, rude, and unproductive way to run your Issues board.

**Comment by unman** [comment]
@straussmaus  If you look at the guidelines you'll see that this isn't the right place to ask questions. Andrew directed you to qubes-users which is a much better place to get help on issues like this.

The behaviour you report is not a bug, it's a result of changes made in Qubes 4.0

In Qubes 3.2 templates were connected to an upstream netvm and used a proxy there to get templates.
In Qubes 4.0 they have no network connectivity and connect to the proxy using qubes-rpc.
You'll find an explanation of this in [the docs](https://www.qubes-os.org/doc/software-update-vm/) in the section on Updates Proxy.
You can change the proxy that is used for updating by editing this file:
 /etc/qubes-rpc/policy/qubes.UpdatesProxy

**Comment by andrewdavidwong** [comment]
Yes, @unman is correct. There are several problems with this issue that merited the response it received:

1. It's evident that the poster did not read our issue reporting guidelines (a link to which is provided whenever someone creates a new issue).
2. The poster did not fill out the provided issue template (and used it incorrectly, putting everything in the first field), which resulted in required information being omitted.
3. The poster evidently hasn't read the documentation or searched for this same topic in the MLs, where it has been covered several times already.

The response that the poster received was worded politely and clearly left open the possibility of reopening the issue in the event that there had been a misunderstanding on our end. The poster chose to react with hostility rather than simply providing the requested information.
