### ISSUE TITLE
qvm-run -n sets incorrect exit code for shutdown VMs

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#4476]
### Qubes OS version:
4.0

### Affected component(s): 
qvm-run

### Steps to reproduce the behavior:
dom0:
`qvm-run -n [shutdown VM] 'echo foo' ; echo $?`

### Expected behavior:
Something != 0 is printed as the VM was shut down and thus the run operation failed.

### Actual behavior:
0 is printed.

### Related issues:
None that I'm aware of.

**Comment by 3hhh** [comment]
> @3hhh Why would you expect "something !=0" ?
As far as I can see, the qvm-run command has performed without error.
If you choose to use qvm-run -n, it would be an error if the VM were started.

You're confusing soundness/correctness of execution with error states there.

But let's do it ground up:
I define an error as a state in which a program failed to execute its main purpose for whatever reason.

`qvm-run`'s main purpose is to execute commands in VMs afaik. `echo foo` is such an example, but was never executed above. Thus the main purpose was missed and an error state was reached. That should've been indicated by something != 0 (the number of errors is counted in the exit code), but resulted in a 0 in Qubes. --> Bug.

**Comment by unman** [comment]
I dont see point in arguing further about your expectations.
If you want to execute a command in a qube, use `qvm-run`. (No need to specify `-a` , as it's default behaviour.)
`qvm-run -n ` has main purpose of running a command **but not starting a qube automatically**. If you _choose_ to use `-n` then you must understand that.
You seem to expect an error if the qube isn't running. I dont, and I can't understand why you do. The program has exactly executed its purpose with the parameters that you chose to pass to it.

**Comment by andrewdavidwong** [comment]
The [man page for `qvm-run -n`](https://dev.qubes-os.org/projects/core-admin-client/en/latest/manpages/qvm-run.html#cmdoption-qvm-run-no-auto) states:

```
--no-auto, --no-autostart, -n
    Do not start the qube automatically, fail the operation if not running.
```

If the target qube is not running, then `qvm-run -n` will not start the qube and will "fail" the operation. Perhaps the disagreement comes down to the ambiguous use of the word "fail" (as a verb) here.

On one interpretation, the fact that the operation "failed" means that a non-zero exit status should be returned. On another interpretation, the fact that the command succeeded at "failing" the operation because the qube was not running means that a zero exit status should be returned.

CC: @marmarek
