### ISSUE TITLE
meminfo-writer service not displayed in Qubes Manager service list

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#4480]
### Qubes OS version:

R 4.0

### Affected component(s): 

Qubes manager ? (not sure)

---

### Steps to reproduce the behavior:

before there was enabled by default service called meminfo-writer. 

now recent debian/whonix doesnt come there by default , i need to add it by default

![testing5](https://user-images.githubusercontent.com/11895339/48076054-57639980-e1dc-11e8-895c-78965711a182.png)

### Expected behavior:

should be there and enabled

### Actual behavior:

not there

**Comment by unman** [comment]
@TNTBOMBOM  The fact that it doesn't appear in the pane is of no significance. As far as I remember this has always been the case.
That's why it says that "unlisted services will follow default"

Check with qvm-service and you'll see it's enabled in default templates.

**Comment by TNTBOMBOM** [comment]
i didnt get what you mean, do you mean its enabled by default even though its not shown there?

as i recall it was always there specially fedora templates.

**Comment by unman** [comment]
It *is* enabled by default, and the rubric tells you that unlisted services will follow default settings.
As I said, check it with `qvm-service`.

I dont use the Qube Manager, nor the Manager in 3.2 before, but I do seem to recall that this was always the case. By "adding" it, you aren't doing anything at all.

**Comment by andrewdavidwong** [comment]
Why not populate the list in Qubes Manager with all the currently-enabled services so that the user can see them there instead of having to use `qvm-service`?

Related: #3891

**Comment by marmarek** [comment]
I think Qubes Manager shows exactly the same info as `qvm-service`. And `meminfo-writer` should always be present (either enabled or disabled). I've just checked and newly created VM indeed lack this service, so @TNTBOMBOM described legitimate bug in handling this service, not only displaying it.
In practice the impact is minimal, as @unman said, the service when unlisted will follow the default and for this case it is enabled (unless VM have PCI devices).

> Why not populate the list in Qubes Manager with all the currently-enabled services so that the user can see them there instead of having to use `qvm-service`?

The thing is dom0 have no knowledge of in-VM default value for various services, or even list of valid services. I admit it wasn't the best design decision, but it is this way right now. Recently I've added a method for VM to tell dom0 what services supported (#4402), but it isn't used by any user tool yet (qvm-service, qubes manager etc). And also it doesn't solve default value problem.

**Comment by andrewdavidwong** [comment]
> The thing is dom0 have no knowledge of in-VM default value for various services, or even list of valid services.

But then how can `qvm-service` get that info? All I'm suggesting is selectively displaying the output of `qvm-service` inside Qubes Manager so that the user can see it in the GUI instead of the command line.

**Comment by marmarek** [comment]
I don't think it selectively display them. In this case (AFAIU) none of `qvm-service` and Qubes Manager shows `meminfo-writer` service for problematic VM.

**Comment by andrewdavidwong** [comment]
The "selectively displaying" part pertains to how Qubes Manager would display the output of `qvm-service`. I added "selectively" since we'd probably want to make the output look nice and pretty, and we might want to display all of it.

Sure, in this case, maybe neither `qvm-service` nor Qubes Manager is showing `meminfo-writer`. That's a bug, fine. But that still doesn't explain this part:

> > Why not populate the list in Qubes Manager with all the currently-enabled services so that the user can see them there instead of having to use `qvm-service`?
> 
> The thing is dom0 have no knowledge of in-VM default value for various services, or even list of valid services.
> 

I don't understand why "dom0 has no knowledge of X" can be the reason why we can't have (basically) a GUI wrapper around `qvm-service`.

**Comment by andrewdavidwong** [comment]
Maybe the answer is, "Well, the user can't use `qvm-service` to do that in the first place, so showing having a GUI wrapper around `qvm-service` wouldn't help"?

**Comment by marmarek** [comment]
By "dom0 have no knowledge of ..." I mean `qvm-service` tool doesn't show them either. "Services" tab in qubes manager is a GUI wrapper around `qvm-service`.

**Comment by brendanhoar** [comment]
When and if this is re-engineered to explicitly list all services, I suggest replacing the checkboxes with a drop down containing: Default, Disabled, Enabled. 

For the Default choice I think the UI as well as the CLI tool need to be aware of what the default setting effectively is and be able to report that to the user. For the UI, perhaps a column that shows the resulting effective value as well?

Brendan

**Comment by unman** [comment]
@andrewdavidwong What's the benefit in keeping this open? It is an instance of #3948, (which I'd overlooked.)
Otherwise you could have issues opened for *all* the services that don't appear in Manager - and, as I said, my experience is that _often_ the pane is not populated. I can raise those issues if you want ;-)

**Comment by marmarek** [comment]
`meminfo-writer` specifically should be always listed either enabled or disabled (see man qvm-service), so it is a bug that it isn't.

**Comment by marmarek** [comment]
I'm having troubles to define the right logic for this. Full details:
`meminfo-writer` service is about enabling/disabling dynamic memory management for given VM. On the VM side there are two parts involved:
 - meminfo-writer service (part of qubes-core-agent package) - responsible for reporting memory needs to dom0 (specifically: to qmemman service in dom0)
 - balloon driver (part of Linux kernel and _I think_ Xen PV drivers for Windows; other OSes with Xen guest support may have it too) - responsible actually taking/giving memory

There are also two memory-related properties:
 - `memory`: initial amount of memory qube gets at its startup; can be later adjusted (up or down) when meminfo-writer service starts; this value should be enough to start the qube up to the meminfo-writer service startup
 - `maxmem`; maximum amount of memory qube can use (upper limit what meminfo-writer can request)

Constraints about meminfo-writer/qmemman as a whole:
 - it works only when all the parts are present: including meminfo-writer inside VM, and balloon driver in VM's kernel
 - when enabled for PV domain without support inside, it's harmless - VM simply will not use extra memory
 - when enabled for PVH or HVM domain without balloon driver (non-Linux OS, or Linux with balloon driver explicitly disabled), the domain will crash: https://github.com/QubesOS/qubes-issues/issues/4135
 - HVM domain with PCI devices will not start if `memory` != `maxmem` - which is the case for domains with dynamic memory management enabled (there is [a workaround](https://github.com/QubesOS/qubes-core-admin/blob/master/templates/libvirt/xen.xml#L5) for this, which use `memory` in place of `maxmem` for such qubes, regardless of meminfo-writer service status)

Now, what I'd like is to remove magic from this as much as possible, especially make it easier to answer the question "if the dynamic memory management for this domain is really used". But also, make it as seamless as possible (do not require setting this manually unless user _want_ to, not _need_ to to avoid domain crash).

Each service (including meminfo-writer) can have 3 states:
- enabled
- disabled
- not set AKA default - means use some per-service default, in most cases "disabled" - but there is no method to get actual value used (other than knowing the logic involved in the default decision and applying it separately)

Now, there are various points in qube lifetime where this value could be changed:
 - template creation - at this point it only have name and label; at this point there is no info what OS is inside or whether it supports meminfo-writer/balloon driver
 - for templates installed with rpm (qubes-packaged templates, not manually installed by the user), shortly after that template is created, it is started for the first time and it reports what it supports (including meminfo-writer support)
 - template-based qube creation - at this point it only have name, label and template (qubes-packaged template already reported support for meminfo-writer, so dom0 do know it)
 - adding/removing PCI devices: if any PCI device is present, meminfo-writer should be disabled, but if last one is removed, it can be enabled back (or not - if user's intention was to keep it disabled...)
 - changing template: switching to the template that have meminfo-writer support or the other way around - rare case, as in practice that means switching to/from non-Linux template and private.img isn't cross-OS compatible
 - template reports meminfo-writer support _after_ some qube based on it is created - also rare, but possible: for example when user installs the template manually (from installation DVD) and installs qubes tools manually much later, or when reporting during initial template installation fails for some reason and template report it on some further start

In each case I can answer the question what should be the default value for meminfo-writer service:
"enabled" if the qube (or its template) support it and there are no PCI devices; otherwise "disabled"

Additionally, if it's disabled, there should be just one memory parameter, either `memory` or `maxmem` and the other one should be ignored. I'm not sure which one, but GUI qube settings right now disable "maxmem" if you disable dynamic memory management, so we can stay with this choice.

But, at any point user can choose to change the default value, and there is no way to tell if the service is set by some internal logic or the user (and should no longer be changed automatically). Additionally, in some cases not changing it automatically may even lead to qube crash.

I see few options:
1. Always set the service value and forcibly change it if any condition affecting its value change (for example adding/removing PCI device) - if user want to override this choice, will need to change it again.
2. Initialize it during domain creation (or initial template features report - on template installation) and not change it later automatically; but improve error reporting if the current value could lead to domain crash (currently GUI qube settings do warn for some of such settings - namely PCI devices case)
3. Introduce new property (properties also may have default values, but in contrast to services, it is possible to see what the actual value it has, regardless of being the default one or set by the user), and set always `meminfo-writer` service value based on this property (internally service is still needed to tell the qube whether to start `meminfo-writer` service or not; we could hide that service, but IMO that would be even more confusing). User can change the property value, but setting service value manually would be overridden by property anyway.

I think the last option would be the clearer solution for the opacity of the "current value of dynamic memory management". One downside is API change - GUI qube settings will need to learn new method for enabling/disabling dynamic memory management. And the same for our documentation (do we describe meminfo-writer service anywhere else than `qvm-service` manual page?).
Also, it still allow the user to set it to invalid value (enabling it when it would cause domain crash), but it can be combined with better error reporting for this.

That's a complex thing...
@andrewdavidwong @woju @unman @marmarta what do you think?

**Comment by andrewdavidwong** [comment]
When a user manually changes a memory-related setting like this, it's one of two cases:

1. A misguided attempt to make the VM behave in a certain way, usually due to the mistaken belief that the desired behavior is being prevented by Qubes' automatic memory management.
2. A legitimate use case for manual memory management.

I don't think any user makes a manual change like this *wanting* the VM to crash, so it's safe to assume that such cases fall under (1). Ideally, we'd either block, warn, or document away all instances of (1).

So, really, the question is what you consider to be the legitimate use cases that fall under (2). If we can identify a common pattern in the user's intentions and expectations across those use cases, we can determine which mechanism will seem intuitive and which defaults will be sensible.

**Comment by woju** [comment]
Well, the problem with solution 3 (property) is that we'd have to come up with a mechanism to pass the information into the VM, and that mechanism is qvm-service. But as you rightly point out, this service has non-trivial interaction with other properties, so I think it should have been property since beginning. Now that logic is implemented around `include_in_balancing` checkbox in advanced tab.

If I could break API, I'd imagine it as some magic value for either `memory` or `maxmem` property. Maybe `maxmem` = 0 means that memory is fixed to `memory`, balancing is disabled and it cannot be set to non-zero if there is pci device (and qvm-pci attach fails for VM with non-zero property value). And similar checks for pvh and hvms. And obviously cannot be changed if VM is running. Virtual service can be written to qubesdb using extension. Checkbox in qubes-manager should remain and just set the property to 0 behind the scenes. Did I miss something?

**Comment by marmarek** [comment]
@woju 
> Maybe `maxmem` = 0 means that memory is fixed to `memory`

I don't think magic value for a property would be much less confusing, but I could be convinced otherwise. Good thing about re-using maxmem is that we don't introduce yet another inter-dependent property.
Also, this means disabling + enabling this mechanism would destroy previous maxmem value :/

> And obviously cannot be changed if VM is running

FTR this isn't such obvious thing. Technically it is possible to enable dynamic memory management at runtime (not sure about disabling, but probably also doable with some extra effort). We don't try to do either of those at the moment.

> Virtual service can be written to qubesdb using extension.

This is what I have in mind by saying "we could hide that service".

@andrewdavidwong 
> So, really, the question is what you consider to be the legitimate use cases that fall under (2). If we can identify a common pattern in the user's intentions and expectations across those use cases, we can determine which mechanism will seem intuitive and which defaults will be sensible.

I think the major use case is for applications needing a lot of memory, fast (faster than qmemman can give it). For example building Android is such a task.

**Comment by andrewdavidwong** [comment]
> I think the major use case is for applications needing a lot of memory, fast (faster than qmemman can give it). For example building Android is such a task.

Right. Another one that comes to mind is assigning a very small amount of memory to VMs that will never need more. In both cases, the user will want the manual setting to persist so long as it won't result in a crash.

This rules out option 1 ("Always set the service value and forcibly change it..."). Users will expect their setting to persist and be confused and upset when it is forcibly changed. They probably won't realize that they have to set it again until they file an issue here and one of us tells them or points them to the documentation.

From a UX perspective, option 2 ("Initialize it during domain creation...  and not change it later automatically; but improve error reporting...") sounds good. Warning users when their setting might result in a crash is a good idea and will prevent a lot of confusion.

From a UX perspective, option 3 ("Introduce new property... and set always meminfo-writer service value based on this property...") sounds bad. It's not intuitive or easily discoverable, so users will likely be confused and not understand how to fix their own mistakes, which will probably result in a lot of help requests (like option 1). You could mitigate this with an explanatory tooltip (#2211) wherever the user manually enters a custom memory setting, but it might be a complex explanation for a tooltip, so clear wording would be crucial.

**Comment by marmarek** [comment]
@andrewdavidwong what do you think about @woju's idea of maxmem = 0 for this purpose? It will also persist. And (unless set by the user to specific value, including 0) could be calculated automatically depending on other conditions. In the GUI settings, it will remain the same: a checkbox "include in memory balancing" + a maxmem field active only when the checkbox is checked.

**Comment by andrewdavidwong** [comment]
Also, you probably don't want to display the system-generated value in the same user-editable field. It might make more sense to display the actual maxmem value as text. Then, provide a checkbox with a label like "Manual override." Checking that box enables an editable field in which the user can specify a value. Saving that value then causes it to be displayed as the maxmem value. Unchecking the manual override option changes the maxmem value back to the system-generated value.

**Comment by marmarek** [comment]
> Well, most users won't know that "0" is a magic value that does something special, so you'll still need a tooltip to explain what it does. It would be more user-friendly to provide a checkbox that does that instead.

Yes, that's the idea - in GUI that would be a checkbox - exactly as it is now (which under the hood would set maxmem to 0, or any other mechanism we choose here). User would need to know that magic value for CLI case only.

> Also, you probably don't want to display the system-generated value in the same user-editable field.

Well, we do that all the time already and I think it's fine. This is the case already for "initial memory" (inherited from template) , "maxmem" (inherited from template, or half of physical memory, capped at 4GB), vcpus (inherited from template). And also a few where GUI do show that the value is "default": netvm, kernel, default dispvm.
BTW the problem applies only to GUI. In CLI, qvm-prefs displays "D" besides the default values (or "-" otherwise).

> It might make more sense to display the actual maxmem value as text. Then, provide a checkbox with a label like "Manual override." Checking that box enables an editable field in which the user can specify a value. Saving that value then causes it to be displayed as the maxmem value. Unchecking the manual override option changes the maxmem value back to the system-generated value.

Hmm, that's interesting direction. When I look at it, we do know when it's safe to enable meminfo-writer for given VM and also I think there are no cases where would want to override automatic choice to _enable_ it even though it is unsafe (the only such thing I can think of is a bug in detection logic so it isn't enabled even if it's safe to do so - but again, that would be a bug, to be fixed). So, maybe indeed we don't need "include in memory balancing" checkbox, but the opposite one "force exclude from memory balancing". And a label (info only) what is the current state - mostly for the automatic case (when the checkbox is unchecked). @marmarta?

**Comment by woju** [comment]
> > And obviously cannot be changed if VM is running
> 
> FTR this isn't such obvious thing. Technically it is possible to enable dynamic memory management at runtime (not sure about disabling, but probably also doable with some extra effort). We don't try to do either of those at the moment.

Um. So I'm not sure the proposal is right. If we'd like to support that in the future, wouldn't it be another incompatible change?

WRT error reporting, it should be improved anyway. In my non-representative opinion, too much problems end with "Got empty response from qubesd".

**Comment by marmarek** [comment]
> WRT error reporting, it should be improved anyway. In my non-representative opinion, too much problems end with "Got empty response from qubesd".

In case of domain crash related to qmemman/meminfo-writer, it's mostly "Cannot connect to qrexec agent for 60 seconds, /var/log/xen/console/guest-...". In some cases there is some useful information, in some not (log ends in some arbitrary place and actual message is in `xl dmesg`/`/var/log/xen/console/hypervisor.log`). This all could be prevented by checking _before_ even starting the domain and reporting incompatible settings.

>  "Got empty response from qubesd"

This is the case of unhandled expection - in most cases a bug, not only incorrect error reporting.

> I wanted to take one of those variables out of equation.

I see. I like this idea more and more. This is rather independent of GUI presentation of this setting (can be a checkbox, in either direction), so the user wouldn't need to know this magic value.
As for `meminfo-writer` service in the "Services" tab (or qvm-service) I think it should be hidden/removed - given it would always be overridden by that checkbox/maxmem setting. On one hand, keeping it would be consistent for anyone already familiar with low level handling of this (but IMO those people also can deal with forced service value, even if it's hidden - similar to other "default" services values). On the other hand, having setting which in practice can't be changed (or even worse: appears to be changeable, but the change is later reverted automatically) IMO is a bad idea. So, I'd propose to keep "memory balancing" setting in just one place ("Advanced" tab) and remove it from "Services" (or actually - given this very bug - do not introduce it back). And to avoid confusing behavior, prevent adding it manually with some sensible explanation ("meminfo-writer service cannot be manually changed, use "include in memory balancing" checkbox in Advanced tab instead", or such).

Oh, I haven't responded to one of @andrewdavidwong points:
> From a UX perspective, option 3 ("Introduce new property... and set always meminfo-writer service value based on this property...") sounds bad. It's not intuitive or easily discoverable, so users will likely be confused and not understand how to fix their own mistakes, which will probably result in a lot of help requests (like option 1). You could mitigate this with an explanatory tooltip (#2211) wherever the user manually enters a custom memory setting, but it might be a complex explanation for a tooltip, so clear wording would be crucial.

I think we all agree that GUI for this should be simple, so user wouldn't need to learn complex logic to understand what she/he see. This include no need to know magic values (even if they are described in some tooltip), or complex interaction between multiple settings.
This is why I think hiding `meminfo-writer` service at all is a good idea. Keeping it there indeed confuse  anyone trying to change it. Especially as its name isn't very descriptive...


So, I think this all can be summarized as:
On low level, have just two properties:
 - `memory` - as currently it is, "initial memory"
 - `maxmem` - when >0, allow domain to have dynamically allocated memory, up to `maxmem` value; default value (in effect until user set it to something manually) would be `min(physical-memory/2, 4GB)` (as currently is) if the qube (or its template) support it and there are no PCI devices; `0` otherwise

`meminfo-writer` service will be hidden and attempting to set it manually will result in an error directing the user to set `maxmem`/checkbox in settings instead

On GUI level, there will be:
 - `memory` property as it currently is
 - info whether dynamic memory management is active
 - checkbox to override default value
 - `maxmem` property, active when dynamic memory management is active

**Comment by woju** [comment]
Instead of info, I'd have just checkbox "Enable dynamic memory management", which inactivate PCI devices and virt_mode, and activate maxmem widget. In turn, this checkbox should be inactive when there is a PCI device or wrong virt_mode. And only then, an explanation why the checkbox cannot be operated.
