### ISSUE TITLE
Wipe RAM of VM when it shuts down or is killed, and during memory balancing

### ISSUE THREAD

**Issue by SuzanneSoy** [QubesOS/qubes-issues#4488]
### Qubes OS version:

4.0

### Affected component(s): 

Domains

---

### Steps to reproduce the behavior:

1. Close or pause all untrusted VMs
2. Read a file containing some secret information (cryptography key, etc.) in a VM
3. Shut down the VM
4. Start an untrusted VM which uses some attack to read the contents of the RAM
5. I could not find any documentation indicating that the RAM that was occupied by the "secret" VM is wiped on shutdown (or when memory balancing deallocates a chunk of RAM). If that's the case, then simply shutting down a VM is not enough to protect in-RAM secrets from an attack that happens after the VM halts.

### Expected behavior:

When a chunk of RAM is released during memory balancing, normal shutdown or kill, it should be zeroed out. If that's already the case, I'll make a PR to add this information to the docs.

### Actual behavior:

I assume that the contents of the RAM remain accessible to an attacker. Otherwise, good news, but the feature is undocumented.

### General notes:

---

### Related issues:

These issues seem are about clearing the RAM of the host when it shuts down, to prevent local forensics (e.g. take the RAM out and plug it into another computer). In this issue, I'm talking about the RAM of a VM being accessed by another VM (e.g. via a future attack similar to Meltdown) after the first was halted.

https://github.com/QubesOS/qubes-issues/issues/1562
https://github.com/QubesOS/qubes-issues/issues/1563

**Comment by cfcs** [comment]
Additional prior related discussions:
- https://github.com/QubesOS/qubes-issues/issues/3504
- https://github.com/QubesOS/qubes-issues/issues/977
- https://github.com/QubesOS/qubes-issues/issues/904

**Comment by andrewdavidwong** [comment]
This would be helpful to protect against Spectre/Meltdown-style attacks.

**Comment by rustybird** [comment]
I'd love to see this too. It would go a long way towards fixing the one aspect (RAM forensics) where _Split dm-crypt_ is [less secure](https://github.com/rustybird/qubes-split-dm-crypt#remaining-attacks) than directly attaching encrypted block devices via `qvm-block`.

**Comment by awokd** [comment]
Isn't this covered by https://github.com/QubesOS/qubes-issues/issues/1562#issuecomment-352486079?

**Comment by andrewdavidwong** [comment]
> Isn't this covered by [#1562 (comment)](https://github.com/QubesOS/qubes-issues/issues/1562#issuecomment-352486079)?

Yes, it appears so. Closing as a duplicate of #1562.

**Comment by tasket** [comment]
You should look into Xen's `scrub-domheap` option, which is being discussed in #1562.

**Comment by marmarek** [comment]
> You should look into Xen's `scrub-domheap` option, which is being discussed in #1562.

That's literally no-op if you run any non-ancient Linux (newer than 3.0 I believe) in a VM.
The option is only about scrubbing pages on balloon, but **Linux does that already** before giving them back to Xen.
On VM shutdown (graceful or not), Xen scrubs the VM's memory before using it for anything else (including using for another VM). Regardless of the `scrub-domheap` option.

See documentation of the option:
```
### scrub-domheap
> `= <boolean>`

> Default: `false`

Scrub domains' freed pages. This is a safety net against a (buggy) domain
accidentally leaking secrets by releasing pages without proper sanitization.
```

and for anybody curious, here is relevant implementation (xen/common/page_alloc.c):
```
            /*
             * Normally we expect a domain to clear pages before freeing them,
             * if it cares about the secrecy of their contents. However, after
             * a domain has died we assume responsibility for erasure. We do
             * scrub regardless if option scrub_domheap is set.
             */
            scrub = d->is_dying || scrub_debug || opt_scrub_domheap;
```

This concludes question in this ticket.

**Comment by tasket** [comment]
This issue's threat model is defined by the possibility of an exploit against the hypervisor (which IMO includes physical interventions such as _coldboot_ as well).  In the moments just after an attack, having freed memory pages (from non-ballooned memory) queued for eventual scrubbing is of little help.

Additionally, a non-Linux guest might have been run, so whatever scrubbing we expect from Linux won't be in effect.

The strongly implied goal here is to have a free memory heap that is kept clean at any given moment (as #1562 states, not having the opportunity to shutdown is a problem).  I think its a reasonable goal so I suggest re-opening this issue.

---

Looking through the Xen source code, there is a _scrub_free_pages()_ function that is called from Xen's _idle_loop()_.  If the scrub function could also be called synchronously (i.e. completed) on each domain termination then we might have the desired solution of quickly clearing out statically (de)allocated memory.

**Comment by marmarek** [comment]
> Additionally, a non-Linux guest might have been run, so whatever scrubbing we expect from Linux won't be in effect.

An OS that supports balloon driver is expected to clear pages from secrets before returning it. It can also choose to not support balloon driver at all if it's not willing to clear pages itself. Balloon driver submitted upstream to Linux in 2008 did scrubbing already. The option exists as a workaround for really ancient kernels (when Xen support wasn't even upstream yet, but as some 3rd-party patches). If your threat model involves such systems, you can also enable this option (but IMO in that case, you have bigger concerns...).
OTOH, effectively clearing _each_ page _twice_ on _every balloon operation_ by enabling `scrub-domheap` option, it will make memory balancing noticeable slower, which will be user visible regression, especially on systems with less total memory.

Anyway, the option has nothing to do with scrubbing on shutdown (clean or not), when Xen is scrubbing the pages in any case.

> This issue's threat model is defined by the possibility of an exploit against the hypervisor (which IMO includes physical interventions such as _coldboot_ as well). In the moments just after an attack, having freed memory pages (from non-ballooned memory) queued for eventual scrubbing is of little help.

So, you mean the threat model is attacker gaining access to your system just after you shutdown some VM? Like, within (mili)seconds? If that's the threat you worry about, synchronous scrubbing likely won't save you either (the only difference is you may see that really scrubbing hasn't completed yet, if you are lucky). On the systems Qubes OS is designed for, this memory scrubbing really is quite quick operation (even via idle_loop). It takes longer if you run a server with several TB of RAM (in a single VM), but that's not our target audience.

Anyway, if somebody is willing to contribute the synchronous scrubbing feature to Xen (upstream) and it gets accepted there, we can consider enabling it (and maybe also backporting relevant patches to the Xen version we use at that time). In that case, the issue may warrant being re-opened. Otherwise, I'd rather not have an open issue with questionable gain to real users and negligible chance to ever being done.

The initial ticket was opened based on a speculation that a released memory is not scrubbed at all. That's not true, so the original point is mute.

**Comment by tasket** [comment]
> So, you mean the threat model is attacker gaining access to your system just after you shutdown some VM? Like, within (mili)seconds?

I think it could be seconds or minutes (or longer), if the user has the misfortune of running large CPU-intensive jobs, preventing the idle loop from completing a scrub.  Perhaps a corner case, but not a small one. It becomes even larger if the attack originates in a domU and all they have to do to prevent idle scrubbing is busy-wait or do other heavy processing.

(Also, systems tend to be quite busy while shutting down. So then what happens to dom0's released static memory? Is the idle loop allowed to complete? A synchronous hypervisor scrub would address this, too.)

The Xen documentation leaves much to be desired, with few details about a domain's lifecycle (for instance, does a memory-balanced domain start with a static allocation, or a bundle of balloon allocations?). We have experienced Qubes users and contributors concurring with the OP because we're not getting a clear picture of a satisfactory process.

**Comment by tasket** [comment]
Informative link to [a patch](https://xen-devel.narkive.com/tPURDU8K/patches-v8-0-8-memory-scrubbing-from-idle-loop) that lead to the current idle-only scrubbing (when pages are not quickly re-allocated to a new VM).  So older versions of Qubes probably do not have this issue's (assumed) vulnerability.
