### ISSUE TITLE
Internal appVM  graphical issue 

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#4492]
### Qubes OS version:

Qubes 4.0

### Affected component(s): 

Graphical issue

---

### Steps to reproduce the behavior:

install (in my example) firetools
try to stretch it similarly in the image:

![graphicqubes](https://user-images.githubusercontent.com/11895339/48203979-b0f4d100-e360-11e8-8e6c-12c2441ceb95.png)

### Expected behavior:

should not copy a fixed screenshots what is opened in the vm

### Actual behavior:

copying/screenshot of what is opened in the vm.

**Comment by andrewdavidwong** [comment]
I don't understand what kind of problem this bug report is attempting to describe. Can you try rephrasing your description of the problem?

**Comment by TNTBOMBOM** [comment]
what do you describe what you see in the screenshot that i provided? 

im really out of words rather than an in-appvm gui issue? i dunno better ...

**Comment by TNTBOMBOM** [comment]
what do you describe what you see in the screenshot that i provided? 

im really out of words rather than an in-appvm gui issue? i dunno better ...

**Comment by andrewdavidwong** [comment]
I have no idea what that screenshot is depicting.

**Comment by iamahuman** [comment]
## Edit proposal

**Qubes OS version**
Qubes 4.0

**Affected component(s) or functionality**
GUI virtualization

**Brief summary**
Some applications (e.g. Firetools), when run under Qubes GUI virtualization, does not properly respond to window resize requests from the user, especially when extending the window.

**How Reproducible**
Always.

**To Reproduce**

Steps to reproduce the behavior:
1. Install and open Firetools
2. Try to resize the Firetools window by stretching its frame.

**Expected behavior**
The Firetools window gets properly resized, and its contents are stretched or rearranged to fill the (now) larger window.

**Actual behavior**
The frame and decorator from the window manager gets extended as requested; however, the contents of the window is left unchanged, and its size stays exactly the same. The remaining extra content area gained by the size extension is filled with graphics from the same VM that had been drawn under the window, making the extra area look transparent (in the context of the virtual screen of the VM).

**Screenshots**
![graphicqubes](https://user-images.githubusercontent.com/11895339/48203979-b0f4d100-e360-11e8-8e6c-12c2441ceb95.png)

**Additional context**


**Solutions you've tried**
None.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
None.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
TBD

**Comment by DemiMarie** [comment]
@marmarek Is `gui-agent` a compositing window manager?

**Comment by iamahuman** [comment]
@DemiMarie Sorry for unsolicited response; would QubesOS/qubes-gui-agent-linux#52 (issue #4351) help?

**Comment by DemiMarie** [comment]
@iamahuman perhaps?  I honestly don’t know.
