### ISSUE TITLE
qubesdb sync blocking dom0+domU processes

### ISSUE THREAD

**Issue by xaki23** [QubesOS/qubes-issues#4498]
### Qubes OS version:

R4.0
R4.0.1-rc1

### Affected component(s): 

qubesdb (and anything depending on it, like qubes-manager and vms)

---

### Steps to reproduce the behavior:

 - create/clone a mirage firewall
 - attach 5+ downstream vms to it
 - start all these vms
 - qvm-kill mirage-fw

 - optional: start tail -f on the mfw console log
 - optional: start strace -f on qubesdb

 - qvm-start mirage-fw
 - try to do anything in qubes-manager
 - note how qubes manager doesnt react at all, not even local stuff like being able to change highlighted row

 - looking at mfw-log this is the initial sync of the qubesdb
 - the client infos arrive with precisely 10 seconds of delay in between

 - looking at qdb-strace it gets caught in its mainloop pselect, which has a 10sec timeout
 - so total blockage time is 10 sec * number of downstream vms

 - replace mirage-fw by a sys-fw clone in this setup, kill+start again, no blockage

### Expected behavior:

no minutes worth of hard blockage during qubesdb sync/multiread

### Actual behavior:

noticeable blocking 

### General notes:

both mfw and sysfw seem to be doing a multiread to sync on startup.
i was unable to find any significant difference from skimming the code.

but no matter what mfw is doing different there, it should not block dom0 that hard.

filing this on both qubes and mirage side since i see room for improvement on either.
(though this might turn purely into a qubes-side thing, depending on closer analysis)

---

### Related issues:

mirage side issue here: https://github.com/mirage/mirage-qubes/issues/25

**Comment by marmarek** [comment]
If that's really about mainloop's pselect timeout, it would handle other requests... There is [another 10s timeout in vchan code](https://github.com/QubesOS/qubes-core-vchan-xen/blob/master/vchan/io.c#L91), but a) it use select, not pselect b) to trigger that VM would need to repeatedly connect/disconnect to qubesdb. Does mirage qubesdb does that?

Anyway, this do sound like qubesdb bug that VM (however it does that) can freeze dom0 operations. I see at least two places for improvements: 
 - waiting for vchan buffer space when writing - right now if dom0 tries to send more data than the vchan buffer, it will wait for space (until VM instance free some)
 - waiting for complete command - if VM starts sending a command, dom0 will try to retrieve it as a whole, possibly waiting for remaining part

Solution for the first one is write buffer. We already have it for local clients, so it shouldn't be hard to add it here too. But it needs to be done careful, to not allow OOM dom0 (repeatedly sending a command requiring large reponse, but not retrieving any of them). I think not processing further commands until response for previous one is fully retrieved should do the job (something that implicitly is the case right now).
For the second one, also some kind of buffering could be done - write command to local buffer and process it only when it's fully retrieved. But that's slightly more complex because of the code structure (all calls to `read_vchan_or_client` needs to be carefully reviewed and some command handlers restructured).

**Comment by marmarek** [comment]
Case described in https://github.com/QubesOS/qubes-issues/issues/4498#issuecomment-438005770 fixed in https://github.com/QubesOS/qubes-core-qubesdb/pull/18
The original issue turned to be not about qubesdb, but network attach code.
