### ISSUE TITLE
Suppress "device available" notifications on initial login

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4527]
### Qubes OS version:

R4.0

### Affected component(s): 

Qubes Manager(?) / device availability notifications

(Not sure about the component; please feel free to edit)

---

### Steps to reproduce the behavior:

1. Boot the computer
2. Log in
3. Observe the flood of notifications about internal devices being available

### Expected behavior:

I only see these notifications when something changes after the initial boot.

### Actual behavior:

I get a bunch of redundant notifications that I end up just ignoring because I get them every single time I boot. I already know what's inside my computer.

### General notes:

There's an argument to be made that this is beneficial because if there's some unexpected (malicious) hardware installed, it might show up in the notifications. However in practice this isn't true because the signal-to-noise ratio is so low I don't pay attention to any of these notifications. In order for that to be effective I would need to be notified only about _new_ hardware devices detected since the last boot.

---

**Comment by airelemental** [comment]
There are similar useless notifications when booted an AppVM containing snaps (with qubes-snapd-helper installed.)

**Comment by t4777sd** [comment]
Maybe an approach to handle this is in the notification of devices to have an "ignore this notification in the future" button. That way for that persistent hardware someone can ignore it and they won't see it anymore. 

This I think is better than having a "only notify if changed since last boot" because sometimes I boot my machine and grab a coffee and don't see the notifications. As a result, if it was unseen, I would want to see it on the next boot.
