### ISSUE TITLE
gui-daemon: deprecated g_type_class_add_private()

### ISSUE THREAD

**Issue by fepitre** [QubesOS/qubes-issues#4547]
Refactor the code for handling the deprecated function g_type_class_add_private(). Currently, we silent the warning during the compilation for GCC8.

**Comment by marmarek** [comment]
This whole task could be solved totally differently: replace mechanism for enabling/disabling audio input to a VM with something else. I.e. remove the whole `pacat-control-object.c`.

For GUI/Audio domain use (#1590), we need something else anyway, because dbus works only locally, but we need to enable/disable mic from dom0, even when pulseaudio run in dedicated VM.

I think it may be replaced with qubesdb. A per-vm entry in qubesdb instance local to Audio VM (which may or may not be dom0). Like `/audio-input-enable/<VM NAME>` with values `0` or `1`. `pacat-simple-vchan` would only read value there (missing value treat as `0`), while core-admin extension would write there.
