### ISSUE TITLE
Graphical interface to manage testing repository updates

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4550]
### Qubes OS version:

R4.0

### Affected component(s): 

Qubes Global Settings

---

### Steps to reproduce the behavior:

Look for a way in Qubes Global Settings to enable the testing repositories.

### Expected behavior:

There are checkboxes for them.

### Actual behavior:

There's only a checkbox for overall dom0 updates.

### General notes:

Overall I'm thinking about something that looks vaguely like https://help.ubuntu.com/community/Repositories/Ubuntu#Updates_Tab. I'm interested in contributing patches for this but I wanted to file an issue first to double-check that it'd be accepted.

---

**Comment by marmarek** [comment]
Good idea. I'd look for a tool for Fedora (or other dnf/yum based distro) first. If that exists, the task would be simple - just include it.
Official Fedora documentation mention only command line tools: https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/package-management/DNF/#sec-Managing_DNF_Repositories

**Comment by strugee** [comment]
I looked last night and didn't find anything new. That Ubuntu tool is only for APT, and the only other package I can think of for Fedora is GNOME Software. I wanted to see if it even includes this functionality but rejected it before I even installed it because it pulls in all sorts of wacky stuff - WebKit, ModemManager, Flatpak, ostree... the list goes on. I don't think we want all that stuff in dom0.

**Comment by strugee** [comment]
Actually, I looked again and found two interfaces we could use - yumex-dnf and dnfdragora. But neither seem optimal because the repository management stuff is integrated in a larger graphical interface. And the package management stuff, at least for installs, won't work because it's dom0.

Here are screenshots of both.

![screenshot_2018-11-27_14-51-34](https://user-images.githubusercontent.com/911174/49108110-52cb5780-f255-11e8-85ee-691112184706.png)
![screenshot_2018-11-27_14-55-35](https://user-images.githubusercontent.com/911174/49108106-4fd06700-f255-11e8-9b30-930bb5bce1ac.png)

**Comment by marmarek** [comment]
https://github.com/timlau/yumex-dnf seems to be dead. As for dnfdragora, it should be possible to either request a feature upstream (and probably implement it...) to open just that dialog, or create a wrapper script to do it.
But on the other hand, this dialog looks pretty simple, so it may be less work to just create it from scratch. As for actual repository configuration, I'd look at [dnf API documentation](https://dnf.readthedocs.io/en/latest/api_repos.html) and config_manager dnf plugin code (/usr/lib/python3.6/site-packages/dnf-plugins/config_manager.py).

This all will work if the application will run in dom0. But for separate GUI VM case, it will need some different handling (probably qrexec services for listing, enabling and disabling repositories). Yet another reason for creating separate application instead of using dnfdragora.

**Comment by strugee** [comment]
@marmarek I'll start working on some qrexec services to start with, so we don't have to rewrite this later.

**Comment by strugee** [comment]
So, I started tinkering with qrexec (which I've never used before) but I can't figure out a good way to test a dom0 to dom0 call. `qrexec-client -d dom0 admin.repos.List` just says:

> ERROR: when target domain is 'dom0', -c must be specified

and then prints usage. Any idea on how to get around this? Or am I going about it wrong?
