### ISSUE TITLE
Clarify TRIM/discard note about 4.0

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4565]
From https://www.qubes-os.org/doc/templates/#important-notes-r40 :
> Template VMs are created in a thin pool, making `qvm-trim-template` no longer necessary.
> 
> The root filesystems in Standalone VMs can employ TRIM/discard on the root fs using normal tools and configuration options.

The following points should be clarified:
- This mentions StandaloneVMs, but what about TemplateVMs?
- This says that "the root filesystems in Standalone VMs *can* employ TRIM/discard...," but do they? Is any user action required to make this happen, or does it happen automatically?
- What are the "normal tools and configuration options"?

Related issue: #3033

CC: @esote

**Comment by xaki23** [comment]
> However, it should be noted that TRIM / discarding doesn't help with free space on thin pools, it's used for SSD wear leveling.

actualy, trim/discard is exactly what makes the thin-pool free up space again.


```
[root@dom0 ~]# qvm-create -l green test-trim
[root@dom0 ~]# qvm-run -p test-trim "sudo mount | grep /rw"
/dev/xvdb on /rw type ext4 (rw,relatime,discard,data=ordered)
[root@dom0 ~]# lvs | grep test-trim-private-snap
  vm-test-trim-private-snap   qubes_dom0 Vwi-aotz--   2.00g pool00   vm-test-trim-private    4.77
```
== default setting is discard enabled


```
[root@dom0 ~]# qvm-run -p test-trim "dd if=/dev/zero of=nullz bs=1M count=1000"
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 4.50928 s, 233 MB/s
[root@dom0 ~]# lvs | grep test-trim-private-snap
  vm-test-trim-private-snap   qubes_dom0 Vwi-aotz--   2.00g pool00   vm-test-trim-private   51.85
[root@dom0 ~]# qvm-run -p test-trim "rm nullz"
[root@dom0 ~]# lvs | grep test-trim-private-snap
  vm-test-trim-private-snap   qubes_dom0 Vwi-aotz--   2.00g pool00   vm-test-trim-private    4.78
```
== space in the pool is freed up automaticly on file deletion (== discard is working)

```
[root@dom0 ~]# qvm-run -p test-trim "dd if=/dev/zero of=nullz bs=1M count=1000"
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 4.24448 s, 247 MB/s
[root@dom0 ~]# lvs | grep test-trim-private-snap
  vm-test-trim-private-snap   qubes_dom0 Vwi-aotz--   2.00g pool00   vm-test-trim-private   53.61
[root@dom0 ~]# qvm-run -p test-trim "sudo mount -o remount,nodiscard /rw"
[root@dom0 ~]# qvm-run -p test-trim "rm nullz"
[root@dom0 ~]# lvs | grep test-trim-private-snap
  vm-test-trim-private-snap   qubes_dom0 Vwi-aotz--   2.00g pool00   vm-test-trim-private   53.61
```
== with discard disabled space in the pool is not freed up

```
[root@dom0 ~]# qvm-run -p test-trim "sudo fstrim -v /rw"
/rw: 1.9 GiB (2035888128 bytes) trimmed
[root@dom0 ~]# lvs | grep test-trim-private-snap
  vm-test-trim-private-snap   qubes_dom0 Vwi-aotz--   2.00g pool00   vm-test-trim-private    4.78
```
== fstrim frees up the space

**Comment by esote** [comment]
@xaki23 I was referring to [disk TRIM](https://en.wikipedia.org/wiki/Trim_(computing)), from what @marmarek said in [#3686 (comment)](https://github.com/QubesOS/qubes-issues/issues/3686#issuecomment-371870930). Nonetheless if discard is enabled by default, it still means no user action is needed per my commit above.

**Comment by xaki23** [comment]
@esote yes, this is all about "disk trim". it is the exact same mechanism. thinpool and ssd even react in pretty much the same way: they add the discarded chunk back to their free list (+/- blocksize constraints). 

the default situation on Qubes 4 is to have trim/discard enabled _above_ the thinpool (so it helps with space management), but disabled _below_ the thinpool (for security/privacy reasons, so no ssd wear leveling).

the reason a "monthly trim in dom0" doesnt "impact space usage" is that discard is already enabled in dom0.
my suggestion would be to just drop the second part of your doc update.
as in, "qvm-trim-template no longer required" is good, but the rest is just confusing.

doing a manual trim on templates once after install is mildly useful because it frees up space allocated by inefficient sparse handling in tar. 
for a freshly installed fedora template, that is around 200MB. 
for a mirage template it reduces space usage from ~180MB to ~8MB.
but this should really be done automaticly during template install and not part of user documentation.

**Comment by esote** [comment]
@xaki23 You're looking at an old commit in the pull request, look at the latest version of it. I removed that part because me and @andrewdavidwong agreed it was confusing.

**Comment by xaki23** [comment]
ups, yes, i only looked at the one commit linked here in the issue, not the three additional ones in the pull-request.
sorry for the confusion.
