### ISSUE TITLE
qubesadmin base.py : "RuntimeError: maximum recursion depth exceeded"

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4568]
### Affected component(s): qubesadmin

---

### Steps to reproduce the behavior:

in dom0 type `python` (or `python3`), in python-shell run

    import qubesadmin
    dummy = qubesadmin.app.QubesBase()
    dummy.nonexistingproperty
    File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 68, in qubesd_call payload_stream)
    [repeated too often for terminal to show start]
    RecursionError: maximum recursion depth exceeded

Especially damaging:
`dummy.get_label("blue")` shows the same behavior.

### Expected behavior:

No recursion

### General notes:

This is probably a recursive import-problem.

---

### Related issues:

Possibly: https://github.com/QubesOS/qubes-issues/issues/2146

**Comment by andrewdavidwong** [comment]
You're sure you don't have NetVM loop, right?

**Comment by GammaSQ** [comment]
Yes.

This is unrelated to networking, unless `qubesadmin.app.QubesBase` somehow trigger qubes-dom0-upgrade?

Anyway, qubes-dom0-upgrade works fine.

**Comment by GammaSQ** [comment]
I just tried creating a loop, just to see what would happen, and it's impossible:
`qvm-prefs: error: Loops in network are unsupported`

**Comment by marmarek** [comment]
While the error is indeed weird for this situation, the reason is that `QubesBase()` is an abstract class, which shouldn't be used directly. Use either `QubesLocal()` or `QubesRemote()`. Or even better `qubesadmin.Qubes()`, which choose the right one automatically.

I'll update the class documentation and make the error less confusing.
