### ISSUE TITLE
Provide a strong, random login password for each VM

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4571]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s): 

qubes-core-admin

---

### Steps to reproduce the behavior:

Run Chromium

### Expected behavior:

The keyring has already been unlocked (with a cryptographically strong password) when I login.

### Actual behavior:

The keyring is still locked.  This encourages a weak, easily-memorable password.

### General notes:

Qubes’s lack of per-VM disk encryption is one of the reasons this is an issue at all, but more importantly, it opens up local privilege escalation vulnerabilities on Windows and possibly other systems.

---

**Comment by marmarek** [comment]
The proper Qubes-way to store passwords, keys and other secrets is to use separate, isolated domain, instead of in-domain store. Regardless of how encrypted it is, it needs to be decrypted to be used, which means if domain is compromised, it will have access to all the secrets, regardless how strongly they are encrypted on the filesystem.
Separate domain makes sense for encryption keys when you can offload actual crypto operation to it (like split-gpg does) - this way, the domain more exposed to attacks (like with web browser, email client etc) never have access to actual key material. But similar reasoning also makes sense for normal passwords - it will not eliminate leaking them into web-browser-running VM, but will limit the scope to recently used passwords, not all if them.

So, it would have more sense to implement split-gpg-like solution for passwords. Maybe gnome-keyring drop-in solution implementing [Secret Service API](https://specifications.freedesktop.org/secret-service/index.html) ?

> Qubes’s lack of per-VM disk encryption is one of the reasons this is an issue at all

Care to explain more? What threat that would prevent? Some in-VM compromise scenario? Limit damage in case of dom0 compromise? If the latter, the expected behavior "The keyring has already been unlocked (with a cryptographically strong password) when I login" contradict it, because that means the password is stored somewhere in recoverable form, so compromised dom0 would have access to it (and to this per-VM disk encryption key too, if the behavior would be the same).

**Comment by DemiMarie** [comment]
> The proper Qubes-way to store passwords, keys and other secrets is to use separate, isolated domain, instead of in-domain store. Regardless of how encrypted it is, it needs to be decrypted to be used, which means if domain is compromised, it will have access to all the secrets, regardless how strongly they are encrypted on the filesystem.

I know and agree.  However, on Windows, a weak password creates in-VM privilege escalation vulnerabilities.  If the VM is joined to a domain, it may create remote code execution vulnerabilities.  I don’t think Linux is similarly vulnerable, unless it is using Kerberos or similar.

> Separate domain makes sense for encryption keys when you can offload actual crypto operation to it (like split-gpg does) - this way, the domain more exposed to attacks (like with web browser, email client etc) never have access to actual key material. But similar reasoning also makes sense for normal passwords - it will not eliminate leaking them into web-browser-running VM, but will limit the scope to recently used passwords, not all of them.
> 
> So, it would have more sense to implement split-gpg-like solution for passwords. Maybe gnome-keyring drop-in solution implementing [Secret Service API](https://specifications.freedesktop.org/secret-service/index.html) ?
>
That would be awesome.
> 
> > Qubes’s lack of per-VM disk encryption is one of the reasons this is an issue at all
> 
> Care to explain more? What threat that would prevent? Some in-VM compromise scenario? Limit damage in case of dom0 compromise? If the latter, the expected behavior "The keyring has already been unlocked (with a cryptographically strong password) when I login" contradict it, because that means the password is stored somewhere in recoverable form, so compromised dom0 would have access to it (and to this per-VM disk encryption key too, if the behavior would be the same).
>
The idea is to securely erase the per-VM disk encryption key when the VM is deleted.

**Comment by marmarek** [comment]
> However, on Windows, a weak password creates in-VM privilege escalation vulnerabilities. If the VM is joined to a domain, it may create remote code execution vulnerabilities.

The original problem you've described applies only to Linux. We do not set empty password on Windows VMs, even with Qubes Windows Tools installed. We recommend enabling auto-login, but it does not affect the user account password.

> The idea is to securely erase the per-VM disk encryption key when the VM is deleted.

That makes sense. It still require the key to be securely erased from dom0, but that's much easier than ensuring the whole VM image securely erased.
