### ISSUE TITLE
Qubes OS as a Software Which Respect the User Freedom

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#4619]
### Qubes OS version:

R x 

### Affected component(s): 

Qubes OS

---

### Whats Happening:

Qubes OS contains non-free software by default. And that's without doubt is less secure , and doesn't respect user freedom (according to free/libre software definition). 

It would be great that if Qubes OS follow Debian example , Which comes as free software by default. 

Many might say how about microcode updates? well Microcode issue is not software , but its hardware problem made by evil companies like intel/amd.Though its not necessary all hardware needs a microcode updates e.g: 

- [The KGPE-D16](https://store.vikings.net/libre-friendly-hardware/vikings-d16-workstation) with coreboot/libreboot will run perfectly fine without microcode updates on the 6200 Opterons. 

 But again , even if there is no single hardware that doesnt need a microcode-nonfree updates it is not a software issue. (also new linux kernels wont solve Spectre V2 issue by default due to drop down performance read more [here](https://www.zdnet.com/article/linus-torvalds-after-big-linux-performance-hit-spectre-v2-patch-needs-curbs/)). 

---

**Comment by unman** [comment]
> without doubt is less secure

This is certainly not true. Let's not confuse respecting freedom with offering security.

**Comment by marmarek** [comment]
See also https://www.qubes-os.org/faq/#will-qubes-seek-to-get-certified-under-the-gnu-free-system-distribution-guidelines-gnu-fsdg

As @unman said, secure software doesn't need to be free and also free software doesn't necessary mean it's secure - those are two independent things. While in many cases being able to audit source code make it easier to _verify_ its security, it isn't required to be secure. Additionally, Qubes OS provide means to isolate those components, so even if your network card is running proprietary firmware, it is isolated from the rest of the system.

Also note that even if you have source code available, you actually run compiled binaries. And this is why we're working on [reproducible builds](https://reproducible-builds.org/who/) - to allow verification that the binaries you use are indeed coming from the source we publish.

That said, we do [encourage](https://www.qubes-os.org/news/2016/07/21/new-hw-certification-for-q4/) using free software. We'd very much like to have all the hardware on the market shipped with open source firmware and not require any binary blobs. Unfortunately, it isn't the case - many computers include components requiring proprietary firmware. Since hardware requirements for Qubes OS are already quite high, we decided to not rise the bar even further by _requiring_ not only hardware meeting Qubes requirements, but also running only free firmware. Especially when the device requiring non-free firmware is a network adapter (needed to install extra packages - like the firmware), or GPU (needed to install Qubes OS at all). This is why we ship those packages by default.
I don't exclude possibility of [partnering with a hardware vendor](https://www.qubes-os.org/doc/certified-hardware/) to deliver a hardware running only free software + a Qubes OS configuration shipping only such. But until then, default Qubes OS installation should be as much compatible with various machines available on the market. You can easily remove firmware packages after installation if you want. You can also [build](https://www.qubes-os.org/doc/qubes-builder/) own image with components of your choice.

**Comment by TNTBOMBOM** [comment]
> This is certainly not true. Let's not confuse respecting freedom with offering security.

Not thats a total rubbish , Do you tell me that i should trust a Secure Non-free firmware or package or OS? I think we are in 2018 not in 2008 , how many thousands reports showing hidden backdoors and sold vulnerabilities associated with proprietary software or meant to be dysfunction or the software has multiple functions (malware)...? There are many reports around the internet small samples like some collected stuff in [GNU-Proprietary](https://www.gnu.org/proprietary/) to [Cyber arsenal](https://wikileaks.org/vault7/) to ..etc

So no, Security should be always with the companion of free software.

> See also https://www.qubes-os.org/faq/#will-qubes-seek-to-get-certified-under-the-gnu-free-system-distribution-guidelines-gnu-fsdg

No comparison, Debian better than Qubes ethically because its free software. Nobody said it should be FSDG , but on the same time it shouldnt contain non-free software.  (because Qubes is faraway from FSDG since its supporting the installation of Windows malware OS)

>I don't exclude possibility of partnering with a hardware vendor to deliver a hardware running only free software + a Qubes OS configuration shipping only such. But until then, default Qubes OS installation should be as much compatible with various machines available on the market. 

Alright , thats sound fair until then.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by 948127524** [comment]
"You can easily remove firmware packages after installation if you want."
How would I go about removing firmware except for graphic drivers?
And what about VMs? I would like to run linux-libre on all VMs if possible.

**Comment by andrewdavidwong** [comment]
> "You can easily remove firmware packages after installation if you want."
How would I go about removing firmware except for graphic drivers?
And what about VMs? I would like to run linux-libre on all VMs if possible.

As explained in our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), `qubes-issues` is not the place to ask questions (especially not closed issues). We ask that you please send your questions to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead.
