### ISSUE TITLE
No recycle-symbol for disp-vms

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4620]
### Affected component(s): xfce windows

---

### Steps to reproduce the behavior:

Press Alt+F3 to open Application Finder.
type "disp" to search programs running in disposable VMs.

Start a program.

### Expected behavior:

I'm not entirely sure where the recycle-symbol should appear. I remember it distinctly on all the windows running in a disposable-VM, but dimmly remember them in the application-finder as well. I'd expect for every interaction that either starts a disposable VM or is happening inside a disposable VM to announce itself with a recycle-symbol.

### Actual behavior:

In the application finder, the "directories" on the left are red locks with recycle-symbol. However, neither the icons in the application finder (the list on the right), nor the icons visible at the top left of started windows are replaced with the recycle-symbol.

**Comment by marmarek** [comment]
This may be problematic visually, because for applications - both in menu and on running windows (which BTW technically are completely different things) - we use actual application icon, and recycle-symbol may not fit well. Right now that symbol is designed to fit the default padlock icon.

One idea would be to slightly downscale the actual icon, shift it to (for example) left top corner, then add the symbol on right bottom corner, overlapping with the icon. Actually, we could do that with all the icons - instead of changing their colors, add such overlay padlock with appropriate color, possibly with recycle symbol for DispVM. Similar to how Nautilus file manager mark read-only files, or symlinks.
