### ISSUE TITLE
unable to install on asus x470f

### ISSUE THREAD

**Issue by nothingworth** [QubesOS/qubes-issues#4623]
### Qubes OS version: 

R4.0

### Affected component(s): 

motherboards: asus x470f bios version 4024, cpu: amd 2700x

---

### Steps to reproduce the behavior:

I use usb drive to install Qubes on a new pc. After test the media & install qubes R4.0 I got below result.

### Actual behavior:

[Firmware Bug]: cpu 0, try to use APIC510 (LVT offset 1）for vector 0xf9, but the register is already in use for vector 0x0 on this cpu
[Firmware Bug]: cpu 0, failed to setup threshold interrupt for bank 0, block 0 (MSRC0002003=0xd010000000000000)
[Firmware Bug]: cpu 0, try to use APIC510 (LVT offset 1）for vector 0xf9, but the register is already in use for vector 0x0 on this cpu
[Firmware Bug]: cpu 0, failed to setup threshold interrupt for bank 1, block 0 (MSRC0002013=0xd010000000000000)
[Firmware Bug]: cpu 0, try to use APIC520 (LVT offset 2）for vector 0xf4, but the register is already in use for vector 0x0 on this cpu
.
.
.
[Firmware Bug]: cpu 15, try to use APIC510 (LVT offset 1）for vector 0xf9, but the register is already in use for vector 0x0 on this cpu
[Firmware Bug]: cpu 15, failed to setup threshold interrupt for bank 0, block 0 (MSRC0002003=0xd010000000000000)
[Firmware Bug]: cpu 15, try to use APIC510 (LVT offset 1）for vector 0xf9, but the register is already in use for vector 0x0 on this cpu
[Firmware Bug]: cpu 15, failed to setup threshold interrupt for bank 1, block 0 (MSRC0002013=0xd010000000000000)
[Firmware Bug]: cpu 15, try to use APIC520 (LVT offset 2）for vector 0xf4, but the register is already in use for vector 0x0 on this cpu

ACPI Error: Needed [Integer/String/Buffer], found [Region] ffff8807d69737e0 (20170531/exresop-424)
ACPI Exception: AE_AML_OPERAND_TYPE, Could not execute arguments for [IOB2] (Region) (20170531/nsinit-412)

nouveau 0000:08:00.0: DRM: Pointer to flat panel table invalid

 

### General notes:

I don't know how to save the /run/initramfs/rdsosreport.txt to usb. So I pick all the red lines here. 

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
