### ISSUE TITLE
Attach audio input works on debian but not fedora

### ISSUE THREAD

**Issue by keeponhacking** [QubesOS/qubes-issues#4637]
### Qubes OS version:

Qubes 3.2

### Affected component(s): 

USB Microphone attachment to VM

---

### Steps to reproduce the behavior:

When I right click on a VM in qubes manager and attach the audio-input to debian VM the microphone works.
When I fo the same for a fedora VM it doesnt work.

I should say that in pavucontrol the mic is assigned the same way and I see that the levels spike for both VM but the audio is not passed to the fedora in some way

### General notes:

---

**Comment by z4ppy** [comment]
Same here, release 3.2 and fedora 28

I did a downgrade of pulseaudio for that works (but qubes-gui-vm is
downgraded too).

Sorry for my poor english

Regards,

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
