### ISSUE TITLE
Signing key for some QSBs is not in the QSB repo

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4664]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s): 

Qubes Security Bulletin repository

---

### Steps to reproduce the behavior:

Attempt to verify QSB 40.

### Expected behavior:

The keys needed to verify QSB 40 are in the QSB repo.

### Actual behavior:

While the signatures (at least @marmarek’s) on QSB 40 are valid, the corresponding public key is not in the repository.  The public key is valid (signed by the Qubes Master Signing Key), but I had to fetch it from a keyserver.

### General notes:

This is low-priority, but a minor nusance.

---

**Comment by andrewdavidwong** [comment]
All the required keys should already be here:

https://github.com/QubesOS/qubes-secpack/tree/master/keys/security-team

I used to add signed tags in `qubes-secpack`, but we decided that this might be confusing, since the key I used to sign them is not in `qubes-secpack`. Since I'm not a member of the Qubes Security Team (QST), we decided that it would make more sense for me to stop adding signed tags in `qubes-secpack` than to add my signing key. I still sign my own commits, but a QST member will always add a signed tag on top of my commit, so it should never be necessary to verify my signatures.

I hope this clears things up. If you still believe that one or more _required_ keys belonging to QST members are missing from `qubes-secpack`, please specify the missing key(s).

**Comment by DemiMarie** [comment]
This either has been fixed, or I was using GPG incorrectly.
