### ISSUE TITLE
GUI: use an standalone HVM as a DVM Template

### ISSUE THREAD

**Issue by ThomasWaldmann** [QubesOS/qubes-issues#4670]
Sometimes you want to start from a clean windows install and just try some windows software or do some tests, but not keep the resulting changes.

It would be nice if one could label a hvm as a template VM from the GUI and also use the GUI to create a DVM based on that.

**Comment by kschubitz** [comment]
This is actually already possible:
Just create a Windows 7 DVM (ie. "win7-dvm"), then do: "qvm-prefs win7-dvm template_for_dispvms True"
After this you can set win7-dvm as Disposable VM for other VMs, just make sure QWT is installed and working properly, otherwise the files can't be copied/opened (obviously).

The downside is that Windows HVMs are ram hungry, so you can run out of memory pretty fast if you open multiple files in DVMs.

**Comment by kschubitz** [comment]
I just saw that you wanted to do all this from the GUI, my mistake.

**Comment by marmarek** [comment]
From our IRL conversation I remember it was about standalone VMs. Adjusted title appropriately.

**Comment by ThomasWaldmann** [comment]
@marmarek thanks for fixing this, will try it as soon as it lands in stable channel.

**Comment by marmarek** [comment]
Note this only lands into Qubes 4.1.
