### ISSUE TITLE
qubes-qrexec-agent.service should be after qubes-misc-post.service

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4676]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s): 

qubes domU agent

---

### Steps to reproduce the behavior:

Include code in `/rw/config/rc.local` that edits (say) a `.desktop` file in `/etc/xdg/applications`.

### Expected behavior:

The edit has completed before the `.desktop` file is launched.

### Actual behavior:

There is a race condition.

### General notes:

The fix is trivial.

---

**Comment by marmarek** [comment]
I don't think qrexec agent should be started any later. For the problem you observe I see two better solutions:
 - instead of modifying `.desktop` file in rc.local, have customized one in `~/.local/share/applications` - which takes precedence over `/usr/share/applications`
 - add a waiting for rc.local (`qubes-misc-post.service`) in `qubes.WaitForSession` service - which have exactly this purpose - waiting until full user session is set, including everything needed to launch `.desktop` files; `qubes.WaitForSession` is already used before `qubes.StartApp`
