### ISSUE TITLE
Fedora 30: review final proposal for DNF UUID and possibly opt-out by default

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4698]
There is considered [feature](https://fedoraproject.org/wiki/Changes/DNF_UUID) that could allow tracking individual installations of Fedora 30+. Privacy concerns are discussed there, but depending on the final proposal it may or may not be enough for our privacy standards. Right now there is [discussion on fedora-devel](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/OATXNKZAF7VW7RBIJHD2RREDXUEHJGHQ/) about it.

**Comment by t4777sd** [comment]
Thank you for always looking out for the users here.

**Comment by lunarthegrey** [comment]
Whatever the final proposal is, I think the new template should opt-out by default if they choose to implement it. I believe it wouldn't be very good for privacy.

I also wonder how this would work with cloned templates. Would the UUID be generated when using `dnf` for the first time or installing the OS? I could see this providing false statistics. Depending on how it works, it could expose people who are using a template, rather than running a fresh install. For example, if everyone using the Fedora 30 Qubes template had the same UUID. I didn't read the whole discussion because it's quite long, so I might be missing something.

**Comment by marmarek** [comment]
The discussion resulted in dropping UUID idea at all. And instead use "countme" boolean flag which gets set once a week (at most). This way, they can more reliably count users, without being able to distinguish individual installations. I think that solve privacy concern here.
See https://fedoraproject.org/wiki/Changes/DNF_Better_Counting
