### ISSUE TITLE
Macbook Pro (Retina, 13-inch, Early 2015):Qubes R3.2.1 no network device available

### ISSUE THREAD

**Issue by qu3stbaby** [QubesOS/qubes-issues#4707]
### Qubes OS version:
Qubes 3.2.1

### Affected component(s):
Qubes R3.2.1 System Network manager

### Steps to reproduce the behavior:
Following the steps on [this](https://www.qubes-os.org/doc/macbook-troubleshooting/#7-fix-system-freezes-due-to-broadcom-bcm43602)
```
sudo su -
xl pci-assignable-list
echo 03:00.0 > /sys/bus/pci/drivers/pciback/permissive
qvm-start sys-net
xl pci-attach sys-net 03:00.0
```

### Expected behavior:
There should be wifi showing so that I can connect

### Actual behavior:
`Device not managed` showed under Ethernet Network in the networkmanager applet

### General notes:
Null
### Related issues:
Null

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
