### ISSUE TITLE
Smartcard passthrough to HVM domain and/or RDP session

### ISSUE THREAD

**Issue by michaelschefczyk** [QubesOS/qubes-issues#4708]
Dear All,

On a notebook with R4.0 with just one USB controller, I would very much like to be able to pass an USB smartcard to an RDP session. I think that this goal is currently off limits. If anyone should see a way, I would very much like to learn about that.

One good mechanism to pass an USB smartcard to an RDP session in Linux is freerdp2-x11 plus some smartcard packages. For Debian stretch, everything is available in the normal repositories with the exception of freerdp2-x11, which is in stretch-backports. As far as I know, other common RDP clients do not include smartcard passthrough support.

Using the Debian 9 template does not work, as freerdp2-x11 will not function. I think this is due to freerdp requiring more of a desktop environment.

What does work half way is to install a Debian 9 HVM with freerdp2-x11. That will allow RDP sessions without relevant restrictions. Then, the impediment does seem to be that one cannot pass a single USB device plugged into the only USB controller available at the notebook to a HVM domain. Is this correct?

Also, adding the qubes repository to the Debian 9 HVM and trying to install qubes-usb-proxy seems to break that system.

Is there a path which I did not detect?

Thank you very much for your efforts!

Michael Schefczyk

**Comment by marmarek** [comment]
On Sun, Jan 13, 2019 at 06:24:00AM -0800, michaelschefczyk wrote:
> Using the Debian 9 template does not work, as freerdp2-x11 will not function. I think this is due to freerdp requiring more of a desktop environment.

What exactly is the problem? I've just tried `xfreerdp /v:...` on debian-9 based VM and it works for me.

> Then, the impediment does seem to be that one cannot pass a single USB device plugged into the only USB controller available at the notebook to a HVM domain. Is this correct?

Without qubes services inside, yes.

> Also, adding the qubes repository to the Debian 9 HVM and trying to install qubes-usb-proxy seems to break that system.

It should be possible to do that, but you need to be careful. Especially qubes-core-agent package modify /etc/fstab and include various services (especially qubes-mount-dirs.service) that assume /rw presence and /home living in /rw/home. Also qubes-gui-agent package (and a service with that name) will conflict with local X server.
But you should be able to install qubes-core-agent-qrexec and then qubes-usb-proxy. If not, please report exact errors (including broken dependencies).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by michaelschefczyk** [comment]
Thank you very much for responding so quickly!!

I did make a mistake here by trying xfreerdp in the template VM, not in an AppVM. After installing the packages in the template VM and rebooting it, xfreerdp does work perfectly well in an AppVM based on it. This is due to me otherwise using virtualization for servers, not desktop components as in qubes.

Installing freerdp2-x11 from stretch-backports and libusb-dev libccid pcscd libpcsclite1 plus libpcsclite-dev, redirecting the smartcard to an RDP session did work just as on a standard Debian PC. I guess that I will set up a few connect scripts in the AppVM and create shortcuts to them as shown in the qubes documentation.

**Comment by andrewdavidwong** [comment]
Looks like there's nothing to do here, so I'm closing this as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
