### ISSUE TITLE
Qubes Update: missing information in dom0 update details

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4742]
### Qubes OS version:

`R4.0.1`

### Affected component(s): 

Qubes Update widget

---

### Steps to reproduce the behavior:

Use the Qubes Update widget to update dom0 when no dom0 updates are available.

### Expected behavior:

Like `qubes-dom0-update` on the command line, the "details" pane should report that there are no updates available.

### Actual behavior:

The "details" pane just says:

```

Updating dom0

local:
    ----------

```

### General notes:

---

**Comment by marmarta** [comment]
@marmarek , another case when salt output looks lacking.

**Comment by marmarek** [comment]
I think this is because we use slightly different salt command for updating dom0 and VM. In case of VM it is `qubesctl ... state.sls update.qubes-vm` (a full state), while for dom0 it is `qubesctl pkg.upgrade` (a single salt function). The former execute multiple functions and wrap the result of each in a nice structure, while the latter output only result of that function (what would be put in `changes` field of state output), without all the other fields.

Unifying this indeed is a good idea.
