### ISSUE TITLE
"Port number or service 'xmpp-client' is invalid" in firewall settings

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4766]
### Qubes OS version:

R4.0

### Affected component(s):

Qubes Manager

---

### Steps to reproduce the behavior:

1. Open a VM's firewall settings
2. Ensure it is set to "Limit outgoing Internet connections to..."
3. Click the plus button
4. Set "Address" to example.com (or whatever) and "Protocol" to TCP
5. Type "xmpp" into "Service" and notice it autocompletes to "xmpp-client"
6. Hit OK (or Enter)

### Expected behavior:

The firewall rule is added.

### Actual behavior:

A dialog box pops up telling me that "xmpp-client" is an invalid port or service.

### General notes:

---

**Comment by strugee** [comment]
Seems to happen with `ircs` as the service too.

**Comment by bp2626** [comment]
It also occurs with smtps TCP or UDP.

4.14.74-1.pvops.qubes.x86_64

**Comment by dmoerner** [comment]
I think there are two separate issues here:

1. Some of the "services" listed in qubesmanager/firewall.py are actually protocols, but the algorithm seems to only be matching service names. The appropriate service for the smtps protocol on port 465 is urd. People sometimes also use the name "SMTPS" for traffic on port 587, but there the appropriate service name is submission. The service for ircs is actually called ircs-u. The simplest solution is to only list service names (urd, submission, ircs-u) in the gui, perhaps adding a note that protocol names can be found in /etc/services. A more involved solution would also match protocol names. (But I think it's important to be careful with this, the smpts/SMTPS case is a good example where protocol names might introduce confusion.)

2. I suspect that hyphens are not being properly matched. That's why xmpp-client isn't working, even though it is a service name. (And although ircs shouldn't work, ircs-u should work, but it doesn't.) But a quick glance at the code revealed that it's not clear why this is an issue, line 149 of qubesmanager/firewall.py does seem like it should handle hyphens appropriately.
