### ISSUE TITLE
Installation finished but “Qubes” boot option is missing and xen.cfg is empty r4.0.1 dell latiude e5xxx

### ISSUE THREAD

**Issue by jonull101** [QubesOS/qubes-issues#4802]
### Qubes OS version:
r4.0.1

### Affected component(s):
anaconda

---

### Steps to reproduce the behavior:
sh-4.3# efibootmgr
EFI variables are not supported on this system.
sh-4.3#modprobe efivars
modprobe: FATAL: Module efivars not found in directory /lib/modules/4.14.74-1.pvops.qubes.x86_64

### Expected behavior:

EFI variables should be supported on the system.

### Actual behavior:

EFI variables are not supported on this system.

### General notes:
In the troubleshoot UEFI you have an option 4. which says se below:
4. 
Create boot entry in EFI firmware (replace /dev/sda with your disk name and -p 1 with /boot/efi partition number):
efibootmgr -v -c -u -L Qubes -l /EFI/qubes/xen.efi -d /dev/sda -p 1 "placeholder /mapbs /noexitboot"

Well it does not work well since i get the error:
EFI variables are not supported on this system.

Can anyone give me a hand and guide on this one?

---

**Comment by andrewdavidwong** [comment]
This might be too localized for qubes-issues, but I'll leave it open for now to see what the devs think.

**Comment by marmarek** [comment]
"EFI variables are not supported on this system." message suggests the system is _not_ booted in EFI mode. So, indeed it doesn't look like an installer issue (at least at this stage) and better be discussed on qubes-users mailing list.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
