### ISSUE TITLE
R 3.2 dom0 install / update spooky messages in terminal (not found deltainfo, not found updateinfo)

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#4823]
### Qubes OS version:

R 3.2

### Affected component(s):

dom0 (?)

---

### Steps to reproduce the behavior:

Try doing anything with qubes-dom0-update, like run an update or install software 

 

### Expected behavior:

The action completes without any messages that would be obviously spooky

### Actual behavior:

messages 
not found deltainfo for: Fedora 23
not found updateinfo for Fedors 23 

appear, and they make me feel... worried.

### General notes:

The updates, however, seem to install fine. At least the last check and install happened without issue. Still, what are those messages about (and how to fix them)?

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
