### ISSUE TITLE
R4.1: Restore Grub2 in UEFI mode

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4902]
Current installation image boot xen.efi directly for a good reason: https://github.com/QubesOS/qubes-issues/issues/3505
But with Xen >= 4.11 and Grub 2.02, this reason doesn't apply anymore, because it's possible to boot Xen using multiboot2 protocol. This means Grub would load all the related files (using its own filesystem support), instead of Xen relying on fragile EFI FS services.
Restoring Grub should give more flexibility - at least allow to choose boot option (including "rescue"), and also edit boot options.

This is about installer image for now. Similar idea applies to installed system too.

**Comment by marmarek** [comment]
Blocked on https://bugzilla.redhat.com/show_bug.cgi?id=1691559 (multiboot2 module excluded from grub2-efi-x64-modules Fedora package).

Since it was done on purpose there, depending on upstream response, we may need to fork grub2 package :/

**Comment by brendanhoar** [comment]
This red hat/fedora security issue is from around the same timeframe:  https://bugzilla.redhat.com/show_bug.cgi?id=1549798

It's listed as QEMU/multiboot and does not mention grub...but there are several linked tracking bugs, some of which appear to be closed or duplicates, that are not publicly available. Odds on future security bulletins making it clear this blocker is related? 

Especially because the discussion in this other issue indicates that they are paying a lot of attention to secure boot validation chains... https://bugzilla.redhat.com/show_bug.cgi?id=1318667

B

**Comment by iprid23** [comment]
I was just about to write a Git Issue about this feature but then I found this. Anyway there was nothing in the documentation regarding the fact that xen.efi does not allow you to pick kernel/modify kernel parameters.

**Comment by marmarek** [comment]
`xen.efi` needs separate `xen.cfg` for that (which we have). See https://www.qubes-os.org/doc/uefi-troubleshooting/ and https://wiki.xenproject.org/wiki/Xen_EFI#Xen_as_EFI_binary_.28loading.29

**Comment by JarrahG** [comment]
I'm currently testing this configuration on my system and can confirm that the install with the above patches applied worked well. 
However, another patch for the kernel and kernel-latest packages will be required to change their install script to update both `/boot/grub2/grub.cfg` and `/boot/efi/EFI/qubes/grub.cfg`. Currently only the former is being updated by the install script.

**Comment by marmarek** [comment]
Good point, thanks for the reminder.
