### ISSUE TITLE
DNS Servers Not Different For VPN-Connected, Whonix, Etc.

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#4906]
### Qubes OS version:
R4.0

### Affected component(s) or functionality:

DNS / `nslookup` on AppVMs

---

### Steps to reproduce the behavior:

Create several App VMs.  Some connect to sys-firewall.  Some connect through Proxy VM configured like https://www.qubes-os.org/doc/vpn/ (including "DNS Handling Script")

Some are connected through `sys-whonix`

Notice that `nslookup` on every AppVM shows:

```
user@host:~$ nslookup
> google.com
Server:         10.139.1.1
Address:        10.139.1.1#53

Non-authoritative answer:
Name:   google.com
Address: 172.217.19.78
> 
```

### Expected or desired behavior:

Well really I don't know.  I read https://www.qubes-os.org/doc/networking/, I read https://www.qubes-os.org/doc/firewall/, I read https://www.qubes-os.org/doc/vpn/.  And there is nothing that really explains how DNS works so I understand like I want.

But the desired behavior is:

- AppVMs connected through sys-firewall use default DNS
- AppVMs connected through VPN proxy use VPN for DNS
- AppVMs connected through `sys-whonix` use tor for DNS

And I guess we would see something different for each `nslookup` , not always `10.139.1.1`?

### Actual behavior:

`nslookup` shows DNS always like above

### General notes:

If there is a doc page that explains this please send the link.

---

**Comment by t4777sd** [comment]
10.139.1.1 just the internal address that forwards to the parent VM in the network chain. So, dns for normal vm uses sys-net (forwarding from VM -> sys-firewall -> sys-net). Once sys-firewall gets it, then it forwards it because sys-firewall is not designed to process the request so it forwards it. DNS for VPN uses VPN. DNS for whonix uses whonix. Each VM forwards the DNS request to its parent using that same address which is just an alias for being forwarded down the line. 

Which VPN actually processes it will depend on if one is setup to process DNS requests. If not, then sys-net will process it by forwarded it to whatever DNS server it has in it's resolv file (for example google 8.8.8.8). 

If you have a VPN or whonix it sits between the VM and sys-net. So, it does not forward the request to sys-net. It will instead perform the DNS request as it wants to (typically VPN through the VPN server and whonix through tor) and replies back to the VM. So, each group of VMs are using separate DNS resolving.

**Comment by straussmaus** [comment]
@t4777sd

Thank you for explaining this.

>  Each VM forwards the DNS request to its parent using that same address which is just an alias for being forwarded down the line.

Where in the AppVM is the code/file/process that "labels" this alias?  I want the reassurance of seeing it for myself.

**Comment by marmarek** [comment]
> Where in the AppVM is the code/file/process that "labels" this alias? I want the reassurance of seeing it for myself.

See `iptables -t nat -nL`, especially `PR-QBS` chain. It's filled by `/usr/lib/qubes/qubes-setup-dnat-to-ns` script.

**Comment by straussmaus** [comment]
@marmarek

??  The output of `iptables -t nat -nL` is:

```
sudo iptables -t nat -nL
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
PR-QBS     all  --  0.0.0.0/0            0.0.0.0/0           
PR-QBS-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0           

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
MASQUERADE  all  --  0.0.0.0/0            0.0.0.0/0           

Chain PR-QBS (1 references)
target     prot opt source               destination         

Chain PR-QBS-SERVICES (1 references)
target     prot opt source               destination
```

What is `PR-QBS` and what does it have to do with this?  You dropped a term out of context?  And *what* is " filled by /usr/lib/qubes/qubes-setup-dnat-to-ns script."?  These are not normal standard Linux words, they are specific to the way Qubes is handling this.

**Comment by marmarek** [comment]
> ?? The output of `iptables -t nat -nL` is:

I forgot to say important detail: it's in network-providing VM (sys-net, sys-firewall, vpn vm etc).

**Comment by straussmaus** [comment]
@marmarek Okay then same questions.

This is the output of `iptables -t nat -nL from a VPN VM:

```
sudo iptables -t nat -nL
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
PR-QBS     all  --  0.0.0.0/0            0.0.0.0/0           
PR-QBS-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0           

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
MASQUERADE  all  --  0.0.0.0/0            0.0.0.0/0           

Chain PR-QBS (1 references)
target     prot opt source               destination         
DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 to:10.5.0.1
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 to:10.5.0.1

Chain PR-QBS-SERVICES (1 references)
target     prot opt source               destination  
```

This does not tell me anything about what DNS server I'm using.  I get this from `sys-firewall`:

```
Chain PR-QBS (1 references)
target     prot opt source               destination         
DNAT       udp  --  0.0.0.0/0            10.139.1.1           udp dpt:53 to:10.139.1.1
DNAT       tcp  --  0.0.0.0/0            10.139.1.1           tcp dpt:53 to:10.139.1.1
DNAT       udp  --  0.0.0.0/0            10.139.1.2           udp dpt:53 to:10.139.1.2
DNAT       tcp  --  0.0.0.0/0            10.139.1.2           tcp dpt:53 to:10.139.1.2
```

**Comment by t4777sd** [comment]
I recommend to post your questions to the Qubes Users mailing list. You can access it here: https://groups.google.com/forum/#!searchin/qubes-users/dns%7Csort:date/qubes-users/wNLLXi7aIyA/MutLpALuAgAJ

That is a thread that talks about DNS a bit, but you can post your own thread to gain clarification about how DNS works.

**Comment by straussmaus** [comment]
@t4777sd I know how DNS works.  I run three bind servers.  Anyway the mailing list is not an option until the Qubes team fixes it but that is not something for this issue.

**Comment by unman** [comment]
@straussmaus If you dont like the mailing list use the [Forum](https://qubes-os.info/). This really isn't the first place to go if you dont understand the documentation.

Your "expected behaviour" is *exactly* what happens.

Each qube has private IP set for DNS resolution. At the upstream netvm, any DNS requests are caught in the PR-QBS chain in nat table and subject to Destination NAT. 
In sys-net, DNS requests are subject to DNAT to the DNS resolver used for the external network.
In sys-whonix, DNS requests are subject to REDIRECT in the **PREROUTING** chain in nat table, and sent to localhost 5300 on sys-whonix, where Tor magic resolves them through the Tor network.
What happens in VPN netvm will depend on how you have configured it - in every case DNS requests _should_ be sent down the VPN tunnel.

Check the NAT table in sys-net, sys-whonix, and whatever you are using for VPN to confirm this.
The individual qubes are unaware of the DNS resolver that they ultimately use.

This is explained in the 2nd paragraph of the [networking page](https://www.qubes-os.org/doc/networking/) .
If you think that page could be clarified please submit a PR.

**Comment by andrewdavidwong** [comment]
> Anyway the mailing list is not an option until the Qubes team fixes it but that is not something for this issue.

If there is a legitimate problem with the mailing list that we can fix, please file an issue for it so that we can fix it. If it's just something you don't like, then I'm sorry, but we can't make an exception to the rules for that.

**Comment by straussmaus** [comment]
@unman 
>  If you dont like the mailing list use the Forum.

The forum is not online.  Also it is not an Issue tracker but doc Issues are Issues not conversations.

> Your "expected behaviour" is exactly what happens.

No it's not.  Pasting from my comment above:

```
And I guess we would see something different for each nslookup , not always 10.139.1.1?
Actual behavior:

nslookup shows DNS always like above
```

But the second paragraph in the link you sent sounds like it is saying that all DNS requests go to the same DNS server.  See:

```
The IP address of eth0 interface in AppVM, as well as two IP addresses to be used as nameservers (DNS1 and DNS2), are passed via QubesDB to AppVM during its boot (thus, there is no need for DHCP daemon in the network driver domain). DNS1 and DNS2 are private addresses; whenever an interface is brought up in the network driver domain, the /usr/lib/qubes/qubes_setup_dnat_to_ns script sets up the DNAT iptables rules translating DNS1 and DNS2 to the newly learned real dns servers. This way AppVM networking configuration does not need to be changed when configuration in the network driver domain changes (e.g. user switches to a different WLAN). Moreover, in the network driver domain, there is no DNS server either, and consequently there are no ports open to the VMs.
```

Your explanation gives different details for sys-whonix and VPN netvm.  Also none of this relates to my original comment.  You got off track *but* I really liked reading those details and they helped a lot because the networking page does not talk about this at all, which is why this Issue was important

> If you think that page could be clarified please submit a PR.

Well that is crazy.  Only the person who writes the code can write the doc.  If I write the doc what am I basing it on?  My understanding of your explanation?

Anyway I consider this Issue closed so I will close it.

@andrewdavidwong 

>  If it's just something you don't like, then I'm sorry, but we can't make an exception to the rules for that.

I did not ask for an exception.
