### ISSUE TITLE
ipv6 troubles?

### ISSUE THREAD

**Issue by ThomasWaldmann** [QubesOS/qubes-issues#4964]
Qubes 4.01 - this is still in the state of a suspicion, didn't fully debug this yet.

But maybe it is already known or rings a bell, so just posting it for feedback

I don't have working ipv6 internet in the VMs, I read in the wiki that this is opt-in (thus: not the default).

OTOH, name servers (no matter whether you reach them via v4 or v6) answer name queries with A **and** AAAA records.

Then a connection will be tried to one of the resolved IPs, following the preferences in `/etc/gai.conf` (on Debian 9).

The default preference is "v6 first, v4 second", so it means it will prefer the (by default) non-working v6.

Is this the reason for the quite long wait times I experience e.g. when using github? Some requests fast, some take forever (likely until it retries with v4?).

I somehow know this problem from non-qubes context with non-v6 LANs that have a DNS returning v6 addresses - I usually update the gai.conf there to look like this:
```
precedence  ::1/128       50
precedence  ::/0          40
precedence  2002::/16     30
precedence ::/96          20
precedence ::ffff:0:0/96  100
```

Maybe qubes should default to that ^^^ matching the "no ipv6 in VM" default?

**Comment by marmarek** [comment]
> OTOH, name servers (no matter whether you reach them via v4 or v6) answer name queries with A **and** AAAA records.

Qubes do not modify DNS responses. If a domain has both A and AAAA records (and application asks for both), both will be returned.

> The default preference is "v6 first, v4 second", so it means it will prefer the (by default) non-working v6.

This is indeed default for most modern systems (not only Linux). But if there is no IPv6 connectivity, it should be detected quite quickly, because there is no default route for IPv6. It doesn't even involve sending anything, application get "no route to host" answer immediately from the kernel.
Of course there may be some broken applications that doesn't deal with it correctly, but I wouldn't suspect any common app fall into this category.

But, if you have IPv6 default gateway, but there is no real IPv6 connectivity later on the network, then indeed it may cause such timeouts. Normally, any router (including network-providing VM) when get a packet it can't route, should respond with appropriate ICMP error (so application can immediately fallback to IPv4). But it's not uncommon for people to drop all ICMP on firewalls without understanding consequences...

If you have some VPN, or Tor in between, it may be configured to drop IPv6 instead of properly responding with ICMP.

In summary:
 - if you didn't enabled 'ipv6' feature, then VMs will not have IPv6 default gateway, the problem is probably somewhere else
 - if you enabled it, but you're connected to a network not providing IPv6, sys-net should generate appropriate ICMP replies; unless you specifically filtered out ICMP(v6) traffic (using qvm-firewall or custom scripts), it shouldn't result in delays
 - if you enabled it and you're connected to a network advertising IPv6 support, but not really providing it and a router configured to not generate/filter ICMP packets, then it may be source of the problem; proper solution would be to fix this network, but as a workaround you can edit gai.conf, or disable IPv6 on your system (it may be better to use network manager settings for that, as those work immediately; for 'ipv6' feature to take effect, you need to restart VMs)

**Comment by ThomasWaldmann** [comment]
I didn't enable it (yet). Thanks for explaining, will continue analyzing...

**Comment by ThomasWaldmann** [comment]
Just noted that the TTL on github.com is 60 seconds. So there's a bit more frequent nameserver traffic than usual.
