### ISSUE TITLE
create Debian buster template

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4970]
Buster is in full freeze since 2019-03-12.

Upgrading Qubes Debian stretch template to buster template worked well.

Buster is working stable and fast for me.

There soon will be a testers-only release of Non-Qubes-Whonix 15 which will be based on Debian buster.

(Whonix changes for porting to buster: https://github.com/Whonix/Whonix/compare/5959902f0f8faf71c3b45e04c03ad7d5940cee2e...15.0.0.0.7-developers-only)

The Qubes Debian buster template is a prerequisite for a Qubes-Whonix 15 templates.

Please create Debian buster template.

**Comment by unman** [comment]
It's usually about 4 months from full freeze to release - Jessie was closer to 6 months.
Plenty of time for testing.

**Comment by adrelanos** [comment]
To unblock release of Qubes-Whonix 15 it might be enough to merge https://github.com/QubesOS/qubes-builder-debian/pull/29. I wasn't aware that qubes-builder-debian source code already contains `buster` whenever it also contains `stretch` so the port seems almost complete and doable at first sight.

**Comment by adrelanos** [comment]
I see a template was uploaded.

https://github.com/QubesOS/updates-status/issues/1161

How to install on Qubes R4?

    sudo qubes-dom0-update --enablerepo=qubes-templates-itl-testing qubes-template-debian-10

?

**Comment by unman** [comment]
`sudo qubes-dom0-update --enablerepo=qubes-templates-itl-testing qubes-template-buster`

**Comment by adrelanos** [comment]
Was the naming scheme changed?

What's the name in QVMM? debian-10? Or debian-buster?

I am asking since I already manually created a TemplateVM debian-buster
and foresee the official one to become debian-10. This could brick
something.

**Comment by marmarek** [comment]
This change was unintentional, missing entry in config. Next build should use debian-10 name.

**Comment by adrelanos** [comment]
sudo qubes-dom0-update --enablerepo=qubes-templates-itl-testing qubes-template-debian-10

**Comment by TNTBOMBOM** [comment]
provide as well if possible Debian-10-minimal template. Thanks

**Comment by marmarek** [comment]
> provide as well if possible Debian-10-minimal template. Thanks :)

Done.

**Comment by 3hhh** [comment]
I tested the full template and noticed the following:

- The `cups.browsed` service opens a socket on eth0. I'm not sure whether that service is required at all.
- I'm not sure what `exim4` is needed for. I recall that it was a dependency in jessie for something relevant, but it was possible to remove it now.

Otherwise everything seems fine so far.

**Comment by marmarek** [comment]
> The `cups.browsed` service opens a socket on eth0. I'm not sure whether that service is required at all.

In theory it is for discovering network printers automatically. In practice it's unreachable because of layers of firewalls. So, it's only wasting RAM.

> I'm not sure what `exim4` is needed for. I recall that it was a dependency in jessie for something relevant, but it was possible to remove it now.

Looks like `cron` package `Recommends:` mail server (`default-mta | mail-transport-agent`). We disable `cron` service by default, so maybe we could avoid installing it in the first place. @unman any opinion? Generally [we avoid changing distribution defaults](https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros)
