### ISSUE TITLE
Fedora 30: updates proxy do not start

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4973]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
updates proxy

**Brief summary**
qubes-updates-proxy.service do not start, because tinyproxy is at `/usr/bin/tinyproxy`, but unit file  expects it at `/usr/sbin/tinyproxy`.

Subtask of #4845

**Comment by unman** [comment]
Compare #4929 - the same issue in buster. Does this reflect an upstream change in tinyproxy?

**Comment by esote** [comment]
@unman It appears to be an intentional change. The file listing [used to](https://fedora.pkgs.org/29/fedora-x86_64/tinyproxy-1.8.4-4.fc29.x86_64.rpm.html) have both `/bin` and `/sbin` [until now](https://fedora.pkgs.org/rawhide/fedora-x86_64/tinyproxy-1.10.0-3.fc30.x86_64.rpm.html). (See file listings on linked pages.) Although I can't find any online discussion on the change.

**Comment by esote** [comment]
@unman Found [the commit](https://github.com/tinyproxy/tinyproxy/commit/8d0ea71486688323fff65bc3730bae209a70db7b) for this change.
