### ISSUE TITLE
Qubes Global Settings TypeError

### ISSUE THREAD

**Issue by nzjgko** [QubesOS/qubes-issues#4988]
**Qubes OS version**
R4.0 with qubes-dom0-current-testing repository enabled

**Affected component(s) or functionality**
Qubes Global Settings

**Brief summary**
Can't open Qubes Global Settings.

**To Reproduce**
1. Get the the latest qubes-dom0-current-testing repository updates.
2. Try to open Qubes Global Settings via Applications -> System Tools -> Qubes Global Settings or via terminal ro via Qube Manager.
3. See the error.

**Expected behavior**
Qubes Global Settings windows opens.

**Actual behavior**
Get a windows with the error:

```
Whoops. A critical error has occured. This is most likely a bug in Qubes Global Settings application.

TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'at line 248 of file global_settings.py.

```

**Comment by iprid23** [comment]
Hello @nzjgko @andrewdavidwong 
I've reproduced this and traced it to this commit:
https://github.com/QubesOS/qubes-manager/commit/00ccce4816057c21221764e4381323482a2aaf1f#diff-03fdb1e1cbbd91819134b74dfc18f0ad

When this line of code was introduced:
```
           self.updates_dom0_val = self.qvm_collection.domains[
                'dom0'].features['service.qubes-update-check']
```
it did not take into account that self.qvm_collection.domains['dom0'].features['service.qubes-update-check'] is a string, whereas  `self.updates_dom0.setChecked(self.updates_dom0_val)` expects self.updates_dom0_val to be a boolean. A simple fix I am using is to just cast it:
```
 self.updates_dom0_val = bool(self.qvm_collection.domains[
                'dom0'].features['service.qubes-update-check']) 
```
I am not that experienced in Python though so I am not offering a pull request because someone could offer a better fix. And there could be more problems with strings passed where booleans are expected so a through check would be best.

Regards and I hope I can help to make Qubes better

**Comment by zS3mNH2** [comment]
According to #5146, this should be solved and in stable repository. However, it is not updateable via Qubes updates:

Running "sudo qubes-dom0-update --clean" gives the following:

```
33 files removed
Fedora 25 - x86_64 - Updates                    2.1 MB/s |  24 MB     00:11    
Fedora 25 - x86_64                              3.6 MB/s |  50 MB     00:13    
Qubes Dom0 Repository (updates)                 2.0 MB/s |  11 MB     00:05    
determining the fastest mirror (15 hosts).. done.--  B/s |   0  B     --:-- ETA
Qubes Templates repository                      1.7 kB/s |  12 kB     00:07    
Last metadata expiration check: 0:00:01 ago on Mon Jul  8 23:04:17 2019.
Dependencies resolved.
Nothing to do.
Complete!
No packages downloaded

```

```
rpm -q qubes-manager
qubes-manager-4.0.33-1.fc25.noarch

```

**Comment by marmarek** [comment]
I confirm that indeed update (contrary to the automatic comment) is not available in the stable repository. Looks like uploading the package failed.

**Comment by marmarek** [comment]
> I confirm that indeed update (contrary to the automatic comment) is not available in the stable repository. Looks like uploading the package failed.

Uploaded now.

**Comment by zS3mNH2** [comment]
FYI, I just tried to update with the --clean command it returns failed synchronization for all qubes related repositories:

Failed to synchronize cache for repo 'qubes-dom0-current'

**Comment by andrewdavidwong** [comment]
> FYI, I just tried to update with the --clean command it returns failed synchronization for all qubes related repositories:
> 
> Failed to synchronize cache for repo 'qubes-dom0-current'

I was able to download and install this update today, so I think you're just experiencing a temporary network problem. Usually waiting a bit and trying again works.

**Comment by hugoncosta** [comment]
Can confirm the update is live on the stable repo, just update and the problem will be instantly solved, thank you!
