### ISSUE TITLE
UX problem with warning icon next to "Networking" field

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#5115]
**Qubes OS version**

4.0.1

**Affected component(s) or functionality**

Qubes Manager 

**Brief summary**

Installing Debian Buster 10 from testing then open Basic settings page from Qubes manager it will show up a yellow mark (look at the screenshot).

**Expected behavior**

Doesnt show any error mark/sign 

**Actual behavior**

Showing error mark/sign

**Screenshots**

![busterqubesmanager](https://user-images.githubusercontent.com/11895339/59982413-932f6000-9601-11e9-9f7c-68c683ba6398.png)

**Comment by andrewdavidwong** [comment]
The icon itself is a feature, not a bug. Hover over it for an explanation.

Nonetheless, I can see two potential reasons to keep this bug report open:

1. The fact that you thought the icon was a bug indicates that there is a UX problem. In particular, users may not realize that they can or should hover over the icon for an explanation.
2. Perhaps you're thinking that the Debian 10 template should be configured out-of-the-box *not* to have the problem indicated by the icon.

Unfortunately, the latter is probably not possible, since the warning icon is caused by your default DisposableVM Template setting, which is global. It would be worse if installing a new template were to change this independent setting out from under you, especially if you had specifically configured it. Likewise, giving a TemplateVM a NetVM out-of-the-box is a no-go.

That leaves us with the first reason, so I'll label this as a UX issue and re-title it accordingly.

**Comment by andrewdavidwong** [comment]
One idea for how to address this is to have to some text next to the icon, e.g.:

> **Caution:** Unexpected network access possible. Learn more...

Where clicking on "Learn more..." provides the full explanation.

I also think the full explanation should be more verbose, e.g.:

> **Caution:** The Default DisposableVM Template (see the Advanced tab) has a different Networking setting than this qube. This configuration may result in unexpected network access. For example, you may have set this qube's Networking to "none" in order to prevent any data from being transmitted out. However, if the Default DisposableVM Template's Networking is set to "sys-firewall," then a DisposableVM started from this qube may be able to transmit data out, contrary to your intention. You may wish to set the Default DisposableVM Template for this qube to one with equally restrictive Networking settings.

**Comment by marmarta** [comment]
Maybe we should actually change the defaults a bit and make default DisposableVM for templates be "none" - templates are not, after all, designed for everyday use. (@adrelanos - do you use dispVMs from templates anywhere in Whonix? @marmarek - you probably want to be in this conversation)
I'm also not that convinced that a tooltip is insufficient - adding more text to the already-cramped Settings app seems like a bad idea. I can reword the tooltip according to @andrewdavidwong 's suggestion, though - it looks good.

**Comment by andrewdavidwong** [comment]
> I'm also not that convinced that a tooltip is insufficient - adding more text to the already-cramped Settings app seems like a bad idea.

Fair enough. I just mean some way to hint to the user that there's a tooltip to be found by hovering there. Perhaps the icon is already sufficient for that.

> I can reword the tooltip according to @andrewdavidwong 's suggestion, though - it looks good.

:+1:

**Comment by adrelanos** [comment]
Marta Marczykowska-Górecka:
> @adrelanos - do you use dispVMs from templates anywhere in Whonix?


open-link-confirmation uses qvm-open-in-dvm. That is broken, just now
fixed (as per above linked git commit) one bug related to it. There is
still another bug I didn't test this for a while and qvm-open-in-dvm
outputs "Request refused" with exit code 126 but no one had asked about
it for a very long time.

**Comment by andrewdavidwong** [comment]
Another example of a user being confused by this:

https://www.reddit.com/r/Qubes/comments/cws947/yellow_triangle_warning_next_to_networking_in/

**Comment by marmarta** [comment]
Okay, nobody invented any better way of putting it, so let's do the rewording.
