### ISSUE TITLE
Unable to connect to yum.qubes-os.org

### ISSUE THREAD

**Issue by dmoerner** [QubesOS/qubes-issues#5130]
I'm sorry if there's another way to report infrastructure problems, but I have been unable to connect to yum.qubes-os.org for at least 7 hours. dnf fails to refresh the repository in both dom0 and domU, websites like isitdownrightnow show it as failing to resolve. I am able to ping yum.qubes-os.org, it resolves to bruschetta.qubes-os.org.

It would be nice if there was some sort of site tracking whether infrastructure is up; perhaps there is but I just couldn't find it.

**Comment by mossy-nw** [comment]
I think the qubes-users@googlegroups.com email list is the bset place to check in quickly on things.  (See also https://www.qubes-os.org/support/#qubes-users ) 

I posted a question there, hopefully we'll find out soon!

**Comment by marmarek** [comment]
It's back online.

**Comment by phagara** [comment]
@marmarek the package repositories are down again

**Comment by marmarek** [comment]
Yes, there are some issues with the server, server provider is looking into it.

**Comment by marmarek** [comment]
There was a hardware failure beyond repair, the server was replaced and reinstalled (thanks to salt, this part took only minutes). All repositories should be live now.
Since this is new install, SSH host key and SSL certs are new - shouldn't matter for users.
One thing we've lost in the process is recent history of qubes users counter. Latest data I have is from February 2019, so 4 months are missing. If anyone has more recent version of data file (https://tools.qubes-os.org/counter/stats.json), please send it to me.
