### ISSUE TITLE
Renaming 'sys-net' breaks update proxy by not updating '/etc/qubes-rpc/policy/qubes.UpdatesProxy' with new name.

### ISSUE THREAD

**Issue by eirikke** [QubesOS/qubes-issues#5147]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
qubes-update-proxy
/etc/qubes-rpc/policy/qubes.UpdatesProxy
qubes-manager

**Brief summary**
If 'sys-net' is renamed or if new netvm is created '/etc/qubes-rpc/policy/qubes.UpdatesProxy' does not update line "$type:TemplateVM $default allow,target=sys-net", thus breaking the "Update qubes system" option.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Shutdown all VMs connected to 'sys-net'.
_2. Shutdown 'sys-net'.
_3. Rename 'sys-net' to any acceptable name.
_4. Restart renamed 'sys-net' and attached VMs (in this case sys-firewall).
_5. Highlight Fedora-26 or Debian-9 and click on the blue arrow 'Update qubes system' option.
_6. Observe that neither template will be able to update do to failure or qubes-updates-proxy not being able to connect to the repositories.

**Expected behavior**
Clicking "Update qubes system" updates selected qubes template.

**Actual behavior**
Clicking "Update qubes system" opens terminal for selected and gives the "Error: Failed to synchronize cache for repo 'qubes-vm-r4.0-current'" error.

**Solutions you've tried**
Editing the '/etc/qubes-rpc/policy/qubes.UpdatesProxy' line "$type:TemplateVM $default allow,target=sys-net" to reflect the new netvm or new netvm name fixes this issue for both the Fedore-26 and Debian-9 templates(which were both the templates tested).

**Comment by unman** [comment]
The problem here is that Qubes cant know what your intention is if you create a new netvm, since any qube can potentially act as host for the update-proxy.
Even in the case where you remove sys-net and the relevant line exists in Qubes.UpdatesProxy (whether active or not), then it is not necessarily clear what it is you want to do. Do you  want a new 'sys-net' (by whatever name) to be there, some other qube? 
How will Qubes know what to do, or select on your behalf?

**Comment by jdorel** [comment]
Maybe this should be a new attribute of one of the VMs ?
