### ISSUE TITLE
libvirt: ttyconsole not created

### ISSUE THREAD

**Issue by fepitre** [QubesOS/qubes-issues#5156]
While troubleshooting ```qvm-console``` tool, I managed to see that it was finally related to libvirt side. I'm facing a problem which is kind of random. Sometimes, a default standard PVH AppVM, got in it's log ```libxl-driver.log```:
```
2019-07-09 20:32:04.473+0000: libxl: libxl.c:1853:libxl_console_get_tty: unable to read console tty path `/local/domain/38/console/tty': Ressource temporairement non disponible
```
saying that the tty console is inaccessible whereas in xenstore:
```
38 = ""
  device = ""
...
   console = ""
    0 = ""
     frontend = "/local/domain/38/console"
     backend = "/local/domain/0/backend/console/38/0"
     frontend-id = "38"
     online = "1"
     state = "1"
     protocol = "vt100"
  type = "pvh"
  dm-version = "qemu_xen"
```
it exists and is accessible throught ```xl console```. A look at the current libvirt XML part related to the console of the VM:
```
<console type='pty'>
  <target type='xen' port='0'/>
</console>
```
the tty ```/dev/pts/X``` is not defined. Shutting down all the running VM and starting again this VM allows to obtain finally a tty console through libvirt and then through ```qvm-console```. A first talk with @marmarek seems that it's libvirt side and it's possibly a race condition. I never experienced such behavior, only on a fresh Qubes R4.0.2 installed on a HP DL360p Gen8.

**Comment by fepitre** [comment]
@marmarek: maybe I should notify upstream?

**Comment by marmarek** [comment]
Yes, good idea.

**Comment by fepitre** [comment]
Created libvirt issue: https://bugzilla.redhat.com/show_bug.cgi?id=1731678

**Comment by DemiMarie** [comment]
We may need to patch this ourselves, sadly.

**Comment by marmarek** [comment]
Sadly, yes. I was looking into this briefly, but didn't find anything obvious. Libxl->libvirt event reporting and VM startup logic is fairly complex (asynchronous code with "callback hell" pattern...), so I try to avoid looking at it, to not loose to many sanity points ;)

**Comment by pwmarcz** [comment]
I spent some time looking at code of libvirt and libxl. Here is how it's supposed to work:

1. We create a new domain via libvirt.
2. libvirt: [`libxlDomainStart`](https://github.com/libvirt/libvirt/blob/a37a8c569d7b05f39ec46665af9e81a9321d3d1a/src/libxl/libxl_domain.c#L1250) executes, registers a callback (`libxlConsoleCallback`) and creates a domain (`libxl_domain_create_new`).
3. libxl: the VM gets created, launches a bootloader, [sets `/local/<dom>/console/tty` in xenstore to the right device](https://github.com/xen-project/xen/blob/RELEASE-4.8.5/tools/libxl/libxl_bootloader.c#L486) and then [calls the callback function...](https://github.com/xen-project/xen/blob/RELEASE-4.8.5/tools/libxl/libxl_bootloader.c#L504)
   * which [uses libxl's async operations library](https://github.com/xen-project/xen/blob/RELEASE-4.8.5/tools/libxl/libxl_create.c#L999) to execute the original callback; so it possibly executes later? I'm not sure.
4. libvirt: eventually, [`libxlConsoleCallback`](https://github.com/libvirt/libvirt/blob/a37a8c569d7b05f39ec46665af9e81a9321d3d1a/src/libxl/libxl_domain.c#L1097) gets executed, and it tries to determine the TTY device by calling `libxl_console_get_tty`.
5. libxl: [`libxl_console_get_tty`](https://github.com/xen-project/xen/blob/RELEASE-4.8.5/tools/libxl/libxl.c#L1815) tries to read `/local/<dom>/console/tty` and fails.
   * I don't think the read from xenstore actually fails, but rather it returns an empty string (which is also interpreted as failure). From what I've seen in the xenstore code, I think a read cannot fail with `EAGAIN`. Also see below.

Now, what happens in xenstored? I ran the daemon with trace option (XENSTORED_TRACE=1), and got the following trace:

```
$ grep '/domain/6/console/tty' xenstored-trace.log 
IN 0x18618b0 20200211 16:02:56 WRITE (/local/domain/10/console/tty )
IN 0x18618b0 20200211 16:02:56 SET_PERMS (/local/domain/10/console/tty n0 r10 )
IN 0x18618b0 20200211 16:02:56 READ (/local/domain/10/console/tty )
OUT 0x185f140 20200211 16:02:56 WATCH_EVENT (/local/domain/10/console/tty dom10 )
IN 0x185f140 20200211 16:02:56 WRITE (/local/domain/10/console/tty /dev/pts/9)
OUT 0x185f140 20200211 16:02:56 WATCH_EVENT (/local/domain/10/console/tty dom10 )
```

It looks like at first, the key is initialized to empty (there are a bunch of other keys related to console being written to at the same time), and then `/dev/pts/9` is written. However, the READ happens before WRITE. 

For other machines, where `libvirt` did not error out, the trace looks like this:

```
IN 0x185df50 20200211 15:07:52 WRITE (/local/domain/6/console/tty )
IN 0x185df50 20200211 15:07:52 SET_PERMS (/local/domain/6/console/tty n0 r6 )
OUT 0x185f140 20200211 15:07:52 WATCH_EVENT (/local/domain/6/console/tty dom6 )
IN 0x185f140 20200211 15:07:52 WRITE (/local/domain/6/console/tty /dev/pts/6)
OUT 0x185f140 20200211 15:07:52 WATCH_EVENT (/local/domain/6/console/tty dom6 )
IN 0x185df50 20200211 15:07:52 READ (/local/domain/6/console/tty )
```

Note also that the WRITE and the READ happen from different connections to xenstored (the hex number at the beginning).

I can see two explanations:

* The logic in `libxl` is somehow wrong and calls the callback before writing.

  The code is pretty complicated, but it doesn't look like that to me.
* The race condition is in `xenstored`, because one connection handler (on a separate thread?) writes a key, and another reads it.

  I don't know if that's possible and whether `xenstored` gives any guarantees about operation order.

**Comment by pwmarcz** [comment]
Okay, according to @marmarek we don't use libxl to run a bootloader, so my reading of the code changes. We skip the PTY setting part, and skip to [`domcreate_bootloader_done`](https://github.com/xen-project/xen/blob/RELEASE-4.8.5/tools/libxl/libxl_create.c#L1022) then `domcreate_devmodel_started`, `domcreate_attach_devices`, and finally `domcreate_console_available` at which point we run the "console available" callback. 

The console path would be then set [in xenconsoled](https://github.com/xen-project/xen/blob/RELEASE-4.8.5/tools/console/daemon/io.c#L412), but libxl knows nothing about that and does not wait for it to appear, so there is a race condition.
