### ISSUE TITLE
Dom0 update caused Qubes tools to become out of sync with Xen regarding running state of VMs

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5303]
**Qubes OS version (if applicable)**
R4.0 current-testing

**Affected component(s) or functionality (if applicable)**
qui components, qubes-/qvm- components

**Brief summary**
After a combined dom0 update yesterday (qubes-updates: 1283, 1285, 1289), qubes tools became out of sync with xen w/r/t running state of VMs. e.g. Qubes Domains widget could be used to initiate shutdown of VMs, but shutdown status was not updated (VMs remained in menu). xentop was used to verify that VM shutdowns had completed.

**Additional context**
Presumably running update 1289 ( https://github.com/QubesOS/updates-status/issues/1289 ) without an intervening restart was the culprit.

Rebooting returned system to normal behavior.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/software-update-dom0/

No mention that updates should not be performed on a system in use or that a shutdown/restart is warranted.* 

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

B

\* I could, instead, submit this as a bug report about how live-system updates to qubes-core should better preserve state when swapping out the code infrastructure. However, as there were xen updates in parallel, I don't want to 100% assume that is the issue. Let me know.

**Comment by andrewdavidwong** [comment]
I think this should be more than a documentation issue. In order of preference (but without taking into account feasibility or cost):

1. Make it so that this problem doesn't arise in the first place.
2. Warm the user about updating dom0 while running VMs and prompt the user to reboot afterward.
3. Document this.

**Comment by marmarek** [comment]
> Make it so that this problem doesn't arise in the first place.

This specific issue is caused by incomplete libvirt daemon restart handling. There is a TODO comment in the code...
https://github.com/QubesOS/qubes-core-admin/blob/46ad75a3ba5c8dbb8db18472923ebaea3d7638ce/qubes/app.py#L112:

            # TODO: re-register event handlers

Generally, updating dom0 or VMs within the same Qubes major release should be safe. Any problems arising from this should be handled as bugs, not a missing reboot step.

**Comment by andrewdavidwong** [comment]
> Generally, updating dom0 or VMs within the same Qubes major release should be safe. Any problems arising from this should be handled as bugs, not a missing reboot step.

In that case, I'll convert this to a more specific bug report.

**Comment by brendanhoar** [comment]
Thanks!
