### ISSUE TITLE
qvm-create error message unhelpful on missing template

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#5316]
**Qubes OS version**

R4.0.2-rc1

```
[user@dom0 ~]$ rpm -q qubes-core-admin-client
qubes-core-admin-client-4.0.26-0.1.16.fc25.noarch
```

**Affected component(s) or functionality**
qubes-core-admin-client

**Brief summary**
When creating a VM with qvm-create and specifying a template that does not exist, it tries anyway, and then provides a very generic error message when it fails - which can be non-obvious to a user if you made a subtle typo.

**To Reproduce**
```
[user@dom0 ~]$ qvm-create -l red -t some-template-name-with-a-subtle-typo foo
app: Error creating VM: Got empty response from qubesd. See journalctl in dom0 for details.
```

**Expected behavior**
```
[user@dom0 ~]$ qvm-create -l red -t some-template-name-with-a-subtle-typo foo
qvm-create: Error creating VM: Template "some-template-name-with-a-subtle-typo" does not exist.
```
(or similar)

**Additional context**
I'm not sure that we should actually refuse to make the qubesd call if the client is not aware of the template VM (could just be state synchronization issues, and we don't necessarily want to forbid an action that would otherwise succeed - and also it's probably undesirable to require admin.vm.List permissions to perform admin.vm.Create.AppVM), so it seems that client-side checking for the existence of the template is probably not the way to go. However, a better error message would still be helpful.

Also, it's not clear that this even matters, since most users will probably want to use the `qubes-vm-create` GUI anyway, where template choice is enforced to be (probably) legal via only being able to select extant ones in a dropdown menu, and one could assume that qvm-create is for people who know what they're doing and don't make typos...

**Comment by marmarek** [comment]
Summary of a discussion with @pwmarcz:
Some ideas:
1. Convert (hidden) `PermissionDenied` exception to some client-reported `QubesException` (`QubesVMNotFoundError` probably).
2. Handle it client side (either verify before trying to create the VM, or after - trying to guess why it failed)

The first one is better, but have an issue with restricted policy and possible data leak: if someone use an core-admin extension to limit what templates can be used (by handling appropriate `admin-permission:...` event), it will be possible to distinguish between "no such template" and "disallowed template" cases. It's because `fire_event_for_permission()` call is after template existence check. Some idea would be to raise `QubesVMNotFoundError` in such extension when one want to hide template, but it doesn't looks nice. And would probably require some extra logging to avoid very confusing situations when debugging related stuff.

**Comment by ben-grande** [comment]
This issue was solved at least for `qvm-create`.

```sh
qvm-create -l red -t ohno yes
app: Error creating VM: No such domain: 'ohno'
```

https://github.com/QubesOS/qubes-core-admin/blob/335c9085b454706d99c511a71fd9c178b8ed5885/qubes/api/admin.py#L1232
