### ISSUE TITLE
Doamin sys-net has failed to start :internal error : libxenlight failed to create new domain 'sys-net'

### ISSUE THREAD

**Issue by 0xh0n3y** [QubesOS/qubes-issues#5336]
**Qubes OS version 4.0**

Wifi is not starting up

No vm is working since i had installed qubes Os

![15691464816271524460321676305138](https://user-images.githubusercontent.com/23690578/65385577-19b52400-dd4e-11e9-855a-f5a9ceb236a0.jpg)
![15691465289774471603849747728900](https://user-images.githubusercontent.com/23690578/65385583-2df92100-dd4e-11e9-9f21-908bd87f84a8.jpg)

**Comment by marmarek** [comment]
Check `/var/log/libvirt/libxl/libxl-driver.log` for details.

**Comment by 0xh0n3y** [comment]
How to fix this issue ?

**Comment by marmarek** [comment]
Please provide more details (as I asked in https://github.com/QubesOS/qubes-issues/issues/5336#issuecomment-533874656), so I can find how to help you.

**Comment by 0xh0n3y** [comment]
![20190922_181631](https://user-images.githubusercontent.com/23690578/65387474-5d675800-dd65-11e9-9195-d8f23723b7e3.jpg)
![20190922_181651](https://user-images.githubusercontent.com/23690578/65387475-5dffee80-dd65-11e9-8d84-13cbedd5b81c.jpg)

**Comment by marmarek** [comment]
Looks like you don't have IOMMU/VT-d in your hardware (or is disabled in BIOS). You should also got a warning about that during installation. See https://www.qubes-os.org/doc/system-requirements/#qubes-release-4x for details.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
