### ISSUE TITLE
Many parallel qrexec requests can make the source domain hang

### ISSUE THREAD

**Issue by HW42** [QubesOS/qubes-issues#5344]
**Qubes OS version**

4.0

**Affected component(s) or functionality**

qrexec

**Brief summary**

Under some circumstances (I think the trigger are multiple parallel qrexec connections opened quickly, but that's not sure, see below) any new qrexec connection to/from the source domain will hang.

When it happens I haven't noticed anything helpful in `dmesg`, `xl dmesg` or qrexec logs.

**To Reproduce**

I don't have found a reliable way to trigger this yet. The most reliable way to trigger it that I found so far is tunneling socks over qrexec and then use Firefox. Sometimes even the bunch of connections Firefox opens on startup are enough to trigger it. But sometimes it won't trigger at all.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

#5343

**Comment by HW42** [comment]
Running qrexec-client manually in dom0 it says `vchan connection timeout`.

**Comment by iamahuman** [comment]
Try specifing the `--buffer-size=` flag with a small value, or increasing the `limit` parameter of gntalloc.ko (not sure gntdev.ko is also relevant) That aside if you need to do a lot of qrexec in parallel you might also use some kind of multiplexing program.

This is probably not a DoS issue since it's neither Dom0 nor the target domain that hangs.
