### ISSUE TITLE
Fix HVM Frame Size

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#5350]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
HVM 

**Brief summary**
HVM Frame/Screen size is hitting the bottom of the main screen which is leading to the disappearance of the HVM taskbar.

**To Reproduce**
Install GNU/Linux OS as HVM (Windows HVM not effected)

**Expected behavior**
The frame size should be minimize to fit the entire HVM screen

**Actual behavior**
The frame size is too large to the level you cant see the taskbar of the HVM.

**Screenshots**

![kali](https://user-images.githubusercontent.com/11895339/65786815-012a7c80-e147-11e9-94ff-7aecd1ff2d83.png)

**Comment by marmarek** [comment]
If you like using a VM in fullscreen (without a frame, and covering host's task bar), you can do that from window's context menu (right click on the title bar). Alternatively, you can configure your HVM to use lower screen resolution, in which case the window will be smaller. In fact I suspect the HVM may use higher resolution than your host have, so even without title bar, it won't fit.
Using "just smaller frame", won't be enough, as based on your screenshot, majority of taken space is not because of HVM's title bar and frame, but from task bar of your dom0. And also, reducing window frame (title bar in practice) won't leave enough space for VM name, which is also important information.

Based on the above, I don't think there is any bug to be fixed, it's just configuration / usage of your HVM.

**Comment by TNTBOMBOM** [comment]
> If you like using a VM in fullscreen (without a frame, and covering host's task bar), you can do that from window's context menu (right click on the title bar)

The full screen option doesnt work actually when i press on it. 

> Alternatively, you can configure your HVM to use lower screen resolution, in which case the window will be smaller.

Yes this solved the issue, i didnt know changing internal screen size would effect the frame of the HVM from outside. this one solved it.

> majority of taken space is not because of HVM's title bar and frame, but from task bar of your dom0.

Thought that as well , but in fact it wasnt solved because the size of the frame is too big. 

Conclusion: 

default display resolution of the HVM after OS installation is: 1920x1080 or sometimes 1024x768 and both wont show the full size of the OS , so the solution is to switch the resolution to 800x600 and it will fit with you. 

Thx!
