### ISSUE TITLE
Show windows from all monitors. Xfce 

### ISSUE THREAD

**Issue by 240hz** [QubesOS/qubes-issues#5396]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Multiple monitor setups: Xfce window button: properties option

**Brief summary**
option "show windows from all monitors" resets after reboot. It is fixed in a newer Version of Xfce

**To Reproduce**
*Uncheck* - "show windows from all monitors" 
*reboot*

**Expected behavior**
window buttons should appear on the panel with the corresponding monitor.

**Actual behavior**
window buttons are combined from all monitor.

**Screenshots**
not in reach of system

**Additional context**
xxx

**Solutions you've tried**
checking and unchecking. fixes it.

*This is fixed on the version Fedora uses*

**Comment by andrewdavidwong** [comment]
Since this is an upstream Xfce bug that already been fixed in newer versions of Xfce used by newer versions of Fedora, this should automatically be fixed the next time dom0 is upgraded to Fedora 29 in Qubes 4.1. Therefore, I'm closing this as both `not our bug` and a `duplicate` of #4225. If anyone believes this is a mistake, please let me know, and I'll be happy to reopen this issue. Thank you.

**Comment by 240hz** [comment]
Thank You!
