### ISSUE TITLE
firefox: cannot exit fullscreen

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5424]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**

**Brief summary**

**To Reproduce**
1. on fedora-30
1. Open firefox
1. Right click the title and click `Fullscreen`
1. Right click the title and click `Exit Fullscreen Mode`

**Expected behavior**
Exit Fullscreen Mode

**Actual behavior**
cannot exit fullscreen

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by andrewdavidwong** [comment]
I can also reproduce this on Fedora 30. The `Exit Fullscreen Mode` menu option appears to be unresponsive (clicking on it does nothing; doesn't even dismiss the context menu).

By contrast, with Chromium, you can also make it go fullscreen by selecting the `Fullscreen` option from the Xfce title menu. However, in order to "undo" this, you have to double-left-click the top of the window. Right-clicking does nothing.

I'm not sure whether this is actually a Qubes bug.

**Comment by locriacyber** [comment]
Using r4.1 with arch linux, cannot reproduce here / works for me.

**Comment by marmarta** [comment]
Also works for me on fedora-35. Pretty sure it was a FF/Gnome? bug that got fixed at some point.
