### ISSUE TITLE
Qubes Settings menu item - move to top

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5447]
**The problem you're addressing (if any)**
If a VM has a substantial number of applications enabled, it can be difficult to locate the Qubes Settings menu option.

**Describe the solution you'd like**
Force Qubes Settings to the top of the list, instead of sorting it alphabetically.

**Where is the value to a user, and who might that user be?**
Users with many applications enabled in a particular VM.

**Describe alternatives you've considered**
Shell script to run locally on a regular basis that locates and renames the desktop files with a prefix symbol or number character that will cause it to sort to the top.

**Comment by andrewdavidwong** [comment]
The list is alphabetical, so it shouldn't be too hard to find. Can you say a bit more about why this should be the default for everyone rather than just personal preference?

**Comment by qwrd** [comment]
I'm going to upvote this.

It is something that has been bothering me as well. The qube settings shortcut for each domain/template/etc in the "start" menu will be placed somewhere in the lower middle of the app list. They will be mixed among other shortcuts which makes them rather cumbersome to locate in well populated menus. And since the VM menus will likely contain different number of apps, this will result in the shortcut being located in a different position for each menu.

Naturally, since the qube settings are part of the system settings rather than an app inside the qube, I do believe they should be exempt from the alphabetical order. They should instead be placed in a more prominent location that is consistent across all menus i.e. the first item in the menu.

**Comment by brendanhoar** [comment]
> The list is alphabetical, so it shouldn't be too hard to find. Can you say a bit more about why this should be the default for everyone rather than just personal preference?

Repeatedly, the result of installing QWT is a VM menu with dozens (scores?) of entries by default. How do I remove them? Well...I have to go dig out the Qubes Preferences...buried somewhere 2/3 or 3/4 down in a very long list.

**Comment by ninavizz** [comment]
I hate to be a pain after @marmarta  has already submitted the PR, but I'd like to recommend moving the flyout in addition to moving the `Qube settings` item to the top, so that the most naturally selectable item for each user is the first _app_ in that flyout—not the `Qube settings` item (which I agree should be separated from the crowd of app names).

While I trust that keeping the flyout in place would not bother technical users comfortable with using not-fully-finessed experiences, it'll help new and less technical users a lot.

![image](https://user-images.githubusercontent.com/8262612/70934694-501fd980-1ff3-11ea-9f76-e8eb963dca7b.png)

Longer-term, it'd be nice to introduce columns to the flyout—but that will take a lot of finesse to make behave usably, so I don't want to introduce with the open PR... but would like to toss out there for discussion, as a consideration for future enhancements to the App menu:

![image](https://user-images.githubusercontent.com/8262612/70934818-a8ef7200-1ff3-11ea-8e09-fe7f86aa09bd.png)

**Comment by marmarta** [comment]
I like the idea of columns, although that's probably a lot of work - I think XFCE menu does not support it by default

**Comment by brendanhoar** [comment]
On Mon, Dec 16, 2019 at 2:32 PM Marta Marczykowska-Górecka <
notifications@github.com> wrote:

> I like the idea of columns, although that's probably a lot of work - I
> think XFCE menu does not support it by default
>

Also keep in mind that the default Windows application names are often
*very* wide.

B

**Comment by mfc** [comment]
cross-referencing this ticket with: https://github.com/QubesOS/qubes-issues/issues/5520

**Comment by ninavizz** [comment]
I actually suspect that putting the Settings icon/function at _the bottom_ would be preferable to the top—as accessing apps is more likely to be a primary need. The core issue seems to be that it's annoying for the Settings function to be alphabetized with the apps, and that it should be anchored somewhere consistently.

**Comment by ninavizz** [comment]
Put updated art for the Qube Settings icons, in #5677

**Comment by brendanhoar** [comment]
> Longer-term, it'd be nice to introduce columns to the flyout (in addition to then moving the Settings item to the bottom)

I'll reiterate my argument for the Qubes Settings to be kept at the top and offset from application actions:

1. It is the one standard menu item across all VMs. Qubes-supplied template, Windows HVM, FreeBSD HVM, Android environment. It's going to be in the menu.
2. It would always be the same motion for all VMs and it is the only menu item guaranteed to do the exact same thing for all VMs.
3. In addition it is the one menu item *that does invoke a process inside the VM*. 
4. It is the standard "maintenance of the VM" action that you'll generally need at least once per VM. Some users are in and out of it daily, perhaps those with lower memory systems that reconfigure memory more often for different workstreams. 

Anyway...
Putting Qubes Settings at the bottom of a varying length list would be (to me) almost as "crazy making" as putting it in the list alphabetically. I'd still have to go look for it.

Brendan

**Comment by marmarta** [comment]
I agree with putting settings on top - while I'm not sure if "daily" is a good estimate of common usage, I think it's easier to locate on top, and easier to consistently ignore if you need something else.

**Comment by sptankard** [comment]
Was going to file a separate issue for this but found this one. I'd like to suggest changing the text of the menu entries (using sys-net as an example): 

From:    "sys-net: Qube Settings"
To:  "Qube Settings for sys-net..." or "Qube Settings: sys-net..."

My main reason for this is because this is the one menu entry that will not boot the qube or invoke a process inside it. 

Not sure of the impacts on translations/l10n.

One of the mockups by @ninavizz already included these labels as just "Qube Settings", which solves the semantic problem. But I actually think retaining the name of the qube in the label is useful for those using alternative menu picker software (such as i3 dmenu, or synapse launcher). Maybe also useful for screenreaders.

**Comment by andrewdavidwong** [comment]
@tabbyrobin, please open a separate issue for that. ([Every issue must be about a single, actionable thing.](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing))

(If your suggested renaming would result in the "Qube Settings" entry always being on top, then it would be appropriate to post it here as an suggested way of implementing this enhancement request, but I don't see how it could, since many VMs will have names starting with characters that get sorted before `Q`.)

**Comment by UndeadDevel** [comment]
It seems this issue should get a `affects Q4.1` label and autoclosed on Q4.1 EOL, since Q4.2 replaces the old app menu with a new one that either doesn't have "Qube Settings" entry (search section) or always has one at the top (domains section).
