### ISSUE TITLE
apt can't recognize the applications of snap

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5477]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**

**Brief summary**

**To Reproduce**
_Steps to reproduce the behavior:_
_0. create a Standalone VM
_1. use `snap` to install a package
_2. Click on `Refresh Applications`
_3. use `apt` to install a package
_4. the applications of snap disappeared

**Expected behavior**

**Actual behavior**

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/2766

**Comment by pwmarcz** [comment]
This seems to depend on `$XDG_DATA_DIRS` containing the right directory (`/var/lib/snapd/desktop`). This is true when executing `qubes.GetAppmenus` remotely (or from a terminal), but not from inside a post-install trigger (probably because  `sudo` censors the environment variables).

The right `$XDG_DATA_DIRS` is ensured by a script in `/etc/profile.d` put there by `snapd` package.

I don't know what would be a proper solution. I would propose to modify the `qubes.GetAppmenus` script like this:

```sh
# Workaround for Snap packages
if [ -e /etc/profile.d/apps-bin-path.sh ]; then
    source /etc/profile.d/apps-bin-path.sh
fi
```

Or even hardcode `/var/lib/snapd/desktop` there directly.

**Comment by marmarek** [comment]
There may be very similar problem with flatpak, so sourcing just one file probably isn't enough. Maybe the script should source them all? I _guess_ very similar applies to rpm/dnf on Fedora too, so that would handle it as well (hopefully).
