### ISSUE TITLE
Version Control Hosting Provider

### ISSUE THREAD

**Issue by trAa1bOJ** [QubesOS/qubes-issues#5535]
GitHub is a subsidiary of Microsoft. Microsoft's behavior as an organization is in direct contradiction of QubesOS's ideology in regards to privacy. I hereby propose to move to another provider. GitLab could be a decent option, and there are several other turnkey options out there that are not part of an evil corporation that fights against privacy rights.

**Comment by strugee** [comment]
See https://www.qubes-os.org/faq/#why-do-you-use-github.

**Comment by andrewdavidwong** [comment]
> GitHub is a subsidiary of Microsoft. Microsoft's behavior as an organization is in direct contradiction of QubesOS's ideology in regards to privacy. I hereby propose to move to another provider. GitLab could be a decent option, and there are several other turnkey options out there that are not part of an evil corporation that fights against privacy rights.

The [FAQ entry](https://www.qubes-os.org/faq/#why-do-you-use-github) @strugee linked addresses this. Specifically:

 - Since we distrust the infrastructure, the use of GitHub does not negatively affect the security or privacy of Qubes users or the Qubes OS Project.
 - Although we would like, in principle, to use a provider that is more closely aligned with the project, 
 much of our development workflow is currently set up to use GitHub. In practice, the time and effort required to make such a switch means that the costs would significantly outweigh the benefits. We'll deliver more value to our users by focusing on higher priority issues for the foreseeable future.

**Comment by marmarek** [comment]
what @andrewdavidwong said
