### ISSUE TITLE
qvm-create-windows-qube support thread

### ISSUE THREAD

**Issue by mfp20** [QubesOS/qubes-issues#5573]
**The problem you're addressing (if any)**
Not a Qubes problem itself. The qvm-create-windows-qube project doesn't have issue tracker and wiki, but some Qubes users are using it as de facto standard for windows installation. Despite being the wrong issue tracker, it would be useful to host this thread in order for us to be able to speak about this tool and its evolution in time. 

**Describe the solution you'd like**
Please admins leave the thread open until things change (ex: the qvm-create-windows-qube script goes incorporated into Qubes distro, or its author opens the issue tracker and wiki on its repo).

**Where is the value to a user, and who might that user be?**
Windows VM users using qvm-create-windows-qube to automate the install process, would have a way to report the current status of installing a virtualized copy of Windows on cube, expecially considering the obsolescence of the existing working solution (ie: to use Windows7).

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
The need of open this thread started in [issue 5289](https://github.com/QubesOS/qubes-issues/issues/5572#issuecomment-573663664). There are plenty docs scattered on github and google groups, but most of that information is obsolete: there's no clear path to get a working Windows10 virtualized environment on Qubes.

**Comment by mfp20** [comment]
@brendanhoar I've tried qvm-create-windows-qube in the past 2 days. Don't think anything changed, but please have a look yourself and report back: I've probably done something wrong. I've to say Windows7 was a good install procedure. Windows10 is a no-no-go.

**Comment by brendanhoar** [comment]
@mfp20 - are you sure elliot's repo doesn't have an issue tracker? I posted an issue there this morning... https://github.com/elliotkillick/qvm-create-windows-qube/issues

**Comment by andrewdavidwong** [comment]
I understand your desire to leave this open in order to receive support. However, there are three major problems with this issue:

1. qubes-issues is not a forum for providing user support. It's an issue tracker to support development work on Qubes. Support requests should go to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead.
2. qubes-issues is only for Qubes-specific issues.
3. qubes-issues isn't for compiling tips, workarounds, or other forms of documentation. It's to facilitate the developers' workflow in making changes to Qubes code.

It sounds like _some_ of the things you care about could be opened as proper issues in qubes-issues, and those would be left open.

**Comment by mfp20** [comment]
@brendanhoar 

Look at the issue tracker over there: the first entry is ~15hrs older than this issue here. Probably the author have seen our discussion here and opened the issue tracker there.

@andrewdavidwong 
Sorry for bothering here. The issue is solved, as there is an issue tracker there, now :)
