### ISSUE TITLE
Increase AppVM's default swap size

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5581]
**The problem you're addressing (if any)**

* Larger VMs need more than the standard 1G of swap
* only 1G of volatile is swap, others seem to be unused.

**Describe the solution you'd like**
Increase AppVM's default swap size

**Where is the value to a user, and who might that user be?**
Run programs that require plenty of memory

**Describe alternatives you've considered**

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/4880

**Comment by marmarek** [comment]
Generally swap is only meant to be used as a buffer until qmemman gives more memory. Relying on swap as main memory extension to actually being used will lead to very poor performance...
Maybe you need to increase maxmem instead?

**Comment by andrewdavidwong** [comment]
> Generally swap is only meant to be used as a buffer until qmemman gives more memory. Relying on swap as main memory extension to actually being used will lead to very poor performance...

It sounds like this is a "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by denisj44** [comment]
I used to work on an linux and my application was mmaping hugeeeeee files in memory and it was working like charm while enabling overcommit, But the catch was to have also a huge swap in order it to work. It was very efficient. As it seems also to be in qubes. Until I reach 10GB where it crash because I increased the swap to 10GB using the method from #4880. Yes for some computations swap is needed and can be enough efficient.

**Comment by iinta** [comment]
ok this is old thread, have problem with the swap still.

I have 32Gb memory and assigned 550 to vm at start max 4k was having with R4.2.0-rc4 few browser windows open, terminals and git at shell.  running 2 cores i7 11th generation.

Well suddenly my vm hang and had full cpu usage, memory full and swap 1gb also at tap. had to restart the vm. 
Greatnp  increased the starting memory and max memory resumed what i was doing, task manager show me cpu under 50pct and only 1/3 of the memory in use, and FFS for unknown treason the swap partition get filled over 50pct. 

So the bug here firefox might leak directly to swap? cos the swap filling stopped when closed www.page or that is my assumption dunno the tech side. 
had the same sudden hang problem with other VM earlier running almost same few browsers with tabs.

**Comment by iinta** [comment]
indeed i'm not seeing help, i reported fault from my personal perspective,
to developers who understand system. cos same looking issue was still not
corrected, after all these years. i do not ask community help. i report
ERROR, cant you see difference?! peon time was long ago, bug report from
user not only dev report errors and bugs. here at suomi finland your
chinese dont seem to understand team work an error reporting fixing,
security hole against usersand privacy maybe not just  this error but many
other dos attacks example. thats why users can communicate and report bugs
my quess is at russia and germany no one report errors east europe stays
broken no one cares bus faulty pipes, your mentality  avi wonka putous
realise no one asked your opinion regarding personal error report with
the tool assembled to this os community users cant fix such errors and bugs
causing all users problems. i was not asking how to do something like forum
discussion coffee negltistion like saddasm hussein times at south italy.
haters like like you seem to comment every issue which is not their
problem. stop hsrrarsment devs know whats is theis responbility realice if
not fixablee they just close bug report, your kind of clown comment every
besser wischerissue acting like hsnging bar ty fuvk laws gucking terrorist
human harasment look www.wct.org terrorist act against civilian populagion,
enemy lf  free western country people. sick bastard from hell.  d0nt you
understand clear english?! it sounds like i am terrorrist hater asking
firemen community helps from twin towers... realise what you write? you
dont understand english translator user.. you anttisocial group dont do
user support or  OS development you wow to handle csr at east india is not
western way to handle user and customer issues firemen exting cuish fire
and ems not fo computer support or development. do you really want me call
your terrorist company number 000 official customer emergency support how
to install nt.

10th year of harashment of me at my home in finland paid isp internet and
no fear terrorist act sick government criminals year 2023 im
not joinin your street groups human harasment terrorism activist
recruitment dont accept truth  im not joining your #maan alainen armeija#
ranks.
nt effi finland kettu tytöt activists civilian harasment vandal law hater
terrorist civilian attack tallin manual 2.0 cyber criminals and internet
terrorists  community service cant do official support work human customer
support, harasment community support im not asking how to faq jarg0n stop
harashment in suomi finland!  im not not asking your indian opinion we are
western country not phone center customers.

**Comment by iinta** [comment]
sorry for my explosion but you kind of telling opinion witout asking my
home country and services are now like hitlers state, center telling her
one  witout asking on every civilian front same illegal censorship issue,
hitlers state first steps to slave human civilian population . freedom of
privacy and speech every internet application same gov criminals harasment
cos war and terrorist basement group is not interesting for i. what you
watch dont understand illegal civilian monitoring, crimes against humanity
-->terrorism. viranomaisten mielivaltaa pol. eu european union. laws apply
here at finland suomi perkele.
have a nice year
