### ISSUE TITLE
archlinux: kernel inside VM not working

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5584]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
archlinux

**Brief summary**
kernel inside VM not working

**To Reproduce**
_1. `sudo pacman -S linux`
_2. Mode: `HVM` kernel: `(none)`
_3. start VM

**Actual behavior**

```
Cannot connect to qrexec agent for 60 seconds
```

**Comment by icequbes1** [comment]
@zaoqi Did you install GRUB (or some other bootloader) to /dev/xvda?

I had to install grub, linux, generate the grub config and install grub to /dev/xvda before using in-VM kernel.

I also had to increase qrexec_timeout since there was some issue bringing up /dev/xvdc1 (swap).

There was also some issue with GUI - I could run a gnome-terminal but did not see any output, same with other X windows - black screen. Not an issue when using dom0-provided kernel. Using `qvm-run -p` or `qvm-console-dispvm` is the only way to do things.

**Comment by DemiMarie** [comment]
@icequbes1 do you have the `u2mfn` module loaded?

**Comment by icequbes1** [comment]
Oops, you are right; I did not RTFM[1]; just needed to install qubes-kernel-vm-support and GUI windows are good in HVM, in-VM kernel (5.9.14).

[1]: https://www.qubes-os.org/doc/managing-vm-kernel/

**Comment by DemiMarie** [comment]
`qubes-kernel-vm-support` should be part of the default Arch template.  If it is not, that’s a separate bug.

**Comment by icequbes1** [comment]
If qubes-kernel-vm-support is not expected to be manually installed by a user, I agree the bug is that Arch template doesn't include include it.

Based on builder-rpm and builder-debian, non-minimal templates install qubes-kernel-vm-support, kernel package, and grub during 04_install_qubes.sh. Arch does not, so perhaps that is the resolution to this issue (since I wrongly assumed users were to manually perform these actions).

**Comment by DemiMarie** [comment]
Looks like there is another problem: `/etc/default/grub` doesn’t source `/etc/default/grub.qubes`.

**Comment by icequbes1** [comment]
There were a couple of things that were still needed but I have not had the time to test to get a PR going: 

- [core-agent-linux](https://github.com/QubesOS/qubes-core-agent-linux/compare/master...icequbes1:in-vm-kernel) needed to `install` /etc/default/grub.qubes

- [linux-utils](https://github.com/QubesOS/qubes-linux-utils/compare/master...icequbes1:in-vm-kernel) needed to install /etc/default/grub.qubes-vm-support to disable xen_scrub_pages kernel option (which then gets re-enabled in the initramfs/initcpio). My branch cheats because ideally the flag would get set during mkinitcpio (but probably require a libalpm hook).

- [builder-archlinux](https://github.com/QubesOS/qubes-builder-archlinux/compare/master...icequbes1:in-vm-kernel) to make in-vm kernel work as part of the template build.

This was to match what I saw in the Debian and Fedora templates - vm-support is automatically included unless the template is a minimal - which brings in kernel/headers/grub/mkinitcpio/linux-firmware.

Have not had the time/ability to test so hopefully this saves some effort if you are trying to get this working.
