### ISSUE TITLE
Progress bar stop moving in initial setip

### ISSUE THREAD

**Issue by marillindie** [QubesOS/qubes-issues#5598]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._

R4.0.3

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._

Initial Setup

**Brief summary**
_A clear and concise summary of the bug._

The configuration progress bar stopped moving.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to '...'_
_2. Click on '....'_
_3. Scroll down to '....'_
_4. See error_

(I don't know, as it just appears after installation)

**Expected behavior**
_A clear and concise description of what you expected to happen._

The progress bar should be moving while the process of configuration.

**Actual behavior**
_What actually happened (instead of what you expected to happen)._

The Qubes OS Setup windows shows up and after a while the progress bar stop moving. However, according to the text underneath, the configuration goes on as expected.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

None. Since it doesn't really matter the process of installation, I just forgot about it and the installation went on successfully.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by 92VV3M42d3v8** [comment]
What is actual step of Progress bar when it stopped. Was it "Setting up Networking"

**Comment by sjvudp** [comment]
Installing on an USB stick, I can confirm this: I think it was towards the end of installing the VM configurations. Being an "experienced" Linux user, I ran "top", "watch cat /proc/meminfo" and "journalctl -b -f" in another virtual console, just to see that something is happening. (I'd wish there were "iftop" and "iotop" available"). In my case there were significant read stalls due to dirty buffers occupying all the available buffer space it seemed. (The latter is typical for Linux with rather large RAM and slow disk writes)

**Comment by eribabu** [comment]
Hello,

I am experiencing this issue also.
**Release**: Qubes R4.0
**OS Media**: USB 3.1 Kingston Flash Drive
**Affected Components**: 
- Initial Setup > Finish Configuration > Window Title "[Dom0] Qubes OS Setup"

**Steps to Reproduce:**
1. Use default qubes setup, click "FINISH CONFIGURATION"
2. Wait for progress bar to hang
3. Progress bar hangs at "Configuring TemplateVM debian-10"

**Frequency:**
Always. For my build, it consistently hangs on "Configuring TemplateVM devian-10"

I do not know how to access logs to see if the configuration of qubes is still in progress, and since this is using USB as my OS media, it is going to take much longer than 15 minutes. Waited 20 minutes so far; will update thread if it proceeds past this point.

**Comment by eribabu** [comment]
> I do not know how to access logs to see if the configuration of qubes is still in progress, and since this is using USB as my OS media, it is going to take much longer than 15 minutes. Waited 20 minutes so far; will update thread if it proceeds past this point.

**Update:** Out of morbid curiosity, I waited for 5 hours and I noticed it had moved on to "Configuring TemplateVM whonix-gw-15", which means activity _is_ going on in the background. Indeed, it seems the bug is specifically with the progress bar.

**Comment by sjvudp** [comment]
>>> eribabu <notifications@github.com> schrieb am 05.03.2020 um 02:10 in Nachricht
<8608_1583370648_5E605198_8608_5162_1_QubesOS/qubes-issues/issues/5598/594975068
github.com>:
>>  I do not know how to access logs to see if the configuration of qubes is 
> still in progress, and since this is using USB as my OS media, it is going to 
> take much longer than 15 minutes. Waited 20 minutes so far; will update 
> thread if it proceeds past this point.
> 
> **Update:** Out of morbid curiosity, I waited for 5 hours and I noticed it 
> had moved on to "Configuring TemplateVM whonix-gw-15", which means activity 
> _is_ going on in the background. Indeed, it seems the bug is specifically 
> with the progress bar.

Seems to be: "no progress, no progress bar" ;-)

More seriously: Should the progress bar move towards an end when something is going on, or should it move all the time until something is finished? In the latter case it would be a "busy bar" IMHO.

Most progress bars there days seem to be "dummy bars".

Regsrds,
Ulrich

**Comment by eribabu** [comment]
> More seriously: Should the progress bar move towards an end when something is going on, or should it move all the time until something is finished? In the latter case it would be a "busy bar" IMHO.

Yes - an indication that the initial setup is still continuing and is otherwise not hung. What I would like to see, as an end-user, is a view of the initial setup logs. This would be helpful for individuals troubleshooting installation problems (which I am still working through, because I'm not sure how to get console access during initial setup), and requesting assistance when they need it. If we're really getting fancy, a dump of key system characteristics that might be useful for troubleshooting when the initial setup process hangs.
