### ISSUE TITLE
qvm-kill --all gives final state of all named VMs, no output for dispxxxx VMs

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5607]
**Qubes OS version**
R4.0.x updated to current-testing today.

**Affected component(s) or functionality**
qvm-kill

**Brief summary**
qvm-kill --all gives final state of all named VMs. However, if disposable VMs were killed, they are not noted in the output.

**To Reproduce**
1. Start a disposable VM (name format begins with 'disp')
2. Start other VMs.
3. qvm-kill --all

**Expected behavior**
Output includes the name of the disposable VM

**Actual behavior**
Only state of named VMs is listed.

**Comment by marmarek** [comment]
@pwmarcz may be something for you :)

**Comment by pwmarcz** [comment]
`qvm-kill --all` gives something like this for me:

```
Domain is powered off: 'anon-whonix'
Domain is powered off: 'debian-10'
Domain is powered off: 'default-mgmt-dvm'
```

This is not a list of all the VMs, but error messages for VMs that were already off. The command, by convention, is silent if everything succeeded.

I can change the message so that it's more clear, e.g. add a prefix like "Failed to kill 'vm_name': ..."

**Comment by marmarek** [comment]
For this specific message it feels like it should be not shown at all. AFAIR it's separate exception type.
