### ISSUE TITLE
Expiring qrexec_timeout shouldn't kill the VM

### ISSUE THREAD

**Issue by sdaro** [QubesOS/qubes-issues#5625]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Installation process
Network
systemVMs
AppVMs

**Brief summary**
Expiring qrexec_timeout is causing unusable (system)VMs, because it kills AppVMs during initialization.
This happened on slow USB sticks and busy systems.
This happened to me during installation as well as during daily OS usage while creating new domains.
The installation process is interrupting and shows an error message. After clicking "OK" the user will see the login window.
After logon the system looks initialized, but it isn't. The network isn't working correctly and the systemVMs won't start any application.
A new user of Qubes OS that want to try Qubes OS is totally overwhelmed with this situation because everything seems OK but the system isn't configured correctly.
The issues #4419 and #3533 could be caused by this VM killing.

**To Reproduce**
_1. Install Qubes OS on a slow USB stick.
_2. After first reboot during the initialization process: experience the error: "Cannot connect to qrexec agent for 60 seconds, see /var/log/xen/console/guest-sys-net.log for details"

**Expected behavior**
An unexpected long running startup shouldn't cause a kill of the VM.

**Actual behavior**
The expiring qrexec_timeout is killing the VM.
This results in
* an unfinished installation process
* partially configured systemVMs
* defect AppVMs

**Screenshots**
-

**Additional context**
-

**Solutions you've tried**
After the installation, before the first boot I have altered the installation script, see: [hotfix](https://github.com/sdaro/qubes-anaconda-addon/commit/cdd7461b54f3cb07c3e2a65d5826fb5bc9572224#diff-97295458a775914e619378aede0b2447)
After I changed the qrexec_timeout to 600 seconds everything works fine.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#4419
#3533

**Comment by marmarek** [comment]
qrexec_timeout in practice should be named "startup timeout". And on  startup timeout VM should be killed (maybe unless debug is enabled for this VM) as otherwise many operations will wait for that VM, possibly indefinitely. If that happens during system startup, user won't be even able to login, as no login screen is available yet.

I think the problem is different:
* too low default timeout on some systems (especially on USB): here we could apply some heuristic to make it higher on slow systems - maybe anaconda-addon should do that?
* VM killed in the middle of startup may lead to corrupted state: our storage implementation explicitly keeps vm disks state from before VM start - maybe in case of failed startup, it should revert to that state, instead of committing (possibly broken) state from the failed start?

**Comment by sdaro** [comment]
In my opinion a heuristic in anaconda would only adress the state at installation time.
When a system is very powerful but busy in some situation, this will happen again. It getting more complex when you have different storages with different performance. I don't know if a heuristic is a solution here.

What's the reason for not asking the user? I think the user's intuition is a better heuristic 😀

With your second point I'm totally agree. It can happen that you run into the same problem over and over again, but you always have an consistent state.

**Comment by rustybird** [comment]
> VM killed in the middle of startup may lead to corrupted state: our storage implementation explicitly keeps vm disks state from before VM start - maybe in case of failed startup, it should revert to that state, instead of committing (possibly broken) state from the failed start?

That too could lead to data loss, e.g. if an early running service like fetchmail successfully moves some data from a remote server to the VM, but then the VM is killed. Which seems worse than the status quo, where only _incorrectly_ written software inside the VM (not using fsync properly, buggy filesystem etc.) can lose data.

**Comment by rustybird** [comment]
A `qvm-volume` command to manually revert (or manually commit) a `save_on_stop` volume of a halted VM would be neat though.

**Comment by marmarek** [comment]
There is already `qvm-volume revert`, but this is useful only if you set `revisions_to_keep` to something > 0.

**Comment by marmarek** [comment]
cc @marmarta

**Comment by rustybird** [comment]
I wonder if it would be possible (and a good idea) to not call `stop()` on the storage at all if the VM was killed instead of shut down. This would unify the storage state of (1) VMs that crashed because they were killed with that of (2) VMs that crashed because the whole host crashed.

`qvm-volume` could then meaningfully show that state, and offer to "revert to before start" or commit (after a minor modification to storage driver API, e.g. giving `stop()` a `revert` parameter defaulting to `False`).

**Comment by xaki23** [comment]
> A `qvm-volume` command to manually "revert to before last start" (or to manually commit) a `save_on_stop` volume of a killed VM would be neat though.

commit verb would really be useful, in particular with options tol --all and --ignore-revs-to-keep. 
(with those two, i would probably end up having it run on every dom0 boot...)

**Comment by sdaro** [comment]
Just for clarification:
The intention for filing this issue was not to develop a treatment for the consequences of an accident.
The intention was to prevent the occurrence of the accident itself. 😃

**Comment by brendanhoar** [comment]
For this use of qrexec-timeout (auto-start VMs & manually started VMs) perhaps best to ask the user if they want to shut down or qvm-start-gui instead? Inevitably I end up watching VMs get killed, manually setting qrexec-timeout to 3600, running qvm-start-gui only to find a windows VM stuck in the boot menu. And leaving qrexec-timeout at that value for months until it causes some other side effect and then I groan when I finally figure that out.

How to determine “internal” use of qrexec-timeout vs. “user-facing” use...is left to the developers, whom I must have surely annoyed by this point. :)
