### ISSUE TITLE
manual partitioning (custom installation): enhance documentation

### ISSUE THREAD

**Issue by sjvudp** [QubesOS/qubes-issues#5632]
**The problem you're addressing (if any)**
There are suprises (things not explained) after following the custom installtion procedure.
It is not explained why the swap should not use the thin pool, and it's not explained how the thin pool will be used.

In "**5. Create LVM volumes:**" the root filesystem will be as large as the thin pool `qubes_dom0/pool00`. At that moment that seems reasonable, while the user might wonder why there is a thin pool at all.

When using the system, the user might find out that all the VMs and template VMs allocate thin-provisioned logical volumes from the same pool (a fact that should be mentioned in the setup docs).
This means that the thin pool will be significantly over-provisioned, and depending on it's actual size, the system may freeze when the pool's space is exhausted.

Knowing that it seems a dubious advice to allocate the root filesystem as big as the thin pool. It should have an upper bound if `pool00` is large.

**Describe the solution you'd like**
Actually I did not use thin pools a lot before, but maybe root (/) should be fully provisioned with a reasonable size, while additional VMs use a thin pool.
It's also thinkable that essential VMs and the root filesystem uses one thin pool, while non-essential VMs use another thin pool. That way growing non-essential VMs could not bring essential VMs to a halt.

**Where is the value to a user, and who might that user be?**
Reliability when allocating more data. A "safe" feeling. A better understanding of the mechanisms involved.

**Describe alternatives you've considered**
Re-installing with a different layout.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.hope.net/schedule.html#-qubes-os-the-operating-system-that-can-protect-you-even-if-you-get-hacked-
https://www.qubes-os.org/doc/custom-install/

**Comment by marmarek** [comment]
> Knowing that it seems a dubious advice to allocate the root filesystem as big as the thin pool. It should have an upper bound if `pool00` is large.

This alone is something I've tried convince the installer multiple times. But unfortunately the installer we use (anaconda, from Fedora) doesn't give any flexibility to set pool size - it sets it as large as volumes in it, and this is why we create root filesystem that big.

As for root filesystem size, it is also tricky point - normally about 10-20G should be enough. But in some cases it is used as a transient space for large data - specifically during template installation and restoring backups. Those operations alone may need 10-20G of _free_ space on root filesystem.
Allocating ~40G root filesystem statically would mean this space (most of the time unused) would be unavailable to VMs. Both of the tasks could use less space (#2534 for templates, #4791 for backups) - when done, indeed allocating static space for root filesystem will be a better thing to do. But until then, wasting ~20G is not something I want to do in the default configuration, especially as we recommend fast SSD/NVMe which tends to be smaller for the same price tag.

**Comment by andrewdavidwong** [comment]
The "custom installation" page was severely out-of-date and had remained so for an extended period of time, with no one able or willing to update it. The outdated content has proven misleading or unhelpful to many users. Since we have nothing with which to replace the outdated content, removing it seems like the lesser of two evils. (Note that the content is still available via Git history and other archives for historical reasons and for any users still on EOL releases.) If anyone is able and willing to contribute the relevant knowledge and/or text for customizing the installation of a supported Qubes release, we can bring this page back in the future. Since the page no longer exists, this issue is no longer applicable and is therefore being closed as "won't do."

(In addition, it sounds like this issue may have rested on a misunderstanding, as it sounds like the page may have already been out-of-date at the time this issue was opened.)
