### ISSUE TITLE
Custom install doc: /etc/crypttab contains wrong UUID after re-install

### ISSUE THREAD

**Issue by sjvudp** [QubesOS/qubes-issues#5637]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
Boot: It fails.

**Brief summary**
I reinstalled Qubes OS using custom partitions as documented. The new install was unable to boot, not finding the unencrypted PV. First I thought it was due to the fact that initrd has no `cryptsetup` , but I was wrong...

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Reinstall with custom partitioning as described.
_2. At the dialog where to select the disk to use, I escaped to the TTY and did the setup.
_3. Back at the dialog I continued without any problem. **Note:** The docs should have mentioned that for custom partitions, you should uncheck "Encrypt my data", becasue if you leave it checked, you are asked to enter a password twice (thinking it's the password for your custom LUKS), and then a third time for your actual pre-existing LUKS device...

**Expected behavior**
Qubes OS boots successfully.

**Actual behavior**
Boot takes _very_ long, and never asks for a password to open the LUKS device.
Systemd complains that the unencrypted device could not be found.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
First I rebuilt the initrd, adding cryptsetupt to it. I was able to open the device manually, but that did not help to get out from emergency mode.

At some point I noticed that the UUID reported by `blockid` was different from the one in /etc/crypttab.
So I commented the existing entry and added another one with the actual UUID of my LUKS device, rebuildiing initrd. Then the LUKS device was found and a password was asked for.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/installation-guide/
https://www.qubes-os.org/doc/custom-install/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/2835

**Comment by unman** [comment]
@sjvudp I'm trying to get clear about what you did (and didn't do) here.
> The docs should have mentioned that for custom partitions, you should uncheck "Encrypt my data"

The instructions on the "custom install" page **clearly state** that you should do this. Did you miss that?
Did you leave that option checked before encountering the problem you are reporting here? Or did you encounter this problem after restarting installation and *unchecking* that option.

Did you take the *optional* step in the instructions of wiping the disk?

**Comment by andrewdavidwong** [comment]
The "custom installation" page was severely out-of-date and had remained so for an extended period of time, with no one able or willing to update it. The outdated content has proven misleading or unhelpful to many users. Since we have nothing with which to replace the outdated content, removing it seems like the lesser of two evils. (Note that the content is still available via Git history and other archives for historical reasons and for any users still on EOL releases.) If anyone is able and willing to contribute the relevant knowledge and/or text for customizing the installation of a supported Qubes release, we can bring this page back in the future. Since the page no longer exists, this issue is no longer applicable and is therefore being closed as "won't fix."

(In addition, this issue seems to be specific to Qubes 4.0, which has been EOL for a long time now.)

**Comment by sjvudp** [comment]
Of course deleting any doc is faster than updating it, but to the user that kind of "solution" isn't really helpful.
