### ISSUE TITLE
4.0.3 Torrent File Not Correctly Formatted

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#5640]
**Qubes OS version**

4.0.3

**Affected component(s) or functionality**

Torrent download file

**Brief summary**

_1. Go to https://www.qubes-os.org/downloads/
_2. Download torrent file https://mirrors.edge.kernel.org/qubes/iso/Qubes-R4.0.3-x86_64.torrent
_3. Type `ctorrent Qubes-R4.0.3-x86_64.torrent`
_4. See error:

```
Listening on 0.0.0.0:2706
error, invalid tracker url format!
error, tracker setup failed.
```

It is possible I am just doing something really stupid.  But torrent file looks like a binary file when viewed with `less`

**Comment by xaki23** [comment]
it is normal for a torrent to be "mostly binary", they always start with some (bencoded) text though.
this torrent file looks just fine.
the problem is most likely you are using some 10-15 year old piece of client that doesn't support udp trackers at all.

any of the clients here should work: https://en.wikipedia.org/wiki/UDP_tracker

**Comment by straussmaus** [comment]
@xaki23 

> the problem is most likely you are using some 10-15 year old piece of client that doesn't support udp trackers at all.

Two replies:

1 - Yes, ctorrent could not handle it but rtorrent can.

2 - I still can not download the file using torrent because I am using whonix which does not support UDP.

@andrewdavidwong Should I create a new Issue as an Infrastructure Feature request that the Qubes .iso torrent should be usable over whonix?  If you think this is correct please close the issue.

**Comment by xaki23** [comment]
torrenting over tor will never work properly, despite the accidental name match.
even if you have a tcp-using tracker, if you put only torified clients on that torrent, they will never be able to talk to each other, at all.
the whole dht/kademlia/magnet parts of modern bittorrent also are not going to work.
this is really worse than "clients behind NAT" since not even any nat-punch strategies are going to work.

the most useful approach might be to add a note to the download page that tor-users should use direct download instead of torrent.

**Comment by straussmaus** [comment]
So you are saying I was correct when I wrote "It is possible I am just doing something really stupid."  I'm glad you agree with me.

Yes I forgot that torrent uses UDP (and I know tor != torrent) so I am closing this issue.

> the most useful approach might be to add a note to the download page that tor-users should use direct download instead of torrent.

I agree.  But you could also remind people that using a torrent offers some privacy by itself so Tor might not be necessary depending on circumstances.
