### ISSUE TITLE
Remove redundant "needs restarting" icons in Qube Manager

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#5661]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
Qube Manager

**Brief summary**
Non-named dispVMs get a 'needs restarting' icon. It's pointless for them, as they cannot exactly be restarted.

related to #5657

**Comment by hexagonrecursion** [comment]
>  they cannot exactly be restarted.

But you can manually a dispVM shut them down. My understanding is that the "needs restarting" icon is supposed to inform the user that they are running outdated software and should restart **or shut down** the affected qubes.

**Comment by andrewdavidwong** [comment]
> > they cannot exactly be restarted.
> 
> But you can manually a dispVM shut them down. My understanding is that the "needs restarting" icon is supposed to inform the user that they are running outdated software and should restart **or shut down** the affected qubes.

I see your point. If a user keeps a DisposableVM running for a long time, it may be running old software that has since received security updates in the underlying templates. Perhaps the "needs restarting" icon should be replaced with a "running outdated software" icon (whatever that might look like) rather than just removed entirely.

@marmarek, @marmarta: What do you think?
