### ISSUE TITLE
Qubes os USB keyboard dead

### ISSUE THREAD

**Issue by chaywoo** [QubesOS/qubes-issues#5734]
Hi! I am writing this from my phone because I am locked out of qubes-OS.. Does anybody know if there are any command lines I can enter in the grub command prompt to enable USB keyboard? I have a ton of paper work to print. Yesterday I was trying to install a USB printer but I decided to make it a network printer since I was having a time with usb.. I installed a brother printer driver in the template vm as there qubes directions suggested. After trying to adjust the properties of the printer the properties window froze, I restarted the qube then I couldn't bring up the printer properties window, then I rebooted the computer and the usb keyboard shuts off right after the grub boot menu and before the disk password. Im completely locked out. LoL
Surely there must be something I can do. I hope. I really appreciate any suggestions thank you sincerely.. - Chris 

### Affected component(s) or functionality:

---

### General notes:

---

**Comment by xaki23** [comment]
remove the hide_all_usb part from the grub/xen/kernel commandline.

for details see https://www.qubes-os.org/doc/usb-qubes/

**Comment by chaywoo** [comment]
Thanks for the reply. Unless im missing something everything on the page seems to suggest actions taken in dom0.. I am unable to find any reference to  
Grub/zen/kernal command line. I've tried some of the command lines on the page but they don't work in grub. It sounds like I need to edit the contents of a file from within grub, but i don't know how to do that. Just a little green but I like qubes a lot. Thanks for taking a moment to give me something to try I really appreciate it. 
- Chris

**Comment by xaki23** [comment]
just edit the grub/xen/kernel commandline on-the-fly (from inside grub) to remove the mentioned parameter.
or fire up any live system, mount /boot, and edit the grub config file there.

you still will have to work through the linked qubes-usb docs for a permanent fix ... after you trick it into booting.
(and i would recommend disabling autostart for sys-usb, that makes it much easier to recover from breaking sys-usb if yout only kbd is usb)

**Comment by chaywoo** [comment]
Awesome thanks so much. I attempted to edit on the fly...  edit grub/zen/kernel and grub said 'can't find command edit' so I tried again with a capital Edit and EDIT.. is there a link that might explain how one would edit on the fly in grub? I have a couple of windows computers, but I remote into them from the qubes master computer. Thank's so 
much
- Chris

**Comment by xaki23** [comment]
(i dont have any computer using grub here, so i am flying blind)
afair it is just going to the menu entry you want to start, and then hitting "e" instead of enter. 
there should be a hint at the bottom of the screen/menu about this.

**Comment by chaywoo** [comment]
Progress! Now I can make it to the log in screen, keyboard seems to work, caps lock light etc, but no characters are making to the login in password entry box. Sigh, well I must head out for a few hours will try again when I get back, thanks so much for the great tips..
- Chris

**Comment by xaki23** [comment]
most likely you need to disable sys-usb autostart.

this means booting some linux off usb (any fedora live version should do), 
mounting dom0 root (open luks, lvm, pick right device, mount it), 
and removing some file (symlink) like /etc/systemd/system/multi-user.target.wants/qubes-vm@sys-usb.service

given how much handholding a simple args edit required, it may be more realistic if you just reinstall and restore from backup.
good luck.

**Comment by chaywoo** [comment]
I get it, thanks I really appreciate all the great pointers very much..
- Chris

**Comment by xaki23** [comment]
actualy reading my own post above again, there may be a different/easier way.
since it is the multi-user.target that autostarts the vm, booting dom0 into the systemd equiv of single-user mode should work (instead of the live-boot-and-manual-mounting part).
some quick googling ... https://docs.fedoraproject.org/en-US/Fedora/18/html/Installation_Guide/s1-boot-init-shutdown-targets.html

so perhaps just adding systemd.unit=rescue.target to the grub/xen/kernel commandline (and removing the hide-all-usb again) results in a barely-working-enough dom0 to log in.

then remove /etc/systemd/system/multi-user.target.wants/qubes-vm@sys-usb.service and perhaps try to run qubesctl for the usb-keyboard target (which should permanently fix up your grub config for the hide-all-usb part).

if you get permission-denied even as root/sudo, you might have to remount root+boot rw ... mount -o remount,rw /

this issue tracker is not a good format for handson support like this, perhaps the qubes-users mailinglist or #qubes on irc.freenode.net are better. (in either place, make sure to send a link to this issue)

**Comment by andrewdavidwong** [comment]
> this issue tracker is not a good format for handson support like this, perhaps the qubes-users mailinglist or #qubes on irc.freenode.net are better. (in either place, make sure to send a link to this issue)

Indeed, based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. However, we understand that you may have limited computing capabilities due to being locked out of your Qubes machine. If possible, we ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by chaywoo** [comment]
Thanks Andrew! You are exactly correct I was stuck on my phone! Also to xaki23, you gave me enough information to make it happen! It works! I could NOT have EVER figured this out, without your help, thank you very very much.. I was locked out by the root user being locked.. I searched and found a way to change root user password. I tried to make it blank, but that didnt work, so I changed the password using the rd.break enforce=0 or something like that and changed the password to root, even though it said is was a bad password, then the next boot I wasnt locked out and I was in the root@dom0, then I learned that I needed to use "RM" for deleting the file you said to delete, and now all is well! Everything works like nothing happened! Now all I have to do is move this post to the right place.. Thanks again! What would I be doing right now without that information? I think I would be having a melt down! LoL Thanks so much!
