### ISSUE TITLE
Persistent USB device attachment does not work after dom0 reboot

### ISSUE THREAD

**Issue by greenrd** [QubesOS/qubes-issues#5736]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
qvm-usb

**Brief summary**
The `qvm-usb` `-p` option to attach a device to a VM persistently worked initially, but after rebooting dom0, the VM failed to start because Qubes thought the device didn't exist. However, the device did exist.

**To Reproduce**

1. Enable USBVM and USB keyboard: sudo qubesctl state.sls qvm.usb-keyboard
2. Create AppVM, let's call it "audio"
3. Start AppVM
4. Plug in USB device, e.g. USB webcam
5. Attach USB device to new AppVM, e.g. `qvm-usb attach -p audio sys-usb:2-4`
6. Shut down dom0
7. Boot into Windows on host machine
8. Reboot, boot into Qubes OS
7. Observe that USB device is now numbered `sys-usb:1-4`
8. Try to start AppVM

**Expected behavior**
AppVM should start with USB device attached

**Actual behavior**
AppVM fails to start with error saying USB device does not exist. It does exist, it just has a different number. (I think the device should be identified by its USB vendor and product ID, using the device number only to disambiguate if necessary, in case you have multiple devices with the same vendor and product ID.)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/usb-devices/
https://www.qubes-os.org/doc/device-handling/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/4780

**Comment by greenrd** [comment]
Workaround to allow VM to start, for the record: `qvm-usb detach audio sys-usb:2-4`

**Comment by promovicz** [comment]
Can confirm this bug. Same issue also applies to block devices. It happens with all persistent devices that have changing names.

The real issue with this is three-fold:

  * qvm-usb and other tools should display persistent devices that aren't present. They currently don't.
  * Domains shouldn't fail to start when dynamic devices such as USB are missing.
  * Qubes shouldn't use the device names it currently uses. Neither USB bus numbers nor the device minor used for block devices are stable identifiers. There probably needs to be some device identity management.

Same problem also occurs if you try to persistently attach a block devices, such as an LVM logical volume on another disk. This is highly annoying because it limits me to just the Qubes-managed volumes.

**Comment by promovicz** [comment]
Workaround that does it for me:

Install an RPC hook script on the dom0 that identifies and then attaches the right devices to the calling VM.

Something like this could also be part of a final solution by being integrated with the correct management interfaces, but I couldn't find the time yet to determine how that would work exactly.

**Comment by promovicz** [comment]
Observation about device identifiers:

The "description" of devices seems to be a more useful identifier than the "BACKEND:DEVID" tuple.

In case of LVM volumes it will be the VG and LV name, which is stable and useful. Not sure about straight LUKS.

For USB devices this works brilliantly if the device has a serial number, less so if not but possibly acceptable.

**Comment by james-callahan** [comment]
I've just had the same issue in qubes 4.1
