### ISSUE TITLE
Win10 VM won't start properly after installing qubes windows tools

### ISSUE THREAD

**Issue by lucaszanella** [QubesOS/qubes-issues#5739]
**Qubes OS version**
4.0.1

**Affected component(s) or functionality**
StandaloneVM start

**Brief summary**
After installing qubes-windows-tools on a Windows 10 VM, I used it for a while, everything worked. Now when I go to launch it again, instead of having simply "qubes settings" and "start" like before, I have all the windows apps to start. If I click on one of them, the VM starts but does not show any screen, it just shows up as started. There's also not a "start" option anymore

**To Reproduce**
_Steps to reproduce the behavior:_
Install qubes-windows-tools
shutdown
try to start vm again

**Comment by 0rb677** [comment]
same problem. Qubes 4.0.3
win10 eval iso
https://github.com/elliotkillick/qvm-create-windows-qube

**Comment by lucaszanella** [comment]
I did not use qvm-create-windows-qube, so it looks like it's totally qubes specific

**Comment by lucaszanella** [comment]
@0rb677 somebody said to me in Reddit:


in dom0

`qvm-features win10 gui 1`

*win10 is the name of the machine

I don't know why it works but it works

I have no internet in win10 now. Do you?

**Comment by 0rb677** [comment]
> @0rb677 somebody said to me in Reddit:
> 
> in dom0
> 
> `qvm-features win10 gui 1`
> 
> *win10 is the name of the machine
> 
> I don't know why it works but it works
> 
> I have no internet in win10 now. Do you?

Win 10 is not  good idea. Seamless mode not working, no audio and QWT unmaintained now, no USB passthrouth.
Try win7.

**Comment by elliotkillick** [comment]
This bug affects any Windows qube that doesn't have the Qubes GUI `qvideo` driver installed, including Windows 7, 8 or and others. It's not specific to Windows 10.

It only seems that way because the only desktop Windows OS that supports the `qvideo` driver is Windows 7 (I'm guessing you didn't try Windows 8). However, if you were to uncheck the installation of Qubes GUI tools on the QWT installer in Windows 7 the same bug would emerge.

At first glance, this appears to be a bug in CheckGuiAgentPresence() of advertise-tools.c (https://github.com/QubesOS/qubes-core-agent-windows/blob/master/src/advertise-tools/advertise-tools.c) where it incorrectly detects that the GUI agent is installed whether or not it actually is. However, further research is necessary to verify this.
