### ISSUE TITLE
A real issue with issue #4687

### ISSUE THREAD

**Issue by chaywoo** [QubesOS/qubes-issues#5747]
Qubes 4.03 fresh install, everything updated, but I cant get my appvm private.img to mount as recommended in issue #4687. I bought a second SSD and installed windows10 on the new SSD, but for some reason, Windows10 screwed up the booting capability of the qubes SSD. So after installing Windows10 on the other SSD, I installed ReInstalled Qubes to a 500gb partition on the same Qubes SSD for two qubes systems.. When I installed Qubes 4.03, it screwed up the windows10 boot partition on the other SSD. So then I removed the SSD for qubes and reinstalled windows10, rough night. Now I cant seem to access my old appvm information.. I screwed up the new qubes install trying to copy everything over to the new install, that was a disaster, so I installed qubes again and now I am trying to get the data at least. I have bitcoin wallet with bitcoins, plenty of court documents, calendar appts, I have been searching for days and there isnt much on this topic..
 Here is the error in Dom0 Terminal after entering [user@dom0 ~]$ qvm-block attach DispTest dom0:$dev
qvm-block: error: backend vm 'dom0' doesn't expose device 'private.img'
and now I am pretty sure I have tried everything there is to try. Or at least that I know of, my butt hurts from the seat and my eyes are pissed.. I am so beat down by this fiasco that I will glady send a $20 bitcoin donation to any address as a token of my appreciation as soon as I can get my data back im in trouble if I lose court papers. Im suing the cops long story LoL.. Thanks so much..
-Chris

Please do not delete or remove any part of this issue template. -->

### Affected component(s) or functionality:

---

### General notes:

---

**Comment by chaywoo** [comment]
yes i know its my fault, i should have removed the qubes SSD before installing windows on the other one.. I was lazy and didnt think it would be a problem since they were two seperate drives LoL..

**Comment by chaywoo** [comment]
Pretty much everything else I do is met with one of my favorite phrases of all times.. PERMISSION DENIED. LoL Are there any "Master Keys" available? My own computer telling me to screw off? LoL well I know that must be for the bad guys, but its a little inconvenient.. Yes I know with a Master Key I could really do some damage real fast, but I would prefer me blowing up my computer because i did something stupid rather than my computer giving me the middle finger every time I try to act smart..

**Comment by neowutran** [comment]
Quite hard to understand the final state of this mess. 
You have 1 physical disk with: Windows 10, and 1 physical disk with: a new QubesOS install and your old QubesOS install ? 

IF you didn't destroyed the data while resizing the disk, you could retrieve the data from the old QubesOS install. Multiple way to do that. But for example: 
- First, Decrypt the old QubesOS partition table https://www.qubes-os.org/doc/mount-from-other-os/ 
- Then, Then mount the lvm image https://www.qubes-os.org/doc/mount-lvm-image/ | https://github.com/Qubes-Community/Contents/blob/master/code/OS-administration/mount_lvm_image.sh
- Once you have done that, you can just copy the files you want

Also, this is not a QubesOS issue, so this have probably no reason to be on the QubesOS issues tracking system. And "A real issue with issue" is a horrifying name not matter where you post it. And you can edit comments instead of posting multiples. Try reddit or something similar for this kind of things

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
