### ISSUE TITLE
Grub in HVM on Qubes 4.1 is unusably slow

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5790]
## Observation

openQA test in scenario qubesos-4.1-update-x86_64-system_tests_pvgrub_salt_storage@64bit fails in
[TC_41_HVMGrub_debian-10](https://openqa.qubes-os.org/tests/7017/modules/TC_41_HVMGrub_debian-10/steps/1)

```
# test_000_standalone_vm
# error: 

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/qubes/vm/qubesvm.py", line 1603, in start_qrexec_daemon
    env=qrexec_env, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/site-packages/qubes/vm/qubesvm.py", line 1578, in start_daemon
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['runuser', '-u', 'user', '--', '/usr/sbin/qrexec-daemon', '-q', '19', 'test-inst-vm1', 'user']' returned non-zero exit status 3.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/qubes/tests/integ/grub.py", line 105, in test_000_standalone_vm
    self.loop.run_until_complete(self.testvm1.start())
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/site-packages/qubes/vm/qubesvm.py", line 1162, in start
    yield from self.start_qrexec_daemon()
  File "/usr/lib/python3.7/site-packages/qubes/vm/qubesvm.py", line 1610, in start_qrexec_daemon
    self.qrexec_timeout, self.name
qubes.exc.QubesVMError: Cannot connect to qrexec agent for 90 seconds, see /var/log/xen/console/guest-test-inst-vm1.log for details

# system-out: 
```

## Test suite description
The test start a HVM with in-VM grub bootloader, which tries to load from within the VM.

## Preliminary analysis

The grub is very slow. Specifically, loading kernel + initramfs takes tens of seconds, hitting 60s VM startup timeout.
It works fine on Qubes 4.0, but I haven't isolated which change causes it (ideas: Xen, grub, stubdomain/qemu).

## Reproducible

Fails since (at least) Build [4.1-20190702.2](https://openqa.qubes-os.org/tests/3172)

## Expected result

Last good: (unknown) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=update&machine=64bit&test=system_tests_pvgrub_salt_storage&version=4.1)

**Comment by pwmarcz** [comment]
Debugging notes:

* Qubes 4.1
* Grub 2.02
* Fedora 31-based StandaloneVM, HVM mode, kernel set to "none"

There is over 60-second pause after machine start, before kernel log starts appearing.

I enabled Grub logging (`set pager=0, set debug=all` in Grub config) and "debug mode" in order to see the VGA output.

![image](https://user-images.githubusercontent.com/468495/82052506-08919c80-96bc-11ea-91fb-13730eb85d95.png)

![image](https://user-images.githubusercontent.com/468495/82051869-f82cf200-96ba-11ea-8caf-d165e6bfa6fc.png)

It looks like grub does the opening-disk steps (GPT header, entries etc.) each time it tries to open a file, and the "Detecting ext2..." step takes a few seconds every time.

**Comment by easydozen** [comment]
seabios with _CONFIG_ATA_DMA=y_ should fix this issue.

**Comment by jevank** [comment]
It works and drastically improves Windows boot time too.

**Comment by marmarek** [comment]
Sounds like a good idea to enable it indeed, but requires some testing. The reason why it's disabled upstream is problems with FreeDOS: https://www.mail-archive.com/qemu-devel@nongnu.org/msg593254.html
I guess it means we don't have a chance to convince Fedora to switch the config, and we will need to maintain our own build.

**Comment by deeplow** [comment]
This issue seems to keep happening so I think we should re-open it @marmarek. Although the change seems to have fixed it on `Debian` templates (around test 9375), there are still a lot of instability in fedora templates:

![fedora-fails-full-history](https://user-images.githubusercontent.com/47065258/135448253-c9cde8a7-c7f4-465d-b085-3ef9dcf55f3e.png)

It's also interesting how `fedora-*-xfce` are more affected than simple `fedora-*`. Furthermore, the issue seems to always happen on the `vm.start()` call and I speculate `test_000` happens less times than `test_010` because it has more `vm.start()` calls (3 versus 2) -- so it has more chances to fail.

**note:** simply increasing the `qrexec_timeout` prop to `120` for example, does solve the instability, but it doesn't actually solve the slow startup. So I would argue this is not as much instability of the test, but rather instability of the VM startup.

**Comment by marmarek** [comment]
> It's also interesting how `fedora-*-xfce` are more affected than simple `fedora-*`.

I'm not sure if that's relevant for _this_ test, but I've found that installing updates in fedora-*-xfce templates in openQA was broken recently (or rather: updates were installed and then the template was reverted...). This affected all the tests in the last 2 weeks, fixed in the test run currently in progress.

**Comment by deeplow** [comment]
This also affects `whonix-ws-15`. It's just doesn't show in these tests because the GrubHVM tests [don't run in `whonix-ws-15`](https://github.com/QubesOS/qubes-core-admin/blob/2bc3393/qubes/tests/integ/grub.py#L42).

The audio test [223, 224 and 225](https://github.com/QubesOS/qubes-core-admin/blob/209cd9/qubes/tests/integ/vm_qrexec_gui.py#L604) are also HVMs that start. Those tests locally are always failing for me with this same issue. Oddly enough this issue hasn't surfaced in openQA. On the following plot we can see all the errors that the audio tests 223, 224 and 224 have and none is `Cannot connect to qrexec agent`:

![fails_audio](https://user-images.githubusercontent.com/47065258/135485615-62eebc97-d80c-467a-83fb-d8c6d0d13808.png)

The issue can be reproduced in the terminal with this: 

   ```shell_session
   [user@dom0 ~]$ qvm-create --class AppVM --template fedora-34 --label red --prop virt_mode='hvm' test-1
   [user@dom0 ~]$ qvm-start test-1
   Cannot connect to qrexec agent for 60 seconds, see /var/log/xen/console/guest-test-1.log for details
   ```

**Comment by deeplow** [comment]
> You mean this affects also HVMs with dom0-provided kernel, not only those running in-VM kernel (via grub)?

Sorry for the delay (issues with fan). I believe this is the case and it doesn't actually have to do with in-VM kernels (via grub). But tbh, I'm not too familiar with how HVMs work. I've been able to reproduce this issue with the following as well: (which I think also shows this fact)

```diff
diff --git a/qubes/tests/integ/grub.py b/qubes/tests/integ/grub.py
index abed4f07..383ec7ca 100644
--- a/qubes/tests/integ/grub.py
+++ b/qubes/tests/integ/grub.py
@@ -151,6 +151,27 @@ class GrubBase(object):
 
         self.assertXenScrubPagesEnabled(self.test_template)
 
+    def _create_appvm(self, name):
+        vm = self.app.add_new_vm(
+            qubes.vm.appvm.AppVM,
+            label='red',
+            name=name,
+            template=self.app.domains[self.template])
+        vm.virt_mode = self.virt_mode
+        self.loop.run_until_complete(vm.create_on_disk())
+
+        return vm
+
+    def test_011_appvm_start(self):
+        """ minimum viable prototype to reproduce issue
+        https://github.com/QubesOS/qubes-issues/issues/5790
+
+        similar to test integ/vm_qrexec_gui.py/test_000_start_shutdown"""
+        vm_name = self.make_vm_name('appvm')
+        vm = self._create_appvm(vm_name)
+
+        self.loop.run_until_complete(vm.start())
+
 @unittest.skipUnless(os.path.exists('/var/lib/qubes/vm-kernels/pvgrub2'),
                      'grub-xen package not installed')
 class TC_40_PVGrub(GrubBase):
```

**Comment by marmarek** [comment]
Initial issue about grub is solved already. Other issues can be tracked separately.
