### ISSUE TITLE
Titlebars ruining some applications even in fullscreen

### ISSUE THREAD

**Issue by QUser534** [QubesOS/qubes-issues#5814]
**Qubes OS version**
4.0 fully updated to latest version

**Brief summary**
Certain apps do not display correctly because they show a title bar even though there should be no title bar. This effects even apps running in "full screen" as any child windows created by app which may not be intended by the app to be a real window (such as showing text tooltip, quick popup, context menu, etc) will still show qubes title bars.

**To Reproduce**
1) Download Trader Workstation https://www.interactivebrokers.co.in/en/index.php?f=38477#tws-software

2) Run application and there will be a titlebar surrounding application even if "full screen" is set to enabled for this qube. In "full screen" the primary window will remove the title bar. However, the issue is this uses many "popup" windows that overlay the primary window. All of these will have titlebars even though they should not (they do not even appear in the task bar)

**Expected behavior**
I expect the program to not show titlebars as it has a built-in title bar for all windows that need them. It interrupts the functionality of the program to have them due to the "popup windows" which are used for things as simple as tooltips.

At a minimum a when an application is put in "fullscreen mode" any child windows it creates should be without titlebar. However, an option to be without titlebar even not in fullscreen would be ideal.

You can see an image of what the app looks like you can see it has it's own titlebars: https://i.ytimg.com/vi/L6fxR3NhlSE/maxresdefault.jpg

You might think this is petty, but it impacts the functionality. In the screenshot notice there are "child windows" Each of these will have a Qubes titlebar. These "child windows" can be used as simple to have small tooltips, etc, which now will have a qubes titlebar too.

**Actual behavior**
Titlebars are everywhere where they should not be even if primary window is in fullscreen.

**Screenshots**
Correct looking app: https://i.ytimg.com/vi/L6fxR3NhlSE/maxresdefault.jpg

The picture with the problem would look just like that except primary window would have a qubes titlebar around it and the inner child windows would also have a qubes title bar

**Additional context**
This is not the only app that has this issues. It also affects Think or Swim trading platform. It seems to affect about every java application that has it's own built-in titlebars.

**Solutions you've tried**
Running the app in "fullscreen" which removes titlebars from primary window, but not child windows created by the app. Preferable solution would be a way to exclude the qubes titlebars even when not in fullscreen.

**Comment by marmarek** [comment]
Generally, normal windows do have decoration (titlebar) added on purpose, to convey information to which VM the window belongs. While in case of some applications indeed it means duplicated titlebar, removing it would significantly degrade security isolation provided by qubes (that you always know with which VM you interact). What you can do, is to change window manager theme to some with smaller titlebar.
But things like tooltips or menus should have only a small border without a title bar. And I think this application works almost like I described. I see just two issues:
 - tooltips appears shortly as normal windows (with titlebar) but disappears almost instantly and in most cases appear again correctly with colorful frame (see "Position" tooltip in screenshot below). I think it is issue described in #3982
 - fullscreen button doesn't work for me - nothing happens (even after [enabling it](https://www.qubes-os.org/doc/full-screen-mode/#enabling-full-screen-mode-for-select-vms-1) for this vm). In fact maximize button doesn't work for me either. I see many messages like `invalid PMaxSize for 0x3c00147 (32766/32766)` in `/var/log/qubes/guid.<vmname>.log` and I think those are related to the issue.

Otherwise, based on brief test, it works as expected:

![java-app2](https://user-images.githubusercontent.com/726704/81621707-68075800-93ef-11ea-8808-a396c7412966.png)

Is your main issue about tooltips? Does it behave differently on your side?
