### ISSUE TITLE
i3 Generated config does not float Tor Browser by default

### ISSUE THREAD

**Issue by BawdyAnarchist** [QubesOS/qubes-issues#5818]
**Qubes 4.0.3**

**Affected component:**  TorBrowser in i3wm  
**Summary:**   Default i3 config generated at first login does not set TorBrowser floating

### Steps to Reproduce Undesired Behavior

1. Install i3wm, and then do first login where i3wm generates default config
2. Config file does not contain floating modifier for TorBrowser windows
3. TorBrowser, is forced to tile when launched
4. Undesireable because it causes unique window size to be reported to websites

**Expected Behavior:**  i3 config on Qubes should make Tor Browser floating by default

### Solution

`vi /home/user/.config/i3/config`  
add line: `for_window [title="Tor Browser"] floating enable;`

**Additional Context**   
The line is present in the config files in the [qubes-desktop-linux-i3-settings-qubes](https://github.com/QubesOS/qubes-desktop-linux-i3-settings-qubes) repo, however, it doesn't seem to make it onto the config file generated by i3 at first logon.  It is also present in the files in `/etc/i3/` in dom0.  I deleted my `/home/user/.config/i3/config` and regenerated the default, but line is still not present.

**Comment by h01ger** [comment]
On Tue, May 12, 2020 at 08:32:12PM -0700, BawydAnarchist wrote:
> **Expected Behavior:**  i3 config on Qubes should make Tor Browser floating by default

FWIW, I disagree. Because first I don't think we should differ from upstream
defaults and second because I think torbrowser not floating is the right default
when using i3.


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

In Europe there are people prosecuted by courts because they saved other people
from drowning in the  Mediterranean Sea.  That is almost as absurd  as if there
were people being prosecuted because they save humans from drowning in the sea.

**Comment by BawdyAnarchist** [comment]
Isn't it already the case that the default config generated by Qubes-i3 is different?  And "upstream" for Tor Browser has the window launch as floating, with a preset size.

This is a security feature, without which, users have a much more unique fingerprint.

**Comment by SvenSemmler** [comment]
On Wed, May 13, 2020 at 06:09:23AM -0700, Holger Levsen wrote:
> On Tue, May 12, 2020 at 08:32:12PM -0700, BawydAnarchist wrote:
> > **Expected Behavior:**  i3 config on Qubes should make Tor Browser floating by default
> 
> FWIW, I disagree. Because first I don't think we should differ from upstream
> defaults and second because I think torbrowser not floating is the right default
> when using i3.

+1 ... also the original concern is misguided. Tor Browser in its
current iteration will not report a unique windows size unless the user
explicitly disables that protection in the config. That's why there is a
weired border around the website.

**Comment by BawdyAnarchist** [comment]
Oh, cool. I guess that's a somewhat recent change?  In that case I retract my bug.
