### ISSUE TITLE
qui-devices widget inconsistent failure

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#5821]
**Qubes OS version**
R4.1

**Affected component(s) or functionality**
qui-devices

**Brief summary**
After a failed connect/disconnect, the widget should check which state the device should be in, if for some reason it desynchronized.

**Comment by marmarta** [comment]
@marmarek , you reported this - could you describe how to reproduce it? I have a problem with reproducing this bug.

**Comment by marmarek** [comment]
One way it happens is to attach a microphone, then kill matching `pacat-simple-vchan` process in dom0 (in my case it actually crashed). And then start it again (same arguments).
After this, to get audio working again in the VM, you need to reload pulseaudio module in that VM:
```
pactl unload-module module-vchan-sink
pactl load-module module-vchan-sink
```
At this point, `qvm-device mic` reports mic as detached and attaching/detaching works there. But the widget reports it as still attached and it can't be fixed with just GUI.

Generally the issue arise from the fact that this "detach" method doesn't result in a matching detach event. But the GUI should be resistant to weird cases too, if that's easy to achieve (which I believe is the case here).
