### ISSUE TITLE
Consider a distro other than Fedora for system management

### ISSUE THREAD

**Issue by Strykar** [QubesOS/qubes-issues#5835]
**The problem you're addressing (if any)**

This is a long shot, but I thought I'd ask..
Is it conceivable that another distro could be used for system management under Xen besides Fedora? Or is Qubes so tightly coupled with Fedora/RPM that it's out of the question?

**Describe the solution you'd like**

It would be nice to have the features of Qubes, giving users the choice of distro for system management, even 1 - 2 more other than Fedora or RH derivatives.

**Where is the value to a user, and who might that user be?**

The benefit of choice, not having to learn a new distro/pkg mgr. instead bring the experience of their distro to bear and start getting productive sooner.

**Describe alternatives you've considered**

Debian/Ubuntu, Arch and Suse to name a few.

**Comment by SvenSemmler** [comment]
On Thu, May 21, 2020 at 06:07:37PM -0700, Avinash H. Duduskar wrote:
> This is a long shot, but I thought I'd ask..

This is an evergreen question. 

> Is it conceivable that another distro could be used for system
> management under Xen besides Fedora? Or is Qubes so tightly coupled
> with Fedora/RPM that it's out of the question?

It's conceivable but also largely irrelevant. If you find yourself
installing lots of software in dom0 or customizing it much you are
probably doing something you shouldn't.

Granted if you want to customize XFCE (or KDE / i3) you have to do some
work in dom0 but this will go away soon as the GUI will move into a
dedicated qube (which I am guessing can then be any distro you build the
qubes-core-* packages for).

If dom0 ever gets another distro it will be something very small and not
intended to be touched by the user ever. 

> The benefit of choice, not having to learn a new distro/pkg mgr.
> instead bring the experience of their distro to bear and start getting
> productive sooner.

I am pretty sure this ticket will be closed/rejected by Andrew soon, but
if you take your question over to the qubes-users mailing list you might
get some instructive feedback and we could discuss a little why you
think you need to do much of anything in dom0.

**Comment by qwrd** [comment]
https://github.com/QubesOS/qubes-issues/issues/1919

**Comment by TNTBOMBOM** [comment]
it is a horrible decision no wonder to choose fedora, but as @qwrd posted this is already discussed case. 

and these stuff needs to be fixed for debian: (table)

https://wiki.debian.org/Qubes/Devel

**Comment by andrewdavidwong** [comment]
As qwrd pointed out, there is already an existing issue (#1919) for using Debian in dom0.

The rest of this issue is more of an open-ended question rather than a concrete, actionable feature request. Please see our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/) for more detail about why `qubes-issues` is not the place for such discussions. We suggest taking such development-oriented discussions to the `qubes-devel` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
