### ISSUE TITLE
QVM move-file-to-vm UI window: shows incorrect operation 

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#5841]
**Qubes OS version**
SD Workstation custom/current version

**Affected component(s) or functionality**
qvm move-to-vm UI

**Brief summary**
On the line of text that shows the Operation, it shows `qubes.Filecopy` when in fact the operation is _moving_ the file.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to Nautilis File Manager, w/in any VM
_2. Right Click on two files
_3. Select "Move to VM"
_4. See operation in designated field

**Expected behavior**
To show whatever the operation is to move a file.

**Actual behavior**
Shows the same text as I get when I invoke Copy-To-Vm

**Comment by marmarek** [comment]
Well, "move" operation is nothing else than "copy" and then "remove source". And this is what you see.
And even more: the "copy" part is indeed happening from one qube to another (and thus the operation goes through qrexec policy, which in default config asks the user), but "remove" part is happening in the source qube alone and doesn't involve qrexec (policy) at all.

If we'd go with custom prompts for various services (which is what you propose in #5840), I'd simply describe this as "file copy/move", if that would be more helpful.

**Comment by eloquence** [comment]
It would be great to be as clear as possible in a dialog about what the result of a specific operation is going to be. When a user selects a set of files in the file manager and picks "Move to AppVM", and the next prompt asks them to approve a "copy" operation, they may think they accidentally made the wrong choice earlier. Worse, if they _actually_ made the wrong choice (selecting "move" instead of "copy"), there's nothing in the dialog that makes it clear that the files will be removed.

The GUI sequence here is "Select files in Nautilus" -> right-click and pick the operation -> "Operation execution" dialog appears. So there really are no additional guardrails for the user, as far as I can tell.

Would it be possible for the calling VM to somehow pass along additional information about the operation, so the dialog can be specific and informative, instead of presenting information that is either potentially misleading ("Filecopy") or ambiguous ("copy/move")?

**Comment by marmarek** [comment]
Theoretically, it would be possible to make identical service named `qubes.Filemove`. I don't like it much for the reasons above, but now I see how that could be helpful. It does introduce some compatibility issues when handling templates imported from older version (we do keep backward compatibility between templates within major version number - 4.x here), but I think that would be manageable.

**Comment by rustybird** [comment]
The caller could simply add a `+move` argument (possibly in all cases, so the user's intention doesn't unnecessarily leak to the remote side), which the existing `qubes.Filecopy` happily ignores. Then the dialog would say "Operation: **qubes.Filecopy+move**"

**Comment by rustybird** [comment]
Or even something like `+delete` only for the move case: "Operation: **qubes.Filecopy+delete**"

**Comment by marmarek** [comment]
I was considering it too, but in context of #5840 I think argument would be needed for something else.

**Comment by ninavizz** [comment]
Would be nice to resolve this along with other parts of the qrexec experience being considered with #4721
