### ISSUE TITLE
qvm-sync-clock should perhaps use a higher precision (i.e. nanoseconds) rather than just using second precision when synchronizing time

### ISSUE THREAD

**Issue by trackroute** [QubesOS/qubes-issues#5876]
A the moment qvm-sync-clock uses second level precision to sync time (i.e. it uses "date -u -Iseconds". The problem with ignoring the nanoseconds is that the VMs being synced can end up almost a full second behind ClockVM. e.g, at the moment if the time on ClockVM is 00:00:00.999999999, the time on VM1 is set to 00:00:00.000000000, so it will almost be a second behind.

To switch to a higher resolution we can use "date -lns" rather than "date -lseconds". 
In /etc/qubes-rpc/qubes.GetDate in Dom0 (the python there the nanoseconds can be added by inserting ",%f000".

Though, perhaps second only resolution is a deliberate security feature?

Edit: Sorry for the incoherent initial post, submitted it by accident.

**Comment by xaki23** [comment]
i actually have a changeset for that sitting around somewhere.
@marmarek requested to not change the existing calls, the it uses a new call qubes.GetDateNS and it uses "epoch time float" as transfer format (because turning it into a human-format string just to turn it back is not very useful and makes validation (the regex) a lot more complicated.

note that switching to a higher resolution does _not_ solve the problem of time going backwards.
we are dealing with variable delay between the involved VMs, so a "the delay for this call is unusualy high" will still make the clock jump back.

the workaround for _that_ would be to use the time-slewing mechanism of adjtimex which complicates the whole thing. 

i will see if i can turn the basic "use higher resolution but still do time stepping" into a PR.

**Comment by trackroute** [comment]
Resolved ( #7081 )
