### ISSUE TITLE
qubes-gui: automatically lower override-redirect windows under the screensaver window.

### ISSUE THREAD

**Issue by iamahuman** [QubesOS/qubes-issues#5908]
**The problem you're addressing (if any)**
#2026 - [XFCE] locked xscreensaver displays sensitive notifications

**Describe the solution you'd like**
Ensure X11 override-redirect windows are stacked under the lock screen as they are mapped (but before contents are drawn).

**Where is the value to a user, and who might that user be?**
Resolve #2026 without a VT switch or leaving GUI for console.

**Describe alternatives you've considered**
If VT switch is available (there's an issue here, see #4943 and #5460), following alternatives are desirable:
 - use physlock (#1917)
 - use lightdm's greeter in a new VT (with Xorg `DontVTSwitch` enabled). Test this feature in an existing Qubes installation with `dm-tool --lock` in Dom0. Perhaps also look into [light-locker](https://github.com/the-cavalry/light-locker/).

**Additional context**
Pop-up windows constantly popping up (no pun intended) onto the lock screen is due to `override-redirect`, an inherent problem of X11<sup>[[1]](https://www.jwz.org/xscreensaver/faq.html#popup-windows)[[2]](https://bugzilla.gnome.org/show_bug.cgi?id=154529)</sup>. In this case, however, we're in luck since _every_ application window (save for Dom0 riskers who can't rely on Qubes for security in the first place) is managed by [a single program](https://github.com/QubesOS/qubes-gui-daemon).

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
 - https://www.jwz.org/xscreensaver/faq.html#popup-windows
 - X11 documentation

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#963, #1917, #2026, #2120, #5731

**Comment by marmarek** [comment]
IMO alternative solutions you've listed may have better chance to solve this and similar issues. But one issue with switching to a console/different X instance is drivers compatibility - see issues like #4943

**Comment by iamahuman** [comment]
@marmarek I personally like much more the alternative options too. I suggested this solution _only_ as a conservative approach that will minimize breaking things for existing users. Introducing new packages in an existing release is much of a hassle.

**Comment by marmarek** [comment]
Various alternative options sounds attractive, but switching VT unfortunately is something that leads to issues. Plus upgrade path issue you mentioned.

So, while this isn't very nice, I think this is preferable solution to #2026. 

For implementing this, I need to find one (or both) information: 
1. window(s) ID of screenlocker (then I can use `XRestackWindows` to place override-redirect windows always below it)
2. whether it is active (then I can use `XLowerWindow` on override-redirect windows if screenlocker is active)

For Xscreensaver specifically, the only official way to find the second one is `xscreensaver-command -time` and parse the output. Spawning a process whenever new window is opened isn't particularly good idea... I've looked into implementation and it seems to just read `_SCREENSAVER_STATUS` property on the root window (the status is in the first word).
As for finding screenlocker window ID, I can look for `xscreensaver` window class (this isn't spoofable by the VM, as VM windows have VM name prefix).

i3lock seems to create window with `i3lock` class and no other indicator.

Haven't checked KDE, but I guess there is some d-bus API to get that information. Plus (hopefully) a constant window class.

Have I missed anything?

**Comment by marmarek** [comment]
Alternative to `XLowerWindow` can be `XRaiseWindow` on screenlocker - this way those notification or whatever windows won't hide below everything else.
As for `XRestackWindow`, there is a bit worrying comment in the man page: "For each window in the window array that is not a sibling of the first window, a BadMatch error results" - requires checking what this means in practice and if it's an issue.

**Comment by andrewdavidwong** [comment]
Increasing priority to **critical** based on the discussion in #2026.

**Comment by jamke** [comment]
Guys, to avoid duplicates:
I see all firefox and thunderbird notifications when the Qubes OS R4 screen is **locked** with XScreenSaver.
Is it the same issue that one being discussed here?

It's obviously a bug and at least privacy or even security problem. I know it can be xscreensaver bug but it still kind of undermines "reasonable secure" in Qubes OS description, as I've never had that flaw in KDE screen locker nor Windows. So, maybe "bug" label will be better, because it's "critical enhancement" now.

**Comment by pwmarcz** [comment]
@jamke Thanks for reporting! It seems to be the same issue: notifications appearing on top on locked xscreensaver. I think the fix in https://github.com/QubesOS/qubes-gui-daemon/pull/50 will solve that for all notifications.

**Comment by jamke** [comment]
@pwmarcz ok, thank you for PR with fix! Hope the issue will be solved soon.

**Comment by andrewdavidwong** [comment]
> Guys, to avoid duplicates:
> I see all firefox and thunderbird notifications when the Qubes OS R4 screen is **locked** with XScreenSaver.
> Is it the same issue that one being discussed here?
> 
> It's obviously a bug and at least privacy or even security problem. I know it can be xscreensaver bug but it still kind of undermines "reasonable secure" in Qubes OS description, as I've never had that flaw in KDE screen locker nor Windows. So, maybe "bug" label will be better, because it's "critical enhancement" now.

 - An "enhancement" refers to either a new feature or an improvement in something that already exists.
 - A "bug" refers to a flaw in something that already exists.
 - "Critical" is one of the priority levels.

You can read more about this [here](https://www.qubes-os.org/doc/reporting-bugs/). There's nothing wrong with having a "critical enhancement." That's just an enhancement with a very high priority. It sounds like you might be assuming that bugs are inherently higher priority than enhancements and that enhancements are inherently limited in how important they can be, but that's simply not how we use those terms and labels in this issue tracker (which aims to use industry standard issue tracking terminology and practices).

The bug in XScreenSaver is indeed a bug, but XScreenSaver is upstream software. There's more than one way solve this general problem, which is why we have #2026, #5908, #889, and #1917. Take a look at the discussion on #2026 for more context. This has already been discussed to death, and the three issues that remain open are all `P: critical`. There is really no need to try to amp up the sense of urgency any further, because we all already know and acknowledge how important it is.

By the way, in the discussion on #2026, you can also see people making the mistake of thinking that an "enhancement" can't be a way to address this general security problem, which doesn't logically follow at all. Almost every new feature in Qubes addresses some security problem. You can also see the common mistake of assuming that bugs are inherently higher priority than enhancements, even though we explicitly represent issue *priority* separately from issue *type*. "Enhancement" vs. "bug" is simply a matter of issue classification for organizational purposes. Intuitively, you can think of it this way: This particular problem of notifications leaking through the screen locker is not due to a flaw in any Qubes code (but rather a problem in X or XScreenSaver or the interaction between the two, or something along those lines). Nonetheless, there are improvements we could make to what already exists in Qubes and new features we could implement that would obviate or mitigate the problem. Hence, the particular bug report for XScreenSaver is closed as `not our bug`, but the various enhancements are open as very high priority. (Again, see the discussion on #2026, where this was discussed.)

Having said all this, whether this issue (#5908) should count as a bug or an enhancement ultimately comes down to one question: Should override-redirect windows already have been automatically lowered under the screensaver window in the first place? In other words, is it a mistake or a flaw that this doesn't already happen? Or is this something that no one would have reasonably expected to already be in place, and it is only once we find ourselves in the present situation that it seems worthwhile to take the extra step of implementing such an enhancement? Part of this may depend on the normal behavior for this type of software, as well as standard software development practices, so it ultimately comes down to the Qubes developers' judgment. When issue reporters and I assign these labels, we are usually just making our best educated guess using the information available at the time, with the understanding that new information will become available later and that the labels can easily be changed later with the click of a button. Ultimately, this entire issue tracker is just a tool to facilitate the Qubes developers' workflow and to help them be efficient and productive.

**Comment by marmarek** [comment]
Some observation: notifications shown by `mate-notification-daemon` usually appears over xscreensaver, but those shown by `xfce4-notifyd` usually (but not always) below. I _guess_ the difference is when override-redirect flag is set  (the former does it from the very beginning, the latter only after window is created).
