### ISSUE TITLE
Updates to `kernel` package overwrite `/boot/efi/EFI/qubes/xen.cfg`, rolling back `kernel-latest`

### ISSUE THREAD

**Issue by tgeoghegan** [QubesOS/qubes-issues#5972]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
`qubes-dom0-update`

**Brief summary**
I need a kernel from `kernel-latest` to get hardware support for my laptop (a recent Thinkpad). However `qubes-dom0-update` still does updates on the `kernel` package, which will update `/boot/efi/EFI/qubes/xen.cfg` to point to the newly installed kernel. In my case, this caused my computer to roll back from kernel 5.6.16-1 to 4.19.128-1.

**To Reproduce**
1. `sudo qubes-dom0-update kernel-latest`
2. Consistently apply system updates via dom0 Qubes Updater application until a new `kernel` is found
3. Eventually reboot computer

**Expected behavior**
Updater should notice that 4.19.128-1 is older than 5.6.16-1 and at least avoid overwriting `xen.cfg`.

**Actual behavior**
`xen.cfg` is updated to boot 4.19.128-1 kernel.

**Solutions you've tried**
I was able to boot into a rescue shell with the installer livemedia and manually fix `xen.cfg`. Additionally adding `exclude=kernel` to `/etc/yum.conf` ought to prevent this in the future.

**Comment by andrewdavidwong** [comment]
(FYI, I think you meant `qubes-dom0-update` rather than `qubes-dom0-updater`.)

Since `qubes-dom0-update` uses `dnf` under the hood, I suspect that this is either:

 - Not a bug (perhaps further configuration is required)

or

 - A bug in `dnf`

However, since I'm not certain, I'll leave this issue open to see what @marmarek thinks.

**Comment by marmarek** [comment]
I would rather say it is a bug in our kernel post-install script. This is very similar to the same case for VM kernel: https://github.com/QubesOS/qubes-issues/issues/5309

**Comment by marmarek** [comment]
>  it fails to update the default in-VM kernel when making that update

It doesn't "fail". This is intended behavior - updating any kernel package (latest or not) does not switch default kernel flavor.
dom0 kernel and vm kernel are two separate packages. This feature is missing for dom0 kernel.

**Comment by icequbes1** [comment]
> It doesn't "fail". This is intended behavior - updating any kernel package (latest or not) does not switch default kernel flavor.

Yes, bad choice of words on my part; I did question if it was by design, as I can see valid reasons to not change the default in-VM kernel. My goal was to simply post my observations and how dom0 and in-VM kernel get out of sync.

FWIW, I didn't notice dom0 was 4.19 and PVH/HVM in-VMs were 5.6 for who knows how long, and didn't observe anything out of the ordinary that might be blamed on the kernel.
