### ISSUE TITLE
Don’t call systemctl daemon-reexec during AppVM boot

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5992]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s) or functionality:

AppVM startup scripts

---

### Steps to reproduce the behavior:

Setup encrypted swap in such a fashion that failure to encrypt the swap breaks VM boot.

### Expected or desired behavior:

`systemctl daemon-reexec` does not get called, so <https://github.com/systemd/systemd/issues/11573> does not happen.  I believe that the initramfs systemd already reexecs the systemd in the real root.

### Actual behavior:

https://github.com/systemd/systemd/issues/11573 gets triggered.  This causes services to randomly not start.

### General notes:

This is a systemd bug, but as it shows no signs of being fixed, we should probably work around it.  

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

https://systemd.io/INITRD_INTERFACE

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

None

**Comment by marmarek** [comment]
Actually, the``systemctl daemon-reexec` is under `if systemd_version_changed` - this remains from the times when dom0-provided initramfs used systemd too - different versions caused issues without reexec. But that function is buggy and consider changed version also when there was no systemd in initramfs.
Since we don't use systemd in initramfs anymore, the whole reexec can be dropped, as you propose.
