### ISSUE TITLE
minimal use guide w/ network setup instructions

### ISSUE THREAD

**Issue by raedah** [QubesOS/qubes-issues#6010]
https://www.qubes-os.org/doc/templates/minimal/

The minimal template guide show instructions for many things which require installing pkgs, but what it doesnt explain is how to get the network working on a minimal template in order to be able to install pkgs. To be clear, the networking device works when running the fedora minimal template directly, but networking does not work when using the fedora minimal template with an appvm. The minimal guide does not provide any insight into fixing this, rendering the minimal template unusable.

**Comment by unman** [comment]
@raedah As with all templates, you don't need networking to install packages - they are proxied, as explained [here](
https://www.qubes-os.org/doc/software-update-domu/#updates-proxy). 
Is this why you tagged it "invalid"?
Can you close.

**Comment by andrewdavidwong** [comment]
@unman answered this one well, but in the future, we kindly ask that you send help and support questions to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. As explained in on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), `qubes-issues` is not the place to ask help and support questions. In addition, as noted in the ["Important"](https://www.qubes-os.org/doc/templates/minimal/#important) section on the page you linked, "The Minimal TemplateVMs are intended only for advanced users. If you encounter problems with the Minimal TemplateVMs, we recommend that you use their standard TemplateVM counterparts instead."

------

> Is this why you tagged it "invalid"?

That label is automatically added when choosing the "Question or Support Request" option when creating a new issue, since, as explained above, this is not the appropriate place for such requests. After clicking that button, the issue also comes with text explaining this, which the user must replace with their own issue contents. This is intended to cut down on the number of inappropriate issues filed here.

**Comment by raedah** [comment]
While testing the minimal template it appeared an undocumented component needed to be installed to get network or proxy working, suggesting a documentation enhancement was needed. I since found that the network failure was coming from somewhere else. The minimal template does in fact have a working network proxy by default. Above info noted.
