### ISSUE TITLE
Changing Networking Breaks Qube Manager's Highlighting/Selection

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6036]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Qube Manager Visual Selection/Highlights

**Brief summary**
Highlight or Selection breaks/splits if a Qube's networking is changed while Manager is sorted by NetVM

**To Reproduce**
Open Qube Manager
Sort Qubes by NetVM (ascending or descending) 
Edit Qube Settings for a Qube and change the networking option to a different NetVM or None.

**Expected behavior**
The last used Qube remains fully selected in Qube Manager

**Actual behavior**
When the settings are saved, the selection in Qube Manager gets split up as the items are resorted having selections in different fields on different lines.

**Screenshots**
See attached.
![IMG_3372c](https://user-images.githubusercontent.com/38737447/92434581-d07c0100-f165-11ea-838d-ca2dc8c362fb.jpg)

**Additional context**
The broken selection persists when sorting by any other field but gets corrected when selecting a qube.

It seems to only happen when sorted by NetVM and changing the networking.  I can't seem to get it to occur when sorted by name and then changing the name.

**Comment by marmarta** [comment]
this should be fixed in Qubes 4.1 by https://github.com/QubesOS/qubes-manager/commit/bb1995af2e90aae51f07c518b74d98221c2d5cc1  - weird behavior with selections was one of many reasons for the refactor; I used to be able to reproduce this behavior on old versions, but the new one works fine. I'll close this and if someone gets the error with Qubes 4.1 we'll reopen.
