### ISSUE TITLE
xorg-x11-drv-amdgpu missing from default installation (qubes 4.0, 4.1)

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#6044]
This is probably something that's becoming more of an issue now that more people are using AMD cards (or APUs)

reported here: https://qubes-os.discourse.group/t/xorg-amdgpu-module-does-not-exist/410/6

**Comment by tasket** [comment]
From what I'm reading in the 4.1 logs and online, radeonsi and amdgpu work together but apparently the former can perform most functions by itself in a sub-optimal way.

Unfortunately, although I'm already noticing improvements in responsiveness and correctness in rendering (my guess is alpha-channel processing isn't quite correct without amdgpu) since installing the missing driver, the fedora-32 version still doesn't recognize renoir / ryzen 4000 explicitly:

```
[    25.040] (--) AMDGPU(0): Chipset: "Unknown AMD Radeon GPU" (ChipID = 0x1636)

```

So we'll want to see an update of xorg-x11-drv-amdgpu package to a renoir-aware version in the future.

**Comment by pabpas** [comment]
I didn't know that installing xorg-x11-drv-amdgpu was even possible in dom0! Finally I was able to get rid of the horrible tearing that I have had in Qubes since the beggining :)
BTW, for me it works best together with kernel-latest.

**Comment by isodude** [comment]
What version of kernel-latest is that?

**Comment by isodude** [comment]
Thanks. Then I must have something odd in my setup since I can't get past unwind info errors when starting with the driver. Works with package from f33.

**Comment by johnnyboy-3** [comment]
FYI:
R4.2
Package is available but not installed by default ISO installation.
But didn't even noticed until now after using R4.2 couple of weeks.

**Comment by DemiMarie** [comment]
@johnnyboy-3 Does that mean that you are happy with the default “modesetting” driver?  If so, I think this should be closed as <https://github.com/QubesOS/qubes-issues/labels/R%3A%20declined>, since the modesetting driver is much more stable than the Intel or AMD drivers.

**Comment by johnnyboy-3** [comment]
For now, just reporting that the package is not installed by default.
Hadn't any problems without it though.
Noticed that the picture is darker in mpv when watching a video and brightness/contrast/gamma settings have no effect with amdgpu. (But did not test if those have an effect with the default modesetting driver)
Also didn't test power consumption.

**Comment by DemiMarie** [comment]
The modesetting driver uses Kernel Mode Setting (KMS), whereas the amdgpu driver access the hardware directly.  It is possible that such access can conflict with the kernel driver and cause the system to crash.
