### ISSUE TITLE
Add "Copy to AppVM" in dom0 Right Click Context Menus

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6072]
**The problem you're addressing (if any)**
To copy a file from dom0 to an AppVM, the only method appears to be using the terminal command `qvm-copy-to-vm <dest-vm> <file>`

**Describe the solution you'd like**
It would be great to have an option somewhere in the thunar File Manager Right Click Context menu to copy files to other VMs.

**Where is the value to a user, and who might that user be?**
Improves usability and workflow.

**Describe alternatives you've considered**
None.

**Additional context**
The option should probably NOT include a "move" feature as files being removed from dom0 isn't a good idea.

**Screenshots**
![Screenshot_2020-09-18_22-31-26](https://user-images.githubusercontent.com/38737447/93658100-54ec4080-f9fe-11ea-9a77-9429ef64db30.png)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/copy-from-dom0/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by 92VV3M42d3v8** [comment]
AFAIK Qubes team believes in isolating dom0 as much as possible and I have read somewhere that thunar file manager is planned to be removed from dom0 ( I think in some issue discussion)

**Comment by GWeck** [comment]
Screen shots are stored in dom0. To get them out to the world, they have to be copied to some AppVM. So having this operation as a menu entry would be very helpful.

**Comment by andrewdavidwong** [comment]
> AFAIK Qubes team believes in isolating dom0 as much as possible and I have read somewhere that thunar file manager is planned to be removed from dom0 ( I think in some issue discussion)

Correct. File managers, including Thunar, should not be used in dom0. See [Security Guidelines: dom0 precautions](https://www.qubes-os.org/doc/security-guidelines/#dom0-precautions) and #2458.

> Screen shots are stored in dom0. To get them out to the world, they have to be copied to some AppVM. So having this operation as a menu entry would be very helpful.

No, this can and should be handled by the screenshot tool (see #953, #5809, [qubes-qvm-screenshot-tool](https://github.com/QubesOS/qubes-qvm-screenshot-tool)), or else you run into the security problems associated with using file managers in dom0.

-----

Since this issue is about enhancing file managers in dom0, which rests on the mistaken presupposition that file managers should be used in dom0, I'm closing it as `invalid` in accordance with our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/). If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by GWeck** [comment]
The screenshot tool is just what is needed!

**Comment by andrewdavidwong** [comment]
> The screenshot tool is just what is needed!

That seems to be a common refrain for a while now. I'll bump up the priority on #953 further.

**Comment by zellchristensen** [comment]
I have to concur with @GWeck Pretty much the only reason to be in the file manager is due to screenshots being saved there and trying to get them out.
