### ISSUE TITLE
Qubes Domains widget: Move "Open Qube Manager" to the top of the list

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6119]
**The problem you're addressing (if any)**
When clicking the Qube Manager Tray icon, the option "Open Qube Manager" is always at the bottom of the list making it always in a variable location depending on the number of Qubes that are running.

**Describe the solution you'd like**
Move the option to the top of the list, even above the headings if possible.

**Where is the value to a user, and who might that user be?**
Provides greater usability and consistency for the user.

**Describe alternatives you've considered**
None

**Additional context**
Having the option at the top makes it so a user can more easily and more quickly open the Qube Manager window in a consistent manner as it would always be the first option.  
The user doesn't have to evaluate the length of the list every time it's opened to find the bottom to select the option.

**Comment by andrewdavidwong** [comment]
> When clicking the Qube Manager Tray icon, the option "Open Qube Manager" is always at the bottom of the list making it always in a variable location depending on the number of Qubes that are running.

I have my panel at the bottom of my screen rather than the top, so, for me, it's exactly the opposite situation. The bottom of my list is always (supposed to be) in the same location, but the top is variable depending on how many VMs are running.

Maybe it still makes sense to move it to the top since the default is for the panel to be on top, but that's a UX question that I can't answer.

**Comment by zellchristensen** [comment]
I can see that being a problem then!  Having an option for the user to change it based on their preference would be ideal I think.

**Comment by jamke** [comment]
It's better at the bottom if you have your panel on the left or right too.
First post should be modified - the option can be added, not just "change to top" as otherwise it will make it less comfortable for other half of users.

P.S. Better way for user currently is to install fabulous `easystroke` program and make a gesture e.g. with right button to start Qubes Manager and do a lot of other stuff in dom0.

**Comment by marmarta** [comment]
The more options we give, the more unfriendly and complicated the UI will be. I'm not a fan of making things even more complicated, to be honest.

**Comment by brendanhoar** [comment]
Then the solution is obvious: put it at both the bottom and top of the list.

**Comment by donob4n** [comment]
Hi, I remember on Qubes 3 where the systray icon was the Qube Manager itself and a left click on it shows/hides the manager window.

I think that a nice solution would be recovering this behaviour, a left click on the widget icon opens Qube Manager and a right click shows the current menu.

**Comment by marmarek** [comment]
No, definitely not. We deliberately eliminated the need to use right-click on those icons, this is not discoverable for many users. We are not going back here.

**Comment by donob4n** [comment]
And the opposite? Left click opens menu, right click hide/shows qube manager...

In the end what I would like is to have the Qube Manager ready when I need it without the start-up loading but I don't like to see it minimized (on the task manager bar) all time.

**Comment by marmarta** [comment]
As I've said, I'm against adding very difficult-to-discover, possibly-inconsistent with other tools behaviors. I find that a pretty rare usecase (based on user research, mostly, but also talking with people). If you need it, there are tools to enable this particular use case (see: https://askubuntu.com/questions/646346/xfce-hiding-an-application-from-the-taskbar ). But I don't think this is a good idea to put into our code.
