### ISSUE TITLE
Cannot verify packages from contrib repo

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6124]
_Originally posted by @tlaurion in https://github.com/QubesOS/qubes-issues/issue_comments/709520513:_

@fepitre @marmarek 
```
[user@dom0 ~]$ sudo qubes-dom0-update qubes-repo-contrib
[user@dom0 ~]$ sudo qubes-dom0-update qvm-screenshot-tools
```

No packages avail. Testing because not moved over to stable (testing phase is how long?)

```
[user@dom0 ~]$ sudo qubes-dom0-update --enablerepo=qubes-contrib-dom0-r4.0-current-testing qvm-screenshot-tool
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
--> Running transaction check
---> Package qvm-screenshot-tool.x86_64 0:0.7-0.fc25 will be installed
--> Processing Dependency: scrot for package: qvm-screenshot-tool-0.7-0.fc25.x86_64
--> Running transaction check
---> Package scrot.x86_64 0:0.8-14.fc24 will be installed
--> Processing Dependency: libImlib2.so.1()(64bit) for package: scrot-0.8-14.fc24.x86_64
--> Processing Dependency: libgiblib.so.1()(64bit) for package: scrot-0.8-14.fc24.x86_64
--> Running transaction check
---> Package giblib.x86_64 0:1.2.4-24.fc24 will be installed
---> Package imlib2.x86_64 0:1.4.9-1.fc25 will be installed
--> Finished Dependency Resolution
qvm-screenshot-tool-0.7-0.fc25.x86_64.rpm                   |  18 kB  00:00     
/var/lib/qubes/dom0-updates/packages/imlib2-1.4.9-1.fc25.x86_64.rpm already exists and appears to be complete
/var/lib/qubes/dom0-updates/packages/giblib-1.2.4-24.fc24.x86_64.rpm already exists and appears to be complete
/var/lib/qubes/dom0-updates/packages/scrot-0.8-14.fc24.x86_64.rpm already exists and appears to be complete
Successfully verified /var/lib/qubes/dom0-updates/packages/giblib-1.2.4-24.fc24.x86_64.rpm
Successfully verified /var/lib/qubes/dom0-updates/packages/imlib2-1.4.9-1.fc25.x86_64.rpm
Successfully verified /var/lib/qubes/dom0-updates/packages/qubes-repo-contrib-4.0.6-1.fc25.noarch.rpm
ERROR: could not verify /var/lib/qubes/dom0-updates/packages/qvm-screenshot-tool-0.7-0.fc25.x86_64.rpm
Successfully verified /var/lib/qubes/dom0-updates/packages/scrot-0.8-14.fc24.x86_64.rpm
ERROR: could not verify one or more packages
```

_Follow-up comment from @TheOne-Z in https://github.com/QubesOS/qubes-issues/issues/953#issuecomment-709615568:_
> @marmarek @tlaurion
> I replicated this and it seems that you cannot verify any packages from `qubes-repo-contrib` either, at least in dom0.

**Comment by marmarek** [comment]
Based on @icequbes1 comment in https://github.com/QubesOS/qubes-issues/issues/953#issuecomment-710066621:
It should be enough to add `--clean` option:
```
sudo qubes-dom0-update qubes-repo-contrib
sudo qubes-dom0-update --clean qvm-screenshot-tool
```

**Comment by andrewdavidwong** [comment]
Ok, do you want to implement a further fix for this, or just a doc update?

**Comment by andrewdavidwong** [comment]
Should `--clean` also be added when installing packages in Fedora TemplateVMs?

What about Debian TemplateVMs?

**Comment by marmarek** [comment]
No, this is specific to first package installation in dom0 only.

**Comment by andrewdavidwong** [comment]
Reopening because @juodumas reported in #6139 that using `--clean` did not work.

**Comment by icequbes1** [comment]
The initial approach in my comment for qvm-screenshot-tool was to remove /var/lib/qubes/dom0-updates within sys-whonix, which does work. I assumed `--clean` would do the same, but looking closer it only affects the dnf cache and not the whole dom0-updates fakeroot.

Verified-working steps:

```
sudo qubes-dom0-update qubes-repo-contrib

# I missed this line from @marmarek in my initial response
sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4-contrib-fedora

qvm-run sys-whonix 'sudo rm -rf /var/lib/qubes/dom0-updates'

sudo qubes-dom0-update --enablerepo=qubes-contrib-dom0-r4.0-current-testing qvm-screenshot-tool
```

Looking closer, there appears to be a Debian-updatevm-specific bug that explains why removing /var/lib/qubes/dom0-updates was needed:

note: DOM0_UPD=/var/lib/qubes/dom0-updates

1. qubes-dom0-update.sh transfers the rpmdb from /var/lib/rpm in dom0 to $DOM0_UPD/var/lib/rpm in updatevm
2. rpm on Debian works out of $DOM0_UPD/home/user/.rpmdb
3. qubes-download-dom0-updates.sh in a Debian updatevm symlinks $DOM0_UPD/home/user/.rpmdb to point to $DOM0_UPD/var/lib/rpm
4. qubes-download-dom0-updates.sh runs `rpm --rebuilddb`...this causes the bug
5. Before the rpmdb has been rebuilt, rpm renames the .rpmdb symlink to .rpmdbold.[pid]. This still points to $DOM0_UPD/var/lib/rpm
6. The rpmdb is rebuilt, except now $DOM0_UPD/home/user/.rpmdb is a directory and not a symlink. There are two copies of the rpmdb at this point.
7. After rpmdb is rebuilt, it [tries to remove](https://salsa.debian.org/pkg-rpm-team/rpm/-/blob/master/lib/rpmdb.c#L2435) the backed-up $DOM0_UPDATES/home/user/.rpmdbold.[pid]. This fails (the first time) likely because .rpmdb was originally a symlink. Causes the infamous "Could not delete old database ... at .rpmdbold.123").
8. Any successive qubes-dom0-update calls will only write to $DOM0_UPD/var/lib/rpm. $DOM0_UPD/home/user/.rpmdb is a directory so the symlink from step 1 never gets created, leading rpm in the updatevm to work off of the old rpmdb even if dom0 supplies an updated rpmdb with the new keys for contrib-repo.


Issues:

1. The gpg key from contrib repo does not get imported automatically when first installed.
2. rpmdb rebuilds within a Debian updatevm cause future dom0 updates of the rpmdb from dom0 to not be received.

Options:

1. Remove the $DOM0_UPD/home/user/.rpmdb directory forcefully before creating the symlink, or
2. Copy the $DOM0_UPD/var/lib/rpm to $DOM0_UPD/home/user/.rpmdb, since `rpm --rebuilddb` will kill the symlink anyway. rpmdb just doesn't like symlinks when rebuilding.

`rpmkeys --checksig` later on still validates against the $DOM0_UPD/home/user/.rpmdb for a Debian updatevm like Whonix.

**Comment by juodumas** [comment]
Confirming that I can install contrib packages on dom0 after removing `/var/lib/qubes/dom0-updates` on my Debian UpdateVM.

**Comment by tlaurion** [comment]
This should fix it, but I do not see update of contrib package? https://github.com/QubesOS/qubes-meta-packages/pull/50

**Comment by andrewdavidwong** [comment]
I don't understand. Could you please explain more clearly?
