### ISSUE TITLE
qubes-dom0-update: "this may take some time" message is misleading

### ISSUE THREAD

**Issue by iamahuman** [QubesOS/qubes-issues#6126]
**The problem you're addressing (if any)**
When a Qubes user runs `sudo qubes-dom0-update` in dom0, it shows the following message:

    Using [UpdateVM] as UpdateVM to download updates for Dom0; this may take some time...

Depending on the user, this might come as if the user's choice of `[UpdateVM]` is suboptimal and causes slowdown of system update.

**Describe the solution you'd like**

Something along the lines of:

```diff
-echo "Using $UPDATEVM as UpdateVM to download updates for Dom0; this may take some time..." >&2
+echo "Current UpdateVM in use: $UPDATEVM" >&2
+echo "Downloading updates for Dom0; please wait patiently..." >&2
```

Note that the original message _already_ exceeds 80 columns when the UpdateVM name is longer than 6 characters (e.g. `sys-firewall`).

**Where is the value to a user, and who might that user be?**
This depends on which Dom0 update mechanism the user relies on.
- Qubes update GUI: not affected.
- _some_ novice user using `qubes-dom0-update`: may save time changing UpdateVM to troubleshoot a non-existent performance issue

**Describe alternatives you've considered**
Following messages may be equally or more appropriate:

- `Using $UPDATEVM as UpdateVM to download updates for Dom0; please wait patiently...`
- `Dom0 update may take a long time, please wait... (current UpdateVM to download updates: $UPDATEVM)`

**Additional context**
Note that I'm not submitting a pull request, since this is more of a request for comments.

This may break scripts that parses the output of `qubes-dom0-update`.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
- https://www.qubes-os.org/doc/software-update-dom0/
- https://www.qubes-os.org/doc/dom0-secure-updates/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None

**Comment by andrewdavidwong** [comment]
From a UX perspective, the best thing would be to provide some kind of progress indicator. Presumably, that's not feasible, which is why we just have to say that it could take a long time. So, we want to communicate three main things to the user:

1. Which VM is the UpdateVM. This can be something simple, like `The UpdateVM is: sys-firewall.` or even `sys-firewall is the UpdateVM.`.
2. That a download is starting right now, and the things being downloaded are updates. I also prefer something simple here, like `Downloading...` or `Downloading updates...`.
3. That the download could take a long time (but we don't know even approximately how long and can't offer a progress indicator). I think `This may take some time.` is fine, as are variants like `This may take a while.` and `This might take a long time.`. If we wanted to provide a bit more information about *why* it might take a long time, we could say something like, `Depending on the size of the update and your connection, this may take a while.` Since we provide the option to download updates via `sys-whonix` in the installer, we could also consider explicitly noting that downloading updates over Tor take much longer than usual.

**Comment by alimirjamali** [comment]
Ok. I think this issue has been waiting long enough to fix. The patch for #9355 already solves some of the problems addressed here. For better clarification, both CLI & GUI updates for dom0 do provide much better progress information at this moment. In fact, the only remaining piece is detailed progress bars only in GUI updater (CLI has no issues).

Alternatives to subprocess.PIPE exist which could emulate a full terminal. Regretfully they are in pypi (last time I checked). So we could skip them.

> Note that the original message _already_ exceeds 80 columns when the UpdateVM name is longer than 6 characters (e.g. `sys-firewall`).

Breaking the message to two lines makes very sense. As the current one does not wrap-up nice in GUI updater at the moment.

I will try to come up with a better message based on the above suggestion and make the PR.
