### ISSUE TITLE
Remove --all flag from qvm-remove

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6128]
**The problem you're addressing (if any)**

`qvm-remove --all` is essentially the QubesOS version of `rm -rf --no-preserve-root /`

**Describe the solution you'd like**

`qvm-remove --all` should be an error.

**Where is the value to a user, and who might that user be?**

It avoids a useless feature that is purely a footgun.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

N/A

**Comment by unman** [comment]
I've used this feature perhaps 10 times in the time I've been using Qubes - it's absolutely not useless.
As to it's being a footgun (sic), it does at least have a safety, since the user is prompted whether they wish to proceed. Of course, a user *may* respond Y to this, or indeed may call `qvm-remove --all -f`, but in that case they are getting exactly what they asked for, even if it is not what they wanted.
Since the option is clearly signposted, I doubt any user is going to use it by mistake, whereas `rm -rf *` **is** easily called by mistake in `/`

**Comment by DemiMarie** [comment]
@unman what have you used it for?  From what I can tell, `qvm-remove --all` followed by a reboot leaves the system in an unrecoverable situation.

**Comment by unman** [comment]
On Sun, Oct 18, 2020 at 11:26:39AM -0700, Demi Marie Obenour wrote:
> @unman what have you used it for?  From what I can tell, `qvm-remove --all` followed by a reboot leaves the system in an unrecoverable situation.
> 

I use this when travelling - since I salt my system it's easy to travel
light, salt on arrival, and remove all later. But then I salt the
default qubes back.
Never tried rebooting before doing this - since the templates aren't
removed, why is the system unrecoverable? Or did you force removal of
some system wide requirement to *really* remove all qubes.

**Comment by alimirjamali** [comment]
Submitted a patch. `qvm-remove --all` without `--force` or `--exclude` will show additional warning and as for user excplicit confirmation.

@unman Hopefully this should not interfere with you workflow. You could still use `--force` or `-f` to bypass confirmation.

**Comment by unman** [comment]
On Tue, Jun 25, 2024 at 03:41:43PM -0700, Ali Mirjamali wrote:
[quote] 
@unman Hopefully this should not interfere with you workflow. You could still use `--force` or `-f` to bypass confirmation.
[/quote]
That works for me.
