### ISSUE TITLE
[Tracking] Options for improving Qubes on low-resource hardware

### ISSUE THREAD

**Issue by sptankard** [QubesOS/qubes-issues#6131]
**Qubes OS version (if applicable)**
All versions / recent and future releases.

**Affected component(s) or functionality (if applicable)**
Hardware support, performance, general user experience.

**Brief summary**
This is (intended to be a helpful) meta/tracking issue for assessing options to make Qubes work better on limited / low-resource hardware. (Limited RAM, disk, battery, limited cpu virt features, for low-budget users, etc.)

**Additional context**
One of the main barriers to Qubes is hardware (the other being technical knowlege). For folks without a lot of spare cash this is a particular challenge. By "low-resource" i mean a huge range from making Qubes work better on a laptop with only 8gb RAM, to perhaps eventually Qubes on arm/phones.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
A bunch, but none particularly relevant here.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/3925
https://github.com/QubesOS/qubes-issues/issues/2233
https://github.com/QubesOS/qubes-issues/issues/5298
https://github.com/QubesOS/qubes-issues/issues/2826
https://github.com/QubesOS/qubes-issues/issues/5696
https://github.com/QubesOS/qubes-issues/issues/4398
https://github.com/QubesOS/qubes-issues/issues/3725
https://github.com/QubesOS/qubes-issues/issues/1310
https://github.com/QubesOS/qubes-issues/issues/5041
https://github.com/QubesOS/qubes-issues/issues/3887
https://github.com/QubesOS/qubes-issues/issues/5520
https://github.com/QubesOS/qubes-issues/issues/5371
https://github.com/QubesOS/qubes-issues/issues/4120
https://github.com/QubesOS/qubes-issues/issues/1919
https://github.com/QubesOS/qubes-issues/issues/2766

**Comment by andrewdavidwong** [comment]
I appreciate the effort and intention to be helpful. However, I suggest posting this in the [forum](https://qubes-os.discourse.group/) rather than qubes-issues. In order to keep qubes-issues useful as a practical day-to-day tool for the devs, our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/) require that [every issue must be about a single, actionable thing](https://www.qubes-os.org/doc/reporting-bugs/#every-issue-must-be-about-a-single-actionable-thing), and this issue does not appear to satisfy that requirement. However, the forum has no such requirement. Like GitHub issues, the forum also facilitates discussion and allows you to update your post. It supports additional features that may be beneficial for this type of use case. Therefore, the forum would be more a more appropriate venue for this post. Thank you for your understanding.
