### ISSUE TITLE
Salt: Skipping non-targeted VMs is unreasonably slow

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#6144]
**Qubes OS version**

4.0

**Affected component(s) or functionality**

qubesctl

**Brief summary**

Skipping non-targeted VMs is unreasonably slow as it takes 2-3s per VM.

**To Reproduce**

Assuming you use salt:
1. Enable top files or use a single top file that targets only a few of your VMs.
2. `sudo qubesctl --show-output --all state.highstate`

**Expected behavior**

VMs that are not targeted are skipped within few hundreds of milliseconds.

**Actual behavior**

VMs that are not targeted are reported one at a time, _each_ requiring 2-3s to report `[vm]: SKIP (nothing to do)`.

So for 100 VMs a user may be waiting 200-300s just to see skip messages. Combining all top file targets and checking them against a single VM list shouldn't take that long.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/salt/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

-

**Comment by lkubb** [comment]
Imho this is still a bug in 4.2rc4, nothing has changed about the check being done synchronously:

https://github.com/QubesOS/qubes-mgmt-salt/blob/780e0ef09c6c83cdd301a32d256bc6263c573596/qubessalt/__init__.py#L292-L302

I assume the reason was that the `state` module by default will error if called while another instance is running (even for `state.show_top`), but that can be overridden by passing `concurrent=true`. This would make moving the check into `run_one` possible, thereby parallelizing it.
