### ISSUE TITLE
Grsecurity in HVM mode doesn't work

### ISSUE THREAD

**Issue by DrWhax** [QubesOS/qubes-issues#6159]
**Qubes OS version**

R4

**Affected component(s) or functionality**

In HVM mode, homegrown built grsecurity kernels aren't booting.

**Brief summary**

While booting a VM with kernel set to none and type set to HVM it won't boot, I only see a /var/log/xen/console/guest-xxx-dm.log with errors in the stubdomain kernel.

**To Reproduce**

1. Compile a grsecurity kernel with grsec support + Xen HVM/PVH support , in this case: 5.4.71-grsec
2. sudo dkms autoinstall -k 5.4.71-grsec
3. Boot up an HVM kernel as 'none' and it won't load.

**Expected behavior**

HVM boots fine without the stub domain kernel crashing.

**Actual behavior**

Won't boot.

**Screenshots**

**Additional context**

Attached I have my -dm crash log of the VM in question.
[guest-signal1-dm.log](https://github.com/QubesOS/qubes-issues/files/5448093/guest-signal1-dm.log)

Attached as well is my kernel config [config-5.4.71-grsec.txt](https://github.com/QubesOS/qubes-issues/files/5448113/config-5.4.71-grsec.txt)

**Solutions you've tried**

Making sure u2mfn module is loaded in, but the same kernel boots fine in PVH mode.

Deleting all the other kernels in question and only two remaining are 2 grsec kernels for which I installed u2mfn modules just fine.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

- https://github.com/QubesOS/qubes-issues/issues/5212
- https://www.qubes-os.org/doc/managing-vm-kernel/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

-

**Comment by marmarek** [comment]
Stubdomain kernel is fine, those warnings are harmless and are result of very minimal config there.
The message at the end (`qemu: pin_memory_cacheattr failed: Operation not permitted`) is slightly worrying, but I don't think it's fatal.

This is most likely some grsec incompatibility with Xen HVM, or some specific to the config you set. Sadly, since grsecurity patches are no longer publicly available, we can't help you much here.
Few hints:
 - make sure grub is installed on /dev/xvda (if you started with standard template, it should be there already, but not if you started with minimal)
 - make sure kernel log is printed to the console - no "quiet" option, but "console=hvc0" present and maybe add "earlyprintk=xen"
 - try enabling grsecurity features one by one

**Comment by DrWhax** [comment]
Thanks! Will play some more and let you know how far I come!

**Comment by andrewdavidwong** [comment]
> This is most likely some grsec incompatibility with Xen HVM, or some specific to the config you set. Sadly, since grsecurity patches are no longer publicly available, we can't help you much here.

It sounds like this should be closed as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
