### ISSUE TITLE
Backups with a single archive per VM (or, only backup VM's modified since last backup)

### ISSUE THREAD

**Issue by afk11** [QubesOS/qubes-issues#6169]
**The problem you're addressing (if any)**

I take frequent full system (or there abouts) backups. Over time, I want to delete VM's from my host system, knowing I have a backup somewhere and can easily restore it. When the backups are in a single archive, it's hard to know what VM's are inside so I tend to keep them all. But I'd like to be able to go through a backup and delete VM's I have in more recent backups, so I can keep the 'last backup of VM XYZ' safe

**Describe the solution you'd like**

Make it easier to isolate a single VM from backups

**Where is the value to a user, and who might that user be?**

People who create project VM's, use them for a few months, delete them, but might want to load them later. They don't want to keep every full backup.

**Describe alternatives you've considered**

Two possible solutions to this:
 - add a mode where qubes creates an encrypted backup file *per VM*, so VM's with more recent backups can be deleted
 - add a feature 'backup modified qubes' to the backup process, so only qubes modified since the last backup are included in the backup, but also generate print a file of the VM's in the backup

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Possibly the sparsebak thread?

**Comment by GWeck** [comment]
If there is just one VM in a backup, it might be helpful to enter the name of that VM as part of the backup file name, e.g. qubes-backup-2020-08-17T124831 (Fedora-32). Or, a possibility to specify the name of the backup file, when slecting the target directory.

**Comment by andrewdavidwong** [comment]
> Two possible solutions to this:
> 
> * add a mode where qubes creates an encrypted backup file _per VM_, so VM's with more recent backups can be deleted

This already exists. It's simply `qvm-backup` with a single specified VM to back up. You can script this, if you want, to loop over a list of VMs.

My sense is this is not a mainstream use case. Wanting separate backup files per VM sounds like something that would be an inconvenience to mainstream users but something that a power user might want for a custom DIY setup. Since you can already do this yourself, and since the additional complexity would probably not serve most users, I'm skeptical about this feature.

> * add a feature 'backup modified qubes' to the backup process, so only qubes modified since the last backup are included in the backup, but also generate print a file of the VM's in the backup

This sounds like a cruder version of proper incremental backups (#858), so I'm also skeptical about this proposed feature.

Given these considerations, I'm going to close this issue as "won't do." However, I'm happy to be overturned if the Qubes devs disagree. In addition, if anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by andrewdavidwong** [comment]
> If there is just one VM in a backup, it might be helpful to enter the name of that VM as part of the backup file name, e.g. qubes-backup-2020-08-17T124831 (Fedora-32). Or, a possibility to specify the name of the backup file, when slecting the target directory.

In fact, this is exactly what I do for the precise use case described in the original feature request. When I want to delete a VM but have the option of restoring it later, I simply create a backup that contains only that VM and name it appropriately, e.g., VM name and date. Often, I find that I don't even need the date, because I have only one file with that VM's name in the filename (all previous backups having contained multiple VMs).

**Comment by andrewdavidwong** [comment]
Forum thread: https://qubes-os.discourse.group/t/backups-with-a-single-archive-per-qube/1328/

**Comment by donob4n** [comment]
Ey, since I'm thinking on add some functionality to Qube Manager, maybe an option in context menu for directly backup a Qube could hep on this.

Also, since last Qube Manager support multiple selection, you could select a group of Qubes and directly backup them.

Respect the part for search a Qube or delete an unneeded old backup, an solution could be to write an optional backup summary file with the names of the content inside (names, date, size...), so you can easily see the content of the backup with any text editor.
