### ISSUE TITLE
Archlinux build failure due to pulseaudio 13.99.3

### ISSUE THREAD

**Issue by icequbes1** [QubesOS/qubes-issues#6172]
**Qubes OS version**
R4.1, R4.0 (untested)

**Affected component(s) or functionality**
qubes-gui-agent-linux

**Brief summary**
Archlinux build failure of qubes-gui-agent-linux due to Archlinux using pulseaudio 13.99.3 as of October 31 2020.

**To Reproduce**

1. Build archlinux template

**Expected behavior**
Successful template creation.

**Actual behavior**
Template build failure in qubes-gui-agent-linux.

**Additional context**
`pulsecore/pulse` gets linked to pulsecore-13.99.3, which does not [yet] exist in the repo. Archlinux has pushed pulseaudio 13.99.3 as of October 31 2020.

**Screenshots**
![pulse](https://user-images.githubusercontent.com/71958531/97792342-1370b880-1b9a-11eb-9743-d7cb12d6ffbd.png)

**Solutions you've tried**
Symlink 13.99.3 to 13.99.2 header; build succeeds, basic sanity checks for audio succeed. PR coming.

**Comment by ptitdoc** [comment]
I confirm this problem and the solution works for me.

Also the current dependency on archlinux is:
`depends=( 'alsa-lib' 'alsa-utils' 'pulseaudio-alsa' 'pulseaudio<14.0')`

is not restrictive enough because 13.99.3 being < 14.0 qubes-vm-pulseaudio will be hapilly updated but will break sound.

I would prefer more restrictive version dependencies so that users know that they will break sound if they force update the package. Maybe something like that:
`depends=( 'alsa-lib' 'alsa-utils' 'pulseaudio-alsa' 'pulseaudio=13.99.3')`

What is pulseaudio policy regarding API compatibility ? Is it possible to base ourselves on minor version numbers ? such as 13.99 ?

**Comment by marmarek** [comment]
> What is pulseaudio policy regarding API compatibility ? Is it possible to base ourselves on minor version numbers ? such as 13.99 ?

Hard to say, those seems to _not_ be official releases, but rather some development snapshots. TBH I have no idea why they are shipped as stable packages, but since many distributions do that, there is probably some reason.

**Comment by icequbes1** [comment]
Closing this as it was resolved, and is now succeeded by #6234.
