### ISSUE TITLE
Decouple routing from firewalling / Allow Firewall VM != NetVM / Support passive network proxies

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#6195]
**The problem you're addressing (if any)**

Qubes OS implements its firewall rules at the next downstream netvm.

**Describe the solution you'd like**

Qubes OS supports implementing the firewall rules at any downstream netvm picked by the user, defaulting to the next downstream netvm. The routing still happens inside the next downstream netvm.

This could be implemented as either a firewall VM property holding a VM name similar to the current netvm property or as an opt-out boolean property such as "do not use this proxy VM as firewall, but use the next one".
The latter might cause less configuration overhead.

**Where is the value to a user, and who might that user be?**

Passive network sniffing, IPS (intrusion prevention system), network analysis, ... functionality running in dedicated proxy VMs becomes possible.

**Describe alternatives you've considered**

Currently it is possible as such: `sys-net -- IPS -- sys-fw -- AppVM`

Unfortunately that won't make the IPS see any traffic dropped by a firewall. This traffic however is mostly interesting as it may e.g. show malware attempts contacting CnC servers, but failing at a restrictive `sys-fw`.

So in order to see all traffic one would go with: `sys-net -- sys-fw -- IPS -- AppVM`

Then however Qubes OS will implement its firewall rules on the IPS which may interfere with its behaviour and also breaks the compartmentalization idea (i.e. makes `sys-fw` pointless).

So the only thing one can currently do is to implement the IPS inside `sys-fw`, breaking the compartmentalization idea, or live with the fact that the IPS doesn't see all traffic (e.g. as per http://zrubi.hu/en/2017/traffic-analysis-qubes/).

Ideally, one could go with `sys-net -- sys-fw -- IPS -- AppVM`, but pick `sys-fw` as the firewall VM for `AppVM` anyway. That's what this feature request is about.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/networking/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None.

**Comment by andrewdavidwong** [comment]
> So in order to see all traffic one would go with: `sys-net -- sys-fw -- IPS -- AppVM`
> 
> Then however Qubes OS will implement its firewall rules on the IPS which may interfere with its behaviour

Alternatively, you could declare the firewall rules for the IPS VM so that they're enforced in `sys-fw`.

> and also breaks the compartmentalization idea (i.e. makes `sys-fw` pointless).
> 
> So the only thing one can currently do is to implement the IPS inside `sys-fw`, breaking the compartmentalization idea

You could create a second sys-fw just for this purpose:

```
sys-net -- sys-fw* -- sys-fw-ips -- AppVM
```

*Optional

**Comment by 3hhh** [comment]
> > So in order to see all traffic one would go with: `sys-net -- sys-fw -- IPS -- AppVM`
> > Then however Qubes OS will implement its firewall rules on the IPS which may interfere with its behaviour
> 
> Alternatively, you could declare the firewall rules for the IPS VM so that they're enforced in `sys-fw`.

Indeed that's possibly the best approach right now, thanks!

It's essentially the manual variant of what I suggested and only has the drawback that firewall rules do not stick to their VMs  anymore, but to their network VMs. This then makes network "re-wirings" more error-prone, but still feasible.
 
> > and also breaks the compartmentalization idea (i.e. makes `sys-fw` pointless).
> > So the only thing one can currently do is to implement the IPS inside `sys-fw`, breaking the compartmentalization idea
> 
> You could create a second sys-fw just for this purpose:
> 
> ```
> sys-net -- sys-fw* -- sys-fw-ips -- AppVM
> ```
> 
> *Optional

Yes, but the IPS application would then still either run inside sys-fw-ips or between sys-fw and sys-fw-ips inside a dedicated VM leading to the aforementioned issues.

**Comment by marmarek** [comment]
On Tue, Nov 10, 2020 at 01:08:43PM -0800, 3hhh wrote:
> > > So in order to see all traffic one would go with: `sys-net -- sys-fw -- IPS -- AppVM`
> > > Then however Qubes OS will implement its firewall rules on the IPS which may interfere with its behaviour
> > 
> > Alternatively, you could declare the firewall rules for the IPS VM so that they're enforced in `sys-fw`.
> 
> Indeed that's possibly the best approach right now, thanks!
> 
> It's essentially the manual variant of what I suggested and only has the drawback that firewall rules do not stick to their VMs  anymore, but to their network VMs. 

Yes, this is fundamental problem with your proposed solution. Only the
direct upstream VM (IPS in the example above) knows from where the
traffic comes.
There are two reasons for that:

1. Technical one: each intermediate VM does NAT, to avoid the need to
reconfigure the whole network chain when changing just one VM settings
(which also covers various corner cases like VPN or Tor, where simple
routing table change wouldn't be the right thing to do).

2. Conceptual one: any non-directly connected VM would need to trust the
directly connected one regarding traffic source information. Depending
on the threat model, this may or may not be desirable. Additionally, not
doing NAT would leak source VM info to potentially untrusted VMs on the
network chain (in practice, it may still be possible to guess the source
based on the traffic itself, but it is significantly less accurate).
This may be also privacy issue in case of VPN/Tor (in this case, you
leak not via the actual traffic but by added routing table entries).

So, by applying firewall anywhere else than direct upstream VM, you
loose ability to configure different rules for different VMs. If you're
fine with that, then the solution for your setup is to configure
firewall rules for IPS VM, to be enforced by sys-fw - as Andrew
proposed.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
Ok, it sounds like this is a "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
