### ISSUE TITLE
Move templates from qubes.3isec.org to ftp.qubes-os.org

### ISSUE THREAD

**Issue by cobordism** [QubesOS/qubes-issues#6201]
**Qubes OS version (if applicable)**
Qubes 4.0

**Affected component(s) or functionality (if applicable)**
Templates

**Brief summary**
I'd like to experiment with different templates. 
There are some templates here: https://ftp.qubes-os.org/repo/yum/r4.0/templates-community/rpm/
and there are others here: http://qubes.3isec.org/Templates_4.0/

**Additional context**
The additional templates I mentioned are allegedly by @unman 
It would be nice if they could be hosted on the official ftp.qubes server and signed by appropriate keys - that would make them easier to trust

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
This tells us how to install 'community' templates: https://www.qubes-os.org/doc/templates/#community
It does not mention @unman's templates on 3isec

**Comment by unman** [comment]
On Sun, Nov 15, 2020 at 02:10:33PM -0800, Aron wrote:
> **Qubes OS version (if applicable)**
> Qubes 4.0
> 
> 
> 
> **Affected component(s) or functionality (if applicable)**
> Templates
> 
> 
> **Brief summary**
> I'd like to experiment with different templates. 
> There are some templates here: https://ftp.qubes-os.org/repo/yum/r4.0/templates-community/rpm/
> and there are others here: http://qubes.3isec.org/Templates_4.0/
> 
> 
> **Additional context**
> The additional templates I mentioned are allegedly by @unman 
> It would be nice if they could be hosted on the official ftp.qubes server and signed by appropriate keys - that would make them easier to trust
> 
> 
> 
> **Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
> This tells us how to install 'community' templates: https://www.qubes-os.org/doc/templates/#community
> It does not mention @unman's templates on 3isec
> 
> 
> 

The "allegedly" issue is resolved because I sign all templates (and
packages) that are hosted there.
So you can confirm that easily enough.

The Ubuntu templates I put up cant be hosted by Qubes officially
because of licensing concerns about distributing Ubuntu.
Other templates hosted there are either one offs or produced for
specific purposes: I don't know if they warrant official endorsement.
Some of them (e.g. Arch) are moving in to official hosting.

At best, it might be possible to include a reference to the 3isec
source in the documentation.

**Comment by andrewdavidwong** [comment]
The idea of creating a third category of templates (aside from Official and Community) makes me uncomfortable. Users might find this confusing and not be sure what the difference is between "Community" and this new third category, and that would increase our support requirements. It might also entail more infrastructure overhead (@marmarek would be able to say more about this).

I think it's very kind of @unman to create and host these templates. If he wants some of them (e.g., Arch Linux) to become Community templates, then it looks like that's already happening. If he just wants to create some experiments or one-offs and let other tinkerers have access to them, I don't see why that has to be subsumed by the official Qubes OS Project infrastructure. I think it's fine and healthy for the Qubes ecosystem to extend beyond the borders of official Qubes OS Project infrastructure.

As for documenting it, I'd be inclined to direct this to the community documentation (https://github.com/Qubes-Community), since it seems to me that @unman is doing this as a private individual, not in his official capacity as a core Qubes team member. Likewise, we don't want to commit to documenting every last Qubes enthusiast's personal website in the official docs.

**Comment by unman** [comment]
On Sun, Nov 15, 2020 at 09:50:22PM -0800, Andrew David Wong wrote:
> The idea of creating a third category of templates (aside from Official and Community) makes me uncomfortable. Users might find this confusing and not be sure what the difference is between "Community" and this new third category, and that would increase our support requirements. It might also entail more infrastructure overhead (@marmarek would be able to say more about this).
> 
> I think it's very kind of @unman to create and host these templates. If he wants some of them (e.g., Arch Linux) to become Community templates, then it looks like that's already happening. If he just wants to create some experiments or one-offs and let other tinkerers have access to them, I don't see why that has to be subsumed by the official Qubes OS Project infrastructure. I think it's fine and healthy for the Qubes ecosystem to extend beyond the borders of official Qubes OS Project infrastructure.
> 
> As for documenting it, I'd be inclined to direct this to the community documentation (https://github.com/Qubes-Community), since it seems to me that @unman is doing this as a private individual, not in his official capacity as a core Qubes team member. Likewise, we don't want to commit to documenting every last Qubes enthusiast's personal website in the official docs.
> 

Agree on all counts

**Comment by DemiMarie** [comment]
As far as the Ubuntu templates, could we have an RPM package that, when installed, builds the template from source code?

**Comment by unman** [comment]
On Mon, Nov 16, 2020 at 07:18:31AM -0800, Demi Marie Obenour wrote:
> As far as the Ubuntu templates, could we have an RPM package that, when installed, builds the template from source code?
> 
> -- 

Will you write that?
The difficulties I see are pointing dom0 at Ubuntu repositories and
using debootstrap in dom0 or selected proxy.
And after that, I dont think that would be enough to override the IP
ojections. (I've said before it would have been *much* better if that
bottle hadnt been opened at all: but it has, and we have to live with
the consequences.)

I always suggest that people use Qubes Builder to build their own
templates - it should be straightforward, much easier than people seem
to think.

**Comment by DemiMarie** [comment]
@unman which bottle are you talking about?

**Comment by marmarek** [comment]
Take a look at first section of https://www.qubes-os.org/doc/templates/ubuntu/

**Comment by unman** [comment]
On Mon, Nov 16, 2020 at 07:00:18PM -0800, Demi Marie Obenour wrote:
> @unman which bottle are you talking about?
> 

The bottle containing the Ubuntu IP genie.
Once that was out, we cant put it back. Better not to have opened that
can of worms, (to mix some metaphors).

**Comment by andrewdavidwong** [comment]
It looks like the consensus is that this is a "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by cobordism** [comment]
I have to admit, this whole issue was born more of frustration than anything else.
I found that I needed an updated package that was not available in any of the provided templates and I repeatedly failed at making my own templates or upgrading in place. All instructions/documentation I followed invariably led to either compilation errors or bricked templates... I've lost three days trying to get it to work, and as a result I was left wishing for more up-to-date templates to be readily available.

I fully understand your reasoning though and agree with your decision.
