### ISSUE TITLE
Sum of all thin volumes exceeds limit. Critical Boot Issue

### ISSUE THREAD

**Issue by Jenn145** [QubesOS/qubes-issues#6214]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

Booting/Running the OS entirely

**Brief summary**

Following initial boot of the computer, and entering of the FDE login info, I'm met with an dracut emergency prompt errors pertaining to this known issue:
https://github.com/QubesOS/qubes-issues/issues/5372
https://github.com/QubesOS/qubes-issues/issues/5160

And a new then a new issue following the use of a previous proven repair method, leading to new additional dracut emergency prompt errors.

**How Reproducible**

Every time I boot computer and enter Qubes FDE login info.

**To Reproduce**

1. 1. Turn on computer, enter FDE login info, allow dracut emergency prompt to finalize emiting errors
2. Use known working method for repairing the errors as commented here by "notbyosmosis": https://github.com/QubesOS/qubes-issues/issues/5160
3. Allow dracut emergency prompt to output errors following second use of "lvconvert --repair qubes_dom0/pool00"

**Expected behavior**

Regular boot of Qubes OS

**Actual behavior**

dracut emergency prompt errors pertaining to this known issue:
https://github.com/QubesOS/qubes-issues/issues/5372
https://github.com/QubesOS/qubes-issues/issues/5160

And a new then a new issue following the use of a previous proven repair method, leading to new additional dracut emergency prompt errors.

**Screenshots**

**Additional context**

This issue is critical as one of my backups is corrupted, and the other is lost.

I have been using Qubes for a little while now, and am dealing with a critical issue. After entering FDE login info, the boot-bar loads very slowly before entering an dracut emergency prompt and displaying:

Warning: dracut-initqueue timeout - starting timeout scripts

Warning: dracut-initqueue timeout - starting timeout scripts

Warning: dracut-initqueue timeout - starting timeout scripts

Warning: Could not boot.

Warning: /dev/mapper/qubes_dom0-root does not exist

Warning: /dev/qubes_dom0/root does not exist

I have fixed this issue once in the past with the following steps:

    At the Dracut emergency prompt, I ran:

lvm

vgscan

vgchange -ay

This informed me that there was an issue with activating qubes_dom0/pool00.

At this point, I tried:

lvconvert --repair qubes_dom0/pool00

I received the following error:

Read-only locking type set. Write locks are prohibited.

Can't get lock for qubes_dom0

cannot process volume group qubes_dom0

I exited back to the dracut prompt, and temporarily edited the /etc/lvm/lvm.conf file.

I found the following line:

locking_type=4

and changed it to:

locking_type=1

2) I then retried the lvconvert command:

lvm

lvconvert --repair qubes_dom0/pool00

It worked! Recived a couple of warnings.

I then re-ran the following:

vgscan

vgchange -ay

I then exited back to the dracut prompt and edited the /etc/lvm/lvm.conf file, and changed the locking_type option back to what it was before:

locking_type=1

changed it back to:

locking_type=4

I then rebooted.

QubesOS came up.

For this second occurance of the issue, I attempted the previously used repair method, but received issues following step 2 , the errors displayed:

lvm> lvconvert --repair qubes_dom0/pool00

Using default stripesize 64.00 KiB.

WARNING: Sum of all thin volume sizes (1.10 TiB) exceeds the size of thin pools and the size of whole volume group (930.51 GiB)!

For thin pool auto extension activation/thin_pool_autoextend_threshold should be below 100.

Transaction id 4764 from pool "qubes_dom0/pool00" does not match repaired transaction id 4763 from /dev/mapper/qubes_dom0-lvol0_pmspare.

WARNING: recovery of pools without pool metadata spare LV is not automated.

WARNING: If everything works, remove qubes_dom0/pool00_meta1 volume.

WARNING: Use pvmove command to move qubes_dom0/pool00_tmeta on the best fitting PV.

lvm>

(side note.. after completing the repair method the first time the error occured, an black icon/connection in sys-usb appeared and became present in every session. The connection option was named something like: "qubes_dom0/pool00_metadata")

I have limited knowledge and experience with linux, however I can't imagine I have 1.10 TiB worth of VMs/data in this installation of Qubes. I think theres something up with the metadata pool that got split into a USB option, but I could easily be off.

Please help me out if you can, I can't lose the progress I have made and am nervous messing around in the emergency prompt.

**Solutions you've tried**

Repair method as commented here by "notbyosmosis": https://github.com/QubesOS/qubes-issues/issues/5160

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://github.com/QubesOS/qubes-issues/issues/5160
https://github.com/QubesOS/qubes-issues/issues/5372
https://github.com/QubesOS/qubes-issues/issues/3810
https://github.com/QubesOS/qubes-issues/issues/3133
https://github.com/QubesOS/qubes-issues/issues/5372

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/5160
https://github.com/QubesOS/qubes-issues/issues/5372

**Comment by andrewdavidwong** [comment]
This report is kind of hard to understand.

> dracut emergency prompt errors pertaining to this known issue:
> #5372
> #5160
> 
> And a new then a new issue following the use of a previous proven repair method, leading to new additional dracut emergency prompt errors.

It sounds like _maybe_ this is just a continuation of one of those bugs, in which case this should be posted as a comment on one of those issues rather than filed as a separate bug report.

**Comment by Jenn145** [comment]
I will not be removing this post, as I have yet to get help on mulitple other forums. I will post in the comments of the github posts, as you requested but please leave this post up. I'm in dire need of rescuing my OS.

**Comment by DemiMarie** [comment]
What is the output of `lvm lvs`?  In any case, this would be better suited to the [qubes-users mailing list](mailto:qubes-users@googlegroups.com).

**Comment by andrewdavidwong** [comment]
> I will not be removing this post, as I have yet to get help on mulitple other forums.

I'm sorry, but [qubes-issues is not a place for getting individual help or support](https://www.qubes-os.org/doc/reporting-bugs/). Rather, the purpose of this issue tracker is to track general bugs, enhancements, and tasks in the software itself. In other words, this is a tool to assist the Qubes developers in doing their work, not a forum for users to receive assistance. We do, however, have [places where you can ask for help and support](https://www.qubes-os.org/support/).

> I will post in the comments of the github posts, as you requested

I think there's a misunderstanding. The point is not to ask for help on every issue where it might be relevant. That just makes this tool less effective for the Qubes developers.

> I'm in dire need of rescuing my OS.

I empathize with your situation, and if I had the knowledge to help you, I would (over in one of the [appropriate venues](https://www.qubes-os.org/support/)). At the same time, since you are so adamant, I feel the need to clarify a few things. I will speak frankly so that there is no misunderstanding. Some of this you may not want to hear right now, but please take it in the spirit in which it is intended.

First, remember that Qubes is free and open-source software. This means that it was provided to you "as is" for free, and you are not guaranteed any particular outcome. No one is _obligated_ to take time out of their own lives to help you, but most of us _want_ to anyway.

Second, in your report, you stated, "This issue is critical as one of my backups is corrupted, and the other is lost." As much as it pains me to say this: These are self-inflicted wounds. In the documentation, we clearly state, ["It’s extremely important to make regular backups of all the data you care about. This is true of all computing, not just the use of Qubes. Data loss can and does occur in myriad and unexpected ways. A standard recommendation is to make backups at least weekly: three copies in two different formats, one off-site."](https://www.qubes-os.org/doc/backup-restore/) Frankly, we didn't have to say this at all, because it's just common knowledge about computing in general, not even remotely Qubes-specific. But we said it anyway, because we genuinely don't want our users to lose their data, and we know that most people have pretty bad backup practices. It's not just that we one line, either. We urge you to practice good backup practices throughout the documentation, beginning right with the [installation guide](https://www.qubes-os.org/doc/installation-guide/#backups).

Moreover, we state that the final step of the backup procedure is: ["Test restore your backup. Follow the restore procedure, selecting **Verify backup integrity, do not restore the data**. This step is optional but strongly recommended. A backup is useless if you can’t restore your data from it, and you can’t be sure that your backup is good until you try to restore."](https://www.qubes-os.org/doc/backup-restore/#creating-a-backup) If you had followed this step, you would have a working backup. I say this not to rub salt in the wound, because most of us have been where you are, but to point out the reality that keeping good backups of your data is no one's responsibility but your own, and the failure to do so by an individual user should not cause any particular bug report to have a critical priority for the entire project or company building that software. (This is true of software in general, including proprietary software.)

Again, I reiterate that I empathize with your situation and sincerely hope you get the help you need. However, we have to think about the well-being of the entire project and _all_ Qubes users. We have a system in place for users to ask for help, and there are many good members of our community there who _want_ to help, so please read the [support](https://www.qubes-os.org/support/) page and follow the guidelines there.
