### ISSUE TITLE
System76 Adder WS doesn’t boot

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6215]
**Qubes OS version**

`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**

Graphics

**Brief summary**

Booting R4.0 on a System76 Alder WS does not work.  R4.1 works fine.

**How Reproducible**

100%

**To Reproduce**
Boot R4.0 on a System76 Alder WS

**Expected behavior**

System boots normally

**Actual behavior**

The screen goes black as soon as Xen gives up the VGA console

**Screenshots**

**Additional context**

This is probably a kernel problem.

**Solutions you've tried**

R4.1 works, but as it is still alpha I don’t want to use it as my daily driver.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by dephekt** [comment]
I ran into this today and can reproduce it on 4.0.4-rc2 and 4.0.3. I can also confirm things work on 4.1 alpha. However, I'm at a loss on how to diagnose the issue since there's no UEFI boot menu to enable verbose troubleshooting boot-up and when the issue happens the laptop powers off completely. If anyone has any ideas I'm happy to help diagnose the problem. I could build 4.0.4-rc2 or 4.0.3 myself if there's something in builder.conf I can configure to enable more verbose messages or better enable diagnostics here.

**Comment by DemiMarie** [comment]
Culprit is almost certainly the old kernel version in the R4.0 install ISO.  Since 4.0.4-rc2 doesn’t work that means that a very recent kernel is probably required.  Additionally, I am not sure if the built-in display is attached to the Nvidia or Intel GPU.  If the former, then I would not be surprised if the laptop simply cannot be used without the Nvidia proprietary driver, which QubesOS will never ship.

**Comment by dephekt** [comment]
> I would not be surprised if the laptop simply cannot be used without the Nvidia proprietary driver, which QubesOS will never ship
All I can say there is that I've used it without the proprietary Nvidia driver installed, using just integrated graphics. How things are hooked up behind the scenes I can't speak on, though. E.g. a default install of Ubuntu or Fedora work fine without having the Nvidia blobs installed.
