### ISSUE TITLE
Qubes Update tool extends below edge of screen; buttons not visible

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6221]
**Qubes OS version**

4.0

**Affected component(s) or functionality**

Qubes updater

**Brief summary**

The update window has no scrollbar.
With a large number of templates, the update window is full, and the buttons are hidden below the edge of the screen.

**How Reproducible**

100%

**To Reproduce**
1. Have a large number of templates.
2. Launch the update tool
3. 

**Expected behavior**

List will be scrollable. Buttons will always be accessible.

**Actual behavior**

Window extends below bottom of screen.
Buttons are hidden

**Screenshots**

**Additional context**

Using KDE 

**Solutions you've tried**

Possible to move the window up beyond top of screen (Alt+move) so that buttons are available.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by DemiMarie** [comment]
How many templates do you have?  10 doesn’t seem to be enough, at least with XFCE.

**Comment by GWeck** [comment]
With XFCE, the window is enlarged if new templates are added, but it has no scrollbar. For me 20 templates are shown, and if I add one more template, the window is enlarged accordingly. The buttons are shown in any case.

I have no idea, how many templates are needed under XFCE to make it break.

**Comment by unman** [comment]
On Sat, Nov 21, 2020 at 08:14:14PM -0800, Demi Marie Obenour wrote:
> How many templates do you have?  10 doesn???t seem to be enough, at least with XFCE.
> 

I have tested with Xfce and this also applies there.
How would 10 be enough? That's not going to create a large enough
window, unless you have a tiny screen.
Currently 36 on this machine: a standard x230 with 1366x768.

**Comment by DemiMarie** [comment]
I just thought that 10 was a lot of templates.

**Comment by jamke** [comment]
Note: it is **not about being not optimized** but about **`Qubes Updater` being COMPLETELY UNUSABLE** if one have enough appvms. Because buttons are not visible and there is no way for average user to press them. I'm asking to increase priority of the issue because of this. Also the bug fix seems to be super-easy for one who develops these forms (adding scrollbar as in Qubes backup windows).


> I just thought that 10 was a lot of templates.

Not at all. Even one single VPN requires 4 appvms according to documentation. And one can use a lot of templates with different amount of software (from minimal to super-full) and etc. And one can create appvms with per application approach. It all leads to 30+ appvms instantly.
I'm sure a lot of users have more than 30 appvms but those users are more likely not to participate in polls and Qubes surveys though, so you don't see them much.

**Comment by marmarek** [comment]
> Even one single VPN requires 4 appvms according to documentation

Templates in Qubes OS are specifically to let you install updates once, for a group of VMs. You can create StandaloneVMs for some specific use cases, but using separate template (or standalone vm) for _every_ appvm sounds like you're doing something wrong.

**Comment by brendanhoar** [comment]
Re: lots of templates...

hmm 

I keep a backup of each template to roll back recent problematic updates after getting burned without backups in the past (when burned I used rpm to create a new template and then hunted for all of the customizations I’d already made to the bad template). :(

So that automatically double the number of templates I keep.

I also keep some harder-to-fingerprint templates around that are, essentially, as delivered by the qubes repo and depending upon use case, some get fully updated prior to use with a new (usually disposable) VM, others aren’t updated at all before use with a new VM.

Linux users might have several different template configs: (Debian vs Fedora vs ....), different Qubes builds (minimal, standard) different versions (9, 10, 31, 32, 33), and different uses (standard config, multimedia config, security config).

Windows users might have 5 or so core Windows templates by version (7,8,10,various server versions) under several different spins (workstation, ultimate, core, home, ltsb, ltsc), and customized with apps for different target uses.

Sure, some of the templating overlaps with using flatpack/portable apps/etc., but not all.

I don’t think a scrollbar or other GUI widget that doesn’t assume a short list of templates is too much to ask.

<the soap box is now free>,
Brendan
