### ISSUE TITLE
Restore Backup failings

### ISSUE THREAD

**Issue by jimi3** [QubesOS/qubes-issues#6227]
**Qubes OS version**
R4.0.3 & R4.0.4rc1

**Affected component(s) or functionality**
Restore Backup

**Brief summary**

_failed to decrypt /var/tmp/restorej3aq3bth/vm37/root.img.001.enc:b'scrypt:Passphrase is incorrect\n
Partially restored files left in /var/tmp/restore_*,investigate them and/or clean them up_

1. Fresh install in R4.0.4rc1, run updates prior to restore backup, when i saw this error.
2. Wiped Qubes and installed Qubes R4.0.3 but same error.
3. First restored everything except dom0, and the default Templates and AppVMs, i do need a AppVM to cifs mount NAS drive to restore the Backup.
4. vm37 was a debian-10-printer-dvm Template
5. All VM's are listed as restored in Qubes Manager
6. Turns out that some restored Appvm's were blank as in nothing of my previous doings was restored, others 'seem' to have everything.
7. Some VM's are not even able to start up, "_failed to start:qrexec-daemon startup failed_: Connection to the VM failed"
8. Deleted one of these broken restored AppVM's and this time restored just this one again with success and data showing up this time.
9. Restoring just vm37 does not succeed though, this one didn't make the backup at all.

**How Reproducible**
not sure

**Expected behavior**
Restore with Users generated AppVM content if Passphrase is correct

**Actual behavior**
Partially restored with Users generated AppVM content and wrongly message User that Passphrase is incorrect.

**Additional context**
Verify backup function?

**Solutions you've tried**
fresh new installs of r4.0.3 & r4.0.04rc1, kernel-latest

**Comment by andrewdavidwong** [comment]
You omitted the steps to reproduce, which makes certain details unclear. Please provide the exact steps you performed.

-----

> vm37 was a debian-10-printer-dvm Template

I wonder if it might be due to the printer device assigned to this VM (similar to #6083, perhaps). Were the backup and restore done on the exact same hardware?

-----

> Verify backup function?

Yes, there is one. In the restore GUI, it's called "Verify backup integrity, do not restore the data".

**Comment by jimi3** [comment]
> You omitted the steps to reproduce, which makes certain details unclear. Please provide the exact steps you performed.

Not sure what say here, it was a full Qubes OS Backup that i used that lead to this problem. The Backup was taken with r4.0.3 kernel-latest Qubes OS two weeks ago.
I would need to create a new full OS Backup and try to restore it on a fresh install to maybe reproduce this problem.
Please advice if i misunderstood you.


> I wonder if it might be due to the printer device assigned to this VM (similar to #6083, perhaps). Were the backup and restore done on the exact same hardware?

Same PC, only change in hardware is from 500GB ssd to an 500GB nvme drive.


> Yes, there is one. In the restore GUI, it's called "Verify backup integrity, do not restore the data".

It would be great if this was a default option to use right after writing the backup. Somehow i was under the impression a verify was being done with each backup.

**Comment by andrewdavidwong** [comment]
> It would be great if this was a default option to use right after writing the backup. Somehow i was under the impression a verify was being done with each backup.

There's an open issue for this: #1454

**Comment by jimi3** [comment]
Used a previous Backup and was able to restore the debian-10-printer-dvm template, worked like a charm.
Made a new encrypted backup to my local NAS which i just finished verifying successfully, i was not able to reproduce this error.

> There's an open issue for this: #1454

Thank you.

**Comment by SvenSemmler** [comment]
Ok, I am hitting the same issue with multiple qubes. Migrating from ThinkPad P51 to T430. I tried for two days with different backup media. Backing up on the P51 and restoring on the T430. Over and over I would see the "b'scrypt:Passphrase is incorrect" issue ... mostly close to the end of the restore. Some qubes seem to work other don't.

So I ended up recreating all my templates using the bash script I made for their automatic creation (boy did that effort pay for itself!) and then manually moving the actual user data from the source to the freshly created target qubes.

However there is one qube I can't move this way: a 100GB Windows 10 HVM with all kinds of corporate stuff in it. Recreating that one would be a multi-week nightmare involving corporate IT etc. So ... I found #6083 and that VM had two PCI devices attached. Right now I am backing up again on the P51 after having removed the PCI devices and rebooted the VM a few times. Let's hope this does the trick. 

I am sure it's not the media, because I used multiple different ones and also tried my daily backups as far as 5 days back ... same result: "b'scrypt:Passphrase is incorrect" over and over (after having already spent hours restoring... so the passphrase was correct.

**Comment by SvenSemmler** [comment]
Ok, so it was not #6083. I made a fresh backup as described about and when trying to restore it on the T430 I again hit the "b'scrypt:Passphrase is incorrect" ... BUT I tried more than once and here is the thing: the first try it hit at chunk 9, second time around chunk 21 and just now I made it to chunk 293 !!!

This looks way to random to be an issue with the data. Any ideas what I could try next? Specifically (because this is time critical) ... how can I get the windows VM from the one machine to the other if I can't rely on qvm-backup?

**Comment by brendanhoar** [comment]
If your systems are lvm based (the default) this might be a workable alternative: 

https://github.com/tasket/wyng-backup

B

**Comment by SvenSemmler** [comment]
Update: I know used qvm-run --pass-io with "cat" to first move the entire backup into dom0 of the target machine and then run qvm-backup-restore. I did this to exclude any USB issues. I also monitored my CPU temp at it did not reach 75 degrees at any time. 

This time I made it to chunk 123 (previously with the same backup chunk 9 & 293). So it's not the USB and it's not the CPU. 

When I read through USB I failed at chunk 293 I saw that the tmp directory contained about 10-15 chunks into the future. This time with the file in dom0 I had all 592 chunks already in the tmp dir.

Could it be a RAM issue?

**Comment by SvenSemmler** [comment]
> https://github.com/tasket/wyng-backup

Sorry, I need help with that...

https://qubes-os.discourse.group/t/how-to-use-wyng-backup/4166

**Comment by SvenSemmler** [comment]
In summary:

1. created backup of HVM onto external SSD (using sys-usb)
2. copied backup from external SSD into dom0 of the source machine
3. successfully verified on source machine using backup in dom0
4. removed original HVM from source machine (made a clone first)
5. successfully restored on the source machine using backup in dom0
5. copied backup from the SSD into dom0 of the target machine
6. verify using backup in dom0 on target machine fails at chunk 361 with "b'scrypt: Input is not a valid scrypt-encrypted block"
7. second verify (same as step 6) fails at chunk 133 with "b'scrypt:Passphrase is incorrect"

Conclusion:

* backup file itself (at least on SSD and source machine dom0) is good
* software on both machines up-to-date
* failure happens only on target machine
* failure appears random (different chunk and sometimes different message)

The backup consists of 1061 chunks for root, 1 for private and 1 for firewall (seen when restoring with --verbose on source machine).

**Comment by tasket** [comment]
@SvenSemmler You could try running a quick `md5sum` on both copies of the backup file (on source and destination machines) to see if the sum matches. If it doesn't, then the archive was damaged in the copy process.

**Comment by SvenSemmler** [comment]
@tasket ... I just deleted it on the target machine in anticipation of the dd created file I'll hopefully have in an hour or so. Saw your proposal too late. But I will copy the backup from SSD again, do the md5sum and if they match I'll do one more --verify attempt.

**Comment by SvenSemmler** [comment]
Hi @tasket thank you for the hint -- the md5 sums match on source and target machine.

**Comment by DemiMarie** [comment]
> Hi @tasket thank you for the hint -- the md5 sums match on source and target machine.

For future reference: `sha256sum` is a better choice here, as MD5 is vulnerable to cheap chosen-prefix collision attacks.

**Comment by marmarek** [comment]
@SvenSemmler you may be hitting https://github.com/QubesOS/qubes-issues/issues/4791 - running out of space in /var/tmp in dom0 during restore process. It is fixed in R4.1, but not in R4.0. Fully backporting the fix is tricky (but not impossible), but if you care about restoring from a backup archive that is transferred into dom0 already, you can try manually applying [this change](https://github.com/QubesOS/qubes-core-admin-client/pull/165/commits/93608658a9cb6b75fd73168f4fefcc909eb41b09) to `/usr/lib/python3.5/site-packages/qubesadmin/backup/restore.py` in dom0.

**Comment by SvenSemmler** [comment]
@marmarek thank you. I saw the remains in /var/tmp/restore* and cleaned them out before each new try. Also the target machine has a 2TB SSD and currently less than 20% are used. If you think it makes sense anyway, I can apply the change and retry (for debugging purposes).

I was able to move the qube using the dd method @tasket pointed out, but I am happy to keep debugging this. My next step is to backup some qubes on the target machine and do a verify to see if the issue has something to do with the original backup originating on another machine. 

If there are any other experiments or investigations that could help track this down, please let me know.

**Comment by SvenSemmler** [comment]
TLDR: I no longer think this is a bug in Qubes OS rather than a specific hardware issue with my new computer. I will continue to debug and try and find the issue, but I will do so in the forum and not here. I am OK with this bug being closed (although I am not the original reporter).

Backup/Verify off all qubes on the old machine: no issue
Backup/Verify off all qubes on the new machine: fails again with various errors. Also when moving the windows qube and decompressing it with gunzip the machine frooze twice before it finally worked the third time. Also, just watching some Netflix yesterday evening had the browser tab crash 3 times ... never seen that before with identical qube / memory / software versions on old machine.

Conclusion: hardware issue.

I plan to exchange the CPU within a week anyway. Also suspect it could be RAM. SSD seems less likely but is a distant third possible root cause. I will ask in the forum for ways to debug/check on this. Thank you for your attention and help.

**Comment by andrewdavidwong** [comment]
Given that @jimi3 said he unable to reproduce this (https://github.com/QubesOS/qubes-issues/issues/6227#issuecomment-733042190) and @SvenSemmler has concluded that he is not actually experiencing the bug reported here, I'm closing this for now as "cannot reproduce." If you believe this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by SvenSemmler** [comment]
@andrewdavidwong I'd like to make you and @marmarek aware that following @ludovic's [recommendation](https://qubes-os.discourse.group/t/how-do-i-check-my-cpu-and-ram-from-a-recovery-shell/4189/2) in the forum I have downgraded the kernel on the ThinkPad T430 (aka target machine) to 4.19.182-1 (Xen 4.8.5-30)  and have not observed any issue since. I have already made a complete backup (this never completed before without freeze) and are now running a verify. 

The T430 is not (yet) certified hardware, but might be in the future. Nitrokey is offering it as NitroPad T430 with Qubes pre-installed (ThinkPad T430 with Heads and Nitrokey ... which is exactly what I am doing with the help of @Plexus).

It currently runs a i7-3520M which was in it when I bought it. Originally I planned to upgrade to a i7-3632QM, but that didn't work as [Vt-d is not supported in the rPGA988 socket version](https://qubes-os.discourse.group/t/nitrokey-t430-i5-3632qm-combination/4128). Another thread the Qubes team might be interested in. Ultimately I will upgrade to i7-3740QM once it arrives. Maybe it's a specific issue with that CPU (i7-3520M)? I will try to go back to the current kernel once I've upgraded.

Not sure this is worth for you to track as an issue, but I wanted to share all this with you just in case.

**Comment by SvenSemmler** [comment]
I deleted my last comment as it was factually incorrect. I apologize for the noise. Will take more time/care before posting again.

**Comment by SvenSemmler** [comment]
Final update from my side to benefit future readers of this issue: 

the "b'scrypt:Passphrase is incorrect" was caused by the CPU in the target machine

After exchanging it I repeated all experiments outlined above with multiple media and computers. The issue gone.

**Comment by andrewdavidwong** [comment]
I wonder if this was actually a duplicate of #4493.
