### ISSUE TITLE
ArchLinux update with Qubes Updater

### ISSUE THREAD

**Issue by lubellier** [QubesOS/qubes-issues#6239]
**The problem you're addressing (if any)**
Presently the Qubes Updater tool doesn't detect and doesn't update ArchLinux templateVMs.

**Describe the solution you'd like**
I wish that Qubes Updater detects the ArchLinux updates and update the ArchLinux Qubes, as it's already work for Fedora and Debian Qubes.

**Where is the value to a user, and who might that user be?**
OS updates are very important for security, the user benefits with an automatic update for ArchLinux OS.

**Describe alternatives you've considered**
Manual update:
- from Qube Manager: right click, Update Qube
- from terminal : `pacman -Syu`

**Additional context**
ArchLinux templateVM got already some essential parts of the requested feature, I added the missing parts in my own ArchLinux templateVM and it works (for me).

So _I'll prepare the Pull Requests for this feature_ for Qubes OS 4.0.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
- [Updating software in TemplateVMs](https://www.qubes-os.org/doc/software-update-domu/#updating-software-in-templatevms)

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
Not found.

**Comment by lubellier** [comment]
## How does it work?
- 5mn after the boot, the _qubes-update-check_ systemd timer launches the _qubes-update-check_ systemd service
- this service launches `/usr/lib/qubes/upgrades-status-notify` which 
  + checks if updates are available (OS specific: see `/usr/lib/qubes/upgrades-installed-check`)
  + notifies the _Qubes Updater_ tool if an update is available or not
- In the _Qubes Updater_ tool, the User ask an update, this action launches the _qubes.InstallUpdatesGUI_ qubes-rpc in the target VM
- the _InstallUpdatesGUI_ rpc 
  + launches the OS upgrade (OS specific command)
  + launches the qubes-update-check systemd service which launch the above see `/usr/lib/qubes/upgrades-status-notify` (which notifies the _Qubes Updater_ tool if the VM is or isn't updated, and so the loop is done)

## Analysis
The file `/usr/lib/qubes/upgrades-installed-check` failed on detection of available updates. This file is in the ArchLinux qubes-vm-core package, and so the qubes-core-agent-linux git repository. 
 
The _upgrades-installed-check_ script uses the ArchLinux `checkupdates` command, but `checkupdates` comes from the not installed _pacman-contrib_ package.

The launch of the qubes-update-check service failed on ArchLinux, because the qubes-rpc uses the `service` command which isn't available for this OS. The qubes-update-check file is also in the qubes-core-agent-linux git repository.

## Realization
Modifications only the qubes-core-agent-linux git repository:
1. [ ] fix the upgrades-installed-check script (checkupdate result analysis)
2. [ ] add the pacman-contrib dependency for qubes-vm-core
3. [ ] fix the qubes.InstallUpdatesGUI qubes-rpc (service launching)

## Questions
- for the _qubes-core-agent-linux_ git forked repository, on which branch should I prepare my PR? (_master-staging_, _release4.0-staging_, _master_, _release4.0_). I tested my solution on Qubes OS 4.0 only, but it will nice if available on 4.0 and 4.1.
- how can I add a label to an issue?
- Any remarks before my PR?

**Comment by DemiMarie** [comment]
The Qubes updater uses SaltStack to update VMs, not `qubes.InstallUpdatesGUI`.

**Comment by icequbes1** [comment]
> The Qubes updater uses SaltStack to update VMs, not `qubes.InstallUpdatesGUI`. Please make your PR against `master`.

@DemiMarie Perhaps there is a terminology difference -

- There is the Qubes Updater (`qubes-update-gui`); this uses `qubesctl`/SaltStack
- There is also the "Update qube" function from the Qubes Manager. I believe this is what @lubellier refers to. This does use `qubes.InstallUpdatesGui`, which is just a short way to start a template and run the appropriate package manager command

**Comment by lubellier** [comment]
After the @icequbes1 remark, should I push my `qubes.InstallUpdatesGui` change (viewable in the PR comment)?

Any entry point for fixing (if needed) SaltStack? I'm not yet skilled with Salt...

**Comment by lubellier** [comment]
I found the [SaltStack documentation](https://www.qubes-os.org/doc/salt/), I'll try to understand the eventually changes required for this issue.

**Comment by unman** [comment]
On Mon, Nov 30, 2020 at 03:56:19PM -0800, Ludovic Bellier wrote:
> I found the [SaltStack documentation](https://www.qubes-os.org/doc/salt/), I'll try to understand the eventually changes required for this issue.
> 

The Qubes update using salt uses pkg.uptodate which covers Arch, as well
as Debian and Fedora package managers.
I cant speak to the updater, because I don't have my qubes checking for
updates, but pkg.uptodate certainly works for updates of Arch
templates. I'm surprised that the gui tool doesn't work: changes
required should be minimal.

**Comment by icequbes1** [comment]
> After the @icequbes1 remark, should I push my qubes.InstallUpdatesGui change

@lubellier Yes, because as long as there is a 'Update qube' from Qubes Manager, it is broken for Arch. I cannot say if this functionality is a leftover/forgotten remnant, but it does provide a 1-click solution for users if updates via Salt are broken (which did happen recently).

As for updates via SaltStack, I don't believe there is anything more to do. The only thing that is broken for Arch is notifying dom0 if there are updates available.

- qubes.InstallUpdatesGui starts the qubes-update-check service, which then calls upgrades-status-notify (which for Arch relies on `checkupdates`)
- SaltStack/qubesctl/Qubes Updater: `notify-updates` is a task which executes upgrades-status-notify (see https://github.com/QubesOS/qubes-mgmt-salt-dom0-update/blob/master/update/qubes-vm.sls)

So if you fix the upgrades-status-notify issue with checkupdates, that _should_ be it.

**Comment by lubellier** [comment]
@unman : yes it's minor, see the PR last commit.

thanks @icequbes1 for the explanations, I pushed my last commit.

I request a Peer Review or remarks for my PR.
