### ISSUE TITLE
Inter-qube clipboard is broken with GUI domain

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#6263]
**Qubes OS version**

R4.1

**Affected component(s) or functionality**

gui-daemon

**Brief summary**

gui-daemon consults qrexec policy when using pasting inter-qube clipboard into some VM. This fails in gui-domain.
Furthermore, if qube is using qrexec-based clipboard (Windows), then it fails because of the way the qrexec is called (`qrexec-client` call, which exists in dom0 only).

In hybrid gui-domain, there is yet another issue: gui-daemon in dom0 intercepts clipboard key combos (ctrl+shirt+c/v) and do not pass them to the GUI domain at all.

**To Reproduce**

1. Start GUI domain in R4.1 (either hybrid, or real - both are affected)
2. Try to copy something between qubes.

**Expected behavior**

Successful copy.

**Actual behavior**

Fail on paste, possibly with a message suggesting qrexec policy denial.

**Additional context**

Found by @DemiMarie: https://github.com/QubesOS/qubes-gui-daemon/pull/56#discussion_r537072340

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
For standard (non-qrexec) case we could add a call to dom0 that allows evaluating policy for some specific values. We do want such call anyway for Policy API (I can't quickly find related issue, but an extension of https://github.com/QubesOS/qubes-core-qrexec/pull/54), so we can simply implement this little part with higher priority, and use it for gui-daemon too. I'll write details in a separate issue and link it here in a moment.

But for the clipboard over qrexec case, I'm not sure how to fix it correctly. The idea is have a policy about actual clipboard copy and clipboard paste qubes, not (something)<->gui-domain. The latter policy isn't very useful (basically on/off switch for clipboard access at all). And gui-domain cannot spoof qrexec call source, nor issue qrexec calls bypassing the policy, like it did in dom0.

**Comment by marmarek** [comment]
> I'll write details in a separate issue and link it here in a moment.

https://github.com/QubesOS/qubes-issues/issues/6264

**Comment by DemiMarie** [comment]
The GUI domain can ask dom0 to bypass the policy, though.  We can implement this by means of a `qubes.VMPaste` service, which takes the source and destination qubes as arguments.  If the calling domain is GUI domain for both source and destination qubes, dom0 will then invoke `qubes.ClipboardPaste` to the destination domain as if it was invoked by the source domain, including policy checking.  Otherwise, the call will be denied.

**Comment by marmarek** [comment]
This indeed may work, since for the clipboard operation, GUI domain should be the same for both source and the destination.

**Comment by jamke** [comment]
Note that is not related to this issue, but related to clipboard user experience: please think about making clipboard outlive the application close up. Currently if one copies something from notepad (e.g. kate) and close it, than opens browser - paste will not work. It's because we use xorg that had this bad approach. 
All GNU/Linux distributions and DEs resolve this by adding clipboard manager, but Qubes OS is not doing it as it would take the whole notification area to be filled with clipboard managers of each appvm. So, something different should be provided to avoid user frustration with clipboard buffer being lost all the time.
Maybe something in GUI domain for that?

I was thinking to make some sort of script to send all changes of buffer in all domains to some domain (maybe even dom0, but it can be not secure, even for text buffers) to store and avoid this clipboard loosing behavior, but you guys probably know better and may have proper solution?

**Comment by andrewdavidwong** [comment]
> Note that is not related to this issue, but related to clipboard user experience: please think about making clipboard outlive the application close up. Currently if one copies something from notepad (e.g. kate) and close it, than opens browser - paste will not work. It's because we use xorg that had this bad approach.
> All GNU/Linux distributions and DEs resolve this by adding clipboard manager, but Qubes OS is not doing it as it would take the whole notification area to be filled with clipboard managers of each appvm. So, something different should be provided to avoid user frustration with clipboard buffer being lost all the time.
> Maybe something in GUI domain for that?
> 
> I was thinking to make some sort of script to send all changes of buffer in all domains to some domain (maybe even dom0, but it can be not secure, even for text buffers) to store and avoid this clipboard loosing behavior, but you guys probably know better and may have proper solution?

This should probably be filed as a separate issue.

**Comment by DemiMarie** [comment]
QubesOS/qubes-gui-daemon#59 only handles the GPU pass-through case, not the hybrid GUI domain case.

**Comment by marmarek** [comment]
> [QubesOS/qubes-gui-daemon#59](https://github.com/QubesOS/qubes-gui-daemon/pull/59) only handles the GPU pass-through case, not the hybrid GUI domain case.

With https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/36/commits/1d528c8ccc228c161643729ee6cfd50f8a20c471, it should handle the hybrid case too.
