### ISSUE TITLE
Ubuntu 20.04 template builds with incompletely configured users causing problems with sudo and user login

### ISSUE THREAD

**Issue by asharp** [QubesOS/qubes-issues#6307]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
qubes-builder, the Ubuntu 20.04 template specifically

**Brief summary**
Users aren't being set up correctly, and sudo configuration is incomplete. if you look at /etc/shadow, user and root both have a password of "*" which means the accounts cannot log in interactively. They should instead have an empty password.

/etc/sudoers.d is also missing the files "qubes" and "qubes-input-trigger", which setup passwordless sudo in the other templates. Sudo should work once those files are added, as user is in the "qubes" group.

**How Reproducible**
100%

**Expected behavior**
it should be possible to login as user or root via xl console, and sudo from user to root should be passwordless.

**Actual behavior**
trying to log in as root or user gives a password prompt, sudoing gives a "user is not in the sudoers file.  This incident will be reported." warning message.

**Solutions you've tried**
running:

1. passwd -d root
2. passwd -d user
3. copying qubes and qubes-input-trigger from a fedora qube into /etc/sudoers.d on the ubuntu template

allows user/root to login via console and passwordless sudo to work.

**Comment by icequbes1** [comment]
This is by design - you will have to install `qubes-core-agent-passwordless-root`.

Find the .deb in qubes-src/linux-template-builder/pkgs-for-template/focal/pool/...

**Comment by andrewdavidwong** [comment]
> This is by design - you will have to install `qubes-core-agent-passwordless-root`.
> 
> Find the .deb in qubes-src/linux-template-builder/pkgs-for-template/focal/pool/...

@unman, can you confirm this is intentional? Couldn't find any mention of this in past issues, documentation, or qubes-users.

**Comment by DemiMarie** [comment]
I know that the Arch template builds with `qubes-core-agent-passwordless-root` installed.

**Comment by unman** [comment]
On Fri, Dec 25, 2020 at 08:30:30AM -0800, Andrew David Wong wrote:
> > This is by design - you will have to install `qubes-core-agent-passwordless-root`.
> > 
> > Find the .deb in qubes-src/linux-template-builder/pkgs-for-template/focal/pool/...
> 
> @unman, can you confirm this is intentional? Couldn't find any mention of this in past issues, documentation, or qubes-users.
> 

It's not intentional, but I dont recognise this behaviour.
In fact I've just rebuilt the focal template and it *does* have the
qubes-core-agent-passwordless-root package installed, so the system
displays none of the behaviour complained of.

**Comment by icequbes1** [comment]
Perhaps "by design" is the wrong phrase. I too performed a build and did not get passwordless root, and from my checks of the code, it confirmed that I wouldn't. I later assumed passwordless root was not given by default and users are expected to install it, similar to minimal templates.

Building an R4.0 template with `DISTS_VM=focal` does not bring in `qubes-vm-recommended`, which is what looks to bring in `qubes-core-agent-passwordless-root`.

In builder-debian/template_qubuntu there only exists `packages_qubes.list` which only contains `qubes-vm-dependencies`. I am failing to see how qubes-core-agent-passwordless-root gets pulled into any Ubuntu build unless there is magic with the template flavors/options (`+standard` and `+desktop` did not pull it in for me).

Perhaps detailing the proper build procedure may be useful, as this doc[1] is linked to from qubes-doc...but that only says "Select one of the Ubuntu version options.". `focal` and `focal+desktop` are the only options seen in `setup` and neither have resulted in passwordless root.

[1] https://github.com/Qubes-Community/Contents/blob/master/docs/os/ubuntu.md

**Comment by asharp** [comment]
@unman - This is from my build on 2020-12-23. Did you rebuild from scratch?

@icequbes1 - you either need passwordless sudo, or sudo with password. Sudo with password would then require that the users have working passwords and that user is in a group that can sudo. Not having working passwords also breaks the xen console.

As a more general point: if the source packages are designed to be built into binary packages by end users via qubes-builder, and are maintained to work with these templates (see #6302), then why aren't they also in the standard repos? The packages still need to be maintained, the build infrastructure should already be there, but now the template can be built more reliably (see again #6302) and debugging is easier as everybody has the same packages with consistent versioning.

**Comment by unman** [comment]
On Fri, Dec 25, 2020 at 10:42:00PM -0800, Alex Sharp wrote:
> @unman - This is from my build on 2020-12-23. Did you rebuild from scratch?
> 
> @icequbes1 - you either need passwordless sudo, or sudo with password. Sudo with password would then require that the users have working passwords and that user is in a group that can sudo. Not having working passwords also breaks the xen console.
> 
> As a more general point: if the source packages are designed to be built into binary packages by end users via qubes-builder, and are maintained to work with these templates (see #6302), then why aren't they also in the standard repos? The packages still need to be maintained, the build infrastructure should already be there, but now the template can be built more reliably (see again #6302) and debugging is easier as everybody has the same packages with consistent versioning.
> 

You're both right.

I have a symlink to packages_qubes_standard.list, consequential on
@fepitre refactoring, which you don't have. I'll put in PR to fix this,
for a standard Ubuntu build.

On the more general point, Ubuntu is a second class template, because
Qubes will not distribute it.
Either you get the template from someone else, in which case they
will supply packages, or you roll your own in which case you are building
the packages.
Why aren't packages in the standard Qubes repos? Maintenance and support.
It's been mooted before, and this may change. BUT since the current
infrastructure doesn't seem to catch broken package builds for the *stable*
release, it's under pressure as it is.

**Comment by andrewdavidwong** [comment]
Reopening due to apparent regression reported in #6477.
