### ISSUE TITLE
qubes-dom0-update doesn’t overwrite old RPM database in UpdateVM

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6321]
**Qubes OS version**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**
`qubes-dom0-update`

**Brief summary**
With a Fedora 33+ UpdateVM, `qubes-dom0-update` doesn’t overwrite the RPM database used for updates.

**How Reproducible**
100%

**To Reproduce**

1. Set a Fedora 33 (or later) UpdateVM
2. Install a package with `qubes-dom0-update`
3. Remove the package.
4. Install the package

**Expected behavior**
The package installs successfully

**Actual behavior**
The package does not install successfully the second time.

**Screenshots**

**Additional context**
The cause of this problem is that the RPM database format has changed, from BerkeleyDB to SQLite.  Therefore, the `tar` command that copies dom0’s RPM database doesn’t overwrite the VM’s database.

**Solutions you've tried**
Modifying `qubes-dom0-update` to `rm -rf /var/lib/qubes/dom0-updates/var/lib/rpm` works.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
None

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by mattmccutchen** [comment]
I ran into this problem on my Qubes R4.0 system after I upgraded the UpdateVM from Fedora 32 to 33.  The symptom I saw was repeated "updates available for dom0" messages referring to updates that were already installed.  I had configured the UpdateVM to make all of `/var/lib/qubes/dom0-updates` persist across reboots because of #6250; without that special configuration, a typical user would be unlikely to see this symptom if they frequently reboot the UpdateVM because of updates to its TemplateVM.  I imagine that problems could still occur with successive package management operations like those in the "steps to reproduce" above.

@marmarek Would you consider applying the fix to Qubes R4.0, or do you think the problem affects too few users?  In general, is it expected that an issue with the "Release 4.0 updates" milestone is closed without updating R4.0?  (#6581 is another issue in that state.)

**Comment by andrewdavidwong** [comment]
> In general, is it expected that an issue with the "Release 4.0 updates" milestone is closed without updating R4.0?

No.

**Comment by andrewdavidwong** [comment]
> I ran into this problem on my Qubes R4.0 system after I upgraded the UpdateVM from Fedora 32 to 33.

I am also experiencing this on R4.0 with a Fedora 33 UpdateVM. If there are updates available, running `qubes-dom0-update` more than once without restarting the UpdateVM makes it appear as though the same updates are repeatedly being installed.

**Comment by marmarek** [comment]
> > In general, is it expected that an issue with the "Release 4.0 updates" milestone is closed without updating R4.0?

In fact, yes. I've opened https://github.com/QubesOS/qubes-issues/issues/6655 to have it clarified.
