### ISSUE TITLE
Can’t build Arch template on R4.0

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6327]
**Qubes OS version**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**
`qubes-builder`

**Brief summary**
Building the Arch template involves installing the `qubes-vm-dependencies` meta-package, which doesn’t exist on R4.0.

**How Reproducible**
100%

**To Reproduce**

1. Try to build the Arch template on R4.0

**Expected behavior**
Build succeeds.

**Actual behavior**
Build fails

**Screenshots**

**Additional context**
This could be by design, but in that case I would expect a better error message.

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by icequbes1** [comment]
From just trying to keep up with Arch template changes, it's because some archlinux PRs dealing with packaging are not backported to R4.0:

- https://github.com/QubesOS/qubes-meta-packages/pull/26
- https://github.com/QubesOS/qubes-core-agent-linux/pull/284
- https://github.com/QubesOS/qubes-meta-packages/pull/27 ?

My understanding is core-agent-linux packaging was split and put into meta-packages to match other distro builds on master branch (vm-dependencies is brand new for the R4.1 Arch build).

I have been temporarily working around this issue by:

```
cd qubes-src/builder-archlinux
git revert 49c9ca6bb
git revert bb9825361
```

This replaces `qubes-vm-dependencies` during template build with the explicit packages. Have not investigated all of the changes yet, but I presume the real fix would be to backport meta-packages to R4.0? Or have a release-4.0 branch for builder-archlinux?

**Comment by marmarek** [comment]
meta-packages changes are now backported to release4.0 branch. Can you verify if that works now?

**Comment by DemiMarie** [comment]
It still does not work, sadly.  That said, it could be my fault.  I will retry with a clean `qubes-builder`.

**Comment by DemiMarie** [comment]
I managed to get a working build.  I will report back later today with more information.

**Comment by unman** [comment]
Arch templates now build correctly (after fixing vmm-xen dependency.)
This should  be closed
