### ISSUE TITLE
Qubes Builder does not build snapd-helper for Debian based templates

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6350]
**Qubes OS version**

4.0 updated

**Affected component(s) or functionality**

Qubes Builder

**Brief summary**

As title

**How Reproducible**

100%

**To Reproduce**

1. Run .setup for Debian or Ubuntu templates
2. make qubes-vm
3. make template

**Expected behavior**

Template will be built with snapd-helper, or package will be available

**Actual behavior**

No package built

**Screenshots**

**Additional context**

**Solutions you've tried**

Manually adding entry to builder.conf

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
Can you provide more details? The default builder.conf for R4.0 [does include it https://github.com/QubesOS/qubes-builder/blob/master/example-configs/qubes-os-r4.0.conf#L59]. The package is not installed by default (mostly because it breaks installing snaps in the template itself). AFAIK snap does not support multiple install locations, so the user need to choose only one, on template level - either all snaps installed in the TemplateVM, or only in TemplateBasedVMs.

PS flatpak does support both locations out of the box: flatpaks installd in the TemplateVM needs `--system` option (I think it's the default) and those in TemplateBasedVM - `--user` option. No extra qubes-specific configuration is necessary.

**Comment by unman** [comment]
It's specifically when ./setup.sh is run to configure builder.conf
