### ISSUE TITLE
Pipewire audio support

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6358]
**The problem you're addressing (if any)**
Fedora 34 [will be switching to PipeWire], which brings security and functionality improvements.  PipeWire is API and ABI compatible with PulseAudio, but I do not believe this compatibility extends to PipeWire plugins.

Fortunately, PipeWire has a multiprocess architecture, so we may be able to implement sinks and sources out of process.  PipeWire also handles video input, meaning that we may be able to implement a paravirtualized camera system.

**Describe the solution you'd like**
PipeWire should be supported

**Where is the value to a user, and who might that user be?**
Fedora 34 users will have working audio.

**Describe alternatives you've considered**
We can force Fedora 34 to use PulseAudio, assuming it is still supported.

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by 0spinboson** [comment]
It looks like pipewire either doesn't like my usb microphone with headphone output, or there is an issue with the usb device forwarding in fedora-35, because when I connect my usb device, firefox / youtube refuses to playback any video because it seems to have problems outputting it to the audio device. (When I disconnect the usb device, video playback instantly resumes, after giving vague error messages. Playback via VLC works fine, although the volume scaling is terrible -- even volume set to 1/100 using alsamixer is pretty loud, 5/100 is almost unbearable, distortion starts quickly.)

Using journalctl -xe-t kernel, I also see a constant stream of "usb usb1: not yet implemented" multiple times each second, and "vhci_get_frame_number: 2570 callbacks suppressed" every 5 seconds. This is not an issue in a fedora-32-based qube, so I assume this is all related to the switch to pipewire.

**Comment by DemiMarie** [comment]
Good news: PipeWire has a stable ABI for plugins!

**Comment by DemiMarie** [comment]
Bad news: the documentation is not sufficient for me to be able to create something that works.  I will be filing some issues.

**Comment by jamke** [comment]
The release notes of R4.2 (rc3 currently) state that **PipeWire is already supported in Qubes OS**.
What does it mean? Why this ticket is not closed as solved then?

**It is not obvious what is the current situation with pipewire and pulseaudio in the R4.2.**
* Is there any documentation about the current situation?
* What should user use in dom0 and what in templates in R4.2?
* If pipewire then does it have problems with sys-audio and audio qube approach? Or should user still stick to pulseaudio manually solving the packaging conflicts as it is in R4.1?
* If pipewire should be used in dom0, than will it work with existing user’s templates (e.g. migrated from backup) that use pulseaudio?

**Comment by DemiMarie** [comment]
@jamke It means that the Qubes developers forgot to close the issue.  To answer your questions:

- I am not sure what the documentation status is.
- PipeWire in dom0 is not officially supported.  Audio playback and recording are known to work, but features such as sound volume save & restore don’t.
- PipeWire in sys-audio and in qubes that connect to sys-audio is fully supported, at least to the extent that sys-audio is supported at all.

**Comment by jamke** [comment]
> @jamke To answer your questions

Thank you @DemiMarie , I will reports your answers on forum, because people do no understand the situation with pipewire.

**Comment by SaswatPadhi** [comment]
> Using journalctl -xe-t kernel, I also see a constant stream of "usb usb1: not yet implemented" multiple times each second, and "vhci_get_frame_number: 2570 callbacks suppressed" every 5 seconds. This is not an issue in a fedora-32-based qube, so I assume this is all related to the switch to pipewire.

I still see this issue with my USB headphones.

I am running a Fedora 40 `sys-audio` qube on Qubes R4.2 with `kernel-latest`.

@0spinboson: Was this issue ever resolved for you? Were you able to figure out any workarounds?
