### ISSUE TITLE
qubes-yubikey-dom0 should be part of contrib packages?

### ISSUE THREAD

**Issue by fepitre** [QubesOS/qubes-issues#6361]
Moved from: https://github.com/QubesOS-contrib/build-issues/issues/68
@tlaurion

**Comment by marmarek** [comment]
Currently it's in the main repositories, you suggest moving it to contrib?

**Comment by tlaurion** [comment]
@marmarek no I was just basing myself on the docs saying packages were bot built  right now but that might change

**Comment by tlaurion** [comment]
"Contrary to instruction there, currently there is no binary package in the Qubes repository and you need to compile it yourself. This might change in the future."

**Comment by marmarek** [comment]
Ignore that, use challenge-response mode described in the next section. I'll remove the obsolete section in a moment.

**Comment by andrewdavidwong** [comment]
If I understand correctly, this issue was based on a misunderstanding that has now been cleared up in the documentation (https://github.com/QubesOS/qubes-doc/commit/a48402dc8b6cbe4779b2a41af2fd12b2a93f9027), and there is no desired action left to be taken on this issue. Therefore, I'm closing this issue. If anyone thinks that this should be reopened, please clearly state the proposed action for this issue.
