### ISSUE TITLE
Speaker audio and built-in microphone stop working after upgrade

### ISSUE THREAD

**Issue by b0rr4ch4** [QubesOS/qubes-issues#6367]
**Qubes OS version** 
`uname -r` 4.19.94-1.pvops.qubes.x86_x64

**Affected component(s) or functionality**
Speaker audio and mic builtin

**Brief summary**
Speaker audio and built-in microphone stop working after upgrade

**How Reproducible**
sudo qubes-dom0-update

**Comment by rossifw** [comment]
I am somehow vulnerable if I don't update my qubes with qubes-dom0-update?

**Comment by marmarek** [comment]
Can you specify which exactly update? I guess that's about dom0 kernel? Which kernel you are running now (you can check it with `uname -r` command).

> I am somehow vulnerable if I don't update my qubes with qubes-dom0-update?

We announce important (security) fixes by publishing Qubes Security Bulletins - the latest one is here: https://www.qubes-os.org/news/2020/12/16/qsb-063/ - and it does include dom0 kernel patch.

**Comment by rossifw** [comment]
`uname -r` 4.19.94-1.pvops.qubes.x86_x64

**Comment by 1osdfkjo12sdfa** [comment]
I believe I have this issue. My external mic + sound was working fine. Then after upgrade the external mic stopped working but the sound continues. Its working in dom0 but not in the vms. 

```
INFO ================================================================================
 Package                     Arch   Version             Repository         Size
================================================================================
Installing:
 kernel                      x86_64 1000:5.4.107-1.fc25.qubes
                                                        qubes-dom0-cached  57 M
 kernel-qubes-vm             x86_64 1000:5.4.107-1.fc25.qubes
                                                        qubes-dom0-cached  87 M
 libzstd                     x86_64 1.3.2-1.fc25        qubes-dom0-cached 191 k
 rpm-sign-libs               x86_64 4.14.2.1-3.fc25     qubes-dom0-cached  70 k
Upgrading:
 PackageKit                  x86_64 1.1.5-1.1.fc25      qubes-dom0-cached 664 k
 PackageKit-glib             x86_64 1.1.5-1.1.fc25      qubes-dom0-cached 129 k
 createrepo_c                x86_64 0.10.0-6.1.fc25     qubes-dom0-cached  69 k
 createrepo_c-libs           x86_64 0.10.0-6.1.fc25     qubes-dom0-cached  95 k
 deltarpm                    x86_64 3.6-17.1.fc25       qubes-dom0-cached  89 k
 device-mapper-persistent-data
                             x86_64 0.7.5-3.1.fc25      qubes-dom0-cached 435 k
 drpm                        x86_64 0.3.0-3.1.fc25      qubes-dom0-cached  67 k
 grub2-starfield-theme       x86_64 1:2.02-0.38.1.fc25  qubes-dom0-cached 2.2 M
 hawkey                      x86_64 0.6.4-3.1.fc25      qubes-dom0-cached  64 k
 libsolv                     x86_64 0.6.29-2.1.fc25     qubes-dom0-cached 361 k
 python2-deltarpm            x86_64 3.6-17.1.fc25       qubes-dom0-cached  36 k
 python2-rpm                 x86_64 4.14.2.1-3.fc25     qubes-dom0-cached 117 k
 python3-hawkey              x86_64 0.6.4-3.1.fc25      qubes-dom0-cached  47 k
 python3-qubesimgconverter   x86_64 4.0.32-1.fc25       qubes-dom0-cached  27 k
 python3-rpm                 x86_64 4.14.2.1-3.fc25     qubes-dom0-cached 116 k
 qubes-core-dom0-linux       x86_64 4.0.29-1.fc25       qubes-dom0-cached  54 k
 qubes-core-dom0-linux-kernel-install
                             x86_64 4.0.29-1.fc25       qubes-dom0-cached  14 k
 qubes-mgmt-salt-dom0-update noarch 4.0.10-1.fc25       qubes-dom0-cached  55 k
 qubes-utils                 x86_64 4.0.32-1.fc25       qubes-dom0-cached  23 k
 qubes-utils-libs            x86_64 4.0.32-1.fc25       qubes-dom0-cached  27 k
 rpm                         x86_64 4.14.2.1-3.fc25     qubes-dom0-cached 531 k
 rpm-build-libs              x86_64 4.14.2.1-3.fc25     qubes-dom0-cached 136 k
 rpm-libs                    x86_64 4.14.2.1-3.fc25     qubes-dom0-cached 324 k
 rpm-plugin-selinux          x86_64 4.14.2.1-3.fc25     qubes-dom0-cached  67 k
 rpm-plugin-systemd-inhibit  x86_64 4.14.2.1-3.fc25     qubes-dom0-cached  68 k
 satyr                       x86_64 0.21-2.1.fc25       qubes-dom0-cached 108 k
 xorg-x11-drv-ati            x86_64 18.0.1-1.1.fc25     qubes-dom0-cached 169 k
 xorg-x11-drv-nouveau        x86_64 1:1.0.15-4.1.fc25   qubes-dom0-cached 100 k
Removing:
 kernel                      x86_64 1000:4.19.94-1.pvops.qubes
                                                        @anaconda         252 M
 kernel-qubes-vm             x86_64 1000:4.19.94-1.pvops.qubes
                                                        @anaconda         513 M
```

Tho this happened at the same time as a VM update that may be to blame. 


```
Commandline: /usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold -o DPkg::Options::=--force-confdef dist-upgrade
Upgrade: xserver-xorg-video-dummyqbs:amd64 (4.0.35-1+deb10u1, 4.0.36-1+deb10u1), qubes-gui-agent:amd64 (4.0.35-1+deb10u1, 4.0.36-1+deb10u1), qubes-kernel-vm-support:amd64 (4.0.31+deb10u1, 4.0.32+deb10u1), libqrexec-utils2:amd64 (4.0.31+deb10u1, 4.0.32+deb10u1), pulseaudio-qubes:amd64 (4.0.35-1+deb10u1, 4.0.36-1+deb10u1), libqubes-rpc-filecopy2:amd64 (4.0.31+deb10u1, 4.0.32+deb10u1), xserver-xorg-input-qubes:amd64 (4.0.35-1+deb10u1, 4.0.36-1+deb10u1), qubes-utils:amd64 (4.0.31+deb10u1, 4.0.32+deb10u1)
```

Originally i thought the issues was caused by vm pulseaudio-qubes package that was upgraded. But i tried with various different qubes (debian10, debian9 and Fedora30) and don't get any sound on my mic. 

I tried to roll back pulseaudio-qubes trying packages pulseaudio-qubes_4.0.34-1+deb10u1_amd64.deb
, pulseaudio-qubes_4.0.35-1+deb10u1_amd64.deb, pulseaudio-qubes_4.0.36-1+deb10u1_amd64.deb

None of these worked. When i tried pulseaudio-qubes_4.0.34-1+deb10u1_amd64.deb and also had some music playing there was some weird ringing in the microphone. I attempted to roll back the full vm update but that caused the template to crash then then not boot. 

Also tried to downgrade some of these packages caused the vm to crash. I also tried to do the dom0 reinstall of the template to further trouble shoot this issue but failed. 

```
$ sudo dnf reinstall qubes-template-debian-10
Qubes OS Repository for Dom0                                                                                                                                   25 MB/s |  26 kB     00:00    
Installed package qubes-template-debian-10-4.0.1-201912251612.noarch (from anaconda) not available.
Error: Nothing to do.
```

Next I tried to learn from this person and try their debug approach https://github.com/QubesOS/qubes-issues/issues/4204 

```
launch fresh disposable VM based on unmodified fedora-30 template installed from qubes repository
Dom0: qvm-device mic attach dispXXX dom0:mic
DispVM: parecord -d vchan_input /run/user/1000/recording.tmp
speak or tap on the mic
```

I notice that /run/user/1000/recording.tmp is growing but  when i play the file its actually just silence. So i think the issue is that qubes is just not passing the mic stream to the VM

I also have output from pacat.foo.log

``` 
Connection established.
Stream successfully created.
Buffer metrics: maxlength=4194304, tlength=3072, prebuf=2052, minreq=1024
Using sample spec 's16le 2ch 44100Hz', channel map 'front-left,front-right'.
Connected to device alsa_output.pci-0000_00_1f.3.analog-stereo (0, not suspended).
Stream successfully created.
Buffer metrics: maxlength=4194304, tlength=4096, prebuf=4294967295, minreq=4294967295
Using sample spec 's16le 2ch 44100Hz', channel map 'front-left,front-right'.
Connected to device alsa_output.pci-0000_00_1f.3.analog-stereo.monitor (0, not suspended).
Stream started.
Stream buffer attributes changed.
Stream buffer attributes changed.
Stream underrun.
Stream started.
Stream underrun.
Stream started.
Stream cork
Stream device alsa_output.pci-0000_00_1f.3.analog-stereo suspended.
Stream device alsa_output.pci-0000_00_1f.3.analog-stereo.monitor suspended.
Setting audio-input to enabled
Stream uncork
Stream device alsa_output.pci-0000_00_1f.3.analog-stereo resumed.
Stream device alsa_output.pci-0000_00_1f.3.analog-stereo.monitor resumed.
Stream started.
Recording start
Recording stop
Stream cork
Stream device alsa_output.pci-0000_00_1f.3.analog-stereo suspended.
Stream device alsa_output.pci-0000_00_1f.3.analog-stereo.monitor suspended.
Setting audio-input to disabled

```



## Related issues 

https://github.com/QubesOS/qubes-issues/issues/6391 I am on Carbon x1 7th generation. Seems like it was working for me for a while then this upgarde broke it so i suspect this fix may also resolve this issue. But audio is still working in dom0 its just not getting passed to VMs. Seems that is not the same issue but they look similar.

https://github.com/QubesOS/qubes-issues/issues/6387 this does look like something that could be related seems like pulse audio cna be a bit tricky but this seems too coincidental to make sense.  

https://github.com/QubesOS/qubes-issues/issues/6306 is another but its probably that pusle audio is a bit of a tricky customer ;)
the file is silence.

**Comment by iamahuman** [comment]
@1osdfkjo12sdfa

> I am on Carbon x1 7th generation.

I think you're looking for #6198.

**Comment by 1osdfkjo12sdfa** [comment]
I was going to include that on my related issues but didn't because my internal mic was never working. I do have an external mic that works in dom0 and in vms. But after upgrade it stopped working in vms and just works in dom0. 

So feel like these are different issues tho for sure i am also effected by #6198 but i kind of thought that having internal mic disabled was a feature not a bug :P

**Comment by DemiMarie** [comment]
> I was going to include that on my related issues but didn't because my internal mic was never working. I do have an external mic that works in dom0 and in vms. But after upgrade it stopped working in vms and just works in dom0.
> 
> So feel like these are different issues tho for sure i am also effected by #6198 but i kind of thought that having internal mic disabled was a feature not a bug :P

It’s a bug.  The internal mic should work, but no qube has access to it unless it is attached to the qube.

**Comment by 1osdfkjo12sdfa** [comment]
I agree its a bug that the internal mic does not work. With my external mic I have been attaching it to the VM and no sound is picked up inside the VM. 

I spent some more time on debugging this issue. I upgraded to debian bullseye

```
cd /etc/apt/sources.list.d
sudo vim qubes-4.list
# replace first line with bulls eye 
 ```
 
 It looks like 
 
 ```
 # Main qubes updates repository
deb [arch=amd64] https://deb.qubes-os.org/r4.0/vm bullseye main
#deb-src https://deb.qubes-os.org/r4.0/vm buster main
 ```
 
 then did upgrade 
 
 ```
sudo apt update
sudo apt upgrade 
```

Tested the sound again 

1. Boot VM
2. Attach mic 
3. visit website that tests my sound 
4. tap the mic expecting to see some sign of this sound. 

But failed again. 

5. Then i tried to play some music in the VM and got that mic ringing again. 

I am down to spend smoe more tiem trying to debug this. If yall have some advice or tips let me know. The last thing i want to do is distract yall from higher leverage stuff so if i dont here back i will just continue my adventure :)

**Comment by 1osdfkjo12sdfa** [comment]
FYI I resolved my external sound issue by after attaching in Dom0

1. Opening pauvcontrol
2. Going to recording tab 
3. For the attached VM changing the Source from "Monitor of built in Audio and Stero" to "Built in Audio and Stero"

I think the update i tagged above changed the default for what pauvcontrol was passing to the child VM. 

Should i make a separate issue for this one cos feels a bit different than internal mic issues ?

**Comment by DemiMarie** [comment]
@1osdfkjo12sdfa Indeed I had the same problem.  My workaround was to edit `~/.config/pulse/[some-long-hex-string]-default-source`.

**Comment by deeplow** [comment]
> FYI I resolved my external sound issue by after attaching in Dom0
> 
>     1. Opening pauvcontrol in Dom0
> 
>     2. Going to recording tab
> 
>     3. For the attached VM changing the Source from "Monitor of built in Audio and Stero" to "Built in Audio and Stero"

This also solved it for me.

**Comment by DemiMarie** [comment]
I am not sure whether this is a PulseAudio bug or a Linux bug, but it should be possible to work around it by ensuring that the “Monitor” sources are never used unless explicitly enabled.

**Comment by andrewdavidwong** [comment]
Is this still a problem in 4.1?

**Comment by grey-olli** [comment]
> Is this still a problem in 4.1?

I've different hardware & my sound is not working now. Similar diagnostics - the card is showing sound output but no actual sound. I had such an issue before, later something has been fixed (I don't know what) & I had sound a month or even two. But yesterday I've rebooted & sound is gone. Attempt to boot older linux kernels doesn't help. I've sound in windows, so that is not a hardware issue.

[olli@dom0 ~]$ uname -a
Linux dom0 6.3.9-1.qubes.fc32.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun 23 19:49:58 CEST 2023 x86_64 x86_64 x86_64 GNU/Linux
[olli@dom0 ~]$ cat /etc/*release*
Qubes release 4.1.2 (R4.1)
NAME=Qubes
VERSION="4.1 (R4.1)"
ID=qubes
VERSION_ID=4.1
PRETTY_NAME="Qubes 4.1.2 (R4.1)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:ITL:qubes:4.1"
Qubes release 4.1.2 (R4.1)
Qubes release 4.1.2 (R4.1)
Qubes release 4.1.2 (R4.1)
cpe:/o:ITL:qubes:4.1
[olli@dom0 ~]$ 
 
I should probably make a separate issue with more details.
