### ISSUE TITLE
Attaching the same storage device to multiple domUs simultaneously results in data corruption

### ISSUE THREAD

**Issue by johnnyboy-3** [QubesOS/qubes-issues#6396]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Persistent storage attached to multiple AppVMs

**Brief summary**
From https://qubes-os.discourse.group/t/persistent-storage-on-multiple-domus/2775:
I managed to corrupt some files on my 2nd hard drive due to the fact that i attached them to 2 different domU’s and booted both up. The file system was ext4. I wished that qubes at least gives me GOOD VISIBLE WARNING that i might corrupt data if the storage is already mounted in another running domain.

Thanks & have a great day

**How Reproducible**
Attach Storage to two domU's and boot them simultaneously and use the storage.

**Expected behavior**
A warning that another domU is already running with the storage attached. Or if this is possible: allow both domU's to use the storage simultaneously.

**Actual behavior**
Files on disk get corrupted.

**Solutions you've tried**
Use the affected domains only one at once.

**Comment by iprid** [comment]
Well, logically speaking - you're trying to share a block device between two VMs. So each VM has its own kernel which has its own ext4 driver, so it's only logical that the VMs cannot synchronize their access. They don't know about each other. They don't share their kernel namespace. If you need this, I am thinking you can start a 3rd VM with NFS and export the Volume so that the other VMs can use it. Basically speaking ext4 does not allow sharing the filesystem in this manner directly.

I am also interested in a way of making it easy to share a volume between VMs though. I think it's very useful. But the only way I see it happening is if we have a storage VM which basically does the low-level filesystem stuff and exports the volumes via NFS or something else.
However I do not know how good the performance will be. Perhaps someone has tried network IO between VMs and can comment.

**Comment by DemiMarie** [comment]
IMO, we should allow the same device to be attached read-only to any number of qubes, or read/write to a single qube.  We should not allow more than one qube to have write access to the same block device.

**Comment by DemiMarie** [comment]
> I am also interested in a way of making it easy to share a volume between VMs though. I think it's very useful. But the only way I see it happening is if we have a storage VM which basically does the low-level filesystem stuff and exports the volumes via NFS or something else.

It’s perfectly safe to share a read-only block device.

**Comment by brendanhoar** [comment]
Clarification: 

1. It’s safe to share a read only device across many VMs from a filesystem perspective. 

2. It’s probably not safe to share a read/write filesystem with one VM and, at the same time, give read-only access to any other VMs due to their local caching. You’re not risking the filesystem shared but you are risking stability of the read on VMs.

Basically if across multiple VMs, all VMs have to be given read-only access, none can have write.

Brendan

**Comment by iprid** [comment]
> > I am also interested in a way of making it easy to share a volume between VMs though. I think it's very useful. But the only way I see it happening is if we have a storage VM which basically does the low-level filesystem stuff and exports the volumes via NFS or something else.
> 
> It’s perfectly safe to share a read-only block device.

If everyone is just reading - yes. But normally people would want at least one of the VMs to be write. 
So I guess, what @brendanhoar said.

So I stand by my previous comment that if we want simultaneous read/write => we need a storage VM to implement a filesystem on a block device and then to export it to other VMs. Problem is, that VM becomes an attack target and also all the VMs who share the volume could attack each other by malicious file metadata or other means - excluding the obvious, which would be for one of them to modify an executable on the shared volume so that other VMs can run it.
I guess this could be handled with read/write - basically giving write to only the VMs we trust and having a lot of read VMs.

A perfect scenario would be a volume of PDFs, generally they can be unsafe. So we can have a VM that will download those to a volume. And a read VM which can open them. So if we can make it that the read VM is disposable, we make things much simpler.

Ie. currently you have to start a disposable VM and manually copy the files you need.
But what if a disposable VM could be configured to start with read-only access to a shared volume?
Suddenly we can make it so simple to have VMs that will download stuff without opening it, and
disposable VMs without network access that can open the stuff.
So the attack vector is reduced => basically only the Browser/Client on the download VM can be attacked,
or perhaps the filesystem/file viewer could be attacked by malicious file data.
But we can harden the download VM a bit and make it so that it will not parse for example EXIF stuff,
and ofc to generate thumbnails/etc. So basically to treat any data as dirty.

From there we can build even more =>
Make the download VMs disposable too. So basically you start it => write files to the shared volumes.

Generally I think that Qubes is lacking in the filesystem isolation department. I mean currently we can't get
fine-grained isolation which allows sharing between VMs.

**Comment by DemiMarie** [comment]
Right now, if file sharing really is necessary, the best option I know of is SFTP over qrexec, using \*nix permissions and a chroot() to prevent any write access.  The SFTP server (which comes from OpenSSH) is considered trusted here.

**Comment by brendanhoar** [comment]
If there were a type of Qubes VM supported volume that could be read/write on a single VM and, at dom0’s reques, that VM could be asked to sync the volume and then not modify it for n seconds (what kind of guarantee?), just long enough for dom0 to make a snapshot (via lvm/btrfs) of that synced/frozen volume to allow don0 to share that snapshot with another VM...that could be useful.

I wonder how feasible that is?

-brendan

**Comment by unman** [comment]
On Fri, Feb 19, 2021 at 06:06:49PM -0800, Brendan Hoar wrote:
> If there were a type of Qubes VM supported volume that could be read/write on a single VM and, at dom0???s reques, that VM could be asked to sync the volume and then not modify it for n seconds (what kind of guarantee?), just long enough for dom0 to make a snapshot (via lvm/btrfs) of that synced/frozen volume to allow don0 to share that snapshot with another VM...that could be useful.
> 
> I wonder how feasible that is?
> 
> -brendan
> 

I have packaged rsync and sshfs over qrexec
(https://github.com/unman/qubes-sync), both of which allow for ro/rw
and access controls.
Rsync is far better than sftp imo, but sshfs reduces the overhead of
duplication of data.
I've experimented with other FS too, but havent felt the need to pursue
at length.

**Comment by iprid** [comment]
Can you give relevant docs on how to do that via qrexec?

**Comment by unman** [comment]
On Sat, Feb 20, 2021 at 02:09:59PM -0800, iprid wrote:
> Can you give relevant docs on how to do that via qrexec?
> 

If this is addressed to me, I provided a link, and included some
comments in the ReadMe.

**Comment by iprid** [comment]
@unman, thanks, will try it when I have time.

As for this ticket - perhaps it should be renamed to - Attaching the same storage device to multiple domUs simultaneously with at least one of the domUs with write permssion should not be allowed.

As I am thinking that the real issue here is indeed that the issue creator was able to do what shouldn't be allowed by the system.

**Comment by andrewdavidwong** [comment]
> @unman, thanks, will try it when I have time.
> 
> As for this ticket - perhaps it should be renamed to - Attaching the same storage device to multiple domUs simultaneously with at least one of the domUs with write permssion should not be allowed.
> 
> As I am thinking that the real issue here is indeed that the issue creator was able to do what shouldn't be allowed by the system.

In general, it is better for a bug report to provide a neutral description of problematic behavior and to allow the developers to arrive at their own conclusions about it rather than for the bug report to be prescriptive on the basis of prior self-diagnosis. The latter can often result in an [XY problem](https://en.wikipedia.org/wiki/XY_problem), for example.

**Comment by donob4n** [comment]
Is there any inconvenient if dom0 checks the device is not mounted in the domU before detaching it? How should it be done properly?

**Comment by iprid** [comment]
@donob4n, I think it's a good idea to have such checks in dom0. I think that qvm-block attaches/detaches storage.

**Comment by timdiels** [comment]
One esoteric use case where attaching the same device readonly to multiple VMs is useful is simultaneously backing up a device with borg to a local location in 1 VM and a remote location in another VM when paranoid about e.g. an undiscovered code execution vulnerability in the parsed response from a compromised remote borg server, which would compromise the local repo if in the same VM and eventually everything once I attach a writeable device to restore to. (The idea being to prefer the local location for backup restore. Running borg for both repos in the same VM would not save any time or space, it will redo all the work either way; so might as well split into 2 VMs). Just a nice to have, I'll just run them sequentially.

**Comment by andrewdavidwong** [comment]
Duplicate of #4692

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
