### ISSUE TITLE
Dom0 freezes during / after VM shutdown

### ISSUE THREAD

**Issue by mouflon72** [QubesOS/qubes-issues#6407]
**Qubes OS version**

4.0

**Affected component(s) or functionality**

Dom0 / Qrexec?

**Brief summary**

During/after shutdown of a VM, Dom0 partially freezes (I can partially interact with UI, also from VMs, but not all). The VM appears red in the Qubes Manager widget. When I choose "Kill" there, a message containing "Domain is powered off" appears, but nothing else changes.

**How Reproducible**
Almost always appears, although freeze times differ a lot

**To Reproduce**

1. shutdown a domain (no matter if standalone or from template)
2. see dom0 partially freeze
3. wait a few (sometimes up to 20 or more) minutes
4. VM shows powered off and system goes back to normal

**Expected behavior**
VM shuts down clean

**Actual behavior**

- Dom0 partially freezes. I can interact with some UI, also from VMs, but generally not open any new windows in VM or Dom0, switch tabs in browser etc.. Qrexec also does not react. Sometimes in between I can not interact at all.
- The VM appears red in the Qubes Manager widget. When I choose "Kill" there, a message containing "Domain is powered off" appears, but nothing else changes.
- The VM's log itself shows a clean shutdown, from what I can tell
- After some time the VM appears shutdown and everything goes back to normal

**Additional context**
This has been happening for quite a long time, i just manged to take care about it now. So i cannot say anymore, what specific package versions were present at that time, just that it's a 4.0 install.

**Solutions you've tried**
Went through a few upgrades of Xen, Kernels and so on for about a year, but no change

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
searched the issues archive and mailing list

**Comment by brendanhoar** [comment]
Wondering if this is caused by trim on a badly performing device...
1. Is Qubes et up with the default LVM storage option?
2. Is the problem worse when shutting down VMs with large volume settings?
3. Have you enabled pass down of trim to lower levels in the lvm config?
4. Do you have a SMR (shingled) hard drive that supports trim?

**Comment by mouflon72** [comment]
1. Yes. I grew the LVM at some point, but believe the problem was already there before.
2. Not sure, I will try to observe. Before, it seemed quite random to me. Today I waited more than 20 minutes for the first time before I hard reset the computer. That was with a 240GB VM.
3. Not knowingly
4. NVME SSD

**Comment by Geblaat** [comment]
I have the same issue. Standard Qubes 4.0 install with default LVM fileystem. For me it has been happening for quite a while as well. When Dom0 freezes, the HDD led on my laptop is also constantly blinking. I'm using a SATA SSD and have not changed default TRIM settings. I have to wait a few minutes at most, but I'm not using VM's as large as @mouflon72, my largest is a Windows 7 VM which is about 60GB. 
It may be related to size. The Windows VM is always slow to shutdown but I thought that may also be related to it being Windows. However, I think the freezing is longer for my Linux TemplateVMs than for my AppVMs, so size does seem to be a factor.
Note that the freezing also happens with shutting down DispVMs.

**Comment by DemiMarie** [comment]
Does `virsh -c xen:/// -- destroy -- <vm-name>` work?

**Comment by ejose19** [comment]
@DemiMarie the result is the same as `qvm-kill` or `qvm-shutdown`, all other VMs slowly become unresponsive to the point they freeze and nothing can be done until the problematic VM completely shutdowns.

**Comment by brendanhoar** [comment]
I have a bash script I use in dom0 (Qubes 4.0.x) to get an idea if the current I/O is related to **discards** down to the device (as I have enabled discards down to the device in lvm):

```
#!/bin/bash
watch -n 1 -d \
"if [ -d /sys/block/sda ] ; then pat1=sd pat2=loop; else pat1=xvd ; fi ; sync;echo --DISCARD TOTALS--;cat /sys/block/\$pat1*/stat /sys/block/\$pat2*/stat|awk 'BEGIN {print \"DRIVE IOS    QMERGES   SECTORS      MSWAITS\"} {printf \"%5i %-8s %s %15s %11s\\n\",NR,\$12,\$13,\$14,\$15}'"
```
Usually during shutdown (and/or lvm-thin volume removal) smaller, consecutive requests that would be contiguous are combined as larger I/O transactions so that by the time the request gets to the physical device, there are an optimized number of requests down to the device.  

For properly behaving SSDs, VM-initiated discards at shutdown (guest controlled) or the dom0 qubes-initiated blkdiscard of LVM thin volumes (usually volatile) after shutdown leads to only a minor slowdown. 

However, under some conditions I can think of, there may be a longer I/O storm: 

a) there was a conversation on the kernel list in 2019 about potential bad interactions between some SATA controllers and Samsung (maybe others) SSDs causing lots of IO pauses. Might be something you can see via dmsg or systemctl. FWIW, I use a now-ancient Samsung 850 mSATA as a boot drive on my primary qubes laptop and don't appear to have any issues. Notably, the 850 have the ATA_HORKAGE_NO_NCQ_TRIM flag in the libata quirks. i.e. https://lore.kernel.org/stable/yq1h87du82d.fsf@oracle.com/T/

b) there are other quirks/horkage in the driver  e.g. related to maximum contiguous trim sizes as well. Search for 'trim' in libata-core.c: https://github.com/torvalds/linux/blob/master/drivers/ata/libata-core.c

c) some HDDs that use Shingled Magnetic Recording (SMR) advertise the discard capability, but may not simply log the discard requests and may have to overwrite data in real time in order to mark the discard requests as completed up the driver layer. That would certainly slow things down.

Brendan

**Comment by ejose19** [comment]
@brendanhoar I've tested with the script you provided (adapting device id as this is `nvme`) and this was the result:

```
right before shutdown
--DISCARD TOTALS--
DRIVE IOS      QMERGES      SECTORS	 MSWAITS
    1 26159    41233        24303744	  396043

after shutdown completes
--DISCARD TOTALS--
DRIVE IOS      QMERGES      SECTORS	 MSWAITS
    1 26326    43173        24729984	  396768
```

The freeze still happened, and `watch` output also freezed, until the VM completed its shutdown. It's worth noting that cursor is still functional during this, but VMs & dom0 programs simply doesn't respond. Also something of interest is that there's a lot of single core operations while the shutdown is happening (which are visible in the `CPU Graph` widget).

For reference, heres the output for a VM with lower storage:
```
before
--DISCARD TOTALS--
DRIVE IOS      QMERGES      SECTORS	 MSWAITS
    1 26328    43174        24730496	  396772
    2 0        0               0           0

after
--DISCARD TOTALS--
DRIVE IOS      QMERGES      SECTORS	 MSWAITS
    1 26432    46021        25323776	  397720
    2 0        0               0           0
```
that VM doesn't cause a freeze and completes shutdown quickly (~5s).

I've noticed this behavior using 2 different `nvme` devices, so unless it's an issue directly related with `nvme`, I doubt it's device specific.

**Comment by brendanhoar** [comment]
Hmm - both VM shutdowns led to approximately the same amount (sectors and io count) of discards, so your symptoms do not appear to be discard-related to me.

**Comment by DemiMarie** [comment]
Looks like a dom0 kernel bug.  Only workaround I know is to *not* call `blkdiscard`, which is bad.

**Comment by brendanhoar** [comment]
> Looks like a dom0 kernel bug.  Only workaround I know is to *not* call `blkdiscard`, which is bad.

Hmm...

If this has to do with how the lvm-thin layer splits a large discard request into chunk-sized (typically 64KB) pieces, I wonder if utilizing the --step option (in the blkdiscard invocation) might mitigate the effect. E.g. by setting the step value somewhere between 512MB and 5GB or so, this may reduce the number of outstanding (but usually NOP) IO requests in flight...might be worth experiments?

B

**Comment by brendanhoar** [comment]
FWIW, I am not seeing any noticeable slowness under Qubes 4.0.3 + current-testing + dom0 kernel 5.11.12-xxx shutting down a VM with a 160GB private volume with about 50GB allocated. Drive is mSATA and discards are enabled all the way down the stack to the device (LVM2, luks, etc.).

**Comment by DemiMarie** [comment]
> FWIW, I am not seeing any noticeable slowness under Qubes 4.0.3 + current-testing + dom0 kernel 5.11.12-xxx shutting down a VM with a 160GB private volume with about 50GB allocated. Drive is mSATA and discards are enabled all the way down the stack to the device (LVM2, luks, etc.).

Does your hard drive support TRIM?  If not, the entire discard request might just be a no-op.

**Comment by brendanhoar** [comment]
> Does your hard drive support TRIM?  If not, the entire discard request might just be a no-op.

Yes it does. Samsung 850 EVO SATA.

With discard Enabled all the way down to the device.

Brendan

**Comment by brendanhoar** [comment]
> Not surprised.  Looks like the problem is that discards are `O(n)` *and* prevent other I/O from making forward progress.  Since the freeze is not totally abrupt, it appears that the problem is not a mutex per se, but either lock contention or sheer volume of I/O traffic.

Hmm, kernel optimizations aside...

...does the ioctl in blkdiscard wait to return until all discards are processed? If so, perhaps the --step option can mitigate as I suggested earlier and allow other pending io through during execution. 

There's also some discussion elsewhere about which particular device io scheduler / queueing mechanism handles this type of situation better (and it may be different for SATA vs NVMe) and that changing that configuration one a device might have positive impacts (see: /sys/block/$device/queue/scheduler )

Brendan

**Comment by DemiMarie** [comment]
> > Not surprised.  Looks like the problem is that discards are `O(n)` _and_ prevent other I/O from making forward progress.  Since the freeze is not totally abrupt, it appears that the problem is not a mutex per se, but either lock contention or sheer volume of I/O traffic.
> 
> Hmm, kernel optimizations aside...
> 
> ...does the ioctl in blkdiscard wait to return until all discards are processed? If so, perhaps the --step option can mitigate as I suggested earlier and allow other pending io through during execution.

I suspect that it indeed does.

> There's also some discussion elsewhere about which particular device io scheduler / queueing mechanism handles this type of situation better (and it may be different for SATA vs NVMe) and that changing that configuration on a device might have positive impacts (see: /sys/block/$device/queue/scheduler )

Good point!  Another option would be to modify `dm-thin` to issue discard requests with low priority somehow.

**Comment by brendanhoar** [comment]
> Good point! Another option would be to modify `dm-thin` to issue discard requests with low priority somehow.

With the knowledge that the dom0 kernel may have had horkage flags set for the physical device during device discovery, and that the flag(s) may, among other things, disable NCQ on the device because those particular devices don't correctly handle discards w/ NCQ...

..I'm curious about whether such changes to dm-thin can be appropriately decoupled below dm-thin.

In particular when lvm.conf is configured for issue_discards = 1 and thin_pool_discards = "passdown", layers below dm-thin would need to process the discard (trim or unmap) before any subsequent writes to the discarded areas are made.

Perhaps I am misunderstanding how the layer dm-thin or higher layers would be able to rearrange the discard requests with other IO going on.

Brendan

**Comment by brendanhoar** [comment]
> ...does the ioctl in blkdiscard wait to return until all discards are processed? If so, perhaps the --step option can mitigate as I suggested earlier and allow other pending io through during execution.

It appears the answer to my question is yes as per discussion here: https://github.com/QubesOS/qubes-issues/issues/5426

Based on that discussion, I submitted a PR here: https://github.com/QubesOS/qubes-core-admin/pull/404

Which has been approved.

The PR is a mitigation, and may not reduce the amount of time it takes a VM to fully shut down from a Qubes perspective (it's shut down from a Xen perspective pretty early in the process, but Qubes only considers it shut down after all volume storage operations are finished). 

Essentially, the change reduces IO (and UI) freezing by limiting the size of the iotctls made by blkdiscard to 1GB, and blkdiscard performs these ioctls serially. This allows other I/O to be queued to be serviced in between ioctl calls from blkdiscard.

B

**Comment by Warthog-Capital** [comment]
I would like to say that I have a similar problem. As far as I can see, only Fedora-based VMs cause this freeze, but that might be coincidental (e.g. depending on the AppVM size?). I don't interact with dom0 a lot, but what bothers me is that it causes other AppVMs to freeze, and it also slows down shutting down other AppVMs. So when I shut down multiple VMs right after another, I will constantly get "this VM did not shut down yet, do you want to kill it?" messages, until the first VM finally finishes shutting down.

Summary:
- dom0 stays mostly responsive, as far as I can tell
- AppVMs freeze
- Actions in other AppVMs, such as keyboard shortcuts or clicking at a certain position, are all applied at once, once the first AppVM finished shutting down (leading to a big chaos if I am impatient LMAO)
- Shutdown time is between 2 and 8 minutes, roughly
- My largest AppVM has a size of 280GB, others are mostly in the 10-30 GB range.
- I am using a SATA SSD

Hope this helps.
