### ISSUE TITLE
4.1 iso build fails building desktop-linux-awesome (awesome.spec) for fc33 vm

### ISSUE THREAD

**Issue by permezel** [QubesOS/qubes-issues#6418]
**Qubes OS version**

4.0

**Affected component(s) or functionality**

build

**Brief summary**

build fails

**How Reproducible**

100%

**To Reproduce**

1. Using a fc32 template VM in qubes 4.0
2. make distclean
3. make install-deps
4. Copy the example*/*r4.1.conf to builder.conf, per README.md
5. make qubes-os-iso
6. wait and hope  

**Expected behavior**

Successful ISO build so that I can test the install on Intel NUC10

**Actual behavior**

Failure.

```
-- Build files have been written to: /home/user/rpmbuild/BUILD/awesome-3.5.9/build/x86_64-redhat-linux-gnu
+ popd
~/rpmbuild/BUILD/awesome-3.5.9
+ make -C build VERBOSE=1 -j2 awesome
make: Entering directory '/home/user/rpmbuild/BUILD/awesome-3.5.9/build'
make: *** No rule to make target 'awesome'.  Stop.
make: Leaving directory '/home/user/rpmbuild/BUILD/awesome-3.5.9/build'
error: Bad exit status from /var/tmp/rpm-tmp.9k6hpl (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.9k6hpl (%build)
make[2]: *** [/home/user/qubes-builder/qubes-src/builder-rpm/Makefile-legacy.rpmbuilder:82: dist-package-build] Error 1
make[1]: *** [Makefile.generic:191: packages] Error 1
make: *** [Makefile:254: desktop-linux-awesome-vm] Error 1


```

**Screenshots**

**Additional context**

Find logs attached.
[fail.tar.gz](https://github.com/QubesOS/qubes-issues/files/6018802/fail.tar.gz)

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by fepitre** [comment]
@marmarek as this is remaining since a while, I suggest we drop it (see PR) until @woju updates it?

**Comment by dmoerner** [comment]
I think that @kalkin has refreshed patches for awesome 4.2 (https://github.com/kalkin/qubes-desktop-linux-awesome). I haven't tested them or seen how easily they apply to 4.3.

However, what I see about the new patches is that they only patch awesomerc.lua (the config file) and ship a new qubes.lua file. That means Qubes shouldn't need to ship a separate awesome package at all, but can just ship an `awesome-settings-qubes` package and use the Fedora awesome package. Normally this would present upgrade problems because of the epoch on the awesome package, but I assume in-place upgrades from 4.0 to 4.1 won't be supported.

**Comment by kalkin** [comment]
I myself do not use awesome anymore, but if there is interest I can prepare a minimal package for it.

**Comment by fepitre** [comment]
@kalkin sure. If you have updated the package to be able to build it under Fedora 32, please don't hesitate. Thank you.
