### ISSUE TITLE
Canary 26's header reads Qubes Canary 025

### ISSUE THREAD

**Issue by ctrlaltf24** [QubesOS/qubes-issues#6455]
**Qubes OS version (if applicable)**
N/A

**Affected component(s) or functionality (if applicable)**
https://github.com/QubesOS/qubes-secpack/blob/master/canaries/canary-026-2021.txt

**Brief summary**
The 26th Canary's title reads "---===[ Qubes Canary 025 ]===---" although it is canary 26, not canary 25.

**Additional context**
Doesn't really matter, probably not worth changing it as it would require another message on the secpack.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by iamahuman** [comment]
On Thu, Mar 11, 2021, 10:06 PM Andrew David Wong \<adw () qubes-os ! org\> wrote:
> Dear Qubes Community,
>
> *Note:* When preparing the announcement for this canary, we discovered
a typographical error in the title (the canary number "025" had not been
updated to "026"). However, one of the canary signers is not available
to re-sign an updated canary before the canary deadline. Rather than
invalidate this signer's signature by updating the canary text
immediately, we have decided to proceed with this announcement with the
existing canary text, accompanied with this note explaining the error.
As soon as all signers are available, the error will be fixed, and the
updated canary will be re-signed by all parties. Thank you for your
understanding.

**Comment by iamahuman** [comment]
On Thu, Mar 11, 2021, 01:06 PM Andrew David Wong wrote:
>Dear Qubes Community,
>
>*Note:* When preparing the announcement for this canary, we discovered
a typographical error in the title (the canary number "025" had not been
updated to "026"). However, one of the canary signers is not available
to re-sign an updated canary before the canary deadline. Rather than
invalidate this signer's signature by updating the canary text
immediately, we have decided to proceed with this announcement with the
existing canary text, accompanied with this note explaining the error.
As soon as all signers are available, the error will be fixed, and the
updated canary will be re-signed by all parties. Thank you for your
understanding.

**Comment by ctrlaltf24** [comment]
Thanks for the clarification iamahuman, closing.
