### ISSUE TITLE
change default XFCE menu from Applications Menu to Whisker Menu for R4.1

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#6487]
**The problem you're addressing (if any)**

i recently came across the [Whisker Menu](https://qubes-os.discourse.group/t/replacing-the-q-menu-with-the-better-whisker-menu/3415) in XFCE (thanks @deeplow!), and it is a clear UX improvement over the default Application Menu. it is also already included in Qubes R4.0 dom0. 

I would also propose incorporating the following tweaks in by default, shared by @deeplow:
https://www.pragmaticlinux.com/2021/03/install-and-configure-the-whisker-menu-as-your-xfce-start-menu/

**Describe alternatives you've considered**

I look forward to the [app menu re-write](https://github.com/QubesOS/qubes-issues/issues/5677) but I imagine the milestone for it is R4.2.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/5677

**Comment by ninavizz** [comment]
Hihi! Soooo... I love @deeplow's idea. However, I also am apprehensive of introducing more "ux churn." 

The broader experience for users with a product over time, needs to be the top priority for project sustainability; and the broader/overall experience of using an OS that effectively "yo-yo's" with experiential touchpoints across releases, is not good. Qubes Manager is a great example of that. It was re-done with the best of intentions, but the redesign was as difficult to use as the original in many ways; so users were burdened with both the adaptation factor, plus living with a high-friction design. 

I really, really, really dislike the endless-flyout interaction model the Vanilla menu is based on. For many reasons, it sucks for all users... and yet Marek (as just one example) hates KDE-ish modeled menus (Whiskers) because of how much clicking they require to get to things in nested menus (which I suspect Marek does a lot of, hehe). Swinging back, however, the endless-flyout pattern is especially problematic for users with developing or existing mobility restrictions because of how much they strain the wrist to use all the time.

Developers probably have a much stronger tolerance for uxchurn, than non-developer users—and while developers are the majority of QubesOS users, I'm hesitant to do things that would promote abandonment by non-developer users. 

While Whisker is a far more "visually-appealing" option than the Vanilla menu... what problems does it fundamentally solve for, and whose (user types) problems are those? The primary issue I personally see with the existing menu, is the cognitive burden of parsing "Domain: Qubename" and "Template: Qubename" with every single item; and, how long the lack of grouping-by-type, makes each individual item's name. Second, the typography (font, font weight, line-height, letter-spacing, font color(s), and anti-aliasing or lack thereof) of XFCE is optimized for small amounts of information for each item—whereas Qubes requires 2-3x the information of regular systems, for each favorite or app item entry. 

While Whisker Menu is certainly nifty, it won't fundamentally address any of the above. It will more than likely just wrap existing limitations of Qubes in a nicer presentation—with half the vertical space for scrolling. For power-users, I can't see that going over very well—yet power Linux users will also be able to easily set Whiskers themselves (I did!). 

Related to your last point: I would also like to see much smaller and more stable Qubes feature releases deploy more often... vs packing the volume of features into each that it takes years for each one. I realize the team is impossibly small for an OS with lord knows how many upstream and downstream dependencies, and a dev team that's also the QA team. But, the new appmenu should be coded and available in an Alpha version, as early as this Summer. It would be great to push-out a bugfix release, with the AppMenu included as one major feature—before waiting for a 4.2.0 version to be ready.

**Comment by mfc** [comment]
thanks for sharing your thoughts @ninavizz and for breaking this down. 

i totally agree re: UX churn. i think given how infrequent major releases are and how this change can closely model the App Menu (how Whisker Menu can feel like App Menu but **more**) i'm interested in digging deeper.

i would suggest giving it a try with the recommendations that deeplow shared. with those tweaks (specifically, "Switch categories by hovering"), the number of clicks are the same as App Menu.

i totally agree that Whiskers does not address the "Domain" and "Template" parsing any better than the existing App Menu (so #5677 is still very valuable!). 

so what does it address? from my perspective the UX gains are:

* integrated search
* integrated favorites
* shortcut to All Settings (maybe we could even add shortcut to Qubes Global Settings there)
* adjustable window (can be full screenheight if desired)

i am not aware of any UX minuses it introduces (would be interested to hear any). and for power users actually introduces a better foundation for customization than the existing App Menu.

maybe just to highlight further two of these aspects:

### integrated favorites

i have seen many Qubes users (who have not used XFCE before) starting off not aware that XFCE Panel creation is possible (for creating shortcuts/favorites). XFCE functionality is not at all advertised to the user, and instead the user is expected to learn about such XFCE functionality through self-guided research or others. having integrated favorites in the Menu creates a stronger foundation for new users to start organizing their qubes. the "recently used" menu feature can also help with this.

### integrated search

the integrated search is much superior to Application Finder, and is an effective aid for users with many domains or looking for particular app in particular domain. i think very helpful for newer users and for power-ish users.

----

in terms of timeline of the App Menu redesign (#5677), i defer to you and Marek -- if you think it will be ready for R4.1 then maybe we can skip this ticket entirely. if you don't think it will be ready for R4.1, then i would propose considering this ticket. 

also, seeing in that ticket that Marta will be building the new app menu from scratch - perhaps some Whisker functionality can be reused to make that process easier/faster.

**Comment by ninavizz** [comment]
> i defer to you and Marek

That just bloated my ego unreasonably, lol

> - integrated search
> - integrated favorites
> - shortcut to All Settings (maybe we could even add shortcut to Qubes Global Settings there)

The above as a generalized list of "Major pain-points can we pls consider a quick solution for" I do 100% agree with. It's the interaction model of Whiskers, itself, that would likely present the uxchurn issue... BUT we will hopefully "know" more about that, in 3-4 weeks once user research from #5677 has completed. I'm modifying the "Bessie" prototype to mimic Whiskers' interaction model, per these ideas, and am entirely open to a near-term implementation of Whiskers as a default as a "Step 1" solution in the App Menu saga.

The primary "problem" that remains for me, is that there is no way to designate an app w/in a Qube "a favorite," without the CLI. I mean, I could also totally see Marta adding in a column to #6366 that could solve for that quite easily. 

I also have a very hard time with XFCE's "customization" GUIs—and somewhat anticipate other non-Linux-native users will, too. As such, I'd want to really make sure it's "customized" in what is likely to be the most usable configuration, for all 4 menu locations. 

Longer-term, it's also my personal bias to start favoring sustainability of things build time gets invested on, over speed and ease. If/When XFCE is stepped-back from as a desktop environment, what, then? The upstream dependency remaining from working with hacked XFCE components, also concerns me.

**Comment by deeplow** [comment]
I blame myself a bit for talking so long to making more people aware of this. (in part because [of this](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)). I should have opened a ticket ages ago as I've been using whisker menu for a long time on Qubes. Perhaps then if I had opened a ticket like this then...

However, I don't know if I'd be up for the inclusion of this at this stage now that the [app menu redesign](https://github.com/QubesOS/qubes-issues/issues/5677) is under way. I would say if it is less than two years away, the constant change of UX may disorient some users (as @ninavizz mentions). If more than that, then I think having this as default could help out a LOT of user in the meantime.

> Longer-term, it's also my personal bias to start favoring sustainability of things build time gets invested on, over speed and ease. If/When XFCE is stepped-back from as a desktop environment, what, then? The upstream dependency remaining from working with hacked XFCE components, also concerns me.

I don't think this should be much of a concern. As-is, the whisker menu works just fine. It would not need any patches or hacks (if people want the older menu, they can always get it by switching the XFCE panel settings). So I would not be too concerned about an increased XFCE dependency as it would exactly the same.

On another note, if this moves forward, there should be concerns about how this change will be propagated. Would this override user's XFCE panel preferences or only affect new installations. If the later it may raise user confusion when reading the documentation as some images may show the "whisker" menu and the others the classic one. With their systems up-to-date some users may be confused about why they don't have that "fancy-looking-menu".

**Comment by ninavizz** [comment]
I'm honestly much more concerned about UX churn. Likewise: people have been waiting ages for `4.1` and its feature freeze was some time ago. Getting a **_stable_**, bug-free release, has to be a priority over everything else right now. In a point release, later? Maybe. But hastily rushing to add it to `4.1` I want to push back against.

Again, for project sustainability, a primary (if not #1) concern, is the lack of "Consumer Product" stability with releases. It's hindered the ability for people to adopt & retain use of Qubes who don't also have the patience to manage its quirks. My primary interest is user adoption and retention—and with such a tiiny team in charge of a product, where time is spent is essential to prioritize with care. 

How much time would it take to get Whisker into a point release after 4.1 (including testing), and would those cycles be worth it for a UX improvement that users will then have to re-adjust from, after the fully custom app menu is launched?

**Comment by ninavizz** [comment]
> I think short-term this idea would be great and makes lots of sense as long the interaction models are closer than the current menu.

Whisker is both a totally different interaction model, and is managed through XFCE stuff. This would be a not insignificant amount of churn. If anything, I think writing a blog post about Whisker with instructions for how to use it with Qubes, and Tweeting that many times over a few weeks, would be better. It's very easy to "turn on;" and that is a radically better experience, than "having" to get used to something new when you'd rather not.

**Comment by SvenSemmler** [comment]
My 2 cents:

I think the vast majority of new users that are not in the nerd 
category, will come from a Windows background.

I have my Whisker menu connected to the Win-button on the keyboard, so 
it works *exactly* as under Windows:


1) I hit the 'Win' button with my thumb and start typing what I want 
...exactly like in Windows, then hit return. I am not even looking anymore.

2) I pin my most frequently used Apps as Favorites to the "Start menu" 
... exactly like in Windows.


I get all your arguments about UI churn and I am sure there are many 
Journalists with Mac background ... but even those have probably used a 
Windows UI before. Is it best? I don't know, but at this point it's as 
common a pattern as the keypad on phone or the PRNDL in your car or any 
other omnipresent user interface.

**Comment by ninavizz** [comment]
I'm tailoring one of the two prototypes for user research, to match Whisker's interaction model.

If evidence from user research points to an asap change to Whisker as the default menu, ux-churn be damned, I'll be more ok with such a hasty change. BUT, when we have user research funded and about to happen in a couple of weeks, it feels nutty to make what feels like a pretty significant decision, w/o solid data (ie: data collected to research standards, not anecdotal GH/Forums/Reddit feedback, alone).

_Really_ not wanting to be discouraging—on an aside. Evidence is important, and when we're about to embark on a study we've been preparing for months for, it feels remis to make a move w/o it. With SecureDrop we've onboarded a number of journalists, already; so I also feel somewhat protective of their experiences with Qubes, now, too.

**Comment by SvenSemmler** [comment]
@ninavizz, really appreciate your work here. I am not pushing at all for a hasty adoption, especially if you have a study with our target audience scheduled. Glad to see you consider making this part of the study.  My comment was purely subjective. 

I too was a Mac user for over a decade before switching to Qubes. There I loved the Spotlight feature and before that I used a tool called Quicksilver. The idea is always the same: you usually already know what you want. I found the pattern of hotkey, type the first few letters of what I want and hit return to be very sticky once discovered.

**Comment by ninavizz** [comment]
@SvenSemmler That is very useful feedback Sven, TY!! 

Also, my... well, eagerness to _not_ push Whiskers into `4.1` isn't at all about the work I'm doing, as much a waryness around potentially imposing ux-whiplash. There could well be a lot to learn, from getting Whisker into a point-release... TBD. BUT, this ticket and so many others, are helping all of us understand what folks like/need from an app menu. Which will only help the entire project, in the long run. :)

And, regardless of how Whiskers may or may not be included as a default in a forthcoming release, I'd love to see @andrewdavidwong or @marmarta or @mfc maybe work with @deeplow on a blog article advising this as a "Hey, if you haven't tried this yet..." tip. (cough) including mention on how to que-up an app in a vm as "a favorite," which I have no idea how to do as of yet.

**Comment by andrewdavidwong** [comment]
> In a point release, later?

> How much time would it take to get Whisker into a point release after 4.1 [...]?

> Likewise, to having more insight around the expense involved in the work to make it a new default in a point release.

Point releases (e.g., "4.0.1") are only for backward-compatible bug fixes, not for new features, so it would have to wait for a new major (e.g., "4.0") or minor (e.g., "4.1") release (see https://semver.org/ and https://www.qubes-os.org/doc/version-scheme/).

-----

> And, regardless of how Whiskers may or may not be included as a default in a forthcoming release, I'd love to see @andrewdavidwong or @marmarta or @mfc maybe work with @deeplow on a blog article advising this as a "Hey, if you haven't tried this yet..." tip. (cough) including mention on how to que-up an app in a vm as "a favorite," which I have no idea how to do as of yet.

This seems like something for https://github.com/QubesOS-contrib.

**Comment by mfc** [comment]
so two actions i think we could take would be:

(1) look at what other OSes that ship XFCE by default do. 

this is helpful both in terms of making OS transition easier for new users and understanding what other communities decided from a UX perspective. 

the two most popular XFCE-based distros I'm aware of are Xubuntu and Manjaro, which both use Whisker Menu by default:
* **Xubuntu 20.10**: https://youtu.be/gSz_e6aH-YA?t=229
* **Manjaro 20.1**: https://youtu.be/2P8czcstnh8?t=276

if anyone is familiar with other XFCE-based distros please share any links showing what their default menu is!

(2) run a basic survey in the Qubes community forum (shared to Qubes Users mailing list) asking users which menu they prefer. 

in this survey we can link to deeplow's post on how to enable the Whisker Menu. we ask what menu the user prefers since they may not have been aware of the Whisker Menu (that is, we don't ask which menu they use). maybe doesn't need so heavily advertised as the user survey (so no News, no Twitter). Discourse has poll functionality so should be pretty straight-forward.

**Comment by SvenSemmler** [comment]
> how to que-up an app in a vm as "a favorite,"

right-click & "add as favorite" ... in whisker-menu

**Comment by mfc** [comment]
> 2) run a basic survey in the Qubes community forum (shared to Qubes Users mailing list) asking users which menu they prefer.

i have made an informal survey here: https://qubes-os.discourse.group/t/poll-which-q-menu-do-you-prefer/3473

i will wait for feedback on whether the post looks good before sharing it on qubes-users. i tried to be neutral in the language and presentation, and informative but not leading.

**Comment by ninavizz** [comment]
The primary issue I see with such an approach, is that users rarely "know" what it is exactly they need for a product to better serve their unique needs. One may be more "appealing" than the other, but that doesn't mean it will help them access things easier/faster. If anything, it concerns me that Whiskers may appear niftier, yet ultimately make it harder to find stuff (what I'm currently experiencing with Whiskers—and I would be very irritated if expected to research customization options to overcome, for a default widget). 

Survey design is a legit skill to yield findings that are safely actionable. @marmarta has done some survey work with a prior corporate gig, and obvs I'm able to do it as part of my broader skillset... but I also don't have an ounce of extra bandwidth to give atm. :(

Second concern, is that the segment of Qubes users in forums or Reddit is likely to be minute, against the total user-base. 

In the bigger survey we ran in October, some of the primary points of consistent user feedback were 
- frustration with buggy deploys
- lack of overall system stability
- hardware compatibility
- no visibility into a product roadmap
- usability
- major releases = giant timing unknown 

To me, all of those things feel the most urgent to address—as those are the reasons people abandon products. Usability is obvs certainly huge, but I don't see epic usability wins in Whiskers—yet tossing Whiskers into `4.1` does present too-high an opportunity to add friction to the other points. 

User abandonment = less funding and general support for the project. I want to see Qubes mature into a stable consumer-ready product. Journalists and other at-risk non-technical users, can't handle experiencing the aforementioned feedback points we got in the survey. To me, those feel like the most urgent things to focus on—with all other efforts, no matter how small, distractions.

**Comment by eloquence** [comment]
I've briefly tested Whisker on my Qubes 4.0.4 system. I see the following significant issues in my own testing -- it's possible these can be mitigated by tweaking its configuration:

- When I look at the list of applications for a given VM, I only see a list of icons. Qubes colorizes these by the VM color, which can make them almost unrecognizable -- text is essential to aid identification. The loss of labels makes it therefore much harder to navigate some menus with icons that are essentially just colored blobs (the "Files" icon is a good example).

- Incremental search is helpful, but without a different organizational approach, the search results are dificult to navigate -- matches may occur on VM name or application name, which are fundamentally different organizational levels. So if I type "f" I get a match for `fedora-32` and also for `Firefox`. To disambiguate searches clearly, I have to type so many characters that the search is barely saving me time at all. <br><br>For an incremental search that manages different search results elegantly, consider GNOME's built-in search feature: It presents results in categories like settings, applications, and files.

- At least when adding the whisker panel on my system, some AppVMs show a list of `. . .` instead of the actual applications. This is likely a configuration error on my part, or a bug that could be straightforwardly fixed, but I wanted to mention it.

Overall, I find the existing menu to be more suitable for Qubes OS in its current form; Whisker would likely require further customization to make it better in all respects, instead of better in some and worse in others.

Fundamentally, Qubes introduces complex new concepts for which existing menu paradigms are not a straightforward usability fit. IMO there is limited value in making this change now -- I would recommend instead a more systematic usability review consistent with the approach @ninavizz is advocating for in this issue, and an implementation of a menu system specifically suited for the Qubes use case.

**Comment by mfc** [comment]
>    When I look at the list of applications for a given VM, I only see a list of icons. Qubes colorizes these by the VM color, which can make them almost unrecognizable -- text is essential to aid identification. The loss of labels makes it therefore much harder to navigate some menus with icons that are essentially just colored blobs (the "Files" icon is a good example).

hey Erik, thanks for trying it out and sharing your thoughts. did you configure Whisker Menu as suggested in [the original post](https://github.com/QubesOS/qubes-issues/issues/6487#issue-841972788)? see here: https://qubes-os.discourse.group/t/replacing-the-q-menu-with-the-better-whisker-menu/3415

i'm seeing a lot of responses from folks who do not configure it as suggested. 

i feel a bit that my points are not getting directly addressed, so i will try to clearly address the points that have been raised by others and how they connect to my own.

# this suggestion does not address fundamental issues

I think we all agree on the importance of https://github.com/QubesOS/qubes-issues/issues/5677 and are all on the same page that the existing XFCE menu options do not "do justice" to what a Qubes user needs. this suggestion does not change the need for #5677.

# UX churn

as [Andrew explained](https://github.com/QubesOS/qubes-issues/issues/6487#issuecomment-809448269), UX changes should only be considered on major and minor releases (4.0 -> 4.1, 4.x -> 5.0) and not point releases (4.1.0 -> 4.1.1).

https://github.com/QubesOS/qubes-issues/issues/5677 has TBD release and even when the design is done, needs to be coded from scratch by @marmarta. @ninavizz you have already stated that [feature freeze already happened for R4.1](https://github.com/QubesOS/qubes-issues/issues/6487#issuecomment-808954556) so that strongly suggests these improvements will not be included in R4.1, and hopefully will be in R4.2.

therefore I don't think our fears of UX churn will be borne out by this. having iterative improvements on UX in minor releases I think is to be expected (and hoped for) by the user, and the very low user barrier (very similar UX experience) that can be made between the menus using the configurations shared previously (please again... [configure it as suggested](https://qubes-os.discourse.group/t/replacing-the-q-menu-with-the-better-whisker-menu/3415)).

# the informal poll

I hear [your feedback](https://github.com/QubesOS/qubes-issues/issues/6487#issuecomment-811548589) and agree it is not particularly helpful -- let us ignore it / not consider it in these discussions.

# usability & functionality

> make it harder to find stuff (what I'm currently experiencing with Whiskers

i would love to hear more about what is more difficult to find with Whiskers than Applications Menu. what are you searching for and not finding? how is it more difficult than the Applications Menu?

with the [settings shared by deeplow](https://qubes-os.discourse.group/t/replacing-the-q-menu-with-the-better-whisker-menu/3415) (which can be made the default configuration), the menu is **very, very, very similar** to the Applications Menu:
* same number of clicks to get to an item 
* same amount of text description per item
* same ordering of items, with the exception of location of System Tools

please, configure it as suggested. please tell me what you find is actually different or less usable.

if they can be easily made so similar, what does the Whisker Menu add?

it includes the following additions:
* integrated search
* favorites <-- _this is a huge help for new / non-power users_
* shortcut to All Settings 
* adjustable window (can be made full screenheight if desired, to mirror the feel of the non-adjustable Applications Menu)
* shortcut key to open (Windows key, etc) <-- _very common expectation of new users_
* scrollbar (rather than infinite scrolling with no understanding where you are on the list of domains)
* more customizable by user

for me these are very clearly benefits to the user, and especially most especially the new user. it is also clear that Applications Menu has had little development or functionality added and is the "legacy menu" of XFCE. but why listen to me when we can also look at what other projects that ship XFCE by default do?

the two XFCE-by-default distros that I could find also happen to emphasize user-friendliness. they both ship with Whisker Menu by default:
* Xubuntu 20.10 (user-friendly version of Debian): https://youtu.be/gSz_e6aH-YA?t=229
* Manjaro 20.1 (user-friendly version of Arch Linux): https://youtu.be/2P8czcstnh8?t=276

so then why do we use the Application Menu? well at the time we switched to XFCE, it was the only menu available (given the age of our dom0 Fedora version). since then, as we've upgraded the dom0 version we have gained the Whisker Menu as an option, because it is more recently (relatively) developed. 

Qubes already ships with Whisker Menu so it is with very minimal effort that we could provide an incremental but meaningful increase in usability for Qubes users, and most especially new users. 

please, please, please -- configure the Whisker Menu as suggested -- make it look exactly the same as Applications Menu -- then compare. thanks

**Comment by eloquence** [comment]
@mfc I did in fact follow those docs as closely as I could (I did not remove the existing menu and just put Whisker alongside it for testing purposes), but please note that I am on Qubes 4.0.4, not on a 4.1 nightly, and using the included version of the plugin. With the settings as they are in https://www.pragmaticlinux.com/2021/03/install-and-configure-the-whisker-menu-as-your-xfce-start-menu/ I do not see the behavior you're describing, or as screenshotted in that article; e.g., applications don't have labels.

If someone can provide precise instructions for the recommended state that will work on Qubes 4.0.4, I am happy to re-test.

**Comment by ninavizz** [comment]
> i would love to hear more about what is more difficult to find with Whiskers than Applications Menu. what are you searching for and not finding? how is it more difficult than the Applications Menu?

@mfc My own $0.02 in response to the above: in Whiskers the typography is bulky and lacks hierarchy, so is much more difficult to quickly scan than today's default App menu. XFCE's use of typography is generally not awesome, but for some reason it's just extra bulky in Whiskers (not about any one attribute, but many that cannot be customized in their GUI). 

Second, the lack of a Faceted Search presentation of the Search Results (per Erik's earlier comment) makes what it does generate, overwhelming and feel like bait-and-switch. Like Wordpress websites that use their default Search functionality. 

Yes, Favorites are huge—but there's also not an intuitive way for non-Linux/Windows users to make something a favorite in Whiskers. Yep, most Journalists in Europe and North America are Mac users. Even with its Favorites menu being an intuitive win for developer and Linux users, Whiskers still misses the mark on all the other points of benefit and values being sought in the new app menu design.

If Whiskers were more aligned with [the design principles and goals spoken to in the design brief](https://docs.google.com/document/d/1SCodeRkQjslFvGPiG2LMzyXc4ueR9yMzp9LEOBTwssY/edit#) I just posted to the AppMenu ticket, I'd consider it a worthwhile iterative improvement and not UX Churn. I don't see that alignment, though. It's some progression, and a lot of regression. It's also on me somewhat, for not creating and sharing the aforementioned document, earlier. 

I guess where I'm most puzzled, though, is being confused around why the push to make this a default in `4.1`, vs a well-advertised elective change individual users can easily make? All day I've struggled with my own push-back against this, because of the value _Favorites_ brings to new users. Where I find myself then swinging back to my initial apprehension, tho, is with removing user agency in forcing this as a default. 

When things change radically with any product, users need to be able to trust those changes are more for the better than not. It takes years and many releases, to cultivate that trust. I don't see Whiskers as a default in `4.1,` then a year later a whole new menu experience in `4.2` that's completely different, working towards that goal. 

Anywho, sorry I've been so dominant in this convo. I'll duck-out so other voices can get the floor, unless folks have specific questions for me.

**Comment by eloquence** [comment]
> there was never a discussion around choosing Applications Menu as the default, it just was, so it is nice to finally have this discussion around the Applications Menu and Whisker Menu.

I am as well, thanks for prompting the discussion. I must admit that after trying it for a while, I switched back to the default menu -- there were too many aspects of Whisker I found frustrating in everyday use, the scrolling behavior probably chief among them. It's IMO a bigger change than it may seem and I would recommend against making it for 4.1, but I'm glad users have the option to use it if they prefer it.

**Comment by ninavizz** [comment]
> the scrolling behavior probably chief among them

Well, crap. That is helpful to know. Funny, I just added that as a bullet in my research plan, to look for as either intuitive or desirable/not-desirable in the prototypes I built for testing, lol. Thx for the feedback, @eloquence!

> i'm not sure what a "well-advertised elective change" would be for Qubes (us tweeting "hey check out this feature that's not by default in Qubes"?).

@mfc By the above, I meant more than just a Tweet; like, write an article for the website. We should have a category on the website for "Tips" that just speaks to optimization opportunities for users with Qubes. We could feature articles speaking to compartmentalization, Joanna's older article about how she'd setup her laptop into "domains," one with a desktop tour of Qubes. Expecting all users to be in forums or on email lists isn't the best for many (which I went into in another issue recently, lol). 

Engaged community members could write Tips articles, and then you or Andrew would properly post them—with "Community" in place of author, and the author named at the beginning of the article. Write the article, and then blast it in forums and on email lists. Then Tweet it a few times—meaning compose/post the Tweet, but then RT it a few times so that folks in different timezones and engaged in Twitter at different points throughout a week, see it. 

Right now I see a lot of the community activity around "Ack, I can't do this!" or very technical topics. A more proactive approach to helping folks learn about making the best use of this very advanced tool (Qubes) that even our parents could benefit from using, I think would be really neat. :)

**Comment by andrewdavidwong** [comment]
> > i'm not sure what a "well-advertised elective change" would be for Qubes (us tweeting "hey check out this feature that's not by default in Qubes"?).
> 
> 
> 
> @mfc By the above, I meant more than just a Tweet; like, write an article for the website. We should have a category on the website for "Tips" that just speaks to optimization opportunities for users with Qubes. We could feature articles speaking to compartmentalization, Joanna's older article about how she'd setup her laptop into "domains," one with a desktop tour of Qubes. Expecting all users to be in forums or on email lists isn't the best for many (which I went into in another issue recently, lol). 
> 
> 
> 
> Engaged community members could write Tips articles, and then you or Andrew would properly post them—with "Community" in place of author, and the author named at the beginning of the article. Write the article, and then blast it in forums and on email lists.

Sounds nice in theory. In practice, Marek would probably have to review many of the articles to ensure the tips don't compromise security in unexpected ways, which would demand more of his precious time. If we skip this review, and someone follows the tips and ends up compromising their security, they'd blame us for posting it through official channels and thereby endorsing it. (No good deed and all that, which is why it's often better to say only what's required.)

> Then Tweet it a few times—meaning compose/post the Tweet, but then RT it a few times so that folks in different timezones and engaged in Twitter at different points throughout a week, see it. 
> 

Twitter already has their ICYMI feature for this. I'd be worried about annoying followers by repeatedly tweeting the same thing so many times. If we were going to do that with any message, I'd think it should be the most important ones.

**Comment by andrewdavidwong** [comment]
> Engaged community members could write Tips articles, and then you or Andrew would properly post them

Also, it's not as simple as "they write; we post," because frankly most people are terrible at writing, and most posts will require extensive revision (effectively rewriting) to be suitable for posting through official channels. Maybe one way around this is to have the editors at Qubes Community select a few of their best pages each month, then we could make an official post linking to those pages. Since our post would just have the titles and links along with a disclaimer that they're unofficial, it wouldn't require extensive vetting.

**Comment by mfc** [comment]
hey folks since this didn't happen and users can already beta the app menu rewrite (which will come out as R4.1 update) i am closing this ticket. feel free to comment/re-open if you think was a mistake.
