### ISSUE TITLE
Consistent revision timestamping among LVM and reflink storage pools

### ISSUE THREAD

**Issue by iamahuman** [QubesOS/qubes-issues#6498]
**The problem you're addressing (if any)**
The `reflink` storage pool names each volume revision based on the file's ctime, while the `lvm` storage pool does so based on the time the snapshot is _renamed_ from the main vid.

**Describe the solution you'd like**
Use the `lv_time` field from `lvs` output.

```sh
lvs --noheadings --config=report/time_format="%s" ... -o ...,lv_time
```

**Where is the value to a user, and who might that user be?**
The user can be less confused when attempting to restore the volume snapshot at specific point of time.

**Describe alternatives you've considered**
TBD

**Additional context**
TBD

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
TBD

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
TBD

**Comment by rustybird** [comment]
ctime for reflink revisions tracks when the file was renamed to `_path_clean` in `_commit()`, because the [`rename()` syscall causes an inode status change](https://unix.stackexchange.com/questions/211123/why-does-renaming-a-file-with-mv-command-alter-an-inodes-change-date-time). So it should already be the same as lvm_thin?

**Comment by iamahuman** [comment]
@rustybird That makes sense. Thanks!
