### ISSUE TITLE
Ship a hardened wpa_supplicant configuration

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6510]
**The problem you're addressing (if any)**

`wpa_supplicant` is a large, essential, and complex daemon with substantial attack surface.  In a default Fedora install, it runs unsandboxed and has free reign over the system.  In QubesOS, it is confined within `sys-net`, but there is no reason to make it any more tempting of a target than it needs to be.

**Describe the solution you'd like**

`wpa_supplicant` should run in a sandbox with limited access to resources.  This is not difficult to achieve; I achieved it myself in less than two hours.  PR coming.

**Where is the value to a user, and who might that user be?**

This will benefit any user who uses `wpa_supplicant`, which is the majority of laptop users.

**Describe alternatives you've considered**

None

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by qtpies** [comment]
Because of an issue I ran into I recently replaced wpa_supplicant with [iwd](https://iwd.wiki.kernel.org/) with little effort and I'm enjoying the benefits without any trouble yet. I mention this as it seems that wpa_supplicant will at some point be replaced by iwd, and it might be worth spending time on securing iwd instead of the old and complex wpa_supplicant? If you disagree please ignore my comment.

The only issue I did run into is that Fedora currenlty ships an old version of iwd (1.26) which has an [issue](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/101) with NetworkManager. I currently fixed this by changing sys-net to run from a Debian 10 template, as Debian ships 1.28.

**Comment by quantumpacket** [comment]
Has this made it into the 4.2rc?

**Comment by DemiMarie** [comment]
Nope

**Comment by marmarek** [comment]
This is a feature request for whatever distribution one uses for their sys-net, there is nothing qubes-specific here. In fact, it's less relevant for qubes than other distros due to having it sandboxed in sys-net.
