### ISSUE TITLE
Cant get into tty within HVM

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#6520]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
 HVM

**Brief summary**
User should be able to get into tty using 3 keybinding within HVM or using command from outside the VM within Dom0 (i know HVM is not attached and using Qubes kernel thus wont work but three keys should work)

**How Reproducible**
Install any OS .iso inside an HVM and try to enter to TTY, it will get you into the tty of Qubes instead of the HVM itself (if using keybindings), And if using `sudo xl console HVM` wont work. 

**Expected behavior**
getting to tty of the HVM

**Actual behavior**
getting into tty of Qubes

**Screenshots**
N/A

**Comment by TNTBOMBOM** [comment]
```
qvm-console-dispvm [qube]
```

Doesnt work in the HVM, Yes it will show terminal window but nothing you 
can type within it.

```
qvm-run -u root HVMname 'echo 4 > /proc/sys/kernel/sysrq'
```

HVMname: command failed with code: 1



> Similar to #5492, but to get into the console of any VM:
> 
> ```
> qvm-console-dispvm [qube]
> ```
> 
> To get into a TTY of an HVM qube that has its window showing, you may have to unraw the keyboard, and can then send keypresses with `xdotool`.
> 
> To unraw requires enabling the sysrq functionality (temporarily):
> 
> ```
> # qubes-compatible HVM:
> qvm-run -u root [qube] 'echo 4 > /proc/sys/kernel/sysrq'
> 
> # or, vanilla non-qubes HVM: login via qvm-console-dispvm and run the 'echo 4' command
> 
> xdotool selectwindow key alt+Print+r
> 
> # re-disable sysrq if you are concerned:
> qvm-run -u root [qube] 'echo 0 > /proc/sys/kernel/sysrq'
> ```
> 
> Then you can send the HVM keypresses with:
> 
> ```
> xdotool selectwindow key ctrl+alt+F1
> ```
> 
> ...then click on the window of the qube that should receive the keypress.
> 
> Change the keys (F1, F2, ... F7) as necessary.
> 
> Here is a quick script I've used, invoked as `qvm-switchtty qubenamehere 3`, to set the qubenamehere HVM window to switch to tty3.
> 
> <details><summary>qvm-switchtty</summary>
> 
> ```sh
> #!/bin/sh
> 
> if [ -z "$1" ] || [ -z "$2" ]; then
>    echo "usage: $0 qubename tty" >&2
>    exit 1
> fi
> qube=$1
> 
> if ! qvm-ls "$qube" &>/dev/null; then
>    echo "error: qube $qube not found"
>    exit 1
> fi
> 
> declare -i tty
> tty=$2
> if (( tty < 1 || tty > 12 )); then
>    echo "error: invalid tty $2"
>    exit 1
> fi
> 
> # look for the first window with the qube name as the classname
> win=$(xdotool search --onlyvisible --classname "$qube"|sort -n|head -1 )
> 
> if [ -z "$win" ]; then
>    echo "error: no window found for $qube"
>    exit 1
> fi
> 
> # 1. unraw the keyboard
> qvm-run -u root 'echo 4 > /proc/sys/kernel/sysrq'
> xdotool key --window "$win" alt+Print+r
> qvm-run -u root 'echo 0 > /proc/sys/kernel/sysrq'
> 
> # 2. send tty command
> xdotool key --window "$win" ctrl+alt+F$tty
> ```
> </details>
> 
>

**Comment by icequbes1** [comment]
Allow me to clarify as I don't want to distract from the ultimate intent of this issue - to get into a separate virtual console in an HVM qube.

I don't believe this issue describes a bug in Qubes, but it is a technique not readily accessible/documented. I recommend further discussion on the Qubes OS Discourse/mailing list, but in short:

It sounds you meant a *Standalone* (HVM) qube.

The first thing to try is sending keys directly to the HVM window (from dom0): `xdotool selectwindow key ctrl+alt+F1`.

If the HVM is in graphical mode and F1 or F2 (as executed above) don't appear to do anything, this is where it gets messy because we need to take the keyboard out of raw mode.

I am not an X11 expert, so the easy way is to type SysRq+r. If this is not a Qubes-native VM, try sending `xdotool selectwindow key alt+Print+r`, then the `ctrl+alt+F1` sequence. In a Qubes-native VM, SysRq is disabled for security reasons.

If SysRq is disabled, the option is to temporarily enable it (just keyboard / mask value "4"). Alternatively from _within_ the HVM window and a terminal inside that, try `kbd_mode -u -C /dev/tty7` to set tty7 to Unicode mode. Now try the `xdotool ...` commands from dom0.

If your standalone HVM has no console output at all (via `qvm-console-dispvm` in dom0), there are two possibilities:

1. OS in the HVM is not Xen-aware and has no serial port
2. OS is Xen-aware but not configured to use the Xen console

For scenario 2, the fix is to specify kernel parameter `console=hvc0` when the OS inside the VM boots.

For scenario 1, it gets messy. A serial port pty must be added to the libvirt xml template file...and I am not sure why, but the stubdomain `init` file needs to be patched to replace hvc1 with hvc0 when executing qemu (bottom line: there needs to be `-serial /dev/hvc0` argument in the qemu command).

At dom0:/etc/qubes/templates/libvirt/xen/by-name/[qube-name].xml

```xml
{% extends 'libvirt/xen.xml' %}
{% block devices %}
   {{ super() }}
    <serial type='pty'>
      <target port='0'/>
    </serial>
{% endblock %}
```

In the stubdomain `init`, prior to executing `qemu -sandbox ...`, I have:

```shell
dm_args=$(echo "$dm_args"|sed "s/hvc1/hvc0/")
```

I will make a PR against `qubes-doc` so the procedure is more readily accessible. But I am also unsure if this is the recommended way to do this - I am hacking at it.
