### ISSUE TITLE
kernel-5.11.8: LUKS passphrase truncated

### ISSUE THREAD

**Issue by throwException** [QubesOS/qubes-issues#6539]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
LUKS, cryptsetup, kernel-5.11.8

**Brief summary**
A LUKS passphrase of exactly 64 characters is truncated to 63 characters when added using cryptsetup luksAddKey. Passphrases of 63 or 65 characters seem unaffected. The bug only appears on kernel 5.11.8 from the unstable repo.

**How Reproducible**
Always

**To Reproduce**

1. `sudo cryptsetup luksAddKey /dev/$disk`
2. Type an existing passphrase
3. Type the now passphrase "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
3. Repeat the new passphrase
"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
4. `sudo cryptsetup luksOpen --test-passphrase /dev/$disk`
5. Type the passphrase "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde"

**Expected behavior**
The truncated passphrase should not work.

**Actual behavior**
The truncated passphrase works.

**Additional context**
* Manually entering the full 64 characters passphrase works
* Piping the full 64 characters passphrase into stdin does not work
  `echo
"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef" |
sudo cryptsetup luksOpen --test-passphrase /dev/$disk`

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://linux.die.net/man/8/cryptsetup

**Comment by 0spinboson** [comment]
so kernels 5.11.11 and .12 work fine?

**Comment by marmarek** [comment]
5.11.12 is same.

This is very interesting issue. In fact, the key issue here is that read(2) returns only 64 bytes for 64 bytes + newline input (the newline can be retrieved with subsequent read(2) call), while returning the all the data including newline for any other input. Technically, this is perfectly fine behavior according to POSIX and the issue is that cryptsetup calls read(2) just once, instead of reading until newline. But the kernel behavior is quite interesting here.

Minimized test case (01234.... is typed/pasted, then enter and then ctrl+d if script hasn't terminated):

```
$ python3 -c 'import os; print(repr(os.read(0, 100))); print(repr(os.read(0, 100)))'
0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
b'0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'
b'\n'
$ python3 -c 'import os; print(repr(os.read(0, 100))); print(repr(os.read(0, 100)))'
0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde
b'0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde\n'
b''
$ python3 -c 'import os; print(repr(os.read(0, 100))); print(repr(os.read(0, 100)))'
0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef1
b'0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef1\n'
b''
```

And indeed on kernel 5.4.x it behaves differently.

**Comment by andrewdavidwong** [comment]
Are we waiting for an upstream fix, or is there work to do on the Qubes side for this?
