### ISSUE TITLE
Add Docker as a VM type

### ISSUE THREAD

**Issue by vporton** [QubesOS/qubes-issues#6550]
**The problem you're addressing (if any)**
- Virtualization is slow.
- Disk space is much wasted and fragmented if using VMs.

**Describe the solution you'd like**
Add Docker as a new VM type.

**Where is the value to a user, and who might that user be?**
- users with small disks or much data
- users requiring high performance (especially GPU access)

**Describe alternatives you've considered**

**Additional context**
- This works only with Linux, AFAIK. I think, it also "binds" to a certain kernel version.
- Is Docker as secure as real VMs? It should probably display a warning that it's a less secure option.
- Docker seems not to support "template VMs" (but we can mount multiple filesystems as probably even better alternative).
- Docker would probably also more easily support per user VMs than real VMs do.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by vporton** [comment]
Also Docker allows to transfer files even when "powered off".

**Comment by marmarek** [comment]
Docker is great technology for conveniently packaging whole appliances and not carrying about dependencies, but not really as a security barrier. The most important drawback is sharing the same monolithic kernel between multiple containers - this means:
 - much larger attack surface - easier to escape from a container than from a VM
 - no way to isolate individual drivers (those are part of the kernel) - which we need for Usb VM or Net VM

So, as a generic replacement of VMs, containers are no-go. But as an added layer it could be an option (for example instead of multiple VMs with similar trustworthiness, have one VM with with multiple containers). It is still a challenge to do it right - especially if we are talking about GUI applications. In fact, it is already possible to (manually) run docker inside VM and also some modern packaging solutions use containers themselves (flatpak, snap). Those aren't as strongly isolated as VMs in Qubes, though.

**Comment by ctrlaltf24** [comment]
Some considerations/history
- https://github.com/QubesOS/qubes-issues/issues/2683
- https://www.qubes-os.org/news/2018/01/22/qubes-air/#under-the-hood-qubes-zones
- The isolation between containers that docker provides is far weaker than that of Xen. 
- It would make more sense to implement LXC containers first (as both Xen, QEMU and LXC all support libvirt) to overcome the container related issues first, then add support for docker, as it will need to integrate with a new framework (besides libvirtd)
- The Qubes brand "A reasonably secure operating system" does not make sense to devote developer hours to a hypervisor that is less secure
- The hypervisor is presently a single point of failure in the entire design, if the hypervisor (dom0) is compromised, its all over. There is some protections against storage.
- The tooling the Qubes project has created to be able run Xorg applications within virtual mcahines, various proxies, ect.
- everything marmek said

**Comment by ctrlaltf24** [comment]
>  But as an added layer it could be an option (for example instead of multiple VMs with similar trustworthiness, have one VM with with multiple containers

Will "Qubes Air" support this kind of nesting?

**Comment by andrewdavidwong** [comment]
Closing as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by marmarek** [comment]
> Is "Qubes Air" planned to support this kind of nesting?

On a high-level - yes, the plan is to support several different types of "qube"s connected into one system. Theoretically, some of those qubes may actually be nested in another VM. Whether it will support docker specifically - that's yet to be seen, but likely not initially.
