### ISSUE TITLE
Dispvm automatically killed just after being created. qvm-open-in-vm / OpenURL

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#6562]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

qvm-open-in-vm "@dispvm:XX" / OpenURL

**Brief summary**

Disposable VM are automatically killed if the callee software print something in stdout (qvm-open-in-vm)

**How Reproducible**

100%

**To Reproduce**

Prerequise: 

Take two different disposable VM, from different template. 
One is fedora 33, one is debian 10.

In both, run "firefox" in a terminal and look at the output (stdout / stderr)
Currently, in debian 10 (firefox-esr), stdout is empty.
Currently, in fedora 33 (firefox); stdout is not empty: it contains "[GFX1-]: No GPUs detected via PCI"

(the difference is the firefox version)

If everything is ok until now, you can reproduce the issue and test it.

1. run ``` qvm-open-in-vm '@dispvm:YOUR_FEDORA_DVM' 'https://anyurlwedontcare.com' ``` 
2. run ```qvm-open-in-vm '@dispvm:YOUR_DEBIAN_DVM' 'https://anyurlwedontcare.com' ```

**Expected behavior**

Both dispvm are displaying a firefox GUI

**Actual behavior**

Only debian dispvm is displaying a firefox GUI.
Fedora dispvm have been automatically killed

**Screenshots**

**Additional context**

**Solutions you've tried**

Anything that doesn't send back stdout to qrexec-fork-server is working.
Workaround example: replacing 
``` exec qubes-open "$url" ``` by ``` exec qubes-open "$url" >&2 ``` in ```/etc/qubes-rpc/qubes.OpenURL```

(too tired atm to properly think about a better workaround than that).
 

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Maybe related to https://github.com/QubesOS/qubes-issues/issues/5016

**Comment by andrewdavidwong** [comment]
Possibly related: #6346

**Comment by marmarek** [comment]
The above change indeed workaround the issue, but the real problem is on the sending side:
https://github.com/QubesOS/qubes-core-agent-linux/blob/master/qubes-rpc/qvm-open-in-vm#L51
```
        exec /usr/lib/qubes/qrexec-client-vm "$target" qubes.OpenURL /bin/echo "$filename"
```

Here, the client side of the call is `/bin/echo`, which ends as soon as it prints the URL to open. Especially, it doesn't wait for the web browser to terminate (by waiting for EOF). This means, writing to such (terminated now) process will result in EPIPE error, and will close the connection (actually, this behavior is different in R4.1, where connection is not closed in this case).

So, the proper fix is to wait on the client side for EOF (discarding all the data?). I'm not sure what's the most elegant solution for that, some untested ideas (not as concise as the original):
- `echo "$filename" | /usr/lib/qubes/qrexec-client-vm "$target" qubes.OpenURL >/dev/null`
- `exec /usr/lib/qubes/qrexec-client-vm "$target" qubes.OpenURL /bin/sh -c 'printf '%s\n' '$0'; cat >/dev/null' "$filename"

**Comment by neowutran** [comment]
Thanks :) 
Both of your idea work as expected. I closed the previous pull request and opened a new with the "cat >/dev/null" solution. 
Don't know what is the most elegant solution, one is shorter, one is a little bit more explicit that we need to wait for EOF
