### ISSUE TITLE
Allow infinite retries for LUKS password by default

### ISSUE THREAD

**Issue by herypt** [QubesOS/qubes-issues#6608]
**The problem you're addressing (if any)**
After entering the disk encryption password three times incorrectly you need to restart the computer before being able to try again.
**Describe the solution you'd like**
Allow infinite tries by default by adding `tries=0` to `/etc/crypttab`.
**Where is the value to a user, and who might that user be?**
All users that have a long password and type it incorrectly sometimes would benefit from this.
**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/6530
https://github.com/QubesOS/qubes-issues/issues/3812

**Comment by unman** [comment]
On Fri, May 14, 2021 at 02:18:38AM -0700, herypt wrote:
> **The problem you're addressing (if any)**
> After entering the disk encryption password three times incorrectly you need to restart the computer before being able to try again.
> **Describe the solution you'd like**
> Allow infinite tries by default by adding `tries=0` to `/etc/crypttab`.
> **Where is the value to a user, and who might that user be?**
> All users that have a long password and type it incorrectly sometimes would benefit from this.
> **Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
> https://github.com/QubesOS/qubes-issues/issues/6530
> https://github.com/QubesOS/qubes-issues/issues/3812
> 
> 
> 

Limiting the number of password attempts strikes me as good practice,
and is pretty standard in the industry.

**Comment by andrewdavidwong** [comment]
> Limiting the number of password attempts strikes me as good practice, and is pretty standard in the industry.

Indeed (while acknowledging that the security benefits are limited, since unlimited attempts can be run against the encrypted data directly).

Moreover, if we're just inheriting this setting from upstream, then I see no  Qubes-specific reason to alter it. In that case, this request should be submitted upstream instead.

**Comment by ninavizz** [comment]
The reason I believe this issue was created, is because of #6530 — which is a Qubes-specific reason to alter it. 

On one hand, I don't want to create a security vulnerability with this... and I am not a security expert. On the other hand, when my cat strolled across my laptop and somehow got the screen that prompted me to file #6530, the resulting screen had my stomach drop to the floor in panic. 

So there are two solution opportunity paths: one, don't limit the number of password attempts. Or two, do something about the screen in #6530. 

Thoughts?

**Comment by andrewdavidwong** [comment]
> The reason I believe this issue was created, is because of #6530 — which is a Qubes-specific reason to alter it.
> 
> On one hand, I don't want to create a security vulnerability with this... and I am not a security expert. On the other hand, when my cat strolled across my laptop and somehow got the screen that prompted me to file #6530, the resulting screen had my stomach drop to the floor in panic.
> 
> So there are two solution opportunity paths: one, don't limit the number of password attempts. Or two, do something about the screen in #6530.
> 
> Thoughts @marmarek? @andrewdavidwong I don't want to reopen an issue w/o your blessing, so am leaving this closed.

I understand what you're saying, but I still don't think this issue really has anything to do with #6530. #6530 is essentially about not wanting to show a scary-looking screen to the user. This issue is about the number of allowed password attempts. They are conceptually orthogonal. There are many ways to trigger scary-looking screens, and running out of password attempts is only one of them. So even if, in practice, setting an unlimited number of attempts prevented the scary screen, it would be the wrong solution to the problem.
