### ISSUE TITLE
"Warning: Enforcing GPG signature check globally..." causing panic and confusion

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6643]
**Qubes OS version**

`R4.0`

**Affected component(s) or functionality**

Updates

**Brief summary**

There is a new(ish) warning when performing an update:

> Warning: Enforcing GPG signature check globally as per active RPM security policy (see 'gpgcheck' in dnf.conf(5) for how to squelch this message)

From a purely technical and theoretical perspective, this warning is fine in itself. From a practical real-world perspective, it is not. The problem is that many Qubes users don't know how to react to it, so they panic.

**To Reproduce**

Perform normal updates

**Expected behavior**

Most likely, one or more of the following:

1. The developers didn't consider how users would respond to this message.
2. The developers expected that users would understand the message and follow what it says.
3. The developers expected that users would understand the difference between a *warning* and an *error*.

**Actual behavior**

Predictably, many users do not understand the message and are totally freaked out by it. They think it's a bug and/or that their installation is broken, and they are desperately trying to figure out what to do about it.

**Additional context**

Lots of questions about this on the forum, mailing lists, Reddit, etc.

**Solutions you've tried (and proposed solutions)**

Responding to each question individually (@unman has probably done this the most), but this is incredibly inefficient, and the whole mess could have been avoided by a bit more thoughtful consideration beforehand.

At this point, it's already out there, so a better solution now would be to push an update that does something about this message for all users, whether that means changing the wording, squelching the message, or something else.

In the future, please feel free to run this sort of thing by me before pushing it live. By no means do I claim to be able to foresee or solve every problem, but in this case it would have been easy to point out in advance that many users would likely not understand this message and react negatively to it.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by marmarek** [comment]
The warning is a result of a https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-067-2021.txt fix. Or rather a band-aid we decided to apply, because the upstream RPM developers (and Red Hat Product Security) were unwilling to push the fix in a timely manner.

In fact, this band-aid is not harmless, it does have side-effects (https://github.com/QubesOS/qubes-issues/issues/6522).

Now, a similar band-aid is [applied at DNF level](https://github.com/rpm-software-management/dnf/commit/4747e369c1b5b406688ff0be5447ebd0c29575a6), in a way that avoids such warning and side effects, I think we can drop our version, ensuring new enough DNF version is installed first.
