### ISSUE TITLE
All disposable qube types (template and app vm) should have the disposable icon

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6709]
**Qubes OS version**
4.1

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).**
Nope.

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**
Nope. I'm me. I just provide feedback on JPGs.

**Affected component(s) or functionality**
App Menu and possibly Domains Menu and Qube Manager and Windows Manager.

**Brief summary**
If it's "disposable" anything, it should get the qute double-qube icon with the solid one on the top, and the transparent on on the bottom. In 4.1, currently, Disposable Templates have the regular solid qute qube icons intended to only be used with app vms. 

With #6665 disposable templates and disposable app vms will be clearly disambiguated. We can't fix that with 3rd party menus. No 16x16 icon could successfully communicate those semiotics with intuitive meaning to everyone.

**How Reproducible**
Persistent. 

**To Reproduce**

1. Ask Marek to send a screenshot of 4.1
2. Marek sends a screenshot of 4.1's appmenu, and affirms that's what it looks like in the current build
3. Nina see screenshot and gasps
4. A conversation in ensues, during which @marmarek agrees this should be fixed

**Expected behavior**
Any item in the app menu that opens an ephemeral vm for a user, has the disposable-qube icon on its listing.

**Actual behavior**
I'm sorry, I'm being a touch obnoxious with this unusually simple issue and trying to respect the ask to not delete parts of templates. 

**Screenshots**
Taken by @hackerncoder and shared with me by @marmarek 
![r4 1-menu1](https://user-images.githubusercontent.com/8262612/122321644-0c07e080-ced9-11eb-939e-66f0cad4482d.png)

**Additional context**
Nope

**Solutions you've tried**
Photoshop

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
Nope

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
Nope

**Comment by andrewdavidwong** [comment]
> Users are also unlikely to care if they're opening a disposable template, vs a disposable app vm—outside of memory issues. 

This is an incredibly dangerous misconception. Doing something in a DisposableVM Template when you meant to do it in a DisposableVM can be a *fatal* mistake.

It's a bad idea to treat DisposableVMs and DisposableVM Templates as if they're the same type of thing. Users already get confused about this.

**Comment by ninavizz** [comment]
@andrewdavidwong I discussed this with @marmarek in Wire, and he seemed to agree with what I proposed so I created this issue. Per the screenshot: as I understood Marek to explain—the top item in the menu, is a Disposable VM Template. If as a user I were to go to it to open Firefox, it would then open a Disposable VM, with just Firefox running in it. It would not in any way modify that VM template. 

The one Qubes machine I have at home, I cannot modify—because it needs to be kept to its SecureDrop configured settings. So, I am not able to nose around and test things. 

Question: How are disposable vm templates and disposable vms in the app menu, visually disambiguated, today? If they are not, then how would this issue create a problem? Yes, I looked in the docs, and did not see any screenshots—which in and of itself, felt problematic. 

Final point, it seems problematic to allow users to configure Templates at all, from the app menu. Which would need user research to validate before moving on. "Doing something to a Template" should never be possible, from the app menu. That's not what it should be for, and seems like a perfect opportunity for user error. Restricting configuration stuff to Qubes Manager for Templates, seems like a no-brainer isolation of functionality to prevent user error, to me.

**Comment by andrewdavidwong** [comment]
> the top item in the menu, is a Disposable VM Template. If as a user I were to go to it to open Firefox, it would then open a Disposable VM, with just Firefox running in it. It would not in any way modify that VM template.

Correct. That is how it works right now (and is likely to be confusing for many users).

> Question: How are disposable vm templates and disposable vms in the app menu, visually disambiguated, today?

There are (at least) two kinds of DisposableVMs: (1) "named"/"static" DisposableVMs, which can have a permanent app menu entry and (2) "regular" DisposableVMs (with names like `disp123`) that do not have an entry in the app menu, since they're temporary.

Currently, "named"/"static" DisposableVM app menu entries are indistinguishable from regular persistent (non-disposable) VM entries. There's nothing indicating that they're disposable. However, DisposableVM Template app menu entries have a special icon (two curved arrows forming a circle superimposed on the colored padlock icon).

> Final point, it seems problematic to allow users to configure Templates at all, from the app menu. Which would need user research to validate before moving on. "Doing something to a Template" should never be possible, from the app menu. That's not what it should be for, and seems like a perfect opportunity for user error. Restricting configuration stuff to Qubes Manager for Templates, seems like a no-brainer isolation of functionality to prevent user error, to me.

I don't have an opinion about this right now, but here are two related pieces of information that might be useful:
1. Currently, regular (not disposable) TemplateVMs have app menu entries. This means that, currently, the app menu can be used to start apps inside of regular TemplateVMs but not DisposableVM Templates (barring any advanced menu manipulation).
2. Users will need some way to start up apps inside of their DisposableVM Templates in order to configure them. (This does not apply to all users or all DisposableVM Templates and should be a rare occurrence.) Non-technical users may struggle to figure out how to do this unless we provide some easy way to do it. I think the usual current method is to start a terminal emulator in the DisposableVM Template, then start the desired apps from that terminal.

**Comment by ninavizz** [comment]
![giphy](https://user-images.githubusercontent.com/8262612/122471920-b84ad500-cf74-11eb-8b0d-d7d71c1d62f1.gif)

**Comment by ninavizz** [comment]
@andrewdavidwong Okee doke—this totally breaks some of my own rules, but also feels like a potentially good "hack" of how today's menus order things alphabetically, to present _Disposable Templates_ distinctly enough to hopefully avoid user error... and to also avoid confusion between Disposable VMs and App VMs. Thoughts?

![r4 1-menu1-3](https://user-images.githubusercontent.com/8262612/122502953-6c1b8700-cfac-11eb-8c9b-d1e3217e54b1.png)

**Comment by andrewdavidwong** [comment]
I can see it potentially working. Curious what others think.

**Comment by brendanhoar** [comment]
This is getting closer!

Is there an icon type for "Named disposable vm"? This is an appvm that throws away changes on shutdown, but runs one and only once instance under the same name each time (instead of multiple instance under the disp{1..9999} names like standard disposable VMs). 

Is there an icon type for "Named disposable as system vm"? As above but also providing system services. As per the Qubes documentation, that is one alternate way to ensure sys-net, sys-usb, etc. can be configured in an "even more safe" configuration. 

[Also there's a way to start up named disposable VMs without throwing away changes (e.g. to set wifi credentials).]

Lastly are these officially called "Named Disposable" or "Static Disposable"? I've read both and I did not find either on the Qubes Glossary page.

**Comment by andrewdavidwong** [comment]
> Lastly are these officially called "Named Disposable" or "Static Disposable"? I've read both and I did not find either on the Qubes Glossary page.

There's no official term yet. "Named" seems to be more common, but the fact of having a name is sort of incidental to what sets these apart. "Static" might have unintended connotations.

**Comment by ninavizz** [comment]
@brendanhoar So... the thing with icons, is that no icon should exist that's not clearly intuitive. As I'm typing this in the GitHub browser UI, there are icons immediately above this window for text styling, and icons below to indicate different parts of the UI. All of these icons are one color, no gradients, and probably intuitive to a majority of users. 

Only one of these icons speaks to a concept unique to GitHub (Markdown), and most of the icons speak to semiotics common in text editors and webapp experiences, everywhere.

While I could create an icon to mean literally anything, its value would be diminished significantly and it'd add to the user's cognitive burden (or it'd just serve no purpose) if it didn't prompt an immediate semiotic association. Similarly—when a user is working in an environment unlike any other (so, Qubes) there are only so many "unique things" they can retain an intuitive semiotic association to. 

As an example: I used to work on an HR app, and one of the PMs wanted every section to have unique identifying icons. I pushed-back, because when there are a bunch of icons unique to one isolated ecosystem in the world, it's hard for users to intuitively then remember "Oh, that icon is for 'x-hr-task' and that icon is for 'y-applicant-task', of course!" 

We see text editors across multiple app experiences, so text editor icons have become ubiquitous—and are thus intuitive. Same, with checkmarks, "i" for info, etc. 

Right now in the Qute Qubes icon set, there are 4 basic variations on the icons. 
- The solid qube
- The solid qube with a star in its middle
- Two qubes with the top solid and the bottom transparent
- TWo qubes with the top transparent and the bottom solid

That set I feel has already hit the limit for meaningful semiotics of different related concepts, within a 16x16 footprint, for a totally unique experience that you'll never see spoken to outside of Qubes.

TL;DR it's outside the scope of how the human brain works, for any icon that small to meaningfully communicate these concepts that are incredibly specific to Qubes, work, to users. 

Also: how to solve for all of these problems _well_ and for the long term, is being tackled in #5677. This issue is only to tweak the first application of the Qute Qubes icons set, in 4.1, and to make one tweak in naming to have **all** templates grouped together—to reduce the likelihood of a major user error with a person inadvertently modifying a disposable template. 

Does that all make sense? Sorry I got a bit longwinded. I tend to do that. 

Related: We are going to be rethinking how things are named, to more intuitively/inclusively name all qubes in a comprehensive system that is easier for folks to follow. I will totally reach-out to you to ensure you're included in that effort, as I value your feedback a great deal. :)

**Comment by brendanhoar** [comment]
@ninavizz 

I completely understand.

It is important to assist the user in understanding the security and/or data-loss aspects of the now six (pseudo-)unique types of VMs:

Template VM (persists OS changes only)
Application VM (persists user changes only)
Service VM (e.g. sys-net ... really just a single task Application VM with some security aspects).
Disposable Template VM (persists OS changes)
Disposable VM (disp####, all changed contents thrown out when shut down)
Named Disposable VM (e.g. sys-net, all changed contents thrown out when shut down, unless invoked in a special way, some security aspects)

Whether it is words or icons to differentiate I will leave up to others.

As I said at the top, users, especially vulnerable users, need to have guidance on pitfalls of using the various types incorrectly. I've done so myself and I consider myself a technical user.

Also, if I am just returning to issues already resolved or already being worked on, apologies.

Brendan

**Comment by ninavizz** [comment]
@brendanhoar No worries—and certainly no apologies! TBH, I only learned about half of those VM types exist, myself, after a giant chicken/egg discussion that clarified a lot for me... like, last week. So, it's all good. :D

> As I said at the top, users, especially vulnerable users, need to have guidance on pitfalls of using the various types incorrectly. I've done so myself and I consider myself a technical user.

This is literally the only reason I'm advocating for as clumsy of a UI change, as I feel the `Template (disp):` prefix is. It twists my gut for its clumsyness, and I'm sure twists Andrew's gut for its persisting of an incorrect use of nomenclature. Separating disposable _templates_ from disposable _app vms_ felt like a reeeally important thing to do, tho—and until we move to a fully bespoke app menu, alphabetization is the only way to do it.

For the new App Menu, I've already learned enough in just the past week, to want to make some updates to the design to better distinguish these types of types of types from one another, lol. I'm optimistic tho, that separating "Templates" into their own bucket, tho, will help prevent some security snafus—which will be a good thing. :)

No need to move the comments, all of this is helpful and contextually relevant. If there are no further concerns with the solution I've edited the OG comment to propose, I'm hoping they can go into `4.1` before its first RC. Really wanting such prominent user-facing things as this issue and #6707 proposes, to not go in after folks have already adjusted to the rest of the UI newness in 4.1

**Comment by brendanhoar** [comment]
@ninavizz as per other thread I have corrected a statement above.

**Comment by andrewdavidwong** [comment]
> 1. Template VM (persists OS changes only)

Templates also persist any changes to their user directories.

> 3.5 the persisted storage of a Disposable Template is the same as the parent Template VM, but the VM settings are local, so let's call this half a type

Not quite. Disposable templates are app qubes and therefore have the persistence properties of app qubes, not templates.

> 4.5 Disposable VM (at runtime called disp####, all changed storage contents thrown out when shut down, but has its own persisted settings similar to an App VM.

A (non-named) disposable has no persisted settings at all. It completely ceases to exist when shut down. Rather, any persisted settings would come from the disposable template on which it's based.

> Sometimes the settings, which can be different than the Template VM, might be called a Disposable Template

No, a disposable template is actually an app qube. It's not just a bundle of settings.

> but notably there is no persisted storage other than the storage from the top level Template VM).

No, disposable templates have the persistence properties of app qubes (since they *are* app qubes), which means that their home directories persist (including `/rw/`).

> 5.5 Named Disposable VM [...] Has a way to invoke that allows storage changes to be persisted for setup, but user must be careful when doing so.)

That's simply the act of modifying the disposable template on which the named disposable is based.

-----

> > Lastly are these officially called "Named Disposable" or "Static Disposable"? I've read both and I did not find either on the Qubes Glossary page.
> 
> There's no official term yet. "Named" seems to be more common, but the fact of having a name is sort of incidental to what sets these apart. "Static" might have unintended connotations.

I've decided to add an entry for "named disposable" for now, since it seems to be the term used in the wild.

**Comment by brendanhoar** [comment]
Thanks Andrew for all the corrections.

I think I was closer on the original post w/o the edits but had a moment of doubt after the question from Demi, panicked and then hashed it up from there trying to get it "corrected".

B

**Comment by ninavizz** [comment]
What a mentally exhausting conversation, but so incredibly helpful! Thx again, Brendan and Andrew! 

To close this issue, then, two core changes are requested:
- [ ] Give all DVM Templates the disposable icon
- [ ] List disposable vm templates in the app menu with the prefix `Template (disp):` (per [above mockup](https://github.com/QubesOS/qubes-issues/issues/6709#issuecomment-863731827)) such that they get alphabetically grouped with Templates—and users do not mistake them for being actual app qubes. 

@marmarta Are you still ok taking this on to get it into the first RC for `4.1`?

**Comment by andrewdavidwong** [comment]
> DVM Templates
> disposable vm templates

Both of these terms refer to the same thing.

> and users do not mistake them for being actual app qubes.

Again, they *are* actual app qubes. It's important that users not mistake them for *disposables* or for *regular* app qubes.

**Comment by unman** [comment]
On Fri, Jul 02, 2021 at 03:25:51AM -0700, Andrew David Wong wrote:
> > DVM Templates
> > disposable vm templates
> 
> Both of these terms refer to the same thing.
> 
> > and users do not mistake them for being actual app qubes.
> 
> Again, they *are* actual app qubes. It's important that users not mistake them for *disposables* or for *regular* app qubes.
> 

This is undoubtedly an edge case, but there are people who work
in a DVM Template **and** spawn off disposableVM based off it - the
ability to test something quickly before committing to it is a very
useful feature - I don't mean wonky testing, I mean real world, give this
a try testing.
I don't know how the proposed icons will enhance that: I suspect they may
confuse matters in this case.

**Comment by DemiMarie** [comment]
> On Fri, Jul 02, 2021 at 03:25:51AM -0700, Andrew David Wong wrote: > DVM Templates > disposable vm templates Both of these terms refer to the same thing. > and users do not mistake them for being actual app qubes. Again, they *are* actual app qubes. It's important that users not mistake them for *disposables* or for *regular* app qubes.
> This is undoubtedly an edge case, but there are people who work in a DVM Template **and** spawn off disposableVM based off it - the ability to test something quickly before committing to it is a very useful feature - I don't mean wonky testing, I mean real world, give this a try testing. I don't know how the proposed icons will enhance that: I suspect they may confuse matters in this case.

I know I have done this.  Thanks to qrexec policy, it is possible for a qube to have more privileges than disposable qubes based on it do, which can be quite useful at times.

**Comment by brendanhoar** [comment]
Maybe this is a case of the term "Template" being overloaded in Qubes (while being generally correct)?

Currently: A disposable VM is based on a "disposable VM Template". That disposable VM Template is also an "App VM". That App VM is itself based on a "Template VM". 

Templates, all the way down. :)

What does templating mean in Qubes, in both contexts?

On the technical side it has to do with variations on a) the independence/retention of config files and config inheritance, b) then use of independent volumes vs. snapshots for the different volume types, c) which snapshots are discarded vs. being reintegrated into the original volume, d) volatile volume handling and e) under which conditions the default contents of the "user volume" is deployed "fresh" from the part of the "root volume" that keeps and maintains the default user volume tree.

Many users are uninterested in all that, they want to know what capabilities/risks they provide.

From a user perspective, a user has to be made aware that a VM Template VM does *not* bestow the contents of it's home directory to VMs based off of it. Usually this is through experience.

They should also be made aware that a disposable VM template *DOES* bestow the contents of the AppVM home directory to disposable VMs based off of it. 

This difference has pros and cons.

Pros:
User config can be re-used on disposable VMs by invoking the disposable VM Template to run in a non-disposable way via command line option. I have done so both on purpose and inadvertently (the latter due to a since-resolved defect...IIRC?).

Cons:
In particular, vulnerable users need to know this difference so that they are aware that network-connected disposable VMs may be more susceptible to give fingerprinting information to adversaries than a newly-created AppVM that you use once and then manually delete.

Is there meaningful user confusion? Would a change in terminology reduce this user confusion?

I haven't thought on this hard, but something like "a disposable VM has a Frozen AppVM, and this Frozen AppVM can only be invoked in a non-disposable way in order to make changes that will be retained by doing Xyzzy" might be clearer.

Frozen isn't great, however, as it's not exactly true since the grandparent (from disposable vm viewpoint) Template VM changes are reflected at all levels.

B

**Comment by ninavizz** [comment]
> > DVM Templates
> > disposable vm templates
> 
> Both of these terms refer to the same thing.
> 
> > and users do not mistake them for being actual app qubes.
> 
> Again, they _are_ actual app qubes. It's important that users not mistake them for _disposables_ or for _regular_ app qubes.

Yep, I know both monikers are the same thing. I created the checkboxes, because they're two different development tasks. One, is to replace the icon. The other, is to change the prefix. 

Also, I'm cool doing the icon as a Template icon, for now. How does a user invoke the disposable VM, from the app menu, or by opening a document in an app qube, that then prompts a new DVM to open from the DVM template?

**Comment by ninavizz** [comment]
@unman @brendanhoar 

Ok. The icons were created, before I knew that "Disposable Templates" were a distinct thing. Because the way the app menu and qubes msnager currently present these things, on the Qubes laptop that was handed to me pre-configured by experts who knew all these things that I did not, is really confusing. 

How I use Qubes, is similar to how enterprise users will use Qubes: their admin does the deep learning and configures the thing, but then we need to be able to intuitively use it once it's handed to us, without making mistakes that can expose us to vulnerabilities. 

A disposable template, is not an app qube. THAT, is the primary objective with changing the icon. I don't want to create Yet Another Icon, because right now my brain is exploding just a bit. Also, I want to do a proper naming workshop with the full team, to re-evaluate our ecosystem of qubes and how names and qualifiers such as types and roles, can better facilitate comprehension and "learning by doing."  I am currently working on how to structure such a workshop, and will post here, again, once that is ready.

**Comment by ninavizz** [comment]
Ok... this issue is emerging to be a classic example of why I struggle with GitHub as a place to discuss UX. What _the user experiences_ and how a UI can influence user choices, is really hard to discuss asynchronously and without everyone agreeing on what (tangibly, behavioraly) we're speaking to. 

I had a great conversation with @marmarta just now, on Wire. This issue was initially created, specifying the disposable icon and with my "users don't care what the type of VM is" comment, because of what happens when a  user selects the item in the app menu list. What users may be able to do on the command line, should not have absolute bearing on how we show things in the app menu.

From the App Menu, it is currently not possible to open the Template to modify the Template. So, the major security risk @andrewdavidwong flagged, can only happen from a user acting on the command line. When a user selects the item in the app menu, it spawns a new disposable VM. 

This confusion is precisely why I want to separate qube "Types" from "Roles" in how we speak to them internally, on the website, and in documentation.

A second point of confusion, was a well-intentioned contributor pointing me to an older QA generated screenshot of the app menu with the new icons. From that screenshot, I created the mockup above. Yet when I just backchanneled Marta to see how this issue may fit into pre-4.1 activities, she said that it's requesting for a thing to exist that already exists. Hence, the screenshot below. 

![Wire 2021-07-02 at 19-39-21](https://user-images.githubusercontent.com/8262612/124326341-0ba75080-db3b-11eb-878c-944e0df1bf18.jpg)


In the `4.2` appmenu (below), this is how disposable templates will surface in the App Menu's "App" section. The DVM Template will always be the top-most item and italicized, whereas the running epemeral child VM will show in bold text, beneath it and to the right of the hook-line speaking to descendence. 

https://scene.zeplin.io/project/5f5661dc7cdfdb74dc7c3180/screen/609b0cbff45e75ad58924023

The DVM Template will also be shown in the "Templates" section, but not italicized. The key difference herein will be that when a user opens one from the Templates menu, they will be modifying the template. We should probably also spawn a warning notification of some sort, or a banner within the window, to ensure they understand that. Nope, "Disposables" do not have their own section, because the primary mental model is all that the 3 buckets are reflecting, is the activity a user desires to enter into when opening a qube. Do they want to "do a task in an app," or do they want to modify a thing that will persist across multiple qubes in their system? 

I'm also now feeling inclined to propose renaming Template and App qube _types_, to parent/child qube types... with "App" qubes being a role, and not a type. And, the word "Template" just going away, as there exists no antonym that is explicitly clear across languages < 8th grade comprehension level, that a thing is a spawned item of another thing. I appreciate that per that logic, Standalone VMs should perhaps then be called "Jesus VMs," as they have no parent but _the creator_—but I promise I will not go there. 

| ![giphy](https://user-images.githubusercontent.com/8262612/122471920-b84ad500-cf74-11eb-8b0d-d7d71c1d62f1.gif) | ![giphy](https://user-images.githubusercontent.com/8262612/122471920-b84ad500-cf74-11eb-8b0d-d7d71c1d62f1.gif) |
![giphy](https://user-images.githubusercontent.com/8262612/122471920-b84ad500-cf74-11eb-8b0d-d7d71c1d62f1.gif) |

**Comment by andrewdavidwong** [comment]
> From the App Menu, it is currently not possible to open the Template to modify the Template. So, the major security risk @andrewdavidwong flagged, can only happen from a user acting on the command line. When a user selects the item in the app menu, it spawns a new disposable VM.

That's fine as far as the app menu is concerned, but presumably much of this UX will also be reused in the Qube Manager and the Qubes Domains widget.
