### ISSUE TITLE
Sending encrypted emails doesn't work with thunderbird + split-gpg

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#6712]
[Build 2021061619-4.0] openQA test fails in TC_10_Thunderbird_debian-10

## Observation

openQA test in scenario qubesos-4.0-update-x86_64-system_tests_splitgpg@64bit fails in
[TC_10_Thunderbird_debian-10](https://openqa.qubes-os.org/tests/18402/modules/TC_10_Thunderbird_debian-10/steps/1)

![debian-10-thunderbird-fail](https://user-images.githubusercontent.com/726704/122436127-db877b80-cf98-11eb-8034-d07095051b68.jpg)

## Reproducible

Fails since (at least) Build [2021061619-4.0](https://openqa.qubes-os.org/tests/18402) (current job)

The same test passes on Fedora.

## Expected result

Last good: [2021012013-4.0](https://openqa.qubes-os.org/tests/15975) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=update&machine=64bit&test=system_tests_splitgpg&version=4.0)

**Comment by deeplow** [comment]
I've been digging into this. I have manually reproduced this test on versions 78.10.1, 78.10.2 and 78.11.0.

It seems it stopped working on version 78.10.2. The weird part is that I haven't seen this issue myself on my daily system, nor have I seen user complaints. This leads me to believe that may be issue with the particular handling of the key generated for that test. Will continue working on this.

**Comment by deeplow** [comment]
This also affects fedora-33 and fedora-33-xfce as seen on job [19596](https://openqa.qubes-os.org/tests/19596/). @andrewdavidwong do you think you can update the tags?

**Comment by deeplow** [comment]
Ran the test `TC_10_Thunderbird_debian-10/test_000_send_receive_default` with several conditions to understand what changed from a passing test onto a failing test. This test is to be representative of all ones in `TC_10_Thunderbird_debian` since they all fail with the same error message and pass with Thunderbird 78.10.1.

## Conclusions / Hypothesis

- `H0` - Issue is with splitgpg itself when exporting the pub key (when the following is called `/usr/bin/qubes-gpg-client-wrapper --armor --export --output /home/user/pub.asc`)
  - **counter-arguments:** qubes-gpg-client-wrapper is not thunderbird-version aware.
  - **if verified:** create splitgpg bug

- `H1` [Thunderbird 78.10.2](https://www.thunderbird.net/en-US/thunderbird/78.10.2/releasenotes/) introduced a new parameter for allowing the key to be used in encryption which we need to further change.
  - **if verified:** fix test and documentation to enable said parameter

- `H2` [Thunderbird 78.10.2](https://www.thunderbird.net/en-US/thunderbird/78.10.2/releasenotes/) broke something in the reading of public keys, which is still broken in Thunderbird 78.11.0
  - **if verified:** report bug upsteam with Thunderbird

## Test results

### PASS | debian-10 | thunderbird 78.10.1

Contents of `/tmp/enigdbug.txt` (relevant section -- when this starts diverging from the FAIL case)
```
[...]
2021-07-13 14:16:54.168 [DEBUG] keyRing.jsm: getKeyById: 3D85008B9C2CAE64
2021-07-13 14:16:54.169 [DEBUG] enigmailMsgComposeOverlay.js: Enigmail.msg.focusChange: Enigmail.msg.determineSendFlags
2021-07-13 14:16:54.171 [DEBUG] keyRing.jsm: getValidKeyForRecipient(): emailAddr="user@localhost"
2021-07-13 14:16:54.171 [DEBUG] sqliteDb.jsm: PgpSqliteDb2 openDatabase()
2021-07-13 14:16:54.171 [DEBUG] sqliteDb.jsm: openDatabaseConn()
[...]
```
Full log: [deb-10_thunderbird-78.10.1_enigdb.txt](https://github.com/QubesOS/qubes-issues/files/6809545/deb-10_thunderbird-78.10.1_enigdb.txt)


Command calls for `/usr/bin/qubes-gpg-client-wrapper`:
```
/usr/bin/qubes-gpg-client-wrapper --version
/usr/bin/qubes-gpg-client-wrapper -K --with-colons
/usr/bin/qubes-gpg-client-wrapper --armor --export --output /home/user/pub.asc
/usr/bin/qubes-gpg-client-wrapper --version
/usr/bin/qubes-gpg-client-wrapper --version
/usr/bin/qubes-gpg-client-wrapper --version
/usr/bin/qubes-gpg-client-wrapper --batch --no-sk-comments --status-fd 91 --no-tty --charset utf8 --enable-progress-filter --exit-on-status-write-error --display :0 --ttyname /dev/pts/0 --ttytype xterm-256color --logger-fd 95 --with-colons --list-secret-keys -- 3D85008B9C2CAE64
/usr/bin/qubes-gpg-client-wrapper --enable-special-filenames --batch --no-sk-comments --status-fd 91 --no-tty --charset utf8 --enable-progress-filter --exit-on-status-write-error --display :0 --ttyname /dev/pts/0 --ttytype xterm-256color --logger-fd 93 --sign --detach --armor --textmode -u 3D85008B9C2CAE64 -- -&94
```



### FAIL | debian-10 | thunderbird 78.10.2

Contents of `/tmp/enigdbug.txt` (relevant section -- when this starts diverging from the SUCCESS case)

```
[...]
2021-07-13 14:24:41.246 [DEBUG] keyRing.jsm: getKeyById: C0D7E0C01AE7ADDC
2021-07-13 14:24:41.246 [DEBUG] errorHandling.jsm: determineInvRcptReason: keyId: C0D7E0C01AE7ADDC
2021-07-13 14:24:41.246 [DEBUG] keyRing.jsm: getKeyById: C0D7E0C01AE7ADDC
2021-07-13 14:24:41.307 [DEBUG] enigmailCommon.jsm: dispatchEvent f=resizeDlg
```

Full log: [deb-10_thunderbird-78.10.2_enigdb.txt](https://github.com/QubesOS/qubes-issues/files/6809552/deb-10_thunderbird-78.10.2_enigdb.txt)


Command calls for `/usr/bin/qubes-gpg-client-wrapper`:
```
/usr/bin/qubes-gpg-client-wrapper --version
/usr/bin/qubes-gpg-client-wrapper -K --with-colons
/usr/bin/qubes-gpg-client-wrapper --armor --export --output /home/user/pub.asc
/usr/bin/qubes-gpg-client-wrapper --version
/usr/bin/qubes-gpg-client-wrapper --version
```

### Testing Condition (for reproduction)
- ran modified splitgpg.tests/TC_10_Thunderbird_debian-10/test_000_send_receive_default
- modification inserted a time.sleep before it started sending a message
- After the sleep I would:
   - [enable enigmail logging](https://wiki.mozilla.org/Thunderbird:OpenPGP#OpenPGP_log) (and restart thunderbird)
   - attempted to send message to `user@localhost` and random subject and content (to reproduce the test)

Each test was reproduced twice and the respective logs inspected to make sure the only difference were non-deterministic things like the keyID of the generated keys.

**Comment by andrewdavidwong** [comment]
> This also affects fedora-33 and fedora-33-xfce as seen on job [19596](https://openqa.qubes-os.org/tests/19596/). @andrewdavidwong do you think you can update the tags?

> is distro-independent (affects debian-10 as well as fedora-33 and fedora-33-xfce)

Done. Distro-independence means it should not have any distro-specific labels.

**Comment by andrewdavidwong** [comment]
> I've been digging into this. I have manually reproduced this test on versions 78.10.1, 78.10.2 and 78.11.0.
> 
> It seems it stopped working on version 78.10.2. The weird part is that I haven't seen this issue myself on my daily system, nor have I seen user complaints.

Same. I can send encrypted emails right now with Debian 10 + Thunderbird 78.11.0 + Split GPG.

**Comment by deeplow** [comment]
Found the issue. All thunderbird `TC_10_Thunderbird_*` tests are now passing on my machine. See patch in 
https://github.com/QubesOS/qubes-app-linux-split-gpg/pull/43

The short version is that the thunderbird 78.10.2 included [a bugfix](https://bugzilla.mozilla.org/show_bug.cgi?id=1654893) that added support for offline master key, but incidentally broke the setup where there are no subkeys. (see [here the diff](https://hg.mozilla.org/comm-central/diff/0ad4f197152f19fabade9640fb9ae0fb94dfd3f3/mail/extensions/openpgp/content/modules/encryption.jsm)).

In practice this means for the test we have to generate a key with a sub-key, instead of a single key with all capabilities (which is a non-default configuration either way).
