### ISSUE TITLE
Installer: Debian option sometimes references incorrect desktop files ("Application missing in template!")

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6805]
### Qubes OS version

4.1 Beta-1

### Are you providing feedback about a specific package or packages in testing?

Qubes installer

### Affected component(s) or functionality

Qubes Installer

-----
### Brief summary

If Debian-10 is selected as default, on *some* installs, the menu list is shortened.
Editing the applications in qube settings shows:
```
"Application missing in template! (firefox.desktop)"
"Application missing in template! (xterm.desktop)"
```

### How reproducible

Around 50%

### Steps to reproduce

1. Install Qubes Beta-1
2. Select Debian-10 as only template
3. 

### Expected behavior

Application lists will be correctly created.

### Actual behavior

Application lists are malformed with reference to incorrect desktop files.

### Additional context

I have seen this with reinstalls on the same machine.

-----

**Comment by marmarek** [comment]
Does it affect all default qubes, or only the template itself?

This looks like incomplete debian-10 template install. I guess the list of available apps is empty too, right? If so, can you check `journalctl` from the template installation time (during initial setup), and also qrexec log for debian-10 ?

**Comment by unman** [comment]
On Thu, Jul 29, 2021 at 03:11:47AM -0700, Marek Marczykowski-Górecki wrote:
> Does it affect all default qubes, or only the template itself?
> 
> This looks like incomplete debian-10 template install. I guess the list of available apps is empty too, right? If so, can you check `journalctl` from the template installation time (during initial setup), and also qrexec log for debian-10 ?
> 

No, the template is installed fine, and for most qubes the available
apps look fine.
Further digging suggests that it is limited to the configured sys-
qubes, based on debian-10-dvm.

**Comment by adrelanos** [comment]
Alright, thank you.

Fixed in git. Should be fixed in the next template build.

**Comment by adrelanos** [comment]
To make this issue easier to discover, could you please append to the title

> Application missing in template!

@adw?

**Comment by adrelanos** [comment]
In Qubes R4.0 there where files such as:

* `/var/lib/qubes/vm-templates/fedora-XX/whitelisted-appmenus.list`
* `/var/lib/qubes/vm-templates/fedora-XX/vm-whitelisted-appmenus.list`
* `/var/lib/qubes/vm-templates/fedora-XX/netvm-whitelisted-appmenus.list`

On Qubes R4.1 I can no longer locate these files. Where are these located?

I am asking, because I suspect that there are other bugs are work here.

* If "outside of" template is upgraded using dom0 `qvm-template` the whitelisted-appmenus files aren't updated?
* If "inside of" template is updated using `dnf` or `apt` then the I guess dom0 whitelisted-appmenus won't be updated?

These are two cases which could lead to this issue.

**Comment by marmarek** [comment]
For the latter case, maybe we need a button in a VM settings like "reset selected applications to default"?

**Comment by adrelanos** [comment]
> For the latter case, maybe we need a button in a VM settings like "reset selected applications to default"?

Seems a nice feature for beginners who played to much with it and now wants to go back to the defaults. Separate ticket for that? Because seems a different idea.

----

The point more in this ticket, I think...

As per [screenshot](https://user-images.githubusercontent.com/11895339/152749348-bcba03d4-2d36-4c44-9841-7eda959d312f.png) by user and issue it is my interpretation that this message alarms users, which I think is very unnecessary for such a minor issue.

Maybe `Application missing in template!` could be toned down?

* The easy win is removing `!` but that wouldn't help much.
* "Application missing" sounds to non-technical users like "that could be something really bad". (Technical users might think "Not having gnome-terminal could be irrelevant but might point to issues such as a missing meta package or other issues.)
* Not sure how to reword it? Suggestions?

Seems a hard feature for me anyhow. Well, the template maintainer decided on a list of default start menu entries. Then

* either the user removed some default installed application on purpose. In that case that message isn't helpful.
* either the user removed some default installed application by accident.
* just an upgrade issue.

> > On Qubes R4.1 I can no longer locate these files. Where are these located?
> 
> Those entries were migrated to `qvm-features`.

Nice!

For reference:

* `qvm-features debian-11`
* `qvm-features whonix-ws-16`
* `qvm-features vault`
* etc.

> > If "outside of" template is upgraded using dom0 `qvm-template` the whitelisted-appmenus files aren't updated?
> 
> Theoretically they should be.
> 
> > If "inside of" template is updated using `dnf` or `apt` then the I guess dom0 whitelisted-appmenus won't be updated?
> 
> Currently not, but there is a plan to allow template to advertise default menu entries using mechanism similar to [qvm-service support discovery](https://dev.qubes-os.org/projects/core-admin/en/latest/qubes-features.html#qvm-features-request-qubes-postinstall-service). In any case, it will only affect new VMs created out of such template, existing VMs are not modified (including menu entries selected for the template itself).

But better if there was only one mechanism, not 2? OR perhaps the current "outside of template" mechanism getst ported to qvm-service support discovery so it would still just be 1 mechanism?

> existing VMs are not modified (including menu entries selected for the template itself).

Then we'll always have the "Application missing in template!" scary warning issue whenever default installed applications change and they do over the years and releases.

**Comment by marmarek** [comment]
> > existing VMs are not modified (including menu entries selected for the template itself).
> 
> Then we'll always have the "Application missing in template!" scary warning issue whenever default installed applications change and they do over the years and releases.

How would you propose doing this, without risking rolling back intended user changes (like, removing some app from the menu that was there by default, or adding another one)?

**Comment by adrelanos** [comment]
If the application is not (or no longer) in the template, then it could be handled as any other Linux distribution handles it. When a package is removed, also all of the application's start menu entries vanish. That's a commonplace default and expected.

Since there was no feature request for the `Application missing in template!` feature (?), I think that feature should be disabled by default. I expect it to cause more confusion than usability. But perhaps I am not fully understanding the upside of this feature.

But since the feature already exists it seems useful to keep it. Seems a very useful feature for Template maintainers to check if their start default application selection / config declaration is correct.

**Comment by marmarek** [comment]
Keeping an application on the list even if the template doesn't have it anymore is important when user switches template. Especially for the case of switching back (for example you just wanted to test if something works better/different on another template). For example Fedora ships "Firefox", but Debian ships "Firefox ESR". If those would be removed automatically, user would need to re-configure menu to their liking every time they switch the template. With the current approach, they can have both "Firefox" and "Firefox ESR" on the list, and the menu will contain only the one that actually matters for the current template.

Another (possibly more common) case is to avoid confusion about disappearing applications - previously, if you switch a template, not available applications would silently disappear - you wouldn't know why.

But indeed, the text could be toned down, maybe "Application not available: ..." ?

**Comment by andrewdavidwong** [comment]
This issue is in desperate need of a UX expert, @ninavizz.
