### ISSUE TITLE
Installer - selecting English variant at install is not propagated to templates.

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6814]
### Qubes OS version

4.1 Beta-1

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

N/A

### Are you providing feedback about a specific package or packages in testing?

Installer

### Affected component(s) or functionality

Installer

-----
### Brief summary

Selecting an English variant at Install stage, adjusts keyboard selection as expected.
This change is propagated to dom0, but not to templates.

### How reproducible

100%

### Steps to reproduce

1. Install from 4.1 Beta-1
2. Select English variant
3. After installation, confirm that dom0 uses the expected keyboard mapping
4. check keyboard mappings in any qube

### Expected behavior

qubes will use the same keyboard mapping as selected at install

### Actual behavior

Templates use US mapping.

### Solutions you've tried

manually changing the keyboard mapping.

### Additional context

This is confirmed with Debian selection at install - I have not tested a Fedora install.
This seems to me a major bug - new users will be confused by the lack of consistency between dom0 and templates/qubes.
Although there is a simple method to change the language in Qubes settings, new users will not be immediately aware of this.

-----
### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

 #5271 - refers to selection of non English variants at install.

**Comment by stman** [comment]
Qubes-OS 4.1 Beta 1
Issue details

When installing Qubes-OS 4.1 Beta and choosing a specific keyboard layout during the installation process, this setting is not fully configured later on in Qubes-OS when running Qubes-OS :

It's okay for dom0, but not for all other VM's, where the default english layout will apply.

To correct this, one needs to manualy uncheck the [Dom0] Keyboard utility’s “Use system defaults” box from the Layout tab to force the choosen keyboard layout during installation process to be applied to all VM’s.

If not doing so, the choosen configuration for the keyboard layout choosen during install won’t be applied to all VM’s.

This small configuration bug was not present on the 4.0.4 release of Qubes-OS
Steps to reproduce

See above. It's straight easy.
Expected behavior

The “Use system defaults” should be unchecked automatically after installation process, like it was the case in Qubes-OS 4.0.4
Actual behavior

Dom0 uses the choosen keyboard layout during the installation process (Can be easily checked by launching dom0's terminal), but within all other VM's, it's the english layout that is by default activated.
