### ISSUE TITLE
xfce4 error message: "None of the screen lock tools ran successfully, the screen will not be locked."

### ISSUE THREAD

**Issue by ilka-schulz** [QubesOS/qubes-issues#6849]
### Qubes OS release

- introduced in R4.1.0 beta1

### Brief summary

After locking the screen (`xflock4` in dom0), other lock triggers cause this error message to show up after the next unlock:
![screen-lock-tools](https://user-images.githubusercontent.com/83639952/130430120-f37cd4c0-7f15-4cf7-b7df-135da369a272.png)

### Steps to reproduce

1. have Qubes OS on a **laptop**
2. in `dom0`'s `Xfce Power Manger` under `General` tab, choose value `Lock screen` for key `When laptop lid is closed:`.
3. lock your screen (e.g. `Ctrl`+`Alt`+`L`)
4. close your laptop lid
5. wait for several hours (this is necessary)
6. open your laptop lid and unlock your screen

### Expected behavior

no error message

### Actual behavior

The above error message occurs.

**Comment by marmarek** [comment]
Is this a fresh install, or updated from 4.1 alpha, or even 4.0?

**Comment by ilka-schulz** [comment]
> Is this a fresh install, or updated from 4.1 alpha, or even 4.0?

This is a fresh install of the 4.1.0 beta1:

```text
c0851c7b9567e795ac12f5d9727f4d08 *Qubes-R4.1.0-beta1-x86_64.iso
03540076564bf798ac5b1d9f9d5b34054b1d0376 *Qubes-R4.1.0-beta1-x86_64.iso
e06f9d3b2ddf15263c5600b2dc90e0e59d8bb26512dd2c26a0cb5c47193ffa79 *Qubes-R4.1.0-beta1-x86_64.iso
1848ad39d4fc782d6a7f730ca07e1d08144cf4c71a1a1a1fda2f93f8bcc351e9108e08be3238774ae73f30f3c2eb67868937dbe2475036ae1156be4430f1e349 *Qubes-R4.1.0-beta1-x86_64.iso
```

**Comment by brendanhoar** [comment]
Can confirm this also happened on a fresh install of 4.1rc1 for me as well.

**Comment by zellchristensen** [comment]
I've had this happen twice as well on 4.1 when closing the lid.  I only noticed it when the lid was re-opened.

**Comment by andrewdavidwong** [comment]
Just happened to me on a new Qubes 4.1.1 installation.

**Comment by nightcrowlers** [comment]
Hello, 

I also have had this issue repeatedly (the screen just won't lock if I simply close the lid) but I found a temporary workaround for me. I hope this may help some users in the meantime. I am using Qubes 4.1.1.

I set xfce4-power-manager's settings so that logind handles the lid switch action instead of xfce4. To do that you can run the `xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/logind-handle-lid-switch -t bool -s true` command directly on the dom0 terminal or add it manually in the Settings Editor app (in the `xfce4-power-manager` tab, add the `logind-handle-lid-switch` boolean and set it to True).

Then, you need to tell logind to lock the screen when the lid is closed. This is done by modifying the /etc/systemd/logind.conf file and I changed the following (make sure to remove the '#' to each options you're changing since they're comments, otherwise the defaults will be used):

```
HandleLidSwitch=lock
HandleLidSwitchExternalPower=lock
HandleLidSwitchDocked=lock
...
LidSwitchIgnoreInhibited=yes
```

With these settings, my screen locks instantly when I close my lid like intended and the error messages are gone. I have been using this method for about a month and I couldn't find any problems with it, though, this could maybe introduce security issues (but better than having the screen not lock at all I guess...)

Though I would prefer that someday xfce4 properly handles this itself like it's supposed to. I didn't have this issue on my x230, but it appeared with my Framework laptop (11th gen). I wonder why. But anyway, I hope this can help some people.

**Comment by permezel** [comment]
Now that I am running awesome-wm, I get this every time the system tries to suspend.  It fails to suspend, or lock, due to the modal dialogue pop-up.
The 'clean' way to suspend is to manually run `systemctl suspend`.  This a) locks the screen and b) suspends and c) does not need to restart awesome-wm when woken.  The failing auto-suspend mucks up the window::tag assignments, and one needs to restart awesome-wm (with appropriate rules) to fix things.
