### ISSUE TITLE
Duplication of copy&move to vm context menu entries with hardened memory allocator

### ISSUE THREAD

**Issue by Nurmagoz** [QubesOS/qubes-issues#6873]
### Qubes OS release
Qubes 4.0

### Steps to reproduce

- Open whonix terminal (gw or ws)
- `sudo apt install hardened-malloc && sudo apt install hardened-malloc-kicksecure-enable`
- Restart
- Open Thunar
- Right click anywhere and you will see the same as the image below

### Expected behavior

No duplication

### Actual behavior

Duplication of copy to VM , move to VM multiple times.

### Image

![dracutissue](https://user-images.githubusercontent.com/11895339/132034557-157c5a90-ab41-4f40-83d3-14db55014e65.png)

**Comment by DemiMarie** [comment]
Looks like a bug in Thunar.  Try running it under Valgrind.

**Comment by thestinger** [comment]
ASan works much better than Valgrind although you have to rebuild it and potentially libraries involved in causing it.

**Comment by TNTBOMBOM** [comment]
> Looks like a bug in Thunar. Try running it under Valgrind.

[thunarfullval.txt](https://github.com/QubesOS/qubes-issues/files/7109544/thunarfullval.txt)

**Comment by DemiMarie** [comment]
> ASan works much better than Valgrind although you have to rebuild it and potentially libraries involved in causing it.

I recommended Valgrind because it is much simpler to use, but indeed it turned out to not be helpful.

**Comment by thestinger** [comment]
Those jump based on unconditional value reports tend to just be spammed based on modern compiler code generation.

**Comment by DemiMarie** [comment]
> Those jump based on unconditional value reports tend to just be spammed based on modern compiler code generation.

Why is that?

**Comment by thestinger** [comment]
Compilers now often choose to generate code that reads potentially uninitialized data when they know that the result of it won't impact anything.

For example, consider code like `if (a && b) [ ... }`. The compiler may decide to read `b` before `a` and run this as `if (b && a) { ... }` even though `b` can be uninitialized when `a` is `false` so it won't ever matter that it can be some arbitrary garbage since it's only possible when `a` is `false` and it won't be `true` overall regardless of what garbage is in it. It's the low-level generated code so it doesn't have to care about what's well-defined / correct in the source language.

It's incredibly common to get those warnings from Valgrind nowadays and it's meaningless. Same for certain other kinds of warnings. ASan / MSan is instrumentation added by the compiler and can catch far more issues along with being way more accurate since it knows the source-level semantics of the code and inserts the checks based on that so stuff like the code generation choice above is irrelevant to it.

**Comment by adrelanos** [comment]
Security relevant bug?

Hardened malloc can make memory corruption bugs apparent. Hardened malloc shouldn't have any influence on Qubes thunar integration.

Hardened malloc is planned to be installed by default in Whonix and Kicksecure. Therefore it would be great if this could be fixed.

> Looks like a bug in Thunar.

There are no such bugs when using Hardened Malloc with plain Debian outside of Qubes.

As shown in the screenshot https://user-images.githubusercontent.com/11895339/132034557-157c5a90-ab41-4f40-83d3-14db55014e65.png the `Copy to VM` and `Move to VM` context menu integration which is duplicated is a Qubes feature provided by Qubes thunar integration.

**Comment by DemiMarie** [comment]
We will need to rebuild with address sanitizer and undefined behavior sanitizer turned on.  @marmarek can/should this be integrated into Qubes Builder?

**Comment by TNTBOMBOM** [comment]
Installing hardened-malloc-light doesnt show the error above: 

https://www.kicksecure.com/wiki/Hardened_Malloc_Light

(The test above done with [hardened-malloc](https://www.kicksecure.com/wiki/Hardened_Malloc))

**Comment by DemiMarie** [comment]
> We will need to rebuild with address sanitizer and undefined behavior sanitizer turned on. @marmarek can/should this be integrated into Qubes Builder?

To elaborate: this will require being able to rebuild relevant parts of the distribution from source.  It can’t be done when using existing packaged binaries.

**Comment by TNTBOMBOM** [comment]
Adding side note to the same topic: 

If the user is going to encounter the same bug as mentioned earlier and intends to resolve it by, let's say, reinstalling the whonix-ws-template, but still experiences the same behavior, it's likely because the aforementioned issue persists within the .config directory (located in userspace, not in the root directory). Consequently, the problem will not be resolved on its own. To address this, it is recommended to delete the .config directory (ensuring that nothing important is logged there, such as HexChat conversations, for example).

`rm -r .config `
