### ISSUE TITLE
Kali template is too large. Change template to Kali Core.

### ISSUE THREAD

**Issue by h110w** [QubesOS/qubes-issues#6889]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary
When Downloading Kali Template, Template is too large for Dom0

### Steps to reproduce

qubes-template-kali

### Expected behavior

installed 

### Actual behavior
error an extra 5585 mb of space required

[https://forum.qubes-os.org/t/r4-1-qubes-template-kali-installation-fails-with-disk-quota-exceeded-error/1359?u=h110w](url)

**Comment by andrewdavidwong** [comment]
I'm rather skeptical of this issue.

- What does it mean for a template to be "too large for dom0"? That just sounds like a bug or lack of proper handling for large-file-size templates.
- Regarding `error an extra 5585 mb of space required`, it seems like the logical thing would be to provide it some extra disk space through a temp file, similar to what we do as part of the [Fedora in-place upgrade procedure](https://www.qubes-os.org/doc/template/fedora/upgrade/).
- Why assume that the correct response is to switch to a different version ("Kali Core")? That seems more like avoiding the underlying problem than actually fixing it.
- What is "Kali Core" anyway? I couldn't find anything online indicating that it's an official version of Kali. Would this be our own custom version that we'd have to maintain?

I'm interested in hearing what @fepitre and @marmarek think about this.

**Comment by fepitre** [comment]
@andrewdavidwong This is requested to post this issue from the Forum. The problem with default Kali is that it is *huge* and we currently have issue with new dom0 format being a 20GB only on R4.1.

The problem is when you install a package like template, it first decompress the content into this rather too small 20GB partition. In case of template like Gentoo or Kali, it hits this problem of not enough size. I've personally encountered it multiple times and I had to remove package like some kernels who take a lot of place into dom0 partition. That's said, @marmarek I think we need to decide how we can process this dom0 space issue once and for all.

For the original issue, I'm pretty fine to deliver also the `core` flavor of Kali instead of the standard which embed a huge number of tools that a user can very easily add on-demand from the  `core` one.

**Comment by andrewdavidwong** [comment]
(Improved grammar and orthography of issue title.)

**Comment by fepitre** [comment]
I forgot to mention that`core` and many other Kali flavors are defined with respect to their metapackage: https://www.kali.org/docs/general-use/metapackages/. This is what we use to build Kali.
