### ISSUE TITLE
qubesdb under new Void Linux (to-be) templatevm

### ISSUE THREAD

**Issue by fosslinux** [QubesOS/qubes-issues#6908]
### Qubes OS release

4.1beta1

### Brief summary

I'm attempting to put together a TemplateVM for Void Linux. At the moment, I'm at the stage of packaging each piece that is required and putting it all together in a HVM before using `qubes-builder`. However, I've hit a bit of a roadblock with qubesdb.

### Steps to reproduce

Running `qubesdb-daemon 0` in the HVM (stolen from init scripts in the `qubes-core-qubesdb` repo) produces no output apart from "startup failed". Glancing over the code I can not see anything that would cause this. Startup does really fail (no daemon is created).

### Expected behavior

It launches successfully.

### I have thought of

1. No-systemd, Void uses runit. Not 100% sure how this would change anything but there are some things masked behind checks in the code.

Any pointers would be appreciated.

**Comment by marmarek** [comment]
Make sure you compile it with `SYSTEMD=0` (just append it to the `make` call, or set in the environment).

**Comment by andrewdavidwong** [comment]
It looks like this issue is mainly asking questions and seeking support as a community developer.

Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-devel` mailing list](https://www.qubes-os.org/support/) instead.

In particular, please note that:

- [The issue tracker is not the right place to ask questions.](https://www.qubes-os.org/doc/issue-tracking/#do-not-submit-questions)

- [The issue tracker is not the right place to ask for help or support.](https://www.qubes-os.org/doc/issue-tracking/#i-need-help-have-a-question-or-want-to-discuss-something) 

If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by fosslinux** [comment]
Thank you for the pointer, I will post there. I was not 100% sure where would be best.
