### ISSUE TITLE
GUI protocol: daemon should confirm window destruction

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6914]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1 but should apply to older releases too

### Brief summary
The GUI protocol does not include any confirmation that a resource (such as a window ID) has been released.  This leads to a race condition: if a window ID is destroyed and then immediately reused, events in flight for the old window may be interpreted as being for the new window.

There are two ways to fix this bug.

1. Add a new message (`msg_confirm_destruct`?) to indicate that a window has definitely been destroyed.
2. Add a more general way for the GUI agent to confirm that a protocol round-trip has happened.

In both cases, the GUI agent must ignore events for windows that it has destroyed, until it gets confirmation that the window has in fact been destroyed and no more events will be sent to it.

### Steps to reproduce

None known.  This bug was found while designing a Wayland version of the GUI agent.

### Expected behavior

No race condition

### Actual behavior

Race condition mentioned above.

**Comment by marmarek** [comment]
There is MSG_DESTROY. After an agent sends it, further messages for this window ID are invalid (unless subsequent MSG_CREATE is sent). By design, gui-daemon processes events sequentially, so there is no way for it to hit this problem: it won't see events related to the new window (with reused id) until it processes MSG_DESTROY fully.

Are you sure it isn't another issue, like not sending MSG_DESTROY?
