### ISSUE TITLE
sys-usb not starting.

### ISSUE THREAD

**Issue by NicholasTrust** [QubesOS/qubes-issues#6937]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.0.4

### Brief summary
Hello guysI’m having an issue with sys -USB. When I started up my laptop Sys- USB did not start automatically as I have that option checked. Then took a look at the settings and for some reason I saw that provide Netwerk was checked in the advanced settings of sys- USB. I then tried to reboot my PC and try it all over again and the same issue happened. I tried to check the logs and it’s not showing any logs for that vm. I then attempted to clone it and create a new one based on the same template but this also didn’t work as it gave me the same error. After that I try to even change the template of that VM and also this didn’t work. I’m not sure what to do at this point. Can any one help me?

### Steps to reproduce
The steps I took to reproduce the issue was to simply clone it and try and start it again even after a fresh reboot.

### Expected behavior
The expected behavior was that The VM would start and work fine

### Actual behavior

The actual behavior was that it gave me the same error as the original one.  It says that it got a empty response from qubesd. When I checked journal CTL there was no response.

**Comment by hackerfactor** [comment]
A bunch of us found a similar problem with 4.1.
Here's my workaround:
https://github.com/QubesOS/qubes-issues/issues/6824#issuecomment-908487800

**Comment by unman** [comment]
#6824 is a report of sys-usb failing in 4.1beta.
This is different, and strikes me as more of a support issue, since *most* users on 4.0 have a working sys-usb.
@NicholasTrust I think that you have already raised the issue in the forum. Can I suggest we close this issue, and deal with it there. If a genuine issue is identified this can  be reopened.

On a general note, simply cloning a broken qube will not magically make the clone work.
