### ISSUE TITLE
Upgrading debian to testing version (bookworm) will break qubes-pulseaudio 

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#6986]
### Qubes OS release

Qubes 4.0

### Brief summary

Upgraded my VM to bookworm but discovered that qubes-pulseaudio depends on pulseaudio 14, While bookworm shipped with pulseaudio 15

### Steps to reproduce

- Change debian repos from bullseye to testing
- Change Qubes from bullseye to bullseye-testing (bookworm doesnt exist)
- update && upgrade

### Expected behavior

Qubes tools should work on stable debian so as testing version

### Actual behavior

```
user@host:~$ sudo apt install pulseaudio-qubes
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pulseaudio-qubes : Depends: pulseaudio (< 14.2.1) but 15.0+dfsg1-2 is to be installed
E: Unable to correct problems, you have held broken packages.
user@host:~$ cat /etc/debian_version 
bookworm/sid
```
### Notes

I wonder how qubes tools going to work with distros like kali or so which they are rolling and pulseaudio version will be for surely not the same as in the stable debian version (sometimes higher than the testing version)

**Comment by unman** [comment]
On Mon, Oct 18, 2021 at 09:16:41AM -0700, Frédéric Pierret wrote:
> And as I liked, see officially supported distros. The ones you cited are community only. It means that indeed sound will be broken because they are based on not even release distribution packages.
> 
> At some point we cannot work on every available distributions and moreover on testing ones...
> 
> Le October 18, 2021 3:34:15 PM UTC, TNT BOM BOM ***@***.***> a écrit :
> >But you didnt solve the issue where distros based on debian testing
> >whats going to do? 
> >
> >kali,ubuntu... these are not stable debian versions.
> >
> >Unless the solution to these distros is yeah enjoy your experience
> >without a sound support.

There's a difference between Ubuntu and kali, or Parrot, which have
chosen to base themselves on Debian testing. Ubuntu is stable - they are
(by design) not.
And it's not that they are using a rolling distro like Arch -
they are using a *testing* version - and , as it's said -
```
Testing has more up-to-date software than Stable, and it breaks less
often than Unstable. But when it breaks, it might take a long time for
things to get rectified. Sometimes this could be days and it could be
months at times. It also does not have permanent security support.
```

So yeah, enjoy your experience without a sound support.
It'll be fixed idc.

**Comment by ahf** [comment]
When did Debian testing become unsupported in Qubes? For as long as I can remember, I have been able to mix both stable, oldstable, and testing with only very minor occasional troubles with Qubes because the Qubes packages were built for several Debian targets almost immediately after a stable rotation.

Unfortunately, this issue renders Qubes a much less interesting development platform for people maintaining software where testing on several versions of Debian is beneficial. This was always the single biggest win for me personally with Qubes.

**Comment by marmarek** [comment]
> When did Debian testing become unsupported in Qubes?

It was never supported. It works on best effort basis (in the past, and now too).
