### ISSUE TITLE
Qubes 4.1 rc-1: fedora 34 unknown filesystem type ntfs (ntfs-3g missing)

### ISSUE THREAD

**Issue by rwiesbach** [QubesOS/qubes-issues#7008]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1 rc-1

### Brief summary
as this has been part of the non-minimal templates for years, I assme this is a bug, isn't it?

**Comment by HRio** [comment]
> Closing as "not our bug" (the Qubes OS Project does not develop the software that is causing this bug). If anyone believes this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

possibly this package could be a exception, as its needed in the USB qube for backup / restore.

**Comment by unman** [comment]
On Thu, Dec 09, 2021 at 12:09:03PM -0800, Henrik Riomar wrote:
> > Closing as "not our bug" (the Qubes OS Project does not develop the software that is causing this bug). If anyone believes this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
> 
> possibly this package could be a exception, as its needed in the USB qube for backup / restore.

It is, of course, only  needed if you are attaching a device formatted
with NTFS.
I think that *most* large USB drives come preformatted like this -
whether they remain that way is down to user choice.
I don't know if this is an argument for including the driver - should we
include drivers for Apple devices, or android, on the grounds that those
devices too should be plug and play?

**Comment by HRio** [comment]
> It is, of course, only needed if you are attaching a device formatted with NTFS. I think that *most* large USB drives come preformatted like this - whether they remain that way is down to user choice. I don't know if this is an argument for including the driver - should we include drivers for Apple devices, or android, on the grounds that those devices too should be plug and play?

yes, I guess lots of large external usb3 drives comes pre-formated with ntfs. I do not know if ntfs-3g is that answer to that either, as 5.15 included a much better in kernel implementation (compared to the old kernel implementation), having that enabled in the qubes kernel could be better long term.

For me it was no problem just adding ntfs-3g in the template, but not everybody upgrading from 4.0 to 4.1 (or switching to Fedora 34 in qubes 4.0) might know about this simple solution, I guess it should at least be part of some release notices / upgrade guide, as it has just been working at least since qubes 3 and from Fedora 34 its simply not working anymore, probably due to that Fedora now uses to in kernel implementation?

All these other things you are listing are not things that have been working out of the box up till Fedora 34 became part of backup / restore in qubes.

https://kernelnewbies.org/Linux_5.15#New_NTFS_file_system_implementation
