### ISSUE TITLE
LVM2 output parsing is fragile

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7020]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

This was last observed in R4.0, but I don’t think the behavior has changed since

### Brief summary

The LVM2 storage driver parses the output of the LVM2 command-line tools.  The default output varies according to several configuration options in `/etc/lvm/lvm.conf` and should not be relied upon.  Instead, Qubes OS should use `--reportformat=json` to select JSON output.

### Steps to reproduce
I changed something in `/etc/lvm/lvm.conf` (don’t remember what, sadly).

### Expected behavior
qubesd didn’t break

### Actual behavior
qubesd broke

**Comment by andrewdavidwong** [comment]
> > This is a bug report filed against 4.2, but since 4.2 doesn't exist yet, there can't be a bug in it. (A bug is a flaw in something that exists. This would mean that we plan to introduce a bug in 4.2, which is obviously not what you intended.) So, I'm changing this from a bug to an enhancement.
> 
> I intended it as “this is a flaw in R4.1 and below, but changing it in R4.1 would be too risky, so setting the milestone to R4.2”.

I think it still makes more sense to classify it as an enhancement rather than a bug in that case, because it's a flaw we don't intend to fix in any existing release. Instead, we plan to fix it by introducing a new and improved release down the line in which the flaw no longer exists.

If it would be too risky to introduce the fix in a patch release (e.g., 4.1.1) because it would be a backward-incompatible change, then it should be targeted at the next major release, which would be 5.0. (Minor releases like 4.2 should only add functionality and bug fixes in a backward compatible manner.)
