### ISSUE TITLE
Qube settings revert back after clicking "apply"

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7039]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

Reported at https://groups.google.com/d/msgid/qubes-users/93ac8e99-6591-4682-a4aa-651d2cabdb53n%40googlegroups.com

### Qubes OS release

R4.1

### Brief summary

After clicking "apply", the settings (at least "start qube automatically on boot") revert back to previous value. If then "ok" is clicked, that old setting is saved - reverting what "apply" did.

This happens only when qube settings is started from within of qube manager.

### Steps to reproduce

  1)  Highlight the qube I want to get to open automatically on boot in the
Qubes manager.
  2)  Click on the 'Qube Settings' cog button and the manager opens to the
'Basic' page.
  3)  Click to check the 'start qube automatically on boot' box, the check
mark appears.
  4)  Click on 'Apply'.  The system working icon appears, the change looks
to be working but then the check mark disappears.
  5)  Click on 'OK' and the manager window closes,  the desired change has
not happened.

### Expected behavior

Settings stay changed after "apply".

### Actual behavior

Settings visible in qube settings window revert to previous value after "apply" (but the actual qube properties are changed). If user clicks then "apply" or "ok" again, those reverted values are saved - undoing the changes.

**Comment by 51lieal** [comment]
It happens to me since 4.1 alpha first signed announcement, it's not only in the 'start qube automatically on boot' but in everywhere inside qubes-qube-manager basic and advanced menu. Solution is, you need to click apply 2 times then 'ok' button, clicking  apply 1  time will revert it back to original. I'm always in current-testing repo with latest-kernel.

I forget if it does in 4.0, too old to be remember.

> happens when qube settings is opened from within qube manager

So this mean open 'qube settings' from domain menu? Change settings in each qube is much simple and fast with qubes-qube-manager especially when changing many vm with lot of configuration.

_(I really have a problem replying in qubes-users)_
