### ISSUE TITLE
Better handling for infinite qrexec launch chains

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7046]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Suppose a user has a disposable template qube X that (a) is its own default DispVM template and (b) is set to open files in a DispVM.  In that case, if another qube tries to open files in X, it will recursively spawn DispVMs until the system runs out of memory, which is a rather poor user experience.

### The solution you'd like
`qvm-open-in-dvm` and friends should detect such nonsensical recursive invocations and do something useful.  Possible options include displaying an error message explaining the misconfiguration and opening the file in the qube itself (without creating a new DispVM).

### The value to a user, and who that user might be
Users will be less likely to panic and wonder what is causing a ton of DispVMs to launch :laughing:.

**Comment by iamahuman** [comment]
> displaying an error message explaining the misconfiguration

A dialog, nice.

> and opening the file in the qube itself (without creating a new DispVM).

Perhaps ask for user consent on this, in that dialog?

**Comment by DemiMarie** [comment]
A simple version of this would be for `qubes.StartApp` to skip `/usr/share/applications/qvm-open-in-dvm.desktop` if running in a DisposableVM, as it is basically never what one wants.

**Comment by TheWanderer1983** [comment]
Here is another edge case that needs some sanity checks. I have a non disp qube that loads all my hyperlinks to a disp. It works great if the disp has web browser in it. It does the same infinite spawning of disps if no browser is present.

**Comment by TheWanderer1983** [comment]
Was there recently an update to this? Everything was working for me but now only opening attachments work as expected. Any hyperlinks clicked from emails now are causing the infinite open of disps. 
I disabled the service and tried using using the DisposabelOpen.desktop method with the mimeapps.list all pointing to the disposable. I then added 
 the /etc/qubes/policy.d/30-user.policy
qubes.OpenInVM  *  disp-multi @dispvm allow target=Personal-Mail

It seems to have the same issue. Attachments open fine but hyperlinks from thunderbird go into infinite spawn of disps.

**Comment by TheWanderer1983** [comment]
Turns out it was this issue after all. Sorry to flood this issue.  I removed the ~/.local...qvm-open-in-dvm.desktop and /usr/share/applications... desktop from the disp and it now works again. I should of dug deeper before posting here. It was a little strange given it fixed itself after I installed a browser in the disp and then just stopped working with no changes to the disp or the thunderbird qube as i detailed in my first post.

**Comment by DemiMarie** [comment]
There are two solutions:

1. Check if this is a disposable VM started by `qubes.OpenURL` or `qubes.OpenInVM`, and refuse to start another disposable VM.  This is problematic because users might want to actually do that.
2. Patch `xdg-open` (used by `qubes.OpenURL` and `qubes.OpenInVM`) to do the right thing and refuse to launch `qvm-open-in-dvm.desktop`.

**Comment by marmarek** [comment]
> * Patch `xdg-open` (used by `qubes.OpenURL` and `qubes.OpenInVM`) to do the right thing and refuse to launch `qvm-open-in-dvm.desktop`.

Or maybe modify `qubes.OpenURL`/`qubes.OpenInVM` to check first (via xdg-mime?) what application would be used and refuse to use `qvm-open-in-dvm.desktop`? 

Or another variant of this - modify `qvm-open-in-dvm.desktop` to refuse to be launched from `qubes.OpenURL` / `qubes.OpenInVM` ? Should be rather easy with an environment variable I think.
But whichever solution you choose, it should be smart - it's about preventing infinite chain caused by a single open action. But for for example, if you open a PDF document in a DispVM, and then click on a link there, it should still be possible to get it opened in another DispVM (and similar for opening a document in DispVM from a DispVM started via `qubes.OpenURL`).

Whether to support `qubes.OpenInVM`->`qubes.OpenInVM` chains (via `qvm-open-in-dvm.desktop`) but with different documents, I'm not sure, as I don't see a way for the user to configure such chain in any sensible way. There is always an option to either open in DispVM from a context menu in a file manager (it should still work, as it doesn't go through `qvm-open-in-dvm.desktop`), or from the command line.

In all the cases, there should be also some message to the user why opening didn't work.

**Comment by DemiMarie** [comment]
What about prompting the user with an “Are you sure you want to do this?” prompt?  A flag file could be used to ensure that the user is prompted only once.

**Comment by marmarek** [comment]
On Wed, Oct 18, 2023 at 07:12:11PM -0700, Demi Marie Obenour wrote:
> What about prompting the user with an “Are you sure you want to do this?” prompt?  A flag file could be used to ensure that the user is prompted only once.

That might work.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab

**Comment by marmarek** [comment]
Done in https://github.com/QubesOS/qubes-core-agent-linux/pull/469
