### ISSUE TITLE
Sound Open Firmware in dom0 is too old

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7055]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1

### Brief summary

See https://github.com/QubesOS/qubes-issues/issues/6411#issuecomment-945983086.  This is about the audio problem, which is due to old firmware in dom0.

### Steps to reproduce
See the linked issue.

### Expected behavior

Sound works.

### Actual behavior

Sound fails.

**Comment by solardiz** [comment]
Thanks @DemiMarie. Copying the relevant part of my comment in here, with minor updates:

On Intel Tiger Lake, built-in audio doesn't work in Qubes out-of-the-box. (Audio output via HDMI works, though.) In `dmesg`, it can be seen that the driver complains about missing firmware file. Fedora provides the firmware in `alsa-sof-firmware`, which is (apparently) now installed as fix for #6934. However, installing this package didn't make a difference here because the F32 revision of it is too old to have files for Tiger Lake. So I ended up downloading `sof-bin-v1.9.tar.gz` and manually putting the Intel-signed firmware and topology files in place. The Qubes F32 kernel then complains about ABI version mismatch (kernel's 1.7 vs. firmware's 1.9), but works anyway. With this, audio output starts to work fully (both built-in speakers and external headphones when connected), audio input partially (built-in mic has unusably low sensitivity, which I suspect is a software issue, while external works fine when connected). I had also tried version 1.8 of the SOF files (before 1.9 came out) - with that, puzzlingly the external mic only worked well in dom0, but not at all via pass-through into a VM (I suspect somehow the built-in mic was getting passed through; I wonder what this has to do with SOF files versions - maybe the topology?)

I guess upgrading the dom0 system to newer Fedora would also fix this issue, although I didn't check whether/when Fedora got the proper files in its `alsa-sof-firmware`. Version 1.9 was released between F34 and F35, so it's probably not in F34 (maybe in updates?) and might be in F35. Someone would need to check.

If R4.1 has to stay with F32, then a Qubes OS custom fix would be needed - such as taking this one package from F35+ or maintaining a Qubes OS own one (and accepting the ABI version mismatch, with unknown consequences)?

**Comment by logoerthiner1** [comment]
https://forum.qubes-os.org/t/r4-1-audio-does-not-go-from-appvm-to-dom0-in-default-installation/9532/15

One method to make Intel Tiger Lake Audio Controller work in the latest R4.1, for reference. So it seems that sys-audio is an alternate way of dealing with new audio hardware problems.

**Comment by marmarek** [comment]
Updated alsa-sof-firmware is available in current-testing: https://github.com/QubesOS/updates-status/issues/3022

**Comment by aslfv** [comment]
Audio (Intel Alder Lake PCH-P High Definition Audio Controller) still not working when using alsa-sof-firmware from current-testing. Interestingly: 
1. When using current alsa-sof-firmware [alsa-sof-firmware-2.1.1-1.fc32.noarch.rpm] Qubes OS takes more than 2 min to boot and then shows the following error message:
`[FAILED] Failed to start udev Wait for Complete Device Initializations.` 
2. The only way to prevent the above (1.) (and still without audio) is to install also-sof-firmware < 2.0 OR to use the following kernel parameter (in GRUB):
`snd-intel-dspcfg.dsp_driver=2` 
3. audio will only partly work in Qubes OS when first booting into Ubuntu (22.10) and then performing a warm reboot (with alsa-sof-firmware-2.1.1). Partly means: sof-hda-dsp appears as output devices (instead of Dummy) but only the audio headphone jack is working.

**Comment by marmarek** [comment]
I assume sound fully works under Ubuntu 22.10, right? If so, it may not be (only) about alsa-sof-firmware, as Ubuntu is shipping older one (2.0). Can you check with Fedora 36 Live DVD image?

**Comment by marmarek** [comment]
The alsa-ucm-conf is included in https://github.com/QubesOS/qubes-alsa-lib, version 1.2.4 specifically. Maybe it isn't installed? The package name is `alsa-ucm`. There is also related `alsa-topology` package.
If newer is needed, I can probably include an update too.

**Comment by aslfv** [comment]
Thank you. I had already the latest `alsa-ucm` installed. Installing `alsa-topology` did not solve the issue neither. I do not know if, and how to know if, newer packages would be needed / would help.

**Comment by aslfv** [comment]
> If newer is needed, I can probably include an update too.

Would it be possible to have the update that you, @marmarek, proposed? I am not sure if it will help but I am happy to give it a try. 

Otherwise I am not sure where to look for solutions. I doubt that setting up an audio vm (https://forum.qubes-os.org/t/setting-up-an-audio-vm/5491) will work given that audio is not working in dom0. Or would you consider this worth a try as well?

**Comment by aslfv** [comment]
Based on the following entries, I have tried to identify possible paths for getting audio to work:
`$ journalctl -b | grep sof
...
Sep 20 20:09:38 dom0 kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
Sep 20 20:09:38 dom0 kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: SoundWire enabled on CannonLake+ platform, using SOF driver
Sep 20 20:09:38 dom0 kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: enabling device (0000 -> 0002)
Sep 20 20:09:38 dom0 kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
Sep 20 20:09:38 dom0 kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
Sep 20 20:09:38 dom0 kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
Sep 20 20:09:38 dom0 kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 4
Sep 20 20:09:38 dom0 kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
Sep 20 20:09:38 dom0 kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:19:1
Sep 20 20:09:38 dom0 kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: warn: FW ABI is more recent than kernel
Sep 20 20:09:38 dom0 kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
Sep 20 20:09:38 dom0 kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
Sep 20 20:09:38 dom0 kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:19:1
Sep 20 20:09:38 dom0 kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: warn: FW ABI is more recent than kernel
Sep 20 20:09:47 dom0 kernel: sof_sdw sof_sdw: snd_soc_register_card failed -517
...
Sep 20 20:14:19 dom0 kernel: sof_sdw sof_sdw: snd_soc_register_card failed -517`

`$ journalctl -b | grep sound
Sep 20 20:09:40 dom0 kernel: soundwire sdw:3:025d:0714:01: Probe not complete, timed out
Sep 20 20:09:40 dom0 kernel: soundwire sdw:3:025d:0714:01: Update Slave status failed:-110
Sep 20 20:09:40 dom0 kernel: soundwire sdw:2:025d:0711:01: Probe not complete, timed out
Sep 20 20:09:40 dom0 kernel: soundwire sdw:2:025d:0711:01: Update Slave status failed:-110
Sep 20 20:09:40 dom0 kernel: soundwire sdw:0:025d:1316:01: Probe not complete, timed out
Sep 20 20:09:40 dom0 kernel: soundwire sdw:0:025d:1316:01: Update Slave status failed:-110
Sep 20 20:09:40 dom0 kernel: soundwire sdw:1:025d:1316:01: Probe not complete, timed out
Sep 20 20:09:40 dom0 kernel: soundwire sdw:1:025d:1316:01: Update Slave status failed:-110`

- [x] https://forum.manjaro.org/t/no-audio-device-detected-dell-xps-9320/118291/28 suggests that it could be related to one particular module that needs to be loaded , namely `snd_compress`. But loading the module did not solve the issue. 
- [ ] https://github.com/thesofproject/sof/issues/2901 suggests that the issue could be related to an outdated `alsa-topology` if I understood correctly. So updating these packages could indeed help.
- [ ] https://bbs.archlinux.org/viewtopic.php?id=278572 suggests that the issue could be related to the sequence at which the modules / the firmware (sof) are loaded. It is difficult for me to understand why this would be the case, and how to try this out in Qubes OS.

**Comment by aslfv** [comment]
> * https://bbs.archlinux.org/viewtopic.php?id=278572 and https://wiki.archlinux.org/title/Dell_XPS_13_Plus_(9320)#Audio suggest that the issue could be related to the sequence at which modules / the firmware (sof) are loaded, in cases where `i915` is used. It is difficult for me to understand why this would be the case, and how to try these archlinux specific instructions in Qubes OS: **What is the equivalence of `/etc/mkinitcpio.conf` in Qubes OS?**

I added the following line in `/etc/sysconfig/grub` and updated the `/boot/efi/...` but audio is still not working - assuming that this is the equivalent step to the one describe above on archlinux.org.

```
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX rd.driver.pre=snd_soc_rt715_sdca rd.driver.pre=snd_soc_rt1316_sdw rd.driver.pre=snd_sof_pci_intel_tgl rd.driver.pre=snd_hda_intel rd.driver.pre=snd_soc_sof_sdw rd.driver.post=i915"
```

**Comment by aslfv** [comment]
My issue seems to be related to "some sort of race condition" https://github.com/thesofproject/linux/issues/3777#issuecomment-1192655300. And the following fix for SOF has been proposed: https://github.com/thesofproject/linux/pull/3911

In the meantime the workaround is to either:
- use `blacklist snd_sof_pci_intel_tgl` as kernel option and then `sudo modprobe -r snd_sof_pci_intel_tgl; sudo modprobe snd_sof_pci_intel_tgl ` e.g. as a service https://github.com/thesofproject/linux/issues/3777#issuecomment-1221382023, or
- use `nomodeset` as kernel option https://github.com/thesofproject/linux/issues/3777#issuecomment-1228653110

I opted for using `nomodeset` as kernel option given that I also experienced artifacts on my splash (boot) screens (since I used kernel >= 5.18. No artifacts with `nomodeset`.

I still do not know why this issue did not appear in Ubuntu 22.10 and Fedora 36. My best guess is they both used an OEM kernel image?

**Comment by aslfv** [comment]
My issue seems to be related to "some sort of race condition" https://github.com/thesofproject/linux/issues/3777#issuecomment-1192655300. And the following fix for SOF has been proposed: https://github.com/thesofproject/linux/pull/3911

In the meantime the workaround is to either:
- use `blacklist snd_sof_pci_intel_tgl` as kernel option and then `sudo modprobe -r snd_sof_pci_intel_tgl; sudo modprobe snd_sof_pci_intel_tgl ` e.g. as a service https://github.com/thesofproject/linux/issues/3777#issuecomment-1221382023, or
- use `nomodeset` as kernel option https://github.com/thesofproject/linux/issues/3777#issuecomment-1228653110

I opted for using `nomodeset` as kernel option given that I also experienced artifacts on my splash (boot) screens (since I used kernel >= 5.18. No artifacts with `nomodeset`.

I still do not know why this issue did not appear in Ubuntu 22.10 and Fedora 36. My best guess is they both used an OEM kernel image?
