### ISSUE TITLE
Error message when closing Whonix DispVM over sys-whonix

### ISSUE THREAD

**Issue by Minimalist73** [QubesOS/qubes-issues#7067]
### Qubes OS release
4.1

### Brief summary
When closing a DispVM based on the Whonix DispVM Template, an error message appear

### Steps to reproduce
- Open a Whonix DispVM
- Wait a few seconds after it start
- Close the main window to stop the DispVM
- Error box appear

### Expected behavior
No error message should appear

### Actual behavior
Error message appear each time a Whonix DispVM shutdown.
Both GW and WS Templates are updated.

![2021-11-15-131633](https://user-images.githubusercontent.com/51658826/141780953-aee0c807-fc53-4eba-8ad3-5c1206d20101.png)

Quoting message from @DemiMarie: https://github.com/QubesOS/qubes-issues/issues/6983#issuecomment-968966681

**Comment by lubellier** [comment]
Env: 4.1-rc2

Test Results:
- fails with the SdwdateStatus popup when closing main window to stop the DispVM
- fails with the SdwdateStatus popup when running `qvm-shutdown dispXXXX`

Diagnosis : from @DemiMarie 's [#6983 comment](https://github.com/QubesOS/qubes-issues/issues/6983#issuecomment-968966681) "_A qrexec call can fail because the destination VM does not exist, which is happening in this case. This is a race condition that should really be fixed._"

**Comment by lubellier** [comment]
linked to [#7013](https://github.com/QubesOS/qubes-issues/issues/7013), duplication...

**Comment by marmarek** [comment]
This is mostly a consequence (duplicate?) of https://phabricator.whonix.org/T930

**Comment by adrelanos** [comment]
> This is mostly a consequence (duplicate?) of https://phabricator.whonix.org/T930

Funding available. Anyone up to implement this?

**Comment by andrewdavidwong** [comment]
> linked to [#7013](https://github.com/QubesOS/qubes-issues/issues/7013), duplication...

This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
