### ISSUE TITLE
R4.1 Qubes Manager sort by State fails to group dom0 with other running VMs

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#7073]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1rc1 fully updated

### Brief summary
R4.1 Qubes Manager sort by State fails to group dom0 with other running VMs

### Steps to reproduce
1. Start at least one domU VM.
2. Open Qubes Manager.
3. Click on State column.
4. Note that running VMs (shown with green dot) are grouped at the beginning of the list, but dom0 (also shown with green dot) is at the end of the list, while all non-running VMs are shown in between.

### Expected behavior
dom0 would be grouped with running VMs.

### Actual behavior
Schrödinger's dom0 off by itself in third section of the list.

Note that this bug is rather minor...but could lead to some problems. E.g. if you had planned to take some action that required all domU VMs to be halted but had mistakenly reverse sorted the list, you will see only dom0 "running" at the top. If your list of VMs is long enough, you might assume no other VMs are running, when in fact the running VMs are now at the bottom of the list off-screen.

B

**Comment by andrewdavidwong** [comment]
https://github.com/QubesOS/qubes-issues/issues/7632#issuecomment-1190985511 :

Oh, I see what's happening: The sorting is inverted! In order to get all running qubes to the top of the list, I have click the "State" column heading twice. The first time I click it, it puts only dom0 at top and all running qubes at the bottom of the list. The second time I click it, it inverts the list, so dom0 is at the bottom while all running qubes are at the top. But here's the telltale sign: The running qubes are in *reverse* alphabetical order! In other words, the running qubes are all sorted together, then *subsorted* in *reverse* alphabetical order at the top of the whole Qube Manager list.

So, this is definitely a regression from the 4.0 Qube Manager.
