### ISSUE TITLE
bad interaction of default_guivm setting with guivm determination at default_guivm shutdown 

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#7106]
### Qubes OS release

4.1rc2

### Brief summary

Starting state: `default_guivm` == `dom0`.  I launch some VMs, then set `default_guivm` to `sys-gui-gpu`.

Then:

```
[yann@dom0 ~]$ qvm-start sys-gui-gpu
[yann@dom0 ~]$ less /var/log/xen/console/guest-sys-gui-gpu-dm.log /var/log/xen/console/guest-sys-gui-gpu.log
[yann@dom0 ~]$ qvm-shutdown sys-gui-gpu
sys-gui-gpu: Shutdown error: There are running VMs using this VM as GuiVM: qubes-builder, sys-firewall, sys-gui-gpu, sys-net
```

There is a problem: all those listed VMs really use `dom0` as guivm. Maybe except `sys-gui-gpu` itself, but that one should not prevent itself from shutting down either, I guess.

In any case, I just launched that VM, it did not start up enough to do its job as a guivm, nothing should get in the way of shuting it down.

**Comment by ben-grande** [comment]
Should the global preference `default_guivm` be prevented from switching if there are running qubes using it?

Normally it requires a restart of the clients but in the `GPU` case, it can require a restart of the host, as [instructed in the docs](https://www.qubes-os.org/doc/gui-domain/#gpu-gui-domain-sys-gui-gpu).

> In any case, I just launched that VM, it did not start up enough to do its job as a guivm, nothing should get in the way of shuting it down.

That is the behavior for any qube that uses another qube for `netvm`, `audiovm` and others. If you want to force shutdown, use the `--force` flag, but the default behavior shouldn't change, it is a dependency.

**Comment by ben-grande** [comment]
Not resolved and I don't think it should be.

**Comment by ben-grande** [comment]
The second option.

It is not possible to prevent switching a Global prefs because some qubes are using it as the GuiVM. This is the most weird case as other global prefs do not cause this problem when being modified, most cause when trying to shutdown a qube depending on it.

I'd say that if blocking changing the global prefs for qubes that use the default guivm is not planned to do, not blocking shutdown is not an option (can be overridden with --force as explained above).
