### ISSUE TITLE
Error checking storage configuration

### ISSUE THREAD

**Issue by lordmtrx** [QubesOS/qubes-issues#7117]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1.0-rc2

### Brief summary

Unable to start installation because of the error 'Error checking storage configuration'

### Steps to reproduce

Proxmox virtual machine with default Virtio configuration.

Automatic partition. Also tried without encryption passphrase.

Destination drive should be marked as invalid

### Expected behavior

Installation proceeds

### Actual behavior

Unable to proceed installation

**Comment by andrewdavidwong** [comment]
Installing Qubes OS in a virtual machine is not supported:

https://www.qubes-os.org/faq/#can-i-install-qubes-in-a-virtual-machine-eg-on-vmware

**Comment by lordmtrx** [comment]
Do note that the stable release 4.0.4 does not have this bug and installed fine. I also want note that the RC is shown above the stable release on the homepage where a development build would be expected below or on another page even. If the RC introduces an new feature which makes it impossible to install inside a virtual machine it should be clearly marked as 'You cannot install this inside a virtual machine <link to page>. because this is the only project that I came across that does not support a virtual machine. I wouldn't check the FAQ for a vague error message in a RC release.

**Comment by andrewdavidwong** [comment]
> I also want note that the RC is shown above the stable release on the homepage where a development build would be expected below or on another page even.

They are simply listed from newest to oldest. We have clear messages above each one indicating their status.

> If the RC introduces an new feature which makes it impossible to install inside a virtual machine it should be clearly marked as 'You cannot install this inside a virtual machine .

We would have to put that warning on every release, since no releases support being installed in a VM. It wouldn't be reasonable to put warnings on every release for all the use cases we _don't_ support, as that list is infinitely long. Better just to state our policy for use cases that are frequently asked about. The FAQ seems like a sensible place for something that's frequently asked about.

If a release happens to be installable in a VM, that should be considered a matter of luck. We don't promise to support something just because it happened to be possible on an earlier release (especially when our policy from the outset has been that we don't support it).

> because this is the only project that I came across that does not support a virtual machine.

To be fair, though, this is probably also the only project you've come across that uses its own baremetal hypervisor as part of a security-oriented desktop operating system, right?
