### ISSUE TITLE
Allow to pass CDROM argument for HVMs from qubes-manager

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#712]
**Reported by joanna on 20 Feb 2013 19:27 UTC**
Currently this is only possible from command line via qvm-start --cdrom option.

The challange here is that the ISO might be located in another VM, so opening up a file select dialgo box is probably not the best option. Unless we can fire up file manager in the dest VM (pointed by user) and then choose a file there, and translate this a string like:

vmname:/path/in/the/vm/to/iso

Needs more rethinking.

Migrated-From: https://wiki.qubes-os.org/ticket/712

**Comment by adrelanos** [comment]
I cannot find this "configure path to cdrom or iso" feature in Qubes VM Manager, VM settings. Has this feature been removed in meanwhile?

I think it would be useful to have to creating Windows (and other) HVMs. Instructions on https://www.qubes-os.org/en/doc/hvm-create/ currently requires a terminal because of this.

**Comment by adrelanos** [comment]
Nevermind. Found it. Qubes VM Manager, VM settings -> Advanced -> Additional drive
