### ISSUE TITLE
Template updates fail with a VMRootShell permission error

### ISSUE THREAD

**Issue by ekaflaer** [QubesOS/qubes-issues#7122]
### Qubes OS release
Qubes 4.1 RC2

### Brief summary
I have upgraded QubesOS from 4.0 to 4.1 RC2 without any issues.

But now if I run the Qubes Updater dom0 can be updated, but if the templates are updated I run into a permission issue.

The management vm `disp-mgmt-debian-11` is reported as started, the template vm never seems to get startet and shortly after I get the error message box:

```
Denied: qubes.VMRootShell
Denied qubes.VMRootShell from disp-mgmt-debian-11 to debian-11
```

The output of the updater looks as follow:
```
Updating debian-11

Error on updating debian-11: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=debian-11', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 20.
debian-11:
      ----------
      _error:
          Failed to return clean data
      retcode:
          126
      stderr:
          Request refused
      stdout:
```
The same happens if I run the update command outside of Qubes Update.

### Steps to reproduce

1. Upgrade from QubesOS 4.0 to 4.1
2. Run `Qubes Update` against one template
3. Check the results

### Expected behavior

Qubes Update works as expected without permission errors

### Actual behavior

Qubes Update can not update the templates because of permission errors

**Comment by marmarek** [comment]
Do you get a notification about failed template start (not enough memory maybe)? If no, can you look into `journalctl` for the line about the denial - you should find more details about it; just search for `qubes.VMRootShell`

**Comment by ekaflaer** [comment]
Many thanks for your help and sorry for not checking `journalctl` too.

`journalctl` showed me that the permission was denied because of `/etc/qubes-rpc/policy/qubes.VMRootShell`.

This file did had quite some entries for `disp-mgmt-*` vms and a deny for `anyvm` at the bottom.

Since the file was not tracked by an rpm package I moved it away and now it works.

From my side the bug can be closed but maybe this is an upgrading issue. I do not remember to have created or edited this file.

**Comment by qtpies** [comment]
I have this exact same issue in 4.1. Solution works.

**Comment by tlaurion** [comment]
I confirm this too after upgrading from 4.0.4

Content of qubea.VMRootShell:
disp-mgmt-fedora-33 fedora-33 allow,user=root
Then $anyvm $anyvm deny

So of course, it fails.

Even though previous 4.0.4 had fedora-34. So 4.0.4 was not using it? Or the upgrade script created it? Seems like there is some bug. I cloned 4.0.4 OEM disk image prior of testing this so if you need more info I can feed, please ask.

Is that policy still under use? How is it maintained across template upgrades? Backed up the file and removed it to proceed with template upgrades.

@marmarek ? @fepitre?

**Comment by mfc** [comment]
encountered same issue with in-place R4.0->R4.1 upgrade.

backing up `/etc/qubes-rpc/policy/qubes.VMRootShell` in dom0 and deleting it solved issue [as described](https://github.com/QubesOS/qubes-issues/issues/7122#issuecomment-994690262) by @ekaflaer

**Comment by tlaurion** [comment]
Hmmm I will try to make more time into troubleshooting this and #7114 which are blockers to actually push users into upgrading before Whonix EOL of 03/22 on Qubes 4.0.4

@adrenalos @marmarek: Delays are really short for users. Really surprised by 4.1 release having came so fast. Now we expect users to reinstall and restore backup on top of 4.1 it seems.

**Comment by tlaurion** [comment]
[rpm -qa](https://github.com/QubesOS/qubes-issues/files/8162821/Q40_rpm_qa_sorted.txt)
[qubes-dist-upgrade logs](https://github.com/QubesOS/qubes-issues/files/8164554/qubes-dist-upgrade-all.txt)

**Comment by tlaurion** [comment]
Confirm that removing `/etc/qubes-rpc/policy/qubes.VMRootShell` fixes this issue.

**Comment by tlaurion** [comment]
@marmarek : What should users to with that file /etc/qubes-rpc/policy/qubes.VMRootShell file containing:
```
disp-mgmt-fedora-33 fedora-33 allow,user=root
Then $anyvm $anyvm deny
```

Seems like it is an artifact not updated by anything anymore?

**Comment by marmarek** [comment]
While the file indeed shouldn't be left there, it shouldn't break updates. The fact it does is a bug.

**Comment by tlaurion** [comment]
@marmarek depending on timeline of that being published, I recommend that file being removed by qubes-dist-upgrade script since a lot of users will experience that issue?

**Comment by icequbes1** [comment]
I've run into this as well on an R4.0 to R4.1 upgrade performed today. I believe the fix didn't resolve the issue (or it has resolved some other pre-existing issue).

I used the `qubes-dist-upgrade` script to upgrade R4.0 to R4.1. The upgrade was successful.

After the upgrade, only one qube would update when using `qubesctl` from dom0. Upgrading within the qube using `apt` or `dnf` was fine.

`qubesctl` returned the "Failed to return clean data" _error, with stderr being "Request refused" attempting to update TemplateVMs, except for one TemplateVM.

`journalctl` did show RPC denies, for example a debian 11 template,

```
qrexec-policy-daemon[2260]: qrexec: qubes.VMRootShell: disp-mgmt-debian -> debian: denied: denied by policy /etc/qubes-rpc/policy/qubes.VMRootShell:7
```

The contents of `/etc/qubes-rpc/policy/qubes.VMRootShell`:

```
disp-mgmt-fedora fedora allow,user=root
# 5 lines of comments/empty lines
$anyvm     $anyvm   deny
```

My `fedora` qube is the only one which doesn't give an RPC deny in the journal; all others do.

According to my `qubes-dist-upgrade` logs, `/etc/qubes-rpc/policy/qubes.{VMRootShell,VMShell,Filecopy}` were updated during Stage 2 of the process - where TemplateVMs get their repos updated to R4.1 from R4.1. Based on timestamps, they weren't touched since (e.g., by R4.1). My `fedora` TemplateVM was the last of this stage to get updated.

So what it appears is that the last TemplateVM to be upgraded (while still under R4.0) persists in `/etc/qubes-rpc/policy.qubes.VMRootShell`.

Once under R4.1 it looks like `qubesctl` updates these policies to allow the management VM to execute commands, but uses the R4.1 syntax at `/etc/qubes/policy.d/50-qubesctl-salt.policy` (which gets deleted afterwards, if it was empty to begin with).

I'm not up to speed how the R4.0 policies get evaluated while under R4.1 and how conflicts are dealt with, but it seems like what is happening is:

R4.1 sees this in `/etc/qubes/policy.d/`:

```
qubes.Filecopy * disp-mgmt-debian debian allow user=root
qubes.VMShell * disp-mgmt-debian debian allow user=root
qubes.VMRootShell * disp-mgmt-debian debian allow user=root
```

as well as this in `/etc/qubes-rpc/policy/`:

```
disp-mgmt-fedora fedora allow,user=root
$anyvm     $anyvm   deny
```

And ultimately when trying to update a `debian` qube it denies the request. Only `fedora` qubes are allowed.

Removing the `/etc/qubes-rpc/policy/qubes.VMRootShell` does resolve the issue since it appears to be leftover while under R4.0.

But is this expected behavior to be ignoring the R4.1 RPC policies or allowing the R4.0 policies to override them?
