### ISSUE TITLE
IPv6 routing between AppVMs

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#718]
**Reported by joanna on 24 Feb 2013 15:33 UTC**
None

Migrated-From: https://wiki.qubes-os.org/ticket/718

**Comment by marmarek** [comment]
@woju I think we forgot about this one when implementing "NetVM" in Qubes 4.0...

**Comment by iggs0** [comment]
I'm a little bit disappointed now. I was looking forward to setup and use Qubes OS. Finally with a new machine I did this today using Qubes OS 3.2 rc 2.

I struggled a bit with networking (so my hope is I'm doing something wrong) but finally I got it working. But I did not get an IPv6 assigned (This works properly in my network).

So to be clear: This really means as of today there is no IPv6 in Quebes and for the future you are looking to NAT it ?

I would be happy to "turn" off all firewall features of Qubes OS since I got this covered by an rather extensive network setup. Is this an option ?

**Comment by marmarek** [comment]
On Fri, Aug 12, 2016 at 03:30:41PM -0700, iggs0 wrote:
> So to be clear: This really means as of today there is no IPv6 in Quebes and for the future you are looking to NAT it ?

Yes.

> I would be happy to "turn" off all firewall features of Qubes OS since I got this covered by an rather extensive network setup. Is this an option ?

It depends what you call "all firewall features". You don't need to use
outbound traffic limiting ("Firewall" tab in VM settings). You can even
disable "qubes-firewall" service in Proxy VMs (which will really do
nothing anyway if you don't fill "Firewall" tab in VM settings).

But you can't disable NAT. This is rather unavoidable(*) with tree-like
structure of network connections between VMs (sys-net -> sys-firewall ->
AppVMs, possibly sys-whonix in between).

(*) without modifying every routing table in your LAN.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Script mentioned above: https://github.com/marmarek/qubes-core-agent-linux/commit/789eb511266d9e8bd812e40f952ec2bce6d7a414
