### ISSUE TITLE
Incomplete link to developer FAQ

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#7199]
In the [developer documentation](https://www.qubes-os.org/doc/#developer-documentation) the FAQ should probably point to the [developer section of the FAQ](https://www.qubes-os.org/faq/#developers).

I was trying to do a PR and couldn't find the place to update the index since it's no longer in [doc.md](https://github.com/QubesOS/qubes-doc/blob/master/doc.md).

**Comment by andrewdavidwong** [comment]
Actually, this commit simply caused the link to disappear from the rendered list due to the way the `.yml` file is processed. `#anchors` aren't processed, so this doesn't work. Three choices:

1. Allow the link to no longer appear in the rendered list.
2. Revert this commit and have a link to the FAQ page as a whole (as opposed to an anchor link to a specific section of that page).
3. Find some way change the URL processing to handle `#anchors` (PRs welcome).

I'll default to (1) in the absence of further input.

**Comment by deeplow** [comment]
Could it be that it's interpreting as an inline YAML comment? I mean, in theory it shouldn't because in YAML comments only count if they [have a whitespace before](https://yaml.org/spec/1.2.2/#66-comments).

If that's the issue these options may solve it.
1.  Escaping it 
    ```yaml
     - url: /faq/\#developers
     ```
2.  quotations
    ```yaml
     - url: "/faq/#developers"
     ```

**Comment by andrewdavidwong** [comment]
> Could it be that it's interpreting as an inline YAML comment? I mean, in theory it shouldn't because in YAML comments only count if they [have a whitespace before](https://yaml.org/spec/1.2.2/#66-comments).
> 
> 
> 
> If that's the issue these options may solve it.
> 
> 1.  Escaping it 
> 
>     ```yaml
> 
>      - url: /faq/\#developers
> 
>      ```
> 
> 2.  quotations
> 
>     ```yaml
> 
>      - url: "/faq/#developers"
> 
>      ```

No, I don't think so, since that should just result in the same URL as before, ignoring the "comment."

It's been a while since I looked at the code, but I think it just expects a relative path formatted a certain way.

**Comment by deeplow** [comment]
> It's been a while since I looked at the code, but I think it just expects a relative path formatted a certain way.

I guess that's it, then. I was also looking at the code and it looks quite a bit complex. Probably not worth the effort. I guess let's just close this, then.
