### ISSUE TITLE
fedora34-appvm will always show qrexec-daemon startup failed

### ISSUE THREAD

**Issue by Nurmagoz** [QubesOS/qubes-issues#7256]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

Trying to work on fedora-appvm

### Steps to reproduce

make fedora-appvm based on fedora-34-template (full version) and then open it/close it

### Expected behavior

No errors

### Actual behavior

(Browse-Fedora is the name of the appvm)

qrexec-daemon.c:135:sigchld_parent_handler: Connection to VM failed

![fodoraqrexec](https://user-images.githubusercontent.com/11895339/153199858-9751d82a-a8e5-486f-aa9d-113e066c90f8.png)

**Comment by jamke** [comment]
I have absolutely the same message:
`qrexec-daemon startup failed: 2022-11-16 12:17:08.046 qrexec-daemon[26396]: qrexec-daemon.c:135:sigchld_parent_handler: Connection to the VM failed`

but on up-to-date R4.1.1 with fedora-36 or other template (e.g. fedora-35).

In my case I see that message when I'm trying to start qube that has USB controller attached to it. It's the most important detail in my case. If I remove USB controller from list of the qube settings and keep everything else the same - the qubes starts.

So, currently I have no way to create a usb qube (manually) due to that issue. Please help with ideas.
