### ISSUE TITLE
Attempting to update for QSB-078 results in file conflicts

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7337]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1

### Brief summary

If I have `kernel-5.10.104-1.fc32.qubes.x86_64` installed, applying the QSB-078 patch results in a file conflict error because `kernel-5.10.104-1.fc32.qubes.x86_64` and `kernel-5.10.104-2.fc32.qubes.x86_64` both provide some of the same build-id files.

### Steps to reproduce

See above

### Expected behavior

No file conflict

### Actual behavior

File conflict

**Comment by brendanhoar** [comment]
Confirmed in 4.0 as well, but I did not reboot after the last set of kernel updates yesterday (which may not matter).

B

**Comment by andrewdavidwong** [comment]
Duplicate of #7336

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by DemiMarie** [comment]
@andrewdavidwong I am pretty sure this is not a duplicate of #7336.  Both cause dom0 updates to fail, but for different reasons.  Also, the fix for #7336 was in the lvm2 package and could not have fixed this issue.

**Comment by andrewdavidwong** [comment]
Please indicate this in the issue next time. Otherwise it just looks like a duplicate as result of not having seen the (extremely similar) related issue.

-------
**General Disclaimer:** We have no way of knowing which related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues you've already seen, unless you tell us. Many people file issues without [searching through any existing issues](https://www.qubes-os.org/doc/issue-tracking/#search-tips). So, unless you indicate otherwise, we may operate under the working assumption that you're unaware of any related issues. Even if we have reason to believe you're aware, we may still mention related issues for the benefit of others and in order to cross-link the issues for ease of future reference. This allows us to help the greatest number of people, since users are helped by being pointed to related issues of which they were unaware while they are not harmed by being pointed to related issues of which they were already aware.
