### ISSUE TITLE
X/ImageMagick utility `import` hangs a qube

### ISSUE THREAD

**Issue by iacore** [QubesOS/qubes-issues#7384]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
r4.1

### Brief summary
```
       import  -  saves any visible window on an X server and outputs it as an
       image file. You can capture a single window, the entire screen, or  any
       rectangular portion of the screen. The window to capture is selected by
       clicking the desired window or a program option.
```

Running `import a` in VM will brick that VM until restart.

### Steps to reproduce
1. Install `import` from imagemagick
2. Run `import a` in terminal

Reproduced in Arch Linux & Fedora 32.

### Expected behavior
System no freeze

### Actual behavior
System freeze, GUI and qrexec unresponsive

**Comment by logoerthiner1** [comment]
If you have accidentally run `import a` inside your appvm, you can run `qvm-run --pass-io vmname "pkill import"` in dom0 terminal.

I will try if you run `import a` in dom0.

**Comment by lubellier** [comment]
Hi @locriacyber ,
I suppose you don't use sys-gui, isn't it ? So dom0 manages your display and so you do the screenshots from dom0.
For doing screenshot, you should use the XFCE screenshooter from dom0 (Q menu -> System Tools > Screenshot). You can also use `import` as follow (see `man import`):

```
[user@dom0 ~]$ import -screen a.png
[user@dom0 ~]$ file a.png
a.png: PNG image data, 1920 x 1080, 8-bit/color RGB, non-interlaced
```

So IMHO, your report isn't a bug, if you agree, close it.

Note: you said you reproduced with the Fedora-32 in a VM, is it really a VM or dom0 ? Because If it's a VM, this version is EOL, you should use Fedora-34.

**Comment by logoerthiner1** [comment]
> Hi @locriacyber , I suppose you don't use sys-gui, isn't it ? So dom0 manages your display and so you do the screenshots from dom0. For doing screenshot, you should use the XFCE screenshooter from dom0 (Q menu -> System Tools > Screenshot). You can also use `import` as follow (see `man import`):

IMHO this issue is not about snapshoting, but about that, despite meaningless to snapshot in appVM, the snapshot utility exists, and what is worse, once `import a` is executed, there is no obvious way to exit. How to take snapshot is not important here.

This issue is quite common - `import module` is common in python scripts, and if a python script without the first line `#!/usr/bin/python` is executed directly, `import module` or anything similar will be parsed as shell command and this scenario happens. This may happen many times if you are using linux for some years.

**Comment by adrelanos** [comment]
Affects Qubes R4.3.

**Comment by marmarek** [comment]
That looks to be inherent to not allowing a VM to do the whole X server grab - allowing it would be a security issue (since it could for example steal input events from other VMs). That's not going to change, `import` tool is not really compatible with Qubes VM, so it can be interpreted as "won't fix".

In practice, the practical problem happens when python script is called as bash script, where grabbing screen content wasn't intended anyway, so fixing `import` tool isn't desirable outcome anyway.
