### ISSUE TITLE
Window focused in VM does not raise

### ISSUE THREAD

**Issue by iacore** [QubesOS/qubes-issues#7403]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
r4.1

### Brief summary
When a X window in VM focus another window in the same VM, the mapped window in dom0 does not raise to the top.

### Steps to reproduce
Open any link in VS Code while the web browser is open. VS code should be at top.

### Expected behavior
Open link in browser + raise browser to the top

### Actual behavior
Open link in browser. Browser still at where it was.

**Comment by locriacyber** [comment]
Need change to GUI protocol to allow client feedback of window focus.

**Comment by marmarek** [comment]
We have https://github.com/QubesOS/qubes-gui-common/blob/master/include/qubes-gui-protocol.h#L215 already which is a bit related, although not the same.

It was a design decision to not let a VM to switch focus in dom0 on its own. This would be bad if VM could steal focus from another VM this way. But within the same VM it should be fine, as long as we can ensure this property. I'm not sure how to do it race-free...

**Comment by logoerthiner1** [comment]
https://forum.qubes-os.org/t/feature-request-display-current-domain/10049/7
https://forum.qubes-os.org/t/display-not-updating-to-show-current-program/10241/4

One sentence to summarize: Dom0 disagrees with appVMs on which window is focused, which windows are minimized or in the other workspace, and maybe the z axis of each window.

This problem exists at least ever since Qubes OS R3.2 (when I learnt insecurity of X protocol and tried Qubes OS), in my experience. VSCode and Google Chrome often shows this issue and when you believe you are operating on one window in dom0 view, you are actually operating in VSCode or Google Chrome in the other view. Even when you have minimize the VSCode window, VSCode will still eat away your keyboard and mouse event.

Sometimes it may be that your keyboard / mouse operation is taken away by a window in another workspace. This makes dragging files to other window unsafe, since you may drag it to some unrelated window.

Dom0 disagree with appVM on which window should be focused, and moreover disagree with appVM on the order that the window arranges (z axis). I suspect whether appVM has the concept of Workspaces.

For focusing problem, if changing dom0 source code is hard, why not (1) when appVM want to switch focus, dom0 rejects this request and tells the appVM to focus the original window again, and (2) use "Notify of urgency by making window's decoration blink" or anything similar to mark urgency. This is one of the solutions that is equally good in user experience.

Problem is more complex about the windows in other workspace or merely minimized (hidden in general). How can dom0 tell appVM to not let the hidden windows take away events?

I do not know about whether dom0 and appVM agree on z-axis of each window. I have skimmed the qubes-gui-daemon `xside.c` and did not notice that the daemon explicitly synchronize the z-axis info. I am unfamiliar with GUI protocol anyway.

Actually it will not surprise me if this can only be solved in R4.2 since it requires change in both client side (to tell dom0 focus change) and server side (to reject focus change and tell the correct focus and mark urgency). I have been satisfied with R4.1 about the GUI improvement since the cursor can change now.

I have been using a workaround ever since I am struck by the problem - focus in and out and in and out and finally the VM should know which window I am operating on. This "focus in and out and in and out" have been one of actions that is as common as "Ctrl+Shift+C" "Ctrl+Shift+V", and if the problem persist, I strongly suggest that this problem should be documented as a "known glitch" that will not be fixed anytime soon.

**Comment by DemiMarie** [comment]
> Sometimes it may be that your keyboard / mouse operation is taken away by a window in another workspace. This makes dragging files to other window unsafe, since you may drag it to some unrelated window.

Yeah, it is unsafe sadly.  My Wayland agent (GUI agent as a Wayland compositor) simply leaves this unimplemented (so drag and drop does not work at all).  @ninavizz how bad would it be for drag and drop to be broken?

**Comment by locriacyber** [comment]
This also have the side effect of unable to focus on a window already focused in dom0, unless we send FocusIn on every mouse event (I think this was in the code (gui-agent), but I removed it because it caused some issue).
