### ISSUE TITLE
No DNS in inheriting VMs after enabling fedora-35 template's fedora-updates-testing repo and updating

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#7429]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.0

### Brief summary

If you change the flag from
0 to 1 and shut down the template, then update the template, any newly started VMs begin reporting "temporary" dns errors.

https://forum.qubes-os.org/t/r4-0-fedora-35-update-no-dns/10669/7

As per forum post, likely due to a systemd/resolved update.

### Actual behavior

**Comment by crat0z** [comment]
4.1 too. Stopping/disabling systemd-resolved fixes this.

**Comment by crat0z** [comment]
OK, I've found a somewhat better short term solution. Perform the steps below inside of a template to fix this issue for now
```
sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved
sudo rm /etc/resolv.conf
sudo touch /etc/resolv.conf
```
Some links to look at:
https://src.fedoraproject.org/rpms/systemd/commits/f35
https://github.com/systemd/systemd/pull/21317

As previously mentioned, with systemd-resolved disabled, for some reason systemd still creates the symlink to stub-resolv.conf, which is why the touch command is necessary in the above.

**Comment by lubellier** [comment]
@andrewdavidwong please, see the @Geblaat 's above comment, and add the relevant tags (4.1 stable and P:critical or P:major ?). 
Thank you.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong please, see the @Geblaat 's above comment, and add the relevant tags (4.1 stable and P:critical or P:major ?). 
> 
> Thank you.

The milestone reflects the earliest affected supported release.
