### ISSUE TITLE
Sometimes right click menu appear at topleft

### ISSUE THREAD

**Issue by logoerthiner1** [QubesOS/qubes-issues#7449]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

Sometimes right click menu does not appear at the cursor, but rather at the topleft corner of screen.

This is observed in a fedora-34-xfce based template, in thunar. This behavior does not always appear.

Maybe related to #7316 .

UPDATE: kernel 5.15+, fedora 36, on thunar this phenomenon still exists. On another VM whose file manager is gnome, the right-click menu always appear at cursor.

### Steps to reproduce

1. Open thunar in an appVM based on fedora-34-xfce
2. Spam right click on the window several times.

### Expected behavior

If a right click introduces a menu, the menu always appear at the cursor.

### Actual behavior

Some right click menu appear at topleft corner of screen.

**Comment by straussmaus** [comment]
I also notice this.  In Thunar in whonix-based Qubes.  I do not remember if it happens in Nautilus/Debian, and I can not make it do it there now.

**Comment by qwrd** [comment]
Hello.

I have noticed this happening a lot lately in Thunar. Mostly in less-often used debian-11 VM's. When Thunar window is not maximized (though I'm not sure, if this is a condition), right-clicking on a file/folder will sometimes open a context menu on the top-left of the screen rather than at the mouse cursor.

Rather annoying issue, but I'm not sure how to reproduce it reliably. Seems to happen randomly and several consecutive right-clicks, but then it starts working properly again. Strange.
