### ISSUE TITLE
Dolphin and other KDE apps' file associations broken

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#7487]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

Template includes qubes-menus package, which does not include file `/etc/xdg/menus/applications.menu`.  This causes Dolphin not to know about installed applications, therefore cannot open any file.

The fix is to create a symlink named `applications.menu` pointing to `kf5-applications-qubes.menu` in the aforementioned folder.

Normal Fedora ships `redhat-menus` RPM which has its own `applications.menu` which works fine.

**Comment by andrewdavidwong** [comment]
Does this affect only Fedora templates?

**Comment by Rudd-O** [comment]
I wouldn't know, I didn't check other templates.

**Comment by unman** [comment]
Doesnt seem to be an issue in debian

**Comment by Tellervo89** [comment]
Faced the same issue of Dolphin not recognizing any installed applications. Can confirm that the fix suggested by @Rudd-O solves the issue on Fedora Templates. The file I had to symlink was called kf5-qubes-applications.menu rather than kf5-applications-qubes.menu.

**Comment by jamke** [comment]
I have this too, `fedora-36-minimal` template is defective.
This packaging problem does not exist on fedora 35 templates, nor upstream fedora 36 . And could not find this exact issue mentioned anywhere else. So, it's a Qubes OS bug.

Currently for average Qubes OS user it's almost not possible to use KDE environment and suite-applications in main fedora templates because nothing gets open from file-manager (Dolphin).

I propose this **issue's priority to be increased**, because fedora-35 got EOL recently and in case of fedora-36 template - basic stuff like opening files does not work.

**Comment by jamke** [comment]
@Rudd-O thank you a lot for a workaround by the way! In my case is also was `kf5-qubes-applications.menu`:

For others - command to temporary solve this issue on fedora-36-minimal:
`sudo ln --symbolic /etc/xdg/menus/kf5-qubes-applications.menu /etc/xdg/menus/applications.menu`

**Comment by jamke** [comment]
The same issue on Fedora-37, Fedora-38.
For unprepared user it is still a **MAJOR** bug.
Nothing is opening from file-manager: not text files, nor images and etc.

**Comment by Rudd-O** [comment]
This better be fixed, it's a fatal user experience otherwise.

**Comment by jmickelin** [comment]
I also ran into this problem a while back, and I figured out the issue after a lot of debugging. Note that it's been a while (I should have posted this months ago!) and I'm summarizing off memory, so the details might be slightly incorrect.

### Root cause

The reason that Dolphin (or actually `kbuildsycoca5`, as I recall it) complains about not finding `/etc/xdg/menus/applications.menu` is that it is actually looking for `/etc/xdg/menus/${XDG_MENU_PREFIX}applications.menu` as per the [Freedesktop Menu specification](https://specifications.freedesktop.org/menu-spec/latest/ar01s02.html). Typically, when using a DE, this is set by the session to a suitable value so that the DE can choose its own specific menu structure, e.g. it sets the variable `XDG_MENU_PREFIX=gnome-` (note the hyphen).

The (non-minimal) Fedora template ships with packages that provide a number of different `*-applications.menu` files, such as `gnome-applications.menu` (provided by the package `gnome-menus`),  `xfce-applications.menu` (provided by `garcon`), `qubes-applications.menu` (provided by `qubes-menus`) and, as noted, `kf5-applications.menu` (provided by `kf5-service`, likely pulled in as a dependency on your systems when installing `dolphin`).

However, when _not_ using a DE, such as when running a WM like `i3`, this environment variable is not set to anything! I can't recall the exact manner the programs call each other, but I believe when you start Dolphin, it forks off a process running `kbuildsycoca5` in order to populate the MIME database. However, this process begins by trying to load in the Menu file - `/etc/xdg/menus/applications.menu` in this case, since the prefix is empty!

So the issue is not that `applications.menu` is missing (it should not be there!) but that the environment hasn't specified which of the multitude of specific menu files to use.

Because the file can't be found, the program then errors out before being able to enumerate the `.desktop` files it uses for creating the MIME database. The result is that KDE applications will not have access to any MIME database (or, if one had previously been created, say by starting up Dolphin in a DE in the past, the database will be out of date, never noticing if you install new programs or override file associations manually).

If I am not entirely misremembering, Nautilus uses a different mechanism for updating its database, with the result stored elsewhere, so Dolphin isn't able to piggyback off that either.

### Solution

The fix is easy, however. You just need to tell the environment what prefix to use. It doesn't matter too much which one you choose (whether it's Gnome or kf5, assuming a WM user won't care about whatever DE-specific differences there are in the menus).

My solution was to mimic the X11 configuration scripts [already present](https://github.com/QubesOS/qubes-gui-agent-linux/tree/main/appvm-scripts/etc/X11/xinit/xinitrc.d) in `qubes-gui-agent-linux` and put a script in `/etc/X11/xinit/xinitrc.d`, which is sourced by `Xsession` on startup of the VM:

```
$ cat /etc/X11/xinit/xinitrc.d/55-set-xdg-menu-prefix.sh
export XDG_MENU_PREFIX=kf5-
```
(again, note the hyphen at the end).

Note: This file will be sourced regardless of what session is started, but I believe that if you were to start a full DE session, it would overwrite this value with the one that is correct in that environment, without a problem.

Note that there is already an `xinitrc.d` file that does this (and more), namely `[/etc/X11/Xsession.d/60xfce-desktop](https://github.com/QubesOS/qubes-gui-agent-linux/blob/main/appvm-scripts/etc/X11/Xsession.d/60xfce-desktop)` (part of the `qubes-gui-agent-xfce` package). Thus, a fix could be to simply adapt that file and include it in a non-optional package (maybe `qubes-gui-agent`?), so that it is present even for WM users. Care must be taken to ensure that the prefix chosen corresponds to a `*-applications.menu` file which is also present on such a system.

**Comment by jamke** [comment]
@DemiMarie you assigned and un-sassigned yourself from this one.
Can you (or somebody) please verify that this issue is fixed? @Rudd-O maybe you can?

**Comment by jamke** [comment]
The problem is still in place in R4.2.4 with Fedora-41.-minimal (maybe full too?).

`Dolphin` being installed with all dependencies and still cannot open any file (e.g. txt file).

Pretty sure this is a major problem for all Qt/KDE users of Qubes OS. 
Fedora with KDE, obviously does not have this problem. 

Affects R4.2 (probably R4.3, as the problem is with templates). Please reopen?

**Comment by tasket** [comment]
Oddly enough, I've been using KDE-based templates perfectly fine for probably > 6 years.

What made it work for me was setting `export XDG_CURRENT_DESKTOP=KDE` in /etc/profile.d. I see that someone else also [mentioned](https://github.com/QubesOS/qubes-issues/issues/2968#issuecomment-354776210) this long ago.

Alas, this works until Debian 12, but not in the R4.3 Debian 13.  The above setting gets overridden somehow, and if I force it there is no effect.  This is my biggest speed bump thus far in moving to Qubes R4.3, and the only workaround I have is to restore my Debian 12 KDE template into the R4.3 system and update it with appropriately modified apt sources.  I've been using Debian 12 VMs for the time being, but will try the menu linking and setting XDG_MENU_PREFIX as suggested above to see if they work.

---

Update:
~~It didn't work on a fresh Debian 13 template.~~  However, an upgraded 12 -> 13 template does work with the above measures.   I noticed there are some extra files in /etc on the upgraded template which `dpkg` says are from 'residual-config' packages.  A `diff` between the contents of the two templates should reveal what is missing in the new template.

**Comment by tasket** [comment]
I was able to get KDE working in a fresh debian-13 template and have posted a guide here:

https://forum.qubes-os.org/t/installing-kde-in-a-debian-13-template/37324/1

Update:

I've added an extra step to address the missing file copy, move, pdf convert, etc. actions in Dolphin.  The transition to KDE 6 makes it necessary to update the .desktop files content and location.  You can find an updated guide for KDE service menus here:

https://develop.kde.org/docs/apps/dolphin/service-menus/
