### ISSUE TITLE
xfwm4 bug causing slow/hanging Qubes; xfce bug fix solution attached

### ISSUE THREAD

**Issue by MichaelAnders** [QubesOS/qubes-issues#7500]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
Running Qubes I sometimes notice a slow down in Window reaction. This is related to xfwm4 which shows a high CPU utilization in dom0 (max seen >75% on a 8 CPU system)
This forces me to reboot the system every few hours as else the system is not usable / my UX suffers significantly.
Worst case and I'm afk, Qubes hangs and I need to press the "Reset" button.

### Steps to reproduce
Not clear, it just happens "now and then", maybe related to the number of open windows.

### Expected behavior
The xfwm4 bug is resolved based on known fix.
Initial discussion where I found the solution and posted the commits on March 11th 2022: https://forum.qubes-os.org/t/fixing-known-bug-for-xfwm4-on-dom0/10109/2
Link to solution: https://gitlab.xfce.org/xfce/xfwm4/-/issues/351#note_13692

### Actual behavior
Qubes runs stable

**Comment by MichaelAnders** [comment]
I have a question...

Base on the status of the ticket:

- I understand that you will fix this bug.
- I understand that this will be available with 4.1 which will be released some day (looking at the milestone being roughly at 25%, this is many months away)


What I do not understand is what I can do to fix this? The root cause is known, applying the patch should be trivial on 4.0? And I do not like my system to crash (happens also with my new 5700G) as that could corrupt the file system and that is ugly - even if you have backups (which you might not be able to create as the system might die when you try), you don't want to have that right?

Normally, I'd have expected the following as this is not a "nice to have" issue but severe, data integrity endangering issue:

This is a simple-to-fix bug which affects one tiny part of Qubes. So imho it should be possible to do to the following without too much of effort:
- Patch the bug in github source code
- Compile the code
- Deliver the patch via dom0 update

That way, anyone who has the bug (selfish: me ;) ) won't continue to have the problem instead of now waiting till 4.1 comes around.

I'd complie Qubes myself, but I ran into issues with that and no, I don't want to learn how to do this either, thank you. I do work in IT but that does not mean I want to be able to do everything...

And I do not think that everyone affected should need to fix such a severe bug locally on their system - it should be distributed centrally (probably exchanging one single file).

Thanks!

**Comment by andrewdavidwong** [comment]
> I understand that this will be available with 4.1 which will be released some day (looking at the milestone being roughly at 25%, this is many months away)

Not exactly. Qubes 4.1 is already the current stable release that everyone should be using. The devs generally try to fix bugs in it as they can (depending on priority, capacity, etc.), so the percentage completion of the total milestone doesn't really indicate anything here. (Besides, there are always way more bugs than can ever be fixed, so it never reaches 100%.) So, yes, it *could* be months before this is fixed, but it *could* also be a lot sooner. (No guarantees either way.)

> The root cause is known, applying the patch should be trivial on 4.0?

[Qubes 4.0 reached EOL about a month ago](https://www.qubes-os.org/news/2022/08/04/qubes-4-0-has-reached-eol/) and is therefore no longer receiving updates.

> That way, anyone who has the bug (selfish: me ;) ) won't continue to have the problem instead of now waiting till 4.1 comes around.

[Qubes 4.1.0 was initially released back in February.](https://www.qubes-os.org/news/2022/02/04/qubes-4-1-0/) More recently, [Qubes 4.1.1 was released in July.](https://www.qubes-os.org/news/2022/07/18/qubes-4-1-1/)

It is critically important that you [upgrade your system (including templates and standalones) to avoid EOL](https://www.qubes-os.org/doc/how-to-update/#upgrading-to-avoid-eol). It sounds like you might still be on Qubes 4.0, in which case you should [upgrade to Qubes 4.1](https://www.qubes-os.org/doc/upgrade/4.1/) ASAP.

We announce when things reach EOL, so please keep up with our announcements to be notified in the future. We make sure to cast our announcement net far and wide, so there are *many* ways to stay informed:

- [News section of the Qubes Forum](https://forum.qubes-os.org/c/news/6)
- [News page on the Qubes website](https://www.qubes-os.org/news/)
- [RSS feed](https://www.qubes-os.org/feed.xml)
- [qubes-users mailing list](https://www.qubes-os.org/support/#qubes-users)
- [qubes-devel mailing list](https://www.qubes-os.org/support/#qubes-devel)
- Watching the [qubes-posts repo](https://github.com/QubesOS/qubes-posts) here on GitHub
- [Twitter](https://twitter.com/QubesOS)
- [Reddit](https://www.reddit.com/r/Qubes/)
- [Facebook](https://www.facebook.com/QubesOS)
- [LinkedIn](https://www.linkedin.com/company/qubes-os/)

You only have to use **one** of these in order to get all the important announcements!

There's also [qubes-announce](https://www.qubes-os.org/support/#qubes-announce), which is a very low-volume mailing list for critical Qubes-specific announcements only.

**Comment by MichaelAnders** [comment]
Sorry that you replied so much! I am actually on 4.1... typo / misunderstanding on my side (I expected the milestone to be a future release, e.g. 4.1.1 or 4.1.x, but not current 4.1.0) and didn't double check.

I didn't notice 4.1.1 being out unfortunately, guess I need to check qubes-announce as you wrote (thx!)

> So, yes, it could be months before this is fixed, but it could also be a lot sooner.

I understand all that - I also code for food, so I know what you are saying and your challenges, totally!

My question is (or I overlooked the answer): Why not give out small updates - like a patch - for this bug instead of waiting for months with mine and others system rebooting randomly? I do see dom0 updates time to time and I'd have assumed they belong there so could be "easily" updated?

Maybe it's a philosophy question: I usually try to give out improvements and functionality to customers when ready, and at some point a big update (SP) with everything in it while others prefer only bug fixing and then new stuff with the SP.

**Comment by rustybird** [comment]
https://github.com/QubesOS/qubes-desktop-linux-xfce4-xfwm4/pull/18#issuecomment-1238050681

**Comment by andrewdavidwong** [comment]
> Sorry that you replied so much! I am actually on 4.1... typo / misunderstanding on my side

No worries.

> (I expected the milestone to be a future release, e.g. 4.1.1 or 4.1.x, but not current 4.1.0) and didn't double check.

The milestone is "Release 4.1 **updates**," which is distinct from the (now closed) "Release 4.1" milestone. We always want to have a milestone for the *current* release, because the current release is the one that most needs bug fixes. (By contrast, past releases don't need bug releases because they're no longer supported, and future releases generally don't need as many bug fixes because they haven't been released yet.)

> I didn't notice 4.1.1 being out unfortunately, guess I need to check qubes-announce as you wrote (thx!)

Well, if you're already on 4.1, then you don't have to do anything except [update normally](https://www.qubes-os.org/doc/how-to-update/).

> My question is (or I overlooked the answer): Why not give out small updates - like a patch - for this bug instead of waiting for months with mine and others system rebooting randomly? I do see dom0 updates time to time and I'd have assumed they belong there so could be "easily" updated?

Looks like we got a good answer above from @rustybird about what happened in this case.

**Comment by verygreen** [comment]
I finally found this issue as the explanation why after a few days of uptime my Qubes box would get progressively less responsive to the point that a virtual desktop switch would take 5 seconds on day 20 or so.

I understand that the original fix is unsuitable due to problems it brings, but I wonder if it would be acceptable to take a page out of the old fvmw2 book and add a "restart xfwm2" menu item into some menu that would restart it clearing the leaked state? That way people would not need to hunt down how to do it (does not help there's not even a man page).
