### ISSUE TITLE
qubes-app-shutdown-idle option grayed out in Qube Manager settings

### ISSUE THREAD

**Issue by qwrd** [QubesOS/qubes-issues#7528]
### Qubes OS release
4.1

### Brief summary
I haven't found a bug report issued for this, but there seems to be an issue with the Debian 11 template. QubesOS provides a package/script called qubes-app-shutdown-idle to automatically shutdown idle qubes. Unfortunately it doesn't seem to be working in the Debian 11 template. When opening Qube manager and selecting a qube settings, a window will appear and in the "Basic" tab there is a checkbox that is greyed out: Shut down when idle (package qubes-app-shutdown-idle missing in the template)

I tried running the debian 11 template and apt install qubes-app-shutdown-idle, but that didn't seem to do anything. The "Shutdown when idle" checkbox remains greyed out even after several reboots. The shutdown idle script seems to be installed in the appvm's because files appear in /usr/lib/python3/dist-packages/qubesidle folder, but doesn't seem to be running (qubes-idle-watcher or any other process from the qubesidle folder aren't present in the process list).

### Steps to reproduce
- Install Qubes 4.1 and choose Debian 11 as the default template
- Open Qube manager and open the settings window for a debian-11 appvm
- In the "Basic" tab the "Shutdown when idle" checkbox will be disabled; complains that qubes-app-shutdown-idle is missing
- Run the debian 11 template and install qubes-app-shutdown-idle
- Reboot
- Go to Qube manager and open the settings window for a debian 11 appvm
- Notice again that the "Shutdown when idle" checkbox is still disabled

![idle-disabled](https://user-images.githubusercontent.com/22202985/170662506-4b9f63bf-643f-4862-bbb7-47bc57676bc0.jpg)

### Expected behavior
The qubes-app-shutdown-idle package should be installed as a part of the debian 11 template and the  "Shutdown when idle" checkbox should not be disabled.

### Actual behavior
The debian 11 template is missing the qubes-app-shutdown-idle package and installing it in the template doesn't seem to enable the checkbox to enable the idle shutdown script

### Relevant links
https://forum.qubes-os.org/t/qubes-app-shutdown-idle-script-not-working-debian-11/10260/4

**Comment by andrewdavidwong** [comment]
Perhaps there's also an associated dom0 package that is required.

**Comment by lubellier** [comment]
Shutdown-idle works for Debian 11 in Qubes-OS 4.1, I'm using it a lot. I checked my Qube Manager GUI, the checkbox isn't greyed.

@qwrd: try the below ideas

1. [Update dom0](https://www.qubes-os.org/doc/how-to-update/) [1]
2. Update the debian-11 template [2]
3. Activate the shutdown-idle service via the CLI [3]

Please report here if one of the above ideas solved your problem.

[1] My Qube Manager version is :

```
[user@dom0 ~]$ rpm -qf $(which qubes-qube-manager )
qubes-manager-4.1.23-1.fc32.noarch
```

[2] My shutdown-idle version in my debian-11 template is :

```
[user@dom0 ~]$ rpm -qf $(which qubes-qube-manager )
qubes-manager-4.1.23-1.fc32.noarch
```

[3] in a dom0 terminal, try the `sudo qvm-features chat service.shutdown-idle 1` command. If the *chat* VM was running, restart it. The default shutdown delay is 15mn, but you can change it by editing the below python file (example for 1mn) in your debian-11 template :

```
user@tpl-d11:~$ grep TIMEOUT /usr/lib/python3/dist-packages/qubesidle/idleness_monitor.py
# TIMEOUT_SECONDS = 15 * 60
TIMEOUT_SECONDS = 1 * 60

```

**Comment by qwrd** [comment]
Sorry for the late reply, but I have an update. The checkbox suddenly became active and available on my system. The only thing I did was installed a few packages like Thunar and GIMP in the debian 11 template, ran some updates and rebooted a few times. Now I can use the script on all available qubes via the Qube Manager.

unman: Hmm, thanks for the clarification.

**Comment by GrassfedMeatSticks** [comment]
I ran into this same issue myself (Qubes 4.1.2 R4.1; Debian 11; Kernel 6.1.35-1).

In the templateVM, I
- Installed the **qubes-app-shutdown-idle** package via `sudo apt install qubes-app-shutdown-idle -y --no-install-recommends`
- Modified `/lib/python3/dist-packages/qubesidle/idleness_monitor.py` to **TIMEOUT_SECONDS = 1 * 60** because this is probably where it is configured for all downstream AppVMs (and I didn't want to wait 15 minutes).

### However, the key was that from dom0 I added **supported-service.shutdown-idle** instead of the **~~service.shutdown-idle~~** mentioned in this thread: `qvm-feature <TEMPLATE VM NAME> supported-service.shutdown-idle 1`

I found this by staring and comparing the existing services enabled for the TemplateVM and noticed all of the other services with "service" in the name were prefixed with "**supported-**"

I removed the erroneously-created service by running the following from dom0: `qvm-feature --unset <TEMPLATE VM NAME> service.shutdown-idle 1`

Afterward, the error depicted in this thread was replaced with **Shutdown when idle for more than 15 minutes** (which is obviously statically configure and not derived from the TemplateVM's `/lib/python3/dist-packages/qubesidle/idleness_monitor.py` **TIMEOUT_SECONDS** setting.

As a bonus, I tested it by opening an App in an AppVM (with **Shutdown when idle for more than 15 minutes** checked) based on this TemplateVM and the AppVM shutdown shortly after closing the app.

Maybe this was obvious to everyone else, but it was a little challenging for me. I hope this helps.

**Comment by GrassfedMeatSticks** [comment]
Update: Maybe disregard my post. 

I found that checking the **Shut down when idle for more than 15 minutes** box on the Basic tab inserts **service.shutdown-idle** into the target VM's `qvm-features` listing alongside the **supported-service.shutdown-idle** entry I thought I discovered. Removing **supported-service.shutdown-idle** from the target VM's `qvm-features` does not seem to affect the availability of the **Shut down when idle for more than 15 minutes** checkbox or the functionality of the shut down when idle.

So, similar to @qwrd's findings, maybe it just takes a minute to update. I had done a lot of testing and reboots and really thought **supported-service.shutdown-idle** was the key.

**Comment by qwrd** [comment]
Umm, guys, I'm a bit embarrassed to ask, but I'm pulling out my hair again. Has anyone managed to figure out what the issue is here? I've just installed the **Debian 12** template and tried to enable the shutdown idle script by installing the qubes-app-shutdown-idle package via apt in the template shell, but the option in the Qube Manager remains greyed out again even after several reboots and updates. It works fine for all Debian 11 qubes.
