### ISSUE TITLE
rpmcanon: make error messages more appropriate

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7545]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Current error message of rpmcanon look rather scary and is anti-helpful in finding source of the issue. For example:
https://forum.qubes-os.org/t/error-canonicalizing-file-payload-forged-in-qvm-template-gui/8391
"Payload forged!" doesn't help the user at all. First - what is the "payload"? Second - it isn't "forged", it is incomplete/truncated (see download progress above).

### The solution you'd like

Modify error message to actually help finding the problem. In the case above, something like "file too short - incomplete download?". 

### The value to a user, and who that user might be

Easier troubleshooting.

**Comment by DemiMarie** [comment]
Sorry about that.  The payload is the part of the package that comes after the headers, but that is not obvious, and “Payload forged!” is a terrible error message.  Unfortunately, I am not sure of a way to distinguish a too-short file from a too-long one without decompressing the payload.  Perhaps something like, “RPM package corrupt - incomplete download?”.  That addresses by far the most likely cause of the problem, without scaring the user.

@pmatilai is there some other way to detect a truncated RPM package that I am not aware of?

**Comment by pmatilai** [comment]
You can calculate the expected file size using RPMSIGTAG_SIZE/RPMSIGTAG_LONGSIZE. Just beware that there may be (old) packages with buggy size calculation out there, at least rpm 4.12 and its pre-releases generated buggy sizes into binaries. 

I wouldn't bother though, just state the obvious fact (corrupt rpm) without drawing any conclusions.

**Comment by DemiMarie** [comment]
> You can calculate the expected file size using RPMSIGTAG_SIZE/RPMSIGTAG_LONGSIZE. Just beware that there may be (old) packages with buggy size calculation out there, at least rpm 4.12 and its pre-releases generated buggy sizes into binaries.

Thanks!  Is this the compressed or the uncompressed size?  If the latter, then I can also avoid zeroing it out in the output RPM, which would be nice.

> I wouldn't bother though, just state the obvious fact (corrupt rpm) without drawing any conclusions.

The reason I would like to make a distinction is that a truncated RPM is almost certainly due to a network problem, whereas an RPM that is corrupted in some other way likely has a different cause.  Not sure if that is worthwhile, though.

**Comment by pmatilai** [comment]
The size in those tags is the "physical size", whether compressed or not. Otherwise, you wouldn't be able to use it to calculate the rpm file size, right?

The size tags are totally unprotected in the signature header, and thus completely unreliable. If you create logic around them, the bad guys can trivially lead you to think a crafted rpm was just a download error, I don't think you'd want that.
