### ISSUE TITLE
New version of IT-Grundschutz Module for Qubes Client

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#7617]
### Qubes OS release (if applicable)
R4.1+

### Affected component(s) or functionality (if applicable)
Documentation

### Brief summary
Although Qubes is able to provide a high level of security, like with any other operating system this can be subverted by sufficient stupid usage. Installation, configuration, and usage may be done in such a way that the excellent features of the system are wrongly used or not used at all.

In order to help users set up a secure operating environment, the German Federal Office for Information Security (BSI, Bundesamt für Sicherheit in der Informsationstechnik) has defined an excellent standard covering most relevant issues, in a much more detailed way than is done in ISO 27001. The standard is called IT-Grundschutz (something like baseline security) and covers about 100 areas, called modules. In the area of operating systems, there are, among others, modules for Windows, Unix, and macOS.

As a module for Qubes OS could be helpful, I have provided such a module which is available from the BSI server. In order to reflect changes that occurred in the last two years, I have now updated this module, removed one threat that is no longer relevant, and added three more requirements describing options for the installation of more exotic software.

### Additional context
A draft version of the module is here:
[Qubes_GSC_Module_new_V1.pdf](https://github.com/QubesOS/qubes-issues/files/9110959/Qubes_GSC_Module_new_V1.pdf)
Any comments, corrections, and suggestions for improvement are highly welcome!
In a few weeks, the German version of the module will be published as a user module on the webserver of the BSI. If the BSI sees sufficient interest in this module, it can be promoted to be a part of the standard.

### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted
A lot of suitable parts of the documentation, which helped a lot in the construction of the module.

**Comment by andrewdavidwong** [comment]
Thanks for doing this! However, I'm not quite sure I understand the purpose of this issue. Do you wish to see some change occur in the official Qubes documentation?

**Comment by GWeck** [comment]
No, I don't think that any change in the existing docs is necessary, as they are already exceedingly good. I just brought up this issue for two purposes: to get some feedback on the new text and to make it (better) known that such a half-official recommendation on using Qubes somewhat more securely does exist at all.

**Comment by 51lieal** [comment]
You mention Client Applications of the IT-Grundschutz compendium in the doc, where can i read this ?

In the [QubesDevelopment] reference, you may want to use qubes-devel google group instead of qubes-issue link, or you can use this https://dev.qubes-os.org/en/latest/ as dev doc.

btw, this is great, quick explanation for everyone who want to learn qubes.

**Comment by andrewdavidwong** [comment]
> No, I don't think that any change in the existing docs is necessary, as they are already exceedingly good. I just brought up this issue for two purposes: to get some feedback on the new text and to make it (better) known that such a half-official recommendation on using Qubes somewhat more securely does exist at all.

I understand. While I don't wish to sound ungrateful or discouraging, I think these purposes might be better served on the forum and mailing lists rather than the issue tracker. Getting feedback is certainly useful, but since it is not part of the project's documentation or code, this isn't exactly an appropriate venue to do that. Spreading the word about this is also useful, but we don't use the issue tracker for that even when it comes to official matters. Thank you again for your diligent work on this and for promoting Qubes out in the world!

**Comment by GWeck** [comment]
@andrewdavidwong I put it now into the forum and hope for feedback - for the first version of the module, I got valuable input from @SvenSemmler and @brendanhoar. I hope I can improve this version accoringly!

Thank you for your understanding!
