### ISSUE TITLE
Mute audio from individual VMs

### ISSUE THREAD

**Issue by patranger** [QubesOS/qubes-issues#7651]
### The solution you'd like
It would be useful to be able to mute individual VMs so that, for example, 2 machines were muted and one was not.

**Comment by unman** [comment]
You can already do this.
The audio mixer allows you to mute individual streams, or set them to
different volumes.

**Comment by andrewdavidwong** [comment]
Closed as an "unsuitable proposal" (the proposed action is unsuitable, e.g., because it rests on a false assumption or misunderstanding, or because the thing it tries to fix is not really a problem in the first place). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
