### ISSUE TITLE
System boots with an inactive systemd-timesyncd.service

### ISSUE THREAD

**Issue by kennethrrosen** [QubesOS/qubes-issues#7712]
### Qubes OS release
4.1.1

### Brief summary
After each shutdown or reboot, system clock reverts to past dates

### Steps to reproduce
1. Boot computer or reboot
2. Login

### Expected behavior
Time set to desired timezone and accurate time

### Actual behavior
Time is months behind, though timezone remains correct. System boots with an inactive systemd-timesyncd.service.

**Comment by unman** [comment]
systecmd-timesyncd is disabled by design, because dom0 has no network connectivity.

Qubes does use a clockVM, configurable in Global Settings.
The ClockVM is used to get the time, and to sync it in dom0 and to other qubes.

The fact that your computer does not maintain the correct time is probably not Qubes related.
Often this is the sign of a faulty CMOS battery.

If you enter the BIOS you should be able to set the time and date there, but if your CMOS is broken the date will not be maintained.

**Comment by kennethrrosen** [comment]
Thank you. I'm not sure where the errors arose, but it seems to have resolved itself as the time and date have remained consistent. Apols.

**Comment by kennethrrosen** [comment]
After checking the CMOS battery, the clock continues to boot out of sync and out of date, months behind. Could this be something wrong with the ClockVM or dom0?
