### ISSUE TITLE
Windows Search not working in WIndowsVM based on Windows-10 template with moved user folder

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#7732]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1 with qubes-windows-tools.noarch  4.1.68-1 

### Brief summary
When click on windows serach in VM based on windows 10 template with moved user folder and installed QWT nothings happens, also can't write anything in that field.

### Steps to reproduce
Try to interact with windows search in Windows VM

### Expected behavior
You can search

### Actual behavior
Nothing happens

**Comment by Szewcson** [comment]
Notifications also not responding.

**Comment by Szewcson** [comment]
Also there is a problem with activation, since it looks like VMs are not activated while template is.

**Comment by Szewcson** [comment]
Ok, after creating new VM based on that template everything seems to work normal in that VM. But still I think it worth to look at this issue since some time ago I also have corrupted Windows WM after some time it works fine.

**Comment by andrewdavidwong** [comment]
> Also there is a problem with activation, since it looks like VMs are not activated while template is.

Please note that [every issue must be about a single, actionable thing.](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing) Please open a separate issue for this, if one does not already exist.

**Comment by aslfv** [comment]
I can confirm the issue: Search worked fine for both the Windows 10 TemplateVM and the related AppVM. But it suddenly stopped working in the AppVM as described by @Szewcson. Creating a new AppVM or restoring a backup of the AppVM "solves" the issue but then one runs into the license activation issue mentioned, which is a different issue indeed.

I am still not certain if this is a QubesOS specfic problem, given that the problem is known in Windows (https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/fix-problems-in-windows-search). But none of the solutions proposed there worked on the AppVM. So there could be something specific to the AppVM/QubesOS that prevents these solutions to apply properly.

That said, chances are high that this is caused by some corrupt files: The steps proposed in https://answers.microsoft.com/en-us/windows/forum/all/clearing-searchbar-history-crashes-searchhostexe/9baef86d-6d94-4422-a414-32866dc6dab8 helped me repair window search, in particular the following command to be run via Windows PowerShell with Admin rights:
`Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`

I do not what the command does, so please use at your own risk.

**Comment by Szewcson** [comment]
It is rather QWM bug so it would affects any next release if not fixed in QWM which I understand is still on hold.
