### ISSUE TITLE
re(4) and iwm(4) drivers not working for passed through devices in OpenBSD HVM

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#7765]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1.1

### Brief summary
Don't know if I should report it here or somewhere in Xen Project community. If there kindly please lead me to right place.

After installation of OpenBSD 7.1 as HVM according to @unman and @jcholsap guides xen NIC is working, but physical NICs (Intel Wireless AC-9560 and Realtek 8168 rev 0x15: RTL8168H/8111H) not. For Intel AC-9560 I installed iwm(4) firmware from downloaded package. I also upgraded all packages, fw and OS itself. By the advice of soemone from OpenBSD community I checked if I can run everything on physical machine, and yes when I installed OpenBSD on other HDD it boots and can connect to internet using re(4).
attaching dmesg (for only eth pass through since wifi causing OpenBSD panic) from OpenBSD mailing list:
https://marc.info/?l=openbsd-bugs&m=166318676430481&w=2

### Steps to reproduce
1.) create OpenBSD HVM
2.) passthrough the AC-9560 and Realtek 8168 to that HVM
3.) install OpenBSD 7.1 and fw for the wireless
4.) reboot and try to connect to the internet
4b.) if OpenBSD Panic, remove wifi pass through and try only with eth

### Expected behavior
You can use both NICs in OpenBSD like when it is installed on the host machine.

### Actual behavior
iwm causes OpenBSD Panic! with lots of errors like `iwm0: fw chunk addr 0x404000 len 712 failed to load`
re spamming with `re0: watchdog timeout` and not working

**Comment by Szewcson** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245392

this can be related.

**Comment by DemiMarie** [comment]
@Szewcson good catch!  Would you mind reporting this to the Xen and/or QEMU developers?  This could be a bug in the MMIO emulation logic there.

**Comment by marmarek** [comment]
I'm not sure if that's relevant, but a common cause is incorrect MSI / MSI-X detection/support by the driver. HVM in Qubes do not support MSI-X, but do support MSI. MSI-X, even if the device really supports it, is masked from PCI capabilities. Driver should fallback to MSI (or INTx) if MSI-X fails to setup (or isn't there at all), but many drivers have this path buggy, since it isn't exercised in most common (native) scenario.

**Comment by Szewcson** [comment]
@marmarek so should I still report it to Xen/QEMU or should I try to force it on OpenBSD list as a problem with driver? I remember that @unamn mentioned somewhere that intel fw is buggy (and from my experience even their windows drivers are buggy) and he not recommend using wifi on OpenBSD netvm, but in my case even eth (that should be more reliable in most cases) not working so I wiil want to report it in the right place and hoping that someday, someone will fix that.

**Comment by Szewcson** [comment]
Stefan Sperling answers me that:

> re(4) only uses MSI, it does not ever even try MSI-X. As can be seen here:
> https://github.com/openbsd/src/blob/master/sys/dev/pci/if_re_pci.c#L161
> 
> iwx(4) first tries MSI-X, then falls back on MSI:
> https://github.com/openbsd/src/blob/master/sys/dev/pci/if_iwx.c#L10573
> Your iwx firmare load failure looks like a DMA problem to me.

and about iwm(4) since there was mistake in my report about wirelles:

> At this low level the drivers are equivalent.

He also suggest that:

> Are you sure you applied all the necessary BIOS tweaks for PCI passthrough
> to actually work?

Are there any tweaks that I should add? In every guide there was nothing about it. Just create HVM as normal (with kernel to none).

**Comment by andrewdavidwong** [comment]
It sounds like the problem initially reported has turned out to be an upstream bug. Meanwhile, it appears that this issue may have morphed into a request for help or support with finding workarounds. If that is the case, then this is a friendly reminder that the issue tracker (`qubes-issues`) is not intended to serve as a help desk or tech support center. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!

Therefore, I'm tentatively closing this issue as "not our bug" (the Qubes OS Project does not develop the software that is causing this bug). However, if anyone believes this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

Related FAQ: [Why don’t you fix upstream bugs that affect Qubes OS?](https://www.qubes-os.org/faq/#why-dont-you-fix-upstream-bugs-that-affect-qubes-os)
