### ISSUE TITLE
Choose "spins"/"flavors" of Fedora and Debian with better sets of default apps for standard templates

### ISSUE THREAD

**Issue by Che15ea** [QubesOS/qubes-issues#7784]
Hello
It is quite hard to play videos and view photos smoothly on Debian, Fedora and Whonix VM systems. I suggest to use eog instead of ImageMagick and install vlc in all VMs by default. So we don't need to install different programs by ourselves and affect the software fingerprint of the vm.
Should I suggest Qubes to make the improve or the upstream system?

**Comment by andrewdavidwong** [comment]
There are a few different aspects here:

1. Preinstalling certain programs in Qubes templates by default probably falls under [FAQ: Could you please make my preference the default?](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default)
2. Anti-VM-fingerprinting probably falls under [FAQ: How does Qubes OS provide privacy?](https://www.qubes-os.org/faq/#how-does-qubes-os-provide-privacy) and [FAQ: What about privacy in non-Whonix qubes?](https://www.qubes-os.org/faq/#what-about-privacy-in-non-whonix-qubes) If so, it applies only to Whonix VMs (not to Fedora or plain Debian) and probably belongs on the Whonix issue tracker.
3. Preinstalling certain programs in upstream Whonix, Debian, or Fedora are indeed upstream requests that should be opened in their respective projects' issue trackers.

Since all three appear to have the same practical result of belonging in issue trackers other than this one, I'm going to tentatively close this issue. If anyone has reason to believe that this issue does indeed belong here and should be reopened, please leave a brief comment here explaining why, and we'll be happy to take another look. Thank you for your understanding.

**Comment by Che15ea** [comment]
Hi
Agree to disagree.
It is not possible to play videos in debian and fedora with the default setting. I think it is not a matter of preference but lacks of basic function.
The Image Magic program provides with terrible user experience. Please compare it with eog.
sorry to bother again

**Comment by Che15ea** [comment]
Hi
Agree to disagree.
It is not possible to play videos in debian and fedora with the default setting. I think it is not a matter of preference but lacks of basic function.
The Image Magic program provides with terrible user experience. Please compare it with eog.
sorry to bother again

**Comment by DemiMarie** [comment]
@marmarta what do you think?

**Comment by unman** [comment]
I don't understand the claim that it is quite hard to play videos and
view photos smoothly on Debian. It's trivially easy for anyone who wants
to do so.

Does eog provide the same features and facilities that Imagemagick does
that are used in Qubes?

**Comment by marmarta** [comment]
> I don't understand the claim that it is quite hard to play videos and view photos smoothly on Debian. It's trivially easy for anyone who wants to do so.

Trivially easy means "working comfortably out of the box" :) Having to do more than open the VM file manager and double click on a file, I think, an imperfect user experience. And as for ImageMagick, it is not comfortable for use, it's a very barebones tool, I have to agree that it's not easy to use for most people. 

If those things work the same in default debian/fedora (not sure here), then sadly yeah, this is a problem for their issue trackers, not ours.

**Comment by DemiMarie** [comment]
> If those things work the same in default debian/fedora (not sure here), then sadly yeah, this is a problem for their issue trackers, not ours.

I believe (again not sure) that Fedora Workstation includes both Eye of Gnome and VLC by default.  Qubes OS pulls in a smaller set of packages.

**Comment by Che15ea** [comment]
> > If those things work the same in default debian/fedora (not sure here), then sadly yeah, this is a problem for their issue trackers, not ours.
> 
> I believe (again not sure) that Fedora Workstation includes both Eye of Gnome and VLC by default. Qubes OS pulls in a smaller set of packages.

Fedora has EOG and Whonix WS has VLC. However, the image viewer in debian and whonix, and the video player in Fedora is barely usable while Debian does not have a video player. I think it doesn't increase the size to have EOG on all three and VLC on all three.
Maybe the developer has some consideration to maintain a variety of tools to make the attack surface less predictable, but I still feel it not good to provide some tools that are too terrible to use.

**Comment by Che15ea** [comment]
> I don't understand the claim that it is quite hard to play videos and view photos smoothly on Debian. It's trivially easy for anyone who wants to do so. Does eog provide the same features and facilities that Imagemagick does that are used in Qubes?

Installing an extra player? Not a difficult job for me, but it changes the software fingerprint.

**Comment by andrewdavidwong** [comment]
So, again, we have to distinguish between different things:

1. Default software in upstream distros (upstream Debian, Fedora, Whonix) --> belongs in their issue trackers
2. Default software in *official* Qubes *templates* (Debian and Fedora *Qubes templates*) --> belongs here

VM fingerprinting [is only a concern for Whonix VMs](https://www.qubes-os.org/faq/#what-about-privacy-in-non-whonix-qubes), so that probably belongs in the Whonix issue tracker, unless it's specific to Qubes-Whonix.

IMHO, it makes no sense for the comparatively tiny Qubes OS Project to try to make its Debian and Fedora templates more user-friendly than upstream Debian and Fedora when their respective projects already have hundreds or thousands of times more resources allocated to that goal. It would make more sense to improve those comparatively huge upstream distros so that Qubes can simply inherit those improvements.

**Comment by DemiMarie** [comment]
> IMHO, it makes no sense for the comparatively tiny Qubes OS Project to try to make its Debian and Fedora templates more user-friendly than upstream Debian and Fedora when their respective projects already have hundreds or thousands of times more resources allocated to that goal. It would make more sense to improve those comparatively huge upstream distros so that Qubes can simply inherit those improvements.

If I recall correctly, Fedora has both Eye of GNOME and VLC installed by default _in the workstation spin_.  Qubes OS, however, defaults to installing a different set of packages that includes neither Eye of GNOME nor VLC.

**Comment by unman** [comment]
For Debian, the basic install doesn't include any "image viewer", I
think.
Most users will install a Desktop version, I suppose, but I have no
evidence to support this.
The image viewer that is installed depends on the flavor that is chosen
- I have no idea how that breaks down.

In short , there is no standard install of Debian, and no standard
image viewer.
The only evidence available comes from popcon, (weak as that is):
eog is undoubtedly popular: installed in 26% of sample
This is better than ristretto (12%), gwenview(9%), and eom(6%) - the
default viewers with other DE.
By far the *most* popular though, is imagemagick(37%)

What to make of this? I don't know. But as always, things are never as
clear as one might think(hope?) they are.

The guide CANT be whether one has "to do more than open the VM file
manager and double click on a file", because that already works for
images, and there are MANY file types that require specific packages to
be installed.
Also, from my experience, users don't have any issue in installing a new
package, either to open new file types or provide functionality they
don't already have. (*From my experience*.)
Also, I cant recall the last time I saw a post how to install X in
Debian templates, or how to replace imagemagick. (But as I say,
I don't think that the forums are representative of Qubes users.)

Tbh I'm indifferent as to whether eog is installed or not. (It comes with
a large number of plugins that might be required, and I'm not clear
that it's actively maintained any more.)
I'm opposed to vlc being installed by default.

**Comment by marmarek** [comment]
For R4.2 we strongly consider using "xfce" spin of Fedora as default Fedora template. The one with gnome (standard "Fedora Workstation") has too many packages that are problematic on Qubes (either conflict with something, or simply don't work with our GUI agent).

**Comment by DemiMarie** [comment]
Is there a list of these packages?

**Comment by kalkin** [comment]
@DemiMarie I remember there was at least talk about removing tracker (the search indexing thingy) in some issue. I just remember this one thing, but there might be more applications listed in it. I can't find it currently, may be @andrewdavidwong knows which issue i mean?

**Comment by andrewdavidwong** [comment]
> @DemiMarie I remember there was at least talk about removing tracker (the search indexing thingy) in some issue. I just remember this one thing, but there might be more applications listed in it. I can't find it currently, may be @andrewdavidwong knows which issue i mean?

Doesn't ring a bell, and I wasn't able to find anything in a search, sorry.

**Comment by kalkin** [comment]
This https://github.com/QubesOS/qubes-issues/issues/7028

**Comment by kalkin** [comment]
Also have a look at the comment from @jevank https://github.com/QubesOS/qubes-issues/issues/7028#issuecomment-955695048

**Comment by marmarek** [comment]
Both Debian and Fedora templates in R4.2 are switched to xfce flavors.

**Comment by andrewdavidwong** [comment]
Related forum thread:

https://forum.qubes-os.org/t/default-pre-installed-template-flavor-considering-change-from-gnome-to-xfce/20269
