### ISSUE TITLE
Qubes should keep IP forwarding in VMs with the `provides network` (Net Qube) disabled by default

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#7801]
### Qubes OS release

R4.1

### Brief summary

When a VM is has option `provides network`, Qubes automatically enables IP forwarding.

### Steps to reproduce

Enable  `provides network` in QVMM.

`cat /proc/sys/net/ipv4/ip_forward`

### Expected behavior

`0` - IP forwarding disabled.

### Actual behavior

`1` - IP forwarding enabled.

### Rationale

Instructions to setup Qubes sys-vpn VMs as well as VPN packages are difficult for users to set up.

When following [these Qubes VPN instructions](https://github.com/Qubes-Community/Contents/blob/master/docs/configuration/vpn.md) and simply forgetting to edit `/rw/config/rc.local`, the setup does nothing. The user won't be using the VPN. That would result in a leak, in an unexpected connection over clearnet that was expected to be routed over the VPN.

Also `/rw/config/rc.local` does not seem to be a safe mechanism to configure such scripts as networking might be up and functional before any scripts run from `/rw/config/rc.local` (firewall, vpn) have completed. Meanwhile, there could be leaks.

To avoid leaks, it would be much safer if IP forwarding was disabled by default. Then how could users use some specific things that require it? In these cases, for example in case of above linked instructions, it would be up the these instructions / the scripts to enable IP forwarding should that be required. That documentation / scripts should do so after the firewall has been load.

### Impact on Qubes-Whonix

This is primarily a general Qubes bug report. I.e. unspecific to Whonix.

The impact on Whonix is currently very little because Whonix explicitly ships a config that disabled IP forwarding as well as systemcheck checks if IP forwarding is disabled and would show a warning if it was accidentally enabled. However for defense in depth, it would be much better if Qubes would stick with Linux's default, which is to have IP forwarding disabled by default.

**Comment by marmarek** [comment]
> ### Expected behavior
> 
> `0` - IP forwarding disabled.

No, that isn't expected behavior. With IP forwarding disabled, qube  would not "provide network", unless extra non-obvious steps are made.

The thing you describe sounds more like https://github.com/tasket/Qubes-vpn-support that it doesn't set appropriate dependencies (to setup things before enabling ip forwarding). IP forwarding is enabled by `qubes-network.service`, so VPN can order itself before (maybe even with `Requires` type of dependency, but there are other ways for fail-closed too).

**Comment by tasket** [comment]
@marmarek @adrelanos I recall asking about this long ago, as I didn't want networking active until the firewall rules were set.  I think we should find this discussion and refer back to it.  As it is, my test from a /rw/config/qubes-firewall.d script shows forwarding is 'off'.

I think the original idea was that the service running the firewall scripts completes startup before networking (or at least forwarding) is enabled.

Also the Qubes-vpn-support _startup_ process would be an incorrect reference point, as it only starts the vpn service itself.  The installer sets up a qubes-firewall.d script which I think is the real locus of this security question.

**Comment by tasket** [comment]
> I think the original idea was that the service running the firewall scripts completes

To be clear:  This refers strictly to _Qubes_ services completing the the correct order.

**Comment by tasket** [comment]
For reference, refer to _qubes-firewall.service_ which has dependency `Before=qubes-network.service` and runs the code in '/lib/python3/dist-packages/qubesagent/firewall.py'.  Within `main()` the two firewall execution handlers are called synchronously before sending a 'READY' signal to systemd.

**Comment by andrewdavidwong** [comment]
This issue has been closed as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by adrelanos** [comment]
Ok, so `provides network` is supposed to enable IP forwarding. But can we reopen this ticket as a general ticket to handle the potential IP leak as well as reviewing Qubes documentation to avoid the IP leak danger?

Where's the code for `provides network`?

Then perhaps `provides network` should be renamed to something more technical such as `enable IP forwarding` or something better. The intention is to express for the user to not enable it without knowing what one is doing. Documentation and info tooltip could make clear that this is required for sys-firewall but that ProxyVM alike VMs shouldn't use it. (Because these should enable IP forwarding as part of their scripts.)

**Comment by unman** [comment]
imo we don't want to replace `provides network` with
something more technical - it's surely intended to cover cases *without*
technical requirements.
Why is it necessary to force " ProxyVM alike VMs" (what?) to enable forwarding by some
extra script?

**Comment by marmarek** [comment]
> Because these should enable IP forwarding as part of their scripts.

I don't like this approach. Having IP forwarding enabled at different stages depending on what kind of scripts you use is asking for all kind of issues. Now I guess we discuss a case where you'd like to enable IP forwarding later, but then it become problematic for things that want to be ordered _after_ enabling it. And also, having user-facing option that results in broken configuration by default (allowing something to be a proxy vm without actually forwarding traffic) is a bad design.
There is already a place to insert customization before enabling IP forwarding. If you need firewall rules preventing some kind of traffic being forwarded (like, outside of VPN), insert those rules at that point.

**Comment by adrelanos** [comment]
Currently the process of setting up a sys-vpn is as follows.

1) Open up the documentation in some VM with a browser
2) Create a sys-vpn VM using QVMM.
3) Check "provides network" in QVMM.
4) Perform some manual setup steps to set up the VPN or use something like qubes-vpn-support.
5) Configure other VMs to use sys-vpn.
6) Testing (hopefully).
7) Done.

The problem with this approach is, if something goes wrong in step 4, something as simple as not editing `/rw/config/rc.local` then sys-vpn will happily forward traffic over clearnet and thereby produce a leak. This recently happened to a user I was providing support for.

My suggestion is that step 4 (either manual instructions include enabling IP forwarding because it's part of the script there or that qubes-vpn-support does it) would replace the need for checkbox "provides network".

Asking this another way... What's the purpose for a user of checking the box "provides network" and then not following instructions how to set up a tunnel (such as VPN) and not using something like for example qubes-vpn support? Why would one setup a VM that with "provides network" but then not doing some custom setup in that VM? Maybe a very advanced user that does traffic analysis of their own traffic?

> " ProxyVM alike VMs" (what?)

Terminology isn't great yet indeed. Open for suggestions. What I mean...

ProxyVM alike VMs:

* VMs that route traffic through VPNs (sys-vpn)
* VMs the route traffic through Tor (sys-whonix)
* potentially others such as sys-proxy, sys-ssh, etc.

Other VMs with networking (where there is no risk for IP leaks):

* sys-net

> some extra script?

Extra script makes it sounds rather complex. Enabling IP forwarding would just a single additional line for example for qubes-vpn-support inside an already existing script.

> And also, having user-facing option that results in broken configuration by default (allowing something to be a proxy vm without actually forwarding traffic) is a bad design.

If the proxy VM is set up the wrong way (forget an essential step such as editing `/rw/config/rc.local`) then it should result in a broken configuration, i.e. failing closed and avoiding an IP leak over clearnet.

When you google "qubes vpn" then [this](https://github.com/Qubes-Community/Contents/blob/master/docs/configuration/vpn.md) is a top search result. Due to the lengthy size of the instructions, the many different options would could choose, typos and so forth, it is very difficult for many non-technical users to follow these instructions. Overlooking / forgetting a step such as editing `/rw/config/rc.local` shouldn't result in a leak. How could such a fail-safe design be accomplished?

To improve the linked documentation, two changes might suffice:

* 1) remove `choose "provides network",`
* 2) add `sysctl -w net.ipv4.ip_forward=1` after the firewall rules to script `/rw/config/qubes-firewall-user-script` (if required. Untested.)

**Comment by marmarek** [comment]
> What's the purpose for a user of checking the box "provides network" and then not following instructions how to set up a tunnel (such as VPN) and not using something like for example qubes-vpn support

Tons of standard use cases, starting from creating another sys-net (for example to separate wired from wireless interfaces), another sys-firewall (to isolate group of VMs from others, but possibly allow traffic between them), etc.

> Extra script makes it sounds rather complex.

Exactly. Any instruction that relies on user manually editing some scripts for critical operations will fail at some point. Not enabling IP forwarding by default doesn't really help, it just makes different errors critical. The solution to this issue is not adding extra steps for those custom scripts, but to not require user handling them manually at all.

And IIUC https://github.com/tasket/Qubes-vpn-support does exactly that. It provides a single-step installation (to be run either from the qube itself, or from its template), that setup required scripts in appropriate locations, including loading firewall rules _before_ IP forwarding is enabled. If it loads firewall too late (which I think is _not_ the case), then it's an issue to fix in that repo, not here.
There is also https://github.com/QubesOS-contrib/qubes-tunnel, that can even be installed as a pre-built package from contrib repository (to even skip the `git clone`/"download zip" step).
I user enables "provides network", but then does _nothing_ else, I don't see how is that a Qubes error that it didn't magically read user's mind that they intended to use VPN there.

> 1. remove `choose "provides network",`

Please note "provides network" does way more than just enabling IP forwarding. It allows the qube to be chosen as netvm for others, it enables configuring vif* interfaces, enables DNS forwarding, and few more.

If we want more foolproof VPN setup, I think we can try to integrate "qubes-tunnel" (or similar) tighter. Specifically, instead of "In sys-vpn settings Services tab, add qubes-tunnel service." step in qubes-tunnel, have a checkbox for it that gets enabled only when qubes-tunnel is indeed installed. We have an infrastructure for that ("shutdown-idle" service has similar checkbox, and when it isn't installed, it's grayed-out, instructing user to first install relevant package).

**Comment by tasket** [comment]
Two separate issues here:

1. Does Qubes start the firewall service + interfaces in the right order so as to prevent momentary leaks? (I think it does.)

2. Has the user checked for feedback from their installation process, and are we prompting them to look for the right thing?

> then sys-vpn will happily forward traffic over clearnet and thereby produce a leak.

For this to happen with either qubes-tunnel or Qubes-vpn-support the vpn vm has to be non-configured such that neither the firewall script is installed, nor does the qubes-vpn-handler.service attempt to start; running the installer in the wrong vm can cause it, or forgetting to run it at all.  I'm reluctant to say a project (an OS, even) should be modified because a single user didn't look for signs that a newly added package is running.

Currently if a user sees _any_ of the vpn popups (such as "Ready to start link") then fw has been checked because its the first thing the service does:
```
ExecStartPre=/usr/lib/qubes/qubes-vpn-setup --check-firewall
```

The only conditions for this check to run are: Not a template vm, the service is enabled and /rw/config/vpn exists.  If _Qubes-vpn-support_ was installed in appvm (not template) then rc.local must work as well, but this is automatically installed without user editing; rc.local concerns don't apply for _qubes-tunnel_.

Possible enhancement:  The install script could run the fw check at the end of the install process and report success/fail (or if it had to be _skipped_ in the case where its run in the template vm).  _That tells the user if the firewall script is installed correctly and _... that is what they have to worry about.  It they are expected to worry about "did fw script run THIS TIME" then you're talking about providing runtime visual feedback of the sort that the vpn script already does.  However this could be improved by attempting to show a popup notification when the service itself fails for any reason (instead of only the specific reason the client failed to connect).

> We have an infrastructure for that ("shutdown-idle" service has similar checkbox, and when it isn't installed, it's grayed-out, instructing user to first install relevant package).

This would enhance the install-process feedback for the user, although not directly regarding the firewall's configuration status.  A stronger integration that addresses Patrick's concern directly would be to have _qubes-firewall.service_ check whether qubes-tunnel or similar is enabled and add the basic fail-closed rules internally (repeat for ipv6)...

```
:FORWARD DROP
-I FORWARD -o eth0 -j DROP
-I FORWARD -i eth0 -j DROP
```

This has the added benefit of other vpn setups such as NetworkManager possibly using it as well.
