### ISSUE TITLE
qvm-appmenus --update does not fix missing .desktop entry in menu

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#7846]
### Qubes OS release
r4.1

### Brief summary
For some reason (i.e. I forgot what happened but probably some debugging) I ended up with VM that had 'org.gnome.Nautilus.desktop' in its `menu_items` feature, had the .desktop file in `.local/share/qubes-appmenus/vmname`, but not in the `.local/share/applications` directory, which resulted in the following:
- qube settings thinks the qube has Nautilus in the menu
- qvm-features agrees
- qvm-appmenus agrees 
- Nautilus is not actually in the menu

Running qvm-appmenus --update did not fix the problem, but I think it should. What helped was removing and adding Nautilus to the menu in app settings.

**Comment by alimirjamali** [comment]
It appears that qvm-appmenus removes the the unnecessary orphaned .desktop files but does not update VMs `menu-items` feature. I accept this issue and will work on it.

**Comment by marmarek** [comment]
TBH, I'm not sure if it really should remove entry from `menu-items`. Imagine if you switch your AppVM between templates back and forth, and some applications are named differently (or some are installed some not). If appmenus update would remove stale entries from `menu-items`, you'd need to re-add them after each switch.
This can easily happen for example if you switch to a newer fedora template version, before you install your preferred packages. If you do it in order first switch template and then install extra packages, all your extra apps will be gone from the menu. A more proper way would be first installing packages and then switching template, but IMO doing it the opposite order shouldn't destroy your menu...

An orphaned entry in `menu-items` feature should be harmless (if it isn't, that is an issue). What might be helpful is to add a button in qube settings to remove all orphaned entries.

-----
Now, stepping back a bit, I'm not sure if your diagnosis is correct here. The original issue description says "qube settings thinks the qube has Nautilus in the menu", which does not sound like an orphaned entry. If it would be, it would be marked as "Application missing in template! (org.gnome.Nautilus.desktop)". Since the issue is quite old, it's worth checking when marking orphaned entries was added (it wasn't always this way).

**Comment by marmarta** [comment]
yeah, especially as a lot of people will switch templates, realize that they have some missing programs, then go on to install them. It is too easy to lose something with removing the `menu-items` entry, I agree with @marmarek here.

**Comment by alimirjamali** [comment]
I also agree. I was thinking about the exact issue last night when I was working on it.
