### ISSUE TITLE
Qubes users are uniquely identifiable using firefox-esr in any AppVm

### ISSUE THREAD

**Issue by Garbage4F** [QubesOS/qubes-issues#7864]
### The problem you're addressing (if any)

Advertisers and other actors are able to distinguish Qubes users from all others, if they're using any javascript enabled browser by enumerating the media devices which are named uniquely to Qubes. I'm testing fingerprinting on https://amIunique.org

![AmIUnique](https://user-images.githubusercontent.com/116168942/200114990-dd69bd59-7c6b-43b4-be57-dd04b92badda.jpg)

### The solution you'd like

Default pulseaudio device naming that emulates common sound input + output names 

### The value to a user, and who that user might be

The ability to remain anonymous amongst other firefox users

Note: there are other unique factors uniquely identifying Firefox users (eg. Webgl, Canvas) but there're solutions to prevent that (Canvas Blocker or App Armor profiles). 

Current workarounds: 
* disable sound 
* disable or whitelist sites that may use Javascript

Both of which limit usability, attract increased "human verification" through captchas etc, and also make the browser statistically distinct.

**Comment by 3hhh** [comment]
This is specific to Firefox, not specific to Qubes OS.

Use `privacy.resistFingerprinting = True`, if you want to prevent it. [1]

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1372073

**Comment by Garbage4F** [comment]
In my tests, this particular issue looks **Qubes specfic.**

"resistFingerprinting = true" makes things worse if anything (see screenshot) - the reason I think this a Qubes issue is because an identical install of Debian + XFCE + Firefox 102 ESR outside of Qubes is not unique via media
 device name.

![AmIUnique1](https://user-images.githubusercontent.com/116168942/200134936-535e0d8d-8e9c-4ac3-ac6b-18d2128bacd0.jpg)

**Comment by andrewdavidwong** [comment]
[Qubes OS does not aim to provide any anti-fingerprinting features in non-Whonix qubes.](https://www.qubes-os.org/faq/#what-about-privacy-in-non-whonix-qubes)

-----

Closing as an "unsuitable proposal" (the proposed action is unsuitable, e.g., because it rests on a false assumption or misunderstanding, such as a proposed enhancement designed to fix something that is not really a problem in the first place). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by Garbage4F** [comment]
> [Qubes OS does not aim to provide any anti-fingerprinting features in non-Whonix qubes.](https://www.qubes-os.org/faq/#what-about-privacy-in-non-whonix-qubes)
> 
> Closing as an "unsuitable proposal" (the proposed action is unsuitable, e.g., because it rests on a false assumption or misunderstanding, such as a proposed enhancement designed to fix something that is not really a problem in the first place). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

To quote the page you linked

> For example, a standard [Fedora](https://www.qubes-os.org/doc/templates/fedora/) qube is expected to have basically the same privacy properties as that upstream Fedora distribution, enhanced to some degree by the control Qubes provides over that qube. For most users, this level of privacy may be good enough for many common activities. However, users seeking more advanced privacy features should use Whonix qubes.

This behavior I described is distinct to Qubes appvm guests, upstream Debian users are not uniquely distinct. This has direct security impacts for Qubes users, if you were looking to deliver a malicious payload to Qubes users or a Qubes user in specific, you now have a means of **identifying specifically users of AppVms on Qubes**. Left as is this seems to put Qubes users at increased levels of risks they would not experience if they had just installed the vanilla upstream OS on their hardware, with Qubes not enhancing its baseline security - but actively detracting from it.

Am I misunderstanding something?

**Comment by unman** [comment]
You seem to think this is the only way to identify Qubes users using
stock browsers with JavaScript.
It isn't.
Can you tell me what you think the Qubes unique entry is in your case?

**Comment by 3hhh** [comment]
Please report it to upstream Firefox, if `privacy.resistFingerprinting = True` doesn't work as it should.

**Comment by Garbage4F** [comment]
> You seem to think this is the only way to identify Qubes users using stock browsers with JavaScript. It isn't. Can you tell me what you think the Qubes unique entry is in your case?

My hypothesis was that mediaDevice.label was distinct in Qubes users compared to non-Qubes users, and that was *a* way (not the only way) to ID a Qubes user. However I am wrong in that regard; you need to have granted specific permission to the site for that to work. A test with blank FF profiles +  Debian 11 behaved identically with and without Qubes. I'll be quiet now.

**Comment by unman** [comment]
Thank you for your initial report, the follow up work that you did, and
the graceful way you dealt with it.
I could wish that more users were like you.

**Comment by andrewdavidwong** [comment]
> > [Qubes OS does not aim to provide any anti-fingerprinting features in non-Whonix qubes.](https://www.qubes-os.org/faq/#what-about-privacy-in-non-whonix-qubes)
> > Closing as an "unsuitable proposal" (the proposed action is unsuitable, e.g., because it rests on a false assumption or misunderstanding, such as a proposed enhancement designed to fix something that is not really a problem in the first place). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
> 
> To quote the page you linked
> 
> > For example, a standard [Fedora](https://www.qubes-os.org/doc/templates/fedora/) qube is expected to have basically the same privacy properties as that upstream Fedora distribution, enhanced to some degree by the control Qubes provides over that qube. For most users, this level of privacy may be good enough for many common activities. However, users seeking more advanced privacy features should use Whonix qubes.
> 
> This behavior I described is distinct to Qubes appvm guests, upstream Debian users are not uniquely distinct. Guest AppVms do not have the same privacy properties as the upstream distro.

It sounds like you're interpreting the quoted statement to mean that we explicitly aim to guarantee that Qubes VMs will have at least the same privacy properties as their upstream distros, but that's not what it says, and it's clear from context that we are *not* aiming to achieve that. In particular, the immediately preceding sentences, which you omitted, state: "Qubes OS does not claim to provide special privacy (as opposed to security) properties in non-Whonix qubes. This includes disposables."

Although I stand by the accuracy of the paragraph you quoted, I can see how it might be prone to misinterpretation. Since it's not really necessary to that FAQ entry anyway, I'll remove it in order to avoid such misunderstandings in the future.

> This has a direct impact for Qubes users: if you were looking to deliver a malicious payload to Qubes users, or a Qubes user in specific -- this is a means of **identifying specifically users of AppVms on Qubes**. Left as is this seems to put Qubes users at increased levels of risk, risk they would not experience if they had just installed the vanilla upstream OS on their hardware. In this instance, Qubes is not enhancing upstream's baseline security - but actively detracting from it.

This is fallacious reasoning. Your argument is that, because Qubes allows itself to be identified as Qubes, it's less secure than non-security-oriented upstream distros like Fedora. This is like arguing that because a bank advertises itself as a bank, it's a less secure place to store money than, say, your mattress at home. But that doesn't follow, because banks have a lot of security features that mattresses don't (vaults with big locks, armed guards, etc.). Likewise, Qubes OS has a lot of security features that regular distros don't (security-by-compartmentalization via Xen virtualization supported by special hardware features, secure template system, secure copy/paste and file copy/move system, network hardware and software stack isolation, sys-usb, etc.).

You say that a regular upstream distro would put users at less risk than Qubes because Qubes allows itself to be identified as Qubes. But this completely ignores the fact that regular distros also allows themselves to be identified simply by checking `cat /etc/issue` or `cat /etc/os-release`. You seem to be implying that Qubes is more of a target than a regular distro and hence that users would be more secure by sticking with a regular distro instead of Qubes, but of course this is simply [security through obscurity](https://en.wikipedia.org/wiki/Security_through_obscurity).

You claim that Qubes is "actively detracting" from upstream distros' security. Let's think about whether that claim makes sense. Qubes securely compartmentalizes each instance of an upstream distro that runs inside of it. Even if an attacker can identify that something is "Fedora running inside of a Qubes VM," for example, this doesn't make it an easier target for the attacker than a regular, bare-metal Fedora installation. In the Qubes case, the attacker has to compromise both Fedora *and* try to find a Xen hypervisor escape or some other way to attack other VMs. In the bare-metal Fedora case, the attacker *only* has to compromise Fedora. So, the Qubes case is strictly harder. How exactly is this "actively detracting" from security?

**Comment by andrewdavidwong** [comment]
> You say that a regular upstream distro would put users at less risk than Qubes because Qubes allows itself to be identified as Qubes. But this completely ignores the fact that regular distros also allow themselves to be identified simply by checking `cat /etc/issue` or `cat /etc/os-release`. You seem to be implying that Qubes is more of a target than a regular distro and hence that users would be more secure by sticking with a regular distro instead of Qubes, but of course this is simply [security through obscurity](https://en.wikipedia.org/wiki/Security_through_obscurity).

This is also related to [Kerckhoffs's principle](https://en.wikipedia.org/wiki/Kerckhoffs%27s_principle), the idea that a secure system should be designed under the assumption that the adversary knows all the details of the system. In the case of Qubes, this means that "the attacker doesn't know that this is a Qubes VM" would *not* be a legitimate security assumption. This doesn't mean that we have to blatantly advertise Qubes from inside of VMs as a matter of principle. It just means that trying to keep this information secret from an adversary is not a relevant aspect of proper security design for Qubes as a whole. This is a notable case where security and privacy can come apart, and it's why Qubes OS is primarily a *security*-oriented operating system that relies on its integration with Whonix to provide strong privacy properties.
