### ISSUE TITLE
System halts on suspend and becomes unresponsive after last upgrade

### ISSUE THREAD

**Issue by gangamstyle** [QubesOS/qubes-issues#7904]
### Qubes OS release
4.1.1

### Brief summary
Qubes OS upgrades installed in November added so many bugs that I keep reporting and reporting and reporting.
This bug broke my everyday experience.

I was using Qubes OS for over a year without problems. Now this problem appeared:
If I connect laptop with Qubes OS to external monitor (Type-C connector) and start Suspend process, monitor will turn off as expected, but laptop does not enter suspend state, system does not respond to key presses, does not resume, laptop becomes very hot (CPU 100% ?), power led blinks every second. Only pressing power button for 4+ seconds helps to power off and reboot laptop completely.
Everything worked before this system upgrades, something has broke it.

### Steps to reproduce
Install November updates ?

### Expected behavior
Laptop should enter suspend mode and resume on key press.

**Comment by logoerthiner1** [comment]
Seems similar to #7340 . You may consider looking at how I managed to get the relevant debug information.

Try grabbing logs appears after you suspends the machine via `journalctl` in dom0 on second reboot. However you may be unfortunate as me that the log after suspending does not flush to the hard disk. When you are in a scenario that you need the log desperately, try using xen xhci debug port if you have a USB 3 port. See https://github.com/QubesOS/qubes-issues/issues/6834#issuecomment-1296221396 and maybe https://forum.qubes-os.org/t/what-you-may-need-to-pay-attention-to-when-you-are-debugging-xen-dom0-on-usb-3-0-cable/14715

You can try older or newer xen-hypervisor versions (you mentioned that older xen version used to work; the testing version xen 4.14.5-14 fixes a bug that sometimes does exactly what you have mentioned (#7340) but occasionally) to check out whether the problem lies in xen version; if you are lucky the newer xen-hypervisor solves exactly your problem. You can put the xen hypervisor rom into `/boot` in dom0 with different filenames (xen-4.14.5-5.gz, xen-4.14.5-14.gz, for example) and `sudo grub2-mkconfig -o /boot/efi/EFI/qubes/grub.cfg` to make them appear in grub menu.

You can switch kernel version easily on grub boot menu.

This will help find out whether your issue is related to xen version or dom0 kernel version.

**Comment by gangamstyle** [comment]
@logoerthiner1 sorry I am not very familiar with that kind of debugging.
Update: this issue is not related to external monitor, suspend process fails on normal use. I I can't do anything with it, this happens every day and makes OS unusable. Moving back to Ubuntu until fixed.
Same problem: https://github.com/QubesOS/qubes-issues/issues/7910

**Comment by DemiMarie** [comment]
@gangamstyle no, from the Qubes repositories.  The idea is to figure out which update broke things, which is often a first step to fixing the problem.

**Comment by isodude** [comment]
What hardware are you running?

**Comment by gangamstyle** [comment]
@isodude Lenovo X1 laptop
UPDATE: xen 4.14.5-14 fixed this for me

**Comment by isodude** [comment]
@gangamstyle so we can close the issue?

**Comment by andrewdavidwong** [comment]
Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
