### ISSUE TITLE
Qubes default partition scheme doesn't reflect 4.1

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#7915]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release (if applicable)
4.1

### Brief summary

https://www.qubes-os.org/doc/custom-install/#installer-defaults

Dom0 is now separated and 20gb by default.

**Comment by andrewdavidwong** [comment]
In case you (or any others reading this) are not already aware, the documentation is a community effort, and everyone is welcome to contribute. (That's how things like this get updated!) So, if you'd like to get involved with the project, this is a great way to do it. You can read more about how to submit documentation changes here:

https://www.qubes-os.org/doc/how-to-edit-the-documentation/

You may also be interested in the documentation style guide:

https://www.qubes-os.org/doc/documentation-style-guide/

**Comment by andrewdavidwong** [comment]
The "custom installation" page was severely out-of-date and had remained so for an extended period of time, with no one able or willing to update it. The outdated content has proven misleading or unhelpful to many users. Since we have nothing with which to replace the outdated content, removing it seems like the lesser of two evils. (Note that the content is still available via Git history and other archives for historical reasons and for any users still on EOL releases.) If anyone is able and willing to contribute the relevant knowledge and/or text for customizing the installation of a supported Qubes release, we can bring this page back in the future. Since the page no longer exists, this issue is no longer applicable and is therefore being closed as "won't fix."
