### ISSUE TITLE
Coordinate release of Whonix for R4.2

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7931]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release (if applicable)

4.2

### Brief summary

This is place to coordinate release of Whonix for Qubes R4.2 with @adrelanos

I'll be doing some test template builds, but those aren't meant to be final.

Generally, I don't expect any compatibility issues, but that needs to be tested.

**Comment by adrelanos** [comment]
Please let me know when signed Qubes R4.2 releases are available. Once available, I could look into Qubes-Whonix testing.

**Comment by andrewdavidwong** [comment]
@adrelanos: Just letting you know that [Qubes OS 4.2.0-rc1 is now available for testing](https://www.qubes-os.org/news/2023/06/02/qubes-os-4-2-0-rc1-available-for-testing/).

**Comment by adrelanos** [comment]
Quote myself from https://github.com/QubesOS/qubes-issues/issues/7134#issuecomment-1587510853

> This is blocking the release of Whonix 17 (based on Debian `bookworm`).

When is Qubes Debian bookworm expected?

May I suggest we skip the release Qubes-Whonix 17 for Qubes 4.1?

Qubes-Whonix 17 would be released for Qubes 4.2 only.

**Comment by marmarek** [comment]
> May I suggest we skip the release Qubes-Whonix 17 for Qubes 4.1?

Fine with me as long as Qubes-Whonix 16 would be supported until EOL of Qubes 4.1 (6 months after final release of R4.2).

> When is Qubes Debian bookworm expected?

Testing template in R4.1 repositories is available for a month already. There will be one in R4.2 testing repos this week, and since bookworm is officially released now, I'll expected the template to be moved to stable not long after (unless some severe issues are detected, ofc).

**Comment by adrelanos** [comment]
* https://github.com/QubesOS/qubes-issues/issues/8279 is an issue for Qubes-Whonix 17, because internally used by tb-updater in Template.

**Comment by adrelanos** [comment]
* https://github.com/QubesOS/qubes-issues/issues/1778#issuecomment-1604084319

**Comment by marmarek** [comment]
I tried a local test build of Whonix 17 (bookworm based) and it fails on missing `salt-ssh`, which is know, rather sad, development. We dropped the dependency in bookworm template (until upstream Debian starts supporting it again), but Whonix needs an adjustment too:

- https://github.com/Whonix/qubes-whonix/pull/1

**Comment by marmarek** [comment]
The build failed, I see this in the log:
```
2023-06-28 14:22:32.816689 +0000 build-fedora42: output: + echo 'deb [signed-by=/usr/share/keyrings/derivative.asc] https://deb.kicksecure.com bullseye-testers main'
2023-06-28 14:22:32.816777 +0000 build-fedora42: output: + echo 'deb [signed-by=/usr/share/keyrings/derivative.asc] https://deb.whonix.org bullseye-testers main'
```

Maybe it didn't updated template-whonix repo to new version. I'm doing test build locally now and will let you know.

**Comment by marmarek** [comment]
Local build worked now, I'll (re)start public one.

**Comment by marmarek** [comment]
Not sure if you are watching update-status repo, but the build succeeded this time.

**Comment by adrelanos** [comment]
Next steps, please correct me if I am wrong:

1. Wait for https://github.com/QubesOS/qubes-issues/issues/1778 to be completed (which might be already) (not a blocker for my further progress but a release blocker).
2. I'll do a quick test of Qubes-Whonix 16 in Qubes R4.2 since the template is already available in the community testing repository.
3. I'll test a Qubes-Whonix 16 to Qubes-Whonix 17 release upgrade on Qubes R4.2. (This should be optional, and I don't foresee many issues.)
4. I'll test the new Qubes-Whonix 17 templates and see if any fixes are required.
5. I'll migrate the Qubes-Whonix 17 templates to R4.2 community stable repository.
6. Send a PR to update the Whonix version number for salt in file `/srv/formulas/base/virtual-machines-formula/qvm/whonix.jinja`.
7. Announce the release of Whonix 17.

Anything else that needs coordination?

**Comment by marmarek** [comment]
> Send a PR to update the Whonix version number for salt in file `/srv/formulas/base/virtual-machines-formula/qvm/whonix.jinja`.

At this point (or before it), there needs also to be an update of https://github.com/QubesOS/qubes-meta-packages/blob/main/comps/comps-dom0.xml#L1740 (templates included on the ISO). And possibly minor adjustments to the installer for new naming scheme (this I'd track under #1778 )

**Comment by adrelanos** [comment]
https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/55

**Comment by adrelanos** [comment]
blocker which probably only @marmarek can help with:

* https://github.com/QubesOS/qubes-issues/issues/8325

**Comment by adrelanos** [comment]
another (probably) stable release blocker which affects Whonix because unwanted extraneous packages are installed by default:

* https://github.com/QubesOS/qubes-issues/issues/8330

**Comment by adrelanos** [comment]
[Qubes-Whonix 17 for Qubes R4.2 is available! (Debian 12 bookworm based) - Major Release - Testers Wanted!](https://forums.whonix.org/t/qubes-whonix-17-for-qubes-r4-2-is-available-debian-12-bookworm-based-major-release-testers-wanted/16885)

**Comment by adrelanos** [comment]
> [Qubes-Whonix 17 for Qubes R4.2 is available! (Debian 12 bookworm based) - Major Release - Testers Wanted!](https://forums.whonix.org/t/qubes-whonix-17-for-qubes-r4-2-is-available-debian-12-bookworm-based-major-release-testers-wanted/16885)

* https://github.com/QubesOS/updates-status/issues/3863
* https://github.com/QubesOS/updates-status/issues/3864

If all goes good enough during testing (no issues foreseen), the Template can be moved to the `qubes-templates-community` (stable) repository in 4 days.

**Comment by k4r4b3y** [comment]
Can I use Whonix 17 on Qubes 4.1?

**Comment by adrelanos** [comment]
No.

**Comment by adrelanos** [comment]
From the Whonix side, this is completed.

On the Qubes side, the salt upgrade (https://github.com/QubesOS/qubes-issues/issues/7931#issuecomment-1621892708, https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/55, https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/55) is important, because without the updates salt, installation is difficult for users. (New Whonix version number and https://github.com/QubesOS/qubes-issues/issues/1778)

Waiting for https://github.com/QubesOS/updates-status/issues/3915 to hit Qubes dom0 stable repository.
