### ISSUE TITLE
NixOS templates?

### ISSUE THREAD

**Issue by stuser81** [QubesOS/qubes-issues#7992]
There are currently no NixOS templates in the Qubes ecosystem.

How difficult would this be to achieve? I'm talking about templates for NixOS that are on-par with the default Qubes debian and fedora templates (with full copy-paste and qvm-move/qvm-copy between templates, etc.)

Benefits: We could spin off a NixOS VMs (standalone or AppVMs) based on a single reproducible **Nix configuration file** (the main selling point of NixOS).

**Comment by marmarek** [comment]
For start, it requires somebody to package all relevant qubes packages. I see somebody started (https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/qubes), but that's far from complete. Then, qubes-builder needs to get support for building actual template out of those packages.

Generally, see this document: https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-non-fedora-template.md

**Comment by andrewdavidwong** [comment]
Please note that the issue tracker (qubes-issues) is not intended to be a place for fielding questions. Instead, we have other [venues meant for asking questions, asking for help, and having discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!

If you (@stuser81) or someone else is willing to commit to creating (a) community NixOS template(s), then this issue can be reopened and used for that purpose.

**Comment by evq** [comment]
Hey there, I have been working on a NixOS template here - https://github.com/evq/qubes-nixos-template

A fair bit of the base functionality is present, but I have not yet created an RPM for others to install. Should this issue be re-opened to track the progress?

**Comment by evq** [comment]
I've been looking into what it would take in order to get dom0 initiated updates working. it's a bit tricky to do a one size fits all solution for NixOS users but I was hoping to start with something relatively simple and extensible. ( users may store their system config in /etc/nixos or they may reference a remote git repo, they may use flakes, etc. ) my thought was to take a page out of https://nixos.wiki/wiki/Automatic_system_upgrades and expose flags to allow a user to customize the nixos-rebuild invocation. I already got update checks working with this sort of approach without too much effort and was hoping the the updates themselves would be just as easy.

at first I thought it would be quite straightforward and would just require a custom `qubes.InstallUpdatesGUI` qrexec service. however it seems that this is not actually used ( and is deprecated? ) and instead `qubes-update-gui` injects https://github.com/QubesOS/qubes-core-admin-linux/blob/main/vmupdate/agent/entrypoint.py into the VM and attempts to execute it via `qubes.VMExec`. currently this fails as it has the python3 path hardcoded at `/usr/bin/python3`.

I'm at a bit of a loss as to how to proceed. in general dom0 won't know the correct absolute path to use. you could imagine for instance that `vmupdate` depends on a different python3 version than that of the "system" python3 or there may not be any "system" python3 at all. an option would be to use `makeWrapper` to modify the PATH of `qubes.VMExec` such that a non-absolute `python3` would work and add that in a nix specific conditional in `vmupdate`. I worry though that this is just one of many hardcoded assumptions.

rather this python3 issue seems to be illustrative of a larger mismatch in expectations though or at the very least a gap between my understanding of why the simpler `qubes.InstallUpdatesGUI` approach was abandoned and how this new system was designed. for instance, it seems strange to me that the `vmupdate` code is injected from dom0 as it creates a much tighter coupling than the `qubes.InstallUpdateGUI` approach which allowed for easy replacement for a particular distribution.

can someone help me understand the reasoning for the injection over say having the `vmupdate` agent be a standalone package that is installed in each templatevm?

I have to admit I haven't dug too deeply into the `vmupdate` internals, but perhaps some of the additional complexity is a result of salt based update management? for managing NixOS I think using pure nix in liu of salt might be worth investigating, however I'd like to put this out of scope for the moment. as I mentioned at the start - I'd like to get something simple working first. 

would it make any sense to have `qubes-update-gui` ( or perhaps `qubes-vm-update` / `vmupdate` itself ) fallback to `qubes.InstallUpdatesGUI` when a distro doesn't support the injected `vmupdate` approach?

from the little I currently know, having a fallback behavior seems like it would be the easiest path forward for now and has the advantage of making it easier to provide update support for other non-official templates as well.

**Comment by evq** [comment]
created https://github.com/QubesOS/qubes-issues/issues/9448 based on the `qubes.InstallUpdates` suggestion

**Comment by marmarek** [comment]
> rather this python3 issue seems to be illustrative of a larger mismatch in expectations though or at the very least a gap between my understanding of why the simpler `qubes.InstallUpdatesGUI` approach was abandoned and how this new system was designed. for instance, it seems strange to me that the `vmupdate` code is injected from dom0 as it creates a much tighter coupling than the `qubes.InstallUpdateGUI` approach which allowed for easy replacement for a particular distribution.
> 
> can someone help me understand the reasoning for the injection over say having the `vmupdate` agent be a standalone package that is installed in each templatevm?

Sure. This is compromise we debated about quite a bit. On one hand, something like `qubes.InstallUpdatesGUI` provides a much better abstraction. But on the other hand, it's much less flexible, especially when the update mechanism itself needs an update. Additionally, we use this mechanism to deliver security fixes to the template update mechanism itself (both [Debian](https://www.qubes-os.org/news/2019/01/23/qsb-46/) and [Fedora](https://www.qubes-os.org/news/2021/03/19/qsb-067/) needed this in the past). The last part require us to inject some code into the template _before_ installing updates there - shipping updated `qubes.InstallUpdatesGUI` via a normal template package is not an option in such a case.
The above means #9448 is not a direction we want to go.

As for the issue at hand, using plain `python3` and relying on `$PATH` has its own issues: https://github.com/QubesOS/qubes-issues/issues/9200. How you find "system" python3 in NixOS? We have a mechanism to tell dom0 what distribution is running inside the template (see https://github.com/QubesOS/qubes-core-agent-linux/pull/481) - with that, there can be some conditional code to do things differently for NixOS.

**Comment by evq** [comment]
@marmarek my suggestion doesn't preclude the injection based mechanism where supported, so I'm not sure I understand why you're opposed to a fallback in that case.

**Comment by evq** [comment]
also as mentioned at the start of my message, for NixOS there really needs to be some end user customization of the exact invocation. if not via a `qubes.InstallUpdates` RPC then via another shell script that is written by one of the qubes nix modules.

see: https://github.com/evq/qubes-nixos-template/blob/main/modules/qubes/updates.nix#L74-L87

would your preference be to provide a NixOS `PackageManager` class that just executes a `qubes-nixos-upgrade` shell script which has previously been written out? or would you prefer that flags are read from a file?

**Comment by marmarek** [comment]
> also as mentioned at the start of my message, for NixOS there really needs to be some end user customization of the exact invocation

Sounds like a package manager configuration, but not stored in a file by provided by the user every time they update the system... Isn't there really any config file where this could be set already? I find it hard to believe that the standard update approach is to either write own script or fish out a long command from the shell history...

> would your preference be to provide a NixOS `PackageManager` class that just executes a `qubes-nixos-upgrade` shell script which has previously been written out? or would you prefer that flags are read from a file?

I guess you meant https://github.com/evq/qubes-nixos-template/blob/main/modules/qubes/updates.nix#L13-L31 flags? 
IMO better read flags from a file. This allows easier extension of the actual update call (for example adding progress reporting).

**Comment by evq** [comment]
> Isn't there really any config file where this could be set already?
with NixOS there is a config file for the entire system configuration. what I linked you to earlier is a script that would be generated based on said configuration file, not one that would be manually written by the end user.

https://nixos.wiki/wiki/Automatic_system_upgrades is worth a quick look as it shows how a user would configure unattended system upgrades in nixos. based on this configuration option, a systemd unit is generated which calls `nixos-rebuild` with the user's specified flags.

the approach I am suggesting is mimicking this

**Comment by marmarek** [comment]
> there isn't a "system" python3. instead you would want to launch the python3 which is a dependency of the qubes components. that path will vary over time. the best bet would be a bare `python3` specifically if the distribution is NixOS and to wrap the `qubes.VMExec` such that the PATH is set that `python3` will always use the correct version

Makes sense. The vmupdate could try to execute something like `sh -c 'env PATH=/usr/bin:$PATH python3 .../entrypoint.sh'` (`sh` to get `$PATH` expanded...). Or have a special case for NixOS.

**Comment by unhighghlow** [comment]
> > there isn't a "system" python3. instead you would want to launch the python3 which is a dependency of the qubes components. that path will vary over time. the best bet would be a bare `python3` specifically if the distribution is NixOS and to wrap the `qubes.VMExec` such that the PATH is set that `python3` will always use the correct version
> 
> Makes sense. The vmupdate could try to execute something like `sh -c 'env PATH=/usr/bin:$PATH python3 .../entrypoint.sh'` (`sh` to get `$PATH` expanded...). Or have a special case for NixOS.

The current version of the NixOS template returns:
```
ModuleNotFoundError: No module names 'qubesagent'
```
This indicates that python was found. And the error should be easy to fix, I'll try

**Comment by unhighghlow** [comment]
Weird, it specifically requests the qubesagent library (itself -- "$out"): https://github.com/evq/qubes-nixos-template/blob/2f29942275d6168780dba2d892b769da3e9df6c8/pkgs/qubes-core-agent-linux/default.nix#L406

**Comment by dsg22** [comment]
Hey, I'd like to bikeshed this a bit - feel free to ignore, I'd rather have the NixOS template merged than have things be "perfect". :)

As I understand the proposed qubes-update solution, it requires python3 to be in $PATH (i.e., the user needs to have python3 in environment.systemPackages). This doesn't feel very nix-y.

Would it be acceptable to have the template provide a file, let's say `/etc/qubes/python3-run`, that the updater calls instead of python3? This could be a symlink to python3, or a shell script, or whatever. The updater can then fall back to running python3 directly if that file doesn't exist, for compatibility with templates that don't provide it.

Then, for the NixOS template, this could be a shell script that runs python3 without installing in the environment:
```sh
#!/usr/bin/env nix-shell
#!nix-shell -i sh -p python3Full

python3 $@
```

Also, big thanks to @evq for working on this. Getting a NixOS template for Qubes would be just lovely.

**Comment by evq** [comment]
heya. sorry, it's been a while. [I actually made the changes to `vmupdate` discussed a while back](https://github.com/evq/qubes-core-admin-linux/commit/f681cca2a7d0413f2aff306196711a3371a245b2#diff-b225a3a4bf2375cf76a1c18cf1ce963ac0344b2fc959ad36811d58fccf02739eR167), but they need a rebase and to finish any requested changes from the [PR review.](https://github.com/QubesOS/qubes-core-admin-linux/pull/168)

as suggested it relies on `$PATH` resolution, but it does not require the user to put `python3` in `environment.systemPackages`. [instead it is ensured to be in the `$PATH` for `vmexec` specifically.](https://github.com/evq/qubes-nixos-template/blob/main/modules/qubes/updates.nix#L114) cc @dsg22 

---

[fwiw I believe this list is still largely accurate as far as what is currently working and what is broken/untested.](https://github.com/evq/qubes-nixos-template/tree/main?tab=readme-ov-file#notes)

feedback welcome on what others would find most useful to get working next / how to best proceed on this template.

**Comment by dsg22** [comment]
@evq 

> 
> as suggested it relies on `$PATH` resolution, but it does not require the user to put `python3` in `environment.systemPackages`. [instead it is ensured to be in the `$PATH` for `vmexec` specifically.](https://github.com/evq/qubes-nixos-template/blob/main/modules/qubes/updates.nix#L114) cc [@dsg22](https://github.com/dsg22)

Great to hear :)

> 
> [fwiw I believe this list is still largely accurate as far as what is currently working and what is broken/untested.](https://github.com/evq/qubes-nixos-template/tree/main?tab=readme-ov-file#notes)
> 
> feedback welcome on what others would find most useful to get working next / how to best proceed on this template.

I built the template about a week ago and have only done some light testing. But so far, my top 3 improvement/fix wishlist would be:

### Maintaining GUI and qrexec connections through configuration switches/upgrades

On my first `nixos-rebuild switch --upgrade`, all windows disappeared and VM did not respond to qrexec. Probably qubes-gui-agent and qubes-qrexec-agent got restarted due to upgrade.

### Getting app launches to work from the menu.
E.g. if I run xfce4-terminal, nothing happens. Same with VM manager tray -> "Run terminal". I've been running `qvm-run nixos-test xfce4-terminal` from a dom0 term, which is inconvenient.

Actually testing it just now I see an error in log, looks like the qubes.StartApp RPC script needs a shebang fix.

### Automatic keymap setting.
Dom0 sends a notification to VMs on keymap change so they can switch, but this does not work currently.

**Comment by Saduff** [comment]
> Getting app launches to work from the menu.
> E.g. if I run xfce4-terminal, nothing happens. Same with VM manager tray -> "Run terminal". I've been running qvm-run nixos-test xfce4-terminal from a dom0 term, which is inconvenient.

I just started using Qubes and the NixOS template and ran into the same problem. Unfortunately, this is too much of a hassle, making the NixOS template unusable for me at this time. IMO, this is the most important thing to get working.

Also, great work @evq for creating the NixOS template in the first place.

**Comment by dsg22** [comment]
FWIW, I'm working on those issues I mentioned earlier, just so we don't end up duplicating effort :)

You can find my work in this repo:
https://github.com/dsg22/qubes-nixos-template

Current status is that I've updated all packages to the latest 4.3 versions (I don't think it makes sense to spend effort on packaging the older 4.2 versions, 4.3 is already in RC and I've switched my daily driver to it). I also worked around the issue of qrexec and guid connections dropping on `nixos-rebuild` by telling systemd not to restart them when things change. It means that any updates or changes affecting those services will not be applied until VM restart, but it's better than losing all access to the VM and potentially in a partially-applied state when the terminal running `nixos-rebuild` disappears in the middle of applying the new state.

I checked a debian template, and restarting gui-agent there also means everything disappears and it doesn't recover. So I guess these services are protected in the same way there, though I don't see anything in the systemd unit about it.

Currently working on fixing the qubes.StartApp problems that prevent launching apps from the menu.

**Comment by dsg22** [comment]
Quick update. Launching apps from the menu now works. Also worked around an issue where the launched apps didn't get their environment variables set right. Being able to start programs from the menu is a big milestone, at least in my opinion it makes the template useable for daily driving. Serious props to @evq for doing all the hard work on this. :)

I was hoping to have the keymap notifications working by now so I could cross off my list, but it's turning out to be harder than I thought. The problem is how Qubes is using XDG .desktop files with OnlyShowIn=X-QUBES and autostart as a poor mans service manager. On other Qubes systems, `qubes-gui-runuser` injects the relevant environment variables into `pam_env.so`. It then launches `qubes-session` and from there pretty much all the GUI-related (and some not GUI-related) things get spawned. So everything gets these variables, including `qubes-session-autostart` which is a shell script that runs these .desktop files (since there's no desktop environment, which would normally handle that). @evq's template uses `systemd-xdg-autostart` instead, which generates systemd units from these files. Neat and much better than the hacky script, but turns out it won't run the services (like the keymap notification handler) because there's no registered desktop session with X-QUBES name.

I went back and forth on this, disabled `systemd-xdg-generator` and tried to get the pile-of-scripts approach of qubes working but hit more roadblocks there. Eventually I ditched that approach and went back to `systemd-xdg-generator`, thinking I'd just set the variables manually through `environment.sessionVariables`. Only it turns out it's not enough to set `XDG_SESSION_{CLASS,TYPE}`, `XDG_{SESSION,CURRENT}_DESKTOP` and `XDG_SEAT` to make systemd happy. I also need to set `XDG_VTNR`, the virtual terminal number the display server is running on. Which is a concept that makes no sense in Qubes, where the display is just a buffer in RAM and has no VT. And putting in a dummy value doesn't work, because systemd checks it. So... that's where I'm at.

At this point I'm thinking of just writing systemd units for these things and dumping this .desktop-as-init-system madness. Ideally this would be done in the upstream packaging, but I'll probably just do it in the NixOS module for now.

**Comment by dsg22** [comment]
@evq any chance I could pick your brain a bit? I've never dealt with resholve before. How do I reference the resholved outpath? $out points to the nix store dir pre-resholve. But then I need to fixup paths in the .desktop files, and then I need to point to the resholved versions.

I've worked around the problem mentioned in my earlier comment, so that's not an issue anymore.

**Comment by dsg22** [comment]
Ended up pulling pulling in a copy of resholved-utils.nix and adding a postFixupResholved attribute. Created a PR, hoping upstream will accept it:
https://github.com/NixOS/nixpkgs/pull/439997

Things now working since last update:
* Automatic keymap sync
* bind-dirs (selectively making AppVM directories persistent)
* Icons for menu items

**Comment by dsg22** [comment]
Today's progress:

* Audio is working
* Auto time sync from dom0 working, disabled systemd-timesync iin the template

BTW, I'm not using the flake configuration, so if you notice something broken there let me know and I'll fix it. I try to organize my changes so they work with and without flakes, but I'm not actively testing the flake config.

**Comment by dsg22** [comment]
@marmarek any chance you can give some tips on how to debug DispVM startup? It's not working on the NixOS template, I haven't had time to look into it much. But is there a way to tell qubes to keep a DispVM running even with no apps, so I can debug what's happening?

**Comment by marmarek** [comment]
try named disposable maybe? and then simply `qvm-run -p --service DISPVM_NAME qubes.StartApp+xterm` (or whatever other app you want), instead of `--dispvm` option
