### ISSUE TITLE
Systemd service qubes-network-uplink@.service stops to early (starts up to late)

### ISSUE THREAD

**Issue by swamba** [QubesOS/qubes-issues#8005]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.1.1 (R4.1)

### Brief summary

The qubes-network-uplink@.service stops to early cutting the network connection before targets like remote-fs.target shut down causing mounts like Samba to hang, which causes long shutdown times for qubes.

### Steps to reproduce

Open a qube which has permission to mount a Samba mount.
Manually mount a Samba directory.
Shut down qube.

### Expected behavior

The qube shuts down like any normal qube

### Actual behavior

The qube takes 90 seconds more to shut down then normal qubes.

**Comment by swamba** [comment]
One solution to this is to add the following into the .service file

`Before=remote-fs.target`

I don't know though if this is the right target, I leave that up to you guys.

**Comment by DemiMarie** [comment]
@swamba It probably is, want to make a PR?

**Comment by rustybird** [comment]
Looks like it could be fixed more generally:

`qubes-network-uplink@.service` is missing a `Before=network.target` ordering. Such an ordering would be redundant during startup, because these instances are started through the script in `qubes-network-uplink.service` (which already has the ordering), but it's not redundant during shutdown.

Also, network *provider* units are the ones who are supposed to pull in the passive `network.target` with a `Wants=` dependency. But `qubes-network-uplink.service` and `qubes-network-uplink.service` don't. It's only pulled in coincidentally if another network provider unit is installed and enabled, such as `NetworkManager.service`.

@swamba Can you please try to add this to `qubes-network-uplink@.service` (instead of `Before=remote-fs.target`):

    Before=network.target
    Wants=network.target

And this to `qubes-network-uplink.service`:

    Wants=network.target

Those changes [should](https://www.freedesktop.org/software/systemd/man/systemd.mount.html#Default%20Dependencies) make systemd order the network provider units correctly in relation to your Samba "network mount unit", avoiding the shutdown hang.

**Comment by swamba** [comment]
Hi, I can confirm that the changes @rustybird suggested work for my Fedora 36 qubes/template

My current qubes-network-uplink@.service file looks like this now:

`[Unit]
Description=Qubes network uplink (%i) setup
After=network-pre.target qubes-iptables.service
After=sys-subsystem-net-devices-%i.device
Before=network.target
Wants=network.target
BindsTo=sys-subsystem-net-devices-%i.device

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/lib/qubes/setup-ip add "%i"
ExecStop=/usr/lib/qubes/setup-ip remove "%i"
`
I would appreciate it if someone else would put up a PR for this issue.

**Comment by rustybird** [comment]
Thanks for testing @swamba.

PR: https://github.com/QubesOS/qubes-core-agent-linux/pull/406
