### ISSUE TITLE
"<qube> failed to execute getDate in dom0" frequently when shutting down qubes

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8020]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1.1

### Brief summary

A notification in dom0 saying something like "<qube> failed to execute getDate in dom0" frequently occurs when shutting down qubes. Some users seem to see this more frequently with disposables and/or when shutting down a qube very quickly after starting it. It seems to be relatively harmless, but it does prompt users to wonder:

https://forum.qubes-os.org/t/what-does-dispxxx-failed-to-execute-getdate-in-dom0-mean/16695

### Steps to reproduce

Try starting a disposable then immediately shutting it down.

### Expected behavior

No message about `getDate`.

### Actual behavior

Message about `getDate` as described above.

**Comment by lubellier** [comment]
Not exactly the same issue than https://github.com/QubesOS/qubes-issues/issues/7067 and  https://github.com/QubesOS/qubes-issues/issues/7013 but looks near...

**Comment by GrassfedMeatSticks** [comment]
Hi,

I stumbled upon this issue while researching this error and thought I'd come back to share my finding/solution.

In my case, I was experimenting with the **qubes-app-shutdown-idle** package in a minimal Fedora 38 template on Qubes 4.1.2 (R4.1) and found that a **TIMEOUT_SECONDS** value in the TemplateVM's `/lib/python3.11/site-packages/qubesidle/idleness_monitor.py` of 10 seconds reliably produced this error in downstream App/dispVMs, but 15 seconds did not. I tested these values a couple of times to confirm; I did not test values 11-14. 

Of course, when it comes to utilizing **qubes-app-shutdown-idle**, the downstream App/dispVM must have the Settings -> Basic (tab) -> **Shut down when idle for more than 15 minutes** checked (It would be more helpful if this checkbox could be labeled something more like "Enable qubes-app-shutdown-idle" since the **TIMEOUT_SECONDS** value is configurable and not always 15 minutes).

I hope this data point helps.
