### ISSUE TITLE
R.4.1.2-rc1 installer: Scaling issues make it impossible to recover space from a disk when using kernel-latest on Iris XE

### ISSUE THREAD

**Issue by susanthenerd** [QubesOS/qubes-issues#8029]
### Qubes OS release
R4.1.2-rc1
### Brief summary
Scaling issues generated by kernel-latest on Iris XE(I don't know the exact version it started on), will make anacoda to scale at 2x instead of 1x, making some menus unusable.

### Steps to reproduce
Open the installer with kernel-latest and go to the disk selection menu. The disk needs to not have any free unpartitioned space, which should normaly open a popup where the user can delete partitions from a drive to recover space, however the system will hang for a few seconds and than it will show the bug report menu.

### Expected behavior
Show the recover space popup

### Actual behavior
Bug report menu is show and it impossible to delete the partions in any way without using a console.

**Comment by marmarek** [comment]
Can you post specific message you got in this "bug report menu"?

**Comment by marmarek** [comment]
Extra details from IRC:
> anacoda just has to be configured to scale at 1x
on lower than 1504p resolutions
I'm saying 1504p since that is what I have on my framework  and it is where it scales wrong
And I think it will happend and 1440p aswell

I tried on a Framework, with Intel Xe graphics (the Tiger Lake variant). I have resolution 2256x1504 there. The UI is indeed scaled 2x, but it looks like it should be on this resolution (otherwise everything is tiny). And all the elements, including "reclaim disk space" dialog fits on the screen just fine, and work just fine. Can you post a screenshot/photo of the problem?

**Comment by cristiioan** [comment]
Sorry for replying late!
I'm not sure what exactly causes the issue.When I reinstalled last time, it didn't crash so I think it might be based on the number of partitions on the device that it has to display for deleting one. I know that it is the only thing that was different between the reinstals(except using release and not rc)
