### ISSUE TITLE
Fedora 37 Nautilus: broken widget GtkPopoverMenu (black background instead of transparency)

### ISSUE THREAD

**Issue by aronowski** [QubesOS/qubes-issues#8081]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

When right-clicking inside a Nautilus area, for instance on a folder, a menu pops up but with a black background, which should be transparent instead.
When running Nautilus in a terminal, a message similar to this one is presented:

```
(org.gnome.Nautilus:978): Gtk-WARNING **: 17:54:01.282: Broken accounting of active state for widget 0x5c2dfbbe9640(GtkPopoverMenu)
```

![nautilus](https://user-images.githubusercontent.com/100043949/223495601-592c82c0-6649-4d32-8fcd-cdd36fa1653b.png)

### Steps to reproduce

Install fedora-37 template, run a qube based on it, launch Nautilus in such qube and right-click on a folder.

### Expected behavior

A menu with transparent background pops up along with a color decoration provided by Qubes.

### Actual behavior

A menu with black background pops up along with a color decoration provided by Qubes.

**Comment by noskb** [comment]
The same for GTK4 applications other than Nautilus.

A workaround
```
mkdir ~/.config/gtk-4.0
echo '* { box-shadow: none; }' >  ~/.config/gtk-4.0/gtk.css
```
Then restart the application or qube.

**Comment by DemiMarie** [comment]
Qubes OS should probably do this by default @noskb.

**Comment by marmarek** [comment]
Is there an equivalent location in /etc?

**Comment by noskb** [comment]
According to [gtkcssprovider.c](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkcssprovider.c#L52-84), it looks like `$XDG_CONFIG_HOME/gtk-4.0/gtk.css` only.

**Comment by marmarek** [comment]
I guess we can patch it in user's home dir then... It would need to be in some startup script, and create a flag file (also in homedir) to not do it twice (even if user reverts the change).

**Comment by sityvb** [comment]
> The same for GTK4 applications other than Nautilus.
> 
> A workaround
> 
> ```
> mkdir ~/.config/gtk-4.0
> echo '* { box-shadow: none; }' >  ~/.config/gtk-4.0/gtk.css
> ```
> 
> Then restart the application or qube.

That removes all box shadows, which is very over-reaching, (this may in some cases improve performance, but this really does change apps quite a lot, is generally not necessary), and the popovers are still round, so they have black corners etc.

I personally use such css to fix popovers:

```css
.solid-csd popover > contents, .solid-csd .hover-assistant, .solid-csd .completion {
	box-shadow: none;
	border-radius: 0px;
	margin: 0px;
}
```
margin: 0, hover-assistant and completion are only needed for GtkSourceView popovers. Also, I noticed that GtkDropDown popovers have a top margin too.

Then arrow-less popovers work just like they did in GTK3 solid-csd.
Note that the black background around the arrow remains, and the arrow cannot be removed via css (if that were preferred).
A possible workaround would be
```css
popover > contents {
    border-style: none;
}

popover > arrow {
	border-style: none;
}

popover {
	background-color: @view_bg_color;
}
```
With this instead of the arrow, there would be blank padding on the side of the popover with the arrow.

Also, I noticed that in GTK4 apps when using the default gl renderer instead of cairo, especially on large window sizes the toplevel box shadow on windows has a very major impact on performance.

```css
window {
	box-shadow: none;
	padding: 0px;
}
```
On 1440p this generally increases the framerate multiple fold. (padding 0px, because it looks slightly weird without that box shadow, and the padding is useless anyway on Qubes because there is SSD, and you can't resize from the csd anyway).

A better solution would be for the gui daemon to support alpha transparency, then the popovers will only have a colorful border and a gap instead of this black background (like Firefox and Thunderbird currently work).

Also if something like this were to be applied, a startup script would need to be used, because GTK4 doesn't support system-wide in /etc css overrides.

**Comment by noskb** [comment]
@sityvb 
Thank you for your good insight, it makes sense.
If you don't mind, could you create a PR?

**Comment by noskb** [comment]
Related: https://github.com/QubesOS/qubes-issues/issues/6821
