### ISSUE TITLE
Error when attempting to update dom0 in the Qube Manager

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#8117]
### Qubes OS release
R4.2

### Brief summary
When selecting dom0 in the Qube Manager and clicking the Update icon, an error message

 qubes-dom0-update, '--clean', '--gui' returned non-zero error status 1

is displayed after about half a minute. No update is attempted or performed.

### Steps to reproduce
Select dom0 in the Qube Manager and click the Update icon.

### Expected behavior
dom0 update should start.

### Actual behavior
An error message is displayed and no update is performed. Entering the command `sudo qubes-dom0-update --clean --gui` works as expected.

**Comment by andrewdavidwong** [comment]
Related issue: https://github.com/QubesOS/qubes-issues/issues/6635

**Comment by andrewdavidwong** [comment]
Seems to be very similar to #4652, but the described behavior differs.

**Comment by GWeck** [comment]
It looks like an old problem appearing once again. In R4.1, the updater worked o.k., but in R4.2 this error occurs.

**Comment by marmarta** [comment]
@piotrbartman , this looks like updater issue - what command should I run for dom0 updates from manager in the current updater version?

**Comment by marmarta** [comment]
I think there are two problems here:
- something fails during updating
- there's no way of checking what exactly failed

with a bonus problem of "different ways of doing updates do it differently, clicking update from qui-updates widget launches  a different updater than  clicking update from manager. I think we should unify this to always use the new updater (which is generally better all around), and then we'll be able to see what exactly fails in dom0 update (because I can't replicate this bug on any 4.2 I have around..). I'll open a ticket for it.

**Comment by GWeck** [comment]
On my R4.2 system, the behavior has changed a bit: Now, when you hit the update button in dom0, first nothing happens. Then, after a few minutes, the update window is displayed, showing that the updates are already downloaded and ready for installation. So the download seems to start silently in the background, without any more error.

**Comment by marmarta** [comment]
OK, this feels like very much an issue to be fixed with https://github.com/QubesOS/qubes-issues/issues/8355 , because in the current way you get zero feedback, which is not great.
