### ISSUE TITLE
Screen lock off button

### ISSUE THREAD

**Issue by utenus** [QubesOS/qubes-issues#8148]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Going into settings very often for turn off the lock screen and after movie turn it back on from settings.

### The solution you'd like
It would be useful to add a much-needed function that is known from the MATE environment. There is a convenient button in the action bar to completely disable the screen lock. It is very convenient when you start watching a movie, then you can quickly turn off the lock screen while watching the movie and turn it on again after the movie is over. It is much more convenient than entering the settings.

**Comment by andrewdavidwong** [comment]
Qubes OS uses Xfce, but we don't maintain Xfce. Since this is a feature request for Xfce, I suggest you submit this feature request upstream to their issue tracker instead.

-----

Closing as an "unsuitable proposal" (the proposed action is unsuitable, e.g., because it rests on a false assumption or misunderstanding, such as a proposed enhancement designed to fix something that is not really a problem in the first place). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by rustybird** [comment]
@utenus Right-click the power manager icon (in the upper right corner of the screen) and tick the "Presentation mode" checkbox
