### ISSUE TITLE
VPN not connecting on Fedora 38 

### ISSUE THREAD

**Issue by 92VV3M42d3v8** [QubesOS/qubes-issues#8250]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2.0 rc1

### Steps to reproduce

Install openvpn and try to connect vpn on fedora-38 template. VPN not able to connect. Possible issue with iptables and nftables.

### Expected behavior

VPN connects successfully

### Actual behavior

Not able to connect.

**Comment by andrewdavidwong** [comment]
> Install openvpn and try to connect vpn on fedora-38 template.

Templates do not have normal network access by design:

https://www.qubes-os.org/doc/how-to-install-software/#why-dont-templates-have-network-access

-----

Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
