### ISSUE TITLE
Evolution uses gpg --auto-key-locate option, that isn't supported by split-gpg

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8287]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

Evolution (the default email client in Debian 12) uses `--auto-key-locate local,wkd` option. This fails any gpg operation when split-gpg (v1) is used.

### Steps to reproduce

1. Install debian-12 template
2. Configure Evolution to use qubes-gpg-client-wrapper as gpg
3. Try to send an encrypted and signed message

### Expected behavior

Message sent, encrypted and signed using keys already in the keyring.

### Actual behavior

An error about unsupported `--auto-key-locate local,wkd` option.

**Comment by marmarek** [comment]
The option looks like a complicated feature, with several key discovery mechanisms. It won't work to just allow passing it, as the backend doesn't have network access (and even if it had, it sounds like a bad idea attack-surface-wise).

In general, ignoring it doesn't sound like a good idea either, as that changes the behavior, but actually `local,wkd` is the default value (according to documentation), so maybe ignoring it if used with the default value is the way to go?

BTW The issue won't apply to split-gpg2.

**Comment by andrewdavidwong** [comment]
> The option looks like a complicated feature, with several key discovery mechanisms. It won't work to just allow passing it, as the backend doesn't have network access (and even if it had, it sounds like a bad idea attack-surface-wise).
> 
> In general, ignoring it doesn't sound like a good idea either, as that changes the behavior, but actually `local,wkd` is the default value (according to documentation), so maybe ignoring it if used with the default value is the way to go?

Why not simply print a message stating that Split GPG doesn't support `--auto-key-locate`?

**Comment by marmarek** [comment]
> Why not simply print a message stating that Split GPG doesn't support `--auto-key-locate`?

If you call it manually, that would be okay, but when gpg is called from some application (evolution here), you won't see this message at all. Besides, I don't expect average user to know what specific gpg options mean, so that won't really be meaningful.

**Comment by andrewdavidwong** [comment]
> If you call it manually, that would be okay, but when gpg is called from some application (evolution here), you won't see this message at all.

The message wouldn't have to be limited to the command line. There could be a desktop notification for such cases, similar to when the Split GPG backend is accessed. (But then again, those aren't very useful either.)

> Besides, I don't expect average user to know what specific gpg options mean, so that won't really be meaningful.

Well, we get to make such messages as meaningful as we want, since we're the ones who write them. It's just a matter of including enough explanatory text. But that opens another can of worms, since users rarely seem to read long explanatory notifications and tend to freak out upon seeing them, so I anticipate we'd receive panicked screenshots of the notification asking "What does this mean?!" even if it's perfectly self-explanatory and clearly states that it's safe to ignore in the user's situation. So, yeah, never mind. :)
