### ISSUE TITLE
Global Config: Add setting for customizing global clipboard copy/paste shortcuts

### ISSUE THREAD

**Issue by Eric678** [QubesOS/qubes-issues#8329]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
New R4.2 global config editor does not allow custom setting of the global cliipboard cut and paste key sequences.

### The solution you'd like
Additional drop down menu item for "custom"

### The value to a user, and who that user might be
Personally I have always used Win+C and Win+V and do not wish to have to change.
Also 3 key sequences are more difficult touch typing.
Always wondered why the default for paste was Ctrl+Shift+V as this is required for pasting into any terminal.

**Comment by marmarta** [comment]
Ok, due to amount of fiddling required to make a smart "put your keyboard shortcut here" dropdown (Gtk being fiddly + it would be good to have some sanity checks + and it's not that easy to actually figure out what those should be), I'm adding Win+C/V as options. Other custom options can be set via qvm-features, if someone really wants to, and global config will not complain.
