### ISSUE TITLE
Incomplete GUI Domain Docs

### ISSUE THREAD

**Issue by Philipp-Sc** [QubesOS/qubes-issues#8367]
I am a long time Qubes user and really appreciate your work, I would be happy if we can collect all the information here. If you need later to compile it into one clean document I am happy to help:

The current documentation at [doc/gui-domain](https://www.qubes-os.org/doc/gui-domain/) is incomplete, while the technology works well there is little to no guidance at all.

- There is no progress information regarding the fedora-36-xfce template download
- Actually it appears to be the case that it is better the user first downloads the template and performs a system update, otherwise Qubes Management Tools will be missing
- There is no mention to prepare the template for your needs regarding for example localization and input devices beforehand or can it be done afterwards?
- There is no information how to update, reinstall a sys-gui
- There is no information about what templates (fedora-38-xfce?)  can be used for the sys-gui (template requirements)
- The requirement to change the gui domain for existing qubes and how to do it should not be part of the troubleshooting section, or at least link to the section so users know it exist. 
 
So far I figured out some of the answers by going through the forums and trying to piece the puzzle together but it is really time consuming and requires a trial and error approach. I am sorry If it is the case that I missed the right documentation, maybe it already exists.

Right now I have a sys-gui running, but I do not have the typical Qubes Xfce Menu on the top left corner for easy access to my applications. I need to use the right Qubes Menu to start apps via the terminal. I am probably just missing the right package here, idk.

There also appears to be no sound, leading me to the next question do I need an audio vm?

Thanks in advance for your help.

Best regards,
Philipp-Sc

**Comment by andrewdavidwong** [comment]
> I am a long time Qubes user and really appreciate your work, I would be happy if we can collect all the information here. If you need later to compile it into one clean document I am happy to help

This is a good idea, and I appreciate the effort. However, the issue tracker (qubes-issues) is not the best place for this, as it's intended to be more of a technical tool to support our developers in their work. Instead, this effort would be better suited in one of these places:

- The [forum](https://forum.qubes-os.org/) has a new section for wiki guides and gets the most traffic out of all of our venues.
- The qubes-users mailing list has quite a few readers, but these days it tends to be used more for focused troubleshooting and doesn't host as much extended discussion.
- The qubes-devel mailing list is most likely to be read by developers, but any non-dev messages are unlikely to make it onto the list (or likely to be ignored if they do).

**Comment by Philipp-Sc** [comment]
@andrewdavidwong I see a lot of confusion in the forums, I do not think checking forums for answers to core functionality is the right way to go. Also without proper documentation it makes it extremely difficult for new developers to get a grasp of the system. The best projects like Arch Linux, Gentoo, etc are known for their great documentation / wikis.

**Comment by andrewdavidwong** [comment]
> I see a lot of confusion in the forums, I do not think checking forums for answers to core functionality is the right way to go.

Not just checking, but asking, gathering, and compiling, which is what you wanted to do here. I'm just suggesting you do the same thing you wanted to do here but in a more appropriate venue.

> Also without proper documentation it makes it extremely difficult for new developers to get a grasp of the system. The best projects like Arch Linux, Gentoo, etc are known for their great documentation / wikis.

Definitely, but the best projects also have rules for keeping things organized, otherwise everything would be chaos, and the devs wouldn't be able to efficiently communicate, keep track of things, and find the information they need.

Let me be clear: I am *not* saying that the documentation doesn't need to be improved or that it shouldn't be improved. It should. All I'm saying is that this specific issue tracker has certain [guidelines](https://www.qubes-os.org/doc/issue-tracking/#guidelines) for what content is allowed here, and what you want to do here doesn't appear to fall within these guidelines, so I'm suggesting other venues that seem more suitable.

To be clear, an issue that says "X is missing from the GUI Domain docs" is a perfectly valid type of issue. If you want to open an issue like that (or convert this issue into an issue like that), it would be appropriate here. In fact, there are already several other like that, e.g., #6706, #6773, and #8244, which might already be what you had in mind. (If so, no need to open a duplicate.)

**Comment by Philipp-Sc** [comment]
Thank you for taking the time to elaborate. I'll try to compile an extended doc via the forum.
