### ISSUE TITLE
Can't make the OS in HVM connect to the internet

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#8369]
### Qubes OS release

4.2

### Brief summary

Installing any OS inside any HVM will require internet configuration (adding IP, GW, netmask, etc.). To obtain this information, it is available from Qubes manager settings for the created HVM. Add this info into the NetworkManager, and it should connect, but it doesn't.

### Steps to reproduce

* Install any OS inside an HVM-Qube (in my case Debian/Debian derivatives)
* Try to make it connect to the internet

### Expected behavior

Connect to the internet.

### Actual behavior

It doesnt connect to the internet.

### Might be relevant issues

#7412 
#4189

**Comment by marmarek** [comment]
@DemiMarie this is yet another case where this change causes issues. _If_ that's really what happened here (of which I'm not sure - Windows VM seems to have network working properly), I think it's time to make it opt-in, not opt-out.

**Comment by DemiMarie** [comment]
@marmarek Good point.  Indeed the last problem blamed on this change was actually due to something else, but if it is the cause, then making it opt-in is the right thing to do.  Hopefully in the future Xen will support layer 3 (point-to-point) network interfaces, making all of this moot and improving performance.

**Comment by TNTBOMBOM** [comment]
This issue seems to be fixed from my side, closing.
