### ISSUE TITLE
When executing `qvm-start` with a long list of qube arguments, the last qube doesn't start

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8392]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Steps to reproduce

In dom0, execute a command like:

```
qvm-start qube1 qube2 [...] qube14
```

### Expected behavior

All qubes start.

### Actual behavior

All qubes except for `qube14` start.

**Comment by bzillacodes** [comment]
I tried to reproduce the error without success. Firstly I tried 14 PVH AppVM qubes all with 1 vCPU and 1024M RAM. Then I tried 14-20 qubes but with 2 vCPU and 400-4000M RAM. All seem to start flawlessly. 

Did this happen persistently? And did you try starting `qube14` manually, incase it had been corrupted during cloning/creation/modification processes? Do all the qubes have the same resource topology layout or differences across the 14?

**Comment by andrewdavidwong** [comment]
> I tried to reproduce the error without success. Firstly I tried 14 PVH AppVM qubes all with 1 vCPU and 1024M RAM. Then I tried 14-20 qubes but with 2 vCPU and 400-4000M RAM. All seem to start flawlessly.

Thanks for the repro attempt! Maybe it's something unique to my situation, then.

> Did this happen persistently?

Yes. I have a script that starts a bunch of qubes. I use this daily for doing work, and I've noticed that the last one rarely or never seems to get started by the script.

> And did you try starting qube14 manually, incase it had been corrupted during cloning/creation/modification processes?

Yes, it's completely fine and normal when I start it manually.

> Do all the qubes have the same resource topology layout or differences across the 14?

Yes, AFAIK, just the defaults for the things like VCPUs and memory balancing.

**Comment by bzillacodes** [comment]
For reference: I have been using R4.1.2 (kernel-latest without any dom0 updates applied). I will upgrade dom0/templates and retry to see if I can replicate it.

I may just have to assign a larger amount of minmem in the memory balancing section to see if I can stress out the shared memory allocation, since it seems difficult for my setup to bottleneck using default resource topology, having a total 64gb of RAM doesn't help me reproduce It.

**Comment by jamke** [comment]
Is the last qube somewhat specific, like HVM? 

If the issue is easily reproducible on your PC can you:
1. change the order of qubes to check the the problem is with the last?
2. change the script to use `qvm-start one_qube` on each line for all 14 qubes? It will check if the problem is actually about this tool or just system is not able to start so many qubes.
3. temporary reduce in half the min and max amount of memory for first 13 qubes to check if the issue is about memory amount.

**Comment by andrewdavidwong** [comment]
> Is the last qube somewhat specific, like HVM?

No, just a normal qube.

> change the order of qubes to check the the problem is with the last?

I tried adding a 15th qube, and the 14th still didn't start!

> change the script to use `qvm-start one_qube` on each line for all 14 qubes? It will check if the problem is actually about this tool or just system is not able to start so many qubes.

There's no problem with starting that many qubes, because as soon as I start it manually after the script is done, it starts normally.

> temporary reduce in half the min and max amount of memory for first 13 qubes to check if the issue is about memory amount.

It's definitely not about memory, as I still have plenty of free memory even after starting all of these qubes. (In fact, I often manually start several more afterward without a problem.)

**Comment by andrewdavidwong** [comment]
I've decided to close this issue as "cannot reproduce," since others were unable to reproduce it, and it doesn't bother me enough to trouble with it further. (Attempting to diagnose the phenomenon is turning out to be more disruptive than the phenomenon itself.) If anyone else can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.
