### ISSUE TITLE
`qubes.Input*` from sys-usb should not wait for a guivm in dom0

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#8396]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1.2

### Brief summary
If sys-usb has no guivm, dom0 can't display the `qubes.Input*` prompts. Leaving the system non-accessible until the guivm is added back using another tty shell.

### Steps to reproduce
Removed guivm from sys-usb:
`qvm-prefs sys-usb guivm None`
Restarted sys-usb and prompts for qubes.Input* do not show.

### Expected behavior
`qubes.Input*` prompts should show.

### Actual behavior
`qubes.Input*` prompts don't show.

**Comment by marmarek** [comment]
This is unchanged in R4.2 (the original description still applies). But it works as intended - prompts are shown in a guivm for the source qube. It might be useful to have separate configuration option where prompts for given qube should show up, but that would be a separate feature request.
Otherwise, don't use "ask" action for qrexec calls from gui-less qube, use either "deny" or "allow".
