### ISSUE TITLE
Window Manager update for Dom0

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#84]
**Reported by joanna on 24 Jan 2011 12:13 UTC**
None

Migrated-From: https://wiki.qubes-os.org/ticket/84

**Comment by tlaurion** [comment]
Were there any compiz PoC?

**Comment by ShalokShalom** [comment]
I know this is already decided.

In order to make some things clear:

About the resource consumption:

This counts until you load all apps. Comparing naked desktops makes less sense, imho. 
Plus, its also a question how the distro configured the ISO, which services are loaded and so on. 

Stability: 

Fedora and Debian are fully GTK oriented, so all their packaging is focused on that toolkit and its environments. This includes that all the versions of gcc, libs and so on are ALL completly focused on another DE and Toolkit. They also mix KDE SC 4 with the new stack, which is already known since years as not working fine. 

So, blame distros for choosing a way, that cannot work. Or blame KDE, for ignoring that part, since they are distro fanatics on their own. And spend KaOS a try, who solved it already more than 2 years ago, to bring a superb Plasma5 on the table, a year before all the others.
