### ISSUE TITLE
[Dual Boot/UEFI SB]: grub 2.06 breaks loading the kernel on secure boot enabled systems

### ISSUE THREAD

**Issue by bzillacodes** [QubesOS/qubes-issues#8404]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.2.0-rc1

### Brief summary
Since the grub update of 2.06 (changed from 2.04 in R4.1.2), enrolling the grubx64.efi as a custom EFI in secure boot, grub reports errors about the kernel not loading and no shim_protocol found, when trying to start the install.

### Steps to reproduce
- Have a secure boot enabled system (CSM support disabled, SB enabled, custom EFI enrolled)
- Create/validate the installation medium.
- Enroll the grubx64.efi as a custom enrolled EFI in SB.
- Proceed to start the installation, grub menu appears, but selecting any entry occurs the grub errors such as:

- you need to load a kernel first
- shim_lock protocol not found

### Expected behavior
As from using R4.1.2 with a SB enabled system, upgrading to R4.2.0-rc1 should work with the same strategy.

### Actual behavior
The update of grub from 2.04 to 2.06 breaks SB functionality on UEFI only systems.

**Comment by TNTBOMBOM** [comment]
> Have a secure boot enabled system

Hmm, where does Qubes state that Secure Boot is supported?

**Comment by bzillacodes** [comment]
> > Have a secure boot enabled system
> 
> Hmm, where does Qubes state that Secure Boot is supported?

Well it's not stated anywhere for SB to be officially supported by Qubes OS.

But I have specific cuda workloads (With a lack of vGPU support in Qubes), which leads me to dual booting Ubuntu.

So It wouldn't make much sense for me to disable SB in-between boots, in which, enrolling the Qubes grubx64.efi had worked for me in the past, until the current change of grub 2.06 in R4.2.0-rc1.

**Comment by TNTBOMBOM** [comment]
Ah ok got your point, i think its more of a feature request rather than a bug at current state.

But the ultimate fix is qubes supporting secure boot and thats it: #8206 #4371

**Comment by bzillacodes** [comment]
> But the ultimate fix is qubes supporting secure boot and thats it: #8206 #4371

Alas, I'll likely have to stick with R4.1.2 till then.

**Comment by marmarek** [comment]
I think grub2 disables multiboot2 when SB is enabled, so it can't load Xen in that case... Which kinda makes sense, since multiboot2 format doesn't support signatures, so grub2 can't really verify Xen's signature (if there would be any).

"Fixing" that would involve relaxing this check (making grub2 boot anything, basically defeating all the little remaining benefits of SB), which would be a step backward in SB support (and would need to be reverted to get proper SB support). I don't like going this way, as you can guess. But I can see if it could be configurable (so, you'd still need manual `grub2-mkimage` or similar, but otherwise it might work).

Note that #8206 (especially the second point - https://github.com/QubesOS/qubes-core-admin-linux/pull/131) might make enabling SB a bit easier while not completely disarming it. If you like living on the edge, you can try the script form this PR and enroll unified xen binary directly and skip grub completely.

**Comment by bzillacodes** [comment]
> so grub2 can't really verify Xen's signature (if there would be any).

Hence why I don't need to enroll xen.efi as an EFI PE Image with R4.1, and trying to enroll it on R4.2 makes no diff.

> "Fixing" that would involve relaxing this check (making grub2 boot anything, basically defeating all the little remaining benefits of SB), which would be a step backward in SB support (and would need to be reverted to get proper SB support). I don't like going this way, as you can guess. But I can see if it could be configurable (so, you'd still need manual `grub2-mkimage` or similar, but otherwise it might work).

I did think about disabling SB for the install and attempting to downgrade grub back to 2.04, would this likely work in my case?

> If you like living on the edge, you can try the script form this PR and enroll unified xen binary directly and skip grub completely.

I guess this approach would involve swapping over the xen.gz with the unified one on the installation medium?


Thanks for the insights, much appreciated!

**Comment by bzillacodes** [comment]
> I don't think downgrading grub is realistic (and definitely not supported), but if you are very brave...

My crazy ideas probably come from my simplified high-level understanding, I definitely won't make such attempts on a non-test system...

> (For now) I'd rather recommend installing with SB disabled and enabling only after preparing unified xen.efi on the installed system. 

I will most likely have a look into this as I've been held back testing out R4.2.0-rc1.
