### ISSUE TITLE
default dvm does not clear with reboot

### ISSUE THREAD

**Issue by Catacombs38** [QubesOS/qubes-issues#8420]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Brief summary   
After full reinstall (to make sure nothig I had done to cause issue)  I logged into the qubes forum.  
After did a full power down and restart.
When I started a fresh default dvm Firefox, went to qubes forum.  
i am already logged in.

### Expected behavior
I felt all default dvm  -  disp  would clear everything each time Qube was closesd.  
A default dvm, disp should clear all data, information in it with each shutdown.  
Adding a full power down and restart should not find anything old, like a logged in account in firefox.  (I suspected it might have been some kind of Firefox sync)

### Actual behavior
Opening a default dvm disp already has e logged into qubes forum.

**Comment by DemiMarie** [comment]
Did you click on “Templates” icon instead of “Apps” by accident?

**Comment by bzillacodes** [comment]
Does the VM in question start as disp<num_prefix> or <template_name>-dvm?

**Comment by andrewdavidwong** [comment]
Disposables are automatically destroyed when their last open window is closed. Rebooting Qubes OS is not necessary or relevant here. It sounds like you accidentally used a [disposable template](https://www.qubes-os.org/doc/glossary/#disposable-template) instead of a [disposable](https://www.qubes-os.org/doc/glossary/#disposable) *based on* a disposable template.

Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
