### ISSUE TITLE
Failed to parse firewall rules after enabling IPv6 with qvm-features

### ISSUE THREAD

**Issue by gasull** [QubesOS/qubes-issues#8448]
### Qubes OS release

Qubes release 4.1.2 (R4.1).

### Brief summary

I enabled IPv6 on sys-net and sys-vpn with

```
qvm-features sys-net ipv6 1
qvm-features sys-vpn ipv6 1
```

Since then, I get these errors in some VMs, but not others:

> Failed to parse rules for aaaa:bbbb:cccc::ddd:00 (Failed to resolve example.com)

Despite the errors, I can resolv the domain with `dig` inside the VM, and networking seems to be fine.  The error is always for whatever domain I have at the top of the list in the firewall for the VM, like addons.mozilla.org.

When I disable ipv6 with:

```
qvm-features sys-net ipv6 ''
qvm-features sys-vpn ipv6 ''
```

then the error goes away.

### Steps to reproduce

Enable IPv6.

```
qvm-features sys-net ipv6 ''
qvm-features sys-vpn ipv6 ''
```

### Expected behavior

IPv6 should work and display no firewall errors.

### Actual behavior

It displays the following error:

> Failed to parse rules for aaaa:bbbb:cccc::ddd:00 (Failed to resolve example.com)

**Comment by Istador** [comment]
For me the error message only seems to appear if I add a domain that does not have an `AAAA` DNS record (IPv6) but only an `A` record (IPv4) to the firewall rules of an VM.

Because of the error the firewall blocks all IPv6 for that VM, but IPv4 still works normally.

If there are only domains in the firewall rules that have `A` and `AAAA` records, then both seems to work as expected.

I assume, but have not tested, that a domain that only has an `AAAA` record but no `A` record will have the same issue reversed.

---

IMHO if IPv6 is enabled the error message should only be shown if a domain can't be resolved for both IPv4 and IPv6.

Regardeless of IPv6, if a domain can't be resolved, all the other firewall rules should still be parsed and applied. The firewall rules are allowing things that are otherwise blocked, so if one of the domains (maybe temporarily) can't be resolved, then that's not a situation that should result in blocking everything, but only that one rule with the unresolvable domain should be ignored.

**Comment by marmarek** [comment]
> IMHO if IPv6 is enabled the error message should only be shown if a domain can't be resolved for both IPv4 and IPv6.

This very much makes sense. Currently it is indeed if either fails then error is reported and given protocol is blocked.
