### ISSUE TITLE
4.2: xscreensaver mangle typed characters before being displayed

### ISSUE THREAD

**Issue by rapenne-s** [QubesOS/qubes-issues#8473]
### Qubes OS release

Qubes OS 4.2-RC2

### Brief summary

When the laptop is locked and nothing is displayed on screen, when I start typing to unlock the computer, I need to wait the xscreensaver window to start typing my password.

On 4.1, I was able to start typing my password immediately.

This is really annoying, because you can mistype your password multiple time in a row and get crazy wondering why it's failing :sweat_smile: 

### Steps to reproduce

- lock the screen
- type your password

### Expected behavior

You only have to type the password to unlock the screen, and it won't fail.

### Actual behavior

You need to type a random charactacter and wait the xscreensaver GUI to be displayed to actually start typing the password.

**Comment by marmarek** [comment]
Yes, that's (unfortunate?) change in the new xscreensaver version, due to its vastly improved architecture security-wise (handling of the authentication prompt was split into separate process, it's started only when the prompt is shown, so characters pressed before that are not considered).
If that's bothering you enough, I guess you can send a feature request to xscreensaver maintainer, but IMHO it isn't a big issue and it's pretty easy to get used to it.
