### ISSUE TITLE
In-place upgrade from 4.1 to 4.2-RC2 creates `qubes.Input*.rpmsave` files, preventing boot after `--all-pre-reboot` stage

### ISSUE THREAD

**Issue by rapenne-s** [QubesOS/qubes-issues#8480]
### Qubes OS release

In-between 4.1 and 4.2-RC2

### Brief summary

I followed the upgrade guide from 4.1 to 4.2, after the `--all-pre-reboot` stage which finished correctly, the next reboot, after Qubes OS asking my LUKS passphrase, the plymouth theme is displayed and stay stuck.

Removing plymouth display output lot of text but nothing meaningful.

### Steps to reproduce

Run `qubes-dist-upgrade --all-pre-reboot`, wait and reboot the system.

(this worked on another computer though)

### Expected behavior

It boots as usual

### Actual behavior

Qubes OS can't be used.

I gathered the system logs from another system.

[log.txt](https://github.com/QubesOS/qubes-issues/files/12506204/log.txt)

**Comment by rapenne-s** [comment]
Some progress, after switching the NVIDIA graphics card for an AMD, I have some display, but no USB keyboard

**Comment by aronowski** [comment]
From the attached logs I can see an exception regarding `qubes.InputKeyboard`. Not a Python expert by any means, but apparently some file couldn't be opened by `qrexec-policy-daemon`.

I have some guesses, what that might be, but let's try and diagnose it.

1. Does the policy file described in the [USB qubes document](https://www.qubes-os.org/doc/usb-qubes/#manual-setup-for-usb-keyboards) exist?
2. Does it have the `sys-usb dom0 allow` entry by default?
3. If so and still the keyboard does not work, maybe for some odd reason it couldn't be read, despite the fact [the legacy policy format should take precendence over the new format](https://github.com/QubesOS/qubes-issues/issues/8000)? Maybe booting a live system, decrypting the drive, chrooting into the Qubes OS 4.2 installation and running @marmarta's [*qrexec-legacy-convert*](https://github.com/QubesOS/qubes-core-qrexec/pull/123) script would solve this?

**Comment by rapenne-s** [comment]
I just found and solved the issue.

In `/etc/qubes-rpc/policy` I had two files:

- `qubes.InputKeyboard.rpmsave`
- `qubes.InputMouse.rpmsave`

I removed the `.rpmsave` suffix and it's working again.

So I had two issues in the upgrade, the NVIDIA card not working at all anymore and the `.rpmsave` suffixes added :/

**Comment by rapenne-s** [comment]
In the global configuration manager, in the USB devices tab, there is a warning: "Custom policy changes found. The changes below may be overwritten by existing custom policy changes. View the files listed below to verify the existing policy".

I'm not sure I need to toggle keyboard and mouse from disable to enable because my configuration works, but I wouldn't like these knobs to remove the files.

Here is the content of `qubes.InputKeyboard`

```
sys-usb dom0 allow
$anyvm $anyvm deny
```

and in `qubes.InputMouse`


```
sys-usb dom0 allow
sys-usb dom0 ask,user=root,default_target=dom0
$anyvm $anyvm deny
```

**Comment by aronowski** [comment]
While I don't have my test laptop with 4.2 to confirm this, I can see [a screenshot](https://github.com/QubesOS/qubes-desktop-linux-manager/blob/3e6305098611a76f40f659deb8775fc57b885a4d/images/global_settings_usb_1.png) in the `qubes-desktop-linux-manager` repository, that describes this occurence.

![](https://raw.githubusercontent.com/QubesOS/qubes-desktop-linux-manager/3e6305098611a76f40f659deb8775fc57b885a4d/images/global_settings_usb_1.png)

Furthermore, according to the [Development_documentation.md](https://raw.githubusercontent.com/QubesOS/qubes-desktop-linux-manager/3e6305098611a76f40f659deb8775fc57b885a4d/Development_documentation.md) file in there, there should be a file whose name starts with `50-config` that takes care of this in regard to the new policy files. From what I can see from the source code, it is most likely named just `50-config-input` or `50-config-input.policy`. Once such a file is found, the policy 'disable'/'deny' shall go unused, since the legacy files take precedence.

So, if you're feeling adventurous, edit the new policy files via the 4.2 *Qubes OS Global Config* utility first, enabling mouse and keyboard, then rename the file `/etc/qubes-rpc/policy/qubes.InputMouse` to e.g. `/etc/qubes-rpc/policy/qubes.InputMouse.disabled`, so it acts as a backup as well, and reboot the machine.

- If both keyboard and mouse work, go ahead and repeat this step for `qubes.InputKeyboard` too.
- If, for an unknown reason, the mouse does not work, log in with your keyboard and restore the legacy `qubes.InputMouse` file.

Please keep in mind that, as mentioned earlier, I'm operating with clues only right now, as I don't have 4.2 with me to test this out, so I'm not promising anything.

**Comment by DemiMarie** [comment]
@rapenne-s: were you using Nouveau or proprietary Nvidia drivers?  Proprietary drivers are not tested or supported, and while nouveau ought to work, it has generally been quite buggy.

**Comment by andrewdavidwong** [comment]
> So I had two issues in the upgrade, the NVIDIA card not working at all anymore and the `.rpmsave` suffixes added :/

Since [every issue must be about a single, actionable thing](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing), do you mind if we split these into two separate issues? I know that you had no way of knowing it would turn out to be two things in advance, so I'm not faulting you, but it's going make things a lot harder if we try to continue on with this issue being about two separate things. I know it's unfortunate, since there are already comments pertaining to both separate things on this issue, but sometimes that's the way it goes.

So far, it looks like most of the comments here are about the RPC policy problem, so I'm going to re-title this issue to be just about that, and I encourage you to open a separate issue (if one doesn't already exist) for the Nvidia problem.

**Comment by rapenne-s** [comment]
> So far, it looks like most of the comments here are about the RPC policy problem, so I'm going to re-title this issue to be just about that, and I encourage you to open a separate issue (if one doesn't already exist) for the Nvidia problem.

sure, no problem

**Comment by marmarek** [comment]
This is fixed already in https://github.com/QubesOS/qubes-dist-upgrade/commit/e727b152640e497d1d73ffaf99f6213c6a88fef5
