### ISSUE TITLE
No display after stage 1-3 upgrade from 4.1 to 4.2-RC2 (nvidia related)

### ISSUE THREAD

**Issue by rapenne-s** [QubesOS/qubes-issues#8486]
### Qubes OS release

In-between 4.1 and 4.2-RC2

### Brief summary

I followed the upgrade guide from 4.1 to 4.2, after the --all-pre-reboot stage which finished correctly, the next reboot, after Qubes OS asking my LUKS passphrase, the plymouth theme is displayed and stay stuck.

Removing plymouth display output lot of text but nothing meaningful.

I had an NVIDIA 1060 card running the nouveau driver, swapping it with an AMD RX 480 made it work again.

### Steps to reproduce

Run qubes-dist-upgrade --all-pre-reboot, wait and reboot the system.

### Expected behavior

It boots as usual and I can get to the login prompt

### Actual behavior

After asking the LUKS passphrase, I'm stuck on the Qubes OS plymouth splash screen.

**Comment by rapenne-s** [comment]
> @DemiMarie said: @rapenne-s: were you using Nouveau or proprietary Nvidia drivers? Proprietary drivers are not tested or supported, and while nouveau ought to work, it has generally been quite buggy.

I was using nouveau, I gave up at using the proprietary drivers because I had to recompile at every kernel updates, and it didn't change much.

I tried to blacklist the nouveau driver, this didn't help.

The system had a stock xorg configuration.

**Comment by DemiMarie** [comment]
What kernel version were you using before the upgrade, and what version did you have afterwards?  This seems like a Nouveau regression to me, which I have run into in the past.  I recommend reporting it: <https://nouveau.freedesktop.org/Bugs.html>.

**Comment by rapenne-s** [comment]
Everything should be in this log :) 
https://github.com/QubesOS/qubes-issues/files/12506204/log.txt

I tried to add rd.driver.blacklist=nouveau, this used to work fine by just not using nvidia or nouveau at all (defaulting to vesa I guess?) without any luck

**Comment by DemiMarie** [comment]
@rapenne-s can you report this to Nouveau?  I’m pretty sure nobody who works on Qubes OS has any idea how to fix a Nouveau kernel driver regression.  I know I don’t.

Closing as “not our bug” (the Qubes OS Project does not maintain the code causing this bug).

**Comment by rapenne-s** [comment]
Are you sure it's a nouveau regression? Blacklisting the nouveau driver like I did should have temporarily solved the issue if so, right? :thinking:

**Comment by DemiMarie** [comment]
> Are you sure it's a nouveau regression?

Nope :smile:.  I have had Nouveau regressions before, though, so that was my first thought.

> Blacklisting the nouveau driver like I did should have temporarily solved the issue if so, right? 🤔

It should have, provided that:

1. The module was blocked via the kernel command line (changes to `/etc/modprobe.conf` might not have made it into the initramfs).
2. Blocklisting the nouveau driver worked with the older kernel.
3. The vesa driver actually worked with the new userspace.

> If I gather enough motivation, I could try to swap the card again and see if it displays something now I'm on RC3

I don’t think there have been any changes from RC2 to RC3 that would impact this.  More useful would be some information about what you were using before the upgrade, specifically:

1. What kernel version were you using under R4.1?  If you were using the same kernel version then this isn’t a kernel regression.
2. Can you go back to the kernel you were using under R4.1?  This should be possible with `qubes-dom0-update`; you might need to pass `--action=downgrade` or otherwise fiddle with the command line options.  If the previous kernel works than this _is_ a kernel regression.
3. Can you try a 6.1.x kernel (`kernel` package instead of `kernel-latest`)?  If that fixes things then this is a kernel regression.
4. Are you using the `modesetting` Xorg driver?
5. Do you have all of the relevant firmware packages installed in dom0?

**Comment by rapenne-s** [comment]
1. I used `rd.driver.blacklist=nouveau` which prevents nouveau to be loaded (it was required for when I used the proprietary driver)
2. yes
3. yes

New GFX card today :partying_face: (not an nvidia :smiling_imp: ) as I got my hands in the thing, I've tried the nvidia card again with a fully working 4.2-RC3 and I still had the issue.

I'd prefer to give up, I don't want to fiddle much with downgrading the system right now, and it's way too boring for something that may be just specific to my computer.
