### ISSUE TITLE
Launch first search result when pressing Enter in new app menu

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8662]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

After opening the new app menu, one can begin typing to start searching through available qube shortcuts. However, even when the first result is the one desired, one cannot simply press Enter in order to launch it. Instead, one must press the down arrow first, then press Enter (or click on the first result).

### The solution you'd like

When doing a text search in the new app menu, pressing Enter launches the first result.

### The value to a user, and who that user might be

Improves convenience and quality of life for users who prefer to use the new app menu with only the keyboard.

**Comment by UndeadDevel** [comment]
If I may add a nit-pick for this: while the feature works, it would be nice if `Down arrow` now selected the second item instead of the first, as the first can now already be launched by pressing `Enter`; this is not just for convenience but also to remove superfluous actions (the first `Down arrow` now has no meaningful effect) and reduce confusion as on first glance the first item now does look like it's already selected (on second glance one can notice that a selection would be slightly brighter and have the little border, but UX wise that's IMO too subtle a difference).
