### ISSUE TITLE
qubes-dom0-update lies to the user by claiming no updates are available when the update check actually failed

### ISSUE THREAD

**Issue by no-usernames-left** [QubesOS/qubes-issues#8669]
### Qubes OS release

4.1.2

### Brief summary

When an update check fails, `qubes-dom0-update` claims `No updates available` even though it was not able to ascertain anything of the sort.

### Steps to reproduce

#8482 or #8667

### Expected behavior

Output analogous to "There was an error checking for updates" (and ensuring the exit code is nonzero for good measure).

### Actual behavior

Claims there are no available updates (exit code not checked).

**Comment by andrewdavidwong** [comment]
This is basically the same as https://github.com/QubesOS/qubes-issues/issues/6585, except for `qubes-dom0-updates` instead of Salt.

**Comment by andrewdavidwong** [comment]
@no-usernames-left, the output you report does not seem to match what others reported in #8482 or even what you reported in #8667. In both cases, an error message was reported, except for the last snippet in https://github.com/QubesOS/qubes-issues/issues/8482#issuecomment-1758167606, from what I can tell. If I understand correctly, the relevant case for this issue is if an update fails but there is *no* error message of any kind. It should look the same when there are simply no updates available but the check succeeds. What exact output do you receive?

**Comment by rustybird** [comment]
> There is an Xterm (with a different colour window border because untrusted) which pops open and displays an error, but at the end of the process the updater in `dom0` itself will falsely report that no updates are available.

That's one of the reasons R4.2 switched to showing UpdateVM messages as part of `qubes-dom0-update` output by default (instead of in a terminal popup window), see #8015.

You can get the new behavior on R4.1 too by using `qubes-dom0-update --console --show-output`

**Comment by marmarek** [comment]
So, to add to xterm approach issues, it also eats exit code of the process inside? If that's the case, the easiest fix would be to switch back to no-xterm in R4.1 too, but it's a significant behavior change (for example when started from qubes manager, download progress won't be visible anymore), so probably a bad idea. But surely there is some alternative solution to preserve the exit code (temp file, if nothing else...).
