### ISSUE TITLE
DispVMs based on DVM template with default value of `default_dispvm` always have the DVM template itself as `default_dispvm`

### ISSUE THREAD

**Issue by emanruse** [QubesOS/qubes-issues#8680]
### Qubes OS release

4.1.2

### Brief summary

Setting `default_dispvm` to the default value (the one set through Qubes Global Settings, section "qube defaults") for DVM templates results in DispVMs always having the DVM template itself as their `default_dispvm`.

### Steps to reproduce

1. In Qubes Global Settings, set disposable template = minimal-offline-dvm.

2. Create an AppVM, making it a DVM template (e.g. TEST-dvm), setting its default_dispvm = (default) minimal-offline-dvm.

3. Start a disposable based on TEST-dvm (e.g. disp123).

### Expected behavior

disp123's `default_dispvm` should be minimal-offline-dvm (as set).

### Actual behavior

disp123's `default_dispvm` is TEST-dvm.

#### Additional notes:

To have TEST-dvm based disposables have the desired `default_dispvm`, it must be set explicitly to "minimal-offline-dvm", not to the "(default) minimal-offline-dvm". Only then it works as expected.

[Discussion](https://forum.qubes-os.org/t/whonix-ws-16-dvm-ignores-default-dispvm-template/21267/)

Edit: typo

**Comment by rustybird** [comment]
It's intentional: https://github.com/QubesOS/qubes-core-admin/commit/89624525029bcc7382a7f1ea1c2af5d6d99bb29c

**Comment by rustybird** [comment]
> 1. Receive a malicious email attachment in AppVM "my-mail"
> 2. Save the file in some folder and run "View in VM" for it

"View in DisposableVM", right?

> Result: The file is opened in a DispVM which has the same network connectivity as "my-mail"

No, this would respect my-mail's default_dispvm if explicitly set or fall back on the system-wide default_dispvm otherwise, because the DisposableVM is spawed by an AppVM. The quirk only applies if a DisposableVM is spawned by a DisposableVM.

It would be possible apply this quirk even more narrowly, to only DisposableVMs spawned by a DisposableVM with auto_cleanup==True (e.g. by a disp1234 but not by a disposable sys-usb)

**Comment by rustybird** [comment]
Basically a tradeoff between two possible misconfigurations. The current behavior does seem like the lesser evil to me, but it's unintuitive and undocumented.

Besides improving the docs/UI, I wonder if (in the implicit case) we should also set the child DisposableVM's netvm to None? That doesn't look completely trivial to implement though.

**Comment by adrelanos** [comment]
`default_disvm` -> `default_dispvm`? Please edit.

related:
https://forum.qubes-os.org/t/whonix-ws-16-dvm-ignores-default-dispvm-template/21267

**Comment by andrewdavidwong** [comment]
It looks like this was part of the resolution for [QSB-47](https://www.qubes-os.org/news/2019/02/19/qsb-47/):

> [...]
> 
> To mitigate this problem, we are implementing two changes:
> 
> 1. When a DisposableVM is started, automatically set its
>    `default_dispvm` to the DVM Template on which it is based. This means
>    that, when a DisposableVM is started from another DisposableVM, they
>    will both be based on the same DVM Template. Hence, they will have
>    all the same settings, including the same network settings. This
>    change will not affect DVM Templates for which user has manually
>    modified the `default_dispvm` property.
> 
> [...]

**Comment by andrewdavidwong** [comment]
@emanruse: The second part is off-topic for this issue. [Every issue must be about a single, actionable thing.](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing) Please feel free to open a separate issue for that, if one doesn't exist already.

**Comment by andrewdavidwong** [comment]
> @emanruse: The second part is off-topic for this issue. [Every issue must be about a single, actionable thing.](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing) Please feel free to open a separate issue for that, if one doesn't exist already.

Opened #8688 for this.

**Comment by ben-grande** [comment]
> Please kindly note that the user has understood and has also shown that this intention may not match the overall OS's intent of security. Additionally, it was shown that this intentional design is confusing and misleading, unless one is specifically educated about it (which is not the general case).

I agreed with you it is misleading the way it is treated in the preferences list and the qube manager. The fix is not however a regression, but showing the disposable template it is actually going to use.

> When you say "it is more intuitive", is this a fact or an opinion?

Opinion.

> I am asking because it is a major UI design principle to have the interface reflect actuality (facts), not designer's gut feeling. If the UI says global default_dispv=X, then it must be X by default and nothing else. If special UI hints, documentation etc. are necessary to explain that "even if set to X, this doesn't mean it is always X, only in cases when... and in other cases ..." this is not adding clarity, it is just reaffirming the poor design. A good and secure design is simple, straightforward, and needs no clarifications - "Walk/Don't walk".

I agree the UI should reflect the facts, currently they don't. The fix however is to show the facts, not to revert to use the global disposable template.

- TemplateVMs default netvm is actually none: `default (n/a)`.
- Disposable Templates should have the default dispvm: `default (ITSELF)`.

Where itself is the actual disposable template name.

In both cases, it needs explanation to why it is happening, why templates are non networked, it is documented. What is not documented is the disposable template of a disposable template default setting and its preference and manager counterpart.

> So, if what you say about intuitive is a fact, it should come with proper verifiable evidence. Personally, I could not speak for other's intuition without actual statistical data from test cases.

> If it is an opinion, and if community's voice matters, here is another opinion too: when one installs a security focused OS, one expects security by default, not complicated paths to it, allowing insecurities in-between.

I agree the paths should be easy. You are however biased on using a disposable based on a disposable template of the setting of the disposable template of itself. This is advanced usage and no normal user does this. This is a complicated path. Non-advanced users don't open disposables from disposables.

> I understand you are willing to stop this discussion by enforcing this viewpoint, however please note that this would contradict everything explained above.

We agree the current UI doesn't reflect the reality.
We disagree on the outcome.
