### ISSUE TITLE
rename/fork base distributions such as Debian, Fedora for trademark compliance and to avoid confusion

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#8730]
Qubes official Templates should not use the original names of the base distributions such as `Debian` or `Fedora`.

Quote myself from https://github.com/QubesOS/qubes-issues/issues/2238#issuecomment-546984756

> We can't or shouldn't harden Debian (much) since the result wouldn't be a Debian template with only necessarily modifications to integrate with Qubes. That would be a fork of Debian. Debian is a trademark.
>
> https://www.debian.org/trademark
>
> Forks of Debian shouldn't be called Debian to avoid confusion.

Quote [Debian wiki, Derivatives Guidelines chapter Trademark](https://wiki.debian.org/Derivatives/Guidelines#Trademark):

> Derivative distributions must not be named Debian :)

What the Qubes Debian template is, isn't really Debian. It's a fork of Debian. A Debian Derivative.

Qubes already derivatives a lot from Debian:

* https://github.com/QubesOS/qubes-issues/issues/5367
* additional hardening (for example `/etc/profile.d/zqubes_disable_lesspipe.sh` by qubes-core-agent)
* lots of systemd drop-in files (to see, use `dpkg-query -L qubes-core-agent | grep service.d`)

How do I even discuss a Qubes Debian template with a real Debian installed on hardware in some Qubes aware place (issues, forums)? Then I invent terminology such as "a real (non-Qubes) Debian bookworm". This is to show the confusion that is already reached.

Further Qubes plans to derivative from distribution culture:

* https://github.com/QubesOS/qubes-issues/issues/2238 - I agree with that ticket. Services not starting by default is cleaner, saves system resources and is more secure, however that shouldn't be called Debian since Debian starts most installed services by default, has the opposite policy.
* https://github.com/QubesOS/qubes-issues/issues/1885

Related Qubes FAQ: [What is Qubes’ attitude toward changing guest distros?](https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros). The policy of respecting distribution policy is in direct conflict with Qubes making changes for customization (selected default installed packages), usability (Qubes tools integrations) and security hardening.

If this bug report gets accepted,

* I suggest to create dedicated tickets or discussions for names of the forked Linux distributions separately.
* Keeping this ticket limited to policy/goal question of "should we do this". Technical steps required might require sub tickets.

Fork in this context as used in the title only means to rename for example the Debian template to something else and updating the Qubes documentation. No other gigantic steps (such as forking all of Debian archive `packages.debian.org`, re-building all the Debian archive are suggested. Only acknowledgement that it is a fork of Debian, based on Debian, but not the original Debian.

**Comment by SolarSorcerer** [comment]
Should also keep in mind the trademark of the desktop environment you might be using.

In this use case I will use gnome as a example.
[Here is GNOME's trademark policy](https://foundation.gnome.org/logo-and-trademarks/)
[Here is GNOME's software policy](https://wiki.gnome.org/Foundation/SoftwarePolicy)

Here is a quote that might pertain to QubesOS's template names.

"Software projects which are included in GNOME Circle are not official GNOME software. As such, they cannot use the GNOME trademarks to identify themselves."

**Comment by marmarek** [comment]
A Debian template is not a separate/derivative distribution, it's a Debian installation into a disk image made to work under Qubes OS. Essentially it isn't much different than any other VM "template". You can choose Debian/Fedora/whatever in AWS, OVH, Rackspace etc, you will get pre-installed Debian, with added modifications to integrate with that environment - for cloud services it's usually mechanism to configure the network, provision SSH keys, and few others. Sometimes you can also choose a version with extra software from 3rd-party repositories installed (like, WordPress, various databases etc). In Qubes it's a bit more due to integration with graphical environment running in dom0. But none of it makes it any less Debian.

> Further Qubes plans to derivative from distribution culture:
>
> https://github.com/QubesOS/qubes-issues/issues/2238 - I agree with that ticket. Services not starting by default is cleaner, saves system resources and is more secure, however that shouldn't be called Debian since Debian starts most installed services by default, has the opposite policy.
> https://github.com/QubesOS/qubes-issues/issues/1885

Those are in fact great examples. As you can see, in both cases we in fact did _not_ include them, and in the first case it's even explicitly discussed if that wouldn't be against what Debian is.

---

What might be misleading, is naming templates with "gnome", "xfce" etc. Because it isn't really full _running_ desktop environment there, but it's  just about packages set installed there. But those are still matching what you'd get by choosing GNOME/XFCE etc when installing Debian (or Fedora for that matter):
 - https://github.com/QubesOS/qubes-builder-debian/blob/main/template_debian/xfce/02_install_groups_packages_installed.sh#L12
 - https://github.com/QubesOS/qubes-builder-debian/blob/main/template_debian/gnome/02_install_groups_packages_installed.sh#L12

But then, if you install "Debian with GNOME" and then use only specific applications from there (for example via X11 forwarding over SSH, or similar mechanism), it's still "Debian with GNOME", even though you never run GNOME there. Similarly, you can run `gnome-terminal` under Xfce, I3 or any other desktop environment (which in Qubes OS in fact runs in a different VM). So, maybe it isn't really an issue.

**Comment by DemiMarie** [comment]
> A Debian template is not a separate/derivative distribution, it's a Debian installation into a disk image made to work under Qubes OS. Essentially it isn't much different than any other VM "template". You can choose Debian/Fedora/whatever in AWS, OVH, Rackspace etc, you will get pre-installed Debian, with added modifications to integrate with that environment - for cloud services it's usually mechanism to configure the network, provision SSH keys, and few others. Sometimes you can also choose a version with extra software from 3rd-party repositories installed (like, WordPress, various databases etc). In Qubes it's a bit more due to integration with graphical environment running in dom0. But none of it makes it any less Debian.
> 
> > Further Qubes plans to derivative from distribution culture:
> > #2238 - I agree with that ticket. Services not starting by default is cleaner, saves system resources and is more secure, however that shouldn't be called Debian since Debian starts most installed services by default, has the opposite policy.
> > #1885
> 
> Those are in fact great examples. As you can see, in both cases we in fact did _not_ include them, and in the first case it's even explicitly discussed if that wouldn't be against what Debian is.

We have not included them _yet_, but I was not aware of a final decision here, especially since both issues are still open.  To me, the main argument for #2238 is simply that a TemplateVM is in a quite different situation than most systems.  It makes little sense to have nginx installed if one does not intend to use it, but in the case of Qubes OS, one probably wants to use nginx in an AppVM or DisposableVM, not the TemplateVM!  And my understanding regarding #1885 is that security-misc is a bunch of configuration changes that could just as easily be done by hand.

**Comment by adrelanos** [comment]
Qubes making editorial decisions which packages are included by default and which ones's aren't in Qubes Debian Templates by default:

* https://github.com/QubesOS/qubes-issues/issues/8980

Qubes has been added to the list of [Debian derivatives census](https://wiki.debian.org/Derivatives/Census) since 2017:

* https://github.com/QubesOS/qubes-issues/issues/1834

Qubes wiki page in the Debian wiki:
[Derivatives/Census/Qubes](https://wiki.debian.org/Derivatives/Census/Qubes)

Related decisions for the derivative (or in-decisions):

* https://github.com/QubesOS/qubes-issues/issues/10744

**Comment by h01ger** [comment]
as a Debian developer and member I would find it confusing not to call the Debian templates Debian templates.

Same goes for other distros.
