### ISSUE TITLE
Error message sometimes missing when inter-qube file copy/move fails due to disallowed characters in filename

### ISSUE THREAD

**Issue by xqb34** [QubesOS/qubes-issues#8738]
### Qubes OS release
4.2.0
Installed RC4 and installed updates since then.

### Brief summary
As discussed in #8332 , copy/move files can fail when there are non-english characters, and that is an intended behavior.

However, copy/move sometimes fails _without_ any warning message, which can result in loss of data. 

### Steps to reproduce

Create a file named  عربية or עברית, e.g. `touch عربية` or `touch עברית`.
From the file manager, choose copy to other appVM.

### Expected behavior
File is copied or an error message is presented.

### Actual behavior
File not copied and no error message is displayed to user.

I haven't checked if command line provides any error indication, but if it does not, it would create issues with automatic scripts.

As side note, I am sure that the choice to have strict file name validation has been debated. I personally find that it damages usability (even if there is an error message) because user have existing files and receive files from others. I am sure that there are good security reasons for the choice.

**Comment by jamke** [comment]
Was my message, that included proposal to change Expected behavior section, deleted from this issue?

**Comment by marmarek** [comment]
The main reason for this filtering is that font renderers have security issues related to rendering complex characters. This includes compound characters, but also right-to-left text, especially when mixed with left-to-right. Those are not _very_ common issues, but they do happen from time to time. It would be bad if one qube can completely take over another by having you to copy specially-named file and then let you list the files there...

That said, the current experience definitely should be improved, including:
 - better error reporting ("Invalid or incomplete multibyte or wide character" message is misleading...)
 - an option to allow specific characters set, accepting the risk, but without disabling the whole filter completely

**Comment by jamke** [comment]
> an option to allow specific characters set, accepting the risk, but without disabling the whole filter completely

But what will be still enabled? Will it be possible to simply, reliable and properly copy files as `cp` does? 
What about symlinks in general, is it possible to avoid copy failing because of them and copy `as is` (as `cp` does)?

**Comment by marmarek** [comment]
@jamke it sounds like a misconception of what qvm-copy tool is. It's primary purpose is to _securely_ copy files. That goal may require rejecting some. The version in R4.2 does a better job at protecting target qube than the version in R4.1. Especially qvm-copy is **not** supposed to preserve every potentially malicious file source tries to send. This was quite well explained already in https://github.com/QubesOS/qubes-issues/issues/8581#issuecomment-1753468524

**Comment by xqb34** [comment]
> @jamke it sounds like a misconception of what qvm-copy tool is. It's primary purpose is to _securely_ copy files. That goal may require rejecting some. The version in R4.2 does a better job at protecting target qube than the version in R4.1. Especially qvm-copy is **not** supposed to preserve every potentially malicious file source tries to send. This was quite well explained already in [#8581 (comment)](https://github.com/QubesOS/qubes-issues/issues/8581#issuecomment-1753468524)

I don't know the security considerations well enough to comment on that, but this does create a serious usability issue.
I think that one target audience is journalists - is this convenient for a journalist receiving data that they want to read on some project/disconnected/disposable VM?

Would it make sense to have a "qvm-copy --insecure" tool/option (including in the file manager)?
Or perhaps "qvm-copy --rename-to-uft8" (if it is possible to infer the correct locales for renaming)?
Is there a good existing tool that can be used for the renaming? It would useful in general, but could be very useful to integrate it with the menu option in the file manager, which might resolve the usability issue.
Unfortunately, I think that there would need to be both the "traditional" and the "rename to utf8" options, again to maintain user control over data integrity.
The main downside (other than work that goes into this) would be a bloated menu, which I agree is not super great.

Should we split this to a separate issue, as changing the behavior is not the same as fixing the missing error messages?

**Comment by jamke** [comment]
> Would it make sense to have a "qvm-copy --insecure" tool/option (including in the file manager)?

I think it definitely would!
I understand what you are saying, I just think consequences can be worse, than what's gained, at least in my use cases. Because `qvm-copy` is already "secure", and the filtering is like adding additional layer. Like: why not check copied files with antivirus, or block copying shell/ELF files or something, it all looks as the same approach that copy tool should do to be called secure.

For me secure is more like: 
* for any directory/file it does not cause any code execution itself because of the file naming or data (like buffer overflow or bad parsing code),
* for any directory/file it should not cause user data losses (or increase changes of it); other meaning of secure as in `safe`.

The R4.1 meets these criteria completely.

-----

**My main point**:
After these changes the user will never be sure if Qubes OS copy tool will work as they expect:

* User moves a directory with a big size, goes to drink tea or even sleep, comes back and sees that there is an error about symlink or filename that happened in the beginning of the process.
* After that user can remove this symlink or tar it and start again, once again not being sure that it will not stop in a minute, or an hour.
* If user is able to auto-skip such files, than they will almost certainly loose some files eventually. At least I would.

> Should we split this to a separate issue, as changing the behavior is not the same as fixing the missing error messages?

Both ways are fine with me, as I considered this issue to be not only about the message but about inability to copy Arabic/Jewish filenames. Should I create a separate issue about what I described above?

**Comment by jamke** [comment]
My bad, I though the last reply from @xqb34 was from @marmarek .

**Comment by rustybird** [comment]
Could we keep this ticket focused though...

> Create a file named عربية or עברית, e.g. `touch عربية` or `touch עברית`.

Just so we're all on the same page, in a Bash shell that should be identical to `touch $'\330\271\330\261\330\250\331\212\330\251'` and `touch $'\327\242\327\221\327\250\327\231\327\252'` respectively?

**(1) What's the sticking point with these strings?**

I've tried a few online Unicode analyzers such as https://unicodedecode.com/ and they both seem to be valid UTF-8, made of ordinary(?) Arabic or Hebrew letters, without directionality changes or embedded right-to-left markers.

> From the file manager, choose copy to other appVM.

> File not copied and no error message is displayed to user.

**(2) The filecopy GUI should surface this error to the user.**

**Comment by DemiMarie** [comment]
@marmarta does this fall under “bad UX is bad security”?
