### ISSUE TITLE
"qrexec not connected" warning flag not cleared despite qrexec later connected ok

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#878]
**Reported by joanna on 3 Jul 2014 00:26 UTC**
None

Migrated-From: https://wiki.qubes-os.org/ticket/878

**Comment by ramtej** [comment]
same issue here. Any ideas ?

**Comment by unman** [comment]
@andrewdavidwong Haven't been able to test this - please change milestone to 3.2

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
