### ISSUE TITLE
In-place upgrade from 4.1 to 4.2 shows error message that it could not find qrexec-legacy-convert

### ISSUE THREAD

**Issue by susurri** [QubesOS/qubes-issues#8781]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

In-place upgrade from 4.1 to 4.2 shows error message that it could not find qrexec-legacy-convert

### Steps to reproduce
follow the https://www.qubes-os.org/doc/upgrade/4.2/ steps and

sudo qubes-dist-upgrade --all-post-reboot

### Expected behavior

qubes-dist-upgrade shows no error message

### Actual behavior

qubes-dist-upgrade shows error message that it could not find qrexec-legacy-convert

**Comment by xaki23** [comment]
partial diag. (since this came up on various qubes related chats in the last days)

qrexec-legacy-convert is supplied by pkg qubes-core-qrexec.
but according to https://github.com/QubesOS/qubes-core-qrexec/ this is only present in the q4.2 version of the pkg.

whether it should be present in q4.1 version too, or the q4.2 version should already be installed at the time it is being called, or the call is simply to early ... i dont know. 

@marmarek ?!

**Comment by verygreen** [comment]
I just hit this.

The problem in my case is:
when running `qubes-dist-upgrade --all-pre-reboot` several qube templates failed to update for various reasons.
That aborted the whole execution of the dist-upgrade with exit code 20 without clear indication that phases 2 and 3 were not executed.

so post reboot you run the post-reboot phases while dom0 remains on 4.1 (you can see in /etc/os-release it still says 4.1.2 or such)

In my case I had to return dist-upgrade -r followed by -s to execture the actual phase 2 and 3
(phase3 failed because out of space - so definitely watch that too and free up space as needed)

todo (I'll update the progress as I am still on phase 3, will update once I moved on)
and then I had to manually run phases 5 and 6 (phase 5 also silently failed in because qvm-features-request failed)

What I think needs to be done:

1. A *very* visible message to the dist-upgrade combined pre-reboot option if not all phases executed
2. Post-reboot phases should check os-release to ensure dom0 is already on 4.2 (or whatever the expected release is) before commencing with further changes and if not it should exit with the diagnostic that prior requires phases did not run.

**Comment by marmarek** [comment]
@fepitre since you touch dist-upgrade already, can you add also relevant check to later phases if earlier completed? Specifically, steps 4 and 5 should check if dom0 is 4.2 already (by looking at /etc/os-release?)
