### ISSUE TITLE
Disconnecting and reconnecting a VM from sys-whonix or forcing a restart of sys-whonix does not return connected VMs to sdwdate-gui widget

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8798]
### Qubes OS release
4.2, Whonix 17
(also occurred on 4.1.2 with Whonix 16)

### Brief summary
Forcing a `sys-whonix` restart via Qube Manager or setting the netVM of a `sys-whonix`-connected qube to "None" and back to `sys-whonix` does not bring those qubes back to the `sdwdate-gui` widget in the tray. Only rebooting those workstations will list them in that widget again.

### Steps to reproduce
Either force reboot of `sys-whonix` or disconnect a connected qube and reconnect it via netVM settings.

### Expected behavior
All qubes connected to `sys-whonix` show up in the `sdwdate-gui` tray widget.

### Actual behavior
Only qubes that were started after `sys-whonix` was started and were never disconnected show up in that widget.

**Comment by adrelanos** [comment]
Confirmed.

Qubes doesn't support restarting the Net qube. When attempting to poweroff a Net qube that is currently in use, Qubes prompts to shut down the other VMs.

Fixing this issue would require a redesign for sdwdate-gui-qubes. Mentioned this here just now:
https://forums.whonix.org/t/sdwdate-gui-for-qubes-testers-wanted-developers-welcome/5469/30

But even then specifically fixing this issue is hard to implement. Patches welcome.

I don't think I'll get to implement this and contributions are rare too. So realistically...

Can be closed as "not planned".

**Comment by UndeadDevel** [comment]
Alright yeah that sounds like a lot of work for a relatively minor issue; I do want to note, however, that the new updater does routinely force restart `sys-net` and `sys-firewall` as well as `sys-whonix` after successful updates, so that's part of the standard functionality of QubesOS and this issue also occurs when disconnecting and reconnecting tor workstation qubes and in some other situations (e.g. #8797 as you point out there). I'll leave it to @andrewdavidwong to close.

**Comment by UndeadDevel** [comment]
Curiously, I've noticed that after entering and leaving stand-by, the missing VMs do return to the widget...leaving this here for anyone who finds this issue in the future.
