### ISSUE TITLE
Qube Manager 4.2.0 Release Notes stale, incomplete

### ISSUE THREAD

**Issue by Martin-Buchholz** [QubesOS/qubes-issues#8803]
Fresh install of 4.2.0
dom0: Qube Manager -> About -> Release Notes 
shows "Qubes R4.1 release notes" and is incomplete.
Appears to show the contents of 
/usr/share/doc/qubes-release-notes/README.Qubes-Release-Notes

If release notes refresh is too much work to automate, 
I suggest dropping the "Release Notes" button in the GUI or just leaving a reference to 
https://www.qubes-os.org/doc/releases/4.2/release-notes/
or
https://www.qubes-os.org/doc/releases/notes/
which appear well maintained.

**Comment by alimirjamali** [comment]
Title should read: `Qube Manager 4.2.0 Release Notes stale, incomplete`

The file in question is from [qubes-qubes-release](https://github.com/QubesOS/qubes-qubes-release/blob/main/README.Qubes-Release-Notes) repo.

The suggested update is from [qubes-doc](https://github.com/QubesOS/qubes-doc/blob/main/developer/releases/4_2/release-notes.md) repo.

> If release notes refresh is too much work to automate,
> I suggest dropping the "Release Notes" button in the GUI or just leaving a reference to
> https://www.qubes-os.org/doc/releases/4.2/release-notes/
> or
> https://www.qubes-os.org/doc/releases/notes/
> which appear well maintained.

Since the README.md file does not render nice in Qube Manager, the above suggestion sounds reasonable. For the actual file, maybe dropping it from `qubes-qubes-release` would be better than keeping an unmaintained off-line version. Most users would use a search engine to find the online version.

**Comment by alimirjamali** [comment]
@marmarek What to do with the stale `/usr/share/doc/qubes-release-notes/README.Qubes-Release-Notes` file? I could think of the below possibilities:

1. Delete it from [qubes-qubes-release](https://github.com/QubesOS/qubes-qubes-release/blob/main/README.Qubes-Release-Notes) repo.
2. Keep multiple versions per release tag.
3. Keep just one version with link to the website.
