### ISSUE TITLE
Disposable (dispVM) names instead of numbers

### ISSUE THREAD

**Issue by johnnyboy-3** [QubesOS/qubes-issues#8843]
Numbers are great, but names are easier to memorize.
I think it would be more user friendly to use names for disposable VMs, especially when many disposable VMs are in use.
When names run out, Qubes could switch back to the (old) number system.

Proposes:
NATO phonetic alphabet: dispBravo, dispCharlie, dispTango, ...

or others/a mixture of:
Greek alphabet: dispAlpha, dispBeta, dispGamma, ...
Donaters/Partners/Contributers/CoreTeam: dispJoanna, dispMullvad, dispDemiMarie, dispBespredel, ...
Boys/Girls names as in weather/pressure/storms: dispAlex, dispBethanie, ...
Generic words: dispCat, dispDog, dispRain, dispSunshine, ...

**Comment by ben-grande** [comment]
I disagree with the proposal because:

- Number is used because it is easy to get a range from 0 to 999 (1000 qube names).
- Numbers are supposed to be forgotten, not to be remembered, if you want a dispvm for a specific purpose, you can already create a named disposable.
- If random disposable names are used, at some point, it might be similar to a named disposable the user has created, that can make.
- If using names, than the user has to think to not name a dispvm from a thousand names list, that is not user friendly.

**Comment by johnnyboy-3** [comment]
Thanks for your feedback.
Finding proper names seemed quite difficult when I was writing this post I noticed myself.
