### ISSUE TITLE
Support for standard shortcut keys in Qube Manager

### ISSUE THREAD

**Issue by emanruse** [QubesOS/qubes-issues#8871]
### The problem you're addressing (if any)

The home Home and End keys don't work in Qube Manager.
Standard Ctrl+W, Ctrl+Q also don't work for closing the program.

### The solution you'd like

Working standard shortcut keys.

### The value to a user, and who that user might be

Using standard shortcut keys.

**Comment by alimirjamali** [comment]
> The home Home and End keys don't work in Qube Manager.
> Standard Ctrl+W, Ctrl+Q also don't work for closing the program.

Home and End keys work. But not how most people would expect. It goes to first/last column instead of first/last row. People with higher resolution monitors would most probably never recognize it. It is a good suggestion to assign it to vertical action.

Assigning Ctrl+Q to exit is also a good idea. It is currently Alt+F4 (from MS-Windows world).

I will work on the above

What should Ctrl+W do? It is not a tabbed App (at the moment). I believe it would be better to reserve it for future.

**Comment by alimirjamali** [comment]
I also added Ctrl+N to `New qube`. It is standard and nice. I am not sure about Delete, Clone, Start/Resume, Shutdown, Restart, Kill and others.

**Comment by alimirjamali** [comment]
Most of the below shortcuts are in both VMWare player and VirtualBox. But this is just a draft.

![shortkeys](https://github.com/user-attachments/assets/e45745c5-b9b0-4848-b472-37ab659cf4d8)

**Comment by alimirjamali** [comment]
PR Submitted

Review priority: Low

> We should probably be careful about destructive operations like Delete. Accelerating such could have negative effects. Ctrl+R is a somewhat sensitive too. In a lot of software it means "refresh".

After testings and considerations, I decided to only add Ctrl+Q for Exit, Ctrl+N for New, Home & End keys for Scroll to Top & Bottom. VirtualBox, VMWare Player & Libvirt's Virtual Machine Manager do not agree on shortcuts for other actions. It would be up to a UI/UX expert to decide on the proper shortkeys for those actions. Otherwise it won't be possible to satisfy everyone.

> BTW, considering #7619, do you think you could also add e.g. an F5 to refresh disk usage and similar, at least until we have a fix for the other bug? I understand this may be somewhat difficult as there is no button or menu entry for it, so a "no" would be an understandable answer.

Implementing refresh is entirely different. But if it is added, it is a good suggestion to add manual F5 refresh shortcut. I have to looked into the code deep enough yet to see how hard or how easy it would be to implement it.
