### ISSUE TITLE
tmp.mount service always creates 1 GiB mount, not 50% of RAM

### ISSUE THREAD

**Issue by emanruse** [QubesOS/qubes-issues#8888]
### Qubes OS release

4.2

### Brief summary

The size of the tmpfs mount created by tmp.mount systemd service is not 50% of total RAM but always 1 GiB.

### Steps to reproduce

1. Enable the tmp.mount systemd service.
In Debian-12 templates:
```
cp -a /usr/share/systemd/tmp.mount /usr/lib/systemd/system/                     
systemctl enable tmp.mount
```

In Fedora templates `tmp.mount` seems enabled.

2. Run VMs based on these templates (or even run the templates themselves).

3. Check /tmp size, e.g. `df -h /tmp`

### Expected behavior

The size of the tmpfs mount should be 50% of total RAM, because the service file contains the line

```
Options=mode=1777,strictatime,nosuid,nodev,size=50%%,nr_inodes=1m
```

### Actual behavior

The size of the mounted `/tmp` is always 1 GiB.

Doing this manually (or through `/rw/config/rc.local`), e.g.

```
sudo mount -o remount,size=50% /tmp
```

always works as expected.

**Comment by marmarek** [comment]
> `sudo mount -o remount,size=50% /tmp`

That's rather bad idea. It's 50% of RAM at the mount time, it isn't dynamically adjusted later. This means, if you do that during qube startup, you'll get about 200MB of /tmp (in default setup), which is even smaller.

In fact, changing it to 1GB was to avoid various applications crashing due to too small /tmp. It is this way since 2015 and you are the first one to complain. What is the actual problem you are facing? Too small /tmp for something? Or maybe too large (and something eating RAM via filling /tmp)? If you have some very specific use case requiring unusually big /tmp (_and you can assign sufficiently large amount of memory to that qube_), maybe simply increase /tmp in your rc.local (but using explicit size, not percents)?

**Comment by UndeadDevel** [comment]
I'll add that in one case I ran into this: when scanning some documents (many, but less than 100 pages total) the scanning app refused to continue scanning or even save the documents already scanned due to /tmp being full...was a bit of a pain to recover from as I didn't know much about /tmp (I'm not a professional developer), but I would agree that one doesn't run into these situations every day.

**Comment by marmarek** [comment]
> The actual issue here is that 50% in the unit file means 50%, not 1 GiB.

Ah, so your issue is not that default is 1GiB, but that you don't see why 50% in the unit file is ignored? The answer is simple - it's via drop-in file, `systemctl cat tmp.mount` will show you what actually is used. It has a comment explaining why it is the case. In other words, you are looking at wrong file.

> Actually, I do it through a script which "intelligently" determines the amount of free RAM and sizes /tmp based on that, so that neither writing too much to /tmp will reduce available memory, nor /tmp is too small. But I suppose my own customizations are off-topic.

Yes, for specific cases I would expect some customization could be needed. For some, even the 50% of max RAM could be too little.

BTW, we have considered sizing it based on the "maxmem" setting, but that was a bad idea too: with default 4GiB maxmem, you'd get 2GiB /tmp, and you can easily have a VM that does not reach 2GiB assigned memory, so this size of /tmp would easily cause OOM.
