### ISSUE TITLE
Audio underruns in dom0 soon after uncorking stream

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8955]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Immediately after uncorking a stream, `pacat-simple-vchan` in dom0 reports an underrun.

### Steps to reproduce

Start playing audio.

### Expected behavior

`pacat-simple-vchan` reports no underruns.

### Actual behavior

- If the PulseAudio server is `pipewire-pulse`, then `pacat-simple-vchan` reports a single underrun.  This is fixed by QubesOS/qubes-gui-agent-linux#207.
- If the PulseAudio server is `pulseaudio`, then `pacat-simple-vchan` [reports many underruns for several minutes](https://github.com/QubesOS/qubes-gui-agent-linux/pull/207#issuecomment-1954899868).  This is _not_ fixed by QubesOS/qubes-gui-agent-linux#207.

**Comment by ben-grande** [comment]
I don't want if my comment fit this issue because it is about *underruns in dom0*, but I am experiencing the same thing when:

- using pipewire in the audio client and server
- audio server is sys-usb and the headset stays in sys-usb
- trying to record audio with the headset microphone

I have not tried the linked commits from above. Will try when they reach the stable branch.

**Comment by ben-grande** [comment]
Does this affect in any way non Dom0 AudioVMs that have the package `qubes-audio-daemon` installed? Pulseaudio is still referenced in that package requirement.

**Comment by marmarek** [comment]
> Does this affect in any way non Dom0 AudioVMs that have the package `qubes-audio-daemon` installed? Pulseaudio is still referenced in that package requirement.

`pulseaudio-daemon` is provide by `pulseaudio` but also by `pipewire-pulseaudio`.
