### ISSUE TITLE
Ability to hide (a) qube(s) from updates

### ISSUE THREAD

**Issue by EdGeraghty** [QubesOS/qubes-issues#9029]
### The problem you're addressing (if any)

I have several qubes which are never going to receive updates - currently these qubes are visible in the update manager, but they are clutter

### The solution you'd like

The ability to hide (a) qube(s) from the updating functionality

### The value to a user, and who that user might be

It means we can select all in the update manager rather than having to choose qubes individually. This will benefit anyone running a Windows 10/11 HVM, TempleOS, or a number of other guests such as the mirage-os unikernel.

**Comment by marmarek** [comment]
> Meta question: should this be a feature or a preference? `updatable` is a preference and not a feature.

This is a very good question :) We don't have any guidelines for this, and we don't use it consistently really (*)...
The `updatable` property is really a read-only property more or less meaning if root volume is persistent ("does it make sense to install updates there"). And this too may be misleading when the updating mechanism will support flatpaks installed in the user home in the future.
The properties and features can have a bit different set of behaviors:
- properties:
  - can be listed in qvm-prefs
  - can have custom setter that validates the value, and possibly transform it
  - can have an arbitrary mechanics for default value (like calculated based on other properties, different for different qube type etc)
  - properties are cached, and needs to handle cache invalidation properly (especially tricky for default value that is calculated based on other properties)
- features:
   - just simple key+value, usually value is just boolean (empty for false, "1" for true)
   - few predefined inheritance methods (take default from template, from netvm, from guivm)
   - default value is "feature not set", up for its user to define what that means
   - no validation on setting, no detection for typos in the feature name etc

Generally, properties are smarter. But due to its stricter nature, and potentially smarter behavior, need more care when implementing. This also means committing to its support in the future, converting on upgrades, while restoring old backups in the future etc. More or less it means you cannot really remove it in the future - at least some migration code needs to stay forever.

There was a plan to make features a bit smarter, especially around their documentation and value validation (basically have an API that allows adding extra metadata to some feature names). But that mechanism never materialized and the only thing we have is the `qvm-features` man page.

In this particular case, I think it's okay to go with a feature, especially since `updates-available` is a feature already and is yet another factor for selecting what to update. But if you'd prefer to make it a property, I would be okay with that too.

(*) one one hand `backup_timestamp` or `keyboard_layout` are properties, which aren't really part of core mechanism, but on the other hand, `memory-hotplug`, `video-model` or `uefi` are features but their implementation is deeply integrated into core-admin component.

**Comment by alimirjamali** [comment]
In the last few hours, I considered patching `qubes-core-admin` directly to honour the `skip-update` feature while updating `updates-available` feature. Theoretically this should allow patching everything in one place instead of patching 3 individual repositories.

Finally I decided to revert back to the original plan.

**Comment by alimirjamali** [comment]
The PRs (total of 3) for this issue are ready for review.

Review priority: low

1. `qubes-vm-update`  is patched to ignore VMs with `skip-update` feature. User could still target them and force update on them with `--targets` option.
2. Qubes Manager will show a warning sign+tooltip message for TemplateVMs and StandaloneVMs with `skip-update` feature. Just as a reminded that this is potentially a dangerous and advanced feature.
3. Qubes Update systray widget will not show notifications for TemplateVMs and StandaloneVMs with `skip-update` feature. Neither for outdated nor for EOL with the mentioned feature.
4. By default, Qubes OS Update GUI will not show VMs with `skip-update` feature. User could change this behaviour with `--show-advanced-settings` and change it in settings page. I also added an additional option to hide already updated and not stalled VMs from VM selection page.

Video demo:

https://github.com/user-attachments/assets/d94d698b-ce5e-4552-b004-866049337c3d

**Comment by marmarta** [comment]
I'm reviewing the PRs and I wonder if 4. is not too many layers of hiding - I feel like showing advanced settings (while marking them as advanced) by default is not a bad idea? It still requires CLI command to actually set on a VM, right?

**Comment by alimirjamali** [comment]
> I'm reviewing the PRs and I wonder if 4. is not too many layers of hiding - I feel like showing advanced settings (while marking them as advanced) by default is not a bad idea? It still requires CLI command to actually set on a VM, right?

We discussed this on [forum](https://forum.qubes-os.org/t/qubes-update-tool-template-selection-and-obsolete-status/29446/15). We were/are afraid if novice users might use this potentially dangerous feature and end up with many outdated templates. But reconsidering it, maybe it is not that bad. I will remove `--show-advanced-settings` option and always show the advanced options.

**Comment by kennethrrosen** [comment]
Requesting backport to 4.2 if possible.

**Comment by marmarek** [comment]
Generally new features are not eligible for backporting.
