### ISSUE TITLE
Installing i3 skips security settings. i3-settings-qubes seems to have no effect.

### ISSUE THREAD

**Issue by BrianDL** [QubesOS/qubes-issues#9052]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2

### Brief summary
Installing i3 and i3-settings-qubes according to the documentation disables some security settings.
- All qubes can use full screen regardless of settings.
- Screen capture software doesn't show the usual warning message at the first launch.
- Thunar is missing the qubes integration but qubes-core-agent-thunar is installed and it works as expected in the usual xfce session.
- All windows are tiled (no floating windows). There are no exceptions in the generated i3 config file.

### Steps to reproduce
1. In a new installation, choose debian-12-xfce as base template.
2. run  `sudo qubes-dom0-update i3 i3-settings-qubes` as per https://www.qubes-os.org/doc/i3/
3. log in to i3
4. Accept the prompt to generate a config file.
5. Press $mod+f on any window and verify it fills the whole screen.

### Expected behavior
at (5) it should leave the border of the window visible.

### Actual behavior
at (5) the window that is active when pressing $mod+f fills up the whole screen regardless of settings.

**Comment by marmarek** [comment]
User-initiated fullscreen (as opposed to just maximize) is allowed by design (in xfce the same can be done from titlebar menu). But application itself shouldn't be able to do it on its own, only by explicit user action. If you (as the user) want to keep a colorful border of some window, it's your choice, just use maximize to keep it, or fullscreen to hide it. But application should be able to do only the former (unless fullsceen is allowed for a given qube in settings).
