### ISSUE TITLE
certificate expired qubes.notset.fr

### ISSUE THREAD

**Issue by profeshish** [QubesOS/qubes-issues#9135]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.0

### Brief summary
the certificate for the domain that qubes uses to upgrade its distro has had an expired certificate since the 18th, visited the website manually and looked at the certificate and it is expired.

### Steps to reproduce
-run sudo qubes-dom0-update -y qubes-dist-upgrade from dom0 terminal
-should give a certificate error

**Comment by Minimalist73** [comment]
qubes.notset.fr is not the official Qubes repository, it's a personal repository from a Qubes team member. 
I'm not sure why you are using that in dom0. Since you are trying to install `qubes-dist-upgrade`, I guess you are trying to upgrade to a newer Qubes version. You should backup all your qubes with Qubes Backup and restore them on a clean 4.2 installation.

https://www.qubes-os.org/doc/upgrade/4.2/#clean-installation
