### ISSUE TITLE
Typo in qvm-features (correct spelling in docs though)

### ISSUE THREAD

**Issue by emanruse** [QubesOS/qubes-issues#9139]
### Qubes OS release

4.1.2

### Brief summary

https://www.qubes-os.org/doc/gui-configuration/ advises to set non-existing (due to a typo) `gui-videoram-*` feature through `qvm-features`.

### Steps to reproduce

`qvm-features dom0`

### Expected behavior

`gui-videoram-min ...` (with `o`)

### Actual behavior

`gui-videram-min ...` (missing `o`)

**Comment by UndeadDevel** [comment]
How do you know?

I find no mention of `gui-videram-min` in the QubesOS code via a simple GitHub orga search. [Searching for `gui-videoram-min`](https://github.com/search?q=org%3AQubesOS+gui-videoram-min&type=code), however, yields, e.g. [this](https://github.com/QubesOS/qubes-core-admin/blob/ec10371afa5d923fce159da0b69b70b4067e6502/qubes/ext/gui.py#L80), which writes the values that are read [here](https://github.com/QubesOS/qubes-gui-agent-linux/blob/292277868c8ed6f8c33182df1a5050c32a38ded3/appvm-scripts/usrbin/qubes-run-xorg#L47) and [here](https://github.com/QubesOS/qubes-gui-agent-linux/blob/292277868c8ed6f8c33182df1a5050c32a38ded3/appvm-scripts/usrbin/qubes-run-x11vnc#L43).

**Comment by marmarek** [comment]
> `gui-videram-min ...` (missing `o`)

Perhaps you set it with a typo?

**Comment by marmarek** [comment]
That's a... feature. The features attached to qubes can have arbitrary names, there isn't a close list of supported values. Any extension or even user own scripts can use them to store some values. You could have also some mechanism using `gui-videram-min` for some thing, if you want to. The `qvm-features` tool is a low level tool to manipulate features bypassing any higher level validation. The real issue here is that no other method for setting `gui-videoram-min` exists - https://github.com/QubesOS/qubes-issues/issues/4509
