### ISSUE TITLE
No Qubes/VMs starting - libxenlight failed to create new-domain in 4.2.1

### ISSUE THREAD

**Issue by scallyob** [QubesOS/qubes-issues#9150]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2.1

### Brief summary

I did a full update on April 23 and rebooted April 24. First reboot since April 1.
Now no Qubes/VMs will start.

### Steps to reproduce

1. Update dom0 and all VMs.
2. reboot

### Expected behavior

VMs set to autostart start up

### Actual behavior

"libxenlight failed to create new-domain" pop ups for sys-net, sys-firewall, etc

qvm-ls - shows all VMs halted

/var/log/libvirt/libxl/libxl-driver.log  shows:

> libxl: libxl_dm.c:2857:stubdom_xswait_cb: Domain 1: Stubdom 2 for 1 startup: startup timed out
> libxl: libxl_create.c:1975: domcreate_devmodel_started: Domain 1:device model did not start -9

This repeats many times with the Domain # changing

(there are also errors related to PCI device, but these are present for previous boots as well and are not new. The errors above do not appear until today in the log.)

**Comment by krystian-hebel** [comment]
Good thing I refreshed list of issues, I was about to report the same. I can confirm that VMs were restarted right after upgrade and they worked until following boot.

I also checked that after removing all network controllers from `sys-net` and changing its type to PVH all VMs can be started (obviously without network), so this seems to be the problem with HVM.

This happened on KGPE-D16 with Opteron 6282 SE, with ASUS firmware 3001 (i.e. no coreboot).

**Comment by scallyob** [comment]
> KGPE-D16 with Opteron 6282 SE

Oh no, I'm on same hardware!

**Comment by scallyob** [comment]
Kernel downgrade in dom0 and sys-net did not produce different results.

**Comment by marmarek** [comment]
What can you see in `/var/log/xen/console/guest-sys-net-dm.log` ?

**Comment by scallyob** [comment]
There's a lot in there, not sure what to look for. Don't see errors or warnings. 
(talked about this here: https://forum.qubes-os.org/t/no-qubes-vms-boot-after-latest-updates/26033/14)

**Comment by scallyob** [comment]
I see it start qemu, with a bunch of options, each time it tries to boot. Nothing obvious to me after that that seems like a problem.

**Comment by krystian-hebel** [comment]
> What can you see in `/var/log/xen/console/guest-sys-net-dm.log` ?

For me it ends with:

![image](https://github.com/QubesOS/qubes-issues/assets/40995177/ef9e483c-d7aa-448a-8a58-757c9b6e25ab)

If full log may contain something useful I may try to get it tomorrow, without network it will require some finesse.

**Comment by marmarek** [comment]
Indeed nothing obvious there... But one worrying thing is the timing: the "Rescanning PCI Frontend" messages are on stubdomain cleanup, and based on timestamps it's pretty close to starting qemu. AFAIR the startup timeout is 10s, but usually the stubdomain startup takes below 1s. This is pretty old system, it may be that recent workaround for speculative-execution bugs made it significantly slower.

Is it with current-testing (in dom0) enabled or not? Best to identify which update specifically broke it. dnf history may help, but my guess is Xen package. There is also Xen update in current-testing since yesterday, maybe this one will help?

**Comment by krystian-hebel** [comment]
> Is it with current-testing (in dom0) enabled or not?

No, just default ones.

I also think this may be caused by Xen, that would explain why initial restart of VMs succeeded and only after full reboot they won't come up, will check different versions later.

**Comment by scallyob** [comment]
Is it with current-testing (in dom0) enabled or not?
No.

Tried downgrading to: xen-hvm-stubdom-linux-4.2.9-1.fc37.x86_64.rpm AND xen-hvm-stubdom-linux-full-4.2.9-1.fc37.x86_64.rpm

No change.

Tried downgrading xen, xen-hypervisor, xen-libs, xen-licenses and xen runtime to 4.17.3-4, but it gave me error:

> The operation would result in removing the following protected packages: qubes-core-dom0

So not sure how to proceed.

**Comment by marmarek** [comment]
> Tried downgrading xen, xen-hypervisor, xen-libs, xen-licenses and xen runtime to 4.17.3-4, but it gave me error:
> 
> > The operation would result in removing the following protected packages: qubes-core-dom0
> 
> So not sure how to proceed.

xen package needs to match exact version of python3-xen - so you need this one too

**Comment by scallyob** [comment]
Ok, that allowed the downgrade, now everything is booting.

**Comment by krystian-hebel** [comment]
The problem is still present in 4.17.4-1 from current-testing.

**Comment by krystian-hebel** [comment]
All VMs start when booting with `spec-ctrl=no-ibpb-entry`, which makes me believe this is a performance issue that may have been present for some time, but hidden until XSA-455.

I've noticed the same problem (at least I think it's the same, but didn't do as much testing as on KGPE) on HP t630 with slightly newer CPU. In that case, `sys-usb` was failing which didn't allow me to log in and I didn't had PS/2 keyboard at hand. `spec-ctrl=no-ibpb-entry` helped in that case as well.

@marmarek is it possible to relax the startup timeout to see if it helps?

**Comment by marmarek** [comment]
So, I'm afraid there is not much hope for this old-ish system... The only way to make the system kinda-usable has a tradeoff with security here, by disabling the mitigation for PV domains (which should mean just stubdomains, make sure you don't have any really untrusted PV qubes) with `spec-ctrl=ibpb-entry=no-pv`. It does mean that stubdomain will be able to mount the attack, potentially leaking memory of any other VM (so isolation of sys-net/sys-usb and any other HVM becomes weaker). If that is not an acceptable risk, blame AMD for making buggy CPU, and replace with something newer...

**Comment by andyhhp** [comment]
Yeah sorry... you need https://www.amd.com/content/dam/amd/en/documents/corporate/cr/speculative-return-stack-overflow-whitepaper.pdf and the update from Feb this year in order to have an AMD CPU not needing this mitigation for safety

**Comment by scallyob** [comment]
> by disabling the mitigation for PV domains (which should mean just stubdomains, make sure you don't have any really untrusted PV qubes) with `spec-ctrl=ibpb-entry=no-pv`

1. So this would be a better medium-term solution than excluding xen from updates? (Short-term that is what I am doing: excluding xen updates. Long-term I guess I need to look into buying a new computer.)
2. For someone who doesn't know how to do this, how hard is this to do?

Thanks for looking into this, despite the disappointing conclusion.

**Comment by RA-Kooi** [comment]
> 1. So this would be a better medium-term solution than excluding xen from updates? (Short-term that is what I am doing: excluding xen updates. Long-term I guess I need to look into buying a new computer.)

Yes, by not updaitng Xen you will be vulnerable to vulnerabilities in Xen itself as well as being vulnerable to this CPU bug.
> 2. For someone who doesn't know how to do this, how hard is this to do?

Depending on how Xen is started it could differ, but chances are there's a file called `xen.cfg` in `/boot`. In this file you will something like this:
```ini
[xen]
options=
```
Simply append `spec-ctrl=ibpb-entry=no-pv` to the end of the options line.

**Comment by scallyob** [comment]
> > 1. So this would be a better medium-term solution than excluding xen from updates? (Short-term that is what I am doing: excluding xen updates. Long-term I guess I need to look into buying a new computer.)
> 
> Yes, by not updaitng Xen you will be vulnerable to vulnerabilities in Xen itself as well as being vulnerable to this CPU bug.
> 
> > 2. For someone who doesn't know how to do this, how hard is this to do?
> 
> Depending on how Xen is started it could differ, but chances are there's a file called `xen.cfg` in `/boot`. In this file you will something like this:
> 
> ```ini
> [xen]
> options=
> ```
> 
> Simply append `spec-ctrl=ibpb-entry=no-pv` to the end of the options line.

I do not have xen.cfg in /boot (or any of its subdirectories)
I have xen-4.17.3.config, which appears to not be the same thing and says "do not edit". Any other suggestions on how to accomplish this?

**Comment by Tonux599** [comment]
@scallyob you can add
```
GRUB_CMDLINE_XEN_DEFAULT="$GRUB_CMDLINE_XEN_DEFAULT spec-ctrl=ibpb-entry=no-pv"
```
to the end of `/etc/default/grub` and update with `grub2-mkconfig -o /boot/grub2/grub.cfg` and then reboot.

This is a really unfortunate situation as the KGPE-D16 is the most powerful, binary blob free (when used with Libreboot, old Coreboot, or Dasharo) system that supports Qubes.

I understand that AMD is unlikely to push any microcode updates for these CPU's to aid fixing this, so would appreciate if we could further seek any possible resolutions.

@marmarek could we potentially seek increasing `LIBXL_STUBDOM_START_TIMEOUT` beyond 30 seconds to see if performance is not degraded once it starts? Qubes with PCI assignments have always been slow to start but it's generally once per boot.

Failing that, would it be best to have PCI Qubes use PV with `spec-ctrl=ibpb-entry=no-pv`, or use HVM with `spec-ctrl=ibpb-entry=no-hvm`?

Until #4318 is completed this system is all we got if you want Qubes on blob free firmware.

**Comment by andyhhp** [comment]
IBPB (Indirect Branch Prediction Barrier) *is* the thing AMD retrofitted in microcode for Spectre-v2 defences.

It is **very** expensive.  Sadly it's also the only protection against Branch Type Confusion (BTC, marketed as Retbleed), and Speculative Return Stack Overflow (SRSO, marketed as Inception).

Even in CPUs newer than the Spectre discovery, it's still expensive, and that's with all the pipeline improvements that the CPU vendors could bear to put in.

The performance will be degraded for the lifetime of the VMs.  IBPB is issued on every entry into Xen, so that's every interrupt/vmexit (HVM guests) or every syscall/pagefault/etc (PV guests).

**Comment by andyhhp** [comment]
> This is affecting Intel too, on a recent NUC system FYI running a 13th gen CPU.

This issue really isn't affecting Intel systems.  If you're seeing similar symptoms, it will be a different cause.  Please open a new bug.

**Comment by marmarek** [comment]
No, I don't see any sense in that. If something that normally takes about 1s doesn't complete in 30s, it doesn't sound like usable system at all. It means pretty much everything will be 3000% slower. On the other hand, increasing the timeout will affect also users of otherwise perfectly usable system, as in case of some errors they will need to wait longer.

**Comment by krystian-hebel** [comment]
Some numbers from my HP t630:
- Booted with `qubes.skip_autostart` to avoid starting `sys-net` and `sys-usb` simultaneously, as it always fails.
- Manually starting `sys-net` afterwards in qube manager _usually_ succeeds within 30s timeout.
- Starting Firefox and letting it fully render Fedora start page (counted from clicking on Firefox icon until "Latest Council Video" thumbnail) on already started `sys-net` (HVM) on otherwise idle machine takes ~20 minutes. Out of that, rendering takes at least 15 minutes. For comparison, on non-Qubes laptop loading and rendering takes ~5 seconds.
- Doing the same in `personal` (PVH) is "much faster", it takes roughly 65 seconds. I haven't checked how much of that is waiting for `sys-firewall`/`sys-net` to provide data.

So while increasing `LIBXL_STUBDOM_START_TIMEOUT` could help those VMs get up in time, they wouldn't be useful (maybe except some CPU-bounded benchmarks, but that's not what HVM is used for).

**Comment by mrothfuss** [comment]
This problem has been fixed in the 15h.org coreboot release for KGPE-D16 :) No workarounds required.

https://www.phoronix.com/news/15h-org-AMD-Firmware

**Comment by andyhhp** [comment]
I'll bite.  Fixed how?

The only thing that will recover you performance without modifying the Xen command line would be downgrading the microcode to one without IBPB, and that puts you in an even worse security position by removing the isolation between consecutive VMs.

**Comment by mrothfuss** [comment]
The latest microcode is being applied early in coreboot-15h firmware. This seems to be necessary to provide correct support for IBPB. For unknown reasons, using this microcode in Raptor Engineering's coreboot port would cause kernel panics.

**Comment by mrothfuss** [comment]
Results from a QubesOS tester on coreboot-15h and KGPE-D16 with Opteron 6386 (x2).

QubesOS R4.3-rc3 is running with 0 PV domains. /sys/devices/system/cpu/vulnerabilities reports...
```
spectre_v2: Mitigation: Retpolines; IBPB: conditional (...)
spec_store_bypass: Vulnerable
spectre_v1: Mitigation  (...)
retbleed: Mitigation  (...)
```
All others are listed as Not affected.

Info/Screenshots here: https://forum.qubes-os.org/t/trying-to-install-qubes-4-2-on-kgpe-d16-cause-sudden-reboot/31575/20
