### ISSUE TITLE
Socket-based services should support exiting when remote shuts down write end

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9176]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Existing VMs assume that `qubes.UpdatesProxy` and `qubes.ConnectTCP` will terminate after the server shuts down the write end of its connection.  This is currently implemented by `socat`, with a useless 0.5s timeout.  Native socket-based services would be better, but runs into #9169 with the current `qrexec-client-vm` implementation.  #9169 can be fixed by changes to `qrexec-client-vm` and `qubes-updates-proxy-forwarder@.service`, but these changes work around this problem on the client side, rather than restoring the previous server behavior.  This means that the new services are incompatible with existing VMs that need to be updated, which is very bad.

### The solution you'd like

Add a new service configuration directive that causes the service to send `MSG_DATA_EXIT_CODE` and terminate when the socket server shuts down the connection for writing, the VM shuts down the connection for reading, or both.  These should be controllable separately.

Proposed names: `terminate-on-send-eof` and `terminate-on-recv-eof`.  Both will be incompatible with `force-user=` and executable services.

### The value to a user, and who that user might be

Users will be able to use a native socket-based service instead of `socat` for `qubes.ConnectTCP` and `qubes.UpdatesProxy`, without needing a new `qrexec-client-vm`.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

- [ ] `terminate-on-send-eof=true` works
- [ ] `terminate-on-recv-eof=true` works
- [ ] Combination of `terminate-on-send-eof=true` and `terminate-on-recv-eof=true` works
- [ ] Tests for all of the above
- [ ] Tests that these two options are incompatible with `force-user=` and with executable services.

**Comment by ben-grande** [comment]
> Tests that these two options are incompatible with `force-user=` and with executable services.

Does it make sense to create a lint tool for rpc-config to detect these problems at will instead of at runtime?

The tool [qubes-policy-lint](https://github.com/QubesOS/qubes-core-qrexec/blob/main/qrexec/tools/qubes_policy_lint.py) is a wrapper of `qrexec.policy.parser`, is such thing possible for the rpc-config files I can only see `libqrexec/qrxec.h` and `qrexec/tests/socket/{daemon,agent}.py` handling this bit, so there is no python parser just manual tests? Especially because conflicting options are being implemented (`skip-service-descriptor` and `force-user` already seem to be conflicting from what I gathered).

If it is possible, should I create another issue about this?

**Comment by DemiMarie** [comment]
Please do create another issue.

The format is a strict subset of TOML.  TOML allows lots of syntax that the configuration parser will reject.  However, if the configuration parser accepts a file, it should interpret the file according to the TOML specification.  If you can get the configuration parser to accept a file and parse it dfferently than the TOML specification requires, please report it as a bug.
