### ISSUE TITLE
New applications menu (4.2) has good and not so good properties 

### ISSUE THREAD

**Issue by kord1e** [QubesOS/qubes-issues#9202]
### The problem you're addressing (if any)

In 4.2 the new applications menu has good and not so good new properties:

- Grouping ordinary VMs, templates and service VMs is a good thing in my opinion. However, some "service" VMs such as sys-usb, sys-update-dom0 or sys-clock in my case do not seem to go to the service VMs section.

- There is too much empty space between the VMs in the menu. When you have many VMs, you have to scroll the menu to reach some of them. The menu does not also extend downwards automatically, you just have to scroll.

- Separating dom0-related items into their own menu may be a good thing; however, accessing them requires extra clicks now.

### The solution you'd like

Just discussion about the new menu.

### The value to a user, and who that user might be

Qubes 4.2 users.

**Comment by UndeadDevel** [comment]
This will probably be closed as it's a meta-issue, but I'll give some responses nevertheless:

To
>Grouping ordinary VMs, templates and service VMs is a good thing in my opinion. However, some "service" VMs such as sys-usb, sys-update-dom0 or sys-clock in my case do not seem to go to the service VMs section.

This works for me, including for newly created non-standard service qubes...remember that you have to set the "Provides network" flag on a qube in order to turn it into a service qube. Perhaps you forgot that? I seem to recall that there was also an issue or discussion somewhere about introducing a proper "service qube flag" rather than tying it to network provider functionality.

To
> There is too much empty space between the VMs in the menu. When you have many VMs, you have to scroll the menu to reach some of them. The menu does not also extend downwards automatically, you just have to scroll.

Note that you can use `PgUp`, `PgDown`, `Home`, `End` to more quickly scroll...there's also an issue here about making `Up Arrow` work in more lists of the menu as well as making it generally more accessible for keyboard-only users. You might want to take a look at [my script](https://gist.github.com/UndeadDevel/8501e82a534e5daa2ac60e36945167b9) which you can bind to a keyboard shortcut to open the app menu with the keyboard; it also fixes some of the issues that the app menu still has.

To
> Separating dom0-related items into their own menu may be a good thing; however, accessing them requires extra clicks now.

Note that once you open the app menu you can immediately start typing to search its entries, so e.g. if you want to open the dom0 Keyboard app you can open the app menu and type `keyb` and then press `Down Arrow` and `Enter` (or, if you subscribe to the `current-testing` repo, just `Enter`, as that new feature has already been moved there yesterday) to launch it. Personally I don't find this to be an issue.

**Comment by kord1e** [comment]
Thank you, setting the "provides network" flag worked, now those VMs went to the service menu.

Yes, using keys works but the old menu did not require extra scrolling. Everything was visible immediately. (Unless maybe you had a very large number of qubes.)

**Comment by kord1e** [comment]
Another issue: let's say you start a browser in a disposable template and make some configurations to it. Then shutdown the disposable template. 

Now you want to use the browser in a disposable VM. So go to the applications menu to start the browser. But the menu is still in the "templates" category, so it's easy to get confused and start the browser in the template instead of a disposable VM.
