### ISSUE TITLE
Add a warning about the inter-qube clipboard maximum character limit

### ISSUE THREAD

**Issue by qwrd** [QubesOS/qubes-issues#9296]
### The problem you're addressing (if any)
The inter-qube clipboard system appears to have a 65000 character limit, which means that any text longer than this limit that is copied between individual qubes by using the ctrl+shift+c and ctrl+shift+v shortcuts will be silently truncated to 65000 characters. I noticed this in Q4.2 while trying to copy over some config files from one GUI text editor to another in a different qube, and then some syntax errors appeared in the program log. Upon inspection, I noticed that a portion of the config file in the new qube was missing.

### The solution you'd like
Please add some sort of warning message on the screen. When a user tries to copy a text section that is longer than this limit then a message should pop up notifying the user that not all text has been copied over.

### The value to a user, and who that user might be
Any user who copies large portions of text won't wonder why some of it has disappeared.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by Solomon1732** [comment]
I offer that the warning also suggest the user instead copy files between qubes. Not that it will present a popup, but rather say "use qvm-copy" or the like.

**Comment by alimirjamali** [comment]
@marmarek I am looking at commit history to `qubes-gui-daemon` and in this [specific commit](https://github.com/QubesOS/qubes-gui-daemon/commit/72acbaf688a864a0838b6ed2fe5c14ee93c31ef6#diff-7897f6116dd3815ad17499205f816d770805aca6ce63e96ff55be4fe2d95a3d6R473-R474), I can not find where the `MAX_CLIPBOARD_SIZE` is defined. Searching the repo does not provide any clue.

**Comment by marmarek** [comment]
https://github.com/QubesOS/qubes-gui-common/blob/main/include/qubes-gui-protocol.h#L86

**Comment by alimirjamali** [comment]
> https://github.com/QubesOS/qubes-gui-common/blob/main/include/qubes-gui-protocol.h#L86

Thanks for the hint. Regardless of the OP, 65KB sound a little bit low (maybe even 12 years ago). This is less than 1000 at 40 chars width. Was there any security concern?

**Comment by alimirjamali** [comment]
After some consideration and study about this issue, it might not be simple. I could divide it to 3 individual sub-tasks:

1. The 65000 character limit set 11 years ago by Rafal Wojtczuk should had been most probably due to X86 real-mode memory segmentation concerns. Which is no problem on X86-64 and is solved long ago. X11 could easily handle chunks of 256KiB or even higher nowadays before any necessity to switch to INCR. I guess it would be OK to increase the `MAX_CLIPBOARD_SIZE` to 256KiB. The current limit is too low.
2. A patch to `qubes-gui-daemon` is necessary to raise proper errors instead of truncating the buffer.
3. An additional patch to `Qubes Clipboard Widget` might be necessary for visual notification of error raised by GUI daemon.

**Comment by alimirjamali** [comment]
PRs submitted (total of 5)

Review priority: Medium (since bug involves data loss)

Users could set the global clipboard limit via `max_clipboard_size` key within `/etc/qubes/guid.conf`. or via `gui-default-max-clipboard-size` feature of GUIVM (or dom0). Or can set limit per vm via `gui-max-clipboard-size` of individual qubes. The accepted values are between 256 characters to 256000 characters. Default is 64000 characters. Trying to copy sizes over it will trigger a Global Clipboard widget warning message and wipe the global clipboard. See video below:


https://github.com/user-attachments/assets/25264079-29e5-4f1d-ad54-c11cd4f9da11

**Comment by alimirjamali** [comment]
A brief note to potential 1st time contributors who are looking at historic issues with [good first issue](https://github.com/QubesOS/qubes-issues/labels/good%20first%20issue) Label and wondering why the approved solution is relatively complex.

The simple solution to this issue could had been a simple patch to `clipboard.py` of `qubes-desktop-linux-manager` repository. To alert users if the new `/var/run/qubes/qubes-clipboard.bin` size is 65000 characters, then the clipboard might be probably truncated.
