### ISSUE TITLE
Window title of Qubes Template Switcher reads "Template Manager", confusingly similar to that of the Qubes Template Manager

### ISSUE THREAD

**Issue by tokideveloper** [QubesOS/qubes-issues#9298]
### Qubes OS release

R4.2.1

### Brief summary

The window titles of the Template Manager ("Qubes Template Manager") and the Template Switcher ("Template Manager") are confusingly similar.

### Steps to reproduce

1. Open the Template Manager via Q -> gear icon -> Qubes Tools -> Qubes Template Manager.
2. Open the Template Switcher via Q -> gear icon -> Qubes Tools -> Qubes Template Switcher.

### Expected behavior

- The window title of the Template Manager reads "Qubes Template Manager".
- The window title of the Template Switcher reads **"Qubes Template Switcher"**.

### Actual behavior

- The window title of the Template Manager reads "Qubes Template Manager".
- The window title of the Template Switcher reads **"Template Manager"**.

**Comment by alimirjamali** [comment]
This happened during the fix for issue #6504 when the old Template Manager was renamed to Template Switcher.

The old artifacts of it still remains in some of the source files:

https://github.com/QubesOS/qubes-manager/blob/main/qubesmanager/template_manager.py#L66

and resource files:

https://github.com/QubesOS/qubes-manager/blob/main/qubesmanager/i18n/qubesmanager_en.ts#L639
https://github.com/QubesOS/qubes-manager/blob/main/qubesmanager/i18n/qubesmanager_es.ts#L651-L652
