### ISSUE TITLE
Qui domains falsely flags need to restart qubes

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#9375]
### Qubes OS release
4.2

### Brief summary

After forcing updates on a qube which has no updates, the domains widget still shows that the app qube should be restarted, even thought that's not the case. Sounds like a useless situation, but actually this may happen whenever a qube that "MAYBE" has updates but in fact doesn't.

### Steps to reproduce

1. start `work` qube
1. perform updates on all qubes
2. open updater again and force-update some qube which has no updates
3. confirm that no app qube is suggested restart (since there were no actual updates involved)
4. notice on the domains widget work showing updates available :recycle: icon on the work qube

### Expected behavior

There should be no :recycle: icon

### Actual behavior

There should be no :recycle: icon

**Comment by marmarek** [comment]
I don't think that's going to work this way. First of all, updates is not the only thing that can happen when template is started, and the widget doesn't know that. You can start a terminal in the meantime there and change something for example. But also, even if really just updater was involved, there may still be relevant template changes happening, like cleaning up package manager cache (so, freeing some space on rootfs - relevant for AppVMs too), or even just refreshing cached metadata, so update check (or temporarily installing a package in an AppVM) will use up to date version instead, or maybe some no longer needed packages are cleaned up (for example older kernel, which couldn't be removed during earlier update because template was still using it - when using in-vm kernel) - this also I think doesn't qualify as an update (but I'm not sure tbh).

**Comment by marmarek** [comment]
This isn't what is happening. The "restart needed" icon shows if template was running anytime after that app qube was started. https://github.com/marmarek/qubes-desktop-linux-manager/blob/c4fc66b/qui/tray/domains.py#L727
If template was started, it might (and most likely did, even if only some cache) changed something in its filesystem. Note the tooltip says "Qube must be restarted to reflect changes in template" - not mentioning "updates" there is intentional, because that's not the only thing that may change.

**Comment by marmarek** [comment]
> Would it make sense to suppress this volume change in the case where there have been no updates? Or is it too complex / not worth considering.

I'd say the latter. Theoretically we could probably have some marking that only updater did anything with the template and reported no updates, but as said above, that still is some change to the template and there may be a case where even that is relevant.
