### ISSUE TITLE
[Build 2024091704-4.3] salt fails with "No top file or master_tops data matches found"

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#9453]
## Observation

openQA test in scenario qubesos-4.3-update-x86_64-system_tests_guivm_vnc_gui_interactive@64bit fails in
[update_guivm](https://openqa.qubes-os.org/tests/112779/modules/update_guivm/steps/22)

```
local:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or master_tops data matches found. Please see master log for details.
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
DOM0 configuration failed, not continuing
```

`qubesctl state.show_highstate`  fails too

## Reproducible

Fails since (at least) Build [2024091704-4.3](https://openqa.qubes-os.org/tests/112779) (current job)

One of recent dom0 updates broke this (either from Qubes or from Fedora) - it worked a week ago. A packages diff is available at https://openqa.qubes-os.org/tests/112779#investigation

## Expected result

Last good: [2024091004-4.3](https://openqa.qubes-os.org/tests/111689) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=update&machine=64bit&test=system_tests_guivm_vnc_gui_interactive&version=4.3)

**Comment by marmarek** [comment]
This change is to blame: https://github.com/python/cpython/issues/85110, it's included in Python 3.13rc2 which just landed in Fedora 41.

Old behavior:
```
>>> urllib.parse.urlunparse(("file", "", "top.sls", "", "", ""))
'file:///top.sls'
```
New behavior:
```
>>> urllib.parse.urlunparse(("file", "", "top.sls", "", "", ""))
'file:top.sls'
```

Technically, I think the latter might be more correct. But it still breaks salt's expectations.

**Comment by marmarek** [comment]
Upstream report: https://github.com/saltstack/salt/issues/66898

**Comment by marlox-ouda** [comment]
I have also the same issue on Qubes Os 4.2.3 with `fedora-40-xfce` as disposable management vm. It runs python version 3.12.6 where the `urlunparse` change has also landed.

Same patch applies on it.

**Comment by marlox-ouda** [comment]
Sorry. I have not tested it from testing. I was confused by mentionned python version and Qubes Os release 4.3.

But, the patch applies on fc40 and apply on the salt package before it lands on `site-packages`, so it should work.
I will test it tomorrow.

**Comment by marlox-ouda** [comment]
Tested today:
* updated `fedora-40` from `qubes-templates-itl-testing`: `/usr/lib/python3.12/site-packages/salt/utils/url.py` is not patched. So salt fails. File is managed by `salt` package with version `3006.8-1.fc40`.
* updated `debian-12-xfce`  from `qubes-templates-itl-testing`: `/usr/lib/python3/dist-packages/salt/utils/url.py` is not patched. So salt fails on issue #9328, but once patched with `if 0: […]` (see the issue), it works because python version is 3.11 and `urllib` was not patched on this version. File is managed by `salt` package with version `3006.5-1+deb12u1`

I do not understand yet why I cannot get `salt` version `3006.9-2.fc40` (as I see in [current-testing repository](https://ftp.qubes-os.org/repo/yum/r4.2/current-testing/vm/fc40/rpm/)) for fedora. I will look for this side issue.
There is not `salt` package in the [current repository](https://ftp.qubes-os.org/repo/yum/r4.2/current/vm/fc40/rpm/).

**Comment by marlox-ouda** [comment]
Ok. I got it. `qubes-templates-itl-testing` `fedora-40` template has not enabled `qubes-vm-r4.2-current-testing` (in `/etc/yum.repos.d/qubes-r4.repo`).
With this one enabled, I successfully retrieved `salt` package with version `3006:9-2.fc40` that applies the patch and it works as expected.
