### ISSUE TITLE
Migrate qubes-manager tools to Qt6

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#9476]
### The problem you're addressing (if any)
Qt5 will stop being supported.

### The solution you'd like
Stop using it.

**Comment by alimirjamali** [comment]
I believe this is a `Major` issue. Because of two reasons:
1. Free support for Qt5 ended on 26th May 2023. And [extended paid support](https://www.qt.io/blog/qt-5.15-extended-support-for-subscription-license-holders) is only till 26th May 2025. During the paid subscription based support period, security fixes might not be available to Fedora project and others.
2. The major essential PR to `Qube Manager` might conflict with other PRs if it is not reviewed and merged quickly.
