### ISSUE TITLE
Disable direct IO on Btrfs based storage

### ISSUE THREAD

**Issue by ImBearChild** [QubesOS/qubes-issues#9488]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes Release 4.2.3 (R4.2)

### Brief summary

﻿There shouldn't be a use of direct-io on Btrfs because it can lead to various problems.

This would cause CSUM error, which is described in the [documentation of PROXMOX](https://pve.proxmox.com/wiki/Storage:_BTRFS) and there's also an related [issue](https://bugzilla.redhat.com/show_bug.cgi?id=1914433#c25) on the Bugzilla for Fedora. What's more, there are also related [discussions](https://patchwork.kernel.org/project/linux-btrfs/patch/5d52220b-177d-72d4-7825-dbe6cbf8722f@inwind.it/) on the Btrfs mailing list.

﻿Even if direct IO does not cause errors, this setting would also [prevent](https://btrfs.readthedocs.io/en/latest/Compression.html#compatibility) the built-in compression functionality of Btrfs from working properly.

### Steps to reproduce

Run `sudo losetup --list` on a Btrfs based Qubes OS to see that DIO is listed as having a value of 1.

### Expected behavior

Direct IO should be disabled.

### Actual behavior

It's enabled on Btrfs based installation.

### Note

﻿The commit states that this behavior has been [reverted](https://github.com/QubesOS/qubes-vmm-xen/commit/62622997c89d5fc52bbe6895d563c80d9cc1c18e), but I assume it's still being used since the not-script.c introduced in R4.2, which [uses](https://github.com/QubesOS/qubes-linux-utils/blob/e6a80c786a2e520d9417d61c5331910d0785cf40/not-script/not-script.c#L74) `LO_FLAGS_DIRECT_IO`. ﻿(I'm unfamiliar with the code of Qubes OS, so this might be incorrect.)

And maybe it leads to some [regression](https://github.com/QubesOS/qubes-issues/issues/5426#issuecomment-1880579969_) on Btrfs, making qubes on Btrfs slow.﻿ ﻿I made this conjecture because the file "not-script.c" does not exist in R4.1. I'm not sure about this, because I can't simply disable the DIO for testing purposes; if someone could tell me how to do it, I'd be happy to try.

**Comment by marmarek** [comment]
@DemiMarie @rustybird ?

**Comment by rustybird** [comment]
My understanding is that Btrfs used to be more prone to checksum errors with direct I/O mainly because direct I/O exercises substantially different parts of the Btrfs codebase that had some bugs. Since then more attention has been paid to the combination, bugs have been fixed, and it's pretty calm nowadays.

OTOH, besides bugs in the Btrfs codebase itself, these checksum errors can also happen when a ["misbehaving (...) application modifies a buffer in-flight when doing an O_DIRECT write"](https://lore.kernel.org/linux-btrfs/c3cc0815c5756d07201c57063f3759250f662c77.1600961206.git.josef@toxicpanda.com/). In our case the application is xen-blkback on a loop device, so I don't know if that's relevant?

Personally I haven't experienced any such corruption. I've been running Btrfs with direct I/O enabled on my main Qubes OS notebook since R4.1, hacked into the old block script.

> And maybe it leads to some [regression](https://github.com/QubesOS/qubes-issues/issues/5426#issuecomment-1880579969) on Btrfs, making qubes on Btrfs slow

It's plausible that direct I/O leads to different allocation patterns, which could be worse or even pathological in some cases, maybe linked to specific SSD hardware or maybe not. But if that's a common problem to the point where it makes direct I/O a bad trade-off, shouldn't we have seen way more reports of such a regression with R4.2 from users who had R4.1 working fine with Btrfs?

> Even if direct IO does not cause errors, this setting would also [prevent](https://btrfs.readthedocs.io/en/latest/Compression.html#compatibility) the built-in compression functionality of Btrfs from working properly.

Huh, that's an important caveat (previously [stated](https://lore.kernel.org/linux-btrfs/89d0cad2-64b2-4699-b6de-6727398d50d6@gmx.com/)  on the linux-btrfs mailing list) I didn't have on my radar, because I never use compression.

Maybe the not-script should have a mechanism to disable direct I/O. That same mechanism could also be useful to override the 512 byte logical block size.

Or I guess for disabling direct I/O it could also automatically look at the file to see if it's hosted on Btrfs and has compression enabled?

**Comment by DemiMarie** [comment]
> > > ["misbehaving (...) application modifies a buffer in-flight when doing an O_DIRECT write"](https://lore.kernel.org/linux-btrfs/c3cc0815c5756d07201c57063f3759250f662c77.1600961206.git.josef@toxicpanda.com/). In our case the application is xen-blkback on a loop device
> 
> > it turned out that using the Xen PV Block driver in Windows qubes would cause a CSUM error, but Linux qubes and those not using the Xen PV Block driver wouldn't have such an issue.
> 
> Looks like the untrusted qube side can cause checksum errors on the trusted dom0 side. I was hoping that the dom0 backend prevents this.

Is this a security vulnerability from an upstream Xen PoV?

**Comment by ImBearChild** [comment]
> Try shutting down the qubes individually and/or take a look at the qubesd journal to see which .img files are causing long delays and could benefit from manual [defragmentation](https://forum.qubes-os.org/t/btrfs-and-luks-4096-slower-than-lvm-with-big-qubes/27838/2).

It seems that the `qubesd` shutdown process is relatively quick on my machine; from the first "Refilinked file" message to "qubesdb-daemon: terminating," it takes only 8 seconds. However, systemd complains about "Syncing filesystems and block devices" taking too long (30 seconds), which causes it to be killed. Manual defragmentation does not seem to affect this "syncing" issue, but it has helped shorten my qubesd shutdown time.

```
dom0 systemd-shutdown[1]: Syncing filesystems and block devices.
dom0 systemd-shutdown[1]: Syncing filesystems and block devices - timed out, issuing SIGKILL to PID 17446.
```

> Is this a security vulnerability from an upstream Xen PoV?

Maybe not that bad? As far as I know, a CSUM error will prevent further read access, making the qube unstable. (But not damage the filesystem.) However, after I turned off the Windows qube, `btrfs scrub` and `btrfs check` show no errors found.

> Can you easily reproduce the errors with a new Windows qube?

Yes. Here are steps to reproduce:

1. Prepare a new Windows qube
2. Install XEN PV Block driver from qubes tools installer and reboot
3. See Btrfs CSUM error in dmesg.

**Comment by apparatius** [comment]
I can reproduce this as well in Windows 10 qube with testsigning on:
```
bcdedit.exe /set testsigning on
```
And latest xenbus and xenvbd drivers installed from here:
https://xenbits.xenproject.org/pvdrivers/win/

**Comment by rustybird** [comment]
> > Looks like the untrusted qube side can cause checksum errors on the trusted dom0 side. I was hoping that the dom0 backend prevents this.

> Is this a security vulnerability from an upstream Xen PoV?

It would allow a malicious qube to DOS the backup procedure, as that will fail at the first read error and not back up the remaining qubes.

**Comment by rustybird** [comment]
IMHO we should indeed disable direct I/O in the not-script at the moment. @DemiMarie @marmarek

It's difficult to figure out who's technically wrong here in this stack of blkfront-on-WIndows, blkback, loop devices, and Btrfs. Not to mention various manpages/docs that could all be more explicit about interactions with direct I/O.

But in practice, it looks like direct I/O can interfere with system backups, nullify compression, and break Windows VMs.

And it can't be ruled out that technically misused (by whatever part of the stack) direct I/O could cause real data corruption beyond a relatively benign checksum mismatch, especially considering that file-reflink can be hosted by XFS/ZFS/bcachefs too  or even any filesystem, in degraded mode. There's also the still not quite dead legacy 'file' driver that's compatible with arbitrary filesystems.

**Comment by DemiMarie** [comment]
@rustybird I can have the not-script check the filesystem type (via `fstatfs(2)`) and enable direct I/O only on ext4 or XFS (where it is a free performance win).  There might be other filesystems (bcachefs?) where it is safe.  ZFS users should be using the ZFS storage driver, which doesn’t have this issue.

**Comment by rustybird** [comment]
Do we know that it is always safe for XFS and ext4 though? That Btrfs commit said it's simply application misbehavior to modify the buffer during a direct I/O write. (Which isn't explictly mentioned for O_DIRECT in [open(2)](https://www.man7.org/linux/man-pages/man2/open.2.html), but it makes sense. Come to think of it, blkback modifying the buffer during a write doesn't seem great even without direct I/O, right?) As non data checksumming filesystems, they have one less reason to look at the buffer twice. But maybe they do in some circumstances, e.g. depending on journalling options.

It's silly but I like to treat filesystems *as if* they're developed by ruthless "language lawyers" who will see the slightest incorrect use as an opportunity to deploy an optimization destroying the maximum allowable amount of data. So now I'm a bit spooked about direct I/O until it's been diagnosed what exactly is going on here.

**Comment by DemiMarie** [comment]
Modifying a buffer that is in-flight is a straightforward data race and undefined behavior.  No application should ever do this.  The only difference here is that when the junk data is read, BTRFS returns an error, while XFS/ext4 return garbage.

Theoretically, what BTRFS is doing is better.  However, most applications don’t handle I/O errors well, so the BTRFS behavior is a persistent denial of service.

**Comment by Atrate** [comment]
Will linux-utils v4.3.5 be available for Qubes 4.2 or do we have to wait for 4.3 to be released? I think I just experienced disk corruption (recoverable, fortunately) due to the usage of DIO, for the second time in my last 1 months' worth of Qubes usage.

**Comment by rustybird** [comment]
The change was cherry-picked for the [R4.2 branch](https://github.com/QubesOS/qubes-linux-utils/commits/release4.2/) three weeks ago, but the qubes-utils package version hasn't been bumped yet. @marmarek

> I think I just experienced disk corruption (recoverable, fortunately) due to the usage of DIO, for the second time in my last 1 months' worth of Qubes usage.

This happened with Windows VMs both times?

**Comment by Atrate** [comment]
> The change was cherry-picked for the [R4.2 branch](https://github.com/QubesOS/qubes-linux-utils/commits/release4.2/) three weeks ago, but the qubes-utils package version hasn't been bumped yet. @marmarek
> 
> > I think I just experienced disk corruption (recoverable, fortunately) due to the usage of DIO, for the second time in my last 1 months' worth of Qubes usage.
> 
> This happened with Windows VMs both times?

Linux AppVMs. _Technically_ I am not fully sure that this issue is *caused* by DIO (no meaningful logs), but the AppVMs are pretty standard and I have not made any significant modifications to Qubes other than installing it on BTRFS, so it could be due to that.

Also, maybe unrelated, but installing the Xen driver (through QWT) on Windows 10 causes *so many* r/w errors that the VM bluescreens in a couple of minutes. May be related.

**Comment by rustybird** [comment]
> > > I think I just experienced disk corruption [...]
> > 
> > This happened with Windows VMs both times?
> 
> Linux AppVMs.

You might want to keep an eye on this even after updating to qubes-utils-4.2.18, which disables direct I/O. Maybe Btrfs correctly alerted you to a hardware problem. (Just recently I experienced something similar: A faulty power supply had damaged my mainboard, and Btrfs was the first to complain via checksum errors.)

> installing the Xen driver (through QWT) on Windows 10 causes _so many_ r/w errors that the VM bluescreens in a couple of minutes.

That part seems like it could be direct I/O related.

**Comment by Atrate** [comment]
A week or two ago I've updated by setting dom0 repositories to testing, it seems to be fixed, compression works. I'll test out the Windows bugs once the new QWT are released. Any idea as to when I'll be able to set the updates back to stable or security-testing without risking a downgrade?

**Comment by ImBearChild** [comment]
Just to provide some new background information here. According to Btrfs related [pull-request](https://lore.kernel.org/lkml/cover.1742834133.git.dsterba@suse.com/) in 6.15:

> fall back to buffered write if direct io is done on a file that requires checksums
>   - this avoids a problem with checksum mismatch errors, observed e.g. on virtual images when writes to pages under writeback cause the checksum mismatch reports
>   - this may lead to some performance degradation but currently the recommended setup for VM images is to use the NOCOW file attribute that also disables checksums

So direct io on a file that requires checksums is not support by Btrfs. It will fallback to buffered io after 6.15.

**Comment by devZer0** [comment]
is disabling directio still needed , since this patch is now upstream ? https://lore.kernel.org/linux-btrfs/20260210233123.2905307-7-sashal@kernel.org/

**Comment by rustybird** [comment]
If we enabled direct I/O again, on Btrfs this would only make a difference if the image file is nodatasum (due to the [kernel 6.15+ change](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=968f19c5b1b7d5595423b0ac0020cc18dfed8cb5) @ImBearChild linked) and its data profile is single/raid0 (due to the [kernel 7.0+ change](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7c2830f00c3e086292c1ee9f27b61efaf8e76c9a) you @devZer0 linked). Otherwise, Btrfs itself would still disable DIO.

There's a [recent writeup](https://zazolabs.com/odirect-the-problem-that-grew-up/) claiming that for files hosted on XFS (and ext4) DIO can also cause much less frequent but more severe corruption via *meta*data checksums. I don't understand if that's really applicable to xen-blkback, but if it is then presumably it could affect Btrfs as well, which checksums metadata even for nodatasum files.
