### ISSUE TITLE
Qubes Manager/ Firewall: Rules for incoming/ outgoing traffic only

### ISSUE THREAD

**Issue by fowlslegs** [QubesOS/qubes-issues#962]
It would be nice to only allow outbound or inbound connections (esp. combined with my other Qubes Manager/ Firewall suggestion: port specific rules). Maybe borrow some code from GUFW?

**Comment by marmarek** [comment]
What do you mean by "inbound connections"? Those are blocked in Qubes and it is really not a simple task to allow such connections because of multiple layers of firewalls (netvm, firewallvm, the target VM itself). Details here: https://www.qubes-os.org/doc/QubesFirewall/#port-forwarding-to-an-appvm-from-the-outside-world

**Comment by fowlslegs** [comment]
This was one of my lesser thought out suggestions/ bug reports I filed late last night. Feel free to close it.
