### ISSUE TITLE
UI and UX: colorized app icons in taskbar instead of colorized locks

### ISSUE THREAD

**Issue by fowlslegs** [QubesOS/qubes-issues#967]
I'd like if the colorized "app" icons were visible in the taskbar as they are in krunner. Right now, every domU program in the taskbar panel has a colorized lock. This not only looks bad (UI), but changing it would also help users more quickly identify/ remember what is running by not necessarily having to read the text next to it (UX).

**Comment by marmarek** [comment]
This is actually non trivial feature, because dom0 have no idea what application is running in which window. This would require some additional data passed from VM to the dom0, which means slightly more complicated protocol -> bigger attack surface.
Also some applications do not expose icon name (which can be matched with colorized icon already present in dom0), but only icon bitmap (which need to be processed). Surely we don't want to do the later thing at each window creation.

**Comment by adrelanos** [comment]
This is the top usability issue I am struggling with every day.

**Comment by marmarek** [comment]
Yep, really useful feature, I also think the top one in UX category. But releasing **working** 3.0 (with the current feature set) and Whonix 11 have higher priority...

**Comment by marmarek** [comment]
Some preliminary implementation done. Commits linked above (branch `icon-updater`). Will merge it after final R3.0 release (aka R3.1 merge window).
This will needs some testing, especially for different VM types, minimal template (or Whonix based on it), DispVM etc.

**Comment by adrelanos** [comment]
What is the status of this? I am on R3.1 testing and still have colored locks rather then colorized app icons.

**Comment by marmarek** [comment]
Always? See #1495

**Comment by adrelanos** [comment]
"Almost always." I just now noticed, that I have 1 colored app icon at
this moment. Konsole. I haven't noticed that before, so there might have
been one or another colored icon without me noticing. All others (7 from
5 VMs) are colored locks.

**Comment by najamelan** [comment]
This used to work for me on Q4R3, but it seems like this regresses as I switch my vms to fedora-26 template.
