### ISSUE TITLE
X performance issue

### ISSUE THREAD

**Issue by Zrubi** [QubesOS/qubes-issues#976]
Hi,

After I upgraded my Qubes system to 3.0-rc1 I feel severe performance drop. The browsers requires much more CPU and the scrolling is lagish.

no difference if I use the new F-21 templates or the old F-20 based ones.

The only exact thing that if I view the output of top in dom0 and
scrolling in a browser in any AppVM the X.org will eat 100% CPU in dom0

seems to be kernel related:
only the 3.18 is affected - at least on my machine:

cpu:  |
  Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz

chipset:  |
  Intel Corporation 3rd Gen Core processor DRAM Controller [8086:0154] (rev 09)

gpu:  |
  Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09) (prog-if 00 [VGA controller])

**Comment by Zrubi** [comment]
Reinstalled to R2 and this problem is still here :(

now on kernel 3.12.40
note that only if I run several VMs at a time, but still not more than before.
(Xorg and plasma-desktop processes taking huge CPU% and because of this all the desktop is laggish)

Will try to downgrade the kernel - but I feel like the latest X patches may be related to this issue as well

**Comment by Zrubi** [comment]
Now I can confirm: kernel downgrade eliminates this problem. 
dom0 kernel 3.12.23 works fine while 3.12.40 is unusably slow. 

qubes: R2
xen: 4.1.6.1
kernel: 3.12.23-1

**Comment by marmarek** [comment]
Does it still happen in final R3.0?

**Comment by axon-qubes** [comment]
@Zrubi: Any update on this?

**Comment by Zrubi** [comment]
On 04/20/2016 12:51 PM, Axon wrote:
> @Zrubi <https://github.com/Zrubi>: Any update on this?

I had no time to test it on that particular laptop.
On my new one (T450) I have not seen such problems (running Qubes 3.1)

I still have that machine (with Qubes R2), and planning to reinstall  it
to 3.1 soon. But not sure how relevant will be the result...

I would say if this issue where only hit by this single model, we can
close it now.

-- 
Zrubi

**Comment by axon-qubes** [comment]
Ok, closing for now. Feel free to re-open it later if needed.

**Comment by rveldhoven** [comment]
Hey, 
I'm hoping I'm not breaking any rules by bumping this, but I seem to have the same issue.

After a clean install from the installation media for 3.2 qubes is perfectly usable with kernel 4.4.14-11. However after updating dom0 via the Qubes VM Manager qubes became unbearably sluggish on kernel version 4.4.67-12.

On kernel 4.4.14-11 xorg uses maybe 1.3% to 5% CPU.
On the 4.4.46-12 xorg averaged around 67 to 70% CPU and rendering was terribly sluggish and the system was pretty much unusable.

**Comment by marmarek** [comment]
@rtiangha any idea?
@rveldhoven this one, while similar, is about much older versions. Better open new issue and reference this one from there.

**Comment by rtiangha** [comment]
I can't test until this weekend, but the only thing I can think of at the moment is to revert CONFIG_SLUB_DEBUG_ON and see if that has any affect on performance issues and some of the other issues that have been raised lately. But that's just a shot in the dark. A hardware list from @rveldhoven would be useful, though; it might not even be the same system as the OP.

**Comment by v6ak** [comment]
I had a similar issue (not sure about the CPU load, though, but it might have been the case), so I'd ask about potential similarities:

* What's your hardware (GPU/CPU)? I had this issue with a new laptop with Intel i7-7500U, while the old laptop worked OK.
* Is GPU acceleration used? With the new laptop, I have no GPU acceleration on Qubes with any kernel I have tried. You can verify it via glxinfo | grep renderer.
* Is a specific GPU kernel module used? If you have an Intel GPU, try sudo rmmod i915. If you are using the module, it should fail to remove the module with an appropriate error message. If it proceeds, the output is handled by some other (probably generic) module. My experience: Kernel 4.4 does not use it with new laptop, kernel 4.8 and 4.9 does.
* Does installing kernel from qubes-dom0-current-testing resolve the issue? For me, it did so. (And it also has fixed some other issues, including inability to regulate brightness.) It works fluently, with the exception of some non-default Kwin task switching style (which I don't need).

My hypothesis: The GPU is too new, so kernel 4.4 does not have appropriate drivers, so it uses some generic GPU drivers. Also, the newer version of 4.4 kernel has some bug in the generic driver, which causes rendering to be about 1 FPS. (This is also the reason why I didn't have this issue with my older laptop: it is old enough to have appropriate drivers in 4.4 kernel.) Since the newer kernel has drivers for GPU, it doesn't have to use the generic ones, so it works well.

I wonder if your issue is the same.
