### ISSUE TITLE
[3.0-RC1 installer] Bad error reporting about partition layout

### ISSUE THREAD

**Issue by v6ak** [QubesOS/qubes-issues#980]
Steps to reproduce:
1. Run installer
2. Select manual partitioning
3. Select traditional partitions, not LVM
4. Choose one partition for "/" as **encrypted** ext4
5. Don't create any other partitions

Expected results: Get a failure message, because /boot must be on something unencrypted.

Actual results: Got some very vague error message. The expected error message is in console.

**Comment by esote** [comment]
@v6ak Does this still happen on R3.2.1 or R4?

**Comment by v6ak** [comment]
I am not sure. AFAIK, on 4.0, it should not be even possible to make such selection.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
