### ISSUE TITLE
Wrong screen resolution (64x64) set for AppVM X server when xrandr unavailable on Dom0 side

### ISSUE THREAD

**Issue by plushambush** [QubesOS/qubes-issues#998]
When Dom0 start AppVM it set AppVM's X server resolution by asking xrandr for the current screen resolution and passing result to the SetMonitorLayout RPC service on the AppVM side.
But qubes-monitor-layout-notify script which is responsible for this job don't check result returned by xrandr for correct data. As result It send an empty string to the SetMonitorLayout, this empty string is received by xrandr on AppVM side and screen resolution set to minimum (which is 64x64)

Consider using other means of getting screen resolution (xwininfo?) when xrandr is unavailable

Tested on Qubes 3 RC1
Screen setup: 3 heads, 2 video cards (1 on Intel + 2 on Nvidia), Xinerama is on

**Comment by marmarek** [comment]
Can you paste here output of `xrandr` in dom0 in such case?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by plushambush** [comment]
Seem that it's not needed anymore, but as you asked
<pre>
[ricochet@dom0 Desktop]$ xrandr -q
RandR extension missing
</pre>

**Comment by plushambush** [comment]
But this this patch marmarek/qubes-gui-daemon@7bb67acdc3576583f86cd0b6dcae063c6f2bab63 will just make watch-screen-layout-changes ignore all further layout changes and it become completely useless. Isn't it?

**Comment by marmarek** [comment]
Yes, if xrandr does not report screen dimensions it is pointless
forwarding xrandr events to the VM. I think in such a case,
`qubes-monitor-layout-notify` will not be called at all in the first
place.
If you want some other screen size notification method, feel free to
provide a more details, or - preferably - a patch.

Without this mechanism, VM still know the full screen size - it is sent
by gui-daemon at the VM startup.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
